### ISSUE TITLE
Permit `let` and `assert` to be the last expression in a block

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1004]

**Comment by CrowdHailer** [comment]
I see why it's useful for assert it tests. but am curious why it also needs to be the case for let. Can I ask a bit about what the rational is for the change?

**Comment by lpil** [comment]
For me it is a workflow improvement. currently it is quite common for me to be halfway through typing a function and hit save so I can type check it, but then it fails because the last thing I wrote was a let binding. If I keep doing this I think other people will as well so I want to make this user experience a little bit more smoove.

I'll probably have let in the last position omit a warning.

**Comment by CrowdHailer** [comment]
I do come across this quite often, but letting let be the last line in a function will only work if that particular let line has the same type as the return type of the function needs to have. Which certainly there are cases it could do, but if the intention is to right more function after that let binding it's fairly arbitrary whether that particular let is or isn't the correct type.

What would the return type of an `assert` line be? In tests I often write a Nil to compile.
```
assert Ok(_) = final_thing
Nil
```

**Comment by lpil** [comment]
Probably the type of the right hand side, that's what Erlang does.

**Comment by inoas** [comment]
> I'll probably have let in the last position omit a warning.

Good stuff.
