### ISSUE TITLE
🐛 Compiler generates invalid Erlang when compiling a `Div` type variant.

### ISSUE THREAD

**Issue by pd-andy** [gleam-lang/gleam#1006]
Consider the custom type for a simple calculator expression:
```
type Op {
  Add(Int, Int)
  Sub(Int, Int)
  Mul(Int, Int)
  Div(Int, Int)
}
```
The generated erlang will compile the `Div` constructor to `div`, which clashes with erlang's integer division operator (also called `div`).

**Comment by lpil** [comment]
Thank you
