### ISSUE TITLE
Document named accessor syntax in Custom types documentation

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#1031]
https://gleam.run/book/tour/custom-types.html

The only place that the accessor syntax is mention is in respect to tuples with integer keys. worth documenting it can be done with names on records with named keys.

**Comment by hasanhaja** [comment]
Hi, I'm new to the code base and I don't have any experience contributing to open source but I want to start and offer my help. Would you be able to give me some pointers on how I can get familiar with the code base, project and documentation to tackle this issue?

**Comment by lpil** [comment]
Hi @hasanhaja ! Thanks for your help.

For this issue we want to update the documentation on custom types to explain that if one is defined with only one variant then the `.field_name` accessor syntax can be used to get the values of those fields.

```rust
pub type Person {
  Person(name: String)
}

pub fn main() {
  let jane = Person(name: "Jane")
  jane.name // This returns "Jane"
}
```

The documentation would go in this page: https://github.com/gleam-lang/website/blob/main/book-src/tour/custom-types.md
