### ISSUE TITLE
Warn or error on reserved word as filename

### ISSUE THREAD

**Issue by varnerac** [gleam-lang/gleam#1032]
Gleam will compile a file named `external.gleam`. This module cannot be imported anywhere because `external` is a reserved word. The compiler should catch reserved words as module names during compilation.

**Comment by lpil** [comment]
Thank you for the report.

I think we would want to raise an error in this situation.

**Comment by lpil** [comment]
Related to https://github.com/gleam-lang/gleam/issues/1024

**Comment by michaeljones** [comment]
Could this be added here? 

https://github.com/gleam-lang/gleam/blob/97e63a6e467407f4de7e80f20fd5cdda19e726c7/src/project.rs#L192-L232

Or do you think another place would be better?

**Comment by lpil** [comment]
That code is soft-deprecated in favour of the package and project compilers, so if added here it would also need to be in the package compiler too.

Another place it could be is in the `fs` module code that finds the module files.
