### ISSUE TITLE
Basic JS code generation

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1034]
- [x] Expressions
  - [x] Ints (with bitwise operator hints to make then ints rather than floats)
  - [x] Floats
  - [x] Strings
  - [x] Function calls
- [x] Constants
  - [x] Ints
  - [x] Floats
  - [x] Strings
- [x] Module level functions

**Comment by lpil** [comment]
One for @CrowdHailer I think!

**Comment by CrowdHailer** [comment]
@lpil what's the reason for this separation? constants seem very simple compared too (and unrelated too) module function calls.

**Comment by lpil** [comment]
@CrowdHailer Best effort guesses from me! You know more than I do at the moment so if you think there are PRs that split the work into chunks that make more sense for you please do that and we can squidge the issues to match.

**Comment by CrowdHailer** [comment]
#1053 covers string expressions

**Comment by lpil** [comment]
I've added expression sequences

**Comment by CrowdHailer** [comment]
I think you've change the logic a bit. By wrapping everything in immediately invoking functions so that a seqence can always end with a `return expression`. I was avoiding immediatly invoking functions so that you could use return for the try syntax. Not too much of a problem I assume but will need to think a bit differently.

**Comment by lpil** [comment]
`try` is expression based rather than function based, so I don't believe it's possible to use `return` with it unless you wrap it in an iife. If this code where to return at the `try` it would have the wrong result (Error(_) rather than 1).

```rust
let x = {
  try y = z
  y
}
1
```

**Comment by tclain** [comment]
would be happy to help in js codegen as I write js/ts for a living.

Any pointers to help me navigate the codebase and insert this codegen relative code ?

**Comment by lpil** [comment]
Hey @tclain ! It would be great to have you help out, thank you.

Would you be interested in any particular feature compilations? Maybe lists?

**Comment by CrowdHailer** [comment]
@lpil I've added constants for ints + floats to #1055. As they are literals there are no `| 0` hints required.
That PR should then mean all the constants terms in this issue and expressions except for function calls are complete.

**Comment by lpil** [comment]
> As they are literals there are no | 0 hints required.

Int literals are floats unless the hint is added, V8 etc won't apply the optimisation. I'll add it quickly.

> That PR should then mean all the constants terms in this issue and expressions except for function calls are complete.

🎉

**Comment by CrowdHailer** [comment]
Is this one done now?

**Comment by lpil** [comment]
Yes! Thank you
