### ISSUE TITLE
JS: Variables and assignments with `let` 

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1035]
Follows on from https://github.com/gleam-lang/gleam/issues/1034

```rust
let x = 1
x
```

**Comment by lpil** [comment]
Looks like Rescript uses variable rewriting.

```rescript
let y = f => {
  let x = f(1)
  let x = x + 1
  let y = f(x)
  x + y
}
```
```js
function y(f) {
  var x = Curry._1(f, 1);
  var x$1 = x + 1 | 0;
  var y$1 = Curry._1(f, x$1);
  return x$1 + y$1 | 0;
}
```
https://rescript-lang.org/try?code=DYUwLgBAnhC8EDM4D4IG8BQEKkgDzkQAoBGASix3AgPgIGoITLdpCEi8LsHoMBfDEA

I guess this is nicer as it doesn't wastefully allocate and call extra functions. It does make the generator more complex and the resulting code not quite as nice though.

**Comment by CrowdHailer** [comment]
Do we know why it uses variable rewriting? as var can be used multplie times with the same name I cannot see why it's necessary.

**Comment by lpil** [comment]
To avoid IIFEs for scopes I suspect.

**Comment by CrowdHailer** [comment]
> To avoid IIFEs for scopes I suspect.

Is that important? On my last PR I used them for case statements. IIFE's are already used for blocks, using them for case as well allows us to get away with using var. If we don't wrap the case statements we have to use let/const. or not reuse variable names.

Do we know which way we want to go on generating variable names. I would prefer to not use `x$1` x$2` if possible. But it's probably not the worse if we reuse the variable tracking code that the erlang backend already has.

**Comment by lpil** [comment]
I'll do some benchmarking and find out what the performance characteristics
of each option are. We'll use whichever is faster as this will impact all
Gleam code. Get it right here and all future code will benefit.

What could we do in place of x$3 etc? Avoiding name collisions with more
complex schemes was challenging in Erlang so I gave up in the end.

**Comment by CrowdHailer** [comment]
Ok I'll hold off and see what the benchmarks say. I was leaning towards readability as a first priority, and following Joes advice of make it work, before anything else. I'm not sure what the costs of changing the generated JS between gleam versions is, as long as the behaviour is the same I don't see much problem, but maybe I'm missing something.

> What could we do in place of x$3 etc?
If we're not just using the variables given, and need to make sure there unique, the appending `$i` is the scheme I would use.

**Comment by lpil** [comment]
From my benchmarking I've found renaming to be ~2% faster with lower standard deviation for 2 layers of case expression.

I also possibly subjective, but I found the renaming to look like regular JS a little more, though there's not much in it.

```js
  var x = (() => {
      if (false) {
        var x = 1;
        return x;
      } else {
        return (() => {
          if (false) {
            var x = 2;
            return x;
          } else {
            var x = 3;
            return 3;
          }
        })();
      }
    })();
```
```js
    var x;
    if (false) {
      var x$1 = 1;
      x = x$1;
    } else {
      if (true) {
        var x$2 = 1;
        x = x$2;
      } else {
        var x$3 = 2;
        x = x$3;
      }
    }
```

The $ is a little noisy. I would be open to another naming strategy if we can devise a safe one, though I've found this tricky so far

**Comment by CrowdHailer** [comment]
I like $3 for the explicitness of what it's doing right now. and probably simpler to implement.
