### ISSUE TITLE
JS: Tail call optimisation

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1039]
Support for only self-recursion is good enough for this ticket.

Mutual recursion can come later if ever.

```rust
pub fn go(x) {
  0 -> 2
  x -> go(x - 1)
}
```
```javascript
function go(x) {
  while (true) {
    if (x == 0) {
      return 2;
    } else {
      x = x - 1;
    }
  }
}
```

Compilation would be tracking whether a recursive tail call was made, rendering the assignment instead of the call when one is found, and wrapping in while if there are any. We can use the existing tail position checking code and the name of the current function to identify tail calls.

**Comment by michallepicki** [comment]
Some work on this seems to have been done in https://github.com/gleam-lang/gleam/commit/b42814e39ada5fab0783fe5760fa9f69a6bf721b and possibly other commits. What is left?

**Comment by lpil** [comment]
Nothing I think! Thanks
