### ISSUE TITLE
JS: Zero arity custom types

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1043]
- [x] Expressions
  - [x] local
  - [x] imported
  - [x] imported and unqualified
- [x] Patterns
  - [x] local
  - [x] imported
  - [x] imported and unqualified
- [x] Constants
  - [x] local
  - [x] imported
  - [x] imported and unqualified

```rust
pub fn main() {
  North
  East
  South
  West
}

pub type Cardinal {
  North
  East
  South
  West
}
```

Should it reference consts like so?
```js
export const North = "north";

export const East = "east";

export const South = "south";

export const West = "west";

export function main() {
  North;
  East;
  South;
  return West;
}
```

It could be nice for indicating intent in the generated code if you can see where the tags come from. It would be slightly more complex generating the right imports and qualified usages etc.

Related to https://github.com/gleam-lang/gleam/issues/1040

**Comment by CrowdHailer** [comment]
> Should it reference consts like so?

I can't see a strong argument for this. If I was to see zero arity custom types referencing consts I would expect (maybe irrationally) for custom types with fields to reference a constructor function. 

Tbh, I would also be quite happy to see zero arity custom types rendered as follows.
```js
{type: "North"}
```
I suspect @lpil might not agree with me there but I actually quite like the consitency with types with fields. i.e. 
```js
{type: "Point", x: 1, y: 2}
```

**Comment by lpil** [comment]
That's nice! Let's do that.
