### ISSUE TITLE
JS: Operators

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1045]
For expressions and clause guards

- [x] Greater than `>`
- [x] Greater than `>.`
- [x] Greater or equal `>=`
- [x] Greater or equal `>=.`
- [x] Less than `<`
- [x] Less than `<.`
- [x] Less or equal `>=`
- [x] Less or equal `>=.`
- [ ] Boolean and `&&`
- [ ] Boolean or `||`
- [x] Add `+`
- [x] Add `+.`
- [x] Subtract `-`
- [x] Subtract `-.`
- [x] Multiply `*`
- [x] Multiply `*.`
- [x] Divide `/`
- [x] Divide `/.`
- [x] Modulo `%`

**Comment by CrowdHailer** [comment]
All numerical comparisons are tackled in #1055

**Comment by CrowdHailer** [comment]
This Issue should be closed as the boolean operators where added in #1060 

https://github.com/gleam-lang/gleam/pull/1060/files#diff-9e23c200211e3fa575acdbf7ecade7ce9a76c2bd2b5d6e2c227961f81c4b7248R44
