### ISSUE TITLE
JS Imports and calling of functions from other modules

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1046]

**Comment by CrowdHailer** [comment]
@lpil would you like a single PR that tackles this and also making records using constants from the imported module. 
Or would you like them as separate PR's?

**Comment by CrowdHailer** [comment]
Ok, I've decided to tackle constants in #1070 but not records as we haven't yet done records.

I think we should consider #1070 as sufficient for this issue, and maybe add to the checklist in #1043/#1044 an item for using imported records.

**Comment by lpil** [comment]
Good idea, I've updated the checklists.

Happy to go with whatever PR strategy that works for you
