### ISSUE TITLE
Conditional compilation for different platforms

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1051]
We will need to be able to compile code differently on different platforms based on their capabilities. An example here is that the stdlib will need a different implementation for gleam/map.Map and gleam/io.println on JS compared to Erlang.

What should the design be for conditional compilation?

It would be nice to be able to specify different external functions for different platforms, and it would be good if we could use a Gleam implementation alternatively too. e.g. On Erlang we use Erlang maps, on JS we have a custom implementation of an immutable map in Gleam

**Comment by CrowdHailer** [comment]
What about something like the following for a function where there is an off by one difference between the erlang and JS implementations.
```
target erlang {
  external fn erl_foo = "beam" "foo"

  pub fn foo() {
    erl_foo() + 1
  }
}

target javascript {
  pub external foo = "dom" "foo"
}
```

**Comment by lpil** [comment]
That could work, I quite like how that looks. The indentation makes it clearer that something special is happening here.

Another option could be annotations similar to Rust.

```
#if(target == "erlang")
external fn erl_foo = "beam" "foo"

#if(target == "erlang")
pub fn foo() {
  erl_foo() + 1
}

#if(target == "javascript")
pub external foo = "dom" "foo"
```

And there's also string-preprocessor conditional compilation as found in C, C++.

I wonder what other languages have conditional compilation.

**Comment by varnerac** [comment]
I was thinking of something similar. Originally I thought this could be handled as a parameter on the FFI declaration for the target language (Erlang, JavaScript, etc.). Additionally, there could be a pure Gleam function with the same name as the FFI. If not FFI declaration matches, then the pure Gleam version is called.

```
external erlang pub fn reverse= "list" "reverse"

// Called for JS or future targets
pub fn reverse(list) {
 …
}
```

but, this doesn’t handle the case where you want custom Gleam per target language. It only provides custom foreign functions.
