### ISSUE TITLE
Core language tests for JavaScript backend

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1067]
Currently we have tests for Erlang execution in the `test/core_language` directory. It would be good to have similar for JavaScript generation.

Rename the existing directory to `test/erlang_test` and make another for JavaScript. No need for a test framework from npm, just calling functions and a few `assert`s will do to start.

**Comment by CrowdHailer** [comment]
These tests have been added but don't yet pass as they rely on features like lists and matching on booleans to complete.

**Comment by michallepicki** [comment]
Some tests are now running since https://github.com/gleam-lang/gleam/commit/11faa40e02040455fe2364268f94ec82b145a1ea

**Comment by lpil** [comment]
Thank you!
