### ISSUE TITLE
Display module qualifiers when type errors would be otherwise unclear

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#107]
`Map` and `Map` print the same, thought they may be `app.Map` and `lib.Map`. This can result in confusing errors.

It would be nice if we show as few qualifiers as possible for conciseness. Some design work is to be done here.

**Comment by zjhmale** [comment]
I don't think we can have two `Map`s in a single module, this is forbidden in other languages IIRC 🤔

**Comment by lpil** [comment]
Here's an example

```rust
// one.gleam
pub type Thing {
  Thing
}
```

```rust
// two.gleam

import two

pub type Thing {
  Thing
}

pub fn main() {
  Map == one.Map // Type error
}
```

It should be made clear that the two different types named Map are not from the same module.

**Comment by zjhmale** [comment]
Gocha, let me make it clear, pls don't blame if I got wrong 😅  

```rust
// one.gleam
pub type Thing {
  Thing
}
```

```rust
// two.gleam

import one

pub type Thing {
  Thing
};

pub fn main() {
  Thing == one.Thing // Type error
}
```

at present, gleam will display

```
error: Type mismatch

    ┌── /Users/jihuizheng/Documents/gleam-ttt/ttt/src/ttt.gleam:29:12 ───
    │
 29 │   Thing == one.Thing // Type error
    │            ^^^^^^^^^
    │

Expected type:

    Thing

Found type:

    Thing
```

and the ideal output will be

```
error: Type mismatch

    ┌── /Users/jihuizheng/Documents/gleam-ttt/ttt/src/ttt.gleam:29:12 ───
    │
 29 │   Thing == one.Thing // Type error
    │            ^^^^^^^^^
    │

Expected type:

    two.Thing

Found type:

    one.Thing
```

correct?

**Comment by lpil** [comment]
Yes, something like that.

My original idea was to show a qualifier when the type originates from another module but I'm now more sure that is the right approach as it would introduce a lot of noise. It would be good to only show the qualifier if it is the part of the type that is the cause of the error.

**Comment by Kn99HN** [comment]
> To do this we would want to iterate over the document before printing and record which names are used multiple times.

I want to tackle this issue. But I'm unsure about the approach suggested here. I have an idea of where the error is happening. 

Are you suggesting to iterate over the documents before type checker runs? Would you mind elaborating? Thank you!

**Comment by lpil** [comment]
Hello! Thank you for helping

My thought was that we could before printing the types in a particular error we can traverse them all and keep track of any names that we see multiple times. Then we can use that information when printing the type to add a qualifier if this is one of those names that we have seen more than once.

Does that make sense? I can point out some areas of the code base where I think this could fit when I am at my computer later, if that helps.

**Comment by Kn99HN** [comment]
That does make more sense! I can look more into it and will come back if I have question. Thank you!
