### ISSUE TITLE
JS: Lists

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#1075]
- [ ] patterns
  - [x] fixed length
  - [x] spread tail
- [x] expressions
  - [x] fixed length
  - [x] spread tail
  - [x] multi-line expresions as elements `[{1; 2}]`
- [x] constants
  - ~~[ ] multi-line expresions as elements `[{1; 2}]`~~

**Comment by lpil** [comment]
Lists in Gleam are immutable data structure and make use of structural sharing to negate the time and memory costs of conventional immutability.

# Code generation

- Gleam -> JavaScript
- `[]` -> `[]`
- `[1]` -> `[1, []]`
- `[1, 2]` -> `[1, [2, []]]`

**Comment by CrowdHailer** [comment]
Are multi line expressions even possible in constants, wouldn't that require sequences or some such?

**Comment by lpil** [comment]
They're not possible currently

**Comment by CrowdHailer** [comment]
Will take them off the checklist then. Also I marked expression spread as done. I think it's done, the test is here. https://github.com/gleam-lang/gleam/blob/main/src/javascript/tests/lists.rs#L12

**Comment by lpil** [comment]
Ah, nice one! Thank you
