### ISSUE TITLE
command new should check if <folder> already exist

### ISSUE THREAD

**Issue by chespinoza** [gleam-lang/gleam#1076]
I'm just starting trying Gleam, I think it should solve the things I didn't like about Elixir (i.e. the lack of static typing) and I'm really excited to try it out, thanks for the efforts.

While I was playing with the command line tool I realised that the `new` command doesn't check if the folder where the app/lib is going to be created already exist, so if it already exist it just create the files into the existing folder, probably the safest behaviour should be aborting and returning a message indicating the issue, this is not a big problem but it helps to bring a better and safer experience with tooling. 

Cheers.

**Comment by lpil** [comment]
Good idea, thank you
