### ISSUE TITLE
Change external functions to always be inlined

### ISSUE THREAD

**Issue by enerdgumen** [gleam-lang/gleam#1083]
Gleam currently makes external function calls inline, but the behaviour is a bit inconsistent and can be improved.

Let's assume this module, exposing a single external function:
```
// extern.gleam
pub external fn example() -> Nil = "native" "example"
```

### First case: named import

```
// client.gleam
import extern.{example}

pub fn example_call() {
  example()
}
```

It emits the following Erlang code, where the call is inline:
```
// client.erl
-spec example_call() -> nil.
example_call() ->
    native:example().

// extern.erl (useless)
-spec example() -> nil.
example() ->
    native:example().
```

Technically the "extern" module is redundant at Erlang side and may not be generated.

### Second case: simple import

```
// client.gleam
import extern

pub fn example_call() {
  extern.example()
}
```

This time the call is not inlined and Gleam emits the following code:
```
-spec example_call() -> nil.
example_call() ->
    extern:example().
```

### Conclusion

It might be better to handle external funtions that always emit inline calls and never generate Erlang wrappers.
Consequently, if a module exposes only a set of external functions and types, it should not be generated at all.

**Comment by lpil** [comment]
Gleam plays nicely with other languages in the ecosystem so all public functions are exported so they can be used from Erlang, Elixir, and so on, as well as for calling in the REPL for debugging and development.

We could make qualified imports call the external function directly but I'm the performance cost is so small I'm not sure it's advantegeous over the extra clarity of seeing the function name in the generated code. Either option seems about the same to me.

**Comment by enerdgumen** [comment]
I reported this mainly for consistency reasons, even though it's a trivial issue. I think the way a function is imported should not affect the transpiled code. If Gleam want to inline external functions, it should always (or never) do it, not only when that function is imported using the `import module.{function}` syntax.

Regarding the generation of the resulting modules, if gleam calls all the external functions inline, not generating the Erlang modules becomes an option. I think the benefit is just less overhead on Erlang side (less generated code -> less code to read and maintain in case of escape from Gleam). Ideally I would like to see the same Erlang code I would have written by hand.

**Comment by lpil** [comment]
Generating code that you would have written is not an achievable goal because everyone has a slightly different style and approach to writing code.￼

We are going to be revisiting our approach to external functions in the near future because of the JavaScript work, so any change we make now may be wasted effort.￼ let's revisit this issue after that has been done. Thank you￼
