### ISSUE TITLE
Provide a hint when using a generic function without a return type annotation *before* it is defined.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#1096]
Given the following snippet, we will get a compile error on **line 9**.
```rust
1 | import gleam/map.{Map}
2 | 
3 | pub fn insert (map: Map(a, b), key: a, value: b) -> Map(a, b) {
4 |    delete(map, key)
5 |        |> map.insert(key, value)
6 | }
7 |
8 | /// Note the missing return type annotation
9 | pub fn delete (map: Map(x, y), key: x) {
10|    map.delete(map, key)
11| }
```
This is because the compiler cannot unify the inferred type of `delete(map, key)` with the more general inferred type of delete's definition. 

This is the compiler being well-behaved and operating correctly, but might present a bit of a shock to those coming from Haskell/Elm/Purescript/... where order of definition isn't significant to the compiler. I stumbled across this when I _unintentionally_ left a return type annotation off a function and might've spent a long time working out what was up had I not noticed relatively shortly.

Adding a hint to the compile error in scenarios like these might be enough of a nudge to say "Hey, maybe you forgot some type annotations?" Something like:
```
error: Type mismatch
   ┌─ /.../minimal_map_example.gleam:10:5
   │
10 │     map.delete(map, key)
   │     ^^^^^^^^^^^^^^^^^^^^

The type of this returned value doesn't match the return type 
annotation of this function.

Expected type:

    Map(a, b)

Found type:

    Map(c, d)

Hint: It looks like you used this function before I reached it's
definition. That's OK, but sometimes I need extra information
in those cases, did you leave out type annotations? See if
adding them resolves this issue.
```

**Comment by lpil** [comment]
Thanks! I'm not sure what is possible here but it would be good to make this clearer

**Comment by shunjilin** [comment]
I have a question regarding this, In the example given above, shouldn't the ideal situation be that the compiler is able to infer the output of `map.delete` to be that of the input map? At least from the definition of `map.delete`:
```
pub fn delete(from map: Map(k, v), delete key: k) -> Map(k, v)
```
Or is there some other limitation preventing gleam from implementing the above?

**Comment by lpil** [comment]
It is possible, but it would be a larger item of work that I'm not going to be taking on until after the tooling is ready. If someone else would like to take this on that would be cool.

**Comment by lpil** [comment]
This will be solved by https://github.com/gleam-lang/gleam/issues/1814
