### ISSUE TITLE
Typed records in Erlang header files

### ISSUE THREAD

**Issue by varnerac** [gleam-lang/gleam#1103]
Gleam currently generates `.hrl` files with record definitions. It'd be nice if we added type information to those generated record definitions.

For example

```erl
-record(person, {name :: binary()}).
```

vs.

```erl
-record(person, {name}).
```

**Comment by lpil** [comment]
A great idea! Let's do this

**Comment by jcc333** [comment]
I would love to take a crack at this; am I correct in thinking it'd mostly live over in `records`/`record_definition` within src/erl.rs?

**Comment by lpil** [comment]
That would be great, thank you @jcc333 . Yes I think that's right
