### ISSUE TITLE
Syntax error when naming a type an erlang keyword

### ISSUE THREAD

**Issue by shunjilin** [gleam-lang/gleam#1108]
Ran into a different error while checking #1106

Naming a type constructor a reserved keyword leads to invalid erlang code generated:

e.g. gleam code:
```
pub type End {
  Test(String)
}
```

generates:
```erl
-module(module_name).
-compile(no_auto_import).

-export_type([end/0]).

-type end() :: {test, binary()}.
```

error `syntax error before: 'end'` on lines 4,6

~Not sure if there is a straightforward solution for this as functions cannot be quoted unlike atoms~

Edit: my mistake, it seems like the type declaration can be quoted, see #1114

**Comment by lpil** [comment]
Thanks for the report! Merging this one with https://github.com/gleam-lang/gleam/issues/1106

**Comment by lpil** [comment]
Oh sorry! I see this is not 100% the same.
