### ISSUE TITLE
Formatter: Support elm-format style line-break opt-in

### ISSUE THREAD

**Issue by MattCheely** [gleam-lang/gleam#1117]
The gleam formatter is great, and I appreciate the no-configuration approach. Bikeshedding formatting rules is one of my least favorite things to do!

There is one feature from elm-format that I'd love to see added though, which is that if the developer has manually inserted a line break into a data structure or function call, then the formatter will switch to a multi-line format for that data/function.

Some examples:
```rust
// Input
send_msg_resp(conn,    500,    "error")

// Output
send_msg_resp(conn, 500, "error")
```
```rust
// Input
send_msg_resp(conn,
                500, "error")

// Output
send_msg_resp(
  conn,
  500,
  "error",
)
```
```rust
// Input
let err_msg = ["Job timed out after ",     int.to_string(job_timeout),    "ms"]

// Output
let err_msg = ["Job timed out after ", int.to_string(job_timeout), "ms"]
```
```rust
// Input
let err_msg = ["Job timed out after ", int.to_string(job_timeout),
                 "ms"]

// Output
let err_msg = [
  "Job timed out after ",
  int.to_string(job_timeout),
  "ms",
]
```

**Comment by lpil** [comment]
I like this suggestion a lot! Let's do this one.￼
