### ISSUE TITLE
Permit custom type constructors to be aliased when imported

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1126]
```rust
import some/module.{Name as TheAlias}
```

We must ensure that the name is uppercase and that functions and consts are always lowercase when imported, so we'll need to validate this too.

**Comment by matheus-consoli** [comment]
hi, @lpil! I'll likely take a shot on this

**Comment by lpil** [comment]
Fantastic, thank you! Let me know if you want any pointers

**Comment by matheus-consoli** [comment]
Hi, @lpil, I believe I finally managed to come up with a solution to this problem (and it was easier than I initially thot :D), my manual tests passed. But I'm struggling with the tests :( could you guide me on how to properly create a gleam module in a test case? 
I'm looking through the `type_/tests.rs` to get some references, but I'm not sure if it's the easier approach
