### ISSUE TITLE
Error when using `compile-package` on a new project

### ISSUE THREAD

**Issue by JohnDoneth** [gleam-lang/gleam#1146]
## Versions
Gleam 0.16.0-rc1
## Error
```
error: Fatal compiler bug!

This is a bug in the Gleam compiler, sorry!

Please report this crash to https://github.com/gleam-lang/gleam/issues/new
with this information and the code that produces the crash:

Typer could not find a module being imported. 
Missing modules should be detected prior to type checking
```

## Steps to Reproduce

Generate a new project:
```
gleam new gleam_test
cd gleam_test
````

Run the following command:
```
gleam compile-package --src . --name gleam_test --out _build --target javascript
```
My naive assumption is this probably isn't how `compile-package` is supposed to be invoked as I was just attempting to get it working.

**Comment by JohnDoneth** [comment]
It appears that I just needed to change the source directory argument to `src` instead of the current directory.

**Comment by lpil** [comment]
Thank you for the report! This definitely shouldn't happen. I'll try and work out what is going on here shortly.￼￼

**Comment by lpil** [comment]
Thank you
