### ISSUE TITLE
Error when importing prelude module

### ISSUE THREAD

**Issue by krendil** [gleam-lang/gleam#1150]
When attempting to import the prelude module in a gleam file, I receive the following error:

```
error: Unknown import
  ┌─ /mnt/data/Src/gleam/prelude_test/src/prelude_test.gleam:4:8
  │
4 │ import gleam
  │        ^^^^^ did you mean `gleam/os`?

The module `prelude_test` is trying to import the module `gleam`,
but it cannot be found.
```

I've encountered this with gleam v0.15.1 and v0.16.0-rc1.

The issue seems to occur in the compiler when calculating dependencies for the SourceTree. It sees the `gleam` import and tries to look it up in the dependency index, but the index only holds actual files that need to be compiled, not the prelude module.

Attached is a minimal test project that reproduces the issue: [prelude_test.zip](https://github.com/gleam-lang/gleam/files/6614522/prelude_test.zip)

**Comment by michallepicki** [comment]
Possibly closed by https://github.com/gleam-lang/gleam/commit/7aea1fcd2ca8db607659843a597330ee4e3495c5
