### ISSUE TITLE
Implement the pipe operator using assignments

### ISSUE THREAD

**Issue by michallepicki** [gleam-lang/gleam#1153]
The pipe operator is great for concisely representing a series of computations, but it can be surprising when functions that perform side effects are involved. Example:
```
import gleam/io

fn two_args(a, _b) {
  a
}

fn labeled(a a, b _b, c _c) {
  a
}

pub fn main() {
  io.debug("printed third")
  |> two_args(io.debug("printed second"), _)
  |> labeled(b: _, c: io.debug("printed last"), a: io.debug("printed first"))
  Nil
}
```

While this may be natural for experienced programmers, I think this behavior is not very intuitive. One option is to document it and recommend using the pipe operator only when side effects are not involved or can happen in any order.

Another option is to rewrite pipes to temporary assignments, for example:
```
pub fn main() {
  io.debug(1)
  |> two_args(io.debug(2), _)
  |> labeled(b: _, c: io.debug(3), a: io.debug(4))
  Nil
}

// could become:

pub fn main() {
  let tmp1 = io.debug(1)
  let tmp2 = io.debug(2)
  let tmp_two_args = two_args(tmp2, tmp1)
  let tmp3 = io.debug(3)
  let tmp4 = io.debug(4)
  labeled(b: tmp_two_args, c: tmp3, a: tmp4)
  Nil
}
```

This also raises the question: should usage of labeled arguments also be rewritten so that computations are happening in the order that labeled arguments are provided in?

**Comment by lpil** [comment]
Sounds like a good idea to me. It will also make the resulting generated code look more like the input code, which I think is quite appealing.

I don't have a good idea for how to improve the situation with labelled arguments currently. Perhaps we can just leave it as is for now, but if anyone has some suggestions I would be interested in hearing them.￼￼￼

**Comment by lpil** [comment]
Thanks again @michallepicki , this is a grand improvement
