### ISSUE TITLE
Importing a module and a function with the same name causes a runtime error [JS]

### ISSUE THREAD

**Issue by pd-andy** [gleam-lang/gleam#1169]
Given an import like:
```js
import dom/svg.{svg}
```
We produce the js:
```
import * as svg from "./dom/svg.js";
const { svg } = svg;
```
It seems this binding does nothing (and if it did, it would shadow the import) because when the compiled code calls:
```js
  return svg(...)
```
I get the runtime error `svg is not a function`.

Maybe we could do something like capitalising imports or prepending `$`, something that you can't write in gleam code, to avoid these name collisions:
```js
// gleam
import dom/svg.{svg}

// js
import * as Svg from "..."
const { svg } = Svg
```

**Comment by lpil** [comment]
Nice find, thank you
