### ISSUE TITLE
Combine multiple FFI imports compile to a single ESM re-export

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1170]
### Discussed in https://github.com/gleam-lang/gleam/discussions/1168

<div type='discussions-op-text'>

<sup>Originally posted by **pd-andy** June 21, 2021</sup>
Currently when compiling a Gleam module with multiple external fns from the same source, we compile to multiple import/export pairs:
```js
import { from } from "./ref.ffi.js";
export { from };

import { get } from "./ref.ffi.js";
export { get };

import { set } from "./ref.ffi.js";
export { set };

import { update } from "./ref.ffi.js";
export { update };
```
This can actually be reduced to just one line using [ESM re-exports](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#re-exporting_aggregating), resulting in:
```js
export { from, get, set, update } from "./ref.ffi.js";
```

I'm not sure whether this is a tangible win or not, I believe imports are cached so it's not like you'd hit the network multiple times with the current approach and it's nice to have the compiled module more-or-less follow the order of declaration that the original source did.</div>

**Comment by lpil** [comment]
I did a test with Node and it seems that with that syntax you can't use any of the functions in that module when using the re-export syntax.

Maybe something like this then?

```rust
external fn one() -> String  = "thingy" "one"
pub external fn two() -> String = "thingy" "two"
external fn rename_three() -> String  = "thingy" "three"
pub external fn rename_four() -> String = "thingy" "four"
```
```js
import { one, two, three as rename_three, four as rename_four } from "thingy";
export { two, rename_four };
```

@pd-andy

**Comment by pd-andy** [comment]
Huh interesting, I wonder if that behavior is defined on the spec.  Revised version LGTM.
