### ISSUE TITLE
Pipe error message incorrectly displayed when not using a pipe

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/gleam#1177]
Developing a simple script, pasted below:

```rust
import gleam/io
import gleam/iterator
import gleam/string
import shellout.{StderrToStdout}

pub const char_limit = 720

pub fn main(args: List(String)) -> NoReturn {
  case shellout.cmd("xsel", ["-ob"], [StderrToStdout(True)]) {
    Ok(#(output, status)) -> {
      let chunk_size = case args {
        [chunk_size, ..] -> chunk_size
        _-> char_limit
      }
      output
      |> iterator.from_list
      |> iterator.map(with: fn(line) {
        shellout.cmd("xdopaste", [line], [StderrToStdout(True)])
      })
      |> iterator.run
      status
    }

    Error(reason) -> {
      shellout.cmd("xdopaste", [reason], [StderrToStdout(True)])
      1
    }
  }
  |> halt
}

pub external type NoReturn

pub external fn halt(status: Int) -> NoReturn =
  "erlang" "halt"
```

I get the following very confusing error when compiling:
```sh
error: This function cannot handle the argument sent through the (|>) pipe:
   ┌─ ~/src/hyperpaste/src/hyperpaste.gleam:14:11
   │
14 │           _-> char_limit
   │           ^^^^^^^^^^^^^^

The argument is:

    Int

But (|>) is piping it to a function that expects:

    No arguments
```

After commenting a bunch of lines, I get the real error:
```sh
error: Type mismatch
   ┌─ /home/tynanbe/src/hyperpaste/src/hyperpaste.gleam:14:11
   │
14 │           _-> char_limit
   │           ^^^^^^^^^^^^^^

This case clause was found to return a different type than the previous
one, but all case clauses must return the same type.

Expected type:

    String

Found type:

    Int
```

**Comment by lpil** [comment]
Oh dear! Looks like https://github.com/gleam-lang/gleam/pull/1148 may trigger in additional undesired situations.

https://github.com/gleam-lang/gleam/pull/1148/files#diff-b914c906271f7161a76641fbfa2c677c39d61476b6bb03b59379c017f34e260aR107-R109

Here we apply the pipe Situation to all type errors arising from this call, but type errors unrelated to pipes may arise from within that function too. We will need to make this more precise, likely by moving this code into the function itself.

I've not done any testing yet but I'm a little confused as to how it would happen with the code given. I would expect this to trigger it maybe?

```rust
      let chunk_size = case args {
        [chunk_size, ..] -> chunk_size
        _-> char_limit
      }
      |> iterator.from_list
```

I am a little busy sorting out some renovation work on my home so I may not get around to this for a little while. @JohnDoneth  would you be interested in taking a look? No worries if not :)

**Comment by tynanbe** [comment]
> I've not done any testing yet but I'm a little confused as to how it would happen with the code given. I would expect this to trigger it maybe?

As far as I can tell, the overly eager error refers to this pipe:
```rust
  |> halt
```

**Comment by lpil** [comment]
Oh yes you are right, I didn't spot that line at the end

**Comment by edkelly303** [comment]
Just documenting another example, in case it helps:

```rust
import parser.{Parser} //from https://github.com/pd-andy/gleam-string-parser

fn bug() -> Parser(String) {
  parser.any()
  |> parser.then(fn(a) { a })
}
```
Gives an error of:
```
error: This function cannot handle the argument sent through the (|>) pipe:
  ┌─ /home/blah/src/bug_example.gleam:5:18
  │
5 │   |> parser.then(fn(a) { a })
  │                  ^^^^^^^^^^^

The argument is:

    String

But (|>) is piping it to a function that expects:

    String
```
This is perhaps even more confusing than the examples above, as the error message seems to be saying that the expected type is the same as the type we've provided.

I think the true error here is that `parser.then` is expecting an argument that is `fn(String) -> Parser(String)`, but instead I've given it `fn(String) -> String`
