### ISSUE TITLE
More than one discard in a function definition produces invalid JavaScript.

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#1186]
Gleam code
```rust
pub fn handle(_, _) {
    Nil
}
```

JS code
```js
"use strict";

export function handle(_, _) {
  return undefined;
}
```

Error message "Uncaught SyntaxError: Duplicate parameter name not allowed in this context"

Note trying the following does not work as it produces exactly the same output.
```rs
pub fn handle(_a, _b) {
    Nil
}
```

**Comment by lpil** [comment]
Oops, thank you for the report.

**Comment by lpil** [comment]
Sorry wrong button
