### ISSUE TITLE
Case statement with only a catch all produces invalid JavaScript

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#1187]
```rs
pub fn handle() {
    case 1 {
        _ -> Nil
    }
}
```

```js
"use strict";

export function handle() {
  let $ = 1;
   else {
    return undefined;
  }
}
```
Note there is only an else statement, no if statement.

I guess this is an error from trying to add the nicety of using only else, rather than else if for final clauses.

Potentially this is not a JS fix but a gleam fix to forbid a case statement with only one branch which is a catch all. As it is a meaningless construct.

**Comment by lpil** [comment]
Thanks for the report. Let's fix the output, later we can add a warning for this.
