### ISSUE TITLE
Move stdlib's should module to a testing library

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1191]
Question: Should this module be removed and placed in an eunit or Erlang library? (https://github.com/gleam-lang/gleam/issues/1189)
I'm thinking yes as we don't have a good idea of what Gleam testing should look like long term.

```
src/gleam/should.gleam
9:pub external type Expectation
11:pub external fn equal(a, a) -> Expectation =
14:pub external fn not_equal(a, a) -> Expectation =
27:pub external fn be_ok(Result(a, b)) -> Expectation =
30:pub external fn be_error(Result(a, b)) -> Expectation =
```

- [x] Library extracted
- [x] Project templates updated

**Comment by CrowdHailer** [comment]
I also think yes. It's always easier to grow it again in the future. 
There's also no reason a templated project, i.e. a call to `gleam new` can't start a project with more than one dependency. i.e. you can have a default way of test in new projects but it still doesn't need to be in std lib.

**Comment by lpil** [comment]
Including another library by default sounds good. It will allow us to adapt to whatever is best at the time too.
