### ISSUE TITLE
Port stdlib's map module to JS using conditional compilation 

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1195]
We need to implement our own immutable map. This could be done in pure Gleam.

Likely want to do research and benchmarking here.

```
src/gleam/map.gleam
18:pub external type Map(key, value)
32:pub external fn size(Map(k, v)) -> Int =
48:pub external fn to_list(Map(key, value)) -> List(#(key, value)) =
56:pub external fn from_list(List(#(key, value))) -> Map(key, value) =
59:external fn is_key(key, Map(key, v)) -> Bool =
78:pub external fn new() -> Map(key, value) =
94:pub external fn get(from: Map(key, value), get: key) -> Result(value, Nil) =
97:external fn erl_insert(key, value, Map(key, value)) -> Map(key, value) =
117:external fn erl_map_values(fn(key, a) -> b, Map(key, value)) -> Map(key, b) =
146:pub external fn keys(Map(keys, v)) -> List(keys) =
160:pub external fn values(Map(k, values)) -> List(values) =
163:external fn erl_filter(
186:external fn erl_take(List(k), Map(k, v)) -> Map(k, v) =
218:pub external fn merge(into: Map(k, v), merge: Map(k, v)) -> Map(k, v) =
221:external fn erl_delete(k, Map(k, v)) -> Map(k, v) =
```

**Comment by CrowdHailer** [comment]
> Likely want to do research and benchmarking here.

What do we think will do better than the JS implementation of a Map
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

Quote from docs, suggesting it should hold anything we need it too?
> any value (both objects and primitive values) may be used as either a key or a value.

**Comment by lpil** [comment]
The JS Map is not immutable so to use it we would need to clone it on each operation. This would be very slow compared to implementing an immutable map with structural sharing. Could be OK for a first version though.

**Comment by CrowdHailer** [comment]
> Could be OK for a first version though

Are we OK with the principle that first implementations can be slower? Channelling my inner Joe I would say yes. 
There is a similar comment in the issue about the `gleam/int` module using a regex

I don't think we should do silly things. but getting the std libs to parity involves a bit of work already. conflating it with performance seems like another level

**Comment by lpil** [comment]
I think slower is OK so long as we get the behaviour right. For things like `Map` it would be nice to wrap it in an object or something to make it clearer that the runtime representation isn't to be relied upon

**Comment by UnsolvedCypher** [comment]
I would be interested in taking this on if nobody is already working on it. How do you feel about using ImmutableJS for this? Since that is already a battle-tested and performant implementation of immutable maps, it may make more sense to rely on that rather than implementing our own.

**Comment by lpil** [comment]
I'm looking for a zero dependency solution for the stdlib, though we can use existing libraries as references or inline existing code. I think Elm may be a more suitable place to look as immutable JS has a large code size and has features we don't need. As a statically typed language we can be more efficient by doing less at runtime.

**Comment by timjs** [comment]
My first thought was also reusing Elm's implementation. Is that not feasible?

**Comment by lpil** [comment]
I've not read it properly yet but it seems that Elm's implementation doesn't support insertion of arbitrary values, only a subset of Elm values are supported. I think we would need to add immutable js style hashing to the Elm version at least.

**Comment by rafaelfesi** [comment]
Maybe taking a look at the ReScript implementation might help?
