### ISSUE TITLE
Port stdlib's function module to JS using conditional compilation

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1196]
## function

I think we want to rethink the sig of the exception type here as it is very Erlang specific.

```
src/gleam/function.gleam
70:pub external fn rescue(fn() -> a) -> Result(a, Exception) =
```

**Comment by CrowdHailer** [comment]
I wonder if these even belongs in stdlib? It's possible the the ffi language won't have catchable exceptions?

**Comment by lpil** [comment]
Maybe! Though I could see wanting to rescue errors on any platform being common.
