### ISSUE TITLE
Move stdlib's os module code to the gleam_os library

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1197]
These functions cannot be implemented within the browser. Do we move them to an OS library? Or do we have no-op versions?

Remove erlang_timestamp.

```
src/gleam/os.gleam
8:external type CharList
10:external fn os_getenv() -> List(CharList) =
13:external fn os_putenv(key: CharList, value: CharList) -> Bool =
16:external fn os_unsetenv(key: CharList) -> Bool =
19:external fn char_list_to_string(CharList) -> String =
22:external fn string_to_char_list(String) -> CharList =
59:pub external fn system_time(TimeUnit) -> Int =
65:pub external fn erlang_timestamp() -> #(Int, Int, Int) =
```

**Comment by tranzystorek-io** [comment]
I'd opt for a separate library if this functionality is not ubiquitous across all targets

**Comment by CrowdHailer** [comment]
Maybe there's more that should live in gleam_beam??

https://github.com/midas-framework/beam

**Comment by lpil** [comment]
Started this library.  Needs JS Map support to get the last function across

https://github.com/gleam-lang/os

**Comment by lpil** [comment]
Need Map for the last function here

https://github.com/gleam-lang/os/blob/9287d7fde0b93a823d033561544e877728893edb/src/gleam/os.gleam#L19

**Comment by CrowdHailer** [comment]
I like the roc approach of having platforms. Because os access is governed by the platform i.e. node/browser/beam it makes sense that stuff like accessing files belongs in them. Also I don't think you want the job of specifying a common OS api that works over all platforms, seems a thankless task and would have to end up as the lowest common denominator of each

**Comment by lpil** [comment]
Gleam itself is a general purpose programming language but I don't see any reason why not to implement frameworks like Elm and Roc in Gleam. Especially in a future where we have Gleam native :)
