### ISSUE TITLE
Port stdlib's int module to JS using conditional compilation

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1203]
```
src/gleam/int.gleam
33:pub external fn parse(String) -> Result(Int, Nil) =
43:pub external fn to_string(Int) -> String =
59:pub external fn to_base_string(Int, Int) -> String =
75:pub external fn to_float(a: Int) -> Float =
```

**Comment by CrowdHailer** [comment]
### Notes on parse.

The function as it is defined now errors if it cannot convert the whole string to a number i.e.
```rust
parse("1a") == Error(Nil)
```

The JavaScript `parseInt` function would ignore the rest of the string if the first part is a numer. i.e.
```rust
// When targeting JS
parse("1a") == Ok(1)
```

MDN recommends a stricter integer parsing function as follows. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#a_stricter_parse_function 

**However this introduces a regex, which may well be undesirable.**

```js
function filterInt(value) {
  if (/^[-+]?(\d+)$/.test(value)) {
    return Number(value)
  } else {
    return NaN
  }
}
```

### to_string & to_float
These would be trivial to implement

### to_base_string
This should also be trivial to implement as `toString` takes a radix as an argument
```js
a = 100
a.toString(16) // => 64
```

### Question
The stdlib has no function for parsing integers in an arbitrary base. i.e. `parse("64", base: 16) == 100`

**Should we add an issue to make a complementary parsing function to the `to_base_string` function?**

**Comment by lpil** [comment]
That all sounds good! Happy to use a regex in the JS glue code.

> Should we add an issue to make a complementary parsing function to the to_base_string function?

Yup, let's do this.
