### ISSUE TITLE
`gleam format` print output with vscode extension printing `noline` to file

### ISSUE THREAD

**Issue by TanklesXL** [gleam-lang/gleam#1210]
So I've got an example function
```rust
fn operate(
  mem: Map(Int, Int),
  src_a: Int,
  src_b: Int,
  src_dest: Int,
  f: fn(Int, Int) -> Int,
) -> Result(Map(Int, Int), Nil) {
  try a =
    mem
    |> map.get(src_a)
    |> result.then(map.get(mem, _))
  try b =
    mem
    |> map.get(src_b)
    |> result.then(map.get(mem, _))
  try dest = map.get(mem, src_dest)
  Ok(map.insert(mem, dest, f(a, b)))
}
```
when this gets formatted in `vscode` , the formatter prepends 
```
noline
noline
noline
```
to the top of the file, but when the function has a newline after the last `try` like:
```rust
...
  try dest = map.get(mem, src_dest)

  Ok(map.insert(mem, dest, f(a, b)))
}
```
it prepends
```
noline
noline
line
```
I think this  has to do with the number of `try`s present,  and the prints seem to be happening at
https://github.com/gleam-lang/gleam/blob/e9b05fcf6b84117da487ca5facbf65bdb208a304/compiler-core/src/format.rs#L609
and 
https://github.com/gleam-lang/gleam/blob/e9b05fcf6b84117da487ca5facbf65bdb208a304/compiler-core/src/format.rs#L612

when not in vscode and just using the formatter from the command line, those same lines get printed to stdout instead.

**Comment by lpil** [comment]
Oops. Well that was embarrassing
