### ISSUE TITLE
Remove deprecated tuple syntax

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1216]
```rust
tuple(1, 2)
```

**Comment by tranzystorek-io** [comment]
Do we want to do hard deprecate of that syntax? Or just some sort of soft warning for now?

**Comment by lpil** [comment]
Let's just remove it. The current version can be used to upgrade.

**Comment by aflatter** [comment]
Hello, I've just started working on this and hope to make a PR soon. 👋
