### ISSUE TITLE
Request for persistent artefact storage

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [gleam-lang/gleam#1228]
Hi.

I'm adding Gleam support to [erlef/setup-beam](https://github.com/erlef/setup-beam). It's working, as-is (https://github.com/erlef/setup-beam/pull/67), for Windows and Ubuntu, but I feel (I looked at how you're using `setup-erlang` and `setup-beam` in all the gleam-lang org. repo.s) we could benefit from allowing CI on top of the latest version, ie. where you're using `ref:main` in your CI files.

If I got it correct, you're only creating artefacts for Ubuntu, eg. as found at https://github.com/gleam-lang/gleam/suites/3374470508/artifacts/79494359. I've not used GHA to generate artefacts before, so don't exactly know where we could fetch them from using a predictable name.

I could explore fetching further from https://api.github.com/repos/gleam-lang/gleam/actions/artifacts, but still two issues are presented: 1. it seems the artefacts expire after about 3 months, 2. they're not easily identifiable (so we could only assume from the file format that stuff would be Ok).

Is there a place (in GitHub or otherwise) where you're storing the builds for `main`?

Thanks for your time.

**Comment by lpil** [comment]
Hello! Currently if someone wants to use the main branch the action downloads this repo and compiles it from scratch. Are you looking for precompiled versions of whatever the latest version of the main branch is?

**Comment by paulo-ferraz-oliveira** [comment]
Hi, Louis. That's what I'm looking for, precompiled latest main. That way setup-beam would cover, hopefully, whatever setup-gleam already does 😄

**Comment by lpil** [comment]
I'm game in theory but I'm not sure what the best way to do this is. If anyone has a suggestion for how to store these artifacts please do chip in!

**Comment by paulo-ferraz-oliveira** [comment]
Being game is the first step, for sure. Unfortunately I don't know how/where to best put those resources. Let me invite @starbelly to the mix.

**Comment by lpil** [comment]
Let's merge this into #1277
