### ISSUE TITLE
Fatal Compiler bug. "Unexpected unbound var when serialising module metadata"

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#1230]
I can't work out a minimal repro, but I've seen this a few times.

```
error: Fatal compiler bug!

This is a bug in the Gleam compiler, sorry!

Please report this crash to https://github.com/gleam-lang/gleam/issues/new
with this information and the code that produces the crash.

	compiler-core/src/metadata/module_encoder.rs:335
	Unexpected unbound var when serialising module metadata
```

I'm running the command.
```
gleam compile-package --src language/src --out public/gen --name my_app --target javascript
```

**Comment by lpil** [comment]
That's very interesting! Could you share the code that produces this?

**Comment by CrowdHailer** [comment]
I'm scratching my head here.

By commenting out various bits I can say the problem is somewhere in this block.
https://github.com/midas-framework/project_wisdom/blob/main/language/src/language/codegen/javascript.gleam#L154-L165

Also if the target isn't JavaScript I don't seem to have the same issue because I am successfully running unit tests with `gleam eunit`

**Comment by lpil** [comment]
Thank you, that helps a lot.

`gleam eunit` doesn't use the same compilation API at the moment, so it doesn't output any metadata. It may still happen when targetting Erlang if the metadata is generated.

**Comment by CrowdHailer** [comment]
Is this work around for the same compiler bug? https://github.com/gleam-lang/stdlib/commit/dd8a7bacc5db670bb084e8c77b02c0c1c44f605d

**Comment by CrowdHailer** [comment]
I'm not sure if the above advice was missleading, but I've found another place where this error shows up.

Making the following change fixes it.
```diff
-pub fn pop(list, value) {
+pub fn pop(list: List(a), value: a) -> Result(List(a), Nil) {
   do_pop(list, value, [])
 }
```

I was trying to work out how to add some more context to the error, i.e. the module it's working on to see if I could find more of the cases where it matters.

**Comment by lpil** [comment]
> Is this work around for the same compiler bug? gleam-lang/stdlib@dd8a7ba

This was for that tail recursion bug you found #1214

**Comment by lpil** [comment]
Off by one error in function generalisation!

**Comment by CrowdHailer** [comment]
Good find. 

:heart:
