### ISSUE TITLE
Invalid erlang produced when building and destructuring a list.

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#1231]
Gleam code 
```rs
fn main(x) {
  [..x]
}
```
erlang code
```erl
-module(repro).
-compile(no_auto_import).

-spec main(list(J)) -> list(J).
main(X) ->
    [ | X].
```
Syntax error `[ | X]` 

Potentially not an erlang generation issue potentially something to be forbidden an the gleam level because it is a meaningless operation.

**Comment by lpil** [comment]
Thanks for the report! Maybe we should make this a syntax error.
