### ISSUE TITLE
Add a debug view of the term in a bad match for javascript.

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#1239]
match errors in Elixir/Erlang print the term to the console. i.e.
```
iex> 1 = %{foo: 1, bar: [2, fn() -> :foo end]}
** (MatchError) no match of right hand side value: %{bar: [2, #Function<45.40011524/0 in :erl_eval.expr/5>], foo: 1}
```

My suggestion would be to call `JSON.stringify` and add that to the Bad Match message in these two places.
- https://github.com/gleam-lang/gleam/blob/ebb16ecc381e50e57d8918b127183f570578c2b5/compiler-core/src/javascript/pattern.rs#L457
- https://github.com/gleam-lang/gleam/blob/f429ec117ab01416480931627ef6c3d5d95ecc48/compiler-core/src/javascript/expression.rs#L542

**Comment by CrowdHailer** [comment]
Excited for this, makes a big difference. Thank you.

**Comment by lpil** [comment]
Me too! It has been so annoying. Thanks for the nudge to finally do it
