### ISSUE TITLE
`io.get_line()` reads Charlist instead of String

### ISSUE THREAD

**Issue by timjs** [gleam-lang/gleam#1252]
### To reproduce

* Create an escript project with Gleam
* Read a line from stdin, convert it to a `BitString`, try to match on it (see code below)

```rust
import gleam/io
import gleam/bit_string

pub fn main(_: Nil) {
  try line = io.get_line("Enter some text: ")
  let bits =
    line
    |> bit_string.from_string()
  let <<head, tail:bit_string>> = bits
  io.debug(head)
  |> Ok()
}
```

### Expected output

Print the first byte entered.

### Actual output

```
escript: exception error: no match of right hand side value "Hallo\n"
  in function  test:main/1 (/Users/Tim/Library/Mobile Documents/com~apple~CloudDocs/Projecten/gleam-test/gen/src/test.erl, line 17)
  in call from escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
```

### Notes

Apparently the line is read in as a charlist. Trying to set stdin as binary input using the code below:

```rust
external fn get_opts() -> Opts =
  "io" "getopts"

external fn set_opts(Opts) -> Nil =
  "io" "setopts"

type Opts {
  Binary(Bool)
  Encoding(Encoding)
}

type Encoding {
  Latin1
  Unicode
}

pub fn main(_: Nil) {
  io.debug(get_opts())
  io.debug(set_opts(Binary(True)))
}
```
...results in the error:

```
[{binary,false},{encoding,latin1}]
{error,{request,{setopts,{binary,true}}}}
```

Don't know why... I'd expect stdio to be set to `{binary, true}` by default, but it isn't. Is there something else I'd need to do?

### Info

Gleam 0.16.1
Erlang/OTP 24 [erts-12.0.3]
macOS 11.3.1 (20E241)

**Comment by lpil** [comment]
Oh dear! This is quite a bug. We'll ensure this is fixed in the next release

For your call to `setopts` I think the argument needs to be a `List(Opts)`

**Comment by timjs** [comment]
Thanks about the `List(Opts)` tip! Misread the Erlang documentation.
