### ISSUE TITLE
Reused names generating invalid JS

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#1253]
This commit that changes only a variable name breaks a test in my project. https://github.com/midas-framework/project_wisdom/commit/3a01b062a8862712af4f6fe3decf40b99a100902

The version of Gleam I am using is main. commit SHA cf9c9345d053406dcf22c87aae0990a5480aa2b5
To run the tests run `./bin/test` requires node and the gleam compiler. there is also a dockerfile that will give that environment `docker-compose run language bash` then `cd /opt/app/eyg`

I've tried really hard to get a minimum repro in some list tests but not luck with the getting the same behaviour https://github.com/midas-framework/project_wisdom/blob/3a01b062a8862712af4f6fe3decf40b99a100902/eyg/test/eyg/list_test.gleam

The generated JS looks like the following. Line 4 is incorrect it should generate a `typer$6` variable
```js
        let $8 = List.try_fold(
          clauses,
          typer$5,
          (clause, typer) => {
            let variant = clause[0];
            let variable = clause[1];
            let then = clause[2];
            let $6 = List.key_find(variants, variant);
            if ($6.type !== "Ok") throw new Error("Bad match");
            let argument = $6[0];
            let argument$1 = pair_replace(replacements, argument);
            let typer$6 = Object.assign({}, typer$5, { variables: variables });
            let typer$7 = set_variable(variable, argument$1, typer$6);
            let $7 = infer(then, typer$7);
            if ($7.type === "Error") return $7;
            let type_ = $7[0][0];
            let typer$8 = $7[0][1];

            return unify(return_type, type_, typer$8);
          },
        );
```

**Comment by CrowdHailer** [comment]
Here is another occurrence of renaming I have had to do to avoid the bug. https://github.com/midas-framework/project_wisdom/commit/bc7b5357f6989e794c525e338e18e5e053316de4

This time the function misbehaving is `map_state` not fold. The thing they have in common is they are recursive. 

Not sure if this extra report is that helpful beyond the fact that the mapping functions are a bit smaller.

**Comment by lpil** [comment]
Thank you

**Comment by lpil** [comment]
@CrowdHailer Have you hit this again recently? I can't reproduce it with the latest compiler :(

**Comment by CrowdHailer** [comment]
@lpil yes it still exists. took me a while to be sure but here's a small repro at least. 

Given this Gleam code.
```rs
pub fn debug(x) {
  let x = x + 1
  let x = list.map([x], fn(x) { x + 1})
}
```
The following is now generated.
```js
export function debug(x) {
  let x$1 = x + 1;
  let x$2 = $list.map(toList([x$1]), (x) => { return x$1 + 1; });
}
```
The arg is to the anon function is x but is being used as x$1 in the body

**Comment by lpil** [comment]
Thanks for the minimal reproduction, made it really easy to debug
