### ISSUE TITLE
Improve performance of stdlib immutable Map on JavaScript

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1262]
Currently the Map type copies the entire set on each insertion. Change it to use structural sharing.

Using int hashcodes rather than strings would also be good

Elm, ReScript, or Immutable JS could be good references.

https://github.com/gleam-lang/stdlib/blob/3477ae008a46ffca6c79ee4f9ad8ec876d25ce31/src/gleam_stdlib.js#L269

**Comment by schurhammer** [comment]
Heres some blog posts that gives an overview
http://blog.higher-order.net/2009/09/08/understanding-clojures-persistenthashmap-deftwice
https://blog.higher-order.net/2010/08/16/assoc-and-clojures-persistenthashmap-part-ii.html

**Comment by inoas** [comment]
@schurhammer thank you so much!
