### ISSUE TITLE
Alternative case clauses are being accepted without containg all the required variables.

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#1263]
The following code is accepted by the compiler despite being invalid.
```rs
pub fn debug(x) {
  case x {
    Some(y) | None -> y
  }
}
```
The JS output is where the second case returns `y` but one that was never instantiated.
```js
export function debug(x) {
  if (x.type === "Some") {
    let y = x[0];
    return y;
  } else if (x.type === "None") {
    return y;
  } else {
    throw new Error("Bad match");
  }
}
```
If the alternative clauses are defined in the other order. i.e. `None | Some(y)` Then there is a compiler error, which I think is correct behaviour.

**Comment by lpil** [comment]
Good find, thank you
