### ISSUE TITLE
Generate typescript type definitions for Gleam modules when compiling to JavaScript

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1269]
Similar to how we generate Erlang typespecs.

**Comment by vstreame** [comment]
@lpil Are you thinking of this as `*.d.ts` files? Or as typescript `JSDoc` comments?

**Comment by lpil** [comment]
I was leaning towards `.d.ts` files as it seemed like the `JSDoc` format wasn't expressive enough to represent everything in the prelude ([it needs structural typing](https://github.com/gleam-lang/gleam/blob/main/compiler-core/templates/prelude.d.ts))
