### ISSUE TITLE
[Generated docs] Render inline code with appropriate background color

### ISSUE THREAD

**Issue by tranzystorek-io** [gleam-lang/gleam#1273]
Code elements inside documentation text are visually almost indistinguishable from non-code text:

![obraz](https://user-images.githubusercontent.com/5671049/134714102-92c70e5c-11e7-4ace-aca6-1a45dcb3195d.png)

For reference, Rust has nice parameters IMO, with the background color and different font color:

![obraz](https://user-images.githubusercontent.com/5671049/134715139-3bbdfcf5-a33d-40a0-9009-45a04effdc64.png)

I looked at the `index.css` template and the `code` element could probably use a background color, but I'm no CSS wizard 😛

**Comment by lpil** [comment]
Well spotted, let's fix this for sure.
