### ISSUE TITLE
Nightly `gleam` binary compilation

### ISSUE THREAD

**Issue by cognivore** [gleam-lang/gleam#1277]
# Why?

Seemingly, early adopters want to use nightly exclusively because most them also contribute to the tech.
Having nightlies would benefit them, as well as augment CI experience.

# What?

 - [ ] Support all the currently supported release targets
 - [ ] Host nightlies somewhere
 - [ ] Host an archive of nightlies for quick experiments
 - [ ] Enable `nightly` and, perhaps, versions from the archive to be used from `setup-gleam` github hook

# How?

 - [ ] Learn how current release management is performed
 - [ ] Figure out Rust cross-compilation
 - [ ] Determine the level of scrutiny in artefact testing that is acceptable for nightlies
 - [ ] Crowd-source or otherwise obtain access to hardware, perhaps virtual, needed to build and host the artefacts

**Comment by HarryET** [comment]
Hey, I'm happy to have a look at this if it's still somthing that Gleam needs/wants?

**Comment by lpil** [comment]
Assigned you!
