### ISSUE TITLE
Support `--warnings-as-errors` for build tool

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1292]

**Comment by vic** [comment]
I'll also take this one.

**Comment by lpil** [comment]
Thank you

**Comment by pascalwengerter** [comment]
@lpil has this happened via https://github.com/gleam-lang/gleam/commit/c202ebcf6b177be4d80adcff3f6380ed651fb3d0 ? :)

**Comment by lpil** [comment]
Possibly! We'll need to check it is working as that was some time  go and I don't remember if it was before or after this issue was created 😅

**Comment by pascalwengerter** [comment]
> Possibly! We'll need to check it is working as that was some time go and I don't remember if it was before or after this issue was created 😅

Turns out it's been "disabled" via https://github.com/gleam-lang/gleam/blob/2af8497e5f24f300d4c5b01b1dbe2bb6fa83d2cc/compiler-cli/src/main.rs#L359, I have a running version locally but need to refine it a bit more. Is it intended that warnings get swallowed in consecutive builds?

**Comment by lpil** [comment]
Oops 😁 

> Is it intended that warnings get swallowed in consecutive builds?

Currently there's a limitation with conditional compilation, there's an issue for it here:

https://github.com/gleam-lang/gleam/issues/1913

**Comment by pascalwengerter** [comment]
@lpil I guess this was closed by mistake? I'll still try to pick up my (now closed) PR sometime soon :)

**Comment by lpil** [comment]
Nop, it was implemented here: https://github.com/gleam-lang/gleam/commit/3d394fda30828c79531317badf003d3b986f107e

Sorry for closing yours, I thought you had lost interest!

**Comment by pascalwengerter** [comment]
> Nop, it was implemented here: [3d394fd](https://github.com/gleam-lang/gleam/commit/3d394fda30828c79531317badf003d3b986f107e)
> 
> Sorry for closing yours, I thought you had lost interest!

Ah, nice to see it having been re-introduced (and the solution looks more straightforward than mine 😅 )! Let me check for another first-timer friendly issue, then

**Comment by lpil** [comment]
The codebase changed a little since you made your attempt so it was easier for me :)
