### ISSUE TITLE
`gleam deps download` incorrect downloaded package count reporting

### ISSUE THREAD

**Issue by TanklesXL** [gleam-lang/gleam#1329]
Downloading deps reports number of downloaded packages off by 1:

To reproduce
- build gleam main
- `gleam new example`
- `cd example && gleam deps download`

Generated output:
```
Resolving versions
Downloading packages
Downloaded 2 packages in 0.32s
```

Expected output:
```
Resolving versions
Downloading packages
Downloaded 1 package in 0.32s
```
The 1 package expected being the gleam stdlib.

**Comment by lpil** [comment]
Thank you
