### ISSUE TITLE
Negation Operator

### ISSUE THREAD

**Issue by varnerac** [gleam-lang/gleam#1330]
We need a way to negate booleans in a `case` guard statement.

`if !some_bool -> …`

**Comment by lpil** [comment]
Lets do this for sure.

**Comment by timjs** [comment]
There are no prefix operators yet in Gleam, are there? Is `not` as a function not enough?

**Comment by lpil** [comment]
Unfortunately the BEAM does not permit arbitrary functions in guards. Given we have operators for boolean and and or I think a not would fit well, solve this issue, and be predictable for those coming from other languages

**Comment by timjs** [comment]
But does that mean not should be an operator? It would be the only prefix operator in Gleam. And you can still special case not in the compiler, as you probably need to do with and and or.

**Comment by lpil** [comment]
We could possible have a keyword sort of thing that degrades into a function if stored in a variable, but I'm not a big fan of having `not` when we use `&&` and `||` rather than `and` and `or`.

**Comment by lpil** [comment]
@HarryET Tagging you as I hope that'll let me assign this to you

**Comment by HarryET** [comment]
👍🏼 I've got the PR in progress too #1497
