### ISSUE TITLE
`gleam deps list`

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1346]
A command that prints all dependencies

**Comment by tommyschaefer** [comment]
Hi there! I'd love to give this a go if possible 😄

If so, do you have a particular formatting in mind? My initial thought was something along the lines of:

```
From gleam.toml:

    *  gleam_stdlib (~> 0.18)                                    
    *  gleam_otp (~> 0.3)
```

But I also took a look at other dependency list formats:

Ruby `gem list`:

```

*** LOCAL GEMS ***

abbrev (default: 0.1.0)
base64 (default: 0.1.0)
...
```

Elixir `mix deps`:

```
* bunt 0.2.0 (Hex package) (mix)
  locked at 0.2.0 (bunt) 7af5c7e0
  ok
* credo 1.6.1 (Hex package) (mix)
  locked at 1.6.1 (credo) 698607fb
  ok
* dialyxir 1.1.0 (Hex package) (mix)
  locked at 1.1.0 (dialyxir) 07ea8e49
  ok
...
```

Node `npm ls`:

```
assets@ /Users/tom/code/waffle_foundry/assets
├── @babel/core@7.13.15
├── @babel/preset-env@7.13.15
├── @tailwindcss/forms@0.3.2
...
```

Rust `cargo tree --depth 1`:

```
...

gleam-wasm v0.18.0-rc2 (/Users/tom/code/gleam/compiler-wasm)
├── gleam-core v0.18.0-rc2 (/Users/tom/code/gleam/compiler-core) (*)
└── wasm-bindgen v0.2.78
[dev-dependencies]
└── wasm-bindgen-test v0.3.28
```

Of these, I quite like Rust's output, and think that might serve as helpful inspiration 😄 What are your thoughts?

**Comment by lpil** [comment]
I think a flat list of all locked packaged would be good. For now we could show the name and version, but perhaps we could also show the licence in future.

I quite like the first format you've suggested. I think the Elixir one is a bit noisy.

Later on we could have a `gleam deps tree` for the nested format that shows why a package is selected, showing multiple entries for packages depended on multiple times.

**Comment by tommyschaefer** [comment]
That sounds great! I’ll give it a try and submit a PR! 😄
