### ISSUE TITLE
dependency changes not reflected in `manifest.toml` or `build` dir

### ISSUE THREAD

**Issue by TanklesXL** [gleam-lang/gleam#1356]
When adding/modifying dependencies of a project, i would expect that changes made to `gleam.toml` be reflected in `manifest.toml` and `build`.

Note: current latest gleam_erlang is `v0.4.0`

To Reproduce:
```
> gleam new example
> cd example
> gleam add gleam_erlang 
# should install gleam_erlang v0.4.0
```
next: 
- change line in `gleam.toml` for gleam_erlang to be: `gleam_erlang = "~> 0.3.0"`
rerun `gleam deps download`
- the `requirements` section of `manifest.toml` has been updated but the `package` section still says:
```
  { name = "gleam_erlang", version = "0.4.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "gleam_erlang", source = "hex", outer_checksum = "67A456C0D3908050C869D19721BAE300C6C4ED41BFC034CC80DF7828EAB5E183" },
```
- the `build` dir contains `gleam_erlang v0.4.0`

**Comment by lpil** [comment]
Good find. We should unlock packages for which the requirement has changed when performing resolution again.
