### ISSUE TITLE
Pattern match using lowercase boolean value

### ISSUE THREAD

**Issue by TristanCacqueray** [gleam-lang/gleam#1358]
This code compiles and prints "oops"

```gleam
  case 42 > 42 {
    true -> io.println("oops")
    false -> io.println("ok")
  }
```

The erlang compiler does warn about `Warning: variable 'True' is unused`.

I guess gleam would fail when it will check for exhaustiveness, but perhaps the compiler could also emit an user friendly hint or warning for such simple mis-use?

**Comment by lpil** [comment]
I think you're right, this is going to be a common mistake for people used to languages with lowercase boolean values.

In future we will get a warning from this with exhaustiveness checking, but perhaps we should always ban the variable names `true` and `false` in patterns? It seems unlikely they would be intentionally used.
