### ISSUE TITLE
ARM / aarch64 prebuilt binaries for Linux, OSX, and Windows

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1365]
- [x] Linux
- [x] OSX
- [ ] Windows

**Comment by tynanbe** [comment]
Here's a Dockerfile to cross-compile a static gleam binary for Linux ARMv7 (32bit).

Note that `musl` < v1.2 is required for 32bit architectures, at least until the `musl` included with Rust is updated. As I understand it, in v1.2, `musl` made changes to time representation in preparation for years > 2038. This affects OpenSSL and its dependants, and I haven't gotten the build to work when the cross-compilation toolchain uses `musl` > v1.1.x.

Here are some useful resources and other paths to explore:
- https://jensd.be/1126/linux/cross-compiling-for-arm-or-aarch64-on-debian-or-ubuntu
- https://toolchains.bootlin.com/releases_armv7-eabihf.html
- https://actually.fyi/posts/zig-makes-rust-cross-compilation-just-work/
(note that Zig currently bundles `musl` v1.2.x, and I wasn't able to get a working build using it as the cross-compiler)
- https://github.com/richfelker/libcompat_time32

The build can be done with something like the following:
```shell
: podman build -t gleam-armv7:local .
: cd gleam
: cargo clean && podman run --user 0:0 --rm -v .:/volume gleam-armv7:local make build
```

```Dockerfile
FROM clux/muslrust:stable

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      bzip2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN ~/.cargo/bin/rustup target add armv7-unknown-linux-musleabihf \
    && echo "[build]\ntarget = \"armv7-unknown-linux-musleabihf\"\n\n[target.armv7-unknown-linux-musleabihf]\nar = \"arm-linux-ar\"\nlinker = \"arm-linux-gcc\"" > ~/.cargo/config

RUN curl -sSL "https://toolchains.bootlin.com/downloads/releases/toolchains/armv7-eabihf/tarballs/armv7-eabihf--musl--stable-2020.02-2.tar.bz2" | tar xjf - \
    && cp -r armv7-eabihf--musl--stable-2020.02-2/* "${PREFIX}//" \
    && rm -rf "armv7-eabihf--musl--stable-2020.02-2"

ENV AR="arm-linux-ar" \
    CC="arm-linux-gcc" \
    RANLIB="arm-linux-ranlib" \
    AR_armv7_unknown_linux_musleabihf="arm-linux-ar" \
    CC_armv7_unknown_linux_musleabihf="arm-linux-gcc" \
    RANLIB_armv7_unknown_linux_musleabihf="arm-linux-ranlib" \
    CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_RUSTFLAGS="-C target-feature=+crt-static" \
    TARGET_AR="${PREFIX}//arm-linux-ar" \
    TARGET_CC="${PREFIX}//arm-linux-gcc" \
    TARGET_RANLIB="${PREFIX}//arm-linux-ranlib"

RUN curl -sSL "https://www.openssl.org/source/openssl-${SSL_VER}.tar.gz" | tar xzf - \
    && cd "openssl-${SSL_VER}" \
    && ./Configure no-zlib no-shared -fPIC --prefix="${PREFIX}" --openssldir="${PREFIX}//ssl" linux-armv4 \
    && env C_INCLUDE_PATH="${PREFIX}//include" make depend 2> /dev/null \
    && make -j$(nproc) && make install_sw \
    && cd .. && rm -rf "openssl-${SSL_VER}"
```

**Comment by tynanbe** [comment]
For aarch64, it might work to adapt the above Dockerfile, replacing the triplets, and using e.g. this toolchain: https://toolchains.bootlin.com/downloads/releases/toolchains/aarch64/tarballs/aarch64--musl--stable-2021.11-1.tar.bz2
