### ISSUE TITLE
Pipeline error message showing incorrect code

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1378]
```rust
import gleam/string

fn get_data() -> String {
  ""
  |> string.split(on: ",")
}
```
```
error: Type mismatch
  ┌─ src/thingy.gleam:4:3
  │
4 │   ""
  │   ^^

The type of this returned value doesn't match the return type 
annotation of this function.

Expected type:

    String

Found type:

    List(String)
```

**Comment by rnice01** [comment]
I'd like to work on this if possible!

**Comment by lpil** [comment]
That would be great! Go for it @rnice01

**Comment by rnice01** [comment]
@lpil Some pointers would be appreciated 😄 
Not really sure where to start....was trying to see if there were any tests around how stack traces are built, feeling a bit lost though 😅

**Comment by lpil** [comment]
Sure thing! I'm aware it's not obvious how to get started with everything here.

This error is returned from here

https://github.com/gleam-lang/gleam/blob/9cf00997ada9fc2b7937b9dfe264e6d0e6e3fb80/compiler-core/src/type_/expression.rs#L1765-L1766

The source code to display comes from `body.location()`, where in this instance `body` is a `Sequence` created by the code that type checks pipe expressions.
The location given to this sequence comes from the `PipeTyper`

https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/type_/pipe.rs#L56-L59

And that in turn got it from the first pipeline item

https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/type_/pipe.rs#L31

I think what we want is for that location to be the start of the first, and the end of the last expressions.

After that some tests may need updating, including snapshot tests which we manage with this tool: https://github.com/mitsuhiko/insta

It'd be good too to have a test for this exact scenario, like this: https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/type_/tests/errors.rs#L1293-L1311

**Comment by lpil** [comment]
Hi @rnice01 , are you intending to work on this still?
