### ISSUE TITLE
Update Erlang tests to use snapshots + have multiple directories

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1381]
Update the Erlang tests to the same standard as the JS tests.

1. Split big test functions into one per assertion
2. Split the big test module into a module per type of thing being tested
3. Use snapshots rather than hard-coding the expected Erlang.

This can be done in multiple PRs to make it easier.

**Comment by michaeljones** [comment]
I can have a look at this. For some reason I sometimes like tasks like this. For a bit anyway :)

**Comment by lpil** [comment]
Wonderful!

Don't feel it needs to be one massive PR. If you do just some of it that would be great still.

**Comment by lpil** [comment]
Is there more you'd like to do on this @michaeljones ? I am super happy with what you've done

**Comment by michaeljones** [comment]
Happy to have been of help. It depends on whether you're happy with the remaining tests in https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/erlang/tests.rs staying there? I've split out the more obviously group-able ones but it gets harder and harder to decide with the ones left. 

I guess I'm happy to stop there but you might want to take it further.

**Comment by lpil** [comment]
I think snapshots are where the majority of the value come from, so I'm happy. Thank you!
