### ISSUE TITLE
Generate Erlang application files with `gleam compile-package`

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/gleam#1384]
`gleam compile-package --target erlang --name gleam_stdlib --src src --out gen`, which should be used to build deps for Erlang (`rebar3`) and Elixir (`mix`) projects, currently lacks the ability to generate Erlang application files.

### Previous Discussion
lpil: Maybe compile-package will have to start reading gleam.toml. I can't see how we'd get all the data otherwise.
tynanbe: Would it make sense for compile-package to have a flag to do the erlc work too?
lpil: Maybe we should copy whatever `mix` and `rebar3` do.
Actually maybe we shouldn't call `erl`. If we're being called from `rebar3` or `mix` they can compile the Erlang faster than we can. As they don't have to boot the VM.
tynanbe: We'd possibly shell out to `gleam` before and after calling the Erlang compiler from `rebar3` or `mix`, once to compile and once for the app file, unless it can safely do both of those at once.

**Comment by lpil** [comment]
Linking this here as we may want to think more about directory structure

https://www.erlang.org/doc/design_principles/applications.html#directory-structure-guidelines-for-a-development-environment
