### ISSUE TITLE
Gleam 'clean' command

### ISSUE THREAD

**Issue by zoosky** [gleam-lang/gleam#1389]
It would be handy and nice to have a `gleam clean` command.

* Remove artefacts from the build directory that gleam has generated in the past.
* more fine-grained options may be useful.

For reference, see
- https://doc.rust-lang.org/cargo/commands/cargo-clean.html
- https://www.scala-sbt.org/1.x/docs/Running.html

**Comment by lpil** [comment]
Good idea, thank you
