### ISSUE TITLE
Formatter adds superfluous _ in list pattern

### ISSUE THREAD

**Issue by dennisschroeder** [gleam-lang/gleam#1390]
Expected behavior: 

When I type something like this:

```rust
case list {
  [a, b, ..] -> Error("whatever is wrong")
}
```
After saving the file, I expect the formatter not to change the code.

Given behavior:

The formatter changes the pattern to `[a, b, .._] -> Error("whatever is wrong")`
So he adds an underscore after the three dots.

**Comment by lpil** [comment]
Thank you
