### ISSUE TITLE
Flag for selecting the target with `gleam test`, `gleam run`, etc

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1400]
```
gleam run --target javascript
```

Easy to add, just need to add the flag and pass it to the Options struct.

**Comment by vic** [comment]
I'd like to implement this one.

**Comment by lpil** [comment]
Fab, thank you

**Comment by lpil** [comment]
Mind if I pick this one up @vic ?

**Comment by vic** [comment]
no problem, go ahead. :)

**Comment by lpil** [comment]
Thank you
