### ISSUE TITLE
Confusing error message when try expression has incorrect error type compared to function annotation

### ISSUE THREAD

**Issue by silicium14** [gleam-lang/gleam#1403]
This happens when the error type of an expression used in a `try` does not match the error type of the function's annotation. In this case the compiler produces a type mismatch error and the error is reported to be on the last expression of the function. This is confusing because the last expression can have no relation at all with the `try` expression. It would be more clear to the developer if the the compiler reported the error on the `try` statement.

Gleam version: 0.18.2
Example code:
```gleam
pub fn a_function() -> Result(Bool, Nil) {
  try value = Error("a String when the function annotation says Nil")
  // There could many more lines here
  Ok(True)
}
```

Compiler error:
```
error: Type mismatch
  ┌─ /.../example_test.gleam:3:3
  │
3 │   Ok(True)
  │   ^^^^^^^^

The type of this returned value doesn't match the return type 
annotation of this function.

Expected type:

    Result(Bool, Nil)

Found type:

    Result(Bool, String)
```

**Comment by lpil** [comment]
A good suggestion, thank you.

We will need to think carefully about how we could improve this error message. The last try may be many lines back so it could be unclear to show all that code.

**Comment by lpil** [comment]
Some thoughts from the discord channel

![image](https://user-images.githubusercontent.com/6134406/147857265-4e68e94b-4294-4441-8262-ba484d6e5a19.png)

**Comment by silicium14** [comment]
The issue is when the types of the try expression and the return value are consistent with each other, making for a successfully unified Result type, but this unified Result type does not match the function return type annotation.

Example 1: the unified type is `Result(Bool, String)` but the annotation is `Result(Bool, Nil)`
```
pub fn a_function() -> Result(Bool, Nil) {
  try value = Error("a String when the function annotation says Nil")
  Ok(True)
}
```

Example 2: the unified type is `Result(a, String)` but the annotation is `Result(Nil, Nil)`
```
pub fn a_function() -> Result(Nil, Nil) {
  try _ = Ok("irrelevant")
  Error("a string")
}
```

We can see that the offending part can be the try expression, the return value, or both of them. Even when there is only one offender we can't tell which one it is after the unification of types into one Result type. Knowing this, when encountering this error we could show the entire code from the try expression. If this makes for many lines of code we could trim the content. Here is an example :
```
error: Type mismatch
   ┌─ ./src/example.gleam:59:11
   │
59 │   try _ = Ok("irrelevant")
   │           ^^^^^^^^^^^^^^^
60 |   let x = thing()
   ...
82 │   // another lines
83 │   Error("a string")
   │   ^^^^^^^^^^^^^^^^^
The type of the returned value doesn't match the return type annotation of this function.

Expected type:

    Result(Nil, Nil)

Found type:

    Result(a, String)
```
We need to look at the codespan library and see they features offer to solve this.

**Comment by silicium14** [comment]
Closing this since https://github.com/gleam-lang/gleam/pull/1433 was merged.
