### ISSUE TITLE
Case clause with multiple expressions not obvious for beginners

### ISSUE THREAD

**Issue by silicium14** [gleam-lang/gleam#1404]
As a beginner, one might try to put multiple expressions on the right side of a case clause like so
```
pub fn a_function() {
  case True {
    True ->
      let a = 1
      a + 1
    False -> 0
  }
}

```
If we try to compile this we get this error:
```
error: Syntax error
  ┌─ /.../example_test.gleam:6:9
  │
6 │       a + 1
  │         ^ I was not expecting this.

Expected one of: "->"
```
We can fix the code by using braces to turn the multiple expressions into one like so
```
pub fn a_function() {
  case True {
    True -> {
      let a = 1
      a + 1
    }
    False -> 0
  }
}
```
but I think this is not obvious for a beginner, the compiler message does not help and the Language Tour page for Case https://gleam.run/book/tour/case-expressions.html does not show an example of this. This is what I felt when I encountered this. Maybe the compiler could be changed to produce a more helpful message, but I don't know if this is feasible. We could also show this in the Language Tour page.

**Comment by lpil** [comment]
A great suggestion, thank you. Let's see if we can improve the error message.
