### ISSUE TITLE
Allow expressions for the record to update in record update syntax

### ISSUE THREAD

**Issue by silicium14** [gleam-lang/gleam#1411]
Currently the record update syntax only allows an identifier for the record to update. It could be nice if we could use an expression like so:
```
Person(..another_record.person, is_happy: True)
```

**Comment by lpil** [comment]
Definitely. Thank you very much.

**Comment by J3RN** [comment]
I should be looking the relevant parser code for this tonight for [tree-sitter-gleam](https://github.com/J3RN/tree-sitter-gleam), so I'll try to make this update while I'm there. If I don't have anything up by Monday, it's fair game for anyone else to attempt. :grin:

**Comment by lpil** [comment]
Thank you
