### ISSUE TITLE
Better error message when exidently overriding erlang modules with gleam modules

### ISSUE THREAD

**Issue by dennisschroeder** [gleam-lang/gleam#1417]
I created a `system.erl` and `system.gleam` module not taking care of the fact that gleam modules get compiled into erlang modules which causes an error and the whole process crashed.

A nice error message, saying "You can not name a gleam module same as an erlang module, would be helpful.

**Comment by TanklesXL** [comment]
Relates to/replicates #1267?

**Comment by lpil** [comment]
Ah yes! Well spotted. Thank you both!
