### ISSUE TITLE
Pipeline on right side of boolean expression creates invalid Erlang code

### ISSUE THREAD

**Issue by J3RN** [gleam-lang/gleam#1424]
A contrived example:
```gleam
fn bool_expr(x, y) {
  y || x |> negate()
}
```

Fails to compile with this error message:
```
build/dev/erlang/testapp/testapp.erl:12:7: illegal pattern
%   12|     Y orelse _pipe = X,
%     |       ^

build/dev/erlang/testapp/testapp.erl:13:23: variable '_pipe' is unbound
%   13|     gleam@bool:negate(_pipe).
%     |                       ^

build/dev/erlang/testapp/testapp.erl:11:14: Warning: variable 'Y' is unused
%   11| bool_expr(X, Y) ->
%     |              ^

error: Shell command failure

There was a problem when running the shell command `erlc`.
```

The generated Erlang looks like this:
```erlang
-spec bool_expr(boolean(), boolean()) -> boolean().
bool_expr(X, Y) ->
    Y orelse _pipe = X,
    gleam@bool:negate(_pipe).
```

Since `|>` has higher precedence than `||`, so this is parsed as `y || { x |> negate() }`. Apparently variables cannot be created in Erlang boolean expressions (or at least not in this way), and so a correct Erlang representation would be this:
```erlang
_pipe = X,
Y orelse gleam@bool:negate(_pipe).
```

**Comment by lpil** [comment]
Good find, thank you

**Comment by lpil** [comment]
I've created a test for this on main and it seems it be generating the correct code. I guess we already fixed this one

**Comment by J3RN** [comment]
Ah, looks like the Gleam compiler now generates an ALGOL-style `begin ... end` block. Interesting!
```erlang
foobar(X, Y) ->
    Y orelse begin
        _pipe = X,
        gleam@bool:negate(_pipe)
    end.
```
