### ISSUE TITLE
Releases are created with the wrong name

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1437]
![image](https://user-images.githubusercontent.com/6134406/147986330-87019bb3-7371-4943-b539-3850ef97b24a.png)

@thepratt Do you know how to resolve this one? I've not been able to work it out.

**Comment by thepratt** [comment]
I see what happened, a bad merge by me; from #769 introducing a new action type and not being brought forward to #1375.

There are 2 segments, and 1 has the fields - the other does not.

https://github.com/gleam-lang/gleam/blob/main/.github/workflows/release.yaml#L79:L88 should mirror https://github.com/gleam-lang/gleam/blob/main/.github/workflows/release.yaml#L123:L135

**Comment by thepratt** [comment]
My statement above isn't correct, we've used `github.ref` in the past (https://github.com/gleam-lang/gleam/blob/6b60d0dfbf07d6f4150c41320bade620a599d32d/.github/workflows/release.yaml#L19-L21) which seems to have `refs/tags/` prefix attached.

The old action removed the prefix: https://github.com/actions/create-release/blob/main/src/create-release.js#L17 I'll need to do the same.

**Comment by lpil** [comment]
![image](https://user-images.githubusercontent.com/6134406/147990338-4a4eb504-f073-4f8d-9184-c8cdf00bd3f3.png)

My latest release that succeeded doesn't have the prefix, I'm not sure why though. I'll close this for now and re-open if the issue returns.

Thank you

**Comment by thepratt** [comment]
Weird, feel free to assign the issue directly to me if it crops up again.

**Comment by lpil** [comment]
Ah I worked it out. I had removed the `name` property from one use of the action but not the other. I've removed it from both and now we have what we want.
