### ISSUE TITLE
Do not build with --release mode on CI in jobs that mainly run tests

### ISSUE THREAD

**Issue by michallepicki** [gleam-lang/gleam#1443]
While working on [adding rust-cache](https://github.com/gleam-lang/gleam/pull/1440) I noticed that the regular [ci workflow](https://github.com/gleam-lang/gleam/blob/main/.github/workflows/ci.yaml) is currently creating a release build, and then running tests.

So all code (and all deps as well!) are compiled twice: once in release cargo profile, and then in test profile (which is much faster, but still...). edit: Actually some deps three times, for the `clippy` linter in dev profile as well.

From what I can tell the Gleam build process is using cargo defaults, so performing a release build vs building the package for tests only differs in profile flags, like optimizations, am I right? Or is `cargo build` "testing" the creation of the executable more than just running `cargo test`?

The release build is mainly useful for the uploaded linux artifact. It could be a separate job parallel to running tests.

Alternatively I think one should be able to run `cargo build --profile test`

**Comment by michallepicki** [comment]
OK looks like the linter runs in yet another profile (`dev`)... Maybe it could use `--test` as well

**Comment by michallepicki** [comment]
I also see no big reason why clippy needs to run on all platforms. Maybe it would be best to move `clippy` to a separate job running only on ubuntu, with its own cache. Or run it in one job with rustfmt (after rustfmt).

**Comment by lpil** [comment]
All excellent suggestions, let's do these.

I think I originally built the release version on CI to have more confidence that it worked, but we've never had a problem with that so no reason to keep it around.

**Comment by michallepicki** [comment]
Building the release is used for the job that tests creating a new project, so in my PR I kept it but moved to a separate job from test

**Comment by michallepicki** [comment]
Right, then add a linux-x64 target to the release workflow. I can do that.

**Comment by michallepicki** [comment]
Oh wow the only build for linux is with statically linked musl? That explains why it's bigger than other OSes. Ignore my last comment.

**Comment by michallepicki** [comment]
> We could also us a non-release binary. Could share the same build as clippy which runs in dev mode I think

That is now how it's done in https://github.com/gleam-lang/gleam/pull/1444
