### ISSUE TITLE
Validate licences are valid SPDX

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1445]
Part of: https://github.com/erlef/build-and-packaging-wg/issues/34

Error if `gleam.toml` has a non-SPDX licence in it.

Accept non-SPDX licences from Hex as existing Hex packages may not have compliant licence configuration.

**Comment by J3RN** [comment]
I'll take a look at this. My biggest question is whether there's a cleverer way to do this other than simply making a list of all valid license IDs and checking membership. Then again, having a file/database/whatever in this repository seems heavy-handed and calling out to an API or something doubly so.
