### ISSUE TITLE
Upgrade gleam_otp

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1447]
Currently fails to compile on v0.19.0-rc1 due to using `include` rather than `include_lib` in the Erlang module.

**Comment by michallepicki** [comment]
I'll try to fix it

**Comment by lpil** [comment]
Sorry @michallepicki , I have made a bit of a mess of the imports in the build tool so this is going to be a bigger task than expecting. I'm going to have to take this one, sorry to have taken your time.

**Comment by michallepicki** [comment]
no worries, learned a bit about the Erlang preprocessor
