### ISSUE TITLE
passing command line flags after `gleam run` fails to run

### ISSUE THREAD

**Issue by TanklesXL** [gleam-lang/gleam#1457]
As per the failure message:
```
> gleam run --caps=true
error: Found argument '--caps' which wasn't expected, or isn't valid in this context

    If you tried to supply `--caps` as a value rather than a flag, use `-- --caps`

USAGE:
    gleam run [OPTIONS] [ARGUMENTS]...
```
whereas `gleam run ah --caps=true` succeeds

**Comment by lpil** [comment]
Looks like there's a clap bug ticket https://github.com/clap-rs/clap/issues/1538

**Comment by lpil** [comment]
I think we may be able to do this now, the clap issue has been closed

**Comment by TanklesXL** [comment]
Is the gleam build tool using the latest clap version?

**Comment by lpil** [comment]
No idea! Probably not
