### ISSUE TITLE
Non-ascii unicode characters don't print correctly with `io.println`

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1458]
It ruins some of the sponsors and contributors names when I print the credit list for the new release. Seems to be OK for writing to a file, though I've not thoroughly tested.

It's unclear if this is a problem with how we're booting the VM or the implementation of `io.println`.

**Comment by dch** [comment]
Hey @lpil check the VM startup state, via `io:printable_range().` (erlang style), these can be set using [emulator flags](https://www.erlang.org/doc/man/erl.html):

`env ERL_FLAGS="+pc <unicode|latin`> ..." ` ...  should do it.

Having said that, unicode poop still comes out the same here, referring to https://www.erlang.org/doc/man/io.html#format-1

```
dch@wintermute ~> env ERL_FLAGS="+pc latin1" erl
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:80:80] [ds:80:80:10] [async-threads:1] [jit] [dtrace] [sharing-preserving]

Eshell V12.1.5  (abort with ^G)
1> io:printable_range().
latin1
2> io:fwrite("~tp~n",[<<"💩">>]).
<<"©">>
ok
5>
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
^C⏎dch@wintermute ~> env ERL_FLAGS="+pc unicode" erl
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:80:80] [ds:80:80:10] [async-threads:1] [jit] [dtrace] [sharing-preserving]

Eshell V12.1.5  (abort with ^G)
1> io:fwrite("~tp~n",[<<"💩">>]).
<<"©">>
ok
```

**Comment by lpil** [comment]
I seem to recall that  `+pc unicode` didn't resolve this, but I thought what have now did. Perhaps I needed both?

One thing that makes it trickier is that REPL changes a bunch of things related to IO, so you get different results with it than without. This meant what I had previously stopped working as soon as I switch from using the REPL to running a Gleam program.

This is what we do currently: 

https://github.com/gleam-lang/gleam/blob/main/compiler-core/templates/gleam@@main.erl#L6-L7

**Comment by lpil** [comment]
Found a solution. Seems `fwrite` doesn't like unicode, but `put_chars` does. 👍
