### ISSUE TITLE
Add notes on re-building schema_capnp.rs to CONTRIBUTING.md

### ISSUE THREAD

**Issue by michallepicki** [gleam-lang/gleam#1469]
After editing `schema.capnp`, to re-build the `compiler-core/generated/schema_capnp.rs` file I uncommented code in `compiler-core/build.rs` and ran `cd compiler-core && cargo build`. This showed an error so I ran `apt install capnproto` (should a specific version be used?). The generated file referred to source with a full path specific to my computer, so I manually edited it to make it only a file name.

I was able to figure out the process but it wasn't obvious, and I think it would be best if it was documented for other contributors.

**Comment by lpil** [comment]
Oh yes, we should have this for sure.

Longer term I think I'd like to move away from capnp as the maintainence overhead is a bit high, but we can worry about that later.
