### ISSUE TITLE
Running `gleam check` twice on a new project causes it to fail the second time

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1472]
I think this happens as the dependency directories have been created but we don't write the metadata files, so when it runs the second time we attempt to load them but none are found. This results in "module not found" when importing any of them.

**Comment by michallepicki** [comment]
I could not reproduce, maybe it is dependent on the OS, or other factors?

**Comment by lpil** [comment]
Oh hmm. It must have been something else I was doing. I should has investigated more thoroughly. I'll close this and make a new one if it comes up again.

With me there's always a non-zero chance I'm using a broke unreleased version of the compiler
