### ISSUE TITLE
Clear build directory before compilation if the compiler version has changed

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1477]
Let's write the Gleam compiler version to the build directory and wipe the directory if it is absent or has a different compiler version.

When running the build command

1. Read a version file from the build directory
2. Check to see if the contents of the file checks the version of the compiler
3. Clear the build directory if it does not match

We can use the existing helper functions for file IO

**Comment by vstreame** [comment]
I'd love it give this a shot. I'll see if I can open a draft PR for this today

**Comment by lpil** [comment]
Thank you!
