### ISSUE TITLE
A `-` in the `name` field of gleam.toml will cause BEAM to crash

### ISSUE THREAD

**Issue by aslilac** [gleam-lang/gleam#1478]
If you use a hyphen in your package name in gleam.toml you'll get something like...

```
{"init terminating in do_boot",{badarith,[{erlang,'-',[gleam,test],[{error_info,#{module=>erl_erts_errors}}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,685}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,893}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,408}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({badarith,[{erlang,-,[gleam,test],[{_}]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr_list,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})
```

...as an error when trying to `gleam run`.

**Comment by lpil** [comment]
Ah yes! We should validate this. Thank you for the report.

Did you create the project and then change the name? I believe we validate the name upon project creation but not afterwards.

**Comment by aslilac** [comment]
I actually couldn't even use `gleam new` because I was trying to create it in a directory called gleam (which is reserved), so I had to off-road it a little.

Still though, yeah the name is verified by `gleam new` but not `gleam build` or `gleam run`

**Comment by lpil** [comment]
Ah that'll do it. For future reference you can do this

```shell
gleam run --name some_other_name gleam
```
