### ISSUE TITLE
Priv dir after compilation, and also for base project

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/gleam#1486]
The `priv` dir should be copied into the `build` target dir after successful compilation. Some packages place things in there during compilation ([`luaport`](https://github.com/asciibeats/luaport), for example).

If some projects need `priv` to be present in `build/dev/erlang/{package}` during compilation, all the more reason to link it in place to begin with.

The `priv` dir should also be copied into the `build` target dir for the main project itself.

**Comment by lpil** [comment]
Yes, definitely! Thank you
