### ISSUE TITLE
case expression with const clauses

### ISSUE THREAD

**Issue by massivefermion** [gleam-lang/gleam#1493]
Consider this code:

```
import gleam/io

type Kind {
  Kind(code: String)
}

type Toy {
  Toy(kind: Kind, name: String)
}

const stuffed = Kind(code: "stuffed")

const truck = Kind(code: "truck")

const car = Kind(code: "car")

const doll = Kind(code: "doll")

pub fn main() {
  let woody = Toy(kind: doll, name: "woody")

  case woody.kind {
    car -> io.debug("car")
    doll -> io.debug("doll")
    truck -> io.debug("truck")
    stuffed -> io.debug("stuffed")
  }
}
```
If you run this code, you'll get:
> <<"car">>

What happened? Let's look at the produced erlang:
```erlang
-module(gleam_toys).
-compile(no_auto_import).

-export([main/0]).
-export_type([kind/0, toy/0]).

-type kind() :: {kind, binary()}.

-type toy() :: {toy, kind(), binary()}.

-spec main() -> binary().
main() ->
    Woody = {toy, {kind, <<"doll"/utf8>>}, <<"woody"/utf8>>},
    case erlang:element(2, Woody) of
        Car ->
            gleam@io:debug(<<"car"/utf8>>);

        Doll ->
            gleam@io:debug(<<"doll"/utf8>>);

        Truck ->
            gleam@io:debug(<<"truck"/utf8>>);

        Stuffed ->
            gleam@io:debug(<<"stuffed"/utf8>>)
    end.
```
Looks like it's not matching the value with the constants we created, it's just binding it to variables with different names in each clause! The javascript output does essentially the same thing.

Of course this is easy to fix, but I think the above behavior is really counter-intuitive.

```
import gleam/io

type Kind {
  Kind(code: String)
}

type Toy {
  Toy(kind: Kind, name: String)
}

const stuffed = Kind(code: "stuffed")

const truck = Kind(code: "truck")

const car = Kind(code: "car")

const doll = Kind(code: "doll")

pub fn main() {
  let woody = Toy(kind: doll, name: "woody")

  case woody.kind {
    kind if kind==car -> io.debug("car")
    kind if kind==doll -> io.debug("doll")
    kind if kind==truck -> io.debug("truck")
    kind if kind==stuffed -> io.debug("stuffed")
  }
}
```

**Comment by lpil** [comment]
Ah yes this is a common source of confusion coming to languages with this form of pattern matching. The pattern on the left of `->` defines variables, it does not reference them. Elixir has the `^` operator to reference variables, and in Gleam we have guards.

Once we have #34 this will raise an error as all but the first clause is unreachable.

> but I think the above behavior is really counter-intuitive.

What might you suggest we change to make this clearer?

**Comment by massivefermion** [comment]
I guess in elixir it's less of a confusion because you don't really have constants, just module attributes and matching against those is pretty obvious. I did feel this could have been intentional because the syntax would have probably been really confusing for the compiler!
So...no...no suggestions, I like gleam the way it is. I just think that error you mentioned is really necessary to make things clear.

**Comment by lpil** [comment]
Elixir doesn't have which constraints sorry? Gleam should work exactly the same as Elixir except you can't repeat a variable in a pattern and there's no pin operator.

Agreed, things will be much clearer once we have that! A big improvement.

**Comment by massivefermion** [comment]
> Elixir doesn't have which constraints sorry?

not constraints, constants. Elixir does not have constants the way gleam does. So to achieve the same thing, you would use module attributes which is a much more clear syntax for the compiler.
Unless someone is trying to use variables as clauses in a match which seems to be a bad idea anyway. I just assumed constants would be fine but I understand matching over them in gleam would be indistinguishable from matching over variables so I guess that would make a bad idea in gleam too.
