### ISSUE TITLE
case expression with imported const clauses

### ISSUE THREAD

**Issue by massivefermion** [gleam-lang/gleam#1494]
Let's say the following code is inside types.gleam
```
pub type Kind {
  Kind(code: String)
}

pub type Toy {
  Toy(kind: Kind, name: String)
}

pub const stuffed = Kind(code: "stuffed")

pub const truck = Kind(code: "truck")

pub const car = Kind(code: "car")

pub const doll = Kind(code: "doll")
```
Now consider we do this in main.gleam in the same directory as types.gleam:
```
import gleam/io
import types

pub fn main() {
  let woody = types.Toy(kind: types.doll, name: "woody")

  case woody.kind {
    types.car -> io.debug("car")
    types.doll -> io.debug("doll")
    types.truck -> io.debug("truck")
    types.stuffed -> io.debug("stuffed")
  }
}
```

This would give the following error:
>error: Syntax error
   ┌─ ./src/main.gleam:8:10
   │
8│     types.car -> io.debug("car")
   │          ^^^ I'm expecting a type name here.
>Hint: Type names start with a uppercase letter, and can contain a-z, A-Z,
or 0-9.

I don't know, maybe this is not a bug and I just don't understand how the language works but this is really weird because I'm just trying to match a variable with a value! Is this a bug? If not, how should I do what I want to do?
Thanks

EDIT:
This is another method I tested:
```
import gleam/io
import types

pub fn main() {
  let woody = types.Toy(kind: types.doll, name: "woody")

  case woody.kind {
    kind if kind==types.car -> io.debug("car")
    kind if kind==types.doll -> io.debug("doll")
    kind if kind==types.truck -> io.debug("truck")
    kind if kind==types.stuffed -> io.debug("stuffed")
  }
}
```

And this is the error I got this time:
>error: Syntax error
  ┌─ ./src/main.gleam:8:25
  │
8 │     kind if kind==types.car -> io.debug("car")
  │                         ^^^ This integer is not valid for tuple access.
Hint: Only non negative integer literals like 0, or 1_000 can be used.

**Comment by lpil** [comment]
Hello!

Only patterns can be used on the left hand side of `->`, so an expression such as `types.doll` isn't permitted there.

We certainly want support for record access in guards. There's an issue for that feature here which you can subscribe to https://github.com/gleam-lang/gleam/issues/1421
