### ISSUE TITLE
Docs generation comments grouping

### ISSUE THREAD

**Issue by TanklesXL** [gleam-lang/gleam#1496]
Documentation generation places doc comments in the wrong place, as can be seen here: https://hexdocs.pm/glint/glint/flag.html#help_flag_name

**Comment by lpil** [comment]
Thank you. Could you share the source that produced the error? I've been unable to reproduce.

**Comment by TanklesXL** [comment]
You should be able to reproduce with source from this commit https://github.com/TanklesXL/glint/commit/1f7e42e0776d53e4873e8f8549a20e0df752e390

I'll be reinstalling gleam in the meantime to see if i can recreate it

**Comment by TanklesXL** [comment]
Reinstalled compiler and can no longer reproduce, closing ticket
