### ISSUE TITLE
Removing .gleam files seems to not force them to be removed from build / gleam run continues to execute them

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#1502]
1. Created a project with `gleam new module_test`
2. Wondered why the main module is not called main` or `app` and just renamed `module_test.gleam` to `main.gleam`
3. Changed code in `main.gleam`
4. Compiled and executed via `gleam run`
5. Changes I did to main.gleam where not reflected in the output of `gleam run`
6. `gleam clean` and then `gleam run` resulted in the compiler error (as expected): `exception error: undefined function module_test:main/0%`

I guess this is similar to elixir/erlang and that I can change the entry point application run by `gleam run` via changes to `gleam.toml`=>`name` but was a bit surprised that the compiler did not delete build artifacts when there are no more corresponding source code files:

`module_test.gleam` was gone (renamed to main.gleam) and gleam run still ran the compiled version out of build (I guess).

**Comment by lpil** [comment]
Ah yes, it would be good to clear outdated files.
