### ISSUE TITLE
JavaScript target return syntax error

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/gleam#1506]
Latest compiler, v0.6.0 glint.

Looks like a function ends with a case statement, which leads to a syntax error.
https://github.com/TanklesXL/glint/blob/main/src/glint/flag.gleam#L194

Perhaps putting blocks around JS `return` statements would resolve this, but not sure if it's the right approach.

However, I think that the rendering of the `case` statement is also a problem. While it's valid Gleam, it doesn't seem like the JavaScript would produce the intended result here, regardless of syntax error.

```javascript
// .../dist/glint/flag.mjs
function compute_flag(name, value, default$) {
  return if (default$ instanceof I) {
    parse_int
  } else if (default$ instanceof LI) {
    parse_int_list
  } else if (default$ instanceof F) {
    parse_float
  } else if (default$ instanceof LF) {
    parse_float_list
  } else if (default$ instanceof S) {
    parse_string
  } else if (default$ instanceof LS) {
    parse_string_list
  } else if (default$ instanceof B) {
    parse_bool
  } else {
    throwError(
      "case_no_match",
      "glint/flag",
      137,
      "compute_flag",
      "No case clause matched",
      { values: [default$] }
    );
  }(name, value);
}
```
Importing with Node.js v14.19.0 gives:
```
.../dist/glint/flag.mjs:158
  return if (default$ instanceof I) {
         ^^
Uncaught SyntaxError: Unexpected token 'if'
```

**Comment by lpil** [comment]
Spooky, I thought we handled this. Thanks for the report!

**Comment by TanklesXL** [comment]
CI run for glint https://github.com/TanklesXL/glint/actions/runs/1899336908

**Comment by tynanbe** [comment]
> Spooky, I thought we handled this. Thanks for the report!

Indeed, it seems this bug might actually be due to that function call at the end of the `case`.
