### ISSUE TITLE
JavaScript redeclaration syntax error

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/gleam#1507]
Not sure if this only happens with anonymous functions.

**Gleam**
```gleam
// ..
  let prepare_rgb = fn(strings) {
    let strings = "0" |> // ..
```
**JavaScript**
```javascript
let prepare_rgb = (strings) => {
  let strings = (() => {
```
**Error**
```
Uncaught SyntaxError: Identifier 'strings' has already been declared
```

**Comment by lpil** [comment]
Ah! Looks like we're not registering function argument names for anonymous functions.

**Comment by lpil** [comment]
I'm failing to reproduce this one @tynanbe. Do you have some code that has the issue still?

**Comment by tynanbe** [comment]
@lpil confirmed resolved.

The generated JS with Gleam just built from `main`

```javascript
let prepare_rgb = (strings) => {
  let strings$1 = (() => {
    // ..
```
