### ISSUE TITLE
Support \u escape sequence in strings

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/gleam#1509]
I haven't researched this much, but it looks like both Erlang and JavaScript support the `"\x"` escape sequence, e.g. `"\x1b[36mCYAN STRING\x1b[0m"`.

Currently, Gleam only allows `"\e"`, but Node.js doesn't seem to recognize it.

We should investigate further and document findings.

**Comment by lpil** [comment]
Sounds good, but we'll need to ensure that Erlang and JS have exactly the same behaviour for the new escape code.

**Comment by TanklesXL** [comment]
I came across `\u` while playing with JavaScript as well (via gleam_community/ansi)

**Comment by lpil** [comment]
What does that `\u` one do? Is it something that can't be expressed in Gleam today?

**Comment by maxdeviant** [comment]
> What does that `\u` one do? Is it something that can't be expressed in Gleam today?

`\u` is used for representing Unicode characters in strings without using the character literal.

> In addition, JavaScript allows using [Unicode escape sequences](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#unicode_escape_sequences) in the form of `\u0000` or `\u{000000}` in identifiers, which encode the same string value as the actual Unicode characters. For example, `你好` and `\u4f60\u597d` are the same identifiers:
>
> — [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#literals:~:text=In%20addition%2C%20JavaScript%20allows%20using%20Unicode%20escape%20sequences%20in%20the%20form%20of%20%5Cu0000%20or%20%5Cu%7B000000%7D%20in%20identifiers%2C%20which%20encode%20the%20same%20string%20value%20as%20the%20actual%20Unicode%20characters.%20For%20example%2C%20%E4%BD%A0%E5%A5%BD%20and%20%5Cu4f60%5Cu597d%20are%20the%20same%20identifiers%3A)

It can be useful in situations where the Unicode literal is hard to distinguish visually (invisible character, visually similar to another unicode character):

```gleam
let zero_width_literal = "​"

// Does not compile today:
let zero_width_unicode = "\u200b"
```

Certain editors like VS Code will also complain when you use certain Unicode literals:

<img width="272" alt="Screenshot 2023-05-27 at 10 57 22 PM" src="https://github.com/gleam-lang/gleam/assets/1486634/b45afa4c-3bd5-4ed4-8427-2efd85dc62fe">

**Comment by lpil** [comment]
So what is the design here? Is \x redunant if we have \u?

**Comment by bcpeinhardt** [comment]
Hmmm. So for starters I don't thing erlang has `\u` syntax (correct me if I'm wrong people who actually speak erlang), so the impl there isn't straightforward.
I think there's probably a solid argument to scrap all of it and favor bitstrings as the way to handle all of this. Then maybe a library could provide a set of named unicode characters to be used with `<>`
Going to retract my whack for now, as I have other things that require whacking.

**Comment by lpil** [comment]
Let's do just \u for now.

**Comment by lpil** [comment]
How about this syntax?

```rust
\u{HH}       - unicode         (U+00HH)
\u{HHHH}     - unicode         (U+HHHH)
\u{HHHHHHHH} - unicode         (U+HHHHHHHH)
```

**Comment by abs0luty** [comment]
I'm working on it right now. Doesn't seem very hard.

**Comment by abs0luty** [comment]
Implemented it the way @lpil proposed.
