### ISSUE TITLE
Lock build directory during compilation

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1515]
To avoid LSP and CLI conflicting.

We want to use an approach to locking where if the binary exits then the lock is released.

We will want to print a message to say that we are waiting to acquire a lock on the build directory if we have to wait.

This library looks useful. https://docs.rs/named-lock/0.1.1/named_lock/struct.NamedLock.html

**Comment by HarryET** [comment]
Hey, I'll look into this 👍🏼 

Looks this this might be a bit easier? https://docs.rs/dir-lock/0.3.0/dir_lock/struct.DirLock.html

**Comment by lpil** [comment]
That one has ~600 downloads while the one above has ~450,000. Seems like a safer bet to use the one above.

**Comment by HarryET** [comment]
> That one has ~600 downloads while the one above has ~450,000, and it's not clear to me if that one is cross platform. The one above seems a safer bet

Didn't see that, yeah probably safer. Can you see in the docs for that where to unlock?

**Comment by lpil** [comment]
The `lock` and `try_lock` functions return an RAII guard which will unlock the mutex once it goes out of scope.

```rust
pub fn thingy(lock: &NamedLock) {
    let _guard = lock.lock(); // locked
    // do stuff here
} // unlocks here when _guard goes out of scope
```

**Comment by HarryET** [comment]
👌🏼 even better! should only be a couple lines
