### ISSUE TITLE
report unused imports

### ISSUE THREAD

**Issue by megapctr** [gleam-lang/gleam#1516]
it would be nice if the compiler/lsp warned about unused imports, like it does for unused variables.

Perhaps `gleam format` could remove them automatically.

if it's useful, I collected some of the cases to be handled:
- unused imports
- unused named imports, `import foobar as foo`
- ~unused unqualified imports, `import foo.{Foo}`~ (this is already handled)
- unused named unqualified imports, `import foo.{Foo as Foobar} as foobar`, oh god why
- distinguish variables from imports of the same name, e.g.:
```
import gleam/http/request

fn handler(request) {
  io.println(request.path)
}
```

**Comment by lpil** [comment]
Yup, let's get this one in! I'm surprised we don't cover this with the existing usage detection.
