### ISSUE TITLE
Gleam Shell Docummentation / Friendlier Interface (igx)

### ISSUE THREAD

**Issue by ssaunderss** [gleam-lang/gleam#1521]
For those not coming from the Erlang ecosystem, Gleam's shell might be a bit confusing/intimidating at the start. I think there could be a part of `gleam.run` that walks through this a bit more (navigation, compiling/loading .erl modules, the `.` terminator etc.)

Since all Gleam files get compiled to Erlang and are dumped in `/build` it can also get a bit cumbersome to navigate to that directory and compile all of the files you want to interact with. It would be awesome to have an interface similar to Elixir's `iex` (maybe `igx`) where everything is preloaded on iex startup and is a bit more approachable to navigate.

**Comment by michallepicki** [comment]
You don't need to navigate the build directory and compile individual Erlang files yourself, there is the `gleam shell` command, it is mentioned on the website on the [Using the project page](https://gleam.run//writing-gleam/using-the-project/), in the "Run an Erlang shell" section. Currently it is still an Erlang and not a Gleam syntax shell, but does this help with your issue?

**Comment by michallepicki** [comment]
@ssaunderss Or maybe I misunderstood and you have a use-case where it is useful to load individual `.erl` files to the Gleam shell? If so, can you describe it a bit more?

**Comment by lpil** [comment]
Aye, I am surprised you need to do anything inside the `build` directory. Could you share more about what you are doing @ssaunderss ? Thanks

**Comment by ssaunderss** [comment]
Thanks for sharing @michallepicki, I didn't see that before.

The root of the problem I'm running into is accessing nested modules in the shell. I have `src/api/client.gleam` and when I run `gleam shell` I was expecting the module to be automatically loaded so I could call it using `api@client:some_func().`, but this wasn't working. The only way I could access that module in the shell was to navigate to the build directory and compile the `.erl` files by running `c(build/dev/erlang/some_api/build/client.erl)`

**Comment by michallepicki** [comment]
@ssaunderss That doesn't sound right, I just tried this on an example project (the [todomvc example](https://github.com/gleam-lang/example-todomvc)) and it worked:
```
michal@yoga:~/projects/example-todomvc$ gleam shell
  Compiling todomvc
   Compiled in 0.46s
    Running Erlang shell
Erlang/OTP 25 [RELEASE CANDIDATE 1] [erts-13.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Eshell V13.0  (abort with ^G)
1> todomvc@item:is_member({item, 1, false, <<"abc">>}, all).
true
```

**Comment by ssaunderss** [comment]
Got it, I started a fresh shell and it's working now! Probably some user error on my end haha. 

Re: the gleam syntax shell, is that currently on the roadmap? I'd definitely be interested in getting involved there 😊

**Comment by michallepicki** [comment]
@ssaunderss I didn't find a current issue (just a few old ones, [1](https://github.com/gleam-lang/gleam/issues/25) [2](https://github.com/gleam-lang/suggestions/issues/14) [3](https://github.com/gleam-lang/suggestions/issues/51)), there is an open [discussion](https://github.com/gleam-lang/gleam/discussions/1305)

**Comment by ssaunderss** [comment]
Sweet, I'll close this and move the discussion there

**Comment by lpil** [comment]
Thanks @michallepicki 💜
