### ISSUE TITLE
Compiling elli on Windows: `rebar3` was not found.

### ISSUE THREAD

**Issue by manuscrypt** [gleam-lang/gleam#1526]
after following the instructions on https://rebar3.readme.io/docs/getting-started, I can run rebar3 on a windows cmd-line.

> `rebar3 -v`
`rebar 3.18.0 on Erlang/OTP 24 Erts 12.0`

yet, after doing `gleam add gleam_elli` and running `gleam clean && gleam run`, I get this output:

```
Downloading packages
 Downloaded 7 packages in 0.13s
  Compiling gleam_stdlib
  Compiling gleam_erlang
  Compiling gleam_http
  Compiling elli
error: Program not found

The program `rebar3` was not found. Is it installed?
```

gleam.toml
```
name = "gleamagram"
version = "0.1.0"

[dependencies]
gleam_stdlib = "~> 0.20"
gleam_erlang = "~> 0.9"
gleam_http = "~> 3.0"
gleam_elli = "~> 1.1"

[dev-dependencies]
gleeunit = "~> 0.6"
```

manifest.toml
```
packages = [
  { name = "elli", version = "3.3.0", build_tools = ["rebar3"], requirements = [], otp_app = "elli", source = "hex", outer_checksum = "698B13B33D05661DB9FE7EFCBA41B84825A379CCE86E486CF6AFF9285BE0CCF8" },
  { name = "gleam_elli", version = "1.1.1", build_tools = ["gleam"], requirements = ["gleam_http", "elli", "gleam_stdlib", "gleam_otp"], otp_app = "gleam_elli", source = "hex", outer_checksum = "0F603A93E8AEB4892C89B449B12D7E71E9FB67E3BE1588C5ED28DE9293F44B14" },
  { name = "gleam_erlang", version = "0.9.2", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "gleam_erlang", source = "hex", outer_checksum = "15D0B66DA08D63C16EDDF32A70F6EB49E44DC83DB0370B7A45F1E954F8A23174" },
  { name = "gleam_http", version = "3.0.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "gleam_http", source = "hex", outer_checksum = "FB65B42C7AF4C14F1DC0AD9A3ABCE50E9486D3F8D0A42C9E52A2B8BD651739DF" },
  { name = "gleam_otp", version = "0.3.1", build_tools = ["gleam"], requirements = ["gleam_stdlib", "gleam_erlang"], otp_app = "gleam_otp", source = "hex", outer_checksum = "9F779074D0CD3760E280E24247BA17FC673D654234D56B3A8F187DC8FDE299B7" },
  { name = "gleam_stdlib", version = "0.20.0", build_tools = ["gleam"], requirements = [], otp_app = "gleam_stdlib", source = "hex", outer_checksum = "E5715F0CDCB3AB1BB73C6C35E46DA223997F680550E17CE46BC88B710E061CCE" },
  { name = "gleeunit", version = "0.6.1", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "gleeunit", source = "hex", outer_checksum = "5BF486C3E135B7F5ED8C054925FC48E5B2C79016A39F416FD8CF2E860520EE55" },
]

[requirements]
gleam_elli = "~> 1.1"
gleam_erlang = "~> 0.9"
gleam_http = "~> 3.0"
gleam_stdlib = "~> 0.20"
gleeunit = "~> 0.6"
```
That's all the information I can find, but I am happy to provide more if intstructed.

**Comment by lpil** [comment]
Thank you! I've not personally verified that rebar3 dep compilation works on Windows so we'll need to test that this works at all

**Comment by xhh** [comment]
I can confirm that the issue could be fixed by changing [this line](https://github.com/gleam-lang/gleam/blob/2adb6f921f5d08bf1fa44506ab1a8c140eefe341/compiler-core/src/build/project_compiler.rs#L259) from (`"rebar3"`)

```gleam
let status = self.io.exec("rebar3", &args, &env, Some(&project_dir))?;
```

to (`"rebar3.cmd"`)

```gleam
let status = self.io.exec("rebar3.cmd", &args, &env, Some(&project_dir))?;
```

I installed rebar3 according to the [official docs](https://rebar3.org/docs/getting-started/#windows):
![image](https://user-images.githubusercontent.com/159740/158425191-2de62aaa-008d-4d11-90c9-47455417763e.png)

so `rebar.cmd` is the recognizable executable on Windows, rather than `rebar`, which is an escript binary.
Maybe we can choose the `rebar3` exec name according to platform (OS), though I'm not sure if all Windows users of rebar3 have this setup (rebar3.cmd).

**Comment by lpil** [comment]
Wonderful, great investigative work @xhh. We can conditionally change it from rebar to rebar.cmd when running on Windows.

**Comment by lpil** [comment]
Hello! Could you give this a test with Gleam v0.21.0-rc1? Thank you

**Comment by manuscrypt** [comment]
works!

**Comment by lpil** [comment]
Excellent, thank you for your help
