### ISSUE TITLE
Add repology badge

### ISSUE THREAD

**Issue by Aloso** [gleam-lang/gleam#1529]
Add this to the README:

[![Packaging status](https://repology.org/badge/vertical-allrepos/gleam.svg)](https://repology.org/project/gleam/versions)

This is useful because users see at a glance how Gleam can be installed, and package maintainers see immediately if they have to update their package.

Code:

```md
[![Packaging status](https://repology.org/badge/vertical-allrepos/gleam.svg)](https://repology.org/project/gleam/versions)
```

**Comment by lpil** [comment]
I'm unsure about this one as these are unofficial packages largely outside of our control. Having such outdated packages displayed without this context could reflect poorly on us and give the impression Gleam is undermaintained.

**Comment by Aloso** [comment]
Well, the [installation page](https://gleam.run/getting-started/#installing-gleam) also displays some of these packages. It doesn't tell you that they're unofficial packages maintained by different people. It also doesn't tell you that they might be outdated.

Yes, showing the versions might shine a bad light on Gleam, but it's the transparent and responsible thing to do. When I install something, I want the latest version, so when the maintainers intentionally hide the fact that a package is outdated, this does not inspire trust in the project.

----

I also want to note that the packages aren't that outdated. Homebrew and Scoop are up to date. Nixpkgs (unstable), FreeBSD Ports, AUR and MacPorts are on version 1.19, so they're _1 week_ late with updating. Packages for nixpkgs stable are more outdated, but that's only logical since they're in a stable release channel. So the situation isn't nearly as bad as it looks.

**Comment by michallepicki** [comment]
I can see this URL has `vertical-allrepos` in it but to me it seems like this is a very odd default set of repositories shown (I'm not very familiar with repology).

Also I think it's worth mentioning that the Linux Gleam build that can be downloaded from GitHub releases page should work on all distros (thanks to statically linking musl libc) so there's a bit less value in repackaging for different package repositories there.

**Comment by Aloso** [comment]
@michallepicki the value in using a package manager is that packages can be updated with ease. The other benefit is that dependencies are resolved and installed automatically. Yes, gleam doesn't have dependencies, but other packages might depend on gleam.

**Comment by michallepicki** [comment]
@Aloso I didn't say there's no value in it

I personally (and I think many other Gleam users as well) use [asdf](https://github.com/asdf-vm/asdf) with [asdf-gleam](https://github.com/asdf-community/asdf-gleam)

**Comment by inoas** [comment]
I agree that we should rather offer guidance to best install gleam on common plattforms.

The packaging status could be useful to the gleam community to at one glance see and get in touch with maintainers not updating it.

> I personally (and I think many other Gleam users as well) use [asdf](https://github.com/asdf-vm/asdf) with [asdf-gleam](https://github.com/asdf-community/asdf-gleam)

Despite being an ASDF user, I didn't even know that existed, just used homebrew.

**Comment by lpil** [comment]
OK I think my take away from this is that we need to improve the installation documentation. Thanks everyone
