### ISSUE TITLE
Improve formatting of larger LSP diagnostics

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1554]
![image](https://user-images.githubusercontent.com/6134406/157773923-89645494-8035-4dba-a8ca-f56a0d876171.png)

In the discord we've discovered that vscode ruins the formatting of errors in the problems pane. It uses a lot of space, and it does not preserve indentation.

We'll have to redesign the diagnostic struct to be a bit more precise rather than having a big blob of text, but at the same time we want to keep the CLI formatting the same as it is already.

What design would enable this with minimal duplication text content when rendering errors? Ideally we would not have the same text content in multiple places as it would be easy for them to get out-of-sync.

**Comment by zhenfeng-zhu** [comment]
I think rust style is good, like this:
```
error[E0609]: no field `other` on type `Connection`
   --> compiler-cli/src/lsp.rs:190:20
    |
190 |         connection.other;
    |                    ^^^^^ unknown field
    |
    = note: available fields are: `sender`, `receiver`
```

**Comment by lpil** [comment]
It would be good to have the other information too if it can be shown nicely
