### ISSUE TITLE
Enable running on commands from dependency packages

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1558]
It would be useful to be able to run code defined in packages that our Gleam projects depend upon.

For example, a database library may define a way to perform migrations of the database scheme in some controlled way, such as how Ecto does for Elixir. The Elixir programmer would run `mix ecto.migrate` to update their database.

Currently to do this in Gleam you would call the library code from the project main function, but this has the unfortunate drawback of making it so the application code in production has to depend on any package used, even if they are only used for local development. We wish to remove this restriction.

There are 2 parts to this system.
1. Command registration
2. Command execution

# Command registration

This is how we determine that some of the dependency code is a command that can be run by the programmer.

## No registration

Nothing at all! The user instead always provides us with which module to run each time and any module with a `main` function is runnable.

## Package main functions

Any main function in a module with the same name as the package is detected as a command. It would have the same name as the package.

```gleam
// In the wibble package
// In the src/wibble.gleam module
pub fn main() {
  // ...
}
```

This matches the existing API of `gleam run` very closely and has no boilerplate.

## Project level configuration

The programmer adds configuration to their top level `gleam.toml` to define each command, similar to Elixir Mix's aliases feature.

```toml
# In the top level gleam.toml
name = "thingy"
version = "1.0.0"

[commands]
migrate = "db_library/migrate"

[dependencies]
db_library = "~> 1.0"
```

This would allow the user to define a command for any module.

A disadvantage is that programmers would need to include the same command boilerplate for each project that uses

## Package level configuration

The author of a dependency defines commands in their `gleam.toml` and any project that depends on their package would automatically have that command registered.

```toml
# In the dependency's gleam.toml
name = "db_library/migrate"
version = "1.0.0"

[commands]
migrate = "db_library/migrate" # this module would be defined in a dependency package
```

This is more convenient for the programmers depending on packages with commands.

We would need to ensure that multiple packages do not define the same command. Non unique command naming would result in build failures.
This suggests that all commands should be the name of the dependency package and then arguments are used for the subcommands. This does to some degree make the ability to define and name multiple commands seem rather redundant.

## Implicit path based registration

As suggest in https://github.com/gleam-lang/gleam/pull/1557 we could have a convention where certain module paths are exposed as commands, similar to how Elixir's Mix tasks work.

e.g. `src/task/wibble.gleam` is a command called `wibble`.

# Command execution

This is the way that the programmer invokes the command code

## Flags for `gleam run`

Curerntly `gleam run` runs the main function in the module with the same name as the current package. This could be extended to permit the running of a specified module (`gleam run -m some/module`). This is similar to Python's `python -m module` functionality.

We could also base it around package names rather than module names. `gleam run -p some_package`.

One advantage of this is that no registration is required. Any module could be run and we don't need to detect them in advance, the user tells us which one to use and we only check it has a `main` function. We could still use it with a registration system if desired.

This would also be the simplest and also most flexible API to add to the build tool.

## A new command

For example `gleam invoke commandname`

This could get confusing with `gleam run`.

## New top level commands for each dep command

If there was a command named `wibble` then `gleam wibble` would run it.

This API is nice but we would need to think carefully about how help messages work.
We would still want to show a help message if `gleam something` where `something` isn't a command.
It would be non-trivial to include command help information in our help output as it's generated by the `clap` library and it entirely static at present.

**Comment by tynanbe** [comment]
Any project exposing a `main` function will likely route everything through that.

If that's how Gleam projects are meant to run and be structured, It seems unlikely we'd gain much by introducing the extra complexity of choosing arbitrary functions.

**Comment by massivefermion** [comment]
But right now, you can't run the `main` function of a dependency, can you?
Also providing a way for the developer to register multiple commands means that they don't have to parse command line arguments themselves. If it's going to be a recurrent pattern for the build tool, it's better to make it convenient!

**Comment by massivefermion** [comment]
But right now you can't run the main function of a dependency, can you?

**Comment by Lunarmagpie** [comment]
Is it possible I could try implementing this? I want to go the `gleam -m module` route for running things.

**Comment by lpil** [comment]
Yes please! That sounds fantastic.

Changes will be need to made to the project compiler in order to expose the modules that exist so we can determine how to call them (on JavaScript we need to know the package name to determine the import path) and error if the module does not exist.
