### ISSUE TITLE
Incremental compilation

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#157]
May be good to investigate Salsa for this.

**Comment by gamebox** [comment]
Can you assign this to me @lpil just so others know it's active?

**Comment by gamebox** [comment]
Just to clarify should I drop development on this?

**Comment by gamebox** [comment]
My plan was to work on this mostly while I am on paternity leave at the end of June - july

**Comment by lpil** [comment]
I'm not sure how we should approach this feature yet so it would be good to try and do this iteratively if possible, it would make it easier to review and to make design decisions. Happy for you to take the lead though!

Also congratulations! How exciting!

**Comment by gamebox** [comment]
Thanks!  Sorry this was meant for the LSP ticket 🤦‍♂️

**Comment by gamebox** [comment]
This feature is almost working.  Might be working tonight.  Will take me a few days to get the PR together.

**Comment by gamebox** [comment]
I have a working prototype working.  Am testing current compiler invariants against the behavior I see in the new straight-line compiler powered by Salsa.

I want to structure the PRs and the release process as such:

1. PR for the Salsa system itself, completely isolated(minus a couple extra derives and functions needed)
2. PR for adding a flag to compile with the Salsa system(or env var? maybe SALSA=1)
3. PR for adding a flag to incrementally compile(maybe only with SALSA enabled?)
4. PR for running compiler tests with SALSA enabled
5. When all looks good, PR for dropping SourceTree and removing SALSA env var.

Let me know how this looks to you @lpil

**Comment by lpil** [comment]
Sounds good, though I think we may be able to skip the env var step- I don't think we need both systems at once for any reason.

**Comment by gamebox** [comment]
I would usually blue/green a feature like this, but not doing it cuts it down quite a bit

**Comment by lpil** [comment]
Yeah it's a great technique, but I don't think we have enough Gleam code in the world for it to be effective just yet, so if we can cut down the amount of work to do that would be my preference.

**Comment by lpil** [comment]
Gunna close this for more precise issues later
