### ISSUE TITLE
gleam format: comments style

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#1577]
When working on gleam/stdlib I realized a lot of function comments add an empty comment line like so:

```gleam
/// comment
///
fn (x) {
  x
}
```

... yet for a lot of functions this is missing. Should/could this be unified (first in a style guide? then in `gleam format`?)

**Comment by lpil** [comment]
For this I'd say it's more just my personal style rather than a matter of the language style. Both are acceptable and generate the same HTML in the docs

**Comment by inoas** [comment]
Personally I prefer to have it one way via `gleam format` but if-never/until that descision is made, could we setup a style guide for contributing for consistency?

If you think this does not matter, feel free to just close the issue.

**Comment by lpil** [comment]
Let's wait and see if a convention arises. I don't mind either way so much, seems very low impact currently.
