### ISSUE TITLE
Improve hint when binding or rebinding variables omitting `let`

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#1580]
Attempts of binding or rebinding variables without the `let` keyword should print a more obvious error message:

```gleam
pub fn main() {
 foo = 42
}
```

```
error: Syntax error
  ┌─ ./src/main.gleam:2:6
  │
2 │  foo = 42
  │      ^ I was not expecting this.

Expected one of: "}"
```

See: <https://johndoneth.github.io/gleam-playground/?s=A4VwRgBAZgdhC2BDAljAFASggbwFDQHsCIBeCAFgCZcBfIA%3D>

Ref: https://discord.com/channels/768594524158427167/814516237173784607/961748042481041409

**Comment by lpil** [comment]
Good idea, thank you

**Comment by Kn99HN** [comment]
Hi, can I take a crack at this?
