### ISSUE TITLE
Feature request(tooling): gleam publish --no-prompt

### ISSUE THREAD

**Issue by TanklesXL** [gleam-lang/gleam#1583]
It would be nice to have a flag for promptless publishing behaviour such as `--no-prompt` (or similar) option for the publish command to be able to run the command from within CI pipelines. 
For authentication, the command could accept input directly through its arguments or through env vars (maybe `HEXPM_USER` and `HEXPM_PASS`)

**Comment by lpil** [comment]
Great idea!

**Comment by TanklesXL** [comment]
Well that was fast 😅

**Comment by TanklesXL** [comment]
Also, this might be useful for `gleam docs publish` as well? Not sure if this was covered as I can't find the associated changes 😅

**Comment by lpil** [comment]
Sorry, I must have closed this by mistake.

**Comment by TanklesXL** [comment]
@lpil i think you can mark this completed now :)

**Comment by lpil** [comment]
Thank you
