### ISSUE TITLE
Currently bitstring segment size must be multiple of 8 when compiling to JavaScript, add compiletime check

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#1591]
```gleam
// ok
<<1:size(8)>>
<<1:size(x)>>

// not ok
<<1:size(7)>>
```
This won't catch all errors, because x could evaluate at runtime to a value that isn't a multiple of 8. However catching the literal cases when the term is explicitly an integer will still be valuable.

**Comment by massivefermion** [comment]
I don't agree. Being able to manipulate bitstrings at the bit level is actually pretty useful. After doing it in elixir and gleam, I really miss it in javascript and Rust.

**Comment by CrowdHailer** [comment]
This issue isn't saying don't implement bitstrings down to the bit level. it's saying while only bytes strings are supported (as is currently the case) For that time we should warn at compile time, rather than runtime when possible.

If there are suggestions in how to support bit level manipulation in JS it would be good to explore them.
