### ISSUE TITLE
LSP doesn't work for mix projects

### ISSUE THREAD

**Issue by edkelly303** [gleam-lang/gleam#1605]
I have a Gleam app inside an Elixir/Phoenix project, and I'm using the MixGleam project to compile the Gleam code when I start up the Elixir application.

I can compile and run the app just fine, but I get an error on this line in the Language Server in VS Code:
```gleam
import gleam/http/request
```
The error is:
```
Unknown module

Did you mean `http`?

No module has been found with the name `gleam/http/request`.
```
I think this may be something to do with the fact that in `mix.exs` I specify version 3.0.0 of the `http` package, but in the autogenerated `manifest.toml` file, it seems to specify an older version:
```{ name = "gleam_http", version = "2.1.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "gleam_http", source = "hex", outer_checksum = "C2DF02A2BD551B590D92ADA90A67CDEE60EB4BAD48B5EE10A9AB4CE180CBCE36" },```

This may well be an issue of me failing to understand how the Gleam build process and config files like `manifest.toml` work, rather than a real problem with Gleam!

**Comment by miguel-s** [comment]
Hi! The new LSP is awesome!

I ran into the same issue with `gleam_stdlib` and `gleeunit` in a Elixir/Phoenix project  with MixGleam.

### Setup

Gleam dependencies are added to `mix.exs`:

```elixir
defp deps do
  [
    ...
    {:gleam_stdlib, "~> 0.21"},
    {:gleeunit, "~> 0.6", only: [:dev, :test], runtime: false}
  ]
end
```

Gleam config files (`gleam.toml` and `manifest.toml`) are empty except for the app name.

The project compiles and runs fine both in dev and prod.

### Issue

In VSCode the Gleam LSP reports an issue with missing dependencies, for example:

```gleam
import gleam/list.{reduce}
```

Shows a red squiggle with error:

> Unknown module
>
> No module has been found with the name `gleam/list`.

### Solution

Adding all Gleam dependencies to `gleam.toml` and running the command `gleam deps download` removes all error reported in VSCode. I assume the Gleam LSP is trying to compile the project purely with the Gleam commands and is therefore missing these dependencies.

It would be great if either the Gleam LSP could handle dependencies declared in `mix.exs` or if MixGleam could handle updating the `gleam.toml` and `manifest.toml` file. Not sure which option fits better :)

**Comment by lpil** [comment]
Yup that's right. The language server doesn't know anything about mix projects and as such it doesn't know where to find the dependencies. In future versions we could teach it how to understand the mix build directory, but we wouldn't be able to get incremental compilation with every keystroke. Compilation would have to remain the responsibility of mix.

**Comment by rockwotj** [comment]
It would be great to pull out the LSP stuff into another crate so custom compilation could be hooked up. It seems right now all the LSP functionality is in the compiler CLI crate.

**Comment by lpil** [comment]
Could you expand on what do you mean by custom functionality? Thank you

**Comment by rockwotj** [comment]
Sorry I meant to say:

It would be great if the language server integration was in a separate crate so that we could "teach" it to understand where to find dependencies for the various build systems that are used with Gleam. That way there is a "plug n play" approach so you can use the `gleam` tool, mix or any use case that uses package compiler directly.

**Comment by lpil** [comment]
I think that is something we want in the main project for sure!

There will be no crates for public consumption from the Gleam compiler, it is too time costly for us to maintain a public API. Being able to make breaking API changes frequently is important for us currently.

**Comment by rockwotj** [comment]
💯 we're on the same page

**Comment by lpil** [comment]
Closing as there’s no clear way to move forward with this. If anyone has a proposal for a design please do share it, thank you
