### ISSUE TITLE
Wrong hint for Float comparisons

### ISSUE THREAD

**Issue by miguel-s** [gleam-lang/gleam#1607]
Hi, thanks for creating Gleam! I'm having a lot of fun learning it.

I believe I found an error in the compiler hint when comparing Floats with the wrong operator

> Compiling 2 files (.gleam)
> error: Type mismatch
>     ┌─ ./src/treemap.gleam:121:7
>     │
> 121 │       current_ratio >= new_ratio
>     │       ^^^^^^^^^^^^^
> 
> The >= operator expects arguments of this type:
> 
>     Int
> 
> But this argument has this type:
> 
>     Float
> 
> Hint: the >= operator can be used with Floats

To my understanding the hint should be

> Hint: the >=. operator can be used with Floats

**Comment by michallepicki** [comment]
Hi @miguel-s !
I think this has been fixed in https://github.com/gleam-lang/gleam/pull/1579
Can you take look at the changes there and confirm?

**Comment by miguel-s** [comment]
Hi @michallepicki!

Yes that seems to be the fix, looks like I missed that PR earlier.

Thanks :)

**Comment by lpil** [comment]
Thank you @miguel-s ! 💜
