### ISSUE TITLE
Anonymous functions can be parsed with labeled arguments

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#1613]
See: https://canary.discord.com/channels/768594524158427167/811254431051808778/970422823959015454 for the discussion

Example:

```gleam
fn module_substract (minuend a: Int, subtrahend b: Int) -> Int {
  a - b
}

pub fn main() {
  // Works as expected:
  module_substract(1, 1) // 0
  1 |> module_substract(subtrahend: 2) // -1
  1 |> module_substract(minuend: 2) // 1

  // Should work (or fail here):
  let anon_substract = fn (minuend a: Int, subtrahend b: Int) -> Int {
    a - b
  }
  anon_substract(subtrahend: 2, minuend: 2) // should be 0, but fails to compile
  1 |> anon_substract(subtrahend: 2) // should be -1, but fails to compile
  1 |> anon_substract(minuend: 2) // should be 1, but fails to compile
}
```

Example on [Gleam Playground](https://johndoneth.github.io/gleam-playground/?s=GYOwBAtg9gJgrgGwKYH0DOcBGaAuAnAQwGMcwAKCASxDiRBjAIC4wBJEHAGjA03wIAWdBphbscASjABaAHxsOYAN4AoMIxlhMKgL4qVAByxhQkAtTJTV6gPQ2wAdSh4A1mkbukADwNISSGCY1SFhEVF5cQhIyAEZuGKk7MAAGYJiwAB95aHhkdCxI4hwyXn4hehYAJkT7aRi0zOzQvIj%2BaKoaYSqasHrgpIBlAShEBgB3ZxdyZxNzBDAhPCQJIPVkUgIQKBB87DbSAF4TcApqWnpGMQ5uUsJykSvJGXlxZWD1Ak1tdT0PrZ3WlFirdBF0wJVuB1zoFwT00MNRlokCluJg4KRgHN3DgoGAiFAIAZKMgGllGP9doVoiD7t0wEl4SMECJkXVUejZsTsbj8YTiUhSfJNttKftTp0KrD6fZGYjMMi4loOZiuWAcXiCUSSXogA).

**Comment by lpil** [comment]
Good find!

Is that the parser is permitting an anonymous function to be defined with labels. Labels are not supported for anonymous functions so it should be a parse error.

**Comment by inoas** [comment]
Thank you @J3RN !
