### ISSUE TITLE
Better errors for auth and prompts needed

### ISSUE THREAD

**Issue by TanklesXL** [gleam-lang/gleam#1615]
Some interesting behaviour was discovered from running `gleam publish` in github actions, notably the error that when a prompt for username was given and the process tries to read from stdin: https://github.com/TanklesXL/glint/runs/6276010442?check_suite_focus=true

 It seems like since it fails to read from stdin it bails with a less-than-helpful message.

**Comment by lpil** [comment]
Thanks!

**Comment by TanklesXL** [comment]
Relevant run from gh actions: https://github.com/TanklesXL/gladvent/runs/6312252032?check_suite_focus=true#step:4:3153

**Comment by lpil** [comment]
Gunna close this as it hasn't come up since. Please feel free to reopen. Thanks!
