### ISSUE TITLE
Cannot name modules using certain keywords

### ISSUE THREAD

**Issue by sporto** [gleam-lang/gleam#1617]
I named a module `parser`. Then in a test I did

```
import parser

...
parser.whatever()
```

When running the test I got

```
Failure: undef
     Stacktrace:
       parser.whatever
```

Took me a while to figure out that this is because of the module name.
Simply renaming the module to `parserr` fixed the issue and the tests ran.

Thanks

**Comment by lpil** [comment]
Hi @sporto ! There's an issue here for helping with the UX here: https://github.com/gleam-lang/gleam/issues/1267
