### ISSUE TITLE
Formatter: Preserve spaces between comments 

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1621]
As @inoas put it:

1. Idempotency of adding and removing simple comments: If I add and remove `//` in a long test with multiple pipes the formatting I gave it is then removed, as new lines do not get comments between them. I have to manually insert `//` between two outcommented blocks of code to keep the spacing which is tedious. Also new `//` blocks try to glue to the next statement.

```gleam
  value
  |> io.debug

  value
  |> dynamic.from
  |> io.debug

  value
  |> dynamic.from
  |> dynamic.classify
  |> io.debug
```
becomes

```gleam
  // value
  // |> io.debug
  // value
  // |> dynamic.from
  // |> io.debug
  value
  |> dynamic.from
  |> dynamic.classify
  |> io.debug
```

becomes

```gleam
  value
  |> io.debug
  value
  |> dynamic.from
  |> io.debug
  value
  |> dynamic.from
  |> dynamic.classify
  |> io.debug
```

https://github.com/gleam-lang/gleam/discussions/1619#discussioncomment-2708716

**Comment by superhawk610** [comment]
I'd like to give this a try! I have a mostly working solution for now, just trying to figure out the best way to make sure indent whitespace isn't added to empty lines when they're pretty-printed. I should have a PR up soon-ish 🙂

**Comment by lpil** [comment]
Wonderful! Thank you 💜
