### ISSUE TITLE
Wrong CPU type in binary

### ISSUE THREAD

**Issue by varnerac** [gleam-lang/gleam#1626]
`asdf` fails with:

```
/Users/varnerac/.asdf/lib/commands/command-exec.bash: line 28: /Users/varnerac/.asdf/installs/gleam/0.21.0/bin/gleam: Bad CPU type in executable
/Users/varnerac/.asdf/lib/commands/command-exec.bash: line 28: /Users/varnerac/.asdf/installs/gleam/0.21.0/bin/gleam: Undefined error: 0
```

When I download the 0.21.0 macOS ARM64 release from GitHub, it looks like it's actually x86_64

```
-rwxr-xr-x@  1 varnerac  staff    14M Apr 24 08:58 gleam
-rw-r--r--@  1 varnerac  staff    14M May 11 23:51 gleam-v0.21.0-macos-arm64.tar
λ ~/Downloads/ file gleam
gleam: Mach-O 64-bit executable x86_64
```

**Comment by lpil** [comment]
Oh dear! @moogle19 do you have an idea as to what is happening here?

**Comment by CrowdHailer** [comment]
I tried to build gleam main using rust 1.60.0 today. I got an error, unfortunately I don't have it copied down, which a quick google said was mostly related to 32 vs 64 bit architecture.

I'll try add a some more context later but I though this might be related.

**Comment by varnerac** [comment]
As a work around, you can install rust via asdf, install latest rust, and build locally from a ref. That’s what I’m doing.

**Comment by moogle19** [comment]
It seems the explicit target was removed here: https://github.com/gleam-lang/gleam/commit/715c3a7b3aba90fb745d47ced66f44ebd7f15547
which resulted in both macOS jobs building x86_64 binaries (because rust seems to default to the machines target).

I just made a PR to add the `--target` back to the release job.
