### ISSUE TITLE
Some doc-strings are not included in the docs

### ISSUE THREAD

**Issue by NicklasXYZ** [gleam-lang/gleam#1633]
It seems like doc-strings are not included in the docs if both an erlang and javascript block is included after the function that is being documented. I am not sure this is actually the cause but it seems to be the case when I try to build the docs for the following module:

Docs:
https://hexdocs.pm/gleam_stats/gleam_stats/math.html

Related source code: 
https://github.com/nicklasxyz/gleam_stats/blob/v1.0.0/src/gleam_stats/math.gleam#L611-L611

**Comment by lpil** [comment]
Thank you

**Comment by NicklasXYZ** [comment]
https://github.com/gleam-lang/gleam/pull/1651 seems to have fixed the issue :)
