### ISSUE TITLE
Add built-in search to generated documentation

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1634]
### Discussed in https://github.com/gleam-lang/gleam/discussions/1342

<div type='discussions-op-text'>

<sup>Originally posted by **michaeljones** August 12, 2021</sup>
To allow for easily finding a function or type within the modules of the package.

Possible inspiration:
- Elm generated docs: https://package.elm-lang.org/packages/elm/core/latest/
- mdbook search: https://rust-lang.github.io/mdBook/
- Rust generated docs search: https://doc.rust-lang.org/std/

The particular motivation was wanting to find if there was a 'maybe' or 'optional' style decoder in the dynamic package and just wanting to type those words into a search bar instead of navigate.</div>

**Comment by NicklasXYZ** [comment]
Maybe this comment is also relevant here: https://github.com/gleam-lang/stdlib/pull/307#issuecomment-1133779774

**Comment by lpil** [comment]
Great suggestion, thanks

**Comment by lucasavila00** [comment]
There's https://lunrjs.com/ that's used in https://github.com/just-the-docs/just-the-docs

An example can be seen here https://just-the-docs.github.io/just-the-docs/

There's an API to pre-build the indexes https://lunrjs.com/guides/index_prebuilding.html

And some JS code bundled with the docs can search it https://lunrjs.com/guides/searching.html


I'll try to implement it over the next few days.

**Comment by lpil** [comment]
Looks cool! We don't be able to build the index though as the documentation generation if written in Rust and we don't have any guarentee that the user has NodeJS installed. We would need to build the index using Rust.

**Comment by lucasavila00** [comment]
Just the docs build theirs with ruby https://github.com/just-the-docs/just-the-docs/blob/main/lib/tasks/search.rake

I imagine something similar can be done in rust

**Comment by lpil** [comment]
Nice!!

**Comment by lucasavila00** [comment]
My plan is to use this JS code from just the docs as inspiration: https://github.com/just-the-docs/just-the-docs/blob/main/assets/js/just-the-docs.js#L70-L447

Lunr will be added as a vendored dependency https://github.com/just-the-docs/just-the-docs/blob/main/assets/js/vendor/lunr.min.js

The search data built like here https://github.com/just-the-docs/just-the-docs/blob/main/lib/tasks/search.rake
