### ISSUE TITLE
combined import/export generates invalid JS

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#1636]
Found this last night, unfortunately it makes gleam_javascript unusable on the current version at the moment.
```gleam
pub external fn then(a) -> b = "./ffi.js" "then"
```
generates
```js
import { then } from "./browser_ffi.js";

export { then$ };
```
I think this is something to do with keyword escaping not being handled properly.

**Comment by lpil** [comment]
Thank you
