### ISSUE TITLE
Boolean in Bit Strings

### ISSUE THREAD

**Issue by varnerac** [gleam-lang/gleam#1660]
It'd be cool to support `1 -> True` and `0 -> False` (and vice versa) in bit string patterns and values.

**Comment by varnerac** [comment]
So, I was thinking only of this case:

```
<<1:0>> -> False
<<1:1>> -> True
```

**Comment by varnerac** [comment]
Also, the syntax could probably benefit most boolean encodings. For example, if you happen to encode a boolean as a byte, you could match on `<<0:unsigned-int-size(7), my_flag:bool>>`

**Comment by lpil** [comment]
I've asked on twitter and it seems we're split between `<<0:1>>` and `<<0:8>>`. Erlang uses `<<0:8>>`

```erlang
1> erlang:term_to_binary(1).
<<131,97,1>>
2> erlang:term_to_binary(0).
<<131,97,0>>
```

**Comment by varnerac** [comment]
```
<<b1:bool-size(1)>>
<<b2:bool-size(8)>>
```

**Comment by lpil** [comment]
Let's have it default to 1 byte

**Comment by lpil** [comment]
Closing as this hasn't been asked for in a while and the alternative is easy.
