### ISSUE TITLE
Create container image for nightly release

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1661]

**Comment by aflatter** [comment]
@lpil Can you expand on what this issue is about?

**Comment by lpil** [comment]
When a release is made we create a bunch of OCI container images

https://github.com/gleam-lang/gleam/pkgs/container/gleam

https://github.com/gleam-lang/gleam/blob/main/.github/workflows/release-containers.yaml

We want to do the same for the nightly build as well

https://github.com/gleam-lang/gleam/blob/main/.github/workflows/release-nightly.yaml

**Comment by aflatter** [comment]
Ah, thanks, maybe that's something that can be done using the [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) feature of GitHub Actions.
