### ISSUE TITLE
Raise helpful custom error when a user attempts to call functions in constants

### ISSUE THREAD

**Issue by aslilac** [gleam-lang/gleam#1667]
Something like...

```gleam
const puppies = map.from_list([
    "August",
    "Dot",
    "Mady",
    "Spot",
    "Toby"
  ] |> list.map(fn (name) { #(name, Puppy(name, good: True, soft: True)) }))
```

...turns into...

<img width="566" alt="Screen Shot 2022-06-22 at 6 24 06 PM" src="https://user-images.githubusercontent.com/418348/175182048-434cef97-c4c1-4597-8791-0eec9d328a89.png">

...which is definitely not what I expected. If you turn it into a `let` and put it in a function body, it works perfectly, so I'd expect the error to be a bit more specific about the fact that this is failing because it's a `const` declaration

**Comment by lpil** [comment]
We can improve this error message for sure. Thanks for the report

**Comment by isomorpheme** [comment]
I'd like to take a shot at fixing this!

**Comment by lpil** [comment]
Brilliant, thank you

**Comment by Ian-GL** [comment]
Hi! Could I give it a try given it's been a bit since there was some activity with the issue? :)

**Comment by lpil** [comment]
Hey @Ian-GL ! That would be fantastic, thank you
