### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by varnerac** [gleam-lang/gleam#1680]
It be nice to have an option to compile code with support for coverage for testing.

**Comment by lpil** [comment]
Do you mean for the Gleam compiler's test suite?

**Comment by varnerac** [comment]
I’m not sure. In Erlang, we do cover compilation. I’d imagine this would be a pass-through option in `gleam test`, since Gleam handles the `.erl` -> `.beam`.

**Comment by lpil** [comment]
`gleam test` doesn't do anything other than run your program, there's no testing functionality built into Gleam itself. I think we'll need a framework to do some exploratory work here and then we can support them with any compiler features they need. Until then I don't think there's much we can do.
