### ISSUE TITLE
Nightly releases: use cross, add Linux aarch64, rename artifacts for consistency

### ISSUE THREAD

**Issue by michallepicki** [gleam-lang/gleam#1683]
The Github Actions release workflow has gone through a few changes. The nightly release workflow should be updated as well

**Comment by lpil** [comment]
Thank you

**Comment by lpil** [comment]
Had an attempt here https://github.com/gleam-lang/gleam/commit/eebdbec5784cd82a46296e90765ca664bf7eb5af

Let's see how it does tonight

**Comment by lpil** [comment]
Looks like it worked
