### ISSUE TITLE
Improve formatting of function calls with multi-line formattable structures as the final argument

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1685]
Today we use this format:

```gleam
some_function(
  123,
  456,
  fn(x) {
    let y = x + 1
    y
  },
)
```

We want to support this format:

```gleam
some_function(123, 456, fn(x) {
  let y = x + 1
  y
})
```

This style should also be used for function calls, case expressions, blocks, lists, and tuples.

```gleam
some_function(123, 456, another_function_being_called(
  123,
  456,
))

some_function(123, 456, #(
  "Here is a very long string which causes the formatter to wrap it",
))


some_function(123, 456, [
  "Here is a very long string which causes the formatter to wrap it",
])

some_function(123, 456, case my_var {
  True -> True
  False -> False
})

some_function(123, 456, {
  let days = 7
  days * 24 * 60 * 60
})
```

To achieve this we need to implement this printing algebra extension used by Elixir:

https://hexdocs.pm/elixir/1.10.4/Inspect.Algebra.html#next_break_fits/2

We can have 1 PR to implement the algebra and then addition PRs for each formatter change, to make it easier to deliver.

**Comment by giacomocavalieri** [comment]
What if the first line is still longer than the 80 chars limit?

```gleam
some_function(variable_with_really_long_name, whoah_this_is_getting_out_of_hand, [
  "Here is a very long string which causes the formatter to wrap it",
])
```

In this case how should the code be formatted? Should it go back to the current behaviour?

```gleam
some_function(
  variable_with_really_long_name,
  whoah_this_is_getting_out_of_hand,
  ["Here is a very long string which causes the formatter to wrap it"],
)
```

**Comment by lpil** [comment]
Yup, that's right. Basically we want to copy what Elixir does, though I think they never wrap single element lists in that case, they require 2 elements.

**Comment by giacomocavalieri** [comment]
And suppose you had the `next_break_fits`, do you already have an idea on how to achieve this look using it?

The implementation looks pretty straightforward and I may have already managed to implement this in Gleam; however, I'm trying to look at Elixir's pretty printer but it's definitely out of my league and I can't tell how they use it to pretty print functions' arguments

**Comment by lpil** [comment]
I do not, we would need to copy whatever it is that Elixir does.

**Comment by giacomocavalieri** [comment]
Ok 👍 I can give it a try and implement `next_break_fits` and also translate to Rust the basic tests that `Inspect.Algebra` defines!
This could also be a PR on its own just to update the algebra and then someone who understands Elixir better could write the actual pretty printer and/or additional tests :)
What do you think?

**Comment by lpil** [comment]
PRs to improve the algebra and their tests will be accepted!
