### ISSUE TITLE
Bug: Unqualified import + pipe + shadow == JS ReferenceError

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/gleam#1695]
Minimal repro:

```gleam
import gleam/io.{println}
pub fn main() {
  let println =
    "bugger"
    |> println
  println
}
```

https://johndoneth.github.io/gleam-playground/?s=JYWwDg9gTgLgBAcwDYFMCGID0wIDoDeYUwAdjEiQL4BQ1YArgEZwBmJcIapAFAJRz5qcOKnhFS5dgF4hwuACJG9BAhRR5s4QB8AfHHFkKsg5Oo0gA%3D%3D%3D

**Comment by lpil** [comment]
Thank you!
