### ISSUE TITLE
Type constructor `CustomType` breaks js codegen

### ISSUE THREAD

**Issue by lucasavila00** [gleam-lang/gleam#1723]
![image](https://user-images.githubusercontent.com/12750442/183792943-6aa1ab56-05ff-4fbf-90b2-41c0036037c9.png)

**Comment by lpil** [comment]
Oops haha! That's quite a funny edge case. We'll have to fix that one.

**Comment by lpil** [comment]
One solution might be to import constructors under a different name if there is a clash. Or perhaps we always import under a different name to make the code simpler.

What might we rename them to?

**Comment by lucasavila00** [comment]
Perhaps they should be imported with the Gleam prefix, for clarity.
Although I think it would still require checking for a GleamCustomType export, and changing the alias if that creates a collision.

**Comment by lpil** [comment]
Perhaps we copy modules and use a `$` prefix. Then it will never collide

```js
import { CustomType as $CustomType } from "./gleam.js";

...
```

**Comment by lucasavila00** [comment]
Yeah, that's better.
