### ISSUE TITLE
Proposal for NoReturn or Equivalent Type

### ISSUE THREAD

**Issue by dustinws** [gleam-lang/gleam#1729]
Currently the compiler is not able to detect code that will never be executed due to a function that never returns. This can be seen with the `elli.become` function.

```gleam
pub fn main() {
  elli.become(my_service, 8080);

  // This code will never execute
  io.println("Elli service running on port 8080")
}
```

With a return type such as `NoReturn` or an equivalent, the compiler can detect this code and produce either an error or a warning if it is not the last value in an expression.

```gleam
fn do_forever() -> NoReturn {
  forever_stuff()
}

fn the_answer() -> Int {
  do_forever()

  42 // This would be detected by the compiler
}
```
Some things to think about could include:
- Should this produce a compiler error or simply a warning
- What are the implications of enforcing `NoReturn` as the last value in a function body?

In an application that does not use OTP, it might be the case that you would only ever have one function with this type and that it would need to be the last thing called in the `main` function, since having it anywhere else could stop execution of further code.

These are just my thoughts, I hope someone finds this useful 😁

**Comment by lpil** [comment]
A fab suggestion, thank you. Warning when code is unreachable in this way would be very useful

**Comment by lpil** [comment]
Closing this as it hasn't come up since and it would be a type system breaking change. Stability is a focus now. Thank you
