### ISSUE TITLE
Gleam should have its own compiler or interpreter, 

### ISSUE THREAD

**Issue by Haider-Ali-Dev** [gleam-lang/gleam#1733]
The language is built great but depending on JavaScript runtimes and Erlang is not convenient. It may be useful but the problem comes when you're wanting to build systems with gleam. By systems I mean backend systems, parsers, etc. 

I want gleam to have its own compiler which would compile to system binary or an interpreter, JavaScript and Erlang can also be an option.

I want the maintainers and community to think about this and see what an incredible power would have by having its own compiler/interpreter. 

I know gleam has a compiler for JS and ER but I'm referring to a compiler/interpreter which would evaluate expressions, instead of compiling to language

**Comment by inoas** [comment]
Both an interpreter and a native compile target has been talked about but it requires a lot of developer hours.

I have no authority but right now AFAIK [this is the plan to 1.0](https://github.com/gleam-lang/gleam/milestone/24) and to my knowledge full exhaustiveness checks on guards and some LSP improvements are some major things among others to come.

While I certainly hope that we will get a native compile target and an interpreter, personally even some way to get type information during runtime, things like these require more [contributions](https://github.com/gleam-lang/gleam/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and/or a lot more [sponsoring](https://github.com/sponsors/lpil).

You can also find our commuity on [discord](https://discord.com/invite/Fm8Pwmy).

**Comment by lpil** [comment]
Hi @Haider-Ali-Dev ! Native compilation would be wonderful, I agree. There's an issue to track it here: #109
