### ISSUE TITLE
Add support for building Elixir Mix deps

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1738]
So that Gleam projects can use Elixir libraries.

Here's some useful info from tsloughter: https://github.com/Supersonido/rebar_mix/issues/29

Tagging @tynanbe. Looks like we didn't have an issue for this!

**Comment by tynanbe** [comment]
Oh, looking at PR #1484, looks like we did have issue #1408.

I've just pushed an update to my old `mix` branch after rebasing on `main` yesterday, and all seems working on initial testing.

**Comment by lpil** [comment]
Ah, well found. Thanks
