### ISSUE TITLE
Function constants cause erroneous compiler warnings

### ISSUE THREAD

**Issue by J3RN** [gleam-lang/gleam#1742]
In https://github.com/gleam-lang/gleam/pull/1664, we introduced the ability for constant values to be functions. However, when using this in practice the compiler throws warnings.

Example program:
```gleam
import gleam/io

const bar: fn(String) -> Nil = io.println

pub fn main() {
  bar("Hello from test!")
}
```

(heh, tree-sitter-gleam syntax highlighting doesn't accept this because the feature hasn't shipped yet :roll_eyes:)

Compiler output:
```
warning: Unused private constant
  ┌─ ./src/test.gleam:3:7
  │
3 │ const bar: fn(String) -> Nil = io.println
  │       ^^^ This private constant is never used.

Hint: You can safely remove it.

warning: Unused imported module
  ┌─ ./src/test.gleam:1:8
  │
1 │ import gleam/io
  │        ^^^^^^^^ This imported module is never used.

Hint: You can safely remove it.
   Compiled in 0.40s
```

A similar program where `bar` is defined inside `main` causes no warnings on compilation:
```gleam
import gleam/io

pub fn main() {
  let bar = io.println
  bar("Hello from test!")
}
```

Seems like the issue is two part:
1. The compiler doesn't recognize a constant being called as a function as a usage of the constant
2. The compiler doesn't recognize a constant referencing an external module function as usage of that module. (FWIW, a constant referencing an external module data constructor _is_ recognized as usage of that module).

**Comment by lpil** [comment]
Good find, thank you.
