### ISSUE TITLE
gleam test - recompile all files even with no changes

### ISSUE THREAD

**Issue by lissana** [gleam-lang/gleam#1746]
```
Compiled in 11.20s
```

as of now the compiler seems to recompile every module within the project, every time, some caching would be good

**Comment by lpil** [comment]
Hello! Yes, currently incremental compilation is per-package. Per-module will come in future.

May I ask how big your project is, what are the specs of your computer, and what OS you are on? How long does `gleam check` take to run? I am curious as that's the longest I've seen Gleam take to compile and was wondering if there is a compiler performance bug that you are hitting.

**Comment by lissana** [comment]
no bug at all, i am porting a real world project to test the waters, autogenerated protobuf parsers for around 1k messages

**Comment by lissana** [comment]
```
Yes, currently incremental compilation is per-package. ```
yup, noticed this and made the network parsers a separate package, not ideal, but works as a temporal solution

**Comment by lpil** [comment]
Fab, thanks for the details. How many lines of code are in the package?

**Comment by lissana** [comment]
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Gleam                           11          13241           1633         107969

**Comment by lpil** [comment]
Thank you.

Closing this to track in the existing issue. https://github.com/gleam-lang/gleam/issues/1466
