### ISSUE TITLE
Suggestion: Project-wide doc preamble

### ISSUE THREAD

**Issue by NicklasXYZ** [gleam-lang/gleam#1753]
Just a suggestion: 

Make it possible to add a project-wide documentation preamble to be included in all generated doc files.
Instead of having to add scripts and stylesheets across (possibly many) source files it could be nice to collect common elements in just one place.

For example, the scripts and stylesheets shown [here at the top](https://github.com/NicklasXYZ/gleam_stats/blob/main/src/gleam_stats/math.gleam) are included in all the source files of the project. It could be nice to just update something like that in a single place.

**Comment by lpil** [comment]
Could be useful! Do you have examples of this feature in other languages and ideas as to what the interface could be? Thanks

**Comment by NicklasXYZ** [comment]
I've mostly been using python sphinx for documentation and there it is possible to define in a [configuration file](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-templates_path) a template directory.
The files in the template directory are then used to override or extend parts of the default layout: <https://www.sphinx-doc.org/en/master/templating.html>.

**Comment by lpil** [comment]
We could perhaps put something in the `gleam.toml` file. It'd be good to get more examples of what other tools do.

**Comment by NicklasXYZ** [comment]
I found a somewhat similar discussion in the rust repo: https://github.com/rust-lang/cargo/issues/331
