### ISSUE TITLE
Adding a new dep to gleam.toml that is already in the manifest does not update the version

### ISSUE THREAD

**Issue by gavr123456789** [gleam-lang/gleam#1754]
How to reproduce:

```
> gleam new server
> gleam add gleam_http
> gleam add gleam_elli
> gleam build
Manually add gleam_otp = "0.4.0" line to gleam.toml
```
Real: Got error `gleam_otp is specified with the requirement 0.4.0, but it is locked to 0.5.0, which is incompatible`  
Expected: The gleam_otp version will change to 0.4 in the manifest.

Now to avoid this problem, you need to delete the manifest file, delete the folder.build, and then build the project again.

**Comment by lpil** [comment]
Thank you. We should unlock deps that are added to the `gleam.toml` that were not there previously before resolution.
