### ISSUE TITLE
tutorial for beginners

### ISSUE THREAD

**Issue by pguerin3** [gleam-lang/gleam#1755]
For all the non-BEAMers out here, that haven't been exposed to Erlang, Elixir, etc, where is the starting point in learning Gleam?
I read the website, and I can get gleam shell open, but I can't get anything to work in the shell.

**Comment by NicklasXYZ** [comment]
The shell that is opened is an Erlang shell, so you have to remember to use Erlang syntax to call your functions.

**Comment by NicklasXYZ** [comment]
To get started have a look here (writing gleam): https://gleam.run/documentation/

**Comment by inoas** [comment]
IMHO for a start you should treat gleam as an entirely compiled language - that it runs on JavaScript and on BEAM is another story and that you can introspect that at runtime again is another story.

When learning Java, the first thing one does ain't deciphering Java Byte Code either. At least that's how I hope Gleam accessibility can be made true, if that isn't the case. IMHO for a start you would only possibly encounter Erlang in terms of compiler requirements and then when running `io.debug` or `string.from` or when building OTP apps (aka concurrency).

IMHO just think of the Gleam shell as non existant for now, if you want to write Gleam. It is IMHO more a tool that allows (via Erlang) to introspect and debug running production applications. Personally I hope that the REPL story will improve in future.

**Comment by inoas** [comment]
One more note: If you want to get into the underpinnings of the BEAM VM I'd still go IEX/Elixir route first, because that shell is much nicer IMHO. It means you need to learn another syntax (Elixir) but I found it easier to grasp at a first glance than Erlang.

**Comment by pguerin3** [comment]
ok - so I'm hearing that I need to give up on the Gleam shell.
What about snippets for Gleam - where can I find those?

**Comment by inoas** [comment]
You don't _need_ to but it _may_ be a harsh onboarding experience going for Erlang first.
If you want to use the REPL then I'd recommend learning some Erlang :).

There are no ready-made snippets to my knowledge but you can look at some gleam code here:

- https://gleam.run/book/tour/
- https://github.com/gleam-lang/example-todomvc
- https://github.com/gleam-lang/stdlib
- https://github.com/gleam-lang/awesome-gleam

And try executing snippets here: https://johndoneth.github.io/gleam-playground/
And for further questions find our developer community in these places: https://gleam.run/community/
