### ISSUE TITLE
JS: Remainder operator

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/gleam#1784]
### Gleam
```gleam
let n = 1
n % 0
```
### JavaScript
```javascript
NaN
```

**Comment by inoas** [comment]
The same: <https://johndoneth.github.io/gleam-playground/?s=A4VwRgBAZgdhC2BDAljAFASggbwFAQIgEYIBSCABlwF8g%3D%3D%3D>

**Comment by lpil** [comment]
Oh dear! Is this the behaviour on the latest version of Gleam? We can’t refer to the playground as it is quite out of date now.

**Comment by inoas** [comment]
> Oh dear! Is this the behaviour on the latest version of Gleam? We can’t refer to the playground as it is quite out of date now.

It is in 0.23.0

```gleam
pub fn operator_remainder_test() {
  13 % 3
  |> should.equal(1)

  -13 % 3
  |> should.equal(-1)

  13 % -3
  |> should.equal(1)

  -13 % -3
  |> should.equal(-1)

  1 % 0
  |> should.equal(0)

  1 % -0
  |> should.equal(-0)
}
```

**Comment by inoas** [comment]
IMHO the operator should internally and in docs be named remainder not modulo, for details see https://github.com/gleam-lang/gleam/commit/7d1ebf20a7f96f36d63c5f182a9cfd2be1d47336#commitcomment-86422710
