### ISSUE TITLE
gleam publish - suggest to how to push tags

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#1803]
- Should read the version from gleam.toml, for the example below `0.0.1` is assumed.
- Should suggest something along this lines: 
  ```
  After commiting and puhsing changes you should publish a tag. For example call:

    git tag v0.0.1
    git push origin --tags
  
  This will source code in your documentation on hexdocs.pm available on github.
  ```

**Comment by inoas** [comment]
I also wonder if it should warn about non commited workspace... not sure if it so far requires git, but if there is a .git and git status doesnt return empty then gleam publish published the current local version that may not be committed (and thus if you tag it might not pick up those changes sin the tag? - not a git ultra pro here sorry

**Comment by inoas** [comment]
@hayleigh-dot-dev noted AFAIU that

1. check if there are uncommited local changes, if there are abort the publishing.
2. elm does not allow publishing if there is no matching tag (we should check for .git and if .git is given, do the same)

**Comment by lpil** [comment]
Sounds good!

Let's print a message if the user has specified repo config that we can generate URLs for, and make the message specific to the git host used.

Let's not enforce the creation of a tag or a clean working directory.
