### ISSUE TITLE
documentation generator: sidebar should be collapsable

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#1805]
on low-width screens this will improve ergonomics a lot when reading doc and example source code inlined in the docs.

**Comment by lpil** [comment]
It is on narrow displays :)

![image](https://user-images.githubusercontent.com/6134406/197268142-f4d30c01-c287-4615-9ea7-c2766dba7952.png)

**Comment by inoas** [comment]
I meant _high width_ displays not _low width_... which is not the same :D

On small windows we could still save a lot on the horizontal space by having no horizontal margins, borders and just a small horizontal padding and probably use a tad smaller font.

If I can find out how to compile locally I can take a look how to improve this for both wide screen and small screens.

For wide screens the horizontal scrolling inside the source code box is just bad IMHO and we should take more horizontal space, maybe add another horizontal break-point?

**Comment by lpil** [comment]
There is no size at which the sidebar makes the page layout smaller. The sidebar collapses before the page is of a width that would mean both the sidebar and the content cannot fit.
