### ISSUE TITLE
documentation generator should pickup CHANGELOG, NOTICE and LICENSE

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#1807]
documentation generator should pickup CHANGELOG.md or CHANGELOG, NOTICE.md or NOTICE and LICENSE.md or LICENSE and put them on the sidebar below README.

Order could be:

- Readme
- Changelog (if exists)
- License (if exists)
- Notice (if exists)

**Comment by lpil** [comment]
I don't think we should automatically add pages but the user can add them themselves using the `documentation.pages` config

https://gleam.run/writing-gleam/gleam-toml/

**Comment by inoas** [comment]
I didn't know about it. Sorry.

I'd prefer if gleam new added a [documentation] block that links the generated README so that nothing is magic then, because right not it automagically adds the README.md. If it was done through the generator, people would know about it.

Does it support automatically generating html out of md?

```
pages = [
  { title = "My Page", path = "my-page.html", source = "./path/to/my-page.md" },
]
```

Can it also create links to text documents? Like:

`{ title = "License", path = "license.txt", source = "LICENSE" },`

How would I generate the documentation locally to test/check before publishing instead of asking here?

**Comment by lpil** [comment]
`gleam docs build` can be used locally to check out what would be published
