### ISSUE TITLE
Reference error

### ISSUE THREAD

**Issue by rockwotj** [gleam-lang/gleam#1831]
I was playing around with some pathological edge cases in gleam, and I'm fairly certain this should be an error:

```gleam
pub fn main() {
  let x = 3;
  x + let a = 5;
  x + a
}
```

[Playground](https://johndoneth.github.io/gleam-playground/?s=MYewdgzgLgBAhjAvDARHFAoUlYCMmq6bbQzAErDHily7nIDacANDLm8ALpA%3D)

Interestingly enough if you do something like this:

```gleam
pub fn main() {
  let x = 3;
  let y = x + let a = 5;
  x + a
}
```

then gleam gives a nice error message:

```
error: Unknown variable
  ┌─ ./src/main.gleam:4:7
  │
4 │   x + a
  │       ^ did you mean `x`?

The name `a` is not in scope here.
```

Probably low priority because nobody should write code like this :)

**Comment by lpil** [comment]
Sounds good, let's forbid that.

Should the rule be that let only assigns directly within a `{...}` block.

**Comment by rockwotj** [comment]
> Should the rule be that let only assigns directly within a {...} block.

Are you suggesting forbidding let/assert expressions outside of the top level of a Sequence?

**Comment by lpil** [comment]
They would be permitted but they would effectively be in the own scope that immediately closes after them, and as such you cannot use the variable they define anywhere.

**Comment by lpil** [comment]
Not 100% sure on the right behaviour here. Have made a poll https://twitter.com/louispilfold/status/1634521544457158658
