### ISSUE TITLE
Javascript nested sequences 

### ISSUE THREAD

**Issue by rockwotj** [gleam-lang/gleam#1834]
I believe nested sequences within JavaScript is broken.

Take this example program (that granted is doing naughty things ignoring the `Result`).

```gleam
pub fn main() -> Result(Int, Nil) {
  let x = 1;
  {
    try b = Error(Nil);
    b
  }
  Ok(x)
}
```

The result of `main` in Erlang is `Ok(1)` but `Error(Nil)` in JavaScript.

Output Erlang:

```erlang
-module(main).
-compile(no_auto_import).

-export([main/0]).

-spec main() -> {ok, integer()} | {error, nil}.
main() ->
    X = 1,
    case {error, nil} of
        {error, _try} -> {error, _try};
        {ok, B} ->
            B
    end,
    {ok, X}.
```

Output JavaScript:

```javascript
import { Ok, Error } from "./gleam.mjs";

export function main() {
  let x = 1;
  let $ = new Error(undefined);
  if (!$.isOk()) return $;
  let b = $[0];

  b;
  return new Ok(x);
}
```

I think sequences in JS need to be unconditionally wrapped in a lambda due to `try`. It maybe that if there are no try statements then the lambda may be omitted, but that seems unnecessary.

**Comment by lpil** [comment]
We are supposed to wrap sequences in a function.

I think the budget is that we are not doing the same wrapping for try, which we should. Should be an easy fix!

**Comment by rockwotj** [comment]
Maybe I am missing something, but this doesn't seem like an easy fix.

Here's a diff that I think should fix things:

```diff
diff --git a/compiler-core/src/javascript/expression.rs b/compiler-core/src/javascript/expression.rs
index 34bbf0b3..169efe8f 100644
--- a/compiler-core/src/javascript/expression.rs
+++ b/compiler-core/src/javascript/expression.rs
@@ -375,7 +375,14 @@ impl<'module> Generator<'module> {
         let mut documents = Vec::with_capacity(count * 3);
         for (i, expression) in expressions.iter().enumerate() {
             if i + 1 < count {
-                documents.push(self.not_in_tail_position(|gen| gen.expression(expression))?);
+                documents.push(self.not_in_tail_position(|gen| {
+                    // Nested sequences still need to wrapped in iife for `try`.
+                    if matches!(expression, TypedExpr::Sequence { .. } | TypedExpr::Pipeline { .. }) {
+                        gen.immediately_involked_function_expression(expression)
+                    } else {
+                        gen.expression(expression)
+                    }
+                })?);
                 if !matches!(
                     expression,
                     TypedExpr::Assignment { .. } | TypedExpr::Case { .. }
diff --git a/compiler-core/src/javascript/tests/try_.rs b/compiler-core/src/javascript/tests/try_.rs
index ea12a304..1315fae6 100644
--- a/compiler-core/src/javascript/tests/try_.rs
+++ b/compiler-core/src/javascript/tests/try_.rs
@@ -70,3 +70,19 @@ fn assert_in_block() {
 }"#,
     )
 }
+
+#[test]
+fn in_anonymous_block() {
+    assert_js!(
+        r#"pub fn main(x) {
+  let y = 1
+  {
+    try z = x
+    Ok(z + 1)
+  }
+  let y = y + 1
+  let y = y + 1
+  y
+}"#,
+    )
+}
```

However the AST is not really what I expect. Here's roughly the AST for the test I wrote.

```
Seq {
  Assignment { y = 1 }
  Seq {
    Try { z = x }
    Seq {
      Call { Ok constructor with z + 1 }
      Seq {
        Assignment { y += 1 }
        Seq {
          Assignment { y += 1 }
          Var { y }
        }
      }
    }
  }
}
```

This AST makes it very tricky to actually wrap the Seq in the original program within an IIFE. You don't want to blindly wrap all `try` statements because we want the early return if there is no nested sequences.

**Comment by rockwotj** [comment]
For the record I expected an AST like:

```
Seq {
  Assignment { y = 1 }
  Seq {
    Try { z = x }
    Call { Ok constructor with z + 1 }
  }
  Assignment { y += 1 }
  Assignment { y += 1 }
  Var { y }
}
```

Which I believe would make my above patch work.

**Comment by lpil** [comment]
I think that is caused by the bug that causes #1707 . The way that `use` is parsed doesn't have that issue, we'll migrate `try` to work the same way.

**Comment by rockwotj** [comment]
Sorry the AST was a rough example to demonstrate the nested sequences, it's indeed not quite right. I see the issue and why the AST is currently parsed like that.

I think the AST should match the user intent and the erlang codegen path needs to handle `try` correctly, but it sounds like from the other issue `try` may be going away or turning into syntax sugar for `use`?

**Comment by lpil** [comment]
`try` will stay (or at least, we've not decided to remove it yet) but the AST design used for `try` will be changed to match the one for `use`.

**Comment by lpil** [comment]
Looking more closely at your patch above, I'm not sure why that wouldn't be what we're after? I've just applied it and run the tests and they all pass. Is there an edge case I'm missing?

**Comment by rockwotj** [comment]
> Looking more closely at your patch above, I'm not sure why that wouldn't be what we're after? I've just applied it and run the tests and they all pass. Is there an edge case I'm missing? Sorry I think I'm getting a bit confused

No my apologies I've confused myself! I think I was confused about how the `Try` AST node works and why it needs wrapping (I didn't realize `Try` had a continuation node in `then`, which is what you were saying in https://github.com/gleam-lang/gleam/issues/1834#issuecomment-1311912381)

**Comment by lpil** [comment]
Bril, thanks. I agree the compiler can be rather confusing!
