### ISSUE TITLE
Allow `gleam run` to specify module and function

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#1844]
## suggested cli interface

- `gleam run benchmark` runs `src/benchmark.gleam`'s `main` function.
- `gleam run benchmark runner` runs `src/benchmark.gleam`s `runner` function.
- `gleam run foo/bar quux` runs `src/foo/bar.gleam`'s `quux` function.
- `gleam run foo/bar quux batz kek` runs `src/foo/bar.gleam`'s `quux` function with `args[0]` `"batz"` and `args[1]` `"kek"`.
- `gleam run benchmark main "hello world"` runs `src/benchmark.gleam`s `main` function with arg "hello word"

### targets

- Should imply `--target erlang`.
- Should be able to specify `--target javascript` before module and function names, so other args can be passed into the called function, aka `gleam run --target javascript foo/bar quux batz kek`.

### why?

`erl -pa ./build/dev/erlang/*/ebin -noshell -eval 'gleam@@main:run(my_benchmark)'` is not very newbie friendly

**Comment by lpil** [comment]
Good idea, though we have an issue for tracking this here: https://github.com/gleam-lang/gleam/issues/1558

**Comment by inoas** [comment]
Oh, sorry, I searched the issues and could not find it.

**Comment by lpil** [comment]
It was a tricky one to find! I agree!
