### ISSUE TITLE
Update CI to upgrade deprecated commands

### ISSUE THREAD

**Issue by Ian-GL** [gleam-lang/gleam#1847]
I noticed there are warnings in the recent Actions runs given that there was a change on the command to set variables. The guide to upgrade is [this one](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) and it seems like a simple change.

I would like to take up this task. Opened an issue first to discuss the approach. My plan would be to first change the nightly workflow given it is less complex and if it works without issues, then make a follow up PR with the rest of the workflows.

**Comment by lpil** [comment]
Fab, thank you!

**Comment by lpil** [comment]
Thank you!
