### ISSUE TITLE
Erlang build dir bugs

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/gleam#1859]
Commit https://github.com/gleam-lang/gleam/commit/915a4025e6733dde7a68a2719a9e3d1b091d431d breaks compilation and tests for the Erlang target.

When trying to compile, I get

```
INFO compile{package=rad}: Performing code generation
 INFO compile{package=rad}: skipping_entrypoint_generation
 INFO compile{package=rad}: copying_native_source_files
DEBUG compile{package=rad}: linking_priv_to_build
DEBUG compile{package=rad}: symlinking src="build/packages/rad/priv" dest="build/dev/erlang/rad/priv"
DEBUG removing_failed_build package=rad
DEBUG deleting_directory path="build/dev/erlang/rad"
DEBUG directory_did_not_exist_for_deletion path="build/dev/erlang/rad"
ERROR Failed error=FileIo { kind: File, action: Link, path: "build/dev/erlang/rad/priv", err: Some("No such file or directory (os error 2)") }
error: File IO failure

An error occurred while trying to link this file:

    build/dev/erlang/rad/priv

The error message from the file IO library was:

    No such file or directory (os error 2)
```

I think commit https://github.com/gleam-lang/gleam/commit/c0b9efcb049b1308e693db822fc06a5c0896c9d9 partially fixes `gleam test`.

With current `main`, after `gleam build` fails, if I copy `build/dev/erlang/rad` from my `rad` repo (compilation succeeds when it's the main project rather than a dep), testing succeeds if I then run `gleam test`; however, if I run `gleam build` and then `gleam test`, 69/70 of argamak's test assertions fail for the Erlang target (all succeed for JS).

**Comment by lpil** [comment]
Thanks. Could you share the code that produces the issue please so I can debug?

**Comment by tynanbe** [comment]
https://github.com/tynanbe/argamak/tree/gleam_v0.25

**Comment by lpil** [comment]
I think I have fixed this on main, could you give it a test for me please? 🙏

**Comment by tynanbe** [comment]
I think it's good.
After `gleam clean` I don't see the errors anymore with latest `main`.
Thank you!

**Comment by lpil** [comment]
Brill, thank you!
