### ISSUE TITLE
Disallow declaring functions with unlabelled arguments after labelled arguments

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1860]
https://github.com/lpil/nerf/pull/6/files#r1028573265

```gleam
fn wibble(
  label_a a: Int
  b: Int
) {
  todo
}
```

The compiler should probably reject this as it's not possible to use the label `label_a` as the following argument has no label. I'll open an issue for that in the compiler repo.

**Comment by Ian-GL** [comment]
Could I take this one?

I was exploring a bit and I see the function args are parsed using `Paser::series_of`, which (if I'm understanding correctly), will parse each arg independently of what came before. So for this I think we'll need to look at the previous arg all the time so in case it is a labeled one then we throw the error.

Is that possible using `Paser::series_of` or would it be best to look at another way to reduce it and keep the acc of previous arguments? This would also be useful for #1874 to raise on duplicate arg names.

**Comment by lpil** [comment]
This would be best handled in the type checker, it'll be easier there than in the parser and it means that we'll still be able to type check the rest of the module.

As much as possible the parser should not perform validation that could be done later in the process as we'll get more useful information the later we wait.

**Comment by lpil** [comment]
Do you still wish to work on this @Ian-GL ?

**Comment by Ian-GL** [comment]
Hey @lpil , thanks for asking. I'd like to but I haven't gotten time to dig into how the type checker works and I'm not sure if I'll have time soon to really focus on it. Wouldn't like to be a blocker.
