### ISSUE TITLE
boilerplate reduction: library/app specific perlude

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#1871]
I am having a lot of import statements in some modules and it would be handy if I could specify app/library specific perlude ontop of gleam's standard perlude.

The perlude could be a file named `perlude.gleam` in the lib/app root and could only allow/run import statements (any other gleam code is being ignored).

**Comment by lpil** [comment]
Hi @inoas , does https://github.com/gleam-lang/gleam/issues/614 cover this?

**Comment by inoas** [comment]
They are not automatically imported. They would be in some `.gleam` or `.toml` file explicltly listed.

I don't yet grasp how https://github.com/gleam-lang/gleam/issues/614 can help?
It seems that it would bridge, wouldn't it? That could be nice to make library types be first class in the application/library one is building?

What would help is the LSP auto adding/complemeting import statements if a given type of the project is typed out. That way the verbosity is kept but it would not hurt. The LSP could even go so far and remove import statements and/or parts of them that are not used because it knows about if they are required as far as I understand?

Would that kind of automation via LSP be possible/desired?
If yes then there is no need for this issue here (and I'd open one for the LSP instead?)

**Comment by lpil** [comment]
I'm sorry, I don't understand what us being proposed here. What should happen if you have a `prelude.gleam` file with those contents?

**Comment by inoas** [comment]
They could be prepended to any module within the given gleam library/app?

**Comment by lpil** [comment]
Sorry, all imports in Gleam are to be explicit.

**Comment by inoas** [comment]
What about this alternate idea?

> What would help is the LSP auto adding/complemeting import statements if a given type of the project is typed out [edit: or a given module.function is typed out].
> That way the verbosity is kept but it would not hurt. The LSP could even go so far and remove import statements and/or parts of them that are not used because it knows about if they are required as far as I understand?
>
> Would that kind of automation via LSP be possible/desired?
> If yes then there is no need for this issue here (and I'd open one for the LSP instead?)

**Comment by lpil** [comment]
Yes totally, we want module autocompletion #1540
