### ISSUE TITLE
'gleam new' shouldn't create git repository if already in one

### ISSUE THREAD

**Issue by rlipscombe** [gleam-lang/gleam#1875]
If I run `gleam new foo` while I'm already in a git work tree, it shouldn't run "git init".

**Comment by lpil** [comment]
Sounds good!

**Comment by rlipscombe** [comment]
More generally, I wonder whether this behaviour should be controlled by an option (and default to off) along with the `.github/` creation.

**Comment by lpil** [comment]
Sounds good also 👍

**Comment by bookshelfdave** [comment]
The `git init` seems to happen after the root is created, are you referring to checking parent directories recursively for a `.git` dir?
https://github.com/gleam-lang/gleam/blob/67def5b4a72b104a32f2a45c13f2cbf6d1109881/compiler-cli/src/new.rs#L57-L62

**Comment by lpil** [comment]
Yup that's what we would do

**Comment by rlipscombe** [comment]
It's what "cargo new" does: https://github.com/rust-lang/cargo/blob/master/src/cargo/ops/cargo_new.rs#L752 and https://github.com/rust-lang/cargo/blob/1023fa5c1ed51602933f7b938d7fde2e7598767c/src/cargo/util/vcs.rs#L11

**Comment by rlipscombe** [comment]
Gleam just seems to run "git init", so "git rev-parse --is-inside-work-tree" would seem like the simplest comparable thing to do?

**Comment by lpil** [comment]
Sounds good to me.

**Comment by bookshelfdave** [comment]
> More generally, I wonder whether this behaviour should be controlled by an option (and default to off) along with another option for the `.github/` creation.

any thoughts on what these options should be named?
