### ISSUE TITLE
Support creating a new Gleam project in the current directory with `gleam new .`

### ISSUE THREAD

**Issue by samueldurantes** [gleam-lang/gleam#1879]
Apparently not is possible to create a Gleam project in your current directory.

Example:

![image](https://user-images.githubusercontent.com/44513615/205461410-caff5c07-57a5-49d1-982d-73b5407bfd61.png)

**Comment by lpil** [comment]
Sounds good to me 👍

**Comment by pascalwengerter** [comment]
@lpil would you prefer `gleam new .` or `gleam init` (according to how Rust handles it IIRC) or potentially both/aliasing it somehow?

**Comment by lpil** [comment]
`gleam new .` please 🙏

**Comment by abs0luty** [comment]
I can work on this one. ❤
