### ISSUE TITLE
Precompiled Windows binary

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#188]

**Comment by EskiMag** [comment]
Aren't we able to build Windows binary in a similar way as the MacOS and Linux ones?

**Comment by lpil** [comment]
I'm sure we can do that.

I've not started this as I don't have a windows machine to test with and the tests are currently failing for Windows on CI.

**Comment by thehabbos007** [comment]
After #299 letting windows compile it seems there might be problems with importing with slashes, so `import gleam/list` seems to fail on windows currently. Will look further into this

**Comment by lpil** [comment]
Thank you. Would you like to open an issue to track this @thehabbos007 ?

**Comment by thehabbos007** [comment]
> 
> 
> Thank you. Would you like to open an issue to track this @thehabbos007 ?

I'll open an issue when i can confirm it's a problem :)

**Comment by lpil** [comment]
Thank you
