### ISSUE TITLE
Formatter: Large numbers could be autoformatted to use `_` for improved community code consistency.

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#1883]
So `54678023` => `54_678_023` and `54678023.2231` => `54_678_023.2231`?

**Comment by lpil** [comment]
Sounds good 👍

**Comment by inoas** [comment]
1. FP does not get underscored (not sure if it is valid even).
2. Leave hex, octa and binary ints as the programmer styled them, as discussed
