### ISSUE TITLE
Disallow valueless list append expression 

### ISSUE THREAD

**Issue by wezm** [gleam-lang/gleam#1890]
I wrote these two examples while working on my advent of code and in each case was surprised they compiled without error or warning.

Says it returns list but compiles with empty body:

```gleam
pub type Trace {
  Trace(x: Int, cycles: Int)
}

fn inflate(out: List(Trace), this: #(Trace, Trace)) -> List(Trace) {

}
```

`..` operator is applied to nothing:

```gleam
  case instruction {
    "noop" -> [Trace(head.x, head.cycles + 1), ..trace]
    "addx " <> amount -> [Trace(head.x + parse_int(amount), head.cycles + 2), ..]
  }
```

**Comment by lpil** [comment]
That code emits a `todo` warning for the empty function body. Did it not for you?

**Comment by wezm** [comment]
> First: That code should emit a `todo` warning for the empty function body. Did it not for you?

You're right it does. I probably had a bunch of warnings at the time and missed it. My expectation is that it would be an error though, reserving the warning for when `todo` is explicitly present,

> Second: That looks valid to me. Which bit do you mean?

This line has a bug:

```gleam
    "addx " <> amount -> [Trace(head.x + parse_int(amount), head.cycles + 2), ..]
```

It should have been:

```gleam
    "addx " <> amount -> [Trace(head.x + parse_int(amount), head.cycles + 2), ..rest]
```

The use of `..` on the right hand side (not a pattern context in my mind) with nothing to its right was my mistake, but I was also surprised that it compiled.

**Comment by lpil** [comment]
Oh yes! I see now. Let's get this fixed.
