### ISSUE TITLE
Default rebar3 version from `gleam new` is wrong

### ISSUE THREAD

**Issue by RosieBaish** [gleam-lang/gleam#1894]
Apologies in advance if I'm messing this up - I'm new to both Gleam and Erlang!

The default .github/workflow provided by `gleam new` fails at the step "Run erlef/setup-beam@v1.15.0"
`Error: Requested rebar3 version (25.1) not found in version list (should you be using option 'version-type': 'strict'?)`

Based on some research, it appears that the latest version of rebar3 is [3.20](https://github.com/erlang/rebar3/releases/tag/3.20.0)

I think the regression was introduced [here](https://github.com/gleam-lang/gleam/commit/c868e70784516d8e065ab9e51064285feea7f6ef)
when the 25.1 was erroneously copied from the lines above.

I changed it to `          rebar3-version: "3.20"` in my config and that worked.

I'm happy to make a PR fixing it, but I don't know what the correct version number wants to be (see earlier point about having a total of 90 minutes experience with any of this tech stack)

Steps to reproduce:

`gleam new test_repo`
`git commit -am "Initial Commit"`
`git remote add origin git@github.com:<whatever you like>`
`git push -u origin main`

Expected result:
The hello world test should run

Actual result:
Github action fails to run with the above error

**Comment by inoas** [comment]
@RosieBaish AFAIU this is not you doing anything wrong but the problem is exactly how you describe it, thanks for digging in so deep. `#1895` should fix it.
