### ISSUE TITLE
JavaScript target uses 32-bit multiplication

### ISSUE THREAD

**Issue by brettkolodny** [gleam-lang/gleam#1898]
The following gleam code
```gleam
4294967295 * -1
```
compiles to:
```js
Math.imul(4294967295, -1)
```
Since `Math.imul` performs 32-bit multiplication this will lead to overflow, and is divergent behavior from the Erlang target which will have no overflow at the same values.

**Comment by lpil** [comment]
Good find, thank you. I forget why we use `imul`, I should have made better notes.

Does |0 cast to a 32 bit int? I thought it was 64

**Comment by lpil** [comment]
Let's remove all the `|0` and `imul` stuff.
