### ISSUE TITLE
Surprising parsing of negative numbers

### ISSUE THREAD

**Issue by jiegillet** [gleam-lang/gleam#1926]
```
$ gleam --version
gleam 0.25.0
```

I'm not too sure if I should call this one a bug, but it's at least a surprising behavior. In doubt, I'm opening this issue.

`x-1` is parsed as `x` minus one, but `x -1` (with a space before the minus sign) is parsed as `{ x } { -1 }`, which could potentially go unnoticed and cause bugs.

**Comment by lpil** [comment]
Hello! Thank you for the report.

This is the design of the parser. Using the formatter, the LSP, or type checking the program will show the issue here so I think this is clear enough currently.
