### ISSUE TITLE
Incomplete type inference

### ISSUE THREAD

**Issue by jiegillet** [gleam-lang/gleam#1928]
```
$ gleam --version
gleam 0.25.0
```

This one might be less of a bug than a missing feature, but I was surprised by it, so in doubt I'm opening this issue.

I expected the following code to compile (like it would in Elm)
```gleam
type Bar { Bar(bar: Int) }

fn foo() {
  let x = Bar(1)
  [fn (b) { b.bar }]
  |> List.map(fn (unbar) { unbar(x)})
}
```
but I got
```
14 │   [fn (b) { b.bar }]
   │             ^ I don't know what type this is

In order to access a record field we need to know what type it is,
but I can't tell the type here. Try adding type annotations to your
function and try again.
```
Adding type annotations does fix the problem, but I thought the type could be inferred from its use in `unbar(x)`.

**Comment by lpil** [comment]
Unfortunately this is undecidable for the type checking algorithm we use. Given `[fn (b) { b.bar }]` there is no way to know what `b` is, hence the error message saying we can't tell.
