### ISSUE TITLE
Ints do not get formatted in patterns and constants

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1934]
```gleam
assert 123456789876543 = ...
```
```gleam
const x = 123456789876543
```

Would you like to take this one @inoas ?

**Comment by inoas** [comment]
I can at least give it a try, yes!

**Comment by inoas** [comment]
If I am not mistaken `const foo = 1.` does not get reformatted correctly neither?

**Comment by lpil** [comment]
AH yes, floats also

**Comment by inoas** [comment]
Also for patterns, I hope I didn't miss anything else. I am a but confused that there are different places for this.

**Comment by lpil** [comment]
They are different things.
