### ISSUE TITLE
Windows - CI dies on unescaped backslashes in generated tests

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#1939]
Problem: https://github.com/gleam-lang/gleam/actions/runs/3821363367/jobs/6500437012

For instance:
```rust
    insta::assert_snapshot!(
        "variable_or_module",
        output,
        "./cases/variable_or_module"
    );
```

... from `/test-package-compiler/src/generated_tests.rs` inserts backslashes as a path (as native on windows) and then these strings are treated not at literals but the backslashes are treated as escape chars, the path is created somewhere down from here:
https://github.com/gleam-lang/gleam/blob/db0e50b0e05a9376df8208d7ca0aa383f5c6df02/test-package-compiler/build.rs#L14-L16

**Comment by lpil** [comment]
thanks!
