### ISSUE TITLE
formatter: floats with only zeros as fp part such as 1.00, 1.000 should be shorted to one fp zero

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#1940]
Let me know that/if you want this, then once I have some time I will take a look at this.

**Comment by inoas** [comment]
> juliaailuj: clang-format doesn't seem to trim trailing zeros, Prettier does
https://discord.com/channels/768594524158427167/768594524158427170/1059480877316448386

**Comment by lpil** [comment]
Sounds good

**Comment by inoas** [comment]
#2009 should close this, if it doesn't I will reopen this issue.
