### ISSUE TITLE
InMemoryFileSystem uses inconsistent paths during compilation

### ISSUE THREAD

**Issue by greenfork** [gleam-lang/gleam#1948]
Here is a bare-bone Gleam project list of files after compilation:
```
./src/temp.gleam
build/dev/erlang/gleam_version
build/dev/erlang/temp/_gleam_artefacts/temp.erl
build/dev/erlang/temp/_gleam_artefacts/gleam@@compile.erl
build/dev/erlang/temp/_gleam_artefacts/temp.cache_meta
build/dev/erlang/temp/_gleam_artefacts/temp.gleam_module
build/dev/erlang/temp/ebin/temp.app
build/dev/erlang/temp/_gleam_artefacts/temp@@main.erl
build/packages/gleam_stdlib/gleam.toml
build/dev/erlang/gleam_stdlib/ebin/gleam_stdlib.app
```

Notice that `./src` must start with `./` or else it will be silently ignored. This happens because here

```rust
// compiler-core/src/io/memory.rs
impl FileSystemReader for InMemoryFileSystem {
    fn gleam_source_files(&self, dir: &Path) -> Vec<PathBuf> {
        self.files
            .deref()
            .borrow()
            .iter()
            .map(|(file_path, _)| file_path.to_path_buf())
            .filter(|file_path| file_path.starts_with(dir))
            .filter(|file_path| file_path.extension() == Some(OsStr::new("gleam")))
            .collect()
    }
```

the check `file_path.starts_with(dir)` actually uses a value `.` for `dir`. Here is a piece of source code where I had troubles because of this:

```rust
    let fs = InMemoryFileSystem::new();
    [
        (format!("./src/{PROJECT_NAME}.gleam"), input),
        (
            "build/packages/gleam_stdlib/gleam.toml".to_string(),
            "name = \"gleam_stdlib\"".to_string(),
        ),
    ]
    .iter()
    .for_each(|(path, contents)| fs.write(&Path::new(path), contents).unwrap());

    tracing::info!("Compiling packages");
    let _ = ProjectCompiler::new(
        PackageConfig {
            target: options.target.unwrap(),
            name: PROJECT_NAME.to_string(),
            ..Default::default()
        },
        options,
        vec![manifest_from_name("gleam_stdlib")],
        Box::new(crate::cli::Reporter::new()),
        fs.clone(),
    )
    .compile()?;

```

**Comment by greenfork** [comment]
Also note that Gleam playground depends on this behavior

https://github.com/JohnDoneth/gleam-playground/blob/80e46a08507a4581da074fdb1aa7212cd67a264a/src/index.ts#L131-L137

**Comment by lpil** [comment]
Hi @greenfork !

This is an internal API and so there's generally no support for its use outside the compiler. If you wish to improve it in some fashion patches will be accepted but the current plan is that no work would be done on it beyond what the compiler requires.

What are you looking to do with it?

**Comment by greenfork** [comment]
I wrote a `gleam transpile` command which takes Gleam code and outputs Erlang code, I want to implement a repl with its help. I don't mind if it is not going to be changed, I don't use it as a library. But it would be a code improvement to make it consistent, I thought I should report it. I spent a couple of hours trying to debug this but I'm a novice in Rust, maybe it's not a problem for future contributors.

**Comment by lpil** [comment]
Sweet! You may also be interested in the `gleam compile-package` command which does something similar for use by other build tools.

**Comment by greenfork** [comment]
Okay, thanks, I will look at that command.

About documentation you probably mean this?
```
// Only supports absolute paths. For now. In future we could have a explicit
// current directory, or say that the current directory is always the root.
```

I think it should say that paths must start with `./` specifically because `/src` doesn't work too. But again I don't mind it too much if you think it is clear enough.

**Comment by lpil** [comment]
Paths must start with `/`, this is how it is always used within the compiler

**Comment by greenfork** [comment]
I'm sorry, I'm not sure what you mean. When I change the above line from `"./src/{PROJECT_NAME}.gleam"` to `"/src/{PROJECT_NAME}.gleam"`, it stops finding this file. Maybe I misunderstand something, I will probably have a working PR in the near future where it should be more clear.

**Comment by lpil** [comment]
The issue is likely elsewhere in that case. Possibly it is being used with a compiler subsystem that doesn't support it and uses relatively paths.
