### ISSUE TITLE
Generated JS is invalid when piping a variable defined by an import.

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#1954]
example
```gleam
import gleam/string

external fn str() -> String = "ffi" "string"

pub fn example() {
   let str = str()
   |> string.uppercase

   str
}
```

generates
```js
import * as $string from "../../gleam_stdlib/dist/gleam/string.mjs";
import { string as str } from "ffi";

export function example() {
  let str = (() => {
    let _pipe = str();
    return $string.uppercase(_pipe);
  })();
  return str;
}

```

Playground link. https://johndoneth.github.io/gleam-playground/?s=MYewdgzgLgBAhjAvDARHFAoUlYCMmq6bbQzAErDHily7nIDacANDLm8ALpA%3D

Fails with 
```
Uncaught ReferenceError: can't access lexical declaration 'str' before initialization
```

**Comment by lpil** [comment]
The playground is extremely outdated now so best not use it for anything to do with bugs. Does this happen with v0.26.0-rc1?

**Comment by CrowdHailer** [comment]
It happens on 0.25.3 at least, I discovered the bug on code I was building locally

**Comment by lpil** [comment]
Could you test with the latest version please? 🙏

**Comment by CrowdHailer** [comment]
It's still installing. but yes

**Comment by CrowdHailer** [comment]
Yes, I can confirm same error on 0.26.0-rc1

**Comment by lpil** [comment]
Thank you

**Comment by lpil** [comment]
Fixed in https://github.com/gleam-lang/gleam/pull/1957
