### ISSUE TITLE
❓ Types and constructors are imported together if they share the same name.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#1958]
If I have the following two modules...
```gleam
// foo.gleam
pub type A { B }
pub type C { A }
```
```gleam
// bar.gleam
import foo.{A}
```
...the import of `A` brings in both the _type_ `A`, and the `A` _constructor_ for the type `C`. There is currently no way to indicate which one you actually wanted to import, nor is there a way to explicitly import both.

Is this intended, an oversight, or a bug?

**Comment by hayleigh-dot-dev** [comment]
This example may feel contrived, but I have no run into this twice in Real World™️ code working on ren's compiler, but one in particular caused a compiler error...
```gleam
// ren/ast/expr.gleam
import ren/ast/lit.{Lit}

pub type Expr {
  Lit(Lit(Expr))
}
```
```gleam
// ren/ast/lit.gleam

// To head off any "define these types in the same module" suggestions,
// I'll point out that this type is parameterised because it is reused
// elsewhere as well.
pub type Lit(expr) {
 ... 
}
```
```gleam
// ren/query/parse.gleam

import ren/ast/expr.{Lit} // Importing the `Lit` *constructor*
import ren/ast/lit.{Lit} // Importing the `Lit` *type*
```
In this scenario the compiler complains about an ambiguous import where there is none. Semantically, the namespaces for constructors and types are separate so this should be allowed.

**Comment by lpil** [comment]
What are you proposing here? :)

**Comment by hayleigh-dot-dev** [comment]
Dunno really, "a way to distinguish type and constructor imports", but I don't think I have any ideas on what that might look like. 

Perhaps:
```gleam
// This *always* imports the `Foo` type
import thing.{Foo}
// This imports the `Foo` type and the `Bar` constructor
import thing.{Foo(Bar)}
// This imports the `Foo` type and all its constructors
import thing.{Foo(..)}`
```

**Comment by lpil** [comment]
Coolio. Any new syntax would need to be backwards compatible with the existing syntax so that one wouldn't work there, but something else would be good.

**Comment by hayleigh-dot-dev** [comment]
I don't think you can get backwards compat here, there's a semantic ambiguity coming from the fact that a single piece of syntax can mean two things so we just go "why not both".

Any fix for this will be a breaking change I think.

**Comment by lpil** [comment]
Thankfully that's not the case, we have have an additional syntax for specifying one or the other and retain the existing syntax for both.

**Comment by lpil** [comment]
Having said that, if we have a new syntax like the one you suggest then it would make it easier to create a constructor re-export syntax that would enforce that all constructors also get re-exported.

**Comment by lpil** [comment]
```gleam
// Import a type only
import thing.{type Foo}

// Import a value only
import thing.{!type Foo}
```
An initial syntax idea.

**Comment by NthTensor** [comment]
I've been ran into this for the first time recently when testing something. Hayleigh's syntax with qualified constructor imports seems quite nice and readable. Could we make this backwards compatible by continuing to allow unqualified imports but always defaulting to the type rather than the constructor when both are defined?

**Comment by lpil** [comment]
I'm gunna go back on what I said before about being backwards compatible. A breaking change is OK! Let's work out what's right before v1.

**Comment by giacomocavalieri** [comment]
If breaking changes are ok I really like Hayleigh's proposal!

**Comment by lpil** [comment]
Hayleigh and I have been chatting this over and are proposing that `import wibble.{Wibble}` would only import the value constructor, and `import wibble.{type Wibble}` would import the type.

Unlike `import module.{Type.{Constructor1, Constructor2}}` it does not introduce the idea that types are namespaces, and it keeps imports (`import module.{Constructor}`) consistent with expressions (`let x = module.Constructor(y)`).
