### ISSUE TITLE
✨ Introduce a `panic` keyword to intentionally crash a program.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#1961]
In the ren compiler I have this util to crash the program with a given message in cases like running a logically impossible code path or for features that aren't yet implemented:
```gleam
/// Intentionally crash the program with some message along with information
/// about where the crash was called from.
///
pub fn crash(module: String, line: Int, message: String) -> a {
  io.println("[" <> module <> "]:" <> int.to_string(line) <> " FATAL ERROR")
  io.println(fit_to_width(message, 80))
  io.println("")
  io.println("This is probably a bug. Please report it by opening an issue at:")
  io.println("https://github.com/ren-lang/compiler/issues/new")

  assert False = True

  // The above assertion will always fail and crash the program. The Gleam compiler
  // can't know that, though, so we pretend to infinitely recurse the `crash`
  // function so we can satisfy the return type `a`.
  crash(module, line, message)
}
```

I think it might be valuable to have some built-in construct to do this instead of userland code. What do you think?

**Comment by lpil** [comment]
I agree! Let's have this.

The only thing to decide is what the name should be. I quite like `panic` and `crash`.

**Comment by inoas** [comment]
I like crash over panic because crash says shat it does, panic is less clear of a word. also crash is one syllable and feels more harsh which is good for what it does.

**Comment by lpil** [comment]
On the flip side I think `panic` is used in a few languages, while I don't know any languages that use `crash`.

**Comment by inoas** [comment]
To
me `panic` sounds wholly unrecoverable and kernel/is related.

To me `else` (and `if`) should be reserved solely for a possible if/else expression.

```gleam
let Ok(_) = myfun(data) or crash
let Ok(_) = myfun(data) or crash("custom msg")
```

**Comment by lpil** [comment]
I'm ruling out `or` as I don't want to have confusion between `||` and `or`.

**Comment by inoas** [comment]
Had the same thought but what about a potential if/else expression - ruled out?

**Comment by lpil** [comment]
We would use `else` for `if` rather than `or`, it is what most people expect.

**Comment by inoas** [comment]
yes, what I am saying is that `if`/`else` are maybe being used as an expression, where `or` `when`, `where` is less likely. `if` already exists in 2 contexts where it is not an expression afaiu (case guards and target blocks) now if we add `else` here we are even more closing the way to having an `if/else`-expression that is unambigious at first sight and instead it could also be a target block or guard (if) or a panic clause (else).

**Comment by lpil** [comment]
Generally we aim to have few keywords that are reuses in consistent ways rather than a larger number of unique ones. For example, how fn is used for module functions and closures.

**Comment by lpil** [comment]
I want to avoid any language associated with exceptions that are raised and caught as it may give the impression it is to be used for flow control like it is in those languages.

"Panic" is used in Go and Rust for this, so there is convention there.
