### ISSUE TITLE
LSP does not work in `./test` only in `./src`

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#1971]
Editor: vscode latest stable, gleam extension latest version
- LSP in 0.26.0 does not work in test dir only in src dir (and only for all targets and erlang, not for javascript, tested in stdlib) 
- LSP in `if javascript {}`-blocks never worked? (seems not to in 0.25.3, 0.26.0 nor nightly).

**Comment by lpil** [comment]
Thanks!

> LSP in if javascript {}-blocks never worked? (seems not to in 0.25.3, 0.26.0 nor nightly).

To do this set the project target to JavaScript.
