### ISSUE TITLE
🎨 Preserve single-expression blocks when formatting.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#1977]
Currently the formatter will strip single-expression blocks like `{ x }` and format as just the expression `x`. This can be a bit frustrating when you code that you know will be in a block later but you've triggered formatting from a file save or something and now you have to and add them back: I suggest removing this behaviour because users are rarely adding redundant blocks without purpose.

This change would also have the side-effect of allowing users a way to opt-in to uniform formatting of case expressions. It can be a bit hard to scan larger cases when some expressions are on the same line and some are on a newline or are a block:
```gleam
case pat {
  pat.Alias(_, _) ->
    debug.crash("expr.gleam", 689, "Alias patterns unsupported")
  pat.Bind(name) -> [imp.Const(name, expr)]
  pat.Value(Arr(elements)) -> {
    use assignments, pat, i <- list.index_fold(elements, [])
    let index = imp.Number(int.to_float(i))
    list.append(
      assignments,
      to_imp_assignments_from_pat(pat, imp.Index(expr, index)),
    )
  }
  pat.Value(Con(_, args)) -> {
    let arr = pat.Value(Arr([pat.Wildcard, ..args]))
    to_imp_assignments_from_pat(arr, expr)
  }
  pat.Value(Num(_)) -> []
  pat.Value(Obj(fields)) -> {
    use assignments, field <- list.fold(fields, [])
    let #(key, pat) = field
    let expr = imp.Access(expr, [key])
    list.append(assignments, to_imp_assignments_from_pat(pat, expr))
  }
  pat.Value(Str(_)) -> []
  pat.Wildcard -> []
  pat.Typeof(_, pat) -> to_imp_assignments_from_pat(pat, expr)
}
``` 
👆 this is some dense code anyway (sorry) but it can be quite easy to miss a case in these situations. There are three (!) different formats for the case bodies here: 1) short expressions being rendered inline with the pattern, 2) long expressions being rendered indented on a new line, and 3) blocks.

Gleam's formatter doesn't typically take context clues from user formatting so currently there's no way to get a consistent format for each case, but with the proposed change I could write each case body as a block - even those with a single expression - and have uniform formatting for all of them.

**Comment by lpil** [comment]
Good suggestion. Another reason I would like this is because sometime I write a single value for a case clause and save before writing the rest, resulting in the formatter removing the braces and I have to type them again. Quite annoying!
