### ISSUE TITLE
compiler panics while inferring type of expression

### ISSUE THREAD

**Issue by evomassiny** [gleam-lang/gleam#1978]
Hi,

First of all, thanks for your work on this language !
While toying with it, I've stumbled across a compiler bug:

while inferring the type of this `case` expression,
 the compiler reaches an ["unreachable!()" statement](https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/type_/expression.rs#L1808):

```gleam
import gleam/regex.{Match}

pub fn main() {
  let str = ""
  let _ = case 1 {
    _ if Match(str, []) -> True // this line panics
    _ -> False
  }
}
```

The exact output is:
```
bash $ gleam run
  Compiling bug
error: Fatal compiler bug!

This is a bug in the Gleam compiler, sorry!

Please report this crash to https://github.com/gleam-lang/gleam/issues/new
with this information and the code that produces the crash.

        compiler-core/src/type_/expression.rs:1808
        internal error: entered unreachable code
 
```

I'm using a `gleam` binary directly compiled from sources, from the current lastest commit (2af8497e5f24f300d4c5b01b1dbe2bb6fa83d2cc).

Best regards,

evomassiny

**Comment by lpil** [comment]
Thank you for the thorough report! I wonder what the issue is here... We'll get it fixed ASAP

**Comment by lpil** [comment]
Ah yes! Great detective work. I think the ideal solution here would be to permit local variables in "constants" as they could be in a clause guard.

Probably should rename them from "constant" to be honest!

**Comment by lpil** [comment]
Hi @maurobalbi , did you want to pick this up?
