### ISSUE TITLE
🐛 Invalid Erlang is emitted when a constructor called `Let` is used as a function.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#1981]
I had the following code:
```gleam
pub fn run(expr: Expr) -> Expr {
  core.fold(
    ...
    core.Let,
    ...
  )
}
```
This compiles fine but attempting to run the code on Erlang emits the following error...
```
build/dev/erlang/ren/_gleam_artefacts/ren@ir@core@eval.erl:12:44: syntax error before: 'let'
%   12|         fun(Field@0, Field@1, Field@2) -> {let, Field@0, Field@1, Field@2} end,
%     |  
```
...and then also a bunch of other errors that are derived from this syntax error (which was very confusing).

Writing the code to use a lambda instead of the constructor resolves this issue and compiles and executes fine:
```gleam
pub fn run(expr: Expr) -> Expr {
  core.fold(
    ...
    fn(name, value, body) { core.Let(name, value, body) },
    ...
  )
}
```

**Comment by lpil** [comment]
Huh! What does `let` do in Erlang? 🤔 

Should be an easy fix :)
