### ISSUE TITLE
Problem when generating pattern-match in js for custom type without fieldname

### ISSUE THREAD

**Issue by JohnBjrk** [gleam-lang/gleam#1982]
Sorry if this is a duplicate, seems like someone should have bumped into this before, but I could not find a previous issue.

When executing `gleam run --target=javascript` for a newly created project with the following code in the main module:

```gleam
import gleam/io

type BadType {
  NoFieldName(a: String, String)
  HasFieldName(a: String, b: String)
}

pub fn main() {
  let b = NoFieldName("Hello ", "problem")
  case b {
    NoFieldName(a, b) -> io.println(a <> b)
    HasFieldName(a, b) -> io.println(a <> b)
  }
}
```

The compiler gives the following error:

> This is a bug in the Gleam compiler, sorry!
>
>Please report this crash to https://github.com/gleam-lang/gleam/issues/new
>with this information and the code that produces the crash.
>
>	compiler-core/src/javascript/pattern.rs:408
>	argument present in field map

It seems that matching on a custom type where a field is unnamed triggers this problem.

Changing the type to this makes the code compile and run successfully.

```gleam
type BadType {
  NoFieldName(a: String, c: String)
  HasFieldName(a: String, b: String)
}
```

**gleam --version**
gleam 0.26.1

**OS**
macOS 12.6.3

**Comment by lpil** [comment]
Thank you for the report

**Comment by JohnBjrk** [comment]
I started to look into this a bit. Seems the problem occurs more specifically when the custom type constructor has a mix of labelled and unlabelled arguments.

I think I found a fix but I need to test it some more.
