### ISSUE TITLE
`int.product([])` should be 1

### ISSUE THREAD

**Issue by jiegillet** [gleam-lang/gleam#1984]
Currently the product of an empty list is 0, but it should be 1.

The sum and product functions aggregate integers, but given no input, they should return the identity element of the operation. For addition, the identity is 0 (a + 0 == a), for multiplication it should be one (a * 1 == a).

In Elixir, `Enum.product([]) == 1`, Mathematica and Matlab do the same.

**Comment by inoas** [comment]
If this is an issue, it is with `gleam-lang/stdlib` not `gleam-lang/gleam`:
https://github.com/gleam-lang/stdlib/blob/main/src/gleam/int.gleam#L466-L468

**Comment by lpil** [comment]
Thanks all!
