### ISSUE TITLE
{ { let b = 1 } b } should parse as a nested sequences

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1991]
Seems we're flattening scopes which can result in unexpected variable scope.

```gleam
let b = 1
{
  let b = 2
}
b // This should be 1
```

**Comment by Ashish020202** [comment]
can I work on this .

**Comment by lpil** [comment]
Wonderful, thank you!

**Comment by lpil** [comment]
I'll be happy to, but would you mind completing your in-progress PR first? 🙏 

https://github.com/gleam-lang/gleam/pull/1995

**Comment by Ashish020202** [comment]
👍🙏

**Comment by lpil** [comment]
Oops, thanks
