### ISSUE TITLE
Error locations should include `src/` and `test/`.

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1994]

**Comment by inoas** [comment]
Aren't these included already?

<img width="1680" alt="Screenshot 2023-03-04 at 10 24 41" src="https://user-images.githubusercontent.com/20972207/222890417-b895fc70-6770-4dd2-9c3d-fffbf500b8e9.png">

Clearly shows `./src/gleam/order.gleam:37:5` or `./test/gleam/order_test.gleam:12:19`
It is even clickable in iTerm on mac and goes directly to the file and line.

**Comment by lpil** [comment]
Oh no, it is only 1 error that is missing them and I didn't note which one it was? 😆 

Well since I've forgotten which I will close this for now.
