### ISSUE TITLE
Homebrew install of Gleam 0.26.2: Unlabelled argument after labelled argument

### ISSUE THREAD

**Issue by ErikSchierboom** [gleam-lang/gleam#1996]
I've installed the latest Gleam version (0.26.2) via homebrew, but when I try to run `gleam test` I get an error:

```shell
  Compiling gleam_stdlib
error: Unlabelled argument after labelled argument
    ┌─ build/packages/gleam_stdlib/src/gleam/list.gleam:576:34
    │
576 │ pub fn prepend(to list: List(a), item: a) -> List(a) {
    │                                  ^^^^^^^

All unlabelled arguments must come before any labelled arguments.
```

Is this a problem with how I have defined my tests or is it actually something in the standard library?

edit: this is the project I'm working on: https://github.com/exercism/gleam/tree/run-length-encoding/exercises/practice/run-length-encoding

**Comment by inoas** [comment]
Try running `gleam update` to get a recent stdlib.

**Comment by ErikSchierboom** [comment]
Yep, that worked! Thanks
