### ISSUE TITLE
Binary matching slices the wrong length in JavaScript target

### ISSUE THREAD

**Issue by Nicd** [gleam-lang/gleam#2001]
Affected code:

```gleam
pub fn test_test() {
  let input = "Θ foo bar"
  case input {
    "Θ" <> rest -> rest
  }
}
```

Expected output is ` foo bar` (includes space at the start), and this is what is gotten in Erlang target. In JavaScript target, the return value is `foo bar` (space is sliced out). The generated JS is:

```javascript
export function test_test() {
  let input = "Θ foo bar";
  if (input.startsWith("Θ")) {
    let rest = input.slice(2);
    ...
```

The `slice` here has the wrong index. Θ only takes up one UTF-16 code unit so the index should be 1. This also occurs with `"`, but for example `&` results in a slice index 1.

Gleam version 0.26.2, Node.js 18.14.0.

**Comment by lpil** [comment]
oops! Thank you

**Comment by JohnBjrk** [comment]
Started to look at this one. One obvious thing is that the slice index is calculated as the `.len()` on a `SmolStr` which gives the number of bytes (not characters or graphemes. A simple solution could be to convert to a `String` and use `.chars.count()`. However this will not work for all grapheme-clusters. A more robust solution would be to use https://crates.io/crates/unicode-segmentation to get full support for all grapheme clusters. On the other hand on JavaScript side the string will be a UTF-16 (or UCS-2) string. Some quick research on this gave me the impression that handling of grapheme clusters is JavaScript in not very robust. So it might not be worth adding a new dependency to the complier to handle this. Any thoughts on this?

**Comment by lpil** [comment]
> However this will not work for all grapheme-clusters. 

I've not checked but I believe being a very old function JavaScript's `String.prototype.slice` isn't unicode aware so correctly handling unicode here would result in incorrect results. `smoltr.chars().count()` may be what we want. Or perhaps there's a constant relationship between `smolstr.len()` and the number of characters so we can do this in constant time. That would be ideal.

**Comment by Nicd** [comment]
Reading the specification (I added emphasis):

> The phrase "the substring of S from inclusiveStart to exclusiveEnd" (where S is a String value or a sequence of code units and inclusiveStart and exclusiveEnd are [integers](https://tc39.es/ecma262/multipage/notational-conventions.html#integer)) denotes the String value consisting of the consecutive _code units_ of S beginning at index inclusiveStart and ending immediately before index exclusiveEnd (which is the empty String when inclusiveStart = exclusiveEnd).

So, slicing in JS is done in code units, in JS's case 16 bits (which is how the other string length / index based functions work too). This can be verified in a JS console:

```
"🫥".length
2
"🫥".slice(1)
'\uDEE5'
```

**Comment by JohnBjrk** [comment]
So this makes if quite tricky to handle slicing of code points which are represented as surrogate pairs in UTF-16. `chars().count()` for 🫥 will give 1. So then I guess we need to handle this by encoding the `SmolStr` as UTF-16

**Comment by lpil** [comment]
Ah yes! That makes sense. Thanks

**Comment by Nicd** [comment]
Sorry to say that this isn't completely fixed, it seems?

```gleam
...
"\"" <> rest -> encode_named(rest, string_builder.append(acc, "&quot;"))
...
```

compiles to

```javascript
    ...
    } else if (text.startsWith("\"")) {
      let rest = text.slice(2);
      loop$text = rest;
      loop$acc = $string_builder.append(acc, "&quot;");
    } ...
```

The count for `"` is still wrong, that is. Could it be related to the `\`? I see also `"\\"` match results in a length of 2.

**Comment by JohnBjrk** [comment]
Ok, yes it sounds like it has to do with the escaping of the character. I can have a look, but I’m not sure I have the time today. Maybe tomorrow. If anyone else wants to have a look please feel free (I can leave a comment when I start to look at it).

**Comment by JohnBjrk** [comment]
Alright, started to have a look at this. I didn't consider that the lexer (of course) escapes the \ in strings. So when we then later on calculates the slice index the string that is used actually has a \ character (because that will be needed for outputting the string-literal later on). I guess that means we need to add some unescaping when calculating the slice-index.

**Comment by lpil** [comment]
>  I didn't consider that the lexer (of course) escapes the \ in strings

It's actually the opposite, we leave them as-is in the source rather than rewrite the codes into whatever characters they represent. We'll need to check for `\` when counting and discard the `\` of each `\.` pair.

**Comment by JohnBjrk** [comment]
Yes, exactly. Thats what I was trying to describe :)
Do you think it will be safe to assume that we can disregard all \ ? (My guess is yes because the only way I could have ended up there was because it represents a valid escape)

**Comment by lpil** [comment]
We can only discard the first character in `\.`, so if there's `\\` we need to count the second one.

**Comment by inoas** [comment]
This misses target 0.28 or 1.0 @lpil?

**Comment by lpil** [comment]
It closes, thank you!
