### ISSUE TITLE
Duplicate unused variable warnings from Erlang

### ISSUE THREAD

**Issue by digitalcora** [gleam-lang/gleam#2005]
Versions:

* Gleam 0.26.2
* OTP 25.2.1

Minimal example:

```gleam
// src/example.gleam

import gleam/io

pub fn main() {
  let unused = True
  io.println("Hello world!")
}
```

Compile output:

```
build/dev/erlang/example/_gleam_artefacts/example.erl:8:5: Warning: variable 'Unused' is unused
%    8|     Unused = true,
%     |     ^


warning: Unused variable
  ┌─ ./src/example.gleam:4:7
  │
4 │   let unused = True
  │       ^^^^^^ This variable is never used.

Hint: You can ignore it with an underscore: `_unused`.
```

Both Erlang and Gleam print separate warnings about the variable being unused. There is otherwise no consequence (I think), but it can make the output quite noisy when there are multiple unused variables.

**Comment by lpil** [comment]
I agree, this is quite annoying! A short term fix would be to see if we can disable unused variable and value warnings only (I wish to keep the others).

Longer term once we have improved our dead code detection we can avoid unused code.
