### ISSUE TITLE
weird issue with the % operator in js side

### ISSUE THREAD

**Issue by massivefermion** [gleam-lang/gleam#2020]
I was just trying to do some work on birl when I came accross a weird issue in the js side!
When I do `12_600_000_000 % 31_536_000_000_000` I get `12_600_000_000` in the erlang side as I should. But in the js side, I get `-284901888` which didn't make sense to me. So I investigated and the problem seems to stem from [here](https://github.com/gleam-lang/gleam/blob/7d1ebf20a7f96f36d63c5f182a9cfd2be1d47336/compiler-core/templates/prelude.js#L389), specifically `a % b | 0` which does not make sense because `|` is a bitwise operator (and would mess up the calculation in case `a%b` is not NaN) and it seems to me that it was supposed to be `||` because that actually solves the issue.
But I didn't make a PR because I'm not exactly sure why you would need `|| 0` to be there in the first place so maybe I'm misunderstanding something. Is there something wrong or undesirable about js's `%` operator that needs to be corrected in this way?
EDIT: I did see the issue about `n % 0` but there is already a check for it! and also that would still be solved by `|| 0` not the bitwise operator `|` !
Thanks

**Comment by lpil** [comment]
Oh yes, that's a bug, we're using the wrong number of bits for integers there. Thank you

**Comment by inoas** [comment]
```
❯ deno
Deno 1.30.0
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> 1 | 0
1
> null | 0
0
> 0 | 0
0
> NaN | 0
0
> Infinity | 0
0
> 1 / 0 | 0
0
> 1 % 0 | 0
0
```
... seems to be in line with the implementation that `x % 0` and `x / 0` return 0?
