### ISSUE TITLE
a / 0 = 0 and a % 0 = 0 is not a good idea!

### ISSUE THREAD

**Issue by massivefermion** [gleam-lang/gleam#2021]
I just noticed this behavior in gleam and I don't think it's a good idea.
It may seem like that 0 is a special number that could be returned to somehow tell the developer that they shouldn't be doing something but mathematically it's no different than returning any other arbitrary number like 420 or 69! 
And you should also keep in mind there are cases where the answer is legitimately equal to zero, `0 / b = 0` and `kb % b = 0` so you're just making the situation really confusing and error-prone when you also use 0 as an error indicator.
Even javascript that is usually ridiculed for such things has a better solution than this: `a / 0 = Infinity` and `a % 0 = NaN`. It's true that `typeof NaN == 'number'` and `typeof Infinity == 'number'` but at least you could check for error using `isNaN` and `result == Infinity`.
But when you just return an arbitrary number as result, you make it impossible to reliably check for error and people would need to come up with solutions that should have been offered by the language itself in the first place.
I think erlang has the correct behavior which is just to crash the application. Keep in mind, `a / 0` and `a % 0` are no different than `a / "some string"` and `a % "some other string"`. Zero as denominator is not acceptable as an input the same way strings are not, simply because the operations are **not defined** for both of them. The only difference here is we can't type check for 0, so the only thing that makes sense in this situation is to crash.

**Comment by inoas** [comment]
What I do is never using `%` or `/` (and I feel that the recent change to int.modulo and int.remainder to recommend % over the functions isn't good) except for guards and there explicitly testing for the divisor to be `!= 0`.

I feel a division by 0 should crash because it an expected error.
If run inside a process the process can restart.
If there is a permanent error I rather see that permanent error.

I wish this was different and I was sad to see this change happening but then on the other hand the workaround is there and easy to do as described in my first sentence.

However I feel expecially for newbies this will be unexpected and a hard crash is much better.

Also: If you want to divide by 0 and NOT crash you can explicitly handle an `Error` returning from int.divide/modulo/remainder and then chose tho return 0 or whatever.

**Comment by lpil** [comment]
> It may seem like that 0 is a special number that could be returned to somehow tell the developer that they shouldn't be doing something but mathematically it's no different than returning any other arbitrary number like 420 or 69!

Yes, just like NaN!

There is no mathematically "correct" answer to this question, so it becomes a matter of API design, and this is the one we believe fits best for Gleam. It has the advantage of only using numbers, it doesn't introduce a special number that isn't a number.

> But when you just return an arbitrary number as result, you make it impossible to reliably check for error

Functions that treat this case as an error are included in the standard library, this is more generous than any language I found in my research.

> I think erlang has the correct behavior which is just to crash the application. 

Gleam core is total, it never crashes.

The concept of crashing doesn't exist in mathematics either so it cannot be reasoned as a more correct behaviour.

> Keep in mind, a / 0 and a % 0 are no different than a / "some string" and a % "some other string"

This isn't true. We can and do detect division by the incorrect type statically and reject these programs.

> Zero as denominator is not acceptable as an input the same way strings are not, simply because the operations are not defined for both of them.

This isn't true either. If we were talking about mathematics it would be true, but it is not. We're talking about programming languages, where integers have different properties to mathematical integers. For example, they are bounded.

I understand that this is not one of the more common approaches to this solution, but I have full confidence it is the correct one for Gleam, and as yet no one has presented any problems in real code coming from this approach, including yourself.

**Comment by lpil** [comment]
> I feel a division by 0 should crash because it an expected error.

Gleam core is total. This will never happen.

**Comment by inoas** [comment]
> I understand that this is not one of the more common approaches to this solution, but I have full confidence it is the correct one for Gleam, and as yet no one has presented any problems in real code coming from this approach, including yourself.

This will be one of the (very few <3) gotchas of the language to learn and memorize. If not done this can result into massive losses of cash or service or worse, at least that's my humble and not important(!) opinion.
