### ISSUE TITLE
`panic` highlight-js

### ISSUE THREAD

**Issue by inoas-nbw** [gleam-lang/gleam#2022]
- fix highlight js of docs generator
- fix highlight js on gleam website
- fix highlight js repo

Ref: https://github.com/gleam-lang/gleam/pull/2019

I will do that chore unless someone beats me to it.

**Comment by inoas** [comment]
https://github.com/gleam-lang/gleam-highlight.js/pull/2 needs to be merged then this can be closed.

**Comment by lpil** [comment]
Thank you!
