### ISSUE TITLE
0.27: open github support ticket to request support for `panic` and `let assert`

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#2027]
> let assert breaks treesitter again? https://github.com/gleam-lang/gleam/blob/d4c9c680fd2be72c30be37924dfbfc9de65b3b11/test/project_erlang/test/project_test.gleam#L42

**Comment by lpil** [comment]
Aye! We'll need to update tree sitter and release it + Gleam v0.27 first.

**Comment by inoas** [comment]
https://github.com/gleam-lang/tree-sitter-gleam/issues/45
https://github.com/gleam-lang/tree-sitter-gleam/pull/46 ... not sure If I will get this mergable.

**Comment by inoas** [comment]
https://github.com/gleam-lang/tree-sitter-gleam/pull/50 is through and a new releae is out, will you get in touch with github @lpil or should I attempt to - whuch email or link did you use?

**Comment by lpil** [comment]
Go for it! I just used the support portal

https://support.github.com/tickets/personal/0

**Comment by inoas** [comment]
I've setup a ticket. If I can't get through I will let you know.
