### ISSUE TITLE
when type is missing for argument to external function, complains about unlabelled argument

### ISSUE THREAD

**Issue by keroami** [gleam-lang/gleam#2037]
```
pub fn f1(a: String, fun b) {
  fun(a)
  b(a)
}

pub external fn f(a: String, b) -> Nil =
  "./blah" "die_blah"
```
results in
```
error: Unlabelled argument after labelled argument
  ┌─ ./src/problem.gleam:6:30
  │
6 │ pub external fn f(a: String, b) -> Nil =
  │                              ^

All unlabelled arguments must come before any labelled arguments.
```
gleam 0.27.0

**Comment by lpil** [comment]
Hello!

Yes, this is correct. That is the syntax for a labelled external function. External functions are not implemented in Gleam so you cannot provide argument names, only labels.

**Comment by keroami** [comment]
What surprised me, is that 0.26 compiled this just fine. Maybe something for `gleam fix` to warn about?

What confused me is not even the problem, but the error message.

I meant the code as `pub exteral fn(arg1: type, arg2)`, and today I think the compiler parses `pub external fn (label: type1, type2)`. Although "unlabelled argument" makes some sense, I think "unlabelled type" would help me more. I compared it to `pub fn` for a reason, I'm thinking the same way about them and as far as I understand it, it would be `pub fn (label arg: type)`, `pub fn(arg: type)` and `pub fn(arg)` (not type)

**Comment by lpil** [comment]
Yeah there was a bug in the previous versions where the error wouldn't be emitted. Unfortunate!

Would the word parameter be clearer? It's a label used to give a value so the name type label would not be right. The syntax is a bit surprising here.

**Comment by keroami** [comment]
ah, I only jumped on the bandwagon with 0.26.0 so I missed the error before ;)

I don't think parameter would be clearer.

Maybe something like: "All unlabelled arguments must come before any labelled arguments. For an external function, an argument is a type." when the error is given for an external function?

**Comment by lpil** [comment]
A clearer error message could go a long way here! What do you mean by the argument is a type?
