### ISSUE TITLE
Formatter removes essential brackets in bitstrings

### ISSUE THREAD

**Issue by jiegillet** [gleam-lang/gleam#2045]
Using bitstrings, I tried the following expression 

```gleam
let small_byte = <<leading_bit:1, 1 + 1:7>>
```
But I got a syntax error:

```gleam
22 │   let small_byte = <<leading_bit:1, 1 + 1:7>>
   │                                       ^ I was not expecting this.

Expected one of: 
">>"
```

So I tried this

```gleam
let small_byte = <<leading_bit:1, { 1 + 1 }:7>>
```

which compiles and works fine. 
Unfortunately `gleam format` removes the brackets, so in practice with a format-on-save workflow, this will effectively not compile.

I expected the first expression I wrote to parse and compile, so that would be my preferred resolution.
If that's not possible, then at least `gleam format` should not remove the brackets.

**Comment by lpil** [comment]
Thank you!
