### ISSUE TITLE
double negation should throw an error (or warning)

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#2050]
This should throw an error(?) and hint at removing the unnecessary double negation:

```gleam
--a
```

This should throw a warning(?) and hint at removing the unnecessary double negation:

```gleam
- { -a }
```

Ref: https://github.com/gleam-lang/gleam/pull/2033

**Comment by lpil** [comment]
Sounds sensible! Same for `!!x`

**Comment by bcpeinhardt** [comment]
I'd like to work on this as a way to get introduced to contributing.

**Comment by lpil** [comment]
Wonderful, thank you @bcpeinhardt !

**Comment by bcpeinhardt** [comment]
Quick question:
Currently, a double unary minus on a float is a type error. For instance,
```
let x = --7.0
```
produces
```
error: Type mismatch
  ┌─ /home/benjaminp/Repos/test_double_unary/src/test_double_unary.gleam:5:12
  │
5 │   let x = --7.0
  │            ^^^^

Expected type:

    Int

Found type:

    Float
```
My understanding of this is as follows, although I'm really new to this codebase (like 2 days) so I could be very wrong.

This may be on purpose, but it doesn't seem like it is. The untyped AST struct for the unary minus (-x) is called `NegateInt`, which I think may be where the confusion arose.
In the expression typer, it looks like the infer_negate_int method looks for an integer, when really it should also work for a float. I think the reason this didn't come up before is that for some reason when an integer or float is parsed, the first unary minus is stored in the int or float itself (the value will be a smolstr of "-7"). It's not until the second unary minus is present that you get an actual NegateInt struct. 
If you want to see this in action, do `gleam new double_minus_float` and paste the following
```
pub fn main() {
  let x = -7.0
  let y = -x
}
```

Assuming this read of the situation is correct, I'd like to:
1. Rename `NegateInt` and `NegateBool` to `UnaryMinus` and `UnaryBang` respectively
2. Finish adding the warnings and make a pull request

After that, maybe we can have a conversation about whether the leading unary minus should be separated for integer literal to be it's own leading minus token in the parser.

**Comment by bcpeinhardt** [comment]
May I also suggest the majestic NegateFloat operator
```
let x = .-7.0
let y = .-x
let z = .-.- y
```

**Comment by bcpeinhardt** [comment]
Update: I found the test `negate_float_as_integer` in parse/type_/tests/errors, which would indicate that the inability to negate a float is a deliberate design decision. It feels inconsistent though. 
```
let x = -7.0 // this is fine
// let y = -x // error
let y = 0.0 -. x // this is fine
```
I think a special operator for negating floats would be the most consistent option design wise, although I understand it would break some things. I wouldn't recommend the float subtract `-.` though, as it will look like working with decimals, which is why I reversed it in my half joke earlier.
```
let x = -.70 // x is 70, not 0.7
```

**Comment by bcpeinhardt** [comment]
Pull request for all this: https://github.com/gleam-lang/gleam/pull/2120
The pull request currently includes support for unary minus on floats so you can check it out and see what you think, but if you're set on not having a unary negation for floats I can remove that part.
