### ISSUE TITLE
LSP should cache content of unsaved files on startup

### ISSUE THREAD

**Issue by JohnBjrk** [gleam-lang/gleam#2054]
After merging #2052 (which fixes #2031) the LSP diagnostics might end up in an inconsistent state if LSP is restarted with unsaved files (only tested in VS Code) assuming that the unsaved files are kept by the editor.

Investigate if there is a way of loading such unsaved files from the editor at startup of LSP. If this is possible they should be read into the `LspFsProxy` mem-cache and then a compilation triggered from the LSP to sync all diagnostics.

**Comment by lpil** [comment]
Thank you. I wonder if we can get the state of the open files from the client on load, that would be nice.
