### ISSUE TITLE
Enable configuring of runtimes

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#2065]
Allow setting erlang/beam, deno or nodejs boot args.

**Comment by inoas** [comment]
> @JohnBjrk I used it to pass --perf flag to node which was quite useful for understanding my performance bottleneck on map inserts.

**Comment by Lunarmagpie** [comment]
I think it would be useful if this feature also supported using ts-node to run node code, ie `node ts-node gleam_module.mjs`

**Comment by lpil** [comment]
Super useful, especially on the BEAM. We'll need to figure out a good design for this so let's start by researching what other languages do here.

I though we had an existing issue for this but I can't find it now 🤔

**Comment by lpil** [comment]
We need to do research and see what other languages and build tools do.

**Comment by lpil** [comment]
Closing as I believe we can do this all with the deno config + BEAM env vars now
