### ISSUE TITLE
docs generator: prefix ids on layout and prefix function ids to avoid potential clashes

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#2066]
19 ids on the base layout I think

**Comment by lpil** [comment]
I don't know what this means, could you give more detail please?

**Comment by inoas** [comment]
i’d add an f prefix to function anchors and a gleam- prefix to static layout ids so that bith can never collide. if you name a function syntax_theme it woukd almost collide

**Comment by lpil** [comment]
Sounds good! Thanks
