### ISSUE TITLE
warn about performance issues that could arise from using list.length to find out if a list is empty

### ISSUE THREAD

**Issue by despairblue** [gleam-lang/gleam#2067]
When using `list.length` to find out if a list is empty the compiler could emit a warning telling the developer to use `list.empty` instead and linking to some part of the documentation that goes into detail about `list` being a linked list and `list.length` iterating over the list to find it's length.

Code that should produce a warning:
```gleam
pub fn non_empty_list(list: List(a)) -> Option(List(a)) {
  // O(n), so potentially super slow.
  case list.length(list) == 0 {
    True -> Some(list)
    False -> None
  }
}

pub fn non_empty_list(list: List(a)) -> Option(List(a)) {
  // O(n), so potentially super slow.
  case list.length(list) {
    0 -> Some(list)
    _ -> None
  }
}
```

What to replace it with:
```gleam
pub fn non_empty_list(list: List(a)) -> Option(List(a)) {
  case list.is_empty(list) {
    True -> Some(list)
    False -> None
  }
}

pub fn non_empty_list(list: List(a)) -> Option(List(a)) {
  case list == [] {
    True -> Some(list)
    False -> None
  }
}
```

For reference see the discord conversation around here: https://discord.com/channels/768594524158427167/768594524158427170/1084786897680879696

**Comment by lpil** [comment]
Great suggestion, thank you.

**Comment by maxdeviant** [comment]
I would be interested in working on this issue 🙂
