### ISSUE TITLE
LSP for 0.28.0-rc1 doesn't update when i delete characters

### ISSUE THREAD

**Issue by Lunarmagpie** [gleam-lang/gleam#2093]
First type this correct code
```
import gleam/io

pub fn main() {
  io.println("Hello from test!")
}
```
Now make it incorrect
```
import gleam/io

pub fn main() {a
  io.println("Hello from test!")
}
```
Revert your code back to the original by deleting `a` with backspace.
The LSP still shows this error
![image](https://user-images.githubusercontent.com/65521138/227831618-15b04a72-7a73-4c27-8942-cd7af4020ab0.png)

**Comment by lpil** [comment]
Hello! What editor are you using? I've been unable to reproduce this, and we do reanalyse on every new input. I wonder if you editor isn't sending an event in this case.
