### ISSUE TITLE
`gleam --module` should prioritize using the language target for a dependency over the project's target

### ISSUE THREAD

**Issue by Lunarmagpie** [gleam-lang/gleam#2096]
For example, if i do `gleam -m rad` it should use the `javascript` target because that is set in rad's `gleam.toml`. Otherwise, a project like this would crash and that's not intended lol.

**Comment by lpil** [comment]
A good suggestion! This will be tricky as we would have to identify the module prior to compilation, but we could probably traverse the filesystem to find it.

**Comment by Lunarmagpie** [comment]
So I've been thinking about this and there's a larger issue. When you set `target=` in your project, it says what target a dependency can be run on. But a project that only compiles to erlang may ship with a tool that can only run on js.
