### ISSUE TITLE
`view source` link issue with published gleam docs(v0.28.0-rc2)

### ISSUE THREAD

**Issue by massivefermion** [gleam-lang/gleam#2101]
I just went back to make a quick change in `blah` and quickly published it. But then I realized there was something wrong with the docs. When I clicked on the `view source` link of one of the functions, I got a `404` from github and I realized the `view source` is using the wrong url. It was attaching the local path of `blah` on my laptop to `https://github.com/massivefermion/blah/blob/v0.8.1/`! So I replaced the published version using `v0.27.0` and the problem was fixed.

**Comment by inoas** [comment]
it is fixed in main https://github.com/gleam-lang/gleam/issues/2100
