### ISSUE TITLE
Bug:  LSP show definition removes error diagnostics

### ISSUE THREAD

**Issue by rawhat** [gleam-lang/gleam#2105]
In a file with a diagnostic error, attempting to hover definition/info, the diagnostics disappear.

![image](https://user-images.githubusercontent.com/2095509/229564994-c128c568-ee27-49be-ad04-0e41951b86fb.png)

Presuming as well that the `Nil` here is at least a symptom of the issue.

Let me know if you need LSP logs for any of this!

**Comment by lpil** [comment]
Thank you
