### ISSUE TITLE
"Not exhaustive pattern match" when shadowing prelude types

### ISSUE THREAD

**Issue by digitalcora** [gleam-lang/gleam#2108]
In the example below I define my own `Result` type with its own `Ok` and `Error` constructors, plus an extra one. Then I try to pattern-match on a function (`list.at`) that returns the original `gleam.Result` type.

```gleam
import gleam
import gleam/list

type Result {
  Ok(Int)
  Halt(Int)
  Error(String)
}

fn test() -> Result {
  case list.at([1, 2, 3], 0) {
    gleam.Ok(val) -> Ok(val)
    gleam.Error(Nil) -> Halt(0)
  }
}
```

The compiler appears to be confused by this and thinks `list.at` now returns my custom `Result` type, and errors because I haven't matched `Halt`.

```
error: Not exhaustive pattern match
   ┌─ ./src/scratch.gleam:11:3
   │
11 │ ╭   case list.at([1, 2, 3], 0) {
12 │ │     gleam.Ok(val) -> Ok(val)
13 │ │     gleam.Error(Nil) -> Halt(0)
14 │ │   }
   │ ╰───^

This case expression does not match all possibilities.
Each constructor must have a pattern that matches it or
else it could crash.

These values are not matched:

  - Halt
```

Of course, if I add a `Halt(_)` pattern as this message suggests, it correctly errors because of a type mismatch. I can only get it to compile by adding a `_ -> panic` case.

**Comment by lpil** [comment]
Oh dear, that is quite funny. I see a PR has been opened, y'all are too fast for me :)
