### ISSUE TITLE
Docs reveal opaque type constructors for constants

### ISSUE THREAD

**Issue by digitalcora** [gleam-lang/gleam#2111]
Not sure if this is really an issue, but it seems like an inconsistency in how opaque types are treated in docs. Example:

```gleam
pub opaque type Secret {
  Number(Int)
}

pub const the_answer = Number(42)
```

This renders in the generated docs as:

```gleam
pub const the_answer: Secret = Number(42)
```

`Number` itself is otherwise not exposed in the docs and cannot be used from outside the module, so this could be confusing.

It could alternatively render like:

```gleam
pub const the_answer: Secret
```

But maybe this would also be confusing? As there is no explicit indication that the reason you're not seeing the value is because it has an opaque type.

**Comment by lpil** [comment]
I agree, the way that code is rendered in the documentation is not idea. It has been bugging me for ages!

I would like to change all the code previews to be in a format that makes sense for the reader, rather than what was written in the source file.
