### ISSUE TITLE
Formatter splices comments above use expressions into the middle of them

### ISSUE THREAD

**Issue by fabjan** [gleam-lang/gleam#2118]
## Expected behavior

This code:

```gleam
fn start() {
  let cache_size = 100

  // TODO: use supervisor
  // Start our dependencies
  use client <- result.then(
    http_client.start(cache_size)
    |> cmd_snag("starting HTTP client"),
  )
}
```

is OK and should not be changed by `gleam format`.

## Observed behavior

When run through `gleam format` (with 0.28.0 or 0.28.1), the code above is reformatted as:

```gleam
fn start() {
  let cache_size = 100

  use client <- // TODO: use supervisor
  // Start our dependencies
  result.then(
    http_client.start(cache_size)
    |> cmd_snag("starting HTTP client"),
  )
}
```

## Notes

The VS Code Gleam extension (v2.2.0) formatting does not do this "splicing" of the comment.

Gleam 0.27.0 also does not mess up the comment (it leaves it as is in the code above), so this appears to be a regression of the formatter that was introduced with 0.28.

**Comment by lpil** [comment]
This has been fixed on main, thank you
