### ISSUE TITLE
Formatter deletes empty line after a let binding if it is a function with an annotated return type

### ISSUE THREAD

**Issue by fabjan** [gleam-lang/gleam#2119]
## Expected behavior

This code should pass through the formatter untouched:

```gleam
fn greet(what) {
  let dupe = fn(s) -> String { s <> s }

  let times = 3

  let message = string.repeat(dupe(what) <> " ", times)

  io.println(message)
}
```

Leaving empty lines between let bindings is useful for readability, and is allowed by the formatter most of the time.

## Actual behavior

The empty line after the bound anonymous function is removed by `gleam format`:

```gleam
fn greet(what) {
  let dupe = fn(s) -> String { s <> s }
  let times = 3

  let message = string.repeat(dupe(what) <> " ", times)

  io.println(message)
}
```

## Notes

If the return type annotation is removed the formatter keeps the empty line.

Just annotating the function parameter does not cause the formatter to delete the line.

**Comment by fabjan** [comment]
Oh, I just discovered another very similar case, might be related so I leave it here before assuming you want a separate issue.

This code also gets the empty line after the closing curly brace deleted by `gleam format`:

```gleam
fn greet(what) {
  let greeting = {
    let x = "Hello "
    x <> what <> "!"
  }

  let times = 3

  let message = string.repeat(greeting <> " ", times)

  io.println(message)
}
```

On the other hand, the curly braces from a case expression does not cause the empty line to be deleted, this is left alone:

```gleam
fn greet(what) {
  let greeting = case what {
    "World" -> "Hello"
    "Gleam" -> "Hi"
    _ -> "Hello"
  }

  let times = 3

  let message = string.repeat(greeting <> " ", times)

  io.println(message)
}
```

**Comment by lpil** [comment]
Nice finds! Thank you
