### ISSUE TITLE
Unused variable warning when error occurs before usage

### ISSUE THREAD

**Issue by digitalcora** [gleam-lang/gleam#2124]
Example:

```gleam
import gleam/string

fn test(arg: String) -> Nil {
  string.nope(arg)
  Nil
}
```

Result:

```
warning: Unused variable
   │
17 │ fn test(arg: String) -> Nil {
   │         ^^^^^^^^^^^ This variable is never used.

Hint: You can ignore it with an underscore: `_arg`.

error: Unknown module field
   │
18 │   string.nope(arg)
   │         ^^^^^ Did you mean `crop`?

The module `gleam/string` does not have a `nope` field.
```

This is a bit of a weird one, but personally I would say that the variable _is_ "used" here and so the warning is more confusing than helpful. Could the compiler recognize that it has incomplete information about variable usage due to the error, and avoid emitting warnings?

**Comment by lpil** [comment]
Thanks! I think we could fix this by only checking for unused values if the module successfully type checks.

We will be replacing the usage detection system in future with one based off a call graph, so this will be fixed by that if no one picks this up before that.

**Comment by tinfoil-knight** [comment]
Hey @lpil,
I was trying this out with `gleam 0.32.0-dev`. The issue no longer exists.

This is the output currently for the code mentioned in the description:
```
  Compiling gleam_stdlib
  Compiling gleeunit
  Compiling helloworld
error: Unknown module field
  ┌─ /Users/tinfoil-knight/helloworld/src/helloworld.gleam:4:9
  │
4 │   string.nope(arg)
  │         ^^^^^ Did you mean `crop`?

The module `gleam/string` does not have a `nope` field.
```

**Comment by lpil** [comment]
Oops! I forgot to close this issue. Thank you
