### ISSUE TITLE
gleam cli commands should search for a parent directory with a `gleam.toml` file

### ISSUE THREAD

**Issue by Lunarmagpie** [gleam-lang/gleam#2134]
Build tools like `cargo` have this behavior. I think it would be a bit easier to use gleam if this was a feature.

**Comment by lpil** [comment]
Could be good! What use cases might there be for this?

What would `gleam run` do in this case also with respect to $PWD?

**Comment by Lunarmagpie** [comment]
> Could be good! What use cases might there be for this?

When I'm using my terminal I am sometimes going into a subdirectory I guess. It's not really a common thing to have to be in a subdirectory but this would be very convenient when I am.

> What would gleam run do in this case also with respect to $PWD?

`$PWD` would be the directory containing the `gleam.toml`. This is what cargo does.

**Comment by lpil** [comment]
Nice, sounds good then. Let's do it!

**Comment by fffnite** [comment]
Having a look at this at the moment. One issue I'm having is that while replacing the function `project_paths_at_current_directory()` with a recursive function that checks for `gleam.toml` generally seems to be working, a bunch of tests call this function and as they don't use/have a `gleam.toml` file in any directory, they fail.

Not sure the preferred way to handle this? should the tests have a separate path resolve function or should I provide some kind of empty file just to satisfy them or some other approach ^^?

**Comment by lpil** [comment]
Thanks for working on this. Which tests are these?

**Comment by fffnite** [comment]
these are the test:

```
failures:
    build_lock::locking_dev_erlang
    build_lock::locking_dev_javascript
    build_lock::locking_global
    build_lock::locking_lsp_erlang
    build_lock::locking_lsp_javascript
    build_lock::locking_prod_erlang
    build_lock::locking_prod_javascript
    dependencies::provide_conflicting_package
    dependencies::provide_existing_package
    dependencies::provide_wrong_package
    dependencies::provided_is_absolute
    dependencies::provided_recursive
  ```
  
  all of them were simply using the current working dir and moving on but now that that function is specifically looking for a gleam.toml file instead of just passing $PWD, they ain't happy ^^;

**Comment by lpil** [comment]
Let's have them work in some test directory rather than add config to the root, that could be potentially confusing.
