### ISSUE TITLE
Lsp diagnostic not removed when reverting a file to last saved state

### ISSUE THREAD

**Issue by JohnBjrk** [gleam-lang/gleam#2138]
```gleam
import gleam/io

type Param {
  Param(value: String)
}

pub fn main() {
  test(Param("Hej"))
  io.println("Hello from lsp_cache_issue!")
}

fn test(a: Param) {
  io.debug(a)
}
```

In a fresh project. First add  + error after the string in println. An error will show. Then remove  + error and the error will disappear. Now remove the final m in the type Param of in fn test. An error appears. Add the m back. Error is still preset.

*Expected behaviour:* Error should always be removed when the file is reverted to the last saved (error free) state.

Hint: The logger for the lsp says:
> INFO compile{package=lsp_cache_issue}: analysing_modules count=0

I also added some additional traces (on top of current main) and saw that the lsp is receiving the expected `textDocument/didSave` and `textDocument/didChange` notifications before reporting this.

Furthermore, when removing the corresponding cache-files under `build/lsp` the error is disappears after saving the file one more time.

*Environment*
- gleam 0.28.3
- VS Code 1.77.3

**Comment by lpil** [comment]
Thank you
