### ISSUE TITLE
LSP crashes after entering text

### ISSUE THREAD

**Issue by rawhat** [gleam-lang/gleam#2141]
This is on `main` as of a few minutes ago.  Generating a new project with `gleam new ...` and navigating to the generated source file.

Entering any text crashes the LSP with the following error:

`
[ERROR][2023-05-04 18:01:31] .../vim/lsp/rpc.lua:734	"rpc"	"gleam"	"stderr"	"error: Fatal compiler bug!\n\nThis is a bug in the Gleam compiler, sorry!\n\nPlease report this crash to https://github.com/gleam-lang/gleam/issues/new\nwith this information and the code that produces the crash.\n\n\t/home/alex/gleams/gleam/compiler-core/src/language_server/engine.rs:307\n\tModule must exist\n"
`

Seems to occur in both VSCode and neovim.

Thank you :)

**Comment by lpil** [comment]
Thank you. This is fixed in ce2a8eae839a4e0613b10b9165e155f8362e71e5
