### ISSUE TITLE
Syntax error in type annotation links to non-existent documentation

### ISSUE THREAD

**Issue by Innf107** [gleam-lang/gleam#2142]
Running [this playground example](https://johndoneth.github.io/gleam-playground/?s=JYWwDg9gTgLgBAcwDYFMCGID0wIChdgCuARnAGYB25AFAB4CUcA3rnHKvAnAFxzVpwAtAD44aRgF5yFOoyZxacAL6sFuFQRLS4INMBlzVZagFZ66oA%3D%3D) raises the following syntax error

```
error: Syntax error
  ┌─ ./src/main.gleam:4:9
  │
4 │   let g : (a -> a) = fn(x) { x }
  │         ^ I was expecting a type after this.

See: https://gleam.run/book/tour/type-annotations
 ```

But the given link 404s.

**Comment by lpil** [comment]
Thank you! This is now fixed and a redirect has been added.
