### ISSUE TITLE
Add info about Gleam to the Wikipedia

### ISSUE THREAD

**Issue by romul** [gleam-lang/gleam#2145]
I think Gleam is a very promising language. And it's worthy to mention it in Wikipedia:

https://en.wikipedia.org/wiki/Gleam
https://en.wikipedia.org/wiki/List_of_programming_languages
https://en.wikipedia.org/wiki/Timeline_of_programming_languages

**Comment by romul** [comment]
@lpil  Don't worry. The only requirement is to create a page https://en.wikipedia.org/wiki/Gleam_(programming_language)
I guess it would be better if you write it. After that we can add Gleam to the lists of programming languages without any trouble.

Some examples for inspiration what topics to cover:
https://en.wikipedia.org/wiki/Elixir_(programming_language)
https://en.wikipedia.org/wiki/Elm_(programming_language)

**Comment by lpil** [comment]
I think as the creator it's best I do not create it, I am biased and not an establish wikipedia author. I suspect it would be less likely to be deleted coming from someone who does contribute to wikipedia.

**Comment by lpil** [comment]
I'm closing this as I don't think this is something the core team can do, but it would be awesome if someone else did!
