### ISSUE TITLE
Provide the antagonist to `gleam add`

### ISSUE THREAD

**Issue by manuel-rubio** [gleam-lang/gleam#2148]
The command `gleam add` is great and it's providing an easy way to add a dependency, but if we were wrong and we need to undo that, we need a clean way to remove a dependency.

As a plus, list the orphan dependencies that are still in the manifest file but not anymore referred by the dependencies from `geam.toml` could be also great.

**Comment by digitalcora** [comment]
> As a plus, list the orphan dependencies

I could be mistaken but I think Gleam commands always rewrite the manifest to align with the current `gleam.toml` when it has changed, so the only situation where you'd have "orphan" deps in the manifest is if you edited `gleam.toml` but haven't yet run any commands that would prompt a refresh. IMO this is a better way of handling it (if Gleam never leaves the manifest in an out-of-sync state, you don't need any separate commands to manually fix it).

**Comment by lpil** [comment]
We could have a command to remove the entry from `gleam.toml` though. I don't see any reason why not :)

**Comment by digitalcora** [comment]
Oh yeah, for sure, I would also like a `gleam remove`. Was only commenting on the second part 🙂

**Comment by manuel-rubio** [comment]
I'm sorry, I wasn't aware gleam command do that by default. It's great, and as you said, yes, it's then a matter of only providing the removal for the dependency.
