### ISSUE TITLE
gleam test in new project fails to compile with syntax error

### ISSUE THREAD

**Issue by drmason13** [gleam-lang/gleam#2150]
Hiya, first time user here. I've just installed gleam, erlang and rebar3 on my system following the getting started guide. I installed using cargo with make install:
```
git clone https://github.com/gleam-lang/gleam.git --branch v0.27.0
make install
```

I'm on WSL2, in case that's a known issue.

Then (after a reboot) I setup my first project:
```
:~/gleam$ gleam new jobwalker
Your Gleam project jobwalker has been successfully created.
The project can be compiled and tested by running these commands:

        cd jobwalker
        gleam test

:~/gleam$ cd jobwalker/
:~/gleam/jobwalker (main #%)$ gleam test
  Resolving versions
Downloading packages
 Downloaded 2 packages in 0.19s
  Compiling gleam_stdlib
error: Syntax error
    ┌─ build/packages/gleam_stdlib/src/gleam/dynamic.gleam:136:15
    │
136 │     |> result.try(fn(raw) {
    │               ^^^ I was not expecting this.

Expected one of:
A positive integer or a field name.
```

```
$ gleam --version
gleam 0.27.0

$ erl -version
Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 13.2

$ rebar3 --version
rebar 3.20.0 on Erlang/OTP 25 Erts 13.2
```

Let me know if there's any more information I can provide to help debug.

**Comment by drmason13** [comment]
Might be related to #1992 and a removal of try?

I've also noticed that, whatever I put in my gleam.toml for the gleam_stdlib package, 0.28.2 is installed even though I'm running gleam 0.27.0. It seems that gleam 0.27.0 doesn't understand gleam 0.28.x stdlib, which is fair since it's pre 1.x.

I do think `gleam new` should install a version of the stdlib that's compatible with the installed version of gleam for a smoother onboarding experience for new users.

The for me fix was to simply build the latest version of gleam, git clone the whole repo (not just the 0.27.0 branch) and then install either the current latest version (0.29.0-dev at the time of writing) or perhaps a tagged 0.28.x commit.

I haven't figured out how to downgrade the version of gleam_stdlib that is used by a project.

**Comment by lpil** [comment]
Yup, that's right! The latest version of the stdlib doesn't support historical versions of Gleam. Best upgrade to 0.28.3, the easiest way to do that would be to download one of the precompiled binaries: https://github.com/gleam-lang/gleam/releases/tag/v0.28.3

> I do think gleam new should install a version of the stdlib that's compatible with the installed version of gleam for a smoother onboarding experience for new users.

Unfortunately there's no way to do this without introducing extremely restrictive version constraints, which would cause much larger problems. While we're still rapidly developing Gleam we're opting to only support the current version, and ask users to upgrade.

I'll fix that page to not recommend an old version, it's very misleading as it is currently.

Thanks!
