### ISSUE TITLE
Could `if` statement makes sense here?

### ISSUE THREAD

**Issue by manuel-rubio** [gleam-lang/gleam#2152]
I was reading code like this:
```gleam
  case list.length(events) >= tracker.limit {
    True -> Error(TooIntense)
    False -> Ok(IntensityTracker(..tracker, events: events))
  }
```
Because I came from Erlang and Elixir, I could consider something that's clear to keep it as Erlanger but maybe it could be simplified (my alchemist is yelling about it! :-D ):
```gleam
  if list.length(events) >= tracker.limit {
    Error(TooIntense)
  } else {
    Ok(IntensityTracker(..tracker, events: events))
  }
```
Of course, it should be useful and used for Bool evaluations, what do you think?

**Comment by inoas** [comment]
I'd like an if/else which only takes boolean (no boolish) expressions and short cuts

if foo && bar && quux {
} else {

**Comment by inoas** [comment]
Personally I'd like an if/else
- which only takes boolean (no boolish) expressions
- short cuts
- enforces else
- does not have any elseif feature

```gleam
if foo() && bar() && quux() {
  True
} else {
  False
}
```

...goes into `else` after `foo()` returned `False`.

That being said, except for reserving if and else as keywords this can be added quite easily down the line, and the gains are small I guess, so IMHO this is quite low prio.
