### ISSUE TITLE
Error message improvement for running modules

### ISSUE THREAD

**Issue by dangdennis** [gleam-lang/gleam#2155]
On first encountering `gleam run -m codegen` in the gleam package index, I was unsure what's considered a valid module. I had a file at `src/project_name/x.gleam`. Then I figured I could write `gleam run -m src/project_name/x`. 

This yielded error:
```
error: Module does not exist

Module `src/project_name/x` was not found
Hint: Try creating the file `src/src/project_name/x.gleam`.
```

I think a specific error message can be added that informs gleam users of some these incidental knowledge:
1. only files placed inside `/test` and `/src` are modules
2. you don't need the `src/` or `test/` path prefix

New error message to handle this case. Should handle both /test and /src prefixes accordingly.
```
error: Module does not exist

You are calling a module with `/src` ((replace with /test when appropriate)). 
Only files within /src and /test are valid modules. 
Hint: Try running the file `project_name/the_path/without/src_or_test`.
```

**Comment by lpil** [comment]
Good idea! Thank you.

We could even check to see if it starts with `src` or `test` and recommend the correct value if that module exists.

```
$ gleam run -m src/one/two
error: Module does not exist

No module was found with the name `src/one/two`.

Did you mean `one/two`, from the package `wibble`?
```

**Comment by dangdennis** [comment]
@lpil can you assign this to me? Would like to see it through!

**Comment by dangdennis** [comment]
Gasp there’s a gleam 1.0 milestone

**Comment by lpil** [comment]
Sure thing! Thank you

**Comment by dangdennis** [comment]
@lpil Can you point me in the direction on how to best find if a module is available within the project's dependency graph?

Got the first part done where I handle the src/ and test/ prefixes with the hint using a trimmed version of the module. Looking into the your suggestion now too.

Assuming there's an easy to use API already, I'll likely do that work in the run command handler, and pass the various values along into the `Error::ModuleDoesNotExist`.

**Comment by lpil** [comment]
Fab! Thanks.

Here's where the searching for the module is done:

https://github.com/gleam-lang/gleam/blob/9507ea6876133ee2fc78f2c96db0736b56c03212/compiler-cli/src/run.rs#L43-L48

The logic will want to be something like this:

```rust
if found(module) {
    ok()
} else if (module.starts_with("src/") && found(module.strip_prefix("src/"))) {
    error_about_src_prefix()
} else if (module.starts_with("test/") && found(module.strip_prefix("test/"))) {
    error_about_test_prefix()
} else {
    error()
}
```
