### ISSUE TITLE
Unhide `gleam lsp` command and have it print usage message when run

### ISSUE THREAD

**Issue by chiroptical** [gleam-lang/gleam#2157]
My understanding is that this subcommand was documented at one point, but people would run it and it would appear to hang (because no output was printed).

If an additional log line was printed, like `Starting lsp server...` it should indicate that at least something is happening and CLI users would be less confused.

The biggest issue I can think of is that w/e is printed here could end up in your editor when starting the LSP automatically. Not sure if printing to standard error or out would be better.

**Comment by lpil** [comment]
Good idea!

We'd need to print to standard error because LSP talks over stdio, so printing anything would be invalid and break the protocol.

**Comment by chiroptical** [comment]
I'll try to implement this over the weekend.
