### ISSUE TITLE
LSP: do not provide autocompletions within comments

### ISSUE THREAD

**Issue by Lunarmagpie** [gleam-lang/gleam#2161]
Heres a screenshot of this issue
![image](https://github.com/gleam-lang/gleam/assets/65521138/da4b02f0-1080-4512-9d14-ed38eca51ee1)

Rust's LSP and pylance do not have this behavior. I think that is what gleam should do.

I am on gleam version nightly-230517 installed through asdf.

**Comment by lpil** [comment]
Thanks for the report! The LSP does not yet understand comments, further work on understanding the position of the cursor within code is planned 🙏
