### ISSUE TITLE
Autocompletion does not provide suggestions sometimes

### ISSUE THREAD

**Issue by VlkrS** [gleam-lang/gleam#2167]
I am testing gleam 0.29 autocompletion with helix editor.

When I start entering 

``
  io.pri
``

in line 9 of a gleam source file, I see on the wire:

``
{"jsonrpc":"2.0","method":"textDocument/completion","params":{"position":{"character":8,"line":9},"textDocument":{"uri":"file:///<path_to_file>"}},"id":5}
``

and as a response I see:
``
{"jsonrpc":"2.0","id":5,"result":null}
``

when I completely type

``
  io.println
``

I see

``
{"jsonrpc":"2.0","method":"textDocument/completion","params":{"position":{"character":12,"line":9},"textDocument":{"uri":"file:///<path_to_file>"}},"id":2}
``

and as a response I see

``
{"jsonrpc":"2.0","id":2,"result":[{"detail":"fn() -> fn(String) -> Nil","kind":3,"label":"main"},{"detail": ...
``

From this point on, I can now *delete* characters from the same line and will still receive autocompletions, but it seems to be a precondition to have typed a complete, valid symbol first to make that happen.

**Comment by lpil** [comment]
Hi there! The steps you've given to reproduce the issue don't work for me. Could you provide the code as well please? Thank you.

**Comment by VlkrS** [comment]
Here's the most minimal example that shows this behavior when trying to get autocomplete to propose ``io.println`` in the body of ``main()``:

```
import gleam/io

pub fn main() {
  io.pri
}
```

**Comment by lpil** [comment]
I just tried this with a new project from `gleam new` and I got completions. :(

![image](https://github.com/gleam-lang/gleam/assets/6134406/2a5348a9-ce94-4a87-8e23-ba6597780114)


What was the code the previous time it successfully type checked? I think there's probably some pre-existing state that needs to be set-up.

**Comment by VlkrS** [comment]
NB: I'm seeing this behavior with helix-editor... I can't test on VSCode.

The behavior is the same when I start from a (compiled, running) file:

```
import gleam/io

pub fn main() {
  io.println("test")
}
```

and then insert a new line

```
import gleam/io

pub fn main() {
  io.println("test")
  io.pri
}
```

I'm not an LSP expert, but on the wire it looks pretty much the same, with ```didChange``` events, being sent, Notifications about ```compiling-gleam``` being received, ```publishDiagnostics``` being received (diagnostics make sense, too), ```completion``` requests being sent, but answered with a result of ```null```...

**Comment by yastanotheruser** [comment]
@lpil I replicated this issue on VSCodium. when opening a new line and typing `i` you get the suggestions, you press Escape and open the popup again with Ctrl-Space and you get suggestions again, but if you type `io`, press Escape and then trigger completion again you get no results, I guess this is the case for Helix as well.

**Comment by lpil** [comment]
Ahah! Fab, thank you. I think this is due to the position of the cursor being outside the function as it was last time we got type information from the AST.

**Comment by yastanotheruser** [comment]
yep, and it seems ast updates require both the file is syntactically correct and can be compiled, which is not always the case. not sure how other language servers deal with this.

**Comment by lpil** [comment]
Generally they do the same as we do, only getting new compile information when the code is valid. We're being rather crude in how we use that information currently, we can make the LSP much more robust to further edits.

**Comment by VlkrS** [comment]
@lpil Thanks for fixing that :-)
