### ISSUE TITLE
Compiler crash on `type` with comment and empty line

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#2174]
I have this code that makes the compiler crash:

```gleam
pub type PropertyParameter {
  AlternateTextRepresentation(uri: String)
  CommonName(name: String)
  CalendarUserType(user_type: String) // Default is "INDIVIDUAL"

}
```

The reported information is:

```
compiler-core/src/format.rs:1757
no consecutive empty lines
```

It seems like the problem arises because of the comment and the empty line below, when removing either one of those it works just fine

**Comment by lpil** [comment]
Oops, thank you.
