### ISSUE TITLE
Private function in a public constant is not defined

### ISSUE THREAD

**Issue by greenfork** [gleam-lang/gleam#2178]
```gleam
// src/public_fun_constant.gleam
import public_fun_constant/fun

pub fn main() {
  fun.c()
}

// src/public_fun_constant/fun.gleam
import gleam/io

fn hello() {
  io.println("Hello from public_fun_constant!")
}

pub const c = hello
```

Produces this:

```
 Compiling public_fun_constant
   Compiled in 0.43s
    Running public_fun_constant.main
exception error: undefined function public_fun_constant@fun:hello/0
```

I understand that the value is inlined by the compiler (at least for Erlang target) but maybe there's a solution for this. If the function is supposed to be private, we can put it into `priv/`, so it is not a hard blocker. But probably a clearer error should be in place?

It is also a problem for records that contain private functions.

**Comment by lpil** [comment]
Good find! That's an interesting problem. I'm not sure how we should solve this. It seems like we'll have to in Erlang export "private" functions if they are used in public constants.

Another option is to require referenced functions to be public, which is disappointing in another way.

> If the function is supposed to be private, we can put it into priv/, so it is not a hard blocker. 

The priv directory contains non-code assets, so the contents won't get compiled and loaded. It's for things like images, CSS, etc.

**Comment by greenfork** [comment]
Correction to my `priv/`, I meant `internal/` directory that is not used for documentation generation and is considered "private".

**Comment by JohnBjrk** [comment]
I found a slight variation of this issue today:

# wobble.gleam
```rust
pub type Api {
  Api(method: fn(String) -> String)
}

pub const api1 = Api(impl)

fn impl(s: String) {
  "Prefix " <> s
}
```

# wibble.gleam
```rust
import wobble.{api1}
import gleam/io

pub fn main() {
  api1.method("test")
  |> io.debug()
}
```

When running with:
> gleam run -m wibble

I get the following error:

> exception error: undefined function wobble:impl/1
>   in function  wibble:main/0 (/Users/john.bjork/git/glimt/build/dev/erlang/glimt/_gleam_artefacts/wibble.erl, line 8)

My assumption was that there should be a compile-time error for this (similar to when exposing private types through public function), but if there is a way to make it work without exposing the functions that would be even better.

**Comment by massivefermion** [comment]
> Another option is to require referenced functions to be public, which is disappointing in another way.
Why is it disappointing? As far as I can see, that's just a rename! you can just make the function public and give it the name of the constant. I don't what new capabilities are provided by allowing a public constant refer to a private function!
