### ISSUE TITLE
Improve LSP support for path dependencies

### ISSUE THREAD

**Issue by NthTensor** [gleam-lang/gleam#2185]
Continuing work for https://github.com/gleam-lang/gleam/pull/2153.

The LSP should update gracefully and immediately when the source code of local dependencies changes. This may involve adding a way for multiple LSP instances to coordinate. 

Probably requires #2183 to be implemented first.

**Comment by lpil** [comment]
I think if we had [module level loading in dependency packages](https://github.com/gleam-lang/gleam/issues/2183#issuecomment-1567088917) we could get this for free, the LSP would be able to identify which modules are in need of reloading. I don't think we would need to do any coordination between LSP engine instances in that case.
