### ISSUE TITLE
Convert external functions and types to use attribute syntax

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2193]
Related to, and possibly follows on from https://github.com/gleam-lang/gleam/issues/2191

Old syntax:

```rust
external type Blah

if erlang {
  external fn wibble(Int) -> Int =
    "wobble" "wubble"
}

if javascript {
  external fn wibble(Int) -> Int =
    "./wobble.mjs" "wubble"
}
```

New syntax

```rust
type Blah

@external(erlang, "wobble", "wubble")
@external(javascript, "./wobble.mjs", "wubble")
fn wibble(Int) -> Int
```

We will also want `gleam fix` to update this syntax. https://github.com/gleam-lang/gleam/issues/2194

Prior discussion: https://github.com/gleam-lang/gleam/discussions/2133. Note this does not include the change to the external function syntax.

**Comment by inoas** [comment]
What happend to `external type Blah` - is it implicit that it is an external type, now?

**Comment by lpil** [comment]
Yup, an external type is one that has no constructors in Gleam
