### ISSUE TITLE
`gleam fix` to update external syntax

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2194]
Follows on from https://github.com/gleam-lang/gleam/issues/2193

See the linked issue for details on the new syntax.

One thing we need to think about is that sometimes it might be ambiguous as to whether it is a JavaScript or Erlang external function. What should we do here?

**Comment by inoas** [comment]
> One thing we need to think about is that sometimes it might be ambiguous as to whether it is a JavaScript or Erlang external function. What should we do here?

If in a file both, target erlang and target javascript exist, add the type for both external targets, else only for one. That may not be perfect but good enough?

**Comment by lpil** [comment]
I've let the programmer decide in https://github.com/gleam-lang/gleam/pull/2233
