### ISSUE TITLE
Show tooltips on function declarations

### ISSUE THREAD

**Issue by maxdeviant** [gleam-lang/gleam#2197]
Something that would be very nice to have is showing tooltips when how you hover over function declarations.

If I hover my mouse over the name of a function at its declaration site nothing happens:

<img width="227" alt="Screenshot 2023-05-29 at 10 09 59 PM" src="https://github.com/gleam-lang/vscode-gleam/assets/1486634/53ffb2c3-e1df-42c9-a613-b4797a810797">

But if I hover over the same function at a call site I see a tooltip with some handy information:

<img width="203" alt="Screenshot 2023-05-29 at 10 10 28 PM" src="https://github.com/gleam-lang/vscode-gleam/assets/1486634/3cd67cab-237f-4ea2-8f1a-dc3d6ff4486f">

**Comment by jamesbirtles** [comment]
Seems like this is implemented now
<img width="386" alt="CleanShot 2023-11-02 at 19 26 12@2x" src="https://github.com/gleam-lang/gleam/assets/3743418/53e329bc-2ed2-4362-a9f6-9108f3b0dca5">

**Comment by lpil** [comment]
Thank you
