### ISSUE TITLE
Get rid of duplication of gleam.mjs (the prelude)

### ISSUE THREAD

**Issue by schurhammer** [gleam-lang/gleam#2201]
Currently gleam.mjs is copied into each package/dependency separately so the same code is duplicated many times.
This can lead to pitfalls in FFI code, especially with the `instanceof` operator, not to mention the wasted bytes.

There have been some suggestions to resolve this:

- Move `gleam.mjs` into the parent directory. (my suggestion)
  - e.g. `.../javascript/gleam.mjs` instead of `.../javascript/my_package/gleam.mjs`
  - This means you will have to import `"../gleam.mjs"` in FFI code instead of `"./gleam.mjs"`
- Load `gleam.mjs` into a global variable. (hayleigh's suggestion)
  - e.g. `window.$gleam ??= {...}`
  - This could lead to a conflict if two independent gleam apps are running in the same global scope
- Only the main package gets the "real" `gleam.mjs`, and other packages get a `gleam.mjs` that re-exports the real one. (lpil's suggestion)

**Comment by lpil** [comment]
Thank you 💜
