### ISSUE TITLE
🎨 Format docs type signatures the same `gleam format` does for user code.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#2202]
I find that the way that the documentation generates the type signatures does not match the way code is formatted by `gleam format`. Beyond being a bit triggering, I find it can hurt readability because of _how_ the docs types get rendered.

Consider this function from `nibble/pratt`. In the source code it is formatted like so:
```gleam
pub fn expression(
  one_of first: List(fn(Config(a, tok, ctx)) -> Parser(a, tok, ctx)),
  and_then then: List(Operator(a, tok, ctx)),
  dropping spaces: Parser(Nil, tok, ctx),
) -> Parser(a, tok, ctx)
```
But in the generated docs it is formatted as...
```gleam
pub fn expression(one_of first: List(
    fn(Config(a, b, c)) -> Parser(a, b, c),
  ), and_then then: List(Operator(a, b, c)), dropping spaces: Parser(
    Nil,
    b,
    c,
  )) -> Parser(a, b, c)
```
This is _significantly_ harder to read! It would be great if we just lift the approach taken by `gleam format` and make sure it is also applied to the docs generator.

**Comment by lpil** [comment]
This has been annoying me forever but I never get round to it. Lets get this fixed.
