### ISSUE TITLE
Constant's type is determined only once which causes strange errors

### ISSUE THREAD

**Issue by greenfork** [gleam-lang/gleam#2204]
This code:

```gleam
import gleam/io
import gleam/result

pub fn with_smth(f: fn() -> a) -> a {
  f()
}

pub const with_smth2 = with_smth

pub fn main() {
  use <- with_smth2()
  Ok(Nil)
}

pub fn another() {
  use <- with_smth2()
  Nil
}
```

produces this error:

```
error: Type mismatch
   ┌─ /tmp/const_forward/src/const_forward.gleam:17:3
   │
17 │   Nil
   │   ^^^

Expected type:

    fn() -> Result(Nil, a)

Found type:

    fn() -> Nil
```

The problem is that when this constant is public and used in multiple files, these files fail in random order depending on slight code changes, and the error doesn't give enough context.

**Comment by lpil** [comment]
This is a bug in the type checker, this code should be accepted. Thank you

**Comment by lpil** [comment]
Wicked!

**Comment by lpil** [comment]
Are you planning to look into this @bcpeinhardt ?

**Comment by bcpeinhardt** [comment]
I knew there was one I was missing 😂 I picked up a bunch of issues and then got crazy busy, yes I actually have time today to 😁

**Comment by bcpeinhardt** [comment]
Can you help me understand what you mean by generalizing constants?
What's the goal with this kind of syntax? What sort of pattern does this enable?
Like imagine we had syntax to support this idea of assigning a function as a constant, what would be the difference between
`pub fn identity(foo: a) -> a` and `pub const fn identity(foo: a) -> a`?

**Comment by lpil** [comment]
Generalizing is something that is done in the type inference algorithm to determine the most general type for something.

> What's the goal with this kind of syntax? What sort of pattern does this enable?

There's no new syntax being proposed here, just fixing a bug with existing constants.

**Comment by lpil** [comment]
Are you working on this @bcpeinhardt ?

**Comment by bcpeinhardt** [comment]
Yes sorry!

**Comment by lpil** [comment]
Are you still working on this @bcpeinhardt ?

**Comment by bcpeinhardt** [comment]
You're gonna have to give it to someone smarter and less busy 😂 sorry for wasting so much time with it

**Comment by lpil** [comment]
Type systems are hard! No worries

**Comment by ascandone** [comment]
In case it's useful to anyone, here's a simpler example of the bug:

```gleam
fn id(a) {
  a
}

const idc = id

pub fn main() {
  idc(42)
  idc("42")
  Nil
}
```
error:
```
error: Type mismatch
  ┌─ /Users/alessandro/Documents/dev/prove/playground_gleam/src/playground_gleam.gleam:9:7
  │
9 │   idc("42")
  │       ^^^^

Expected type:

    Int

Found type:

    String
```

Hower it compiles using explicit type annotations:
```gleam
const idc: fn(a) -> a = id
```

**Comment by ascandone** [comment]
Local bindings behave in the same way:
```gleam
pub fn main() {
  let id = fn(a) { a }
  id(0)
  id("")
  Nil
}
```
err:
```
error: Type mismatch
  ┌─ /Users/alessandro/Documents/dev/prove/playground_gleam/src/playground_gleam.gleam:4:6
  │
4 │   id("")
  │      ^^

Expected type:

    Int

Found type:

    String
```


Is it supposed to be an error @lpil ? The [following](https://ocaml.org/play#code=bGV0IG1haW4gKCkgPSAKICBsZXQgaWQgeCA9IHggaW4KICBsZXQgXyA9IGlkIDAgaW4KICBsZXQgXyA9IGlkICIiIGluCiAgKCkKCg%3D%3D) is a valid ocaml program:
```ocaml
let main () = 
  let id x = x in
  let _ = id 0 in
  let _ = id "" in
  ()
```

**Comment by omprakaash** [comment]
Hey can I work on this issue ?

**Comment by lpil** [comment]
Of course! The way to fix it will be to include constants as well in the code that orders functions by their use via a call graph. Once done they'll get generalised correctly.

**Comment by omprakaash** [comment]
Got it. Thanks !
