### ISSUE TITLE
Docs font not loading properly in Chrome

### ISSUE THREAD

**Issue by maxdeviant** [gleam-lang/gleam#2208]
Today I discovered that the font used in the docs generated by Gleam ("Karla") is not loading properly in Chrome.

In docs generated by older versions of Gleam (v0.22) the font is loaded from Google Fonts and loads fine:

<img width="1381" alt="Screenshot 2023-05-31 at 8 58 12 PM" src="https://github.com/gleam-lang/gleam/assets/1486634/226a5eac-3ac1-49c7-8c84-53a2ace0433e">

https://hexdocs.pm/gleam_bitwise/index.css?v=0.22.0-dev

However, when loading docs generated by the current version of Gleam (v0.29) the font is loaded from local font files and does not load fine in Chrome, which results in the docs falling back to the system font:

<img width="1381" alt="Screenshot 2023-05-31 at 8 58 22 PM" src="https://github.com/gleam-lang/gleam/assets/1486634/bd24cda9-72a9-4c70-8a39-5ad02f820339">

https://hexdocs.pm/glenvy/css/index.css?v=0.29.0

While trying to troubleshoot the issue I discovered that docs generated by Gleam v0.29 do show the proper font in Safari:

<img width="1276" alt="Screenshot 2023-05-31 at 9 25 04 PM" src="https://github.com/gleam-lang/gleam/assets/1486634/b6f7bcdf-7079-44eb-b8e9-bca32e9aaecb">

So it seems like a browser-specific issue (at least impacting Chrome, I haven't tested other browsers).

My original Discord post: https://discord.com/channels/768594524158427167/1113633239077240862

**Comment by maxdeviant** [comment]
For context, this is the PR where we switched from loading fonts from Google Fonts: https://github.com/gleam-lang/gleam/pull/1821

**Comment by maxdeviant** [comment]
My browser/system information where I'm seeing the problem:

**Browser:** Google Chrome Version 114.0.5735.90 (Official Build) (arm64)
**OS:** macOS Ventura 13.4 (22F66)

**Comment by NthTensor** [comment]
I am also seeing this difference on Linux with Firefox. It looks like the old version was using the "Karla" family in css but never actually loads that font. Looking at glenvy, I see that the font is being loaded.

Here is what I think is happening: The font you dislike on Glenvy actually is Karla, the one you like better on bitwise is your system font.

**Comment by maxdeviant** [comment]
> Here is what I think is happening: The font you dislike on Glenvy actually is Karla, the one you like better on bitwise is your system font.

I don't think that's the case.

The lowercase `g` in Karla is a pretty telltale sign that the font is being loaded:

<img width="1098" alt="Screenshot 2023-05-31 at 9 33 53 PM" src="https://github.com/gleam-lang/gleam/assets/1486634/3d93cddb-3636-4063-ba9f-a07c25dbf13e">

Which is present in the version that loads correctly (when loading Karla from Google Fonts in Chrome, or when loading Karla locally in Safai). This is when Karla is loaded (which is the font I like):

<img width="1206" alt="Screenshot 2023-05-31 at 9 36 11 PM" src="https://github.com/gleam-lang/gleam/assets/1486634/6870db89-b476-4071-b06d-1f92c4e68540">

The version of the font that I dislike is the system font:

<img width="1381" alt="Screenshot 2023-05-31 at 8 58 22 PM" src="https://github.com/gleam-lang/gleam/assets/1486634/f58204d2-78de-4eaf-baba-3db1610a26aa">

**Comment by NthTensor** [comment]
> I don't think that is the case.

Look at the computed css properties in your inspector. It should underline which of the font-families is actually active out of the fonts list. 

For me at-least, I see that `Karla` is underlined on glenvy ans `sans-serif` is underlined on bitwise.

**Comment by maxdeviant** [comment]
> > I don't think that is the case.
> 
> Look at the computed css properties in your inspector. It should underline which of the font-families is actually active out of the fonts list.
> 
> For me at-least, I see that `Karla` is underlined on glenvy and `sans-serif` is underlined on bitwise.

In Chrome (not sure if that's also which browser you're referring to) there's no discernible difference in the inspector AFAICT.

In Chrome, viewing https://hexdocs.pm/gleam_bitwise/index.html:

<img width="288" alt="Screenshot 2023-05-31 at 9 40 24 PM" src="https://github.com/gleam-lang/gleam/assets/1486634/45cfe7cd-d102-4683-8f4a-615a455e6002">

<img width="496" alt="Screenshot 2023-05-31 at 9 40 49 PM" src="https://github.com/gleam-lang/gleam/assets/1486634/ff85890d-a00d-4891-9b8c-b4f3aa70dcb1">

Karla is being rendered here.

In Chrome, viewing https://hexdocs.pm/glenvy/index.html:

<img width="351" alt="Screenshot 2023-05-31 at 9 41 02 PM" src="https://github.com/gleam-lang/gleam/assets/1486634/61312143-4f14-4a11-8ad9-78cb02612727">

<img width="500" alt="Screenshot 2023-05-31 at 9 41 13 PM" src="https://github.com/gleam-lang/gleam/assets/1486634/e60cea42-0afb-40d3-8f79-33274b806ded">

The system font is being rendered here.

**Comment by NthTensor** [comment]
Ok, I think we are both right. On my machine glenvy is Karla and bitwise is not. I even have that teltail `g`. Very strange.

**Comment by maxdeviant** [comment]
> Ok, I think we are both right. On my machine glenvy is Karla and bitwise is not. I even have that teltail `g`. Very strange.

What browser/OS combo are you using?

**Comment by maxdeviant** [comment]
Installed Firefox just for this, but confirming that Karla is loading/rendering properly in Firefox on macOS:

<img width="1392" alt="Screenshot 2023-05-31 at 9 51 47 PM" src="https://github.com/gleam-lang/gleam/assets/1486634/cdd322a3-825f-4187-8ea7-f5f4da5f317e">

**Comment by NthTensor** [comment]
Firefox/Linux. The weird thing is that Karla is *not* working on bitwise.

**Comment by maxdeviant** [comment]
> Firefox/Linux. The weird thing is that Karla is _not_ working on bitwise.

My first guess would be some sort of cross-site resource blocking.

**Comment by maxdeviant** [comment]
Just noticed that Chrome does has this "Rendered Fonts" bar to show you which font is actually being rendered:

<img width="489" alt="Screenshot 2023-05-31 at 10 00 19 PM" src="https://github.com/gleam-lang/gleam/assets/1486634/9b2606dd-8da7-4b01-bee9-2a88395a723f">
