### ISSUE TITLE
Emit a warning when a .gleam file has an invalid name

### ISSUE THREAD

**Issue by greenfork** [gleam-lang/gleam#2210]
I tried having a file `20230601211333_create_accounts_table.gleam` somewhere in `src/`, it was not compiled to Erlang and LSP didn't see it. After I removed the number prefix from the file name, it became visible. This probably happens because Erlang modules can't start with a number.

I think the compiler should at least emit a warning about such cases. Would be best to include such files in compilation, maybe prefix them with `@` automatically when converting to Erlang modules.

**Comment by lpil** [comment]
I like the warning idea, let's do that.
