### ISSUE TITLE
✨ Allow imports to be aliased with `as _`.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#2236]
This would allow you to do:

```gleam
import wibble.{wobble} as _
```

to effectively hide the `wibble` module, only exposing the `wobble` function. This is particularly useful if there are multiple modules with the same name but you only want to import specific things from each:

```gleam
import mist/internal/handler.{HandlerResponse} as _
import glisten/handler.{HandlerMessage} as _
```

**Comment by thefloofe22** [comment]
Would love to work on this if it's still up for grabs

**Comment by lpil** [comment]
Brilliant, thank you @thefloofe22 !

**Comment by TristanCacqueray** [comment]
Shouldn't the module be implicitly hidden when it is imported with unqualified names? That's how Haskell's import work.

**Comment by lpil** [comment]
No, it should not.
