### ISSUE TITLE
Formatting long case branches with multiple subjects

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#2239]
When the case branches get long and there are multiple subjects the formatter will keep the first one on a single line a split the second arguments on multiple lines:
```gleam 
case one, other {
  gleam.NamedType(one_name, one_module, one_parameters), gleam.NamedType(
    other_name,
    other_module,
    other_parameters,
  ) -> todo("compare named types")
}
```

I feel like it would be better if it first tried to keep the other subjects on single lines as well:
```gleam 
case one, other {
  gleam.NamedType(one_name, one_module, one_parameters)
  , gleam.NamedType(other_name, other_module, other_parameters) ->
    todo("compare named types")
}
```

**Comment by lpil** [comment]
Agreed! Though comma last as that's what we use everywhere else

**Comment by giacomocavalieri** [comment]
I think I want to try and tackle this issue, what should it look like?

```gleam
// 1.

case one, other {
  gleam.NamedType(one_name, one_module, one_parameters),
  gleam.NamedType(other_name, other_module, other_parameters) ->
    todo("compare named types")
}

// With alternative patterns
case one, other {
  gleam.NamedType(one_name, one_module, one_parameters),
  gleam.NamedType(other_name, other_module, other_parameters)
  | gleam.NamedType(one_name, one_module, one_parameters),
  gleam.NamedType(other_name, other_module, other_parameters) ->
    todo("compare named types")
}
```

```gleam
// 2.

case one, other {
  gleam.NamedType(one_name, one_module, one_parameters),
    gleam.NamedType(other_name, other_module, other_parameters)
  ->
    todo("compare named types")
}

// With alternative patterns
case one, other {
  gleam.NamedType(one_name, one_module, one_parameters),
    gleam.NamedType(other_name, other_module, other_parameters)
  | gleam.NamedType(one_name, one_module, one_parameters),
    gleam.NamedType(other_name, other_module, other_parameters)
  ->
    todo("compare named types")
}
```

I'm not a fan of either; I think I prefer the second one when there's no alternative patterns but I do prefer the first one with alternative patterns.
Another minor point in favour of 1 is that it would be super simple to implement while the second one would be a bit more challenging 😁

**Comment by lpil** [comment]
The alternative patterns example of the former is a no-go because it doesn't visually distinguish between multiple subjects and alternative patterns, they're all on the same level. There will need to be indentation or something else to make them scannable. Otherwise both are fine by me.
