### ISSUE TITLE
LSP: Display function signature when hovering over function name at definition site

### ISSUE THREAD

**Issue by palexanderm** [gleam-lang/gleam#2241]
Consider the following as an example:
```gleam
fn first_if_true(test, first, second) {
  case test(first) {
    True -> first
    False -> second
  } 
}
```
Hovering over `first_if_true` doesn't display the function's signature.
The function signature is only displayed when hovering over the function's name at the call site. For example:
```gleam
fn main() {
  first_if_true(fn(a) -> { a > 0 }, 1, -1)
}
```

**Comment by lpil** [comment]
Good idea, thank you!

**Comment by preveen-stack** [comment]
new to gleam; came across a video on youtube interviewing @lpil on gleam. And LSP means?

**Comment by septemhill** [comment]
> new to gleam; came across a video on youtube interviewing @lpil on gleam. And LSP means?

@preveen-stack LSP -> Language Server Protocol

**Comment by inoas** [comment]
This is a great idea!

**Comment by palexanderm** [comment]
I'm not sure how easy this would be to implement, but I came across this cool feature of OCaml's where the function signature is inlined as virtual text next to the function head.
![image](https://github.com/gleam-lang/gleam/assets/61638460/74074ac3-3db8-4a31-ac80-ef9a1b6bfe58)

**Comment by lpil** [comment]
We already have that feature :)

**Comment by palexanderm** [comment]
I should've done a better job at highlighting the feature I was referring to in the screenshot. I'm referring to the the virtual text that's on line 43 where the inferred function signature is displayed to the left.

**Comment by lpil** [comment]
Yes, we have that. You can see it in my screenshot to the right of the list of completion suggestions

**Comment by palexanderm** [comment]
Is there any way for that information to be available inline as virtual text like in the screenshot I posted?

**Comment by lpil** [comment]
No, we don't want to add features that would encourage the programmer to omit annotation for module function arguments and return types.
