### ISSUE TITLE
LSP: Display function signature when passing arguments

### ISSUE THREAD

**Issue by palexanderm** [gleam-lang/gleam#2242]
In instances like such:
```gleam
fn main() {
  do_something(
}
```
it would be nice to have the function signature for `do_something` displayed as you pass in the arguments so as to know the order and type information.

**Comment by lpil** [comment]
This would be fab, let's get this.

**Comment by preveen-stack** [comment]
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/
```
/**
 * Additional details for a completion item label.
 *
 * @since 3.17.0
 */
export interface [CompletionItemLabelDetails](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItemLabelDetails) {

	/**
	 * An optional string which is rendered less prominently directly after
	 * {@link CompletionItem.label label}, without any spacing. Should be
	 * used for **function signatures** or type annotations.
	 */
	detail?: string;

	/**
	 * An optional string which is rendered less prominently after
	 * {@link CompletionItemLabelDetails.detail}. Should be used for fully qualified
	 * names or file path.
	 */
	description?: string;
}
```

**Comment by lpil** [comment]
It's not a completion in this case as there's nothing being suggested that the programmer could select. It may be an InlayHint, but don't know for sure.

**Comment by jamesbirtles** [comment]
I think this would be a `signature help` - https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#signatureHelp

**Comment by lpil** [comment]
Well researched! Thank you

**Comment by giacomocavalieri** [comment]
I'm working on this!

**Comment by giacomocavalieri** [comment]
I'm working on this!
