### ISSUE TITLE
Assign names to sub patterns in string pattern matching

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#2243]
When pattern matching on strings using `<>` it seems it's not possible to assign names to sub patterns:

```gleam
pub fn main() {
  case "foo" {
    "1" as digit <> rest -> todo
  }
}
```

Results in the error:

```text
error: Syntax error
  ┌─ ./src/main.gleam:5:9
  │
5 │     "1" as digit <> rest -> todo
  │                  ^ I was not expecting this.

Expected one of: "->"
```

**Comment by lpil** [comment]
Let's add this!

**Comment by lpil** [comment]
Fab!

You'll want to add a new optional name field to this AST variant: https://github.com/gleam-lang/gleam/blob/23d6800bf1792317cc428e22597912137071c786/compiler-core/src/ast.rs#L1138

Then you'll need to change the parser to accept this: https://github.com/gleam-lang/gleam/blob/23d6800bf1792317cc428e22597912137071c786/compiler-core/src/parse.rs#L992

And lastly a variable needs to be inserted during analysis which has that string prefix as a constant https://github.com/gleam-lang/gleam/blob/23d6800bf1792317cc428e22597912137071c786/compiler-core/src/type_/pattern.rs#L253

**Comment by giacomocavalieri** [comment]
Thank you so much for the useful info! As soon as I have some free time I'll start working on it 💜

**Comment by OndrejValenta** [comment]
I was just wondering what is that code trying to achive? 
i don't mean technically but from programmer's perspective, when would I use it? how?

**Comment by lpil** [comment]
That code example would be very commonly found in a parser where you want to have flow control based on the contents of a string and also save that content so it can be used to produce a token stream, abstract syntax tree, or similar.

**Comment by giacomocavalieri** [comment]
Yes, that was exactly my use case! I had something like this:
```gleam
case string {
  "1" <> rest -> parse_number("1", rest)
  "2" <> rest -> parse_number("2", rest)
  // the same for digits 3 through 9...
}
```

With this It could become
```gleam
case string {
  "1" as digit <> rest
  | "2" as digit <> rest
  // | the same with digits 3 through 9
  -> parse_number(digit, rest) 
}
```

**Comment by timjs** [comment]
Should it be possible to shorten  your example to:

```gleam
case string {
  ("1" | "2" | "3" ) as digit <> rest // And all other digits till 9
  -> parse_number(digit, rest) 
}
```

**Comment by giacomocavalieri** [comment]
For now the compiler doesn't support nested patterns like this, but there was some talk about it on the Discord channel... maybe someone will implement that in the future 😊

**Comment by lpil** [comment]
Once #2091 is merged we'll be in a position to add nested or patterns :)
