### ISSUE TITLE
Bug in gleam format

### ISSUE THREAD

**Issue by bcpeinhardt** [gleam-lang/gleam#2245]
I encountered a bug in gleam format that seems to involve blank lines under a comment at the end of a case statement.
Here is the error message encountered on running `gleam format`:
```
error: Fatal compiler bug!

This is a bug in the Gleam compiler, sorry!

Please report this crash to https://github.com/gleam-lang/gleam/issues/new
with this information and the code that produces the crash.

        compiler-core/src/format.rs:1757
        no consecutive empty lines
```

and some of the surrounding lines of code. 

```
// default add token to html content
    [token, ..rest], ParsingHtmlBlock(html_type, content), acc ->
      r_parse_blocks(
        rest,
        ParsingHtmlBlock(html_type, content <> to_lexeme(token)),
        acc,
      )
  }
  // -------------------- Link Reference Definitions ----------------------------
  

}

// --------------- Block Parser Helpers -----------------------------

fn strip_ending_hashes(input: String) -> String {
  case
    input
    |> string.ends_with("#")
  {
    True ->
      input
      |> string.drop_right(1)
      |> strip_ending_hashes
    False -> input
  }
}
```
The error went away upon removing the spaces beneath the "Link Reference Definitions" comment.

I went ahead and pushed a commit in this structure so you could have full context. Don't judge the code too harshly, it's a work in progress xD You can even see the error in Github actions :)
The commit: https://github.com/bcpeinhardt/dtm/commit/0c3d80bbac43493d4d3434f18b5be7210b5ef335

**Comment by bcpeinhardt** [comment]
Around line 670 btw! Yes it's all one file right now lol

**Comment by lpil** [comment]
Could you try the nightly release please? I think this may already be fixed.

**Comment by bcpeinhardt** [comment]
Will try it asap

**Comment by bcpeinhardt** [comment]
Wait how do I get on nightly gleam lol?

**Comment by lpil** [comment]
If you use asdf it's `asdf install gleam nightly` or you can [download the binary](https://github.com/gleam-lang/gleam/releases/tag/nightly)

**Comment by bcpeinhardt** [comment]
I just built from source and gleam format didn't produce an error so I think this is fixed, gonna close this issue :)
Yeah I switched to a mac (previously had a mac also but running linux) so I had brew installed it. Honestly happy with building from source with cargo because it gives me the flexibility to just test drive any single commit.

**Comment by lpil** [comment]
Fab!
