### ISSUE TITLE
Use US spelling instead of British (`gleam/string.{capitalise}`)

### ISSUE THREAD

**Issue by wilkomanger** [gleam-lang/gleam#2252]
Hi, not sure if there's already a decision made about this, but:

I noticed that [`gleam/string.{capitalise}`](https://hexdocs.pm/gleam_stdlib/gleam/string.html#capitalise) use British spelling. Most programming languages use American (US) spelling, as far as I'm aware. I think it would be good to do this as well, for consistency. Also since Gleam is pre-1.0, I assume breaking changes are less of an issue still :smile: 

I haven't seen any other "violations", but if this would actually be done I'd be willing to look for more.

What do you think?

**Comment by lpil** [comment]
Like Erlang and Elixir Gleam uses regular English rather than American English. It is also a language made in London UK! It is all intentional

**Comment by wilkomanger** [comment]
Alright, makes sense then!
