### ISSUE TITLE
String concat operator precedence

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/gleam#2253]
With Gleam `v0.30.0-rc1`, it seems `<>` no longer has higher precedenge than `|>`, but the formatter still removes `{}` when trying to make it explicit.

This bug can be seen when compiling `glint`, for example.

**Comment by lpil** [comment]
Thank you

**Comment by lpil** [comment]
I've been unable to replicate this. Could you provide the code that causes the issue? Thanks

**Comment by tynanbe** [comment]
https://github.com/TanklesXL/glint/blob/73331261616c61f7aeb325f3f6c29ae0a336169f/src/glint/flag.gleam#L277-L278

**Comment by tynanbe** [comment]
> I've been unable to replicate this. Could you provide the code that causes the issue? Thanks

Upon review, it appears that the formatter doesn't remove the braces with Gleam `v0.30.0-rc1` (there was a `.tool-versions` file in the mix confusing things).

However, the code in question worked with `v0.29.0` and fails to compile with `v0.30.0-rc1`.

**Comment by lpil** [comment]
Fab, thank you.

The parser change is intentional, there was a bug in the old version. The new version is correct.
