### ISSUE TITLE
Assign variables to patterns in case expressions

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#226]
```rust
case x {
| Ok([_ | _] as non_empty_list) -> non_empty_list
| _ -> []
}
```

**Comment by OvermindDL1** [comment]
> `| Ok([_ | _] as non_empty_list) -> non_empty_list`

Why not support the erlang way, where you just specify multiple 'matchers' on the value:

> `| Ok([_ | _] = ["this must be first" | rest] = non_empty_list) -> non_empty_list`

And the beam just tries all the matchers, and thus the `non_empty_list` binding is also 'just a matcher' that matches everything, and thus is bound to everything.

**Comment by lpil** [comment]
What's the advantage of that method? It is more expressive but I don't understand when that expressiveness is useful. Do you have a particular example in mind?

**Comment by OvermindDL1** [comment]
> One reason I prefer the as syntax is that it makes it clearer which side the variable name should be.

You have a uniform syntax, whether it's `[_ |_] = some_list` or [head | tail] = list` or so forth, even better if you combined the guards with it as well without needing them to be separated.
