### ISSUE TITLE
Type inference piping into anonymous function not working

### ISSUE THREAD

**Issue by wilkomanger** [gleam-lang/gleam#2266]
Sorry if this is already on the roadmap :sweat_smile: 

I noticed that with the following code:
```gleam
pub fn piece(board: Board, at coords: Coordinates) -> Option(Piece) {
  board
  |> flatten()
  |> find(fn(square) { square.coordinates == coords })
  |> fn(result) {
    case result {
      Ok(square) -> square.occupied_by
      _ -> None
    }
  }
}
```
Gleam gives me the following error:
```
   │
96 │       Ok(square) -> square.occupied_by
   │                     ^^^^^^ I don't know what type this is
```
It works when I add an explicit type to the `result` parameter.

I would expect the above code to work as-is, since through piping it should be clear what the type of the parameter is already.

**Comment by wilkomanger** [comment]
Would it be possible to change inference order only if necessary in cases such as these?

**Comment by lpil** [comment]
How would you know which order is necessary?

**Comment by wilkomanger** [comment]
In abstract I would say:
1. Infer the function being called
2. Infer its arguments
3. Unknown type error at 2.: Try reverse order inference

Would that work?

**Comment by lpil** [comment]
It might help in some situations, but it would result in Gleam code compilation time being `O(N log N)` rather than `O(N)` with code size. A less expensive approach would is needed.

**Comment by wilkomanger** [comment]
I see, tricky :thinking: Unfortunately I don't know a faster approach atm!

**Comment by lpil** [comment]
Do open a discussion if you have any ideas!
