### ISSUE TITLE
gleam.toml gleam = issue with nightly

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#2270]
> The package glacier requires a Gleam version satisfying >= 0.30.0 but you are using v0.0.0-nightly-230714.

Could it take wildcards?

gleam = ">= 0.30.0 | *nightly*" 
or could the nightly carry at least the current version?

**Comment by lpil** [comment]
Good catch! We'll have to change the nightly format from v0.0.0 to something else.

**Comment by inoas** [comment]
Would something like this work? https://github.com/gleam-lang/gleam/pull/2284/files
