### ISSUE TITLE
gleam publish: Show hint about republishing instead of hexpm library error

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#2271]
gleam publish on the same version should show an hint on how to republish.

Also because hexpm talks about republishing maybe --republish is better than --replace, but that's minor.

## Outdated text

~~For a brief time hex.pm allows republishing on the same version tag it seems, but not gleam publish~~

> error: Hex API failure
> 
> There was a problem when using the Hex API.
> 
> This was error from the Hex client library:
> 
>     must explicitly express your intention to replace the release

~~I'd like to see a --force or --republish or --overwrite tag. I'd prefer --republish.
If given the explicit intention as mentioned in the error would be passed through.~~

**Comment by lpil** [comment]
Thanks!
