### ISSUE TITLE
Function has two inferred signatures

### ISSUE THREAD

**Issue by palexanderm** [gleam-lang/gleam#2275]
I've got a function whose inferred signature is different depending on where I hover over the function call to inspect its signature. Hovering over the recursive call shows the function signature I expect. Hovering over the function when it's called elsewhere (in my case from a public function) shows an incorrect function signature.

This is only the case after I updated to v0.30.0 and was not an issue on 0.29.0.

Here is a screen recording of the issue.
https://github.com/gleam-lang/gleam/assets/61638460/989a0a7f-86e1-404e-86fe-5c7b49bb03f9

**Comment by lpil** [comment]
Thank you! Adding a link to the code for reference

https://github.com/palexanderm/aoc-gleam/blob/main/src/aoc2022/day7.gleam

**Comment by palexanderm** [comment]
This is still an issue for me on the latest version.

**Comment by lpil** [comment]
Thank you

**Comment by palexanderm** [comment]
I'm afraid this remains an issue.

**Comment by lpil** [comment]
This is very funny. I wonder how many compiler bugs I'm going to find from this one bit of code 😁

**Comment by palexanderm** [comment]
The language will likely be perfect after this issue is complete 😆

**Comment by lpil** [comment]
Phew! I think I got it this time :)
