### ISSUE TITLE
`gleam test` shows a bunch of warning on new project

### ISSUE THREAD

**Issue by fmterrorf** [gleam-lang/gleam#2276]
Steps to reproduce

1. Run `gleam new myproject`
2. Run `gleam test`
3. Notice that you'll see a bunch of warning 
![image](https://github.com/gleam-lang/gleam/assets/77761194/50d77989-5314-45e4-a99f-881a45767a4e)

Running `gleam test` again seems to remove the warning. 
Removing the `build` directory and running `gleam test` shows the warning again

**Comment by lpil** [comment]
That's right, that syntax is deprecated. Once people have had time to upgrade their Gleam version we will upgrade packages maintained by Gleam core.
