### ISSUE TITLE
format of location line in error messages

### ISSUE THREAD

**Issue by NobbZ** [gleam-lang/gleam#228]
The current location line wraps the file name in angle brackets followed by line and colum number, separated by colons (`</foo/bar.gleam>:1:1`).

Many editors can make output in a similar form (without the angle brackets) clickable in shell or other sub frames/windows to jump to the error location.

Therefore I suggest removing the angle brackets from the location line.

**Comment by lpil** [comment]
This is the result of the codespan library and I'm unsure how to change this format. If someone can work out the solution I'd happy accept a PR, thanks.
