### ISSUE TITLE
External node:module imports aren't supported

### ISSUE THREAD

**Issue by Nicd** [gleam-lang/gleam#2283]
On Gleam 0.30 the following code will show a compile error:

```gleam
@external(javascript, "node:path", "dirname")
pub fn dirname(filename: String) -> String
```

This results in

```
error: Invalid JavaScript module
  ┌─ /path/to/file.gleam:2:1
  │
2 │ pub fn dirname(filename filename: String) -> String
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The function `dirname` has an external JavaScript implementation but the
module path `node:path` is not valid.
```

`node:<module>` is a valid Node.js import that only resolves to a builtin Node.js module. Looks like additionally you can load `data:` and `file:` URLs, and HTTPS URLs with a custom loader: https://nodejs.org/api/esm.html#urls

As a workaround for internal modules, `node:` can be dropped.

**Comment by lpil** [comment]
Thank you!
