### ISSUE TITLE
gleam test requires erlang-dev on Ubuntu; generates lots of warnings.

### ISSUE THREAD

**Issue by calroc** [gleam-lang/gleam#2285]
Hello,

I just downloaded `gleam-v0.30.3-x86_64-unknown-linux-musl.tar.gz` and put the gleam binary in my `PATH` and attempted to start a new project, but running `gleam test` on the new project generates a lot of warnings then an error:

    $ gleam --version
    gleam 0.30.3
    $ cd Desktop/
    /Desktop$ gleam new g
    Your Gleam project g has been successfully created.
    The project can be compiled and tested by running these commands:

	    cd g
	    gleam test

    /Desktop$ cd g
    /Desktop/g$ gleam test
      Resolving versions
    Downloading packages
     Downloaded 2 packages in 0.25s
      Compiling gleam_stdlib

    warning: Deprecated if syntax
       ┌─ /home/spf/Desktop/g/build/packages/gleam_stdlib/src/gleam/base.gleam:14:1
       │
    14 │ if erlang {
       │ ^^^^^^^^^^^

    This syntax has been replaced by the `@target(erlang)` attribute.

    Hint: Run `gleam format` to auto-fix your code.

    warning: Deprecated external fn syntax
       ┌─ /home/spf/Desktop/g/build/packages/gleam_stdlib/src/gleam/base.gleam:15:3
       │  
    15 │ ╭   external fn do_encode64(BitString) -> String =
    16 │ │     "base64" "encode"
       │ ╰─────────────────────^

    This syntax has been replaced by the `@external` attribute.

    Hint: Run `gleam fix` to auto-fix your code.

    warning: Deprecated if syntax
       ┌─ /home/spf/Desktop/g/build/packages/gleam_stdlib/src/gleam/base.gleam:19:1
       │
    19 │ if javascript {
       │ ^^^^^^^^^^^^^^^

    This syntax has been replaced by the `@target(javascript)` attribute.

    Hint: Run `gleam format` to auto-fix your code.

It goes on like that, and then:

    /home/spf/Desktop/g/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit_ffi.erl:6:14: can't find include lib "eunit/include/eunit.hrl"
    %    6| -include_lib("eunit/include/eunit.hrl").
    %     |              ^

    /home/spf/Desktop/g/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit_ffi.erl:14:6: undefined macro 'assertEqual/2'
    %   14|     ?assertEqual(Expected, Actual),
    %     |      ^

    /home/spf/Desktop/g/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit_ffi.erl:17:6: undefined macro 'assertNotEqual/2'
    %   17|     ?assertNotEqual(Expected, Actual),
    %     |      ^

    /home/spf/Desktop/g/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit_ffi.erl:20:6: undefined macro 'assertMatch/2'
    %   20|     ?assertMatch({ok, _}, A),
    %     |      ^

    /home/spf/Desktop/g/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit_ffi.erl:23:6: undefined macro 'assertMatch/2'
    %   23|     ?assertMatch({error, _}, A),
    %     |      ^

    /home/spf/Desktop/g/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit_ffi.erl:3:2: function should_be_error/1 undefined
    %    3| -export([find_files/2, should_equal/2, should_not_equal/2, should_be_ok/1,
    %     |  ^

    /home/spf/Desktop/g/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit_ffi.erl:3:2: function should_be_ok/1 undefined
    %    3| -export([find_files/2, should_equal/2, should_not_equal/2, should_be_ok/1,
    %     |  ^

    /home/spf/Desktop/g/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit_ffi.erl:3:2: function should_equal/2 undefined
    %    3| -export([find_files/2, should_equal/2, should_not_equal/2, should_be_ok/1,
    %     |  ^

    /home/spf/Desktop/g/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit_ffi.erl:3:2: function should_not_equal/2 undefined
    %    3| -export([find_files/2, should_equal/2, should_not_equal/2, should_be_ok/1,
    %     |  ^

    /home/spf/Desktop/g/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit_progress.erl:10:14: can't find include lib "eunit/include/eunit.hrl"
    %   10| -include_lib("eunit/include/eunit.hrl").
    %     |              ^

    /home/spf/Desktop/g/build/dev/erlang/gleeunit/_gleam_artefacts/gleeunit_progress.erl:8:2: Warning: behaviour eunit_listener undefined
    %    8| -behaviour(eunit_listener).
    %     |  ^

    error: Shell command failure

    There was a problem when running the shell command `escript`.

It wants `eunit/include/eunit.hrl`?  On my system (Ubuntu) that is:

    $ sudo apt-get install erlang-dev

After that the tests pass, but I still get a lot of warnings.  I ran `glean fix` and `glean format` and they went away:

    /Desktop/g$ gleam fix
    All fixed!
    /Desktop/g$ gleam format
    /Desktop/g$ gleam test
      Compiling gleam_stdlib
      Compiling gleeunit
      Compiling g
       Compiled in 0.01s
        Running g_test.main
    .
    Finished in 0.006 seconds
    1 tests, 0 failures

**Comment by lpil** [comment]
Hello! The Erlang package on Ubuntu is incomplete. For some reason they decided to remove some of the packages which comes with the standard Erlang distribution.

The warnings are due to us being in a transition away from a deprecated syntax. The standard library is using the old syntax for a number of weeks in order to give users time to upgrade to the new version of Gleam.
