### ISSUE TITLE
Manifests include absolute paths. Should be relative.

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2286]
We will need a test for this.

**Comment by bcpeinhardt** [comment]
Hello!
Just to make sure I understand this correctly, you're saying path dependencies in the `gleam.toml` can be absolute atm, but you'd like it to be limited to only relative paths and to produce an error when an absolute path is provided?

**Comment by lpil** [comment]
It's that internally the build tool only uses absolute paths but when when it writes manifest.toml it should convert them to be relative to the location of the manifest. When read they should be converted back to absolute.

**Comment by bcpeinhardt** [comment]
Got it that makes sense :) I think I'm gonna take a whack at this in the next couple days.
