### ISSUE TITLE
Update github treesitter based syntax highlightning

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#2287]
Has this been requested with the github team already?

It would be great if the updates were ready before 1.0 so people can browse highlighted code on github when the 1.0 impact hits?

Currently it is heavily broken: https://github.com/gleam-lang/stdlib/blob/main/src/gleam/bit_string.gleam

**Comment by lpil** [comment]
I've not asked for an update yet, but the more folks that ask the better I imagine! The tree sitter repo has some PRs that need to be merged so we'll need the maintainers to release them first
