### ISSUE TITLE
✨ Allow assigning names to string prefix patterns.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#2294]
Gleam allows you to assign names to subpatterns for usage in the expression body using `as`. This is useful for many reasons but one reason is to deduplicate work in combination with alternative clause patterns.

We could write something like:
```gleam
case list {
  [1 as x, ..rest] | [2 as x, ..rest] -> 
    // do something with `x` here

  ... ->
    ...
}
```

Unfortunately, the equivalent for string patterns is a syntax error:
```gleam
case string {
  "a" as x <> rest | "b" as x <> rest ->
    // do something with `x` here

  ... ->
    ...
}
```

Instead, you'd have to write something like:
```gleam
case string {
  "a" <> rest | "b" <> rest -> {
    let assert Ok(#(x, rest)) = string.pop_grapheme(string)
    // do something with `x`
  }

  ... ->
    ...
}
```

Which both duplicates work we've already done and makes the code less immediately clear what it does.

**Comment by giacomocavalieri** [comment]
I've been working on this! The issue is [this one](https://github.com/gleam-lang/gleam/issues/2243)
I think I'm almost done but I didn't get much time to get back to it in the last weeks 🥲

**Comment by hayleigh-dot-dev** [comment]
Oh my bad, awesome! ❤️
