### ISSUE TITLE
Add --no-print-progress flag to gleam run and gleam build

### ISSUE THREAD

**Issue by PastMoments** [gleam-lang/gleam#2299]
This is especially useful for piping program's stdout to other things.

Brief discussion about it here:
https://discord.com/channels/768594524158427167/1139046296439758858

**Comment by lpil** [comment]
Good suggestion, thank you. I think I would like to use a more verbose flag as `--silent` is is more likely to be something the Gleam program would want to use. Perhaps `--no-print-progress`?

**Comment by inoas** [comment]
Would this be only about the stdout infos or also about warnings?

**Comment by lpil** [comment]
Only the progress information, warnings and errors would still be printed.

**Comment by ohamill** [comment]
I'd like to work this ticket, if possible. Should I proceed with naming the flag `--no-print-progress`?

**Comment by lpil** [comment]
Yes please 🙏

**Comment by erikareads** [comment]
I would love this!

**Comment by codereport** [comment]
Not sure if the `--silent` would suppress warnings as well but that would be very helpful.

**Comment by lpil** [comment]
It would not, no.

**Comment by inoas** [comment]
--warnings-as-errors would also be helpful for CI purposes (modifying the posix exit code to be 0)
I am personally agains --no-warnings
