### ISSUE TITLE
Type check results change when functions move around source file

### ISSUE THREAD

**Issue by brunoparga** [gleam-lang/gleam#2303]
The code is at https://github.com/brunoparga/lox, to which I've granted @lpil access.

To reproduce:

* run `gleam check`, it should suceed.
* on `src/interpreter.gleam`, move functions `while_stmt` and `do_while_stmt` below `variable_stmt`, right above `evaluate`.
* `gleam check` now fails.

**Comment by lpil** [comment]
Thanks for the context 👍

**Comment by lpil** [comment]
Hi @brunoparga, I checked out your repo but it seems that the code is different now. How do I reproduce this issue? Thanks

**Comment by brunoparga** [comment]
Hey @lpil . Sorry about that. Now there's a new branch in my repo, https://github.com/brunoparga/lox/tree/typecheck-bug. The instructions in the first post of this thread should suffice for reproducing the bug.
