### ISSUE TITLE
Target not detected with run -m and local dep

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/gleam#2314]
Tried to `gleam run -m rad` after adding rad to `gleam.toml` as a local dep, and `gleam` tried to run it with Erlang (the default target, the current project's target is unspecified); however, rad specifies the JavaScript target via `gleam.toml`.

When fetching `rad` from Hex, it appears to work as expected, `gleam` runs the module with the JavaScript target.

**Comment by lpil** [comment]
Thank you.
