### ISSUE TITLE
LSP: code action to remove unused imports

### ISSUE THREAD

**Issue by TristanCacqueray** [gleam-lang/gleam#2318]
This is a feature request for a new language server code action to remove unused imports. When import are unused, next to the warning, the server should provides an action to delete the lines importing unused module.

**Comment by TristanCacqueray** [comment]
Hi @lpil, during your "Converting a Gleam web application to use the Wisp web framework" stream you mentioned this would be good to have, so I figure this could use a tracking issue. Would this be a candidate for a good-first-issue?

**Comment by lpil** [comment]
Fab! Thank you for making this.

I think it could be a challenging first contribution as we don't have anything like this in the language server presently, but it could be fun and useful :)
