### ISSUE TITLE
Permit `gleam run -m mod_from_some_dep` even when the root package does not compile

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2322]
Currently the full package must compile for `gleam run -m` to compile. Make it so it is possible to run modules from dependencies even when the root package does not compile.

This can be done by skipping compilation of the root package when running a command from outside the root package.

**Comment by hfjallemark** [comment]
Ran into this today when playing around with [squirrel](https://github.com/giacomocavalieri/squirrel) -- if I change my SQL query so that it breaks my app somewhere I can't change the query back and run squirrel again without fixing the broken code in my app (e.g. by commenting it out).

**Comment by giacomocavalieri** [comment]
I can give this a shot!
