### ISSUE TITLE
Rename BitString and BitBuilder

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2328]
The "string" in bit string confuses people often, they thing it is something to do with text strings.

The "bit" in bit builder is misleading as they have to be byte aligned.

`BitString` -> `Bits` ? `BitArray` ? `BitSlice`?

`BitBuilder` -> `BytesBuilder` ? Something else?

**Comment by michallepicki** [comment]
I like `BitArray`

**Comment by inoas** [comment]
- I like ByteBuilder or BytesBuilder, clear +1
- I like Bits, BitSlice sounds strange as I cannot imagine slicing a bit (into what? 0 and 1?)
- BitStrings seem to be called BitArrays [usually](https://en.wikipedia.org/wiki/Bit_array) BitMap would also work maybe. I still favour Bits if it makes sense to you all semantically. It is shorter and my only question would be if it would be ambigious in any way.

**Comment by lpil** [comment]
It's a slice of bits, not a slice of a bit. "Slice" might be more clear than "array" as I think folks tend to think arrays as not being slices of other arrays, but that is always what slices are.

**Comment by bcpeinhardt** [comment]
What do you mean when you say the `BitBuilder` has to be byte aligned? Its seems like I should be able to construct a `BitBuilder` from any `BitString` and append any `BitString`.

**Comment by lpil** [comment]
It'll crash if you attempt to construct a bit string from a non-byte aligned bit builder it'll crash. This is a bug, it should pad to be byte aligned.
