### ISSUE TITLE
LSP: Variables defined using "use" should show the variable type in the tooltip

### ISSUE THREAD

**Issue by schurhammer** [gleam-lang/gleam#2335]
Currently it just shows the return type of the whole `use` expression. When hovering one of the variable names it should show the variable's type instead.

For example below, the tooltip should show `Connection`.

![image](https://github.com/gleam-lang/gleam/assets/2063443/ff51e4d9-931e-4ef0-bdbe-a03a0836f749)

**Comment by lpil** [comment]
Thanks
