### ISSUE TITLE
🐛 `--target` flag is missing from `gleam check`.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#2346]
Not much extra detail to add, looks like we forgot to include the target flag for `gleam check`:

```
$ gleam check --target javascript
error: Found argument '--target' which wasn't expected, or isn't valid in this context

        If you tried to supply `--target` as a value rather than a flag, use `-- --target`

USAGE:
    gleam check

For more information try --help
```

**Comment by lpil** [comment]
Thank you.

**Comment by tinfoil-knight** [comment]
Hey @lpil, can I pick this issue up?

Two minor changes are required:
- Updating the `command_check` function to support the `target` flag in [gleam/compiler-cli/src/main.rs](https://github.com/gleam-lang/gleam/blob/a0ce403e2ca1c2ce8a638f94e04a09ff2e08c310/compiler-cli/src/main.rs)
- Updating CLI reference for the check command in [website/writing-gleam/command-line-reference.md](https://github.com/gleam-lang/website/blob/main/writing-gleam/command-line-reference.md)

**Comment by tinfoil-knight** [comment]
@lpil Just tagging here again in case you missed the notification. I went through https://github.com/gleam-lang/gleam/blob/main/CONTRIBUTING.md & I wanted to confirm if I can start working on fixing this issue.

**Comment by lpil** [comment]
Hi @tinfoil-knight ! Sorry, I did not check my inbox yesterday :)

Yes please! Go for it
