### ISSUE TITLE
Markdown tables don't render in HTML docs

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2347]
When markdown is added to a doc comment it does not render correctly in generated HTML documentation.

```gleam
/// | `under`   | `from`  | `request.path`     | `file`                  |
/// |-----------|---------|--------------------|-------------------------|
/// | `/static` | `/data` | `/static/file.txt` | `/data/file.txt`        |
/// | ``        | `/data` | `/static/file.txt` | `/data/static/file.txt` |
/// | `/static` | ``      | `/static/file.txt` | `file.txt`              |
///
pub fn main() -> Nil {
  Nil
}
```

This should render a table, instead it renders this:

![image](https://github.com/gleam-lang/gleam/assets/6134406/578a2750-0227-4492-a1b4-eac8b94dbdb8)

This may be due to how the markdown parser we are using is configured, or perhaps it doesn't support tables.

**Comment by extsalt** [comment]
Can you provide steps to reproduce this?

**Comment by lpil** [comment]
Of course. I've updated the first post. Thanks
