### ISSUE TITLE
🐛 Hex literals containing `0b` break erlang output.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#2356]
I have a literal like `0xffe0bb` that represents a colour. Emitting erlang with this literal is broken because Gleam thinks the `0b` is the beginning of a second literal and so ends up emitting `16#ffe2#b` which is broken.

**Comment by hayleigh-dot-dev** [comment]
As a temporary workaround you can use capitals to avoid running into this bug.

**Comment by lpil** [comment]
Thank you
