### ISSUE TITLE
slight varitations from rust by using 'case' and '->'

### ISSUE THREAD

**Issue by human154** [gleam-lang/gleam#2364]
Gleam seems to have largely followed Rust's lead with syntax/keyword choices except where that is not possible or the alternative could arguably be said to be "better" or "more suitable", but two things stand out as different: using 'case' instead of 'match' and using '->' instead of '=>'.  

I know there is precedent for using '->' and 'case' in other languages.  But I'm curious as to why almost all other syntax overlaps rust except these items? (I know there are other differences but i can see the reason for them.)

Arguably, following rust on these two points as well would make gleam a tiny bit more learnable and consistent for anyone who has looked at rust or those who switch between rust and gleam.

**Comment by lpil** [comment]
Hello! Gleam the language is not styled Rust at all, any syntax similarities are purely coincidental except for using a `pub` keyword, which was copied from Rust.

**Comment by human154** [comment]
I didn't think any of those langs use fn for functions

**Comment by lpil** [comment]
Elixir does.

**Comment by human154** [comment]
I see, for lambdas, all right, well somehow it turned out that all those combined in a way that looks mostly like rust.

**Comment by lpil** [comment]
Yup! I suspect it might have been that Rust and Gleam drew inspirations from similar places. Both languages were created by OCaml fans who wanted to make a language that was attractive to mainstream audiences.

**Comment by human154** [comment]
I was thinking today that ocaml would make a nice target for gleam! :)

**Comment by lpil** [comment]
No plans for any new targets currently. If we were to add one it would likely be something low level and embeddable, possibly a VM like wasm.
