### ISSUE TITLE
0.32-dev `gleam fix` removing used imports

### ISSUE THREAD

**Issue by rawhat** [gleam-lang/gleam#2368]
I don't really have a good handle on how this sometimes does the correct thing, but sometimes does not.  It occurred in both `mist` and `glisten`.  For example, with the current `glisten` master branch, it makes the following changes (trimmed just for highlighting the difference).

Good:
```
+++ b/src/glisten/acceptor.gleam
-import gleam/option.{None, Option, Some}
+import gleam/option.{type Option, None, Some}
-import glisten/handler.{Handler, HandlerMessage, LoopFn, Ready}
+import glisten/handler.{type HandlerMessage, type LoopFn, Handler, Ready}
```

Bad:
```
+++ b/src/glisten/handler.gleam
-import gleam/option.{Option, Some}
+import gleam/option.{type Option}
```

Good and Bad:
```
+++ b/src/glisten.gleam
-import glisten/acceptor.{Pool, over_ssl}
-import glisten/socket.{Closed, ListenSocket, SocketReason, Timeout}
+import glisten/acceptor.{type Pool, over_ssl}
+import glisten/socket.{type ListenSocket, type SocketReason}
```

It seems to handle mixing type imports and constructor imports no problem.

I can try to come up with a `gleam new` reduced example case for this.

**Comment by lpil** [comment]
Thank you
