### ISSUE TITLE
Inconsistency in error messages for unknown field acces

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#2374]
There's a little discrepancy between two record field accesses depending on the place where it happens:

```gleam
import gleam/io

pub type Person {
  Person(name: String)
}

pub fn main() {
  let person = Person("Rob")
  io.println(person.id)
//           ^^^^^^^^^ Did you mean `name`?
  case True {
    _ if person.id -> todo
//             ^^^ Did you mean `name`?
  }
}
```

When accessing a wrong field in a case guard the error message highlights just the field access, if the same happens anywhere else the whole record is highlighted. I feel like the correct behaviour is the one shown in the guard access given the suggestion.
What do you think?

In any case, if that's the desired behaviour I may already have a fix ready 😁

**Comment by giacomocavalieri** [comment]
Now that I think about it, a possible alternative would be to highlight just the field and not even the dot, like this:

```gleam
pub fn main() {
  let person = Person("Rob")
  io.println(person.id)
//                  ^^ Did you mean `name`?
  case True {
    _ if person.id -> todo
//              ^^ Did you mean `name`?
  }
}
```

@lpil what do you think would be the best behaviour here?

**Comment by lpil** [comment]
Highlighting the field with or without the dot sounds good to me!
