### ISSUE TITLE
Block non-core maintainers from using `gleam_` while `gleam publish`

### ISSUE THREAD

**Issue by Grubba27** [gleam-lang/gleam#2378]
Came here from this [topic](https://erlangforums.com/t/is-there-a-gleam-library-to-read-file-contents/2425/2)  and also because I was creating https://github.com/Grubba27/dotenv_gleam and by mistake published into hex package using the `gleam_dotenv` namespace, when I should be not using this.  

# Expected

When running `gleam publish` should check the name in the `gleam.toml` and do an HTTP check for the users allowed to publish the package with a `gleam_*` namespace

**Comment by lpil** [comment]
Let's make it ask "are you sure? [y/N]" with a bit warning message.
