### ISSUE TITLE
Allow as to take an expression when used together with panic

### ISSUE THREAD

**Issue by tssm** [gleam-lang/gleam#2383]
Currently, `as` only accepts values, not expressions, so the following doesn't compile:

```gleam
panic as { a_value <> " some extra info" }
```

Something like the example below must be used instead:

```gleam
{ a_value <> " some extra info" }
|> io.println_error
panic
```

Honestly, I'm not quite sure how important this is considering how short is the workaround, but I was a bit confused the first time I tried to use an expression here. I guess one could argue that `panic as` isn't a function, so expecting it to behave like one may not make sense.

**Comment by lpil** [comment]
Thank you. I think this is a good idea

**Comment by omprakaash** [comment]
Hey can I take a crack at this issue ?

**Comment by lpil** [comment]
Yes of course! Thank you @omprakaash

**Comment by lpil** [comment]
Thank you!
