### ISSUE TITLE
Bug: LSP gives "Unused imported module" when a module is used in JavaScript only.

### ISSUE THREAD

**Issue by Enderchief** [gleam-lang/gleam#2385]
`$ gleam --version # 0.31.0`

When an imported module is only used in JavaScript, the LSP gives "Unused imported module" yet when the same happens for Erlang there is no message.

### Minimal Example

1. Create an basic project with at least one dependency (ex: `gleam_stdlib`).
2. Open it in an editor that uses the Gleam LSP
3. Populate `main.gleam` with the following
```gleam
import gleam/io
import gleam/float

@target(javascript)
pub fn test() {
  io.println("hello world")
}

@target(erlang)
pub fn test() {
  float.to_string(5.1)
}
```

LSP will complain about `gleam/io` being unused but will not complain about `gleam/float`. Changing the target in `gleam.toml` to javascript does not do anything.

### Intended behaviour
Either it should not complain at all, complain based on the set target or complain with a better message.

**Comment by lpil** [comment]
I have been unable to reproduce this either in vscode or with unit tests. Do you have steps to reproduce this?

**Comment by Enderchief** [comment]
Just to make sure, these are *exactly* what I did.

1. Install Gleam 0.32.0 
I just did this to upgrade Gleam
```sh
git clone https://github.com/gleam-lang/gleam.git --branch v0.32.0
cd gleam
make install
gleam --version
```
2. Verify version using `gleam --version // gleam 0.32.0`
3. `gleam new issue_test`
4. `cd issue_test`
5. ```sh
echo 'import gleam/io
import gleam/float

@target(javascript)
pub fn test() {
  io.println("hello world")
}

@target(erlang)
pub fn test() {
  float.to_string(5.1)
}

pub fn main() {
  test()
}
' > src/issue_test.gleam
```
6. `cat src/issue_test.gleam` to verify contents of the file
7. Open `src/issue_test.gleam` in your editor of choice that uses the Gleam LSP. (I first did `code .` for VSCode, then `helix .` for Helix. 
8. You will see an error from the LSP for line 1 (`import gleam/io`)
```
Unused imported module

This imported module is never used.
```

---

Note: Code runs fine, no issues or warning when doing `gleam run`. It is just the LSP that is unhappy.

**Comment by lpil** [comment]
That showing of a warning is correct, the import is not used in the Erlang target, which is the default.

The bit that is a bug and that I was unable to reproduce was changing the target to JavaScript and it not changing target. Does nothing happen at all when you edit that file?

**Comment by Enderchief** [comment]
ah it doesnt happen to me anymore. must have been a one off with something I did wrong intially
