### ISSUE TITLE
New `type` import syntax — emitted JavaScript does not import types correctly

### ISSUE THREAD

**Issue by MystPi** [gleam-lang/gleam#2386]
I think I can best explain this by giving an example.

`module.bella`:
```gleam
// This import uses the new `type` syntax
import a.{type A, A}

pub fn main() {
  A
}
```

`a.bella`:
```gleam
pub type A {
  A
}
```

And here is the generated JavaScript code for `module.bella`:
```js
import * as $a from "./a.mjs";

export function main() {
  return new A();
}
```
As you can see, the generated code does not import/unqualify the class `A` from `./a.mjs` like it should.

This bug does not occur when using the old import syntax (`import a.{A}`).

**Comment by lpil** [comment]
Thank you.
