### ISSUE TITLE
`gleam lsp` fails to exit

### ISSUE THREAD

**Issue by rawhat** [gleam-lang/gleam#2390]
Hello!

I've been running into this for a while (I think I mentioned it in passing in the Discord at some point).  When I open a project in my editor, and the LSP starts, it does not exit the process when the editor exits.  Also, in the case of `:LspStop` in neovim, it similarly does not exit.

Adding some logging to neovim, it is sending these RPC messages:

```
[DEBUG][2023-11-03 13:44:00] .../vim/lsp/rpc.lua:261	"rpc.send"	{  id = 10,  jsonrpc = "2.0",  method = "shutdown"}
[DEBUG][2023-11-03 13:44:00] .../vim/lsp/rpc.lua:364	"rpc.receive"	{  id = 10,  jsonrpc = "2.0"}
[DEBUG][2023-11-03 13:44:00] .../vim/lsp/rpc.lua:261	"rpc.send"	{  jsonrpc = "2.0",  method = "exit"}
```

Based on my reading of the LSP specification, this _should_ mean that it exits?  Looking at the `lsp-server` crate code, it also definitely should be exiting.  But it definitely does not.  Here is an example when launching a Gleam project with VSCode:

```
hooper ~/gleams/mist (master) γ ps -aux | rg gleam
alex      102877  0.0  0.0   9332  6400 pts/1    S+   13:56   0:00 rg gleam
hooper ~/gleams/mist (master) γ code .
hooper ~/gleams/mist (master) γ ps -aux | rg gleam
alex      103103  0.0  0.0 156160 10848 ?        Sl   13:56   0:00 gleam lsp
alex      103254  0.0  0.0   9332  6352 pts/1    S+   13:56   0:00 rg gleam
hooper ~/gleams/mist (master) γ sudo killall code
[sudo] password for alex:
hooper ~/gleams/mist (master) γ ps -aux | rg gleam
alex      103103  0.0  0.0 156160 10848 ?        Sl   13:56   0:00 gleam lsp
alex      103322  0.0  0.0   9332  6272 pts/1    S+   13:56   0:00 rg gleam
```

This also happens with clean exits, not just with kill, but this was easier to demonstrate.

I did also run into this interacting with the LSP process directly:  https://github.com/spawnfest/rawhat/blob/master/src/rappel/lsp.gleam#L66

I'm confused as well, because I would expect stdio being closed should also cause the process to exit.  But it _really_ doesn't want to haha

Hopefully this is helpful / enough information.  I started poking around for this, but I didn't see anything that immediately jumped out at me.

Thank you!

Edit:  Worth noting I have been seeing this issue for a lot of versions.  So it's definitely not a new issue / regression.

**Comment by lpil** [comment]
That's interesting, it does shut down for VSCode. I wonder what the difference is.

**Comment by rawhat** [comment]
Worth noting, that middle example there is VSCode on Linux, and it doesn't exit.  Not that it's particularly helpful, but it's definitely not just Neovim for me.

**Comment by lpil** [comment]
How does this work then? I use this all the time

https://github.com/gleam-lang/vscode-gleam/blob/b81cf9a415d6e7b5a3d5ba3ac2cead313c1e53e9/src/extension.ts#L34

**Comment by rawhat** [comment]
Dunno for sure exactly, but this might be in play here?  https://github.com/microsoft/vscode-languageserver-node/blob/277e4564193c4ed258fe4d8d405d3379665bbab9/client/src/node/main.ts#L225 looks like it will kill the process if it still detects it running when restarting.

**Comment by rawhat** [comment]
I was going to try to replicate with just a script to make this easier... but now I'm even more confused.

https://gist.github.com/rawhat/1243407b1351b9ad80a0e49423bffbf3

This seems to exit just fine?  Though technically, I think it's not how the spec says it should work (it should send back a response before exiting) but even still.  It shuts down on both `exit` and `shutdown` messages immediately.

**Comment by rawhat** [comment]
https://gist.github.com/rawhat/1243407b1351b9ad80a0e49423bffbf3 I think maybe this replicates the behavior?  It should exit at some point, but it just hangs.

**Comment by lpil** [comment]
Ah yes, that must be it. There is code to shut down in this case, we'll need to add some debug printing to find out what is happening.

https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/language_server/server.rs#L79-L84

https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/language_server/server.rs#L90-L92

https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/language_server/server.rs#L107-L111

**Comment by rawhat** [comment]
Interestingly, it's hanging on joining the threads here:  https://github.com/gleam-lang/gleam/blob/main/compiler-cli/src/lsp.rs#L35

Seems to be about the same structure as `rust-analyzer`, from what I can tell.

It's definitely handling the messages correctly and breaking out of the loop.

**Comment by massivefermion** [comment]
I use vscode on fedora and apparently it happens for me too:
```
ps ax | grep gleam
  10094 ?        Sl     0:19 gleam lsp
  21503 ?        Sl     0:01 gleam lsp
  42683 ?        Sl     0:21 gleam lsp
  49972 ?        Sl     0:11 gleam lsp
 136555 ?        Sl     0:01 gleam lsp
```

**Comment by lpil** [comment]
Ah good detective work! I wonder why that is. I must confess I don't remember what it is that causes the IO threads to exit.

**Comment by rawhat** [comment]
Well, definitely not a rustacean, but I think the issue is caused in some fashion by passing `&Connection` and storing it in the `LanguageServer` struct.  Looking at the `rust-analyzer` code, the use of `Connection` is all in one function that borrows for the receive, and otherwise just uses it as the value for the various send/shutdown methods.

https://github.com/gleam-lang/gleam/blob/main/compiler-cli/src/lsp.rs#L32 adding a `drop(connection);` after this line allows the process to exit correctly.

I started going down the path of having this not take in a reference to verify, but that got ugly quite quickly.  I can at least confirm that the drop works!

**Comment by lpil** [comment]
I'll add that `drop` and we'll see how things are after that.

**Comment by lpil** [comment]
Excellent, thank you both! Made my job very easy.
