### ISSUE TITLE
Compiler bug (JS) - infinite loop when parameter name equal to function name

### ISSUE THREAD

**Issue by melbourne2991** [gleam-lang/gleam#2400]
The following:
```
pub fn map(bp: a, map: fn(a) -> a) {
  map(bp)
}
```

Outputs:
```
export function map(loop$bp, loop$map) {
  while (true) {
    let bp = loop$bp;
    let map = loop$map;
    loop$bp = bp;
  }
}
```

Changing the parameter name resolves the issue.
```
pub fn map(bp: a, inner_map: fn(a) -> a) {
  inner_map(bp)
}
```
```
export function map(bp, inner_map) {
  return inner_map(bp);
}
```

My expectation would be that map within the function body references the map parameter, not the function. The lsp seems to understand this so I'm guessing this is just an issue with the js output.

**Comment by lpil** [comment]
Oh dear! That's a funny bug. I'll get this fixed immediately and publish a new version with the fix.
