### ISSUE TITLE
Float division outputs Erlang code that triggers `0.0` warning

### ISSUE THREAD

**Issue by digitalcora** [gleam-lang/gleam#2403]
I encountered this while installing `stdlib` in a new project using the latest versions of Gleam and Erlang, so I'll use that as an example. The offending Gleam code:

```gleam
pub fn divide(a: Float, by b: Float) -> Result(Float, Nil) {
  case b {
    0.0 -> Error(Nil)
    b -> Ok(a /. b)
  }
}
```

On the Erlang target, this is compiled to:

```erlang
divide(A, B) ->
    case B of
        +0.0 ->
            {error, nil};

        B@1 ->
            {ok, case B@1 of
                    0.0 -> 0.0;
                    Gleam@denominator -> A / Gleam@denominator
                end}
    end.
```

The `/.` operator generates an internal `case` which matches on `0.0`, resulting in this warning from the Erlang compiler:

```
/.../build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@float.erl:165:21: Warning: matching on the float 0.0 will no longer also match -0.0 in OTP 27. If you specifically intend to match 0.0 alone, write +0.0 instead.
%  165|                     0.0 -> 0.0;
%     |                     ^
```

Sidebar: it would be nice if this behavior was documented somewhere other than the [news post](https://gleam.run/news/gleam-v0.13-released/) for the version that introduced it, as it might be surprising to those coming from other languages. Perhaps in the existing Language Tour section about numbers?

Assuming the intent is to match on any signed-ness of `0.0`, having this clause be `D when D == 0.0 -> D` might work to silence the warning, or having separate `+0.0 -> +0.0` and `-0.0 -> -0.0` clauses. (Although, when you divide a negative number by negative zero, should the result be a positive zero? 🤔 Is there even a way for a Gleam user to express or obtain a "negative zero" currently?)

**Comment by lpil** [comment]
Ah thank you!! I've fix this on main and documented it in the stdlib int and float modules.

**Comment by digitalcora** [comment]
Great, thank you 💜

Quick note on the changelog entry for this: The warning actually appears on OTP 26.1+ (the current stable version). It's warning _about_ a change that will occur in OTP 27, which is not released yet. The warning actually may not appear in OTP 27, since then the warned-about behavior will become the "normal" behavior.
