### ISSUE TITLE
Adding autocompletion to gleam-cli

### ISSUE THREAD

**Issue by massivefermion** [gleam-lang/gleam#2409]
I think we can use [this](https://crates.io/crates/clap_complete) to add auto-completion for the `gleam` cli. I'm filing it as an issue so that maybe someone else can pick it up. Although I may find the time to do it myself.

**Comment by lpil** [comment]
Please see this thread for some context on why we are not using Clap to generate completions: https://github.com/gleam-lang/gleam/pull/2231#issuecomment-1594628507
