### ISSUE TITLE
Improve generated types' interop with Deno

### ISSUE THREAD

**Issue by melbourne2991** [gleam-lang/gleam#2410]
Currently if you try and import one of the *.mjs files generated by gleam into Deno directly Deno will ignore the corresponding *.d.mts file.  This leads to a lot of type "holes" that get filled with `any`.

The exact issue is [described in the deno docs](https://docs.deno.com/runtime/manual/advanced/typescript/types):

> This can cause a couple problems though. For example, let's say I want to consume a TypeScript file that has already been transpiled to JavaScript along with a type definition file. So I have mod.js and mod.d.ts. If I try to import mod.js into Deno, it will only do what I ask it to do, and import mod.js, but that means my code **won't be as well type checked as if TypeScript was considering the mod.d.ts file in place of the mod.js file**.

The "fix" (though I'm not sure it's fair to call it that, it's not exactly a bug) - is fairly straightforward and outlined [here](https://docs.deno.com/runtime/manual/advanced/typescript/types#using-the-triple-slash-reference-directive).

Basically each *.mjs file should contain a triple slash directive pointing to its corresponding *.d.mts file

```javascript
/// <reference types="./coolLib.d.ts" />
```

Deno should then use this to resolve the types correctly.

I think this is important for compatibility with Deno given Gleam is supporting Deno as a runtime. This will make the developer experience much smoother. When I first noticed this I initially assumed that perhaps Gleam's type generation was just lacking maturity and was a WIP because the language is relatively new, but Gleam's type generation actually seems fine - the concern is people new to Gleam might jump to a similar assumption.

In the meantime for anyone else facing this issue this is the script I'm using as a stopgap (expects gleam's build/ to be in the current directory):

```typescript
import { WalkEntry, expandGlob } from "https://deno.land/std@0.207.0/fs/mod.ts";
import { basename } from 'https://deno.land/std@0.207.0/path/mod.ts'

const files = await expandGlob("./build/**/*.mjs");
const tasks = []

for await (const file of files) {
  tasks.push(fixTypes(file));
}

await Promise.all(tasks);
console.log("Done!")

async function fixTypes(file: WalkEntry) {
  let content = await Deno.readTextFile(file.path);

  const refTypeStr = `/// <reference types="./${basename(file.path, '.mjs')}.d.mts" />`
  if (content.includes(refTypeStr)) {
    console.log(`Skipping ${file.path} already fixed.`)
    return;
  }

  content = `/// <reference types="./${basename(file.path, '.mjs')}.d.mts" /> \n\n${content}`
  await Deno.writeTextFile(file.path, content);

  console.log(`Fixed types for ${file.path}`)
}
```

**Comment by lpil** [comment]
Good suggestion, thank you!

We'll have to only emit this comment when the typescript definition generation has been enabled as otherwise it'll be pointing to a file that does not exist.
