### ISSUE TITLE
Feature Wisp Web Framework More Prominently And Provide Info On Use With Phoenix

### ISSUE THREAD

**Issue by human154** [gleam-lang/gleam#2415]
As it is, someone could easily miss the announcement of the Wisp web framework when visiting the Gleam website.  The sooner people become aware of it the sooner they might start contributing to it, and also I think this is something people would particularly want to know about. 

It would be great to feature it in the headline of a news update or have it featured even more prominently on the website.

...just an additional thought...it would also be great to address somewhere on the site how Gleam (and/or Wisp) can/cannot be used along with Phoenix and/or Liveview.

**Comment by lpil** [comment]
The Wisp framework is not an Gleam core project so there will be no advertising of it on the Gleam language website. Gleam core doesn't endorse any particular non-core projects.

If you'd like to contribute to the documentation and marketing for Wisp directly that would be fab! 💜

**Comment by human154** [comment]
You seem like my daughter, a little too principled, but I hope it pays off (and it likely will in the long run). 

I created a topic on the Elixir forum:
https://elixirforum.com/t/gleam-has-a-new-web-framework/59874

**Comment by lpil** [comment]
That's great! Thank you!
