### ISSUE TITLE
Warn about redundant assert in let with catch-all patterns

### ISSUE THREAD

**Issue by michallepicki** [gleam-lang/gleam#2419]
This should issue a warning because the `assert` is redundant, it could be simply `let thing =`:
```gleam
import gleam/io

pub fn main() {
  let assert thing = "Hello from hmm!"
  io.println(thing)
}
```

Possibly depends on https://github.com/gleam-lang/gleam/issues/34

**Comment by lpil** [comment]
Thank you. This is actually part of https://github.com/gleam-lang/gleam/issues/34 as it's the same algorithm.
