### ISSUE TITLE
Decide on keywords to reserve for future use

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2421]
Current ideas:

- auto
- derive
- delegate
- else
- implement
- macro
- test

**Comment by massivefermion** [comment]
I know it does not seem likely but may I suggest `unit` just in case [this](https://github.com/gleam-lang/gleam/discussions/1774) pans out?

**Comment by lpil** [comment]
unit seems very niche so I don't think it would be best to reserve.

test is a good suggestion.
