### ISSUE TITLE
Formatter removes string pattern matching aliases

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#2423]
I noticed a strange behaviour in the formatter where it would remove aliases of string literals in pattern matching branches. The formatter turns this:
```gleam
case string {
  "0" as digit <> rest | "1" as digit <> rest -> foo(digit)
}
```
into
```gleam
case string {
  "0" <> rest | "1" <> rest -> foo(digit)
}
```
stripping it of the string aliases

**Comment by lpil** [comment]
Thank you
