### ISSUE TITLE
use assert / exhaustiveness

### ISSUE THREAD

**Issue by inoas-nbw** [gleam-lang/gleam#2431]
@hayleigh-dot-dev wrote:

> `use [x, y] <- whatever(...)`
> here the pattern is not exhaustive, and so will error (or warn at the moment, but eventually error)
> @massivefermion is suggesting the ability to do
> `use assert [x, y] <- whatever(...)`
> the same way you could for let

tag: @massivefermion

**Comment by lpil** [comment]
This won't be added. We don't want to encourage inexhausive patterns
