### ISSUE TITLE
panic as <expr> and the pipe operator

### ISSUE THREAD

**Issue by omprakaash** [gleam-lang/gleam#2440]
Now that the plan is to have panic take an expression (panic as <expr>), how would one ideally deal with a pipe operator chain ? 

The current behavior is this:
"lets"
  |> panic as "panic”. // line 2
  |> panic as "panic"

Output: panic at line      2

In the new version, when there is a pipeline like this:

"lets"
  |> panic as "panic"
  |> panic as "panic"

The parser now takes the whole expression after the first “as” to be the expression, and I think that this messes up the erl syntax generated.

**Comment by lpil** [comment]
Thank you.

**Comment by omprakaash** [comment]
Should I just try to address this in this PR  - #2411. This issue is more of a "future" issue and is not actually not present in the current version of Gleam. Just wanted to clarify the behavior of panic and pipes.

**Comment by lpil** [comment]
Two different PRs please. Smaller changes is always good!
