### ISSUE TITLE
Incorrect arity error reporting wrong number of expected arguments when in pipeline

### ISSUE THREAD

**Issue by matt-savvy** [gleam-lang/gleam#2441]
When missing an argument in a pipeline, the error reports the wrong number of expected arguments.

With this code:
```gleam
import gleam/int.{multiply}
pub fn wrong_arity_pipeline_test() {
  2
  |> multiply()
  |> should.equal(4)
}
```
I get this error
```
error: Incorrect arity
   ┌─ /...
   │
34 │   |> multiply()
   │      ^^^^^^^^^^ Expected 2 arguments, got 0
```
But I should get 
```
error: Incorrect arity
   ┌─ /...
   │
34 │   |> multiply()
   │      ^^^^^^^^^^ Expected 2 arguments, got 1
```

When not using the pipeline syntax, I get the expected error.
```gleam
import gleam/int.{multiply}
pub fn wrong_arity_test() {
  should.equal(multiply(2), 4)
}
```
Gives
```
error: Incorrect arity
   ┌─ ...
   │
28 │   should.equal(multiply(2), 4)
   │                ^^^^^^^^^^^ Expected 2 arguments, got 1
```

```
$ gleam --version
gleam 0.32.2
```

**Comment by lpil** [comment]
Hello! The pipe operator tries a number of different rewrites and uses the one that type checks successfully, so when none of them succeed it returns one of the the error messages arbitrarily.

If we returned one of the other errors it would be more accurate for your specific code, but less accurate other times. Is that better?

**Comment by matt-savvy** [comment]
> If we returned one of the other errors it would be more accurate for your specific code, but less accurate other times. Is that better?

Hmm, I guess it depends on what kind of code it would produce a less accurate error. I honestly would just assume that if nothing type checks, it would use the same error that it would produce if it were non-pipeline syntax.

**Comment by lpil** [comment]
That's it, there is single way to rewrite a pipe expression. Both error messages are equally correct and the compiler doesn't know which one is the one for whatever the programmer had in mind.

**Comment by matt-savvy** [comment]
So in this case, the compiler tries rewriting this 
```gleam
  2
  |> multiply()
```

 as both `multiply(2)` and `multiply()`, can't find a `multiply/1` or a `multiply/0`, but now that it's time to throw an error,  it doesn't know what the intentions were?

**Comment by lpil** [comment]
It rewrites it to `multiply()(1)` and `multiply(1)`. When neither are correct it doesn't know which you meant.

**Comment by matt-savvy** [comment]
Ahh, that makes sense now. I guess my suggestion would be to assume that the author meant `multiply(n)`, but that's just my take.
