### ISSUE TITLE
Direct string-concat pattern-assigment fails (JS target)

### ISSUE THREAD

**Issue by keroami** [gleam-lang/gleam#2443]
```gleam
pub fn main() {
  let assert "Game " <> id = "Game 1"
}
```
fails with `Error: Assignment pattern did not match`, (removing the `assert` does not change the result), whereas
```gleam
pub fn main() {
  case "Game 1" {
    "Game " <> id -> id
    _ -> "ok"
  }
}
```
is fine.

git main dd Dec 3rd
as well as Try Gleam site.

Neither is a problem for the Erlang target.

**Comment by lpil** [comment]
Thank you
