### ISSUE TITLE
Absolute path for local dependency in gleam.toml always resolves dependencies

### ISSUE THREAD

**Issue by erikareads** [gleam-lang/gleam#2448]
## Problem Statement

Having an absolute path for a local dependency leads to Gleam resolving dependencies on every run. This hits the Hex API and can trigger rate limits.

## Expected Behaviour

An absolute path for a local dependency should behave the same as a relative path for a local dependency.

## Reproduction

```
gleam new local_package
gleam new use_local_package
cd use_local_package
```

Add to `gleam.toml`

```toml
local_package = { path = "/absolute/path/to/local_package" }
```

```
gleam run
```

## Additional information

Here is the `GLEAM_LOG=trace gleam run` output truncated to the relevant part:

```
DEBUG download_deps: locking_build_directory path="/home/erika/projects/gleam/use_local_package/build/packages"
TRACE download_deps: reading_file path="/home/erika/projects/gleam/use_local_package/gleam.toml"
DEBUG download_deps: reading_manifest_toml
TRACE download_deps: reading_file path="/home/erika/projects/gleam/use_local_package/manifest.toml"
DEBUG download_deps: manifest_outdated
INFO download_deps: unlocking_stale_package name="local_package"
```

By comparison with a relative path:

```
DEBUG download_deps: locking_build_directory path="/home/erika/projects/gleam/use_local_package/build/packages"
TRACE download_deps: reading_file path="/home/erika/projects/gleam/use_local_package/gleam.toml"
DEBUG download_deps: reading_manifest_toml
TRACE download_deps: reading_file path="/home/erika/projects/gleam/use_local_package/manifest.toml"
DEBUG download_deps: manifest_up_to_date
```

The change in output localizes the issue to within:
https://github.com/gleam-lang/gleam/blob/main/compiler-cli/src/dependencies.rs#L511

Credit to @keroami for reporting the issue in the Gleam discord.

**Comment by erikareads** [comment]
I'm looking into the issue, but I wanted to throw up an issue while I work.

**Comment by erikareads** [comment]
This seems to be a likely culprit [source](https://github.com/gleam-lang/gleam/blob/main/compiler-cli/src/dependencies.rs#L511):

```rust
if manifest.requirements == config.all_dependencies()?
```

https://github.com/gleam-lang/gleam/issues/2286

It's comparing the manifest deps against the config deps to check,
The problem is that the manifest deps are all rewritten to be relative,
whereas the rewriting (probably) hasn't occured in the config.
So they're different, triggering a resolve.

**Comment by erikareads** [comment]
That's exactly what's happening:

```
[compiler-cli/src/dependencies.rs:508] manifest.requirements.clone() = {
    "gleeunit": Hex {
        version: Range(
            "~> 1.0",
        ),
    },
    "gleam_stdlib": Hex {
        version: Range(
            "~> 0.32",
        ),
    },
    "local_package": Path {
        path: "../local_package",
    },
}
[compiler-cli/src/dependencies.rs:509] config.all_dependencies().clone()? = {
    "gleam_stdlib": Hex {
        version: Range(
            "~> 0.32",
        ),
    },
    "gleeunit": Hex {
        version: Range(
            "~> 1.0",
        ),
    },
    "local_package": Path {
        path: "/home/erika/projects/gleam/local_package",
    },
}
```

**Comment by erikareads** [comment]
As compared to the relative path case:

```
[compiler-cli/src/dependencies.rs:508] manifest.requirements.clone() = {
    "gleeunit": Hex {
        version: Range(
            "~> 1.0",
        ),
    },
    "local_package": Path {
        path: "../local_package",
    },
    "gleam_stdlib": Hex {
        version: Range(
            "~> 0.32",
        ),
    },
}
[compiler-cli/src/dependencies.rs:509] config.all_dependencies().clone()? = {
    "local_package": Path {
        path: "../local_package",
    },
    "gleam_stdlib": Hex {
        version: Range(
            "~> 0.32",
        ),
    },
    "gleeunit": Hex {
        version: Range(
            "~> 1.0",
        ),
    },
}
```

**Comment by erikareads** [comment]
Based on this, it seems like

```rust
config.all_dependencies()
```

Should return relative paths.

**Comment by lpil** [comment]
Bravo! Well discovered.

The compiler must use all absolute paths outside of serialization, so a new equality method would need to be created that'll appropriately handle relative and absolute paths.

The manifest must use relative paths because it is to be used on multiple computers which will have different absolute paths.

**Comment by erikareads** [comment]
One possibility is to implement `PartialEq` like we did for `ProvidedPackageSource`:

https://github.com/gleam-lang/gleam/blob/main/compiler-cli/src/dependencies.rs#L602-L625

```rust
impl PartialEq for ProvidedPackageSource {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Local { path: own_path }, Self::Local { path: other_path }) => {
                is_same_file(own_path, other_path).unwrap_or(false)
            }

            (
                Self::Git {
                    repo: own_repo,
                    commit: own_commit,
                },
                Self::Git {
                    repo: other_repo,
                    commit: other_commit,
                },
            ) => own_repo == other_repo && own_commit == other_commit,

            (Self::Git { .. }, Self::Local { .. }) | (Self::Local { .. }, Self::Git { .. }) => {
                false
            }
        }
    }
}
```
I tried this initially, but `is_same_file` requires an actual path, and can't compare invented paths, so a test case failed.

**Comment by erikareads** [comment]
I think I found my mistake, let me try doing exactly that.

**Comment by erikareads** [comment]
I think this is a workable solution:
https://github.com/gleam-lang/gleam/pull/2451

I confirmed that it solves the issue on my minimal reproduction case.

**Comment by michallepicki** [comment]
What is left to do here after https://github.com/gleam-lang/gleam/pull/2451 got merged?

**Comment by keroami** [comment]
seems solved. I changed a rel path to an abs path and I see no "Resolving" in the output of gleam commands. Also, manifest.toml is not being modified. v0.34-rc1

**Comment by lpil** [comment]
Thank you! @michallepicki always has my back with issues 😁
