### ISSUE TITLE
requirements in manifest.toml do not have a fixed order

### ISSUE THREAD

**Issue by keroami** [gleam-lang/gleam#2450]
instead, they seem to swap (reverse?) all the time!

This causes unnecessary changes (and extra git commits or manual work to prevent that).

In addition, when currently using an absolute path in `gleam.toml` (aware of #2286), this is triggering a swap/reverse in manifest.toml for every compile. The change triggers a re-compile in e.g. vs-code, which is... sub-optimal...

**Comment by keroami** [comment]
See also #2448

**Comment by lpil** [comment]
Thank you

**Comment by lpil** [comment]
I believe this to be fixed
