### ISSUE TITLE
compiler doesn't emit warnings about unused recursive functions

### ISSUE THREAD

**Issue by massivefermion** [gleam-lang/gleam#2452]
If you define a private recursive function, the compiler won't emit warnings if you don't use it because apparently the compiler counts the function calling itself as usage!
I tried fixing it, and I figured [this](https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/type_/expression.rs#L1666) is where I need to make the change, but I don't see a way to figure out whether the function is calling itself or not!

**Comment by lpil** [comment]
Aye, this is a known issue. The use detection code will be completely rewritten in a future version to use a reference graph.
