### ISSUE TITLE
Disable redundant case clause warnings from Erlang compiler

### ISSUE THREAD

**Issue by massivefermion** [gleam-lang/gleam#2458]
I just downloaded `v0.33.0-rc2` and ran it on one of my packages and I got this warning:
```
<path>/build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@float.erl:166:21: Warning: this clause cannot match because a previous clause at line 165 always matches
%  166|                     -0.0 -> -0.0;
```
This is the code it's pointing to:
```erlang
-spec divide(float(), float()) -> {ok, float()} | {error, nil}.
divide(A, B) ->
    case B of
        +0.0 ->
            {error, nil};

        B@1 ->
            {ok, case B@1 of
                    +0.0 -> +0.0;
                    -0.0 -> -0.0;
                    Gleam@denominator -> A / Gleam@denominator
                end}
    end.
```

**Comment by lpil** [comment]
The warning comes from the clause being redundant on OTP 26, but it won't be after OTP 27. This code is correct as it is today.

I'm going to move issue to the compiler repo and change it to disabling these warnings in the Erlang compiler now that Gleam has full exhaustiveness checking.
