### ISSUE TITLE
toml configuration support for forgejo/gitea

### ISSUE THREAD

**Issue by sotolf2** [gleam-lang/gleam#2470]
In gleam.toml

Currently to add a repository for codeberg.org for example one has to use 

```repository = { type = "custom", url = "https://codeberg.org/{user}/{project}/" }```

would be nicer to be able to use something like:

```repository = { type = "codeberg", user = "username", repo = "project" }```

to get it on par with github.

**Comment by lpil** [comment]
Thank you! Perhaps we could add these:

```
repository = { type = "codeberg", user = "username", repo = "project" }
repository = { type = "forgejo", host = "example.com", user = "username", repo = "project" }
repository = { type = "gitea", host = "example.com", user = "username", repo = "project" }
```
