### ISSUE TITLE
String alias is always bound to first alternative value

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#2471]
When pattern matching on strings one could assign a name to a constant prefix, for example:
```gleam
case foo {
  "bar" as prefix <> _ | "baz" as prefix <> _ -> prefix
  _ -> "no prefix"
}
```
However, `prefix` is always bound to the first alternative, that is `"bar"` in this example.
For example this is the generated javascript code:
```js
export function go(foo) {
  if (foo.startsWith("bar")) {
    return "bar";
  } else if (x.startsWith("baz")) {
    return "baz";
  } else {
    return "no prefix";
  }
}
```

I've already started working on a fix!

**Comment by lpil** [comment]
Thank you.
