### ISSUE TITLE
Piping into record constructor with record update

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#2474]
When piping into a record that is also being updated with the dedicated syntax, the compiler complains about a syntax error.

```gleam
import gleam/io
import gleam/string

pub type Pet {
  Pet(name: String, voice: String)
}

pub fn main() {
  let pet = Pet("James", "woof")
  string.uppercase("woof")
  |> Pet(..pet, voice: _)
}
```
This is not allowed and results in the following syntax error:
```
error: Syntax error
   ┌─ /src/main.gleam:11:24
   │
11 │   |> Pet(..pet, voice: _)
   │                        ^ I was not expecting this.

Expected one of: 
An expression
```
Is there a reason why this is not allowed?

**Comment by lpil** [comment]
The `_` is for function calls, it doesn't work with any other syntax today. It could be added for some other expressions in future if we decide that is desired, but as it's just sugar that enables nothing new I'm not in any great rush. A discussion on this could be good.
