### ISSUE TITLE
`gleam add` adds wrong constraint to manifest

### ISSUE THREAD

**Issue by aslilac** [gleam-lang/gleam#2476]
Observed using Gleam v0.33.0

Quick repro:

```sh
gleam add simplifile
git add . && git commit
gleam update
git diff
```

**Comment by lpil** [comment]
What is it doing that's wrong?

**Comment by aslilac** [comment]
it'll add a constraint like `0.0.0` instead, which `gleam update` fixes

**Comment by lpil** [comment]
I've not been able to reproduce this. Does it consistently happen for you with those steps?

**Comment by aslilac** [comment]
<img width="372" alt="Screenshot 2023-12-21 at 9 42 00 AM" src="https://github.com/gleam-lang/gleam/assets/418348/a641b99b-1fe1-4f67-b1db-934cdf029028">

very consistently

**Comment by lpil** [comment]
Oh ! This is the manifest. My mistake, I thought it was in `gleam.toml`.
