### ISSUE TITLE
Prevent formatter wrapping lines in multi-line string concatenation.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#2478]
Because Gleam doesn't have string interpolation, the recommended way to inject values into some template is to just use string concatenation.

This means it's plausible to have code that looks something like:

```rs
"pub fn " <> really_long_function_name <> "(" <> lots_of_args <> ") -> " <> a_very_long_return_type <> " {
  ...
}"
```

It's important for legibility that the formatter doesn't start wrapping lines here, because we want to see the template holistically, the same as we would if we had string interpolation. 

In previous versions of Gleam the formatter worked as expected, preserving the formatting above. On 0.33.0, however, the above is now formatted as:

```rs
  "pub fn "
  <> really_long_function_name
  <> "("
  <> lots_of_args
  <> ") -> "
  <> a_very_long_return_type
  <> " {
    ...
  }"
```

This is a real blow for applications that might rely on this sort of injection into templates. I think an interesting rule to explore applying is if any of the strings being concatenated span multiple lines, then the formatter should not attempt to re-arrange things.

**Comment by lpil** [comment]
That first one doesn't respect the line width, it's certainly not an option. The second one looks easier to read for me, and it respects the line width.

What is the format you think would be better?

**Comment by tynanbe** [comment]
Another example @giacomocavalieri asked me to post:

## Now

```gleam
"output=$("
<> command
<> " 2>&1)
status=${?}
printf '%b\n' \"${output}\" \\
  | sed 's/^/"
<> margin
<> "/'
exit ${status}"
```

## Ideal

```gleam
"output=$(" <> command <> " 2>&1)
status=${?}
printf '%b\n' \"${output}\" \\
  | sed 's/^/" <> margin <> "/'
exit ${status}"
```

**Comment by giacomocavalieri** [comment]
Yeah this is really interesting and falls in the category of strings spanning multiple lines Hayleigh referred to in her comment.

An idea I had looking at this example is treating each of the lines of the multi line string as a separate document, it would be fairly easy to get that look then (provided we add a way for the pretty printer to set the indentation to 0 for certain documents, to avoid indenting the lines of a multi line string changing its content)

This is all random ideas but it could be a starting point to look into a new way to format those, thanks @tynanbe for the example!! 💜

**Comment by tynanbe** [comment]
@giacomocavalieri, here's a (possibly) similar example I'll mention here in case the code is related.

## Now

```gleam
[
  "Success!"
  |> ansi(apply: [1, 31]),
  "",
  "Wrote `"
  <> bin
  <> "`, `"
  <> pwsh_bin
  <> "`",
]
```

## Ideal

```gleam
[
  "Success!"
  |> ansi(apply: [1, 31]),
  "",
  "Wrote `" <> bin <> "`, `" <> pwsh_bin <> "`",
]
```

As can be seen, once a list is multiline, string concat is currently always broken up as much as possible.

## Aside

Another possibly related but separate issue that's been discussed before would be placing pipes on the same line when possible. I mention it here in case such formatting might share any logic with multiline strings and lists.

```gleam
[
  "Success!" |> ansi(apply: [1, 31]),
  // ..
]
```

**Comment by giacomocavalieri** [comment]
Aha! I think the first one is a bug with the formatter: once it sees a pipe it decides to break the list but it should reevaluate for each item if break that one as well on multiple lines. Could you open an issue please? I think it could be fairly easy to fix
