### ISSUE TITLE
Formatter wraps operator needlessly

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2480]
Current

```gleam
  Ok(Lesson(
    name: names.name,
    text: text,
    code: code,
    path: chapter_path
    <> "/"
    previous: None,
    next: None,
  ))
```

Expected

```gleam
  Ok(Lesson(
    name: names.name,
    text: text,
    code: code,
    path: chapter_path <> "/"
    previous: None,
    next: None,
  ))
```

When it does not fit it should be indented

**Comment by jonmellman** [comment]
I looked into this a bit,, but I don't think I'm familiar enough with the formatter to fix it. In case it's helpful, here's what I found:

The line break is inserted by the Formatter's `bin_op` function here: https://github.com/gleam-lang/gleam/blob/2b9cd9ea73723e21ed41822d07287904022603bf/compiler-core/src/format.rs#L954

Removing the break would regress a handful of test cases, like:

```diff
Diff < left / right > :
 pub fn main() {
<  int.to_string(color.red)
<  <> ", "
<  <> int.to_string(color.green)
<  <> ", "
<  <> int.to_string(color.blue)
<  <> ", "
<  <> float.to_string(color.alpha)
>  int.to_string(color.red) <> ", " <> int.to_string(color.green) <> ", " <> int.to_string(
>    color.blue,
>  ) <> ", " <> float.to_string(color.alpha)
 }
 


thread 'format::tests::long_comparison_chain' panicked at compiler-core/src/format/tests.rs:5397:5:
assertion failed: `(left == right)`
```


So, I suspect the formatter needs to learn to not break operators _only if_ they're in encountered in constructor and function invocations. (Caveat that I'm new here so I might be off track.)

**Comment by lpil** [comment]
Ah yes, thank you for the investigation @jonmellman . At the same time Giacomo has just make a PR which I believe fixes this. Thanks both!
