### ISSUE TITLE
LSP: inlay hints

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2482]
https://github.com/gleam-lang/gleam/pull/2393

**Comment by omprakaash** [comment]
Hey can I continue working on this ?

**Comment by lpil** [comment]
You can! Thank you

**Comment by omprakaash** [comment]
```c
import mod1.{Value as V1}
import mod2.{Value as V2}

pub fn main() {
  let x: V1 = mod1.v()
  let y: V2 = mod2.v()
  #(x, y)
}```

I am a bit confused on how to handle qualified imports like those In the above code block. Would the inlay-hints for the return type of main be #(V1, V2) or #(Value, mod2.Value) like in the docs.

**Comment by lpil** [comment]
The former, it should be valid code for the file being viewed.

**Comment by septemhill** [comment]
Hi @lpil, should I close https://github.com/gleam-lang/gleam/issues/2319 and use this issue for tracking `inlay hint` feature ?

**Comment by lpil** [comment]
Oh! There's more info in yours so lets use that one
