### ISSUE TITLE
JavaScript target: `gleam.d.mts` should export from `prelude.d.mts`?

### ISSUE THREAD

**Issue by xhh** [gleam-lang/gleam#2487]
For example, file content of `util.gleam`:

```gleam
pub fn hello(result: Result(Int, String)) {
  case result {
    Ok(i) -> i
    Error(_) -> 0
  }
}
```

The generated `util.d.mts`.

```typescript
import type * as _ from "./gleam.d.mts";

export function hello(result: _.Result<number, string>): number;
```

There's an error under `_.Result<number, string>`: `Type 'Result' is not generic.deno-ts(2315)`.

It will be OK if changing the content of `gleam.d.mts` from:

```typescript
export * from "../prelude.mjs";
```

to

```typescript
export * from "../prelude.d.mts";
```

I'm not sure if the above change is correct. If it is, the related source code seems to be at [compiler-core/src/codegen.rs#L218](https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/codegen.rs#L218):

```rust
 fn write_prelude(&self, writer: &impl FileSystemWriter) -> Result<()> {
    let rexport = format!("export * from \"{}\";\n", self.prelude_location);

    writer.write(&self.output_directory.join("gleam.mjs"), &rexport)?;

    if self.typescript == TypeScriptDeclarations::Emit {
        writer.write(&self.output_directory.join("gleam.d.mts"), &rexport)?; // <==========
    }
    Ok(())
}
```

**Comment by lpil** [comment]
I'm not very familiar with this TypeScript feature, but I believe you are right and this is a bug. Would you mind making a PR? Thank you.
