### ISSUE TITLE
Formatter: removes @external line without gleam def

### ISSUE THREAD

**Issue by keroami** [gleam-lang/gleam#2490]
when I add `@external(erlang, "module" "fun")` but not yet the gleam declaration `pub fn mod_fun() -> Type`, the formatter removes the `@external` line.

Then I have to type it again.

**Comment by lpil** [comment]
Thank you. This should be a parse error.

**Comment by abs0luty** [comment]
I can work on this one

**Comment by lpil** [comment]
Massivefermion is working it currently!

**Comment by abs0luty** [comment]
Ok :3

**Comment by michallepicki** [comment]
I think this can be closed now since https://github.com/gleam-lang/gleam/pull/2497 got merged?

**Comment by keroami** [comment]
checked w/ 0.34.rc1
format does not do anything, as it is (now) a syntax error.
Closing.
