### ISSUE TITLE
`gleam format` breaks up function call strangely when close to line length

### ISSUE THREAD

**Issue by rawhat** [gleam-lang/gleam#2496]
Hello!  Tagging @giacomocavalieri as discussed in the Discord.

The line is formatted like this:

```gleam
let assert Ok(new_stream) =
  stream.new(identifier, settings.initial_window_size, handler, conn,
  )
```

It seems like this should either put the closed paren on the same line, or just break out the arguments into separate lines.  The latter is what happens when I make one of the variable names longer.

Thank you!

**Comment by lpil** [comment]
Oh yes, this is a bug. Thank you

**Comment by giacomocavalieri** [comment]
Working on it! I have a simpler example that gets formatted badly:
```gleam
pub fn main() {
  function_call(that, is, super, close, to, the, max, line, limit, of, 80, chars,
  )
}
```
It looks like it's a problem of function calls and how `NextBreakFits` works by interfering with the normal splitting of a group.
