### ISSUE TITLE
Warn for unused function body

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#2499]
A function with an external implementation can still define a default implementation to be used on other targets:
```gleam
@external(javascript, "foo", "bar")
pub fn foo() -> Int {
  // Implementation that is going to be used on the
  // Erlang target.
  11
}
```
When a function defines an external implementation for all the possible targets its body is never going to be used anywhere:
```gleam
@external(javascript, "foo", "bar")
@external(erlang, "foo", "bar")
pub fn foo() -> Int {
  // This is dead code since there already is an
  // external implementation for all targets.
  11
}
```
This could result in an error/warning so that unused code doesn't go undetected. Not sure if it should be an error or warning though, I'm leaning towards warning similarly to unused module functions/constants though

**Comment by abs0luty** [comment]
I can work on this one

**Comment by lpil** [comment]
After more thought I've realised this means it's not possible to write a library such that it continues working if new targets are added. I'm going to revert this warning to permit this.
