### ISSUE TITLE
Error message for using a function in `case` guard clause is unhelpful

### ISSUE THREAD

**Issue by erikareads** [gleam-lang/gleam#2509]
Guard clauses (`if` inside a match arm) do not allow functions, the current error message doesn't adequately communicate this to the user:

```rust
import gleam/io
import gleam/string

pub fn main() {
  let my_string = "hello"
  case my_string {
    _ if string.length(my_string) > 2 -> io.debug("doesn't work!'")
  }
}
```

```
error: Syntax error
  ┌─ /src/main.gleam:7:23
  │
7 │     _ if string.length(my_string) > 2 -> io.debug("doesn't work!'")
  │                       ^ I was not expecting this.

Expected one of: 
"->"
Hint: Did you mean to wrap a multi line clause in curly braces?
```

Can we improve this to call out the specific error: that we're trying to use a function in a guard clause?

**Comment by abs0luty** [comment]
I can work on this one!

**Comment by abs0luty** [comment]
Added this error message:

```
error: Syntax error
  ┌─ /src/parse/error.gleam:4:21
  │
4 │   _ if string.length(my_string) > 2 -> io.debug("doesn't work!'")
  │                     ^ Call expression used in case `if` guard clause

Equality and comparison of numbers is all that can be used in an `if` guard clause.
See: https://gleam.run/book/tour/case-expressions.html#checking-equality-and-ordering-in-patterns.
```

**Comment by kwshi** [comment]
What is the rationale for this being disallowed, by the way? This feels natural to have to me.

**Comment by lpil** [comment]
It's not supported by the virtual machine. Largely the only operations it supports are constant time, which helps with how it optimises the performance of pattern matching.

**Comment by wmstack** [comment]
I also think the compiler saying
```
expected one of:
"->"
```
is not reasonable when there is only a single expected item. It should be

```
expected "->"
```
