### ISSUE TITLE
🔧 Change `build` in gitignore to `/build`

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#2517]
[lustre_ssg](https://github.com/lustre-labs/lustre_ssg) recommends writing your build script in a file called `build.gleam`. It's not uncommon to want to have some utils/functionality just for build-related things and these naturally end up in a `src/build/` or `test/build/` directory.

The current gitignore means anything in those folders will be ignored and this has tripped me a up a few times before I've realised they're not being tracked!

I think it would be better if the generated `.gitignore` were more specific and only ignored `./build` instead.

**Comment by lpil** [comment]
Sounds good!

**Comment by steven-mathew** [comment]
Hi, I'd like to have a go at this!
