### ISSUE TITLE
gleam docs build excludes functions which only @target a different target

### ISSUE THREAD

**Issue by erikareads** [gleam-lang/gleam#2523]
If a gleam module has functions that only exist for other targets, no documentation is generated for those functions.

## Example

```rust
import gleam/io

pub fn main() {
  io.println("Hello from docs_explore!")
}

/// A function that I care about
/// Only exists for the javascript target
@target(javascript)
pub fn my_function() {
}
```

![image](https://github.com/gleam-lang/gleam/assets/130414394/4189e0f6-4afc-4c48-8e20-81fa5cd983a0)

For libraries that need to support heterogeneous target APIs, I would like to be able to communicate to users that a function only exists for one target.

**Comment by lpil** [comment]
Yes, that is right. Having differing APIs between targets is strongly discouraged and it's unlikely any work will be done to support that.
