### ISSUE TITLE
Gleam not reporting an error when using function unsupported by target

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2531]
```gleam
import gleam/erlang/process

pub fn main() {
  process.sleep(1000)
}
```
```
gleam test --target javascript
```

fyi @giacomocavalieri. Let me know if you'd like to look into this or if I should.

**Comment by giacomocavalieri** [comment]
I can look into it!

**Comment by lpil** [comment]
Thank you 💜

**Comment by giacomocavalieri** [comment]
Ok, it looks like the supported targets are not getting narrowed down correctly if the function is called preceded by the module name:
```gleam
import gleam/erlang/process.{sleep}

pub fn main() {
  sleep(1000)
}
```
Should fail with the correct compilation error.
I'm working on a fix :)

**Comment by lpil** [comment]
Dang you work so fast!!
