### ISSUE TITLE
Bit Array errors still point to bit-string link

### ISSUE THREAD

**Issue by erikareads** [gleam-lang/gleam#2536]
The parser errors for `BitArray` point to the "bit-string" language tour link:

https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/parse/error.rs#L82-L99

Specifically this one: https://gleam.run/book/tour/bit-strings.html

The documentation now mentions Bit Arrays, but the table of contents:
![image](https://github.com/gleam-lang/gleam/assets/130414394/5244c815-d1ed-4286-b452-d735ea3361be)

And the title: 
![image](https://github.com/gleam-lang/gleam/assets/130414394/557340ea-8512-4cb7-b38b-2f8b328f8e12)

And the link: 
![image](https://github.com/gleam-lang/gleam/assets/130414394/144a29fc-d07c-4f05-a300-87c8d23c557c)

all still refer to bit strings.

This may be confusing, since we don't have bit strings anymore.

**Comment by lpil** [comment]
Thank you
