### ISSUE TITLE
(Docs theme) Search bar should have a darker background 

### ISSUE THREAD

**Issue by MystPi** [gleam-lang/gleam#2540]
Currently, the search bar in generated docs has a `transparent` background. This impacts discovery and makes the bar harder to find.

![image](https://github.com/gleam-lang/gleam/assets/86574651/614d18cf-ba9e-455a-8b08-d4283feb7dd6)

The color of the bar when `active` is perfect.

![image](https://github.com/gleam-lang/gleam/assets/86574651/b895f814-1ab8-40d2-bfb1-0ddee4a169e2)

I think that the bar should be that color regardless of when active or focused. The icon should still change color and the page should still be dimmed. Like this:

![msedge_gGuMRWvpI7](https://github.com/gleam-lang/gleam/assets/86574651/e8b6eab8-0eb2-41da-a9bb-cb59b3c0c9db)

I am happy to submit a PR for this if approved!

**Comment by lpil** [comment]
Could be good! I'm interested in what others think

**Comment by lpil** [comment]
Seems like a popular suggestion in discord!

**Comment by MystPi** [comment]
> Could be good! I'm interested in what others think.
> 
> What about in the light mode?

Same thing in the light mode. Since it uses CSS variables it wouldn't require extra work to support both.
