### ISSUE TITLE
Add deprecation to module constants

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#2544]
Right now module constants can be annotated with the `@deprecated` annotation but that won't result in a warning if someone tries using a deprecated constant:
```gleam
@deprecated("don't use this, it's evil")
pub const evil_hello = "hello 😈"

pub fn main() {
  io.println(evil_hello)
}
```
Compiles with no warnings

**Comment by lpil** [comment]
Oh yes! Good idea! Thank you
