### ISSUE TITLE
SyntaxError: Unexpected reserved word -> fs = await import("fs");

### ISSUE THREAD

**Issue by verbus** [gleam-lang/gleam#2547]
All,
it clone https://github.com/gleam-lang/gleam.git --branch v0.34.0
cd gleam

# Build the Gleam compiler. This will take some time!
time make -j 12 install

# Run cargo test
cargo test

# Verify the compiler is installed
# Prints "gleam $VERSION"
gleam --version

exit 0

All is good up to this point.
----

And the not so good....

$cd gleam

$ make test
.
.
.

test/language on JavaScript with Node
cargo run --quiet -- test --target javascript --runtime nodejs
  Compiling language
   Compiled in 0.05s
    Running language_test.main
file:///home/verbus/gleam/test/language/build/dev/javascript/language/ffi_javascript.mjs:4
  fs = await import("fs");
       ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
make[1]: *** [Makefile:16: nodejs] Error 1
make[1]: Leaving directory '/home/verbus/gleam/test/language'
make: *** [Makefile:21: test] Error 2

**Comment by lpil** [comment]
Hi there! Thanks for trying Gleam.

Gleam targets JavaScript, but the version of NodeJS you are using doesn't implement the spec correctly. Judging by <https://node.green/> you're using a version that is over 8 years old and is no longer supported by the NodeJS team. If you upgrade to a version that is still supported by them then you'll be able to run the compiled Gleam code.
