### ISSUE TITLE
New logo and mascot

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2551]
Hello! 💖 

The Gleam project could do with a new logo and mascot as the current one isn't as legible and popular as we'd like it be.

This is an open source project of volunteers and we have little to no budget for this work, so we're treating this like all other aspects of the project and relying on the kindness and enthusiasm of the open source community.

We'd like to develop a new logo and mascot in conjunction with the community, finding something that fits right in with us and our vibe :) 

# The selection process

We'd like to iterate on designs here and on [the Gleam discord](https://discord.gg/Fm8Pwmy). Once we have some potential options we'll solicit a final round feedback from the community before the Gleam core team makes the final decision, likely going with whichever is most popular with the community.

# Vibes

Gleam is all about friendliness, both technologically and socially. We're proud of how supportive and enjoyable and cosy our community is, and it's important to us that all manner of folks feel welcome, especially those from under-represented groups in tech such as but not limited to trans people, and black people and women. We also want it to be clear to troublemakers and hateful people that they would not fit in and are not welcome.

The pink branding is intended to communicate these values, and we want a cute logo and mascot that also communicates this.

The current branding can be seen on the website, including Lucy the star, the current logo. https://gleam.run/

# Goals

We want the mascot and logo to be clearly identifiable as whatever it is, and also distinctly as Gleam.

We want the mascot and logo to be usable at all sorts of different sizes, from a tiny website favicon, to printed on a t-shirt, to projected onto a conference wall during a presentation.

The logo and the mascot don't have to be the same thing or a variation on each other, but we certainly want to have something for each.

I think a low colour count (or low colour count version) would be desirable such that the logo and mascot can work in more places, such as other websites with different branding. We'd have vector versions of the images to ensure highest quality whatever the size, and to avoid having to have the work redrawn.
I'm not a designer though, so perhaps I'm wrong with how this works.

# Animals

Here's some animals that have come up in discussion

## Flamingo

Pink and fabulous

## Inca Tern 

Has a fancy moustache

![image](https://github.com/gleam-lang/gleam/assets/6134406/5d1b4798-9814-4dbf-9b32-c1936c356d9a)

## Seahorses

Fits alongside Erlang's unofficial squid mascot. Erlang being the parent language of Gleam.

Small bioluminescent sea creatures are quite Gleamy.

## Jellyfish

Similar to seahorses! Bioluminescent!

## Starfish

A continuation of the current logo. 

# Prior art

Original branding thread: <https://github.com/gleam-lang/gleam/issues/84>

Here's some existing logos and mascots that I like

## Alpaca language

![image](https://github.com/gleam-lang/gleam/assets/6134406/b20fa156-08e2-42f9-ba54-c5dd605ba551)

## Go language

![image](https://github.com/gleam-lang/gleam/assets/6134406/81ae5af4-78d8-4085-b9e0-f828d8ba9b10)

One thing that is really cool about Go is how the mascot can be adopted by Go projects

![image](https://github.com/gleam-lang/gleam/assets/6134406/5890562b-b689-43e1-b74e-8ffd281f0c2f)

## Pikelet language

![image](https://github.com/gleam-lang/gleam/assets/6134406/1f3b3310-43ad-4dd9-a36e-d6ab3983e3b7)

## Hy language

![image](https://github.com/gleam-lang/gleam/assets/6134406/9e6391bb-f27e-4562-8704-6c7fb42708ac)

## Rust language
Not much of a link between their logo and their mascot, and that's OK!

![image](https://github.com/gleam-lang/gleam/assets/6134406/eeb0b412-19ca-4953-8e7b-f03247ee76e3)

![image](https://github.com/gleam-lang/gleam/assets/6134406/49eaa4a9-b0da-492c-b328-c03128b03d95)

## Ash framework (Theo's mascot)

![image](https://github.com/gleam-lang/gleam/assets/6134406/35830673-f157-4a7c-aa25-20d1ba977d62)

## Witchcraft framework

![image](https://github.com/gleam-lang/gleam/assets/6134406/5bf9c941-112e-4d19-b1ff-0bee590dc47f)

![image](https://github.com/gleam-lang/gleam/assets/6134406/cc585930-eba7-4f20-b07c-9d77d56ffebd)

## Fly platform and their blog artwork

![image](https://github.com/gleam-lang/gleam/assets/6134406/a31a2701-f29a-4e5b-a203-2bb1c420c687)

![image](https://github.com/gleam-lang/gleam/assets/6134406/29eb9dd4-94a7-4c52-9460-4b7fb098ce55)

**Comment by tynanbe** [comment]
As Louis mentioned, apart from the gleamingo (possibly a flamingo wearing shades), I was mostly interested in small, biolominescent sea creatures (hopefully precluding the horrifying sort).

### Sea stars and sea horses both have some fitting representatives.

One difficulty is the word Gleam doesn't easily lend itself to a square/round shape (e.g. avatars, favicons), but it might work to get creative with letter arrangements, such as pairing Gl, ea, and m, with the "ea" stacked above the "m." I don't see a problem with using just the mascot or iconographic part of a logo for those cases though (like Witchcraft does).

## Here's a very rough sketch for the concept of "sea star as A."

![gleam_logo_draft](https://github.com/gleam-lang/gleam/assets/38031130/baa8b74f-8a65-4cf8-b541-73d8275a05fe)

## Here are some inspirational images.

![RTAB4Xbyc](https://github.com/gleam-lang/gleam/assets/38031130/c26332a9-1b1b-48c7-9cec-c1bee97105f3)
![Aquarium-Luminous-Seahorse-Ornament-Glow-In-Dark-Landscaping-Silicone-Sea-Horse-Glowing-Fish-Tank-Decoration-Hippocampus](https://github.com/gleam-lang/gleam/assets/38031130/abf7583c-c61a-40e6-86e1-21f3e12a0f2d)
![starfish on reef seacoast](https://github.com/gleam-lang/gleam/assets/38031130/5434ef0b-30e8-40c3-af77-10055aeae66e)
![starfish-x-ray-scott-camazine](https://github.com/gleam-lang/gleam/assets/38031130/5013c8c7-1b1b-49f8-ae63-68b0450e1606)
![clan-neon-starfish-dozen-glow-pretty-pink-under-lights-aquarium-55447665](https://github.com/gleam-lang/gleam/assets/38031130/829e0504-aefb-4dc1-977c-5cb5a30505be)
![192fd72d204e48d22105a9c179fde5aa](https://github.com/gleam-lang/gleam/assets/38031130/a05d4f54-db90-4b43-bf5f-eabab8a9a551)
![close-up-of-orange-starfish-on-sand-489010151-59847f7f22fa3a0010518acc](https://github.com/gleam-lang/gleam/assets/38031130/59fcbdb8-030c-4b06-ab11-41075233a76b)
![96a0b435321a0d1d5164cec851e823e7](https://github.com/gleam-lang/gleam/assets/38031130/f5ed1e8e-a970-4c0f-b544-81a4132c3280)
![53112bf9b075947fbdc6db330c39c906](https://github.com/gleam-lang/gleam/assets/38031130/edd0cfa9-098e-452f-9bc5-c4daa959cadf)
![02-logo](https://github.com/gleam-lang/gleam/assets/38031130/e08f3509-d8fc-49f9-a1a5-3224b42fbf9f)
![Zodiac Signs Animals](https://github.com/gleam-lang/gleam/assets/38031130/f5364ecc-5599-4cf3-89c5-2702a41a77a7)
![Zodiac](https://github.com/gleam-lang/gleam/assets/38031130/14831ce7-a4ee-42ce-8161-397675c2d239)

**Comment by treuks** [comment]
gotta love the jellyfish concept, 
they're brainless (the language is simple)
they can be glowey and shiny (gleamy as one might say)
and they're also pink.

im sure someone could come up with some kind of a cute way to do a jellyfish

![image](https://github.com/gleam-lang/gleam/assets/18615981/1b43634a-1c8b-4279-b524-1f41e17c7bae)

**Comment by Theosaurus-Rex** [comment]
Hey there! Bear with me as I'm on mobile, Australian internet is terrible.

Here's a few sketches as were riffed on over in the discord, the seahorses seem to be a fan favourite so far 
![Untitled_Artwork_2](https://github.com/gleam-lang/gleam/assets/71990001/f3fb04fb-285f-40b4-9f34-f710f14eb13c)
![Untitled_Artwork_3](https://github.com/gleam-lang/gleam/assets/71990001/2e0728bf-27da-4328-8449-9dcd99675426)
![Untitled_Artwork_4](https://github.com/gleam-lang/gleam/assets/71990001/ffbca11c-170d-44b4-ab9c-812f813c95d5)
![PXL_20240118_064551683](https://github.com/gleam-lang/gleam/assets/71990001/c8ebfd3b-3ce4-43b2-be54-0ff6c9ef4f24)
![PXL_20240118_064543128](https://github.com/gleam-lang/gleam/assets/71990001/5fb938a4-8ad0-4fdc-8ea7-b71c219a37db)

**Comment by MystPi** [comment]
I'm a huge fan of the second image's seahorses—so cute! I could easily see those becoming Gleam's mascot.

**Comment by DanielSherlock** [comment]
It's not the cute direction the new logo/mascot is going in, but I had fun breaking out the felt-tips and colouring pencils to see how my what-if-Lucy-was-a-flamingo idea I had a couple days ago would look.

![flamingo-edited](https://github.com/gleam-lang/gleam/assets/7683894/4c19b071-167c-4843-a837-b4a1cfa0209f)

**Comment by Theosaurus-Rex** [comment]
> It's not the cute direction the new logo/mascot is going in, but I had fun breaking out the felt-tips and colouring pencils to see how my what-if-Lucy-was-a-flamingo idea I had a couple days ago would look.
> 
> ![flamingo-edited](https://private-user-images.githubusercontent.com/7683894/298162933-4c19b071-167c-4843-a837-b4a1cfa0209f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MDkzMTAsIm5iZiI6MTcwNTcwOTAxMCwicGF0aCI6Ii83NjgzODk0LzI5ODE2MjkzMy00YzE5YjA3MS0xNjdjLTQ4NDMtYTgzNy1iNGExY2ZhMDIwOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMDAwMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTIyNzY5Y2E1ODFjZThlYWQ2OWY5NjgwMWI0ZDk0OTg1OGU3MDE4YTM3ZjkwYTI4MmVmOGI3ZDZiNmQyZDJiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qWTEQ4QsfLyNtGJcaWnCCMvjRjBa1F6a9URHXpKAbrc)

I love this! I feel like something like this could work super well as a logo in conjunction with a matching mascot with a more complex and characterized design maybe? But it's such a good vibe ✨

**Comment by lpil** [comment]
hemarkable on twitter says:

> I honestly like Gleam's mascot which looks like Staryu. Maybe giving few more features to your Staryu could be enough?

More Pokemon! 💜

**Comment by synecdokey** [comment]
This is my lunch break contribution to this, it's highly unrefined, and lacks a mascot. Probably needs thicker strokes for low-size legibility, and tweaking the colours slightly, but here we go! I liked the idea of a 'beam' of light, with added sparkles for good measure. Keeps the gleam pink, but with a blue sky, and white sparkles that stand out.
![IMG_1564](https://github.com/gleam-lang/gleam/assets/58845835/ed65f89a-ec74-4d79-b52d-f6520029f884)

**Comment by nadavhames** [comment]
Maybe the style for a fun, cute mascot can be similar to this panda from https://panda-css.com
![panda-bubble-tea](https://github.com/gleam-lang/gleam/assets/25757773/722699e9-f1ce-4a2d-8ca0-9acdd272d67d)

**Comment by massivefermion** [comment]
I'm just gonna put this here as part of my lobbying efforts for marine creatures

![ezgif-1-fc2831a270](https://github.com/gleam-lang/gleam/assets/25373436/0ce1176f-d355-4d2b-bac5-60f86ddc0202)

**Comment by ORESoftware** [comment]
Flamingo dancing with Starfish!!

**Comment by suppyluppy** [comment]
[a bit of an infodump here so take your time]

I'm not really a programmer by profession, but I do love making art related to programming, especially with the mascots. Here's my take on the Gleam mascot, a somewhat cute, glow-in-the-dark starfish. The second option is a starfish that ended up looking like a gemstone-thing (I don't know, looks weird). 

![image](https://github.com/gleam-lang/gleam/assets/151646109/791d3ad9-6b4e-4925-9db6-3ea2c2850f33)

I tried playing around with the starfish's expressions, to see if things just fit for some reason. Note that this isn't the final design, and I made this under an hour for fun.

Forgive me if the colors look a little lighter (technical issues, I guess). And forgive me if I don't seem to be kind (this is the first time I've posted something here, so something of a new experience to me).

(Sidenote here if you love some trivia, the current working name for the starfish is Aster).

**Comment by lpil** [comment]
Wow that's really nice @suppyluppy ! I love how expressive the face is while still managing to be super simple.

To me it looks like Lucy (the existing star mascot) in a new style?

**Comment by Theosaurus-Rex** [comment]
Just dropping some of the other sketches I put in the discord but forgot to post here.
Working on getting these into high-fidelity digital drawings

![image](https://github.com/gleam-lang/gleam/assets/71990001/06708fcc-6d40-4d87-9b9d-8c189c7e28dd)
![image](https://github.com/gleam-lang/gleam/assets/71990001/1935d6fc-2915-46b5-aada-ac672036d654)
![image](https://github.com/gleam-lang/gleam/assets/71990001/890a591d-5430-4279-8d3d-2643634fce51)
![image](https://github.com/gleam-lang/gleam/assets/71990001/056938ce-a50a-4785-bbca-5cfad9c19106)
![image](https://github.com/gleam-lang/gleam/assets/71990001/606beae1-6cc2-42d5-9fa8-1a08fa109845)

**Comment by lpil** [comment]
Hi @suppyluppy ! I'd love to talk to you about this stuff! Perhaps DMs on discord (lpil) or via email (louis@gleam.run)?

**Comment by kamikyoku** [comment]
Alright, so to re-introduce myself, I made the current version of the pink starfish, Lucy. I know that the issue is closed now, and now that the new Lucy has become canon, but I'm here to say thank you to everyone here (and the contributors, and the community), for the love and support you all have given to (dearest) Lucy, and a belated congratulations (i'm so sorry) on the 1.0.0 release! 

I'm planning to do a Q&A about Lucy, but that's for another time (and if anyone is interested)...

**Comment by TanklesXL** [comment]
@kamikyoku  would you be amenable to us updating the link to your profile on the v1 blog post? It currently points to [suppyluppy](https://github.com/suppyluppy) which returns a 404

**Comment by kamikyoku** [comment]
I guess not. I appreciate the credit, but for some reason, I don't want people to know me as "that one who made the cutesy pink starfish from a coding language". It's better to not do anything with it.

**Comment by kamikyoku** [comment]
Thank you so much, everyone!!!

@ffigiel First of all, thank you for telling me about this Lucy project. Lucy is now Lucy. Aster has turned into Astra, her current middle name.

Shout-out to @0xca551e for the "n-sided Lucy"! There's a few easter eggs here and there. Blinking Lucy, "kiki-bouba" reference (I guess all the parameters have "special values" when you put them to each end). I'm going to have a fun time giving suggestions for this one (such as making Lucy glow).

I've heard some interest in merch as well, but I think that's for another time!

**Comment by versecafe** [comment]
@kamikyoku Do you have an svg for Lucy I'm adding a bunch of language icons to [Zed](https://github.com/zed-industries/zed) for newer and or more obscure languages and can't find an svg for Lucy since they're so new

### Sad IDE Without Lucy
<img width="266" alt="image" src="https://github.com/gleam-lang/gleam/assets/147033096/3047f822-5d2a-4cf4-b37a-cecce58d225e">

**Comment by ffigiel** [comment]
@versecafe you can find various SVGs here https://gleam.run/branding/
