### ISSUE TITLE
Codegen (JS) for exhaustive case expression still includes error branch

### ISSUE THREAD

**Issue by wezm** [gleam-lang/gleam#2556]
This may be intended/expected behaviour but I thought I'd mention it. Looking at the generated JavaScript for this example https://tour.gleam.run/flow-control/list-recursion/ I thought it was curious that there is an `else` branch even though the `case` is exhaustive. My expectation was that there would be no `else`. The main drawback to this I see is when targeting front-end JavaScript it will add to code size for each `case` expression. 

### Input

```gleam
import gleam/io

pub fn main() {
  let sum = sum_list([18, 56, 35, 85, 91], 0)
  io.debug(sum)
}

fn sum_list(list: List(Int), total: Int) -> Int {
  case list {
    [first, ..rest] -> sum_list(rest, total + first)
    [] -> total
  }
}
```

### Output

```js
import * as $io from "../gleam_stdlib/gleam/io.mjs";
import { toList, makeError } from "./gleam.mjs";

function sum_list(loop$list, loop$total) {
  while (true) {
    let list = loop$list;
    let total = loop$total;
    if (list.atLeastLength(1)) {
      let first = list.head;
      let rest = list.tail;
      loop$list = rest;
      loop$total = total + first;
    } else if (list.hasLength(0)) {
      return total;
    } else {
      throw makeError(
        "case_no_match",
        "list_rec",
        9,
        "sum_list",
        "No case clause matched",
        { values: [list] }
      )
    }
  }
}
```

### Env

`gleam --version`: gleam 0.33.0 (although this was built from the Gleam 0.34.1 AUR package)

**Comment by lpil** [comment]
Hello! Yes good catch, thank you. This will be part of this work: https://github.com/gleam-lang/gleam/issues/2549

I'll leave this open to make doubly sure.

**Comment by wezm** [comment]
Yay! Thank you.
