### ISSUE TITLE
Function capture syntax incorrectly accepts discard patterns instead of just _

### ISSUE THREAD

**Issue by Nicd** [gleam-lang/gleam#2560]
Example code:

```gleam
let _score = 1000
io.println(_score)
io.println("Foo")
```

This will print only `Foo` and result in no error output or compiler warning. To the user it _looks_ like `_score` is being used as a variable and then as a function argument. But what happens in reality is

```gleam
// Throw away 1000
// Generate fn(a) { io.println(a) } and throw it away
io.println("Foo")
```

Would it be possible to warn in this situation? When we notice that `_score` is matching some discarded pattern. This would leave the door open for typos, though, i.e. `io.println(_socre)` would lead to the same situation before the user notices the typo.

Alternatively the support for labeling function capture arguments could be dropped and only `_` allowed.

A third alternative is to use a different character for function capture (probably not desirable, just throwing it out there).

**Comment by lpil** [comment]
It is only supported to support _, this is a parser bug. Thank you.
