### ISSUE TITLE
Do not render arguments as discarded in HTML documentation

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#2561]
The following code produces a warning from the LSP and the compiler:
```gleam
@external(javascript, "./client-component.ffi.mjs", "register")
pub fn register(app: App(Nil, model, msg), name: String) -> Result(Nil, Error) {
  Error(NotABrowser)
}
```

The warning is that `app` and `name` are unused in the body of the function and should be ignored. This is a problem because if suppress this warning by writing `_app` and `_name` _now the generated documentation implies these parameters are unused_:

<img width="739" alt="image" src="https://github.com/gleam-lang/gleam/assets/9001354/a909335e-651c-4e9e-a797-b8e718f6aa53">

For now I have resigned to just ignoring the warning, but it would be great if it could go away entirely: the argument is used just Gleam can't know about it.

**Comment by lpil** [comment]
The warning is to remain, it is the html docs that are wrong here. They expose far too much about the implementation and need to be rewritten to stop sharing all this information.
