### ISSUE TITLE
🐛 Cannot run a dependency's module if my project can't compile to its target. 

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#2568]
## The problem

Lustre ships with it a tiny web server to make onboarding for folks new to lustre/frontend really easy. The web server is written in _erlang_ but a user's project will be targeting _javascript_. If the user's project includes code that is only compilable on the javascript target, attempting to run

```
gleam run -m lustre/try
```

won't work because Gleam attempts to compile _everything_ with the erlang target and the user's project is not compatible.

## What I'd expect

I'd expect Gleam to compile _lustre_ (and any of its dependencies) with the erlang target and leave the users project untouched. As it stands, the majority of lustre projects will never be able to use this feature now because they will have javascript-specific code in them.

**Comment by lpil** [comment]
Ah! This is a bug. Let's get it fixed ASAP.
