### ISSUE TITLE
Odd formatter behavior on custom types with functions

### ISSUE THREAD

**Issue by jclem** [gleam-lang/gleam#2571]
Given the following unformatted source code:

```gleam
pub fn into_string() {
  Builder(
    accumulator: "",
    update: fn(accum, val) { accum <> val },
    final: fn(accum) { accum },
  )
}
```

...the Gleam formatter (v0.34.1) formats it into this, which (subjectively, but probably for most) is far less readable:

```gleam
pub fn into_string() {
  Builder(accumulator: "", update: fn(accum, val) { accum <> val }, final: fn(
    accum,
  ) {
    accum
  })
}
```

**Comment by jclem** [comment]
Thanks @giacomocavalieri and @lpil!

**Comment by giacomocavalieri** [comment]
Always happy to help with the pretty printer! 💕

**Comment by lpil** [comment]
@giacomocavalieri gets all the credit !
