### ISSUE TITLE
Unused type variable in alias type definition currently accepted without comment

### ISSUE THREAD

**Issue by DanielSherlock** [gleam-lang/gleam#2578]
In the following definition of a type alias, the type variable `a` is not used in the right hand side:

```gleam
type Something(a) = Nil
```

The compiler does not complain about this in any way.

---

Unlike phantom types in record type definitions, this seems like it is always a mistake (or an incomplete implementation).

This is because - as an alias - it is happy as long as the relevant types have the same internal implementation. For example, this code typechecks and runs as it should (but would be unsatisfactory / confusing for someone who wanted it to produce a type error):

```gleam
import gleam/io

type Something(a) = Nil
type X
type Y

fn return(arg : Something(X)) { arg }

pub fn main() {
  let this : Something(Y) = Nil
  io.debug(return(this))
}
```

(Note that if you wanted to use "phantom types in aliases"  like this you might also try to make your alias type opaque, which the compiler _does_ currently complain is nonsense.)

---

I think an unused type variable in an alias type declaration could be a warning, parallel to the "unused variable" warning. @hayleigh-dot-dev says that in Elm it gives a full error.

**Comment by lpil** [comment]
Thank you. I think this should be an error.

**Comment by abs0luty** [comment]
I can take this one!

**Comment by lpil** [comment]
Thank you!

**Comment by lpil** [comment]
I'm gunna pick this one up now, thank you 🙏
