### ISSUE TITLE
usage not propagated/counted for aliased funcs/types

### ISSUE THREAD

**Issue by sdancer** [gleam-lang/gleam#2579]
```
import gleam/erlang/atom.{type Atom, create_from_string as atom}

```

throws a warning, create_from_string is unused

**Comment by lpil** [comment]
Thank you.

**Comment by lpil** [comment]
Thank you.

This system is due to be replaced with a proper reference graph based approach so we can either fix it or replace it. Both are good solutions.

**Comment by lpil** [comment]
Closing to track in other issue
