### ISSUE TITLE
build order of modules not stable

### ISSUE THREAD

**Issue by sdancer** [gleam-lang/gleam#2595]
currently when refactoring, the compiler errors on file "seemingly" in random sequence like [a,b,a,c,a,b] given 3 modules that depend on a module that changed its api
an idea would be to raise the last failing module as high as the dep tree permits on the subsequent build

**Comment by lpil** [comment]
Hello! What version is this with?

**Comment by sdancer** [comment]
0.34.1 vanilla

**Comment by lpil** [comment]
Could you test with the rc please? I believe this is fixed.

**Comment by sdancer** [comment]
sure will try, however deterministic to a machine doesn't mean best human experience
