### ISSUE TITLE
`v1.0.0-rc1` lsp crash!

### ISSUE THREAD

**Issue by massivefermion** [gleam-lang/gleam#2596]
I just opened `ranger` in vscode and this happened! Didn't make any change to the code, so to reproduce it you could just open [ranger](https://github.com/massivefermion/ranger). If that doesn't do it, you could just make the lsp to format the code(I just make a minor change and save the file).
I should also mention that running `gleam build` does not result in a crash!

>  INFO language_server_starting
> Hello human!
> 
> This command is intended to be run by language server clients such
> as a text editor rather than being run directly in the console.
> 
> Many editors will automatically start the language server for you
> when you open a Gleam project. If yours does not you may need to
> look up how to configure your editor to use a language server.
> 
> You can exit this program by pressing ctrl+c.
> 
>  INFO creating_new_language_server_engine path="<path>/ranger"
>  INFO compile{package=gleam_stdlib}: analysing_modules count=0
>  INFO compile{package=gleeunit}: analysing_modules count=0
>  INFO compile{package=ranger}: analysing_modules count=2
> error: Fatal compiler bug!
> 
> This is a bug in the Gleam compiler, sorry!
> 
> Please report this crash to https://github.com/gleam-lang/gleam/issues/new
> and include this error message with your report.
> 
> Panic: compiler-core/src/exhaustiveness.rs:434
> 	Unexpected pattern Tuple { elements: [Id { idx: 0 }, Id { idx: 1 }] }
> Gleam version: 1.0.0-rc1
> Operating system: linux
> 
> If you can also share your code and say what file you were editing or any
> steps to reproduce the crash that would be a great help.
> 
> You may also want to try again with the `GLEAM_LOG=trace` environment
> variable set.
> 
> error: Fatal compiler bug!
> 
> This is a bug in the Gleam compiler, sorry!
> 
> Please report this crash to https://github.com/gleam-lang/gleam/issues/new
> and include this error message with your report.
> 
> Panic: /cargo/registry/src/index.crates.io-6f17d22bba15001f/lsp-server-0.7.6/src/stdio.rs:28
> 	receiver was dropped, failed to send a message: "SendError(..)"
> Gleam version: 1.0.0-rc1
> Operating system: linux
> 
> If you can also share your code and say what file you were editing or any
> steps to reproduce the crash that would be a great help.
> 
> You may also want to try again with the `GLEAM_LOG=trace` environment
> variable set.
> 
> [Info  - 8:58:50 PM] Connection to server got closed. Server will restart.
> true

**Comment by lpil** [comment]
Thank you. Closing this in favour of https://github.com/gleam-lang/gleam/issues/2599 as it has a reproduction.
