### ISSUE TITLE
exaustiveness panic (rc 1.0)

### ISSUE THREAD

**Issue by sdancer** [gleam-lang/gleam#2599]
extracted code

```
import gleam/option

pub type TableItem {
  TableItem(
    index: Int,
    name_kr: String,
    name: String,
 )
}

type Something {
  Something(a:Int, b: option.Option(TableItem), c: Int)
}

fn crashme(old_equip: Result(Something, Nil)) { 
  case old_equip {
   Ok(Something(
      a: a,
      b: option.Some(TableItem(index: index, ..)),
      ..
    )) ->
      index
   }
} 
```

**Comment by sdancer** [comment]
the panics could include where appropriated the environment.current module, which otherwise needs to be added to narrow down the issue

**Comment by hayleigh-dot-dev** [comment]
Adding on to say that compiling [birdie](https://github.com/giacomocavalieri/birdie) results in this crash too:

```
DEBUG compile{package=birdie}: Type checking module="birdie/internal/diff"
error: Fatal compiler bug!

This is a bug in the Gleam compiler, sorry!

Please report this crash to https://github.com/gleam-lang/gleam/issues/new
and include this error message with your report.

Panic: compiler-core/src/exhaustiveness.rs:434
        Unexpected pattern Tuple { elements: [Id { idx: 1 }, Id { idx: 2 }, Id { idx: 3 }, Id { idx: 4 }, Id { idx: 5 }, Id { idx: 6 }] }
Gleam version: 1.0.0-rc1
Operating system: macos
```

**Comment by lpil** [comment]
> the panics could include where appropriated the environment.current_module, which otherwise needs to be added to narrow down the issue

This is already done via Gleam's logging 👍

@hayleigh-dot-dev is that just compiling birdie or is it a dep? Is the project being freshly compiled or did you make other steps to get there? Does it persist after running clean to remove the build directory?

**Comment by hayleigh-dot-dev** [comment]
- birdie was a dep
- the project was last compiled on 0.34.1 before the panic
- after `gleam clean` the project successfully builds

**Comment by sdancer** [comment]
```
This is already done via Gleam's logging 👍```
its not immediately visible, as u can see in the example posted by hayleigh
