### ISSUE TITLE
(Generated docs) Pages generated from markdown have incorrect indentation

### ISSUE THREAD

**Issue by MystPi** [gleam-lang/gleam#2617]
It looks like doc pages generated from markdown (such as a package's readme or lustre's new quickstart) have the first indentation level as only one space instead of two in code examples. Other indentation levels appear to be fine.

From Glen's readme:
![image](https://github.com/gleam-lang/gleam/assets/86574651/074f0821-ca5d-4e86-aff6-351ad3a0df69)

From Lustre's quickstart:
![image](https://github.com/gleam-lang/gleam/assets/86574651/4773e56a-9808-470c-8ed0-8c2bd9da3167)

It doesn't look like this happens in pages generated from source files.

**Comment by lpil** [comment]
Thank you
