### ISSUE TITLE
Gleam compiler issue with lustre RC version specified

### ISSUE THREAD

**Issue by rawhat** [gleam-lang/gleam#2618]
Hello!

I am trying to test out the latest `lustre` release candidate.  I have set the version to this in my `gleam.toml`:

```toml
lustre = "4.0.0-rc1"
```

With both Gleam `v0.34.1` and `v1.0.0-rc2` I get similar output:

```
hooper ~/projects/spades/client (with-lustre*) δ gleam build
  Resolving versions
error: Fatal compiler bug!

This is a bug in the Gleam compiler, sorry!

Please report this crash to https://github.com/gleam-lang/gleam/issues/new
with this information and the code that produces the crash.

        /cargo/registry/src/index.crates.io-6f17d22bba15001f/pubgrub-0.2.1/src/internal/partial_solution.rs:131
        add_derivation should not be called after a decision
```

It works with a version without the `rc1` specified, i.e. `= "3.1.4"` is okay.

Thank you 😄

**Comment by lpil** [comment]
I've been unable to reproduce this. Could you share a reproduction please 🙏 

I think @hayleigh-dot-dev may have one also

**Comment by rawhat** [comment]
Ahhh okay, I see where the issue is stemming from (I think).

It doesn't happen with just `lustre = "4.0.0-rc1"`.  However, it _does_ happen with that _and_ `lustre_http`.  That package depends on `lustre = "~> 3.0"` so I suspect that's the problem?  That it can't resolve those two versions in some fashion.

Seems like this would be expected, but I guess some condition not handled causing it to panic?

**Comment by lpil** [comment]
I couldn't say. We'll need to make a reproduction and share that with the https://github.com/pubgrub-rs/pubgrub team.

**Comment by rawhat** [comment]
https://github.com/rawhat/version_test this replicates the behavior.  I'm not sure what they would like / prefer as a reproduction case in that repo.

**Comment by lpil** [comment]
We'll need to add logging to the compiler so that we can see all the values fed to their library, and then make a reproduction that adds those values directly outside the context of the repo.

**Comment by petera8** [comment]
Any status on this issue? The quick start guide needs to be updated since it doesn't work with `lustre_http` as mentioned by @rawhat .

**Comment by maxdeviant** [comment]
> We'll need to add logging to the compiler so that we can see all the values fed to their library, and then make a reproduction that adds those values directly outside the context of the repo.

I've been digging into this in https://github.com/gleam-lang/gleam/issues/3201.

I was able to create a reproduction outside of the Gleam compiler and have filed an issue with `pubgrub`: https://github.com/pubgrub-rs/pubgrub/issues/222

**Comment by lpil** [comment]
@maxdeviant you hero!! Thank you so much!!
