### ISSUE TITLE
Do not render functions for which there is no implementation for the target

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#2640]
When running `gleam test` it looks like it doesn't check if it can run the tests on the given target so for example with this one:
```gleam
pub fn wobble_test() {
  js_only()
}

@target(javascript, "wibble", "wobble")
fn js_only()
```
I get a runtime exception instead of a compiler warning when running `gleam test --target=erlang`

**Comment by lpil** [comment]
Remember, `gleam test` doesn't do anything but run your main function. It knows nothing of what any external code does.

The issue here is that we generate empty functions when there's no appropriate implementation. Let's remove these so nothing is generated.

**Comment by vatsa287** [comment]
@giacomocavalieri @lpil I am interested in working on this. Could you please assign this to me, I would love to get to know the codebase.

**Comment by lpil** [comment]
Hi @vatsa287 ! Thank you, but now I look at this again I'm not sure what is happening here.

@giacomocavalieri The code you've given here doesn't compile. How are you running `gleam test` given that?

**Comment by giacomocavalieri** [comment]
Ooh that's strange I'm trying to reproduce it but now the compiler is rightfully complaining, that's really curious... I'll let you know if that pops up again!

**Comment by lpil** [comment]
OK! Let's close this until it comes back. Thanks gang
