### ISSUE TITLE
Allow forcing colored output

### ISSUE THREAD

**Issue by tankorsmash** [gleam-lang/gleam#2652]
Hey there! I'm new to Gleam and really enjoying the live tour and how the LSP is built right in.

Since we don't have access to a live reload yet, I've been using `watch -n 0.01 -c -x  gleam build` to re-build my project all the time, but I was hoping to enable forcing color, even if Gleam isn't outputting to a terminal (which was added in https://github.com/gleam-lang/gleam/pull/492).

I hoped maybe `FORCE_COLOR=1` would help, but it seems like Gleam doesn't have support for that either.

Thanks for Gleam!

**Comment by lpil** [comment]
Good idea. Thank you

**Comment by tankorsmash** [comment]
Thank you @dvjn and everyone else!
