### ISSUE TITLE
LSP: Add hover docs for functions used with the pipe operator

### ISSUE THREAD

**Issue by ameknite** [gleam-lang/gleam#2654]
Example: 
This works 
![Screenshot 2024-03-07 at 18 45 49](https://github.com/gleam-lang/vscode-gleam/assets/104745335/30ea75e4-2878-4257-9fcc-93b6bae10996)

This doesn't work
![Screenshot 2024-03-07 at 18 46 11](https://github.com/gleam-lang/vscode-gleam/assets/104745335/519d5281-a8ab-4674-9757-a001a31041be)

**Comment by Acepie** [comment]
Hi, I wanted to try taking a look at fixing this and wrote up https://github.com/gleam-lang/gleam/pull/2678 idk if this is the right way to solve this but it passes a basic repro case at the very least
