### ISSUE TITLE
Compiler: `[..]` breaks Erlang

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/gleam#2657]
This Gleam
```gleam
fn a() {
  case [] {
    [..] -> 1
    _ -> 2
  }
}
```
Produces this Erlang in Gleam v1.0.0
```erlang
-spec a() -> integer().
a() ->
    case [] of
        [ | _] ->
            1;

        _ ->
            2
    end.
```

Which results in
```erlang
syntax error before: '|'
%   20|         [ | _] ->
%     |           ^
```

Note that the formatter currently converts `[..]` into `_`, sidestepping the issue.

No such problem was observed with the JS target.

**Comment by wmstack** [comment]
Also, ideally, pattern matching a list should allow an indeterminate number of elements at the start, end or in the middle.

```gleam
let sum = [1, 2, 3]
  case sum {
   [x, ..rest] -> // 1, [2, 3]
   [..start, y] -> // [1, 2], 3
   [x, ..mid, z] -> // 1, [2], 3
}
```

**Comment by lpil** [comment]
That's right, we only have syntax for fast operations as we don't want you to write slow code.
