### ISSUE TITLE
Windows releases detected as virus

### ISSUE THREAD

**Issue by jonatandorozco** [gleam-lang/gleam#2659]
I tried to download the latest binary v1, but Windows Defender says it contains a virus

![image](https://github.com/gleam-lang/gleam/assets/8442497/db5afed2-1b6f-47cf-8912-06134718b87e)
![image](https://github.com/gleam-lang/gleam/assets/8442497/e43db1c0-0f71-4f3a-8ff6-663d1218c35e)

**Comment by lpil** [comment]
Hi there. Thanks for the report. Is there something I can do to help you here?

**Comment by raxhvl** [comment]
This is likely a windos defender false positive. 

@jonatandorozco Please check if the suggestions [from this thread](https://answers.microsoft.com/en-us/windows/forum/all/how-can-i-know-if-wacatacbml-is-a-false-positive/33107e01-d390-4579-aa94-625a3402d26a) helps to suppress the error.

@lpil - If this becomes a widespread issue in the future consider submitting the release build for [Microsoft Security Review](https://www.microsoft.com/en-us/wdsi/filesubmission#:~:text=files%20that%20you%20believe%20have%20been%20incorrectly%20classified%20as%20malware).

**Comment by lpil** [comment]
Thank you @raxhvl ! I'll close this as there's no action to take now. If this continues to be a problem in future we can open new issues.
