### ISSUE TITLE
Broken link in string escape error message

### ISSUE THREAD

**Issue by bramvbilsen** [gleam-lang/gleam#2667]
Invalid escape codes in string produce the following error:
```
Syntax error

I don't understand this escape code.

Hint: Add another backslash before it.
See: https://gleam.run/book/tour/strings.html#escape-sequences

```
The following link is dead: https://gleam.run/book/tour/strings.html#escape-sequences
I think it should link: https://tour.gleam.run/basics/strings instead

**Comment by lpil** [comment]
Thank you
