### ISSUE TITLE
utf16 serialization

### ISSUE THREAD

**Issue by geniusalert** [gleam-lang/gleam#2671]
let name = "marimota"
  let padded_name =
    bit_array.slice(
      bit_array.append(<<name:utf16>>, bit_array_copy(<<0, 0>>, 22)),
      0,
      44,
    )

**Comment by schurhammer** [comment]
Could you explain the issue a bit more?

**Comment by lpil** [comment]
Hello! I'm going to close this as it's unclear what the issue is. Please feel free to reopen. Thank you
