### ISSUE TITLE
Show helpful error message if trying to append to a string using the spread operator

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#2683]
Some newcomers try doing this `[..wibble, item]` to append an item to a list expecting it to work like prepending does. The error message is not particularly useful as it complains about an unexpected token. We could have a better error message that could explain why this is not possible in Gleam

```text
  [..wibble, wobble, wabble]
             ^^^^^^^^^^^^^^
It looks like you're trying to append items to a list using the `..` operator.
Some more in depth explanation
```

How would you implement this Louis? I would like to give this a try but I'm not sure where to start, I was thinking I could check if there's a comma and a `Parser::series_of` elements after the list's tail...

**Comment by lpil** [comment]
Good idea!
