### ISSUE TITLE
Gleam marks used variable as unused when using pipelines

### ISSUE THREAD

**Issue by blasw** [gleam-lang/gleam#2691]
![image](https://github.com/gleam-lang/gleam/assets/62150922/0c8c6231-ae14-4e2b-bbb0-c2cf843064da)
Hello, I was just playing with the language and found out this bug with gleam. So you can see on the provided screenshot that if I create a variable and then instantly pass it to the pipeline (hint_val) gleam shows that variable is unused. Lower I've implemented the same functionality but repeated variable (no_hint_val) and this time everything is fine. Also this hint is being shown in the cmd when running the code so I dont actually know if it is a compiler or lsp issue.

**Comment by inoas** [comment]
I don't see the point binding and then just using the value of the expression and discarding the binding?

At best I can see a use here, but even then I am not sure:

```
import gleam/io

pub fn main() {
  let hint: String = "42"
  |> io.debug()
}
```

**Comment by lpil** [comment]
Hello! The compiler is correct. The variable `hint_val` is not used anywhere in your code, you can safely remove that assignment.
