### ISSUE TITLE
Some curly brace blocks return Nil for no apparent reason.

### ISSUE THREAD

**Issue by ArseniyKorobenko** [gleam-lang/gleam#2693]
Code:
```gleam
import gleam/io

pub fn main() {
  // prints Nil
  io.debug(foo(10))
  
  // prints Nil
  io.debug({10 {11 12}})
  
  // prints 10
  io.debug({    
    10    
    10
  })
}

fn foo(a) -> Int {
  {
    a
    a 
  }
}
```
Output:
```
Nil
Nil
10
```
Running on the https://tour.gleam.run website.

**Comment by salif** [comment]
If Gleam uses semver, and this bug gets fixed, wouldn't that technically be a breaking change, meaning the next version is 2.0.0? Or am I wrong? Does Gleam use semver?

**Comment by lpil** [comment]
This is a security soundness bug so it would be Gleam v1.0.1.

**Comment by juntuu** [comment]
Hi, I was checking the language out (exited to see it) and noticed this issue.

It seems to only affect the JS generation, Erlang worked as expected.

With a brief look, https://github.com/gleam-lang/gleam/blob/a18e7b765e85ac3027f328365e6127d79f175866/compiler-core/src/javascript/expression.rs#L1426 claims that `Block` handles its own return (used by `expression` generator function), but at least the else branch https://github.com/gleam-lang/gleam/blob/a18e7b765e85ac3027f328365e6127d79f175866/compiler-core/src/javascript/expression.rs#L458-L460 in the `block` generator function does not do so.

Adding a conditional `return` to the else branch with `.map(|doc| self.wrap_return(doc))` seems to fix the example, but I'm not sure if there's more to the bug.
