### ISSUE TITLE
Watchexec halts because of gleam build (escript) sends SIGTTOU

### ISSUE THREAD

**Issue by ad-ops** [gleam-lang/gleam#2710]
### Version
Gleam 1.0.0
Archlinux & MacOs (M2)

### Problem
`escript` build step sends SIGTTOU after compilation is done causing `watchexec` to hang.

```sh
watchexec -r -e gleam -- gleam run
```

### Workaround
Using `fd .gleam | entr -r -s 'gleam run'` works fine, but I would rather use watchexec (which some got to work?). If there are any good work arounds I would be glad to use them.

### Reproduce
```docker
FROM alpine:edge

RUN apk update && \
	apk upgrade && \
	apk add gleam watchexec strace

RUN watchexec --version
RUN gleam --version

WORKDIR app
RUN gleam new hello
WORKDIR hello
RUN gleam run

CMD ["watchexec", "-r", "--stop-signal", "SIGKILL", "--stop-timeout", "5", "-e", "gleam", "-E", "GLEAM_LOG=debug", "strace -e 'trace=!all' gleam run"]
```

**Comment by lpil** [comment]
OK so it looks like `-r` the flag to make watchexec restart the program when file change, but due to `SIGTTOU` being emitted it does not work. Is that right?

Why does it do that? Is that intended behaviour or a bug in watchexec?

**Comment by ad-ops** [comment]
I don’t know much about the underlying issues, but from what I could read the SIGTTOU is sent when a background process tries to write output which it is not allowed to.

It looks like you can disable this with `stty -tostop`, but I had no success running it. I was hoping that maybe there was something that could be set with the erlang build scripts to prevent them from not writing (but it seems to have no issues with the GLEAM_LOG set.

Not the most important issue, but I saw many had the issue on discord so if it is not fixable maybe it is possible have a workaround or documentation.

**Comment by lpil** [comment]
It would be really good to get this working, for sure! I'm keen to understand why it is that watchexec stops when this happens.

**Comment by ad-ops** [comment]
It didn't work to change shell, but it works to remove the INPUT (even if there is no input being sent). [This is the comment](https://unix.stackexchange.com/questions/600386/zsh-why-do-i-get-suspended-background-processes-even-when-i-have-stty-tostop#comment1409197_600460) that hinted to this solution.

```sh
# works as expected
watchexec -r -e gleam -- gleam run </dev/null
```

**Comment by lpil** [comment]
Oh interesting! I must admit I don't understand what is happening here at all. Perhaps we could try not passing stdin to `escript` and see if that changes anything?

**Comment by ad-ops** [comment]
I am also out of my depth with this, but I do like to watch code for changes:-).

I tried to remove [this line](https://github.com/gleam-lang/gleam/blob/5cb2163a6f03ed4e3f1685023ed2cde041fb7450/compiler-cli/src/fs.rs#L198), but it made no difference. I just ran the command by itself and still get the same error, so it is somehow disconnected from gleam.

```sh
watchexec -r --stop-signal SIGKILL --stop-timeout 5 -e gleam -- escript /Users/myuser/ws/gleam/hello/build/dev/erlang/hello/_gleam_artefacts/gleam@@compile.erl --lib /Users/myuser/ws/gleam/hello/build/dev/erlang --out /Users/adrian.opsahl/ws/gleam/hello/build/dev/erlang/hello/ebin /Users/myuser/ws/gleam/hello/build/dev/erlang/hello/_gleam_artefacts/hello.erl
```

I don't know enough erlang to understand if there is anything in the code or how `escript` works. Still the workaround is good enough for me.
