### ISSUE TITLE
Improve error message when using type as term

### ISSUE THREAD

**Issue by iacore** [gleam-lang/gleam#2712]
Again, I was playing with Gleam at https://tour.gleam.run/.

I tried to print a number

```
error: Type mismatch
  ┌─ /src/main.gleam:4:14
  │
4 │   io.println(1)
  │              ^

Expected type:

    String

Found type:

    Int
```

no good. It says "Found type: Int", so I tried to print "Int".

```
error: Unknown variable
  ┌─ /src/main.gleam:5:14
  │
5 │   io.println(Int)
  │              ^^^ Did you mean `Nil`?

The name `Int` is not in scope here.

```

Now it says "The name `Int` is not in scope here" even though the previous error message just mentioned "Int".

This is confusing for me because

- I have used languages with dependent types, where `Int` should be viewed as a term there.
- `Nil` is a valid term, but `Int` is not. Why?
- `Integer` is a valid term in Elixir (as atom).

P.S. I have also noticed #2576 while playing with Gleam.

**Comment by lpil** [comment]
Good suggestion! Thank you

**Comment by iacore** [comment]
Hello @lpil, I have two other questions.

1. Is it good (depending on your interpretation) to add `Int : Type` to Gleam, in order to unify the two namespaces (type and term)? If we do that, we won't even have problems that we have now.
2. `Nil : Nil` is confusing. I think we should change it to e.g. `Nil : NilType`. Erlang and Elixir don't have this problem because their type system is different (`is_nil(x)`).

**Comment by lpil** [comment]
1. Could you expand a little on your proposal? Thanks

2. It is too late to change the name of core types such as Nil. Elixir and Erlang and JavaScript and most other languages I know use the same naming style as Gleam. I think it would be more confusing to add the "Type" prefix to just this one type.

**Comment by inoas** [comment]
I think it makes sense that Nil's type is Nil, it is a very special thing and it doesn't add a lot of confusion.

**Comment by iacore** [comment]
> 1. Could you expand a little on your proposal? Thanks

My proposal is more complex than what Gleam need.

This is how Rust shows error message when a type is put in where a term (they call it "value") is expected.

```
   Compiling playground v0.0.1 (/playground)
error[E0423]: expected value, found builtin type `str`
 --> src/main.rs:7:33
  |
7 |         Ok(v) => println!("{}", str),
  |                                 ^^^ not a value

For more information about this error, try `rustc --explain E0423`.
error: could not compile `playground` (bin "playground") due to 1 previous error
```

> 2. It is too late to change the name of core types such as Nil. Elixir and Erlang and JavaScript and most other languages I know use the same naming style as Gleam. I think it would be more confusing to add the "Type" prefix to just this one type.

Elixir, Erlang and JavaScript  name the term `nil` or `null` (all lowercase). In Gleam, it's `Nil`, `True` and `False`, similar to Rust, Haskell, Idris.

**Comment by iacore** [comment]
If Gleam's type system supports using types as terms, it would look like this:

```
error: Type mismatch
  ┌─ /src/main.gleam:4:14
  │
4 │   io.println(Int)
  │              ^^^

Expected type:

    String

Found type:

    Type
```


```
io.debug(Int) // should print 'Int'
let a: Type = fn() -> Nil
```

Sorry, I am bad with words. Idris calls this "first class types".

**Comment by lpil** [comment]
I see! Instead of making it also a value (which would have very large implications for the language as we'd need to come up with a runtime representation for types, determine what they can be used for, etc) we can make the error message say "This isn't a value" the same way that Rust does.

**Comment by Acepie** [comment]
So for this would it make sense to just change the existing error messages from

`Expected type:` and `Found type:`

to

`Expected a value of type:` and `Found a value of type:`

with a special case for unscoped variables if a type of the same name is found in scope?

**Comment by Acepie** [comment]
Or i guess said differently, would it make sense to provide something like this:

```
error: Unknown variable
  ┌─ /src/one/two.gleam:1:1
  │
1 │ Int
  │ ^^^ A type with the same name is in scope. Did you mean to pass a value of type `Int`?

The a value with the name `Int` is not in scope here.
```
