### ISSUE TITLE
Update or remove page on Docker Hub 

### ISSUE THREAD

**Issue by ad-ops** [gleam-lang/gleam#2725]
[Docker Hub](https://hub.docker.com/u/gleamlang) has old versions for gleam which is confusing when trying to get a docker image with gleam.

It would be better to remove or update them together with the ghcr.io versions.

Also it would be good to document how to use docker in <https://gleam.run>.

**Comment by lpil** [comment]
Hello! Unfortunately that page is nothing to do with us.
