### ISSUE TITLE
Support Deno `--location` runtime flag

### ISSUE THREAD

**Issue by joshgillies** [gleam-lang/gleam#2730]
This flag controls the Deno runtime enabling it to provide globals like `location.href`. (Deno docs: https://docs.deno.com/runtime/manual/runtime/location_api).

For my specific use case I'm working on a module which wraps [worker-tools/deno-fetch-event-adapter](https://github.com/worker-tools/deno-fetch-event-adapter). In order to test this module thoroughly the ability to pass the `--location` flag would be greatly appreciated.

**Comment by abs0luty** [comment]
I can work on this one!

**Comment by lpil** [comment]
He has already made a PR @abs0luty !
