### ISSUE TITLE
JavaScript codegen: incorrectly parenthesised return statement

### ISSUE THREAD

**Issue by juntuu** [gleam-lang/gleam#2735]
Some expressions get parenthesised in the code generation. When such expression is the only one in a block, and also in tail position (e.i. returned), the return statement is parenthesised incorrectly.

For example this gleam code

```gleam
fn b() {
  {
    1 + 2
  }
}
```

produces the following JavaScript, which is syntactically incorrect

```js
function b() {
  (return 1 + 2;)
}
```

**Comment by lpil** [comment]
Thank you
