### ISSUE TITLE
Formatter should not remove single-line breaks and should make multi-line ones into single-line.

### ISSUE THREAD

**Issue by DanikVitek** [gleam-lang/gleam#2747]
Formatter should not remove single-line breaks, except for those within a multi-line expression.
Also, it should make multi-line ones into single-line.

For example:
```gleam
let a = "abc"

io.println(a)
```
should remain intact, while 
```gleam
let a = "abc"


io.println(a)
```
should be transformed into the former.

Meanwhile
```gleam
iterator.from_list([1, 2, 3])
  |> iterator.first

  |> should.equal(Ok(1))
```
should be transformed into
```gleam
iterator.from_list([1, 2, 3])
  |> iterator.first
  |> should.equal(Ok(1))
```

**Comment by DanikVitek** [comment]
This allows for improved readability by grouping related instructions.

**Comment by lpil** [comment]
Can you give examples of when this is not the case? Thank you

**Comment by DanikVitek** [comment]
> Can you give examples of when this is not the case? Thank you

While I was looking into the `gleam-stdlib` sources, I was modifying some code, and it would be formatted on save with the removal of all the blank lines. Then I tried to run `gleam format` and it modified all the files in the stdlib project

**Comment by lpil** [comment]
Could you give an example please? Without one I don't know how to reproduce the problem you are having.

**Comment by DanikVitek** [comment]
try running `gleam format` in `gleam-stdlib`

**Comment by lpil** [comment]
I get no changes. The CI workflow of all Gleam packages verifies there are no changes too.

**Comment by DanikVitek** [comment]
I'll record in the morning

**Comment by DanikVitek** [comment]
I'm using the gleam version, compiled from the master branch on commit `a6ab232`
https://github.com/gleam-lang/gleam/assets/25585136/c9e476d4-7ab5-43a6-9fd7-fafc528bed9e

**Comment by lpil** [comment]
Ah! Using the main branch! That's what I was missing. Thank you

**Comment by lpil** [comment]
I've just tested using main and it doesn't do this. Are you sure you haven't compiled a modified version of main?

**Comment by DanikVitek** [comment]
I've just tested once again myself with the latest main branch version, and it still is squishing the breaks. I'm sure it's unmodified

**Comment by lpil** [comment]
Do the tests fail if you run them?

**Comment by lpil** [comment]
The tests for the compiler. They assert that this does not happen.

I asked for other Windows users to verify the behaviour of main and they have the expected behaviour, so this is something specific to your setup which I'm not going to be able to debug for you I'm afraid.

**Comment by DanikVitek** [comment]
I found the issue. If you use `\r\n` (CRLF) line ending, then the breaks are removed, but if you use `\n` (LF), then the breaks are not removed.

**Comment by DanikVitek** [comment]
https://github.com/gleam-lang/gleam/assets/25585136/a32c5426-397e-4b35-83d0-223e17702ac7

**Comment by lpil** [comment]
Ah yes, that's it. Gleam uses `\n`. Thanks for digging into this!

**Comment by DanikVitek** [comment]
So there won't be measures taken? I mean, the formatted could just transform the line endings into LF, I've seen the `NewLineHandler` type for this in the parser. It would just make sense to transform a CRLF file into and LF file on format.

**Comment by lpil** [comment]
Sounds good! Could you open an issue for that please? Thanks

**Comment by DanikVitek** [comment]
Also, for some reason, when I open `gleam-stdlib`, all files are already marked with CRLF in the bottom right corner of the VSCode. Though, that might be just Windows quirks.
