### ISSUE TITLE
Why does num/0 have a result of 0?

### ISSUE THREAD

**Issue by B-Teague** [gleam-lang/gleam#2749]
I think gleam returning 0 from a number divided by zero is dangerous.  From a math perspective, ```y = 1/x``` never gets anywhere close to a solution of y = zero for very small numbers of x.

The limit as x approaches -0 like -0.00000001 approaches closer to negative infinity -∞ the smaller the fraction.
The limit as x approaches 0 from the positive side like 0.0000001 approaches closer to positive infinity +∞  the smaller the fraction.
These two scenarios are the exact opposite of a solution of y = 0.

This is why any number divided by 0 is always undefined in math.

![image](https://github.com/gleam-lang/gleam/assets/26033987/994af556-bbd3-4b00-b63d-064ec20a5885)

```gleam
import gleam/io
import gleam/int
import gleam/float

pub fn main() { 
  io.println(int.to_string(10 / 0)) //Should never return solution of 0
  io.println(float.to_string(10.0 /. 0.0)) //Should never return solution of 0
}

0 // !!! Dangerous answer !!!
0.0 // !!! Dangerous answer !!!
```

Since division is an unsafe operation, Gleam should probably provide a safe Result type from a division operation or throw a runtime exception when the ```/``` or ```/.``` operators are used to divide by zero.

```gleam
import gleam/io
import gleam/int

pub type ArithmeticError {
   DivideByZero
}

pub fn safeDivide(a: Int, b: Int) -> Result(Int, ArithmeticError) {
  case b == 0 {
    True ->Error(DivideByZero)
    False -> Ok(a / b)
  }
}
```

**Comment by juntuu** [comment]
See https://github.com/gleam-lang/gleam/issues/895

The linked post from Hillel also goes into the math side of this choice.
