### ISSUE TITLE
LSP: add new import via autocompletion (after #2756)

### ISSUE THREAD

**Issue by MarcThu** [gleam-lang/gleam#2757]
It would be a better DX, if new modules could be imported while writing other code.

This feature could be implemented like in Go:
When I am in a function body and type `fmt` I get autocompletion for `fmt` even if this is not imported yet. When I use the autocompletion (press enter), the selected function from `fmt` gets autocompleted as well as imported.

(should be implemented after #2756)

**Comment by lpil** [comment]
Good idea! Thank you
