### ISSUE TITLE
Codegen bug with JS string pattern matching

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#2759]
```gleam
fn main() {
  case Ok(["a", "b c", "d"]) {
    Ok(["a", "b " <> _, "d"]) -> 1
    _ -> 2
  }
}
```
Here the result is `1` on the erlang target (as one would expect) and `2` on the js one.

I tried making it smaller and this example:
```gleam
fn main() {
  case Ok(["b c", "d"]) {
    Ok(["b " <> _, "d"]) -> 1
    _ -> 1
  }
}
```
Crashes on the js target with a `TypeError: Cannot read properties of undefined (reading 'head') `

**Comment by lpil** [comment]
Thank you
