### ISSUE TITLE
Compile Gleam Program To Static Binary

### ISSUE THREAD

**Issue by pateljoel** [gleam-lang/gleam#2777]
Is gleam able to compile a program to a static binary?

I tried to find resources around this and I could not find anything on this, I would assume so since gleam is built using Rust that it can compile to a binary.

**Comment by inoas** [comment]
no.
the compiler is built in rust but it does not compile to binary but compiles to erlang or javascript code.

**Comment by inoas** [comment]
for more or less self contained executables:
- `gleam export erlang-shipment` might help you.
- https://github.com/burrito-elixir/burrito might be worth a look
- packaging things up as a small docker image might help
- running it on target javascript and bundling that up with deno or node might work

**Comment by lpil** [comment]
Thank you @inoas !

**Comment by jcayzac** [comment]
@lpil While @inoas's answer gave some general direction of what might be relevant or worth a look to start embarking on the long journey of a self-contained Gleam executable, it does not address nor solve the original issue, so maybe this should be reopened?

[This blog post](https://www.ethanthoma.com/post/a_gleam_burrito) actually provides a full working solution. It's still quite a rough DX, so maybe Gleam could facilitate the process eventually without requiring all the plumbing we see there?

Cheers!

**Comment by lpil** [comment]
We won't be providing any tooling relating to the BEAM rather than Gleam itself, not unless someone were to provide ongoing financial assistance so we can afford more developers.
