### ISSUE TITLE
gleam run -m can run duplicate module from path dependency

### ISSUE THREAD

**Issue by JohnBjrk** [gleam-lang/gleam#2780]
Create two projects with `gleam new`: demo1 and demo2.

In both project create a file `demo.gleam`.

In demo1 with content:
```gleam
import gleam/io

pub fn main() {
  "demo in demo1"
  |> io.debug()
}
```

In demo2 with content:
```gleam
import gleam/io

pub fn main() {
  "demo in demo2"
  |> io.debug()
}
```

In demo2 add the following to `[dependencies]` in `gleam.toml`:
`demo1 = { path = "../demo1"}`

The run the `demo` module in demo2:
`gleam run -m demo`

On my side I get the output:
"demo in demo1"

Expected error or maybe "demo in demo2" with a warning that demo module was shadowed in demo1 dependency.

Note: If the dependency was made in the other direction (demo1 -> demo2) the module from the main project was run.

**Comment by lpil** [comment]
Oh dear! Thank you

**Comment by lpil** [comment]
This is happening as the deps are searched for the module first, and if found then the root is not compiled. This is not a bug.
