### ISSUE TITLE
Suggestion for testing

### ISSUE THREAD

**Issue by gideaoms** [gleam-lang/gleam#2809]
I was thinking that it would be better if we followed the Javascript way of testing. I mean, just adding a `_test` could not be enough because the same function might be tested in different manners.

I suggest something like this:
```gleam
import gleam/test

test.it("description of the test", fn () {
    // ...
})
```

What do you think?

**Comment by lpil** [comment]
Hello! Gleam has no built-in test capabilities, and you can design your test code in any way you want!

The `_test` convention is from [eunit](https://www.erlang.org/doc/apps/eunit/chapter.html) and you could do something else that you prefer.
