### ISSUE TITLE
`gleam run -m lustre build app` builds an Erlang target on Linux while should only build Javascript

### ISSUE THREAD

**Issue by greenfork** [gleam-lang/gleam#2820]
Doesn't seem to be a problem on MacOS.

Steps to reproduce:

```
git clone 'https://git.sr.ht/~greenfork/taskmgr'
cd taskmgr
git checkout erlang-bug
gleam run -m lustre build app
```

Fails with:

```
/tmp/taskmgr/build/dev/erlang/taskmgr/_gleam_artefacts/taskmgr.erl:110:25: function row_show_hide_ani_effect/0 undefined
%  110|                         row_show_hide_ani_effect()};
%     |                         ^

error: Shell command failure
```

**Comment by lpil** [comment]
What version of Gleam are you using here?

**Comment by greenfork** [comment]
Above I used the version ed8c512b0343306853894c303d2d10e082cc3953.

Here I upgraded to the latest main cf1b6429679f5fb6d46af952576d9eeb87fe31e8 and also upgraded the lustre package.

```
git clone 'https://git.sr.ht/~greenfork/taskmgr'
cd taskmgr
git checkout erlang-bug2
gleam run -m lustre/dev build app
```

**Comment by lpil** [comment]
Ah that's the missing piece of the puzzle. I know what is happening now. Main is currently not suitable for use with cross platform projects while the new dead code elimination is being worked on.

Please include the Gleam version in issue reports, it helps a lot 🙏

**Comment by greenfork** [comment]
Okay, thank you!
