### ISSUE TITLE
Module named `prepend` shadows prelude's `prepend` on JS codegen

### ISSUE THREAD

**Issue by PgBiel** [gleam-lang/gleam#2823]
On latest main, if you import a name from a module named `prepend`, the JS codegen will import the module under a variable named `$prepend`. Similarly, if you write something like `[1, ..tail]`, JS codegen will convert that to `$prepend(1, tail)` and import `$prepend` from the prelude. Doing both in the same file leads to a name conflict, flagged below when running.

![error: $prepend was already defined](https://github.com/gleam-lang/gleam/assets/9021226/86b5fd2a-5828-40c2-8987-3ec955bca078)

Sample project attached below.

[showcase.tar.gz](https://github.com/gleam-lang/gleam/files/14733062/showcase.tar.gz)

One possible solution is to import `prepend` from the prelude aliased to `listPrepend` instead, or use some other naming. I am willing to make a PR for this change (to whichever name is agreed upon).

**Comment by lpil** [comment]
Oh dear! Thank you
