### ISSUE TITLE
String prefix matching doesn't handle unicode escapes on JS codegen

### ISSUE THREAD

**Issue by PgBiel** [gleam-lang/gleam#2828]
The program below prints `Result: fghi` instead of `Result: abcde fghi` when run on the JS target:

```js
pub fn main() {
  let z = "\u{0032} abcde fghi"
  let assert "\u{0032} " <> p = z

  io.println("Result: " <> p)
}
```

Peeking at the generated code, we can see that `p` is being assigned a substring longer than it should be:

```js
export function main() {
  let z = "\u{0032} abcde fghi";
  if (!z.startsWith("\u{0032} ")) {
    throw makeError(
      "assignment_no_match",
      "aog",
      33,
      "main",
      "Assignment pattern did not match",
      { value: z }
    )
  }
  let p = z.slice(8);  // <---- here
  return $io.println("Result: " + p);
}
```

This is because the code at `javascript/pattern.rs` to calculate the length of the prefix string, taking into account escape sequences, is assuming (as seen below) that every escape sequence in a Gleam string has (and expands into) a single character, but Unicode escape sequences always contain more than one character after the backslash (`\u{0032}` vs `\n`), so the `{`, `0`, `0`, `3`, `2` and `}` characters are not being filtered out.

https://github.com/gleam-lang/gleam/blob/5ade71380454d298d542012b7be82bec461e4257/compiler-core/src/javascript/pattern.rs#L864-L871

One possible solution is to just forgo of that logic in `pattern.rs` and generate `z.slice("\u{0032} ".length)` instead.
Alternatively, we can use a nested loop to skip upcoming `{`, (digit), `}` characters.

**Comment by lpil** [comment]
Thank you
