### ISSUE TITLE
`gleam publish` should be able to use a long-lived hex api key to auth publishing to hex.

### ISSUE THREAD

**Issue by Skenvy** [gleam-lang/gleam#2844]
At the moment the `gleam publish` command requires `HEXPM_USER` and `HEXPM_PASS` to authorise publishing. It would be nice to not require the user password to need to be used for this, instead making available a preferred option of a hex api key ~ `HEXPM_API_KEY` ~ so that users can manage their own long lived API keys if they prefer.

**Comment by Skenvy** [comment]
_I would like to start working on this._

**Comment by lpil** [comment]
Fab! Thank you!

**Comment by TomBinford** [comment]
Should this be closed now?

**Comment by lpil** [comment]
Thank you
