### ISSUE TITLE
Replace textwrap library with a custom wrap function with a fixed maximum

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2850]
We use the textwrap library for wrapping error messages to a standard terminal width. The library also does other things such as inspect the terminal that we're running in, but we don't need this stuff, and it makes upgrading it harder. Let's replace it with once simple function that wraps text.

We could copy it from the library perhaps.

**Comment by aznashwan** [comment]
I volunteer myself as tribute. ✋

**Comment by lpil** [comment]
Thank you!!

**Comment by ross-byrne** [comment]
Hello! I'm looking at picking up my first issue and this one looks pretty good. @aznashwan it's been a few months, do you still want to work on this? 

I see the functionality we want here and it looks like `textwrap` just wraps the `terminal_size` crate to get the terminal size or set the fallback. I'm guessing we're happy to just use that crate to re-implement this functionality ourselves, right?

**Comment by lpil** [comment]
The work here is to stop taking terminal size into account. We want wrapping but not variable width.

**Comment by aznashwan** [comment]
> Hello! I'm looking at picking up my first issue and this one looks pretty good. @aznashwan it's been a few months, do you still want to work on this?

Goes without saying by now that it had completely gone under my radar back then (I had transitioned to fixing the [`filepath` module](https://github.com/lpil/filepath/pulls)).

Please feel free to go for it, thank you!

**Comment by ross-byrne** [comment]
@lpil Ah OK, even better so! I thought it was just about `textwrap` specifically.

I'll do some testing to see how `textwrap` currently works and try match that behavior (e.g. when it breaks words etc).
I'll try take as much "inspiration" from how they implemented it as I can.
