### ISSUE TITLE
Go to definition with the gleam language server

### ISSUE THREAD

**Issue by CreggEgg** [gleam-lang/gleam#2851]
It would be a huge improvement if you could go to a function definition when looking at gleam code. 

This is a similar issue to #2125 but this would also be very useful with functions. For example if you are using a library and have given a function the incorrect number of arguments the only thing the error message says is "wrong arity". This is completely fine but it would be much easier to resolve if you could just look at the function definition and see what arguments you are supposed to supply.

I've tried this in neovim and in vscode and have not been able to view definition in either which leads me to believe that this is not an issue with my configuration.

**Comment by CreggEgg** [comment]
I did some more looking and it seems that this is only an issue if the function is in another file. If the functions are in the same file then it works.

**Comment by philipgiuliani** [comment]
The LSP go to definition action was already implemented and will be released with the next gleam release: https://github.com/gleam-lang/gleam/pull/2731

**Comment by lpil** [comment]
Yup! Support for goto def for other packages will be out soon.
