### ISSUE TITLE
JS `BigInt` for `Int`s?

### ISSUE THREAD

**Issue by Rudxain** [gleam-lang/gleam#2853]
Why doesn't the JavaScript transpiler use `BigInt` "under-the-hood" to store `Int`s?

**Comment by lpil** [comment]
Because they are very slow and break interop.

**Comment by Rudxain** [comment]
> break interop.

Do you mean they aren't backwards-compatible? They're from ES2020. Does the JS need to be IE11-compatible?

**Comment by inoas** [comment]
> > break interop.
> 
> Do you mean they aren't backwards-compatible? They're from ES2020. Does the JS need to be IE11-compatible?

They are (usually) not compatible with JSON afair.

**Comment by inoas** [comment]
They are also very slow on JS for common int operations, AFAIK. So they are not a good default until you need very large ints. There is https://hex.pm/packages/bigi for that.

**Comment by Rudxain** [comment]
oh ok, thanks for explaining 👍
