### ISSUE TITLE
How `Float` `BitArray`s could be implemented in JS

### ISSUE THREAD

**Issue by Rudxain** [gleam-lang/gleam#2854]
# What & How
```js
// Rust naming-convention
const u64_Arr = BigUint64Array, f64_Arr = Float64Array

/**
Get the internal bits (binary64 IEEE-754 representation)
@param {number} f
*/
const f64_to_u64 = f => new u64_Arr(new f64_Arr([f]).buffer)[0]

/**
mask the 64 LSBs and read as IEEE-754 binary64 floating-point format
@param {bigint} n
*/
const u64_to_f64 = n => new f64_Arr(new u64_Arr([n]).buffer)[0]

// 0 is endianness-agnostic
console.log(f64_to_u64(0) === 0n) // true
```

[`TypedArray`s are ES-compliant](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-typedarray-objects), they are not "Web APIs" nor NodeJS `Buffer`s. JS has `Float32Array` which matches `size(32)`. Unfortunately, `f16` requires software-emulation, because JS doesn't have built-in support.

The endianness can be forced to `big` or `little` by using `Uint8Array` instead of a single-element `u64_Arr`. However, this **only applies to _integer-endianness_**. ES doesn't explicitly define endianness for _`number`s themselves_, but it does say it's IEEE-754, so it may be `native`. Therefore, the only (known) way to guarantee non-native endianness is to implement software emulation, which may have a "huge" performance impact.

## Why
I'm posting this Issue to help compiler devs implement this easily

**Comment by lpil** [comment]
Hello! Please only open Gleam issues in the Gleam issue tracker. Thank you.

**Comment by Rudxain** [comment]
I was considering to post it in Discussions. Should I move it there?
