### ISSUE TITLE
"too many redirects" HTTP error without a manifest.toml file

### ISSUE THREAD

**Issue by frazjp65** [gleam-lang/gleam#2859]
Gleam version:
1.0.0 (installed through asdf)

OS:
Ubuntu 20.04 (WIndows 10 WSL)

Issue: 
When I run "gleam test" and some other commands when there is no manifest.toml file I get "too many redirects" HTTP error for varying hex URLs. If I am in a project that has the manifest.toml file, there does not seem to be a problem. 

Steps to recreate: 

```bash
gleam new bdemo
cd bdemo
gleam test
```

![image](https://github.com/gleam-lang/gleam/assets/13321887/6c242c53-a8dc-46a6-b1c0-2172d5188816)

Running "curl -sq --max-redirs 0 https://hex.pm/api/packages/gleam_stdlib/releases/0.36.0" is successful.

**Comment by lpil** [comment]
This is us trying to talk to the Hex package manager APIs to get the versions of your deps.

Could you run with the `GLEAM_LOG` environment variable set to `trace` please

**Comment by frazjp65** [comment]
I attached the log.

[gleam.log](https://github.com/gleam-lang/gleam/files/14795032/gleam.log)

**Comment by frazjp65** [comment]
I'll let you decide whether or not to close this. I confirmed that this is not a problem when I compile the current version or the v1.0.0 tag. I am going to look and see if it is something with how asdf installs it.

**Comment by frazjp65** [comment]
I checked the code for asdf-gleam. It just downloads this version for me: https://github.com/gleam-lang/gleam/releases/download/v1.0.0/gleam-v1.0.0-x86_64-unknown-linux-musl.tar.gz

I downloaded that and ran it. The issue came back with that version.

**Comment by lpil** [comment]
Brilliant, thank you very much!
