### ISSUE TITLE
`const` are not in scope inside binary scalars

### ISSUE THREAD

**Issue by dartheian** [gleam-lang/gleam#2867]
While attempting the following:
```gleam
const bit_size = 3

fn my_function() -> BitArray {
    <<1:size(bit_size)>>
}
```
the compiler complains about the `const` not being in scope:
```bash
error: Unknown variable
The name `bit_size` is not in scope here.
```

**Comment by lpil** [comment]
Thank you

**Comment by larzconwell** [comment]
I believe this can be closed since it was fixed by https://github.com/gleam-lang/gleam/pull/2874, I verified this works as expected on `main`.

**Comment by lpil** [comment]
Thank you
