### ISSUE TITLE
Add friendly error message when CWD doesn't exist

### ISSUE THREAD

**Issue by PgBiel** [gleam-lang/gleam#2876]
When running Gleam commands (for example, `gleam clean`) from a directory which has since been deleted, the compiler panics, as shown in the message below. It should perhaps display some proper error message instead (e.g. "Error: You're trying to run this command within a directory that does not exist or was removed. Try running this command again in a valid directory.").

```
error: Fatal compiler bug!

This is a bug in the Gleam compiler, sorry!

Please report this crash to https://github.com/gleam-lang/gleam/issues/new
and include this error message with your report.

Panic: compiler-cli/src/main.rs:566
        Failed to get current directory: FileIo { kind: Directory, action: Open, path: ".", err: Some("No such file or directory (os error 2)") }
Gleam version: 1.0.0
Operating system: linux

If you can also share your code and say what file you were editing or any
steps to reproduce the crash that would be a great help.

You may also want to try again with the `GLEAM_LOG=trace` environment
variable set.
```

**Comment by lpil** [comment]
Good idea! Thank you

**Comment by zahash** [comment]
@lpil can i do this? i have a decent experience in rust.

**Comment by zahash** [comment]
this is the place where the panic occurs.

```rust
// compiler-cli/src/main.rs

fn find_project_paths() -> Result<ProjectPaths> {
    let current_dir = get_current_directory().expect("Failed to get current directory");
    get_project_root(current_dir).map(ProjectPaths::new)
}
```

is it fine to change the error message from "Failed to get current directory" to "Error: You're trying to run this command within a directory that does not exist or was removed. Try running this command again in a valid directory"

or should i do something more fancy? eg: anyhow::Result has the handy dandy `.context("...")` method. something like that in `gleam_core::error::Error` might be useful?

**Comment by zahash** [comment]
gleam won't let me create a project with non utf8 name but i can create a project in a directory where one of the path segments is non-utf8.

eg: 

```sh
mkdir $'\xC0\xC0'
cd $'\xC0\xC0'

gleam new samplegleam
```

and when i `gleam run` the project, it shows this.

```sh
error: Fatal compiler bug!

This is a bug in the Gleam compiler, sorry!

Please report this crash to https://github.com/gleam-lang/gleam/issues/new
and include this error message with your report.

Panic: compiler-cli/src/main.rs:558
	Failed to get current directory: NonUtf8Path { path: "/home/zahash/source/\xC0\xC0/samplegleam" }
Gleam version: 1.0.0
Operating system: linux

If you can also share your code and say what file you were editing or any
steps to reproduce the crash that would be a great help.

You may also want to try again with the `GLEAM_LOG=trace` environment
variable set.
```

well, i wouldn't call it a "compiler bug". and there should instead be better error message saying "gleam doesn't support non-utf8 project paths".

but now that i think about it, wouldn't it be nice if it did allow non-utf8 paths?

**Comment by zahash** [comment]
using a `?` instead of `.expect(...)` gives a much better error message

```rust
fn find_project_paths() -> Result<ProjectPaths> {
    let current_dir = get_current_directory()?;
    get_project_root(current_dir).map(ProjectPaths::new)
}
```

```sh
error: Non UTF-8 Path Encountered

Encountered a non UTF-8 path, but only UTF-8 paths are supported.
```

**Comment by zahash** [comment]
update: i have found a way to recreate the current working directory not found bug. i just ran this in the project root.

`rm -r "$(pwd)"`

and then ran the project `gleam run`. with the `?` change, it gives nicer error message.

```sh
error: File IO failure

An error occurred while trying to open this directory:

    .

The error message from the file IO library was:

    No such file or directory (os error 2)
```

**Comment by zahash** [comment]
anyway, here is a pr https://github.com/gleam-lang/gleam/pull/2886

**Comment by lpil** [comment]
Brilliant, thank you @zahash . The build tool section sounds best to me 👍

**Comment by zahash** [comment]
@lpil 

what about a slight improvement to the error message when non-utf8 paths are encountered? wouldn't showing the actual path be useful?

```rust
            Error::NonUtf8Path { path } => {
                let text = format!(
                    "Encountered a non UTF-8 path {}, but only UTF-8 paths are supported.",
                    path.to_string_lossy()
                );
                Diagnostic {
                    title: "Non UTF-8 Path Encountered".into(),
                    text,
                    level: Level::Error,
                    location: None,
                    hint: None,
                }
            }
```

because the get_current_directory function can fail if the path is non-utf8
```rust
pub fn get_current_directory() -> Result<Utf8PathBuf, Error> {
    let curr_dir = std::env::current_dir().map_err(|e| Error::FileIo {
        kind: FileKind::Directory,
        action: FileIoAction::Open,
        path: ".".into(),
        err: Some(e.to_string()),
    })?;
    Utf8PathBuf::from_path_buf(curr_dir.clone()).map_err(|_| Error::NonUtf8Path { path: curr_dir })
}
```

**Comment by zahash** [comment]
> Nice idea! Thank you

@lpil 

here is the PR for that https://github.com/gleam-lang/gleam/pull/2895
