### ISSUE TITLE
Cache Rust dependencies build step on GitHub actions

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#288]
This is currently blocked by GitHub having not yet released their caching feature.

https://stackoverflow.com/questions/55110729/how-do-i-cache-steps-in-github-actions/57958803#57958803

**Comment by OvermindDL1** [comment]
A popular workaround I've seen so far is to save the cache as a 'Release' (either in same project or another) then just load that release via URL and populate as necessary.

**Comment by lpil** [comment]
Oh wow that's sneaky :)

**Comment by EskiMag** [comment]
I can implement this if you can provide more info. I probably just need to know what to cache.

**Comment by lpil** [comment]
We want to cache the `gleam/target` directory I think. There might be some other directories we want to cache too, there's probably some best practices for caching Rust builds on the internet somewhere.

**Comment by EskiMag** [comment]
OK, I'll check the best practices and try to implement it with the releases hack until the real caching is available.

**Comment by EskiMag** [comment]
You can assign this to me too.

**Comment by EskiMag** [comment]
There's a new preview version of a `cache` action here https://github.com/actions/cache
I tried it, but I exceeded the size limit of a cache (200MB), see https://github.com/EskiMag/gleam/runs/283487225#step:3:0
Are we able to somehow reduce the size to cache?

**Comment by EskiMag** [comment]
The limit is already discussed here https://github.com/actions/cache/issues/6
Maybe it's enough to just wait until it's increased.

**Comment by lpil** [comment]
Good find! Let's wait for it to offer more storage because 200MB is not workable for us.
