### ISSUE TITLE
Code doc links are hard to discover

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#2880]
In the generated docs monospaced words that are also links do not get the same pink colour that links usually have:
![Screenshot 2024-04-01 alle 22 11 38](https://github.com/gleam-lang/gleam/assets/20598369/cddae625-fe0d-477b-b715-3fa58e9a9e29)
They are indistinguishable from normal monospaced words and a pink underline only appears when hovering:
![Screenshot 2024-04-01 alle 22 11 42](https://github.com/gleam-lang/gleam/assets/20598369/14bb8595-227f-4c72-b726-56b2c3bcbbb0)

I think those should be coloured pink like all links and still get an underline on hover, this way one could easily tell monospaced links apart from monospaced text

**Comment by lpil** [comment]
Agreed!

**Comment by samifouad** [comment]
doing some quick testing in my browser, i think i found the css that would need to be added to resolve the issue

```
a code {
    text-decoration: underline;
    text-decoration-color: var(--links);
}
```

here's what it looks like:
![Screenshot from 2024-04-01 21-38-18](https://github.com/gleam-lang/gleam/assets/6378290/9dcb5d76-193e-48e3-8fd6-f2450d7eeeec)

**Comment by samifouad** [comment]
a variation would be this that provides a subtle bit more spacing to differentiate from non-link < code > markup:

```
a code {
    text-decoration: underline;
    text-decoration-color: var(--links);
    padding: 0em 0.3em 0em 0.3em;
    text-underline-offset: 0.1em;
}
```
![Screenshot from 2024-04-01 21-42-14](https://github.com/gleam-lang/gleam/assets/6378290/e0b682c5-a5c2-4aea-a990-633a240f617f)

**Comment by samifouad** [comment]
another note: the first option would keep the thinkness of the underline on hover, the second increases it on hover:
![Screenshot from 2024-04-01 21-49-49](https://github.com/gleam-lang/gleam/assets/6378290/233a56b0-bf6f-4475-a9f3-79b2001db4da)

if the first option is preferred, we could explicity set underline to make it more think by adding:
```
a:hover code {
    text-decoration-thickness: 2px;
}
```

not sure where in the code this gets defined, but i defintely can poke around and submit a pr!

**Comment by JackoCoolio** [comment]
I think just changing the color to match other links is fine here - the font alone is enough to differentiate a code link from a regular link. IMO a pink underline doesn't stand out.

**Comment by samifouad** [comment]
here's what matching other links would look like:

**var(--links)** as code link color to match menu:
![Screenshot from 2024-04-01 23-01-46](https://github.com/gleam-lang/gleam/assets/6378290/eb57eef0-a3e7-4afc-b6a0-d88abd14861e)
![Screenshot from 2024-04-01 23-01-52](https://github.com/gleam-lang/gleam/assets/6378290/80c9db00-90f0-47df-b151-5fca95399e87)

**Comment by samifouad** [comment]
agreed! i think that looks best too!

and pardon my unfamiliarity with the template generation process, but I believe this could be where the edit would need to be made: https://github.com/gleam-lang/gleam/blob/08f1ff0c5e9e90516688a4ae5ecff8172714a0dd/compiler-core/templates/docs-css/index.css#L176

can submit PR if nobody else has it covered!

**Comment by lpil** [comment]
Yes please!
