### ISSUE TITLE
Formatter: some values are indented incorrectly when piped

### ISSUE THREAD

**Issue by MystPi** [gleam-lang/gleam#2890]
Using Gleam v1.0.0.

The formatter indents some values incorrectly when they are piped and are part of a comma-separated sequence of values. So far it seems that blocks and lists are affected.

Example:
```gleam
pub fn main() {
  #(
    1,
    {
        "long enough to need to wrap. blah blah blah blah blah blah blah blah blah"
      }
      |> foo,
    3,
  )
}
```

I think this must be due to the new formatting style of indenting pipes.

**Comment by giacomocavalieri** [comment]
@lpil could you assign this to me? Or I will forget to look at it 😆

**Comment by lpil** [comment]
I'm surprised you can't assign it yourself!

**Comment by giacomocavalieri** [comment]
It looks like this happens to lists as well!
```gleam
fun(
  [
      ["wibble wobble", "wibble", "wobble"],
      ["long enough to go over", "line limit"],
    ]
    |> list.concat
)
```
