### ISSUE TITLE
can not match multi-patterns when use `|`

### ISSUE THREAD

**Issue by lost22git** [gleam-lang/gleam#2893]
## with `|`
![Screenshot 2024-04-04 185217](https://github.com/gleam-lang/gleam/assets/65008815/0ab14841-38a0-4479-9717-e032df3b48d3)

## without `|`
![image](https://github.com/gleam-lang/gleam/assets/65008815/cef2d332-af33-43ab-9123-f44786134a2e)

**Comment by lost22git** [comment]
Of course, I can choose to use negation to temporarily solve this problem

**Comment by lpil** [comment]
`|` is at the top level above `,`, so there you have a multi-pattern for 1 subject, then a muliti-pattern for 2 subjects, then a multi-pattern for 1 subject.

**Comment by lost22git** [comment]
It’s not very clear. So what is the general solution to this problem in gleam?
