### ISSUE TITLE
LSP: Zed failed with Unsupported LSP request

### ISSUE THREAD

**Issue by bondiano** [gleam-lang/gleam#2894]
I'm using Zed and often facing with next LSP error 

```
stderr: Unsupported LSP request textDocument/references
stderr: Gleam version: 1.0.0
stderr: Operating system: macos
```

**Comment by lpil** [comment]
Hello! The LSP does not support the references request. It tells the client this so if it ignores that and tries to use it then this is a bug in Zed.
