### ISSUE TITLE
Compile OSX binary on GitHub actions when a new release is created

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#290]
https://help.github.com/en/github/automating-your-workflow-with-github-actions/events-that-trigger-workflows#release-event-release

**Comment by EskiMag** [comment]
Assign to me please. 🙏

**Comment by EskiMag** [comment]
What does "compile OSX binary" mean exactly? Just `cargo build --release`? Should be the compiled binary then attached to the release which triggered this build? If yes, is it enough to attach just the single `gleam` file?

**Comment by lpil** [comment]
Yes that should do OK. There's an example script I run on a macbook in the `bin` directory which does roughly what we want GitHub to do.
