### ISSUE TITLE
Formatter: support comments in const lists

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2911]
```gleam
const x = [
  // A comment!
  1
]
```

**Comment by giacomocavalieri** [comment]
I can work on this one!

**Comment by giacomocavalieri** [comment]
I checked and it looks like the formatter already does this, so I've just added a test to make sure we don't break it

**Comment by lpil** [comment]
Hi @giacomocavalieri did you forget to push this perhaps? It is not done.

**Comment by giacomocavalieri** [comment]
Mmh no I definitely added the tests to check that... there must be some other cases I didn't take in account then

**Comment by lpil** [comment]
I checked the test, it tested a let assignment and not a const, oops

**Comment by giacomocavalieri** [comment]
Ah! That's it then, if you keep this issue open I'll fix it

**Comment by giacomocavalieri** [comment]
This was closed by #2926

**Comment by lpil** [comment]
Thanks again!
