### ISSUE TITLE
Upgrade reqwest library version

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2921]
https://github.com/gleam-lang/gleam/pull/2919

Seems to have a breaking change

**Comment by juntuu** [comment]
Looks like `reqwest` 0.12 updated its dependency of `http` from 0.2 to ^1. It's currently 0.2 for gleam itself and also `hexpm`.

Updating hexpm and gleam's own http dependency first should resolve the issue.

**Comment by dzvon** [comment]
I can take on this task if no one else has already started working on it.
