### ISSUE TITLE
`debugger` variable name should be overridden in JS

### ISSUE THREAD

**Issue by ghivert** [gleam-lang/gleam#2931]
When using `debugger` as a variable name, which is totally fine in gleam, it returns an error in JS, because `debugger` is a reserved keyword.

Example code:

```gleam
msg.Restart(debugger) -> {
  let restart_effect =
    model.debuggers
    |> debugger.get(debugger)
    |> result.then(fn(d) {
      d.steps
      |> list.first()
      |> result.map(fn(item) { d.dispatcher(item.model) })
    })
    |> result.unwrap(effect.none())
```

JS code

```javascript
let debugger = msg[0];
let restart_effect = (() => {
  let _pipe = model.debuggers;
  let _pipe$1 = $debugger.get(_pipe, debugger);
  let _pipe$2 = $result.then$(
    _pipe$1,
    (d) => {
      let _pipe$2 = d.steps;
      let _pipe$3 = $list.first(_pipe$2);
      return $result.map(
        _pipe$3,
        (item) => { return d.dispatcher(item.model); },
      );
    },
  );
  return $result.unwrap(_pipe$2, $effect.none());
})();
```

In the JS code, in strict mode, `debugger` is reserved. `debugger` should be named `debugger$` or something like that.

**Comment by PgBiel** [comment]
Culprit:
https://github.com/gleam-lang/gleam/commit/4977c1b7#diff-8e92b6138ea4c80a8897bb9a0adcc10f33a7a9b36b5a07d54c78e920b07f0d6eR634

Seems like some bad string replacing happened... :sweat_smile:
