### ISSUE TITLE
New "private members in public API" check fails for re-export

### ISSUE THREAD

**Issue by rawhat** [gleam-lang/gleam#2938]
Hello!

Just testing the v1.1 RC against some of my repos.  In `mist` I am re-exporting some types from an internal module in my public main module.  I added some documentation comments to them just so it's not quite so opaque.

Unfortunately, the new check marks those as a warning.  Example:

```gleam
/// Re-exported type that represents the default `Request` body type. See
/// `mist.read_body` to convert this type into a `BitString`. The `Connection`
/// also holds some additional information about the request. Currently, the
/// only useful field is `client_ip` which is a `Result` with a tuple of
/// integers representing the IPv4 address.
pub type Connection =
  InternalConnection
```

The errors come from public functions that actually _use_ this type.  I've been trying to avoid the whole "make a new type to export and convert between them" where possible.  I suspect this would/will be an issue if we ever get constructor re-exports as well.

**Comment by lpil** [comment]
Thank you. I've reopened the original issue for this and we've reverted this implementation.
