### ISSUE TITLE
Wrong error message when writing a function name which starts with underscore

### ISSUE THREAD

**Issue by Juhan280** [gleam-lang/gleam#2948]
### The bug
![Screenshot_20240410-070642_Termux](https://github.com/gleam-lang/gleam/assets/92646057/b20c215b-bb5f-40aa-97a8-9899f017f5d1)

### Expected behavior 
If `_function_name` is not allowed in gleam, it should say so
If it was supposed to be allowed, you get compiler error

Either way the error message is wrong 

### Version 
gleam 1.1.0-rc1

**Comment by lpil** [comment]
Hello! What do you mean it's wrong? It says in the error that names must start with a lowercase letter.
