### ISSUE TITLE
LSP code action: add missing patterns to case expression

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2957]
The exhaustiveness checker has this information so we need to expose it to the language server

It may be challenging to work out in the exhaustiveness checker if the variant names need to be qualified or not. It would be annoying to have to fix it every time.

Perhaps this needs to come after https://github.com/gleam-lang/gleam/issues/2952

**Comment by GearsDatapacks** [comment]
I'll try and implement this once #3393 is merged, although we should probably fix #2426 first too
