### ISSUE TITLE
`rustfmt` uses deprecated `Node.js 16 actions`

### ISSUE THREAD

**Issue by hamirmahal** [gleam-lang/gleam#2968]

**Comment by hamirmahal** [comment]
We can see this issue on the latest commit to `main`, [f164637](https://github.com/gleam-lang/gleam/commit/f164637e2b67974aff19db18be5a0a60f9d9f9c0).

**Comment by hamirmahal** [comment]
![image](https://github.com/gleam-lang/gleam/assets/43425812/80933577-b99f-40be-8542-ead2f4be7171)

**Comment by hamirmahal** [comment]
https://github.com/gleam-lang/gleam/actions/runs/8631239316

**Comment by lpil** [comment]
Thank you
