### ISSUE TITLE
Comments in lists get moved out of the list during formatting

### ISSUE THREAD

**Issue by jfmengels** [gleam-lang/gleam#2970]
Comments in list get moved out of the list in Gleam v1.0.0.
(Discovered on Ubuntu, on autoformat in VSCode with the Gleam plugin)

## SSCCE

Say I have this code (already formatted)

```gleam
const something = 1

const list = [
  something,
  something,
  something,
  something,
  something,
  something,
  something,
  something,
  something,
  something,
  something,
]
```

and I then comment out one element

```gleam
const something = 1

const list = [
  something,
  something,
  something,
  something,
  something,
  something,
  something,
  // something,
  something,
  something,
  something,
]
```

then the code will be reformatted as
```gleam
const something = 1

const list = [
  something,
  something,
  something,
  something,
  something,
  something,
  something,
  something,
  something,
  something,
]
// something,
```

The same problem appears if I try to add a comment about something

## Why is this a problem?

This is in my opinion a problem because
- it's unexpected
- you can't add comments that target specific parts of the code if they're moved somewhere else on format
- you can't easily comment then uncomment something and expect to get back to the original code

---

Apart from issues like this, the formatter has been great so far :blush:
Thank you for making it, and having it so easily available to newcomers, it's great :heart:

**Comment by lpil** [comment]
How strange, this was reported as done. Closing in favour of the original issue. https://github.com/gleam-lang/gleam/issues/2911
