### ISSUE TITLE
LSP: Hexadecimal and Binary literals don't get highlighted if used with underscore

### ISSUE THREAD

**Issue by PastMoments** [gleam-lang/gleam#2984]
Using gleam v1.0.0, with VSCode. Wasn't sure whether to put it here or in the extension repo, so I just put it here.

![image](https://github.com/gleam-lang/gleam/assets/3858420/ffc141d9-df4d-4113-b05f-6deb62fa4014)
```gleam
let _ = 123
let _ = 1_232_312
let _ = 0xFF
let _ = 0xFF_FF
let _ = 0b101101
let _ = 0b101_101
  ```
This compiles and runs just fine as expected, but the LSP doesn't seem to recognize the hex and binary with underscores as numeric literals and won't highlight them.

Note that unlike regular numbers, I don't want for these to be automatically formatted (the way normal integers are), as there's no clear way of determining where the separation is supposed to be. I'm currently using these underscores extensively in bitarrays to improve readability of magic bytes in file formats. This issue is just about the highlighting.

**Comment by lpil** [comment]
Hello! The language server doesn't provide syntax highlighting so you'll need to open this in the repo for whatever Gleam syntax highlighter you are using.
