### ISSUE TITLE
Formatter: Don't split on the last argument of a function

### ISSUE THREAD

**Issue by jfmengels** [gleam-lang/gleam#2987]
Something that feels a bit annoying to me with the formatter is on splitting sub-expressions rather than the top expression. From a conversation with @giacomocavalieri, I understand this is a special where the last argument is preferred to be split up rather than the rest.

I can see this being somewhat valuable for functions, but I think it doesn't look great for on at least tuples. Example:

```gleam
fn x(schema) {
  something_a_bit_longish(schema: schema, errors_and_context: #([], other_quite_long_thing))
}
--> gets formatted as
fn x(schema) {
  something_a_bit_longish(schema: schema, errors_and_context: #(
    [],
    other_quite_long_thing,
  ))
}
```

I would argue that a better split here would be splitting up the largest expression on the line instead, here being the function call, without touching the sub-expressions, like this:

```gleam
fn x(schema) {
  something_a_bit_longish(
    schema: schema,
    errors_and_context: #([], other_quite_long_thing)
  )
}
```

Then if the value for `errors_and_context` here is still too long, then that would be split it up as well.

I'm assuming the intent was to have last-argument functions (which is common in Gleam) create a new block with less indentation, which I can appreciate. I'm not sure how to combine my proposal with functions, unless by restricting the original re-formatting syntax to only functions. Maybe that would be okay though.

(@giacomocavalieri talked me into creating an issue to have a discussion about this)

**Comment by lpil** [comment]
Hello! This is by design. Thank you
