### ISSUE TITLE
Display qualified type names on LSP hover

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#2993]
When you hover over a variable the LSP can show its type. In this example you can see that it shows `List(Error)`, I think the LSP should show the `Error` type as qualified since it's not defined in the same module and I didn't import It qualified from the module it's defined in. So what I'd like to see here is `List(rule.Error)`
Not sure how feasible this is and we would probably want to make exceptions for prelude types but I think it could make the type on hover more helpful

![The error type should be qualified here since I didnt import unqulified and is not defined here](https://github.com/gleam-lang/gleam/assets/20598369/eda34e8b-14da-4c15-a77b-75dcd550dea2)

**Comment by Acepie** [comment]
Posting here for whoever works on this (I might work on this but wanna see if others have thoughts). The main difficulty with implementing this is that the types that the LSP prints are created using the same type pretty printer that the docs and error messages use. [Currently](https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/type_/pretty.rs#L59) that pretty printer only qualifies types if there would be a collision with an existing type that has already been printed. Making this change would require changing the behavior in a way that still lets those work the same as today (maybe by allowing the caller to pass in modules to never qualify and defaulting to qualify unless the module is explicitly excepted)

**Comment by lpil** [comment]
There are multiple LSP related tickets open that want a context aware printer, so making one and switching over all the LSP stuff sounds good to me.

**Comment by ascandone** [comment]
I'd like to give it a try. I've got a WIP here https://github.com/gleam-lang/gleam/pull/3312
