### ISSUE TITLE
Failure opening tar archive

### ISSUE THREAD

**Issue by aiwaki** [gleam-lang/gleam#2994]
### Steps and code to reproduce the problem

I just want to add packages:

```ps
PS D:\Projects\gleam\my_project> gleam add wisp 
  Resolving versions
Downloading packages
error: Failure opening tar archive

There was a problem when attempting to expand a to a tar archive.    

This was error from the tar library:

    Unable to locate Hex package contents.tar.gz
```
and
```ps
PS D:\Projects\gleam\my_project> gleam add lustre
  Resolving versions
Downloading packages
error: Failure opening tar archive

There was a problem when attempting to expand a to a tar archive.

This was error from the tar library:

    Unable to locate Hex package contents.tar.gz
```

It looks like this error only occurs for these packages

---

### Versions for Gleam, OS, the runtime and any other software used

`gleam 1.0.0`

```
Edition	Windows 11 Pro
Version	23H2
Installed on	‎8/‎17/‎2023
OS build	22631.3374
Experience	Windows Feature Experience Pack 1000.22688.1000.0
```

#### Logs from running Gleam with the `GLEAM_LOG` environment variable set to `trace`
How to do it? I tried just adding it manually, but nothing has changed

**Comment by lpil** [comment]
Do other packages succeed?

> How to do it? I tried just adding it manually, but nothing has changed

This will be specific to whatever shell you are using. If you're using a UNIX-compatible shell you can run `export GLEAM_LOG=trace`.

**Comment by lpil** [comment]
Could you delete `C:\\Users\\makse\\AppData\\Local\\gleam\\hex\\hexpm\\packages` for me and try again please.

**Comment by aiwaki** [comment]
Now everything is all right. I've reinstalled Gleam before, but it looks like that folder didn't go away with it. But it's still strange. Anyway, thanks!
