### ISSUE TITLE
lsp range_includes logic is swapped

### ISSUE THREAD

**Issue by raquentin** [gleam-lang/gleam#2997]
I'm working on LSP code actions and came across this helper function for determining overlap between cursor selection and relevant file characters:

```rust
// Check if the inner range is included in the outer range.
fn range_includes(outer: &lsp_types::Range, inner: &lsp_types::Range) -> bool {
    (outer.start >= inner.start && outer.start <= inner.end)
        || (outer.end >= inner.start && outer.end <= inner.end)
}
```

Is this correct? Consider the case where inner is fully within outer. This implies outer.start < inner.start and inner.end < outer.end. It's like [ ( ) ]. This case fails entirely.

I've switched `inner` and `outer` in the implementation on my local lsp branch while I work through stuff, but can switch back if this behavior is intended.

**Comment by lpil** [comment]
Thank you
