### ISSUE TITLE
Add diagnostic for unnecessary function capture

### ISSUE THREAD

**Issue by u9g** [gleam-lang/gleam#2999]
Thanks for all the work that has gone into the language and the diagnostics, they truly are amazing!

While going through the tutorial, it occurred to me after I wrote this and then removed the `(_)` that the function capture was completely unnecessary, but with no warning I'm sure this error exists in a ton of codebases already, and could be easily dealt with with a diagnostic added to the compiler.

```gleam
  1
  |> int.to_string(_) // <-- (_) is unnecessary and can be removed without changing the meaning of the pipeline
  |> string.repeat(5)
  |> string.drop_left(2)
  |> io.println
```

**Comment by lpil** [comment]
This is a great idea! Thank you!

**Comment by giacomocavalieri** [comment]
I can try and work on this!
