### ISSUE TITLE
Allow for suffix matching in the same way that prefix matching works now

### ISSUE THREAD

**Issue by u9g** [gleam-lang/gleam#3000]
I'm not sure if this is a breaking change, and if it is feel free to close it because of the breaking changes are not possible policy. In any event, in my eyes the following two snippets of code should work but today only the first works.

```gleam
fn get_name(x: String) -> String {
  case x {
    "Hello, " <> name -> name
    _ -> "Unknown"
  }
}
```

```gleam
fn get_greeting_to_mike(x: String) -> String {
  case x {
    greeting <> "Mike" -> greeting
    _ -> "Unknown"
  }
}
```

If this has already been discussed somewhere, I would love to read the discussion about it.

**Comment by lpil** [comment]
Hello! A nice idea but this is an issue you'd need to open with the OTP team as it's a runtime feature rather than something Gleam specific.
