### ISSUE TITLE
LSP completion only works when starting from an empty line

### ISSUE THREAD

**Issue by andrewphelpsj** [gleam-lang/gleam#3009]
Hello! First off, thanks for all the hard work, and congrats! I really appreciate the focus on developer tooling, especially considering how young the ecosystem is.

When using the gleam language server (gleam version 1.1.0) in Neovim (version v0.9.5), I'm running into a bit of an odd issue with regard to completion. I get completions when asking the editor for them (`<C-x><C-o>` by default) on an empty line. However, if the line has something on it, then either I get no completion suggestions, or I get completion suggestions as if the line weren't there. Here is a video that might explain it a bit better:

https://github.com/gleam-lang/gleam/assets/136256549/62af1765-d5d7-4a8b-b365-d6524c0b1c47

When I ask for completions with `io.` already on the line, it seems like I'm not getting anything back from the server.

Let me know if you think that this is a Neovim problem, and I'll file something over there. I'm thinking it isn't though, since other language servers operate as expected.

Lastly, here is a minimal Neovim config that I used to reproduce the issue in that video:
```lua
vim.opt.completeopt:remove('preview')

local on_attach = function(client, bufnr)
  vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
end

local lspconfig = require("lspconfig")

lspconfig.util.default_config = vim.tbl_extend(
  "force",
  lspconfig.util.default_config,
  {
    on_attach = on_attach,
    handlers = {
      ["textDocument/publishDiagnostics"] = vim.lsp.with(
        vim.lsp.diagnostic.on_publish_diagnostics, {
          virtual_text = false,
          signs = false,
        }
      ),
    },
  }
)

lspconfig.gleam.setup{}
```

This assumes that you have the `neovim/nvim-lspconfig` plugin installed, which was the only one installed in the making of that video.

Edit: I got a screenshot of completions that don't consider the line contents:

![image](https://github.com/gleam-lang/gleam/assets/136256549/0db6112e-151c-4194-9a97-3ab3b3f93a80)

**Comment by lpil** [comment]
Hello! Fault tolerant autocompletion is not yet implemented so if you trigger autocompletions at a byte index that is outside of an expression at the previous fault-free compilation then it will not suggest expressions.
