### ISSUE TITLE
Add pre-built binary for Android

### ISSUE THREAD

**Issue by Juhan280** [gleam-lang/gleam#3014]
I was using gleam on Android using termux using the aarch64 linux pre-built binary but it was giving me dns error

![Screenshot_20240420-013201_Termux](https://github.com/gleam-lang/gleam/assets/92646057/36bcffc1-8c70-42de-bf31-2bb43821204f)

After some [discussion in discord](https://discord.com/channels/768594524158427167/1230964341205897267) we found out that it could be solved if I build the binary from source. However it takes a lot of time to build it that way. I would love to have a pre-built binary for Android

**Comment by lpil** [comment]
Hello! Is this something we could do today on GitHub actions? I don't know anything about compiling for Android I'm afraid.

**Comment by Juhan280** [comment]
I am not that experienced in rust. But i did some research. I think we could add the android target to `target` and `include` property of `release.yaml`
![Screenshot_20240420-230047_Termux](https://github.com/gleam-lang/gleam/assets/92646057/00a2bcf7-7564-4a6c-9f5b-6c7676424bcf)


For reference
https://rust-lang.github.io/rustup/cross-compilation.html

**Comment by Juhan280** [comment]
I tried but couldn't make it work 
https://github.com/Juhan280/gleam/actions

**Comment by PgBiel** [comment]
This article suggests it's possible with `cross`: https://reemus.dev/tldr/rust-cross-compilation-github-actions#heading-compiling-with-cross

I saw you tried to do so here: https://github.com/Juhan280/gleam/actions/runs/8767097805/job/24060032517

Seems like a library is missing (`-lunwind` from the error). I wonder whether it can be installed.

Alternatively, this stackoverflow thread had some success with `cargo ndk`[^1]: https://stackoverflow.com/questions/75909583/cross-compiling-rust-crate-on-windows-for-android

We will probably need to experiment with configuring those tools until we find a suitable configuration.

[^1]: https://github.com/bbqsrc/cargo-ndk

**Comment by PgBiel** [comment]
Actually, seems like this is a bug with `cross`, to be addressed soon by upstream (apparently already fixed on cross' main branch): https://github.com/cross-rs/cross/issues/1222

So we should be able to wait for a new `cross` release.

**Comment by Juhan280** [comment]
Termux now provides gleam. This issue can be closed now
![Screenshot_20240725-003948_Termux](https://github.com/user-attachments/assets/1e736542-6926-49cc-8090-160f87e15079)

**Comment by lpil** [comment]
Sweet, thank you!
