### ISSUE TITLE
LSP: Allow jumping to definition on qualified import module name, and unqualified import in import statement.

### ISSUE THREAD

**Issue by quentin-fox** [gleam-lang/gleam#3016]
Loving the new LSP jump-to-definition in 1.1! It makes a big difference when exploring the language for the first time.

Two places that would be great to have jump-to-definition enabled would be the following:

1. Qualified import module name:

```gleam
import gleam/int
               ^
```

Being able to just jump to the file that a module resolves to would be great, so I can poke around in its code without needing to first use a function from that package, then doing jump-to-definition on that.

In the typescript language server, jumping to definition here would just land you at the start of the file that this import resolves to.

2. Unqualified import

Unqualified imports could go one of two places

e.g.
```gleam
let headers: List(Header) = [#('Content-Type', 'application/json')]
                  ^
```

Should jump to :

```gleam
import gleam/http.{type Header}
                        ^
```

And then jumping to definition on the `Header` in the import statement could take us to the definition in the module that it came from.

Alternatively, jumping to definition from here

```gleam
let headers: List(Header) = [#('Content-Type', 'application/json')]
                  ^
```

Could take us directly to where it's defined in the http module, instead of taking us to the import statement.

In this case, we would also want to allow jumping from where it's imported directly to its definition as well, e.g.

```gleam
import gleam/http.{type Header}
                        ^
```

Should jump to where the Header type is defined.

For reference, the typescript language server,  jumping to definition on an equivalent piece of code would take you directly to the module, instead of first taking you to the import statement.

Both approaches could have their benefits - the second is definitely more standard in other language servers I have used.

**Comment by lpil** [comment]
Thank you, good suggestions. 2 has an open PR. Could you split 1 and 3 into their own issues as they're independent items of work.

**Comment by Acepie** [comment]
I'll probably try to work on 1 after the other pr gets merged since most of the plumbing should already be there anyway

**Comment by Acepie** [comment]
1 and 3 should be taken care of by https://github.com/gleam-lang/gleam/pull/3051 whereas in case 2 we will instead just jump directly to the definition
