### ISSUE TITLE
Bad suggestion on import file

### ISSUE THREAD

**Issue by adkron** [gleam-lang/gleam#3021]
gleam -> 1.0.0
OSX - 14.4.1

I had a file spelled wrong, and when I tried to include it in my test, I was given a strange suggestion.

```gleam
 ┌─ /Users/amosking/workspace/talk/test/talk/client_test.gleam:2:1
  │
2 │ import talk/client
  │ ^^^^^^^^^^^^^^^^^^ Did you mean `should`?
```

<img width="237" alt="Screenshot 2024-04-20 at 3 24 48 PM" src="https://github.com/gleam-lang/gleam/assets/4253/041ecd21-0b2c-47b3-8427-2322dc700037">

**Comment by lpil** [comment]
This has been rewritten in v1.1 so if you upgrade you'll get better suggestions. Thank you!
