### ISSUE TITLE
Alias unqualified imports

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#303]
```javascript
import gleam/list.{map as list_map}
```

**Comment by zjhmale** [comment]
working on this

**Comment by lpil** [comment]
Thank you

**Comment by thehabbos007** [comment]
Hey!
I started looking at this feature today and I've suceeded in adding the syntax to the grammar and the AST. However, I am unsure how to correctly do something like module alias. 

I thought maybe adding a variable to the environment might be a solution to alias the imports? I'm not quite sure the implications of doing that though :)

**Comment by lpil** [comment]
Great! Thanks for your help.

I was thinking something like this: 

Add a field to the UnqualifiedImport AST node for the alias name. This is sometimes there and sometimes not so I'd make the field `Option<String>`. https://github.com/gleam-lang/gleam/blob/87aa490e6813bbe208472e1a2bf60ed8e9a39ddf/src/ast.rs#L157-L160

Then in the typer when we are processing each UnqualifiedImport insert the variable or type using the alias field if it is present, or the regular name if it is not.
https://github.com/gleam-lang/gleam/blob/87aa490e6813bbe208472e1a2bf60ed8e9a39ddf/src/typ.rs#L2008-L2016

A test like this one for an aliased value and another for an aliased type would be good https://github.com/gleam-lang/gleam/blob/87aa490e6813bbe208472e1a2bf60ed8e9a39ddf/src/project.rs#L817-L855

**Comment by lpil** [comment]
If you get stuck anywhere or no longer have time to continue please open a WIP PR and either we'll help you continue or I'll pick up this work from you, whichever you prefer :)

**Comment by thehabbos007** [comment]
Yes, I had tried to do the same as above in the typer, but the compiled erlang files use the alias instead of the relevant function. I assume I somehow have to map the alias to the real function name, right? Or am i missing something? :)

**Comment by lpil** [comment]
It's possible there's more to do after those steps. The compiler is too large to fit in my head these days :)

Please open a PR and I'll take a look

**Comment by lpil** [comment]
Waiting on #357
