### ISSUE TITLE
Improve error message for `use` with function with incorrect arity

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#3032]
Consider this snippet of code:
```gleam
import gleam/result

pub fn main() {
  use a <- result.try(todo, todo)
  todo
}
```
The error message from the compiler looks like this:
```txt
error: Incorrect arity
  ┌─ /src/main.gleam:4:3
  │  
4 │ ╭   use a <- result.try(todo, todo)
5 │ │   todo
  │ ╰──────^ Expected 2 arguments, got 3

This call accepts these additional labelled arguments:

  - apply
```
Which I think could be quite confusing, especially since it highlight the whole block below use. I think it could be more helpful if it highlighted just the function name and explained you shouldn't supply its last argument:
```txt
error: Incorrect arity
  ┌─ /src/main.gleam:4:3
  │  
4 │     use a <- result.try(todo, todo)
  │              ^^^^^^^^^^

Something something

See: https://tour.gleam.run/advanced-features/use/
```
I'm not sure how to word the error message though 😅

**Comment by lpil** [comment]
This is one place where I feel that two arrows might be useful, one pointing to the arguments, one pointing to `result.try`.  The library we use does support that I believe, but our diagnostic type only supports one.
