### ISSUE TITLE
Improve error message when there's something that's not a function to the left of `use` 

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#3033]
Consider this snippet of code:
```gleam
pub fn main() {
  use <- 1
  todo
}
```
The resulting error looks like this:
```txt
error: Type mismatch
  ┌─ /src/main.gleam:2:10
  │
2 │   use <- 1
  │          ^

This value is being called as a function but its type is:

    Int
```
But someone who doesn't know how use works might be left wondering _why_ that's an error, I think a more helpful error message could look something like this:
```txt
error: Type mismatch
  ┌─ /src/main.gleam:2:10
  │
2 │   use <- 1
  │          ^

On the right hand side of the `<-` operator should go a function
that takes a callback function as its last argument.
This value has type:

    Int

See: https://tour.gleam.run/advanced-features/use/
```

**Comment by lpil** [comment]
The problem here is that `use` is sugar and the analyser doesn't know anything about it has already been erased. We should promote it to being something more than sugar, then we can have much better error messages.

**Comment by giacomocavalieri** [comment]
Ok! I'd really like to work on this, if I finish my backlog of other issues I need to work on before anyone does this, I'll give it a shot!
