### ISSUE TITLE
Dev dependencies are written into the app list in .app.src

### ISSUE THREAD

**Issue by Nicd** [gleam-lang/gleam#3035]
See the `gleam.toml` in <https://preview.hex.pm/preview/bigi/3.0.0/show/gleam.toml>, `gleeunit` is only a development dependency. But in the created `.app.src`, `gleeunit` is included as a dependency application: <https://preview.hex.pm/preview/bigi/3.0.0/show/src/bigi.app.src>.

Context: I managed to get `bigi` compiling in Elixir by putting `{:bigi, "~> 3.0", manager: :rebar3}` in `mix.exs`, but trying to run fails due to not having `gleeunit`. If I edit `_build/dev/lib/bigi/ebin/bigi.app` and remove `gleeunit` manually, I can open IEx and run `bigi` code successfully! :)

```
zsh/2 486 % iex -S mix
Erlang/OTP 26 [erts-14.1] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.16.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :bigi.zero()
0
iex(2)> :bigi.add(1, 2)
3
```

**Comment by Nicd** [comment]
The compiler (or rebar3?) also warns

```
===> "/home/nicd/test/gleam_test/_build/dev/lib/gleam_json/ebin/gleam_json.app" is missing kernel from applications list
===> "/home/nicd/test/gleam_test/_build/dev/lib/gleam_json/ebin/gleam_json.app" is missing stdlib from applications list
```

and indeed `kernel` and `stdlib` are not in the app files. I'm not sure if that's an issue or not.

**Comment by Nicd** [comment]
Whether dev deps are included is controlled by this line: https://github.com/gleam-lang/gleam/blob/55a4e5881923e5679dde57cf950de389d6e04be4/compiler-core/src/build/project_compiler.rs#L520

We could turn it to `false` there, but I suppose that would break functionality if the user wants some app to exist in development but not in production (like `phoenix_live_reload` type things)? So do we need a dev/prod distinction to proceed with this issue?

**Comment by Acepie** [comment]
Would it ever make sense to include dev deps in prod? Cause the project compiler already has the mode for dev vs prod so unless there is a reason we would want to keep dev deps in prod we could always update that line to check `mode != Mode::Prod` instead since dependencies are all compiled in prod mode already

**Comment by Nicd** [comment]
But, do we ever use the prod mode? I was under the impression that we don't have prod builds. That's what I meant by having a dev/prod distinction, i.e. do we need to start using prod builds?

A lighter alternative could be to detect when building for Hex upload and not including dev deps then?

**Comment by Nicd** [comment]
Hmm, I guess I'll try it out and see. 👍

**Comment by lpil** [comment]
It'd be good to have a test for the contents of the Hex tarball if that's something we don't already have.

**Comment by Nicd** [comment]
There is a `test-package-compiler`, but it forces `include_dev_deps: true`.
