### ISSUE TITLE
Unable to give completions to LSP for dot completions

### ISSUE THREAD

**Issue by u9g** [gleam-lang/gleam#3036]
The following code can't be completed using ctrl+space because it fails to parse.

```gleam
import ct/reflection
import ct/item

pub fn get_item_from_give_code(give_code: String) -> item.Item {
  reflection.
}
```

You will not know about it though, as compilation silently fails, however when I remove the silent failing, we get the following error:

```
Panic: C:\Users\---\Documents\code\4-20-24\gleam\compiler-core\src\build\package_compiler.rs:123
	called `Result::unwrap()` on an `Err` value: Parse { path: "c:\\Users\\Jason\\Documents\\code\\4-20-24\\examplemod\\src\\ct\\act.gleam", src: "import ct/reflection\r\nimport ct/item\r\n\r\npub fn get_item_from_give_code(give_code: String) -> item.Item {\r\n  reflection.\r\n  todo\r\n}\r\n", error: ParseError { error: UnexpectedToken { expected: ["A positive integer or a field name."], hint: None }, location: SrcSpan { start: 123, end: 128 } } }
```

This is a big problem because if we always need completely valid code to offer completions, we can never offer dot completions.

I'm not sure what the next steps are here but I am open to ideas. Maybe something like adding a placeholder for `XX.\n` to the parser that will allow us to finish parsing the line so that we can still get diagnostics?

**Comment by u9g** [comment]
Another thing to consider is that the user has no idea there is a parse error if we silently dispose of parse errors.

**Comment by lpil** [comment]
Hello! This is not implemented yet.
