### ISSUE TITLE
No module has been found with the name `gleam/os`.

### ISSUE THREAD

**Issue by codereport** [gleam-lang/gleam#3042]
Any help on why this isn't working?
```
cph@NV-MJ0FQFL1:~/project_gleam$ cat gleam.toml
name = "project_gleam"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.37.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
```
```
cph@NV-MJ0FQFL1:~/project_gleam$ gleam --version
gleam 1.1.0
```
```
cph@NV-MJ0FQFL1:~/project_gleam$ gleam build
  Compiling project_gleam
error: Unknown module
  ┌─ /home/cph/project_gleam/src/project_gleam.gleam:4:1
  │
4 │ import gleam/os
  │ ^^^^^^^^^^^^^^^

No module has been found with the name `gleam/os`.
```

**Comment by lpil** [comment]
I'm a bit confused as there is no `gleam/os` that I'm aware of. Where did you learn about that module?

**Comment by codereport** [comment]
@lpil 
> I'm a bit confused as there is no `gleam/os` that I'm aware of. Where did you learn about that module?

https://hexdocs.pm/gleam_stdlib/0.12.0/gleam/os/

**Comment by codereport** [comment]
Thanks for the reply @lpil. 

In case your curious, I asked GPT4 to convert some python code and is did it incorrectly using `gleam/os`. Than when I got the error, I googled it and google returned that as one of the top results. 

This was my first time playing with Gleam and I had no clue what the latest version of the library was, and it seemed reasonable that there would be an `os` module. 

A small recommendation would be to do what the C++ Boost libraries do with their documentation. They add a `NOT THE LATEST VERSION` banner at the top of the site with a link to the latest one. See here: https://www.boost.org/doc/libs/1_39_0/libs/range/.

![image](https://github.com/gleam-lang/gleam/assets/36027403/14f7df15-42fb-45c7-acac-289ad28bb676)

PS - Your language seems great. I listed to your interview on The ChangeLog and got interested when you said "Function Go (as opposed to Rust on the Beam)." If it is really in the performance neighborhood of those languages that is really exciting.

**Comment by lpil** [comment]
Please do not use ChatGPT for Gleam code. It is unsuited for programming help and you will have a bad time. A very large portion of the people reporting problems with Gleam are those who are using ChatGPT instead of using the Discord and official documentation.
