### ISSUE TITLE
Do not complain about match on literal empty tuple

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#3068]
Right now the compiler provides a wrong suggestion when one tries to pattern match on a literal empty tuple:
```gleam
case #() {
//   ^^^ Redundant tuple wrapper, you can remove this
  _ -> todo
}
```
But following the compiler's advice would lead to a syntax error, despite this pattern matching being useless I think we do not want this warning on empty tuples

**Comment by lpil** [comment]
Good idea!

**Comment by Acepie** [comment]
In this case, do we want to remove the warning or just change the error message. Cause I can't imagine a case where matching on an empty tuple literally would be right. Maybe instead showing a custom warning for the 0 case suggesting they remove the case itself instead?

**Comment by giacomocavalieri** [comment]
I think for now removing the warning would be just fine. In the future the compiler could warn for more matches on literal values though:
```gleam
case 1 {
//   ^ There's no need to match on this
  _ -> todo
}
```
```gleam
case 1 {
//   ^ There's no need to match on this
  _ -> todo
}
```
```gleam
case "a" {
//   ^^^ There's no need to match on this
  _ -> todo
}
```
```gleam
case Wibble(a, b) {
//   ^^^^^^^^^^^^ We can reuse almost the same warning we have for tuples if
//                matching on an immediately applied record constructor
  _ -> todo
}
```
