### ISSUE TITLE
`Some checks were not successful` in CI

### ISSUE THREAD

**Issue by hamirmahal** [gleam-lang/gleam#3082]
This could be a result of Rust's recent `1.78.0` release.

**Comment by hamirmahal** [comment]
https://github.com/gleam-lang/gleam/actions/runs/8929946798

**Comment by hamirmahal** [comment]
![image](https://github.com/gleam-lang/gleam/assets/43425812/9dbf3031-f841-4b72-b968-c823b16c61c1)

**Comment by giacomocavalieri** [comment]
Thanks for the help! This was addressed in #3075
