### ISSUE TITLE
asdf local gleam version - move compile gleam binary into a bin subdir

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#3085]
`asdf gleam uninstall nightly && asdf gleam install nightly` failed today supposedly because the CI on the nightly was broken.

So I checked if I can use `asdf` to specify a local version, and I can.

in `.tool-versions`:

```
gleam path:../gleam-src/target/debug
```

This means I have my gleam project next to the gleam compiler which in this case is in gleam-src.

However, asdf looks for `PATH/bin/gleam`. I have added a dir and symbolic link into target/debug for now and it works. However to make it seamsless to use asdf with locally compiled versions of gleam it would be nice compiled gleam binaries could be put into a bin subdirectory so for instance into `/target/debug/bin/`. Would that be possible?

**Comment by lpil** [comment]
Not possible I'm afraid. asdf needs to adapt to Gleam, not the other way around.

**Comment by inoas** [comment]
> Not possible I'm afraid. asdf needs to adapt to Gleam, not the other way around.

I will bring it up with asdf then.

Is it possible to commit a symbolic link to git? That would solve it for now?

**Comment by inoas** [comment]
If the submission of the symbolic link works, maybe the PR is fine?
