### ISSUE TITLE
Docker image doesn't work on ARM 

### ISSUE THREAD

**Issue by krystofrezac** [gleam-lang/gleam#3094]
I am trying to use the official docker image but I am getting this error when pulling
```
docker pull ghcr.io/gleam-lang/gleam:v1.1.0-erlang-alpine

v1.1.0-erlang-alpine: Pulling from gleam-lang/gleam
no matching manifest for linux/arm64/v8 in the manifest list entries
```

I am getting the same result on my M1 Macbook and on my ARM Linux server.

Weirdly the older versions (from v1.0.0) work. So I assume that something changed in the build process. 
And if you look at the releases in web ui, they look different. The older ones have `Manifest` info at the bottom and the new ones have a weird value `unknown/unknown` under OS tab.
[v1.0.0](https://github.com/gleam-lang/gleam/pkgs/container/gleam/186437813?tag=v1.0.0-erlang-alpine)
[v1.1.0](https://github.com/gleam-lang/gleam/pkgs/container/gleam/204505765?tag=v1.1.0-erlang-alpine)

I tried overriding the platform with docker flag `--platform=linux/amd64` but that failed later during the build.

**Comment by krystofrezac** [comment]
So i tried the platform flag again and it's working. I probably did something wrong before. It seems that everything is related to this issue https://github.com/docker/build-push-action/issues/820. But nothing is blocking me anymore so I am gonna close this issue. Sorry for the spam.

**Comment by lpil** [comment]
Have we lost something that indicates what the platform is?

**Comment by krystofrezac** [comment]
Sorry, I don't understand the question. Do you mean the platform from which I tried it or that we lost something in the build process?

**Comment by lpil** [comment]
I'm not very familiar with how arch works in docker so this may be a silly question. You said there was something in a manifest with older versions that is now absent from the current ones. Is that something that would help if it was put back?

**Comment by krystofrezac** [comment]
I guess so, based on the error message I am getting. But my knowledge in this topic is also not very deep. 

Perhaps it would help to rerun the publish job. Assuming the bug was fixed in `build-push-action` it would publish "fixed" images. But I'm not sure you can do that without breaking something.

Btw does it work on your machine? I asked my college (also with MacBook m1) and he's getting the same error.

**Comment by lpil** [comment]
I do, but I would expect it to fail as we don't have an arm64 image. I don't understand why it worked previously.

**Comment by krystofrezac** [comment]
That might be it. When I run the `1.0.0` it runs via emulation. But it's still weird that the new one fails during pull but it doesn't matter that much now.

Do you have plans for adding arm64 image? Can I somehow help with it?

<img width="432" alt="Screenshot 2024-05-13 at 9 04 27" src="https://github.com/gleam-lang/gleam/assets/39591095/8345faae-19ea-4d8d-be96-c145b91523b0">

**Comment by Acepie** [comment]
For what its worth I actually ran into the same issue with the node image https://github.com/gleam-lang/gleam/pkgs/container/gleam/204505867?tag=v1.1.0-node but not with https://github.com/gleam-lang/gleam/pkgs/container/gleam/186438067?tag=v1.0.0-node

**Comment by lpil** [comment]
What do we need to do to resolve this?

**Comment by krystofrezac** [comment]
I am not sure yet. I still suspect that the `build-push-action` produces an incorrect manifest but I want to run some tests to be sure. Hopefully, I will have time to look into it next week.
