### ISSUE TITLE
dependencies::is_same_requirements is incorrect

### ISSUE THREAD

**Issue by u9g** [gleam-lang/gleam#3110]
`dependencies::is_same_requirements` is incorrect when a requirement is made using an absolute path in the `gleam.toml` 

this is what the left and right look like after going through the maybe canonicalize operations: 

` INFO download_deps: left: \\?\C:\Users\---\Documents\code\5-7-24\stdlib right: C:\Users\---\Documents\code\5-7-24\stdlib`

The solution is to just unconditionally canonicalize both paths.

**Comment by lpil** [comment]
Ah! Thank you.

**Comment by Francisco-Montanez** [comment]
I can take this if not done

**Comment by lpil** [comment]
Thank you @Francisco-Montanez !
