### ISSUE TITLE
Add diagnostic for panic/todo in option.unwrap / result.unwrap

### ISSUE THREAD

**Issue by u9g** [gleam-lang/gleam#3114]
The suggested fix should be `maybe_x |> option.lazy_unwrap(fn () { panic })` which is likely what the user wanted, as using `maybe_x |> option.unwrap(panic)` always panics since the argument isn't lazily evaluated. `todo` has the same problem as `panic` here.

**Comment by lpil** [comment]
Hello! This would be covered by this: <https://github.com/gleam-lang/gleam/issues/3023>

**Comment by giacomocavalieri** [comment]
Yes, I'm working on #3023 and can confirm that it will fix this problem!
