### ISSUE TITLE
The language server should be updated to use the latest compiled modules when recoverable errors occur

### ISSUE THREAD

**Issue by Acepie** [gleam-lang/gleam#3121]
Now that we have more fault tolerance in the module analysis, we have a number of cases where there can be type errors in a module but still have valid typed ASTs for those modules. Currently we are discarding those ASTs and bubbling up the error. We should instead update the compile step to use the new error filled ASTs and return without doing codegen https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/build/package_compiler.rs#L140

By doing this, the language server should be able to use those modules and give a better editor experience when there are errors

The error is returned here. This can probably just be bubbled up into the return with a slight return type change
https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/build/package_compiler.rs#L442

**Comment by lpil** [comment]
Thank you
