### ISSUE TITLE
Error message more helpful when having triple equals instead of double inside lambda fn

### ISSUE THREAD

**Issue by hagenek** [gleam-lang/gleam#3125]
[1,2,3] |> list.filter(fn (a) { a === 3 }) will produce an error :

```
error: Syntax error
  ┌─ /src/main.gleam:6:37
  │
6 │ [1,2,3] |> list.filter(fn (a) { a === 3 }) 
  │                                     ^ There must be a 'let' to bind variable to value
```
Hint: Use let for binding.
See: https://tour.gleam.run/basics/assignments/

**Comment by lpil** [comment]
Thank you. We don't need to have a specific `===` error message, but let's at least make this not show this error message in this case.

**Comment by giacomocavalieri** [comment]
It could be cool to have a specific error message for this case, especially for folks used to JS:
```text
error: Syntax error
  ┌─ /src/main.gleam:6:37
  │
6 │ [1,2,3] |> list.filter(fn (a) { a === 3 }) 
  │                                   ^^^ Did you mean `==`?

Gleam uses `==` to check for equality between two values.
```

**Comment by rabingaire** [comment]
Humm, I wonder if this error message is enough?

```
error: Syntax error
  ┌─ /Users/rabingaire/Desktop/gleam/example/test_app/src/test_app.gleam:4:37
  │
4 │   [1,2,3] |> list.filter(fn (a) { a === 3 }) 
  │                                     ^^ This operator has no value on its right side

Hint: Remove it or put a value after it.
```

**Comment by giacomocavalieri** [comment]
Yeah I agree that could be more than enough for all other binary operators, but in case of `===` in particular I think the compiler should try being a bit more helpful and show an error message like the one I showed before

**Comment by inoas** [comment]
Because people are so used to strictly equals why can't the formatter just kill it with fire and replace it with double equals?

**Comment by giacomocavalieri** [comment]
That could also be an option, but a good error message is still required as not everyone runs the formatter

**Comment by inoas** [comment]
> That could also be an option, but a good error message is still required as not everyone runs the formatter

100%
