### ISSUE TITLE
complaint about subsequent imported type, when initial type is missing

### ISSUE THREAD

**Issue by keroami** [gleam-lang/gleam#3134]
simple definition in one file:
```gleam
pub type Rule {
  Rule
}
```

trying to use it from another:
```gleam
import rule.{type NonExistent, type Rule}

pub fn x(rule: Rule) {
  todo
}
```

results in error:
```
error: Unknown type
  ┌─ /home/kero/t/src/instance.gleam:5:16
  │
3 │ pub fn x(rule: Rule) {
  │                ^^^^

The type `Rule` is not defined or imported in this module.

```

whereas the problem is with the non-existent type that's imported right before type `Rule`. That is, removing `type Nonexistant, ` will result in a succesful `gleam build`.

gleam git hash f863f0ba (pulled on May 13th)

**Comment by inoas** [comment]
I thought this might fix it https://github.com/orgs/gleam-lang/projects/4?pane=issue&itemId=61796488 ? but trying myself 

```gleam
import gleam/order.{type FooBar, type Order}

pub fn main(order: Order) {
  order
}
```

... I get the same issue as above.

**Comment by lpil** [comment]
Hello! Thanks for testing. This isn't quite finished yet :)
