### ISSUE TITLE
Wrong formatting in `case` expressions in presence of a long comment

### ISSUE THREAD

**Issue by GioeleBucci** [gleam-lang/gleam#3140]
I noticed a weird behaviour when commenting a case with multiple patterns and pointed it out to @giacomocavalieri to assure it wasn't intended behaviour.

Here's an example:
```gleam
fn foo(a: Int, b: Int) -> Bool {
  case a, b {
    // a very long comment a very long comment a very long comment a very long comment
    1, 2 -> True
    _, _ -> False
  }
}
```

After the formatting, the code above becomes the following:
```gleam
fn foo(a: Int, b: Int) -> Bool {
  case a, b {
    // a very long comment a very long comment a very long comment a very long comment
    1, 2
    -> True
    _, _ -> False
  }
}
```

Such behaviour happens only when the comment is quite long (i suppose > 80 characters?) and in case of a shorter one the formatter works as expected.
```gleam
fn foo(a: Int, b: Int) -> Bool {
  case a, b {
    // a not quite long comment
    1, 2 -> True
    _, _ -> False
  }
}
```

### Version info
OS: Windows 11
gleam 1.1.0
rebar 3.22.1 on Erlang/OTP 25 Erts 13.2.2.2

### Logs
[link to pastebin](https://pastebin.com/xzP0wawD)

**Comment by lpil** [comment]
Thank you
