### ISSUE TITLE
Do Gleam support compiling to Rust?

### ISSUE THREAD

**Issue by Jerrody** [gleam-lang/gleam#3145]
I would use Gleam for Game Engine in Rust as script language.

**Comment by lpil** [comment]
It does not, no

**Comment by lpil** [comment]
No, Rust is a very bad compile target, there would be no particular advantages. It would be especially bad for your use case, embedding a scripting language runtime would be much better as it's be easier to interop with and you could load code at runtime.

**Comment by inoas** [comment]
I would love to compile to rust to be able to use the rust eco system as an FFI much like I can use the Erlang one.

**Comment by inoas** [comment]
You mean as a NIF? OK then nvm.

**Comment by lpil** [comment]
Yes, you would need to write the same boilerplate even if we compiled to Rust
