### ISSUE TITLE
Support authenticating with an organization key

### ISSUE THREAD

**Issue by MAHcodes** [gleam-lang/gleam#3154]
hex allows organizations to generate an authenticating key for CI/CD, here: https://hexdocs.pm/hex/Mix.Tasks.Hex.Organization.html#module-generate-organization-key

It would be really useful if Gleam cli offered the authenticating using the key capability for publishing a package via CI/CD

**Comment by Acepie** [comment]
Just wanna double check. From what I can see from the hex docs, it sounds like using an organization key should work the same as using a regular user key once the key is generated. Have you tried using the existing https://github.com/gleam-lang/gleam/blob/main/compiler-cli/src/hex.rs#L13 environment variable to set the key with the organization key?

**Comment by MAHcodes** [comment]
thank you @Acepie , `HEXPM_API_KEY` worked!

tho, it's not included in the help: `gleam publish --help`.

thank you again and feel free to close the issue for whatever reason.

**Comment by Acepie** [comment]
Glad that worked:D though definitely would be good to make that more visible somehow

**Comment by lpil** [comment]
Thanks gang!
