### ISSUE TITLE
Language server does not update module information if the code matches the last successful compile

### ISSUE THREAD

**Issue by Acepie** [gleam-lang/gleam#3172]
Was testing out the new fault tolerance support with the language server and ran into a subtle case where the language server's module information is not properly updated. If the code of the last successful compilation exactly matches the current code then the compiler will reuse the old cached version of the module instead of recompiling the module. This causes issues for the language server since we now update the language server with incomplete/partial module information.

Example

```gleam
import gleam/int
import gleam/io

pub fn main() {
  7
  |> int.to_string
  |> io.println
}
```

If you comment out ` |> int.to_string` and then comment it back in, you will notice that language server functionality stops working within main.

Making any change that invalidates the cache (either a lsp reload or even just adding any white space) fixes the issue so its definitely not a high priority but was annoying/confusing when I first ran into it.

**Comment by lpil** [comment]
Thank you!
