### ISSUE TITLE
`@` is an illegal character in external javascript module name

### ISSUE THREAD

**Issue by ofekd** [gleam-lang/gleam#3179]
This is needed when importing scoped packages which start with `@`.

I could open a PR and add `@` as a character to the regex, but isn't it better to just allow anything, and leave the resolution to the bundler/runtime? 

In Linux, for example, almost any character is a legal filename, and therefore someone somewhere must have a very weirdly-named JS file that they want to use in an `@export`.

**Comment by lpil** [comment]
Thank you
