### ISSUE TITLE
LSP: autocomplete does not take into account prefix

### ISSUE THREAD

**Issue by dvic** [gleam-lang/gleam#3181]
Gleam versions: 1.1.0 and 1.2.0-rc1
Editor: Helix

Typing for example `int.`:

![image](https://github.com/gleam-lang/gleam/assets/1214337/1ce57b17-323c-4303-82ee-dcf90be60bac)

Then going to the `digits` function inserts `int.int.digets`:

![image](https://github.com/gleam-lang/gleam/assets/1214337/0fe34367-0408-42fc-8622-dbdaceedab79)

Finally typing enter, I indeed end up with a duplicate `int.int`:

![image](https://github.com/gleam-lang/gleam/assets/1214337/75ed19b9-16ad-49b8-a5af-e270f4407311)

**Comment by dvic** [comment]
To add to this, what does work:

Type `digits`:
![image](https://github.com/gleam-lang/gleam/assets/1214337/13d339b2-4bac-4555-93df-d6d8f8c875a4)

Select next suggestion:
![image](https://github.com/gleam-lang/gleam/assets/1214337/3d7cd3ea-d109-4582-a9ea-f67c64126ea9)

**Comment by lpil** [comment]
Hello! This is a bug in the LSP specification unfortunately. How completions are applied is ambiguous in the spec so different editors do different things here. VS Code and Zed duplicate the module qualifier, others do not.

This feature is going to be rewritten to not use this part of the spec, but again unfortunately the LSP API that is not ambiguous requires a good deal more work to implement.

**Comment by dvic** [comment]
> This feature is going to be rewritten to not use this part of the spec, but again unfortunately the LSP API that is not ambiguous requires a good deal more work to implement.

Clear. Out of curiosity, what part of the spec are we talking about here? Have you considered using https://github.com/elixir-tools/gen_lsp to handle the generic LSP stuff?

**Comment by lpil** [comment]
That doesn't help with this problem in any way, and I think async Rust is not well suited to a language server as it is CPU bound and only has one client at a time. It adds a lot of complexity in exchange for nothing that I can see.

**Comment by lpil** [comment]
We need to move from the simple completion API to providing text-edits which delete the qualifier. No one has yet done any work on how we're going to determine what the edits are yet. Your help would be super appreciated!!
