### ISSUE TITLE
add `gleam/math` to standard library

### ISSUE THREAD

**Issue by mvolkmann** [gleam-lang/gleam#3188]
Gleam is currently missing lots of math constants and functions found of most other programming languages. It would be nice, and not a breaking change, to add the module `gleam/math` that could define constants like `pi` and functions like those used in trigonometry. This could take inspiration from what is found here for OCaml: https://ocaml.org/manual/5.2/api/Float.html

**Comment by lpil** [comment]
We've already discussed this on discord, so please do not open issues for matters already resolved. Thank you

**Comment by mvolkmann** [comment]
@lpil I want to try to apologize for the way our Discord conversation ended. I think it would help if you knew a little about me. I am much, much older than you. I imagine you are in your 20's or early 30's. I am 63 and nearing retirement. It kind of goes with the territory for us older developers to share advice when we can, not that our opinions are necessarily correct.

I enjoy learning new programming language. Before starting to dig into Gleam, I learned OCaml. I tend to write about everything I learn. See my blog at https://mvolkmann.github.io/blog/. I started a page on Gleam, but there isn't much there yet.

A few years ago I wrote a book on Svelte for Manning. Very soon I will have a book out on htmx for Pragmatic Bookshelf. I'm considering creating an example that combines the use of htmx and Gleam. Who knows, maybe at some point I'll write a book about Gleam.

I really meant no offense when I suggested discussing what we talked about with fellow language designers. I was not being passive aggressive. I do not have direct access to many language designers. I do know Richard Feldman whose is working on Roc, but I assume you have much more access to people like yourself that I do.

I hope my explaining this helps you to not have a negative opinion of me. I find Gleam fascinating in large part due to the things it has in common with OCaml. I'd love to keep writing about it in my blog and maybe give a talk on it at a conference. I do a fair amount of conference speaking.

All the best to you and I hope Gleam continues to gain in popularity!

**Comment by mvolkmann** [comment]
@lpil Can you please email me at r.mark.volkmann@gmail.com to discuss this. I really want to understand what I said that offended you so I can avoid saying such things in the future. I want to help spread awareness of Gleam, but it will be difficult without your support.
