### ISSUE TITLE
Not all errors being printed

### ISSUE THREAD

**Issue by schurhammer** [gleam-lang/gleam#3191]
gleam 1.2.0-rc1-nightly-20240525

When you write an invalid type alias and the alias is used, you get the error "The type `X` is not defined or imported in this module." at the usage site, rather than the actual error of what is wrong with the alias.

e.g. typod Intt instead of Int

```gleam
type X =
  List(Intt)

fn example(a: X) {
  todo
}
```
```
fn example(a: X) {
              ^

The type `X` is not defined or imported in this module.
```

**Comment by lpil** [comment]
What would you have this say instead? There is no type with that name in scope in the module there.

**Comment by schurhammer** [comment]
There is a type X in the module! `type X = List(Intt)`

The error I want to have is this
```
error: Unknown type
   ┌─ /home/julian/projects/gig/src/env.gleam:10:8
   │
10 │   List(Intt)
   │        ^^^^ Did you mean `Int`?

The type `Intt` is not defined or imported in this module.
```
This is what you get when you delete the `example` function. The correct error gets suppressed somehow by that function being present.

**Comment by lpil** [comment]
Oh! It's only printing one of the errors for some reason. That's the bug. Thank you
