### ISSUE TITLE
[WEBSITE] 'Getting Started' link isn't present on gleam.run

### ISSUE THREAD

**Issue by d-m-h** [gleam-lang/gleam#3198]
Hi folks,

I'm not entirely sure where to file this report but I guess this one will get the most visibility. As someone who is new to Gleam, I noticed that the website has a distinct lack of "Getting Started". The only way I discovered the getting started page was by searching for it via a search engine. 

I think that this should be fixed because it is a barrier to entry with the language. The only other way of getting to the "Getting Started" page is by first navigating to Docs > Installing Gleam. I think that the Getting Started Call-to-Action should be on the landing page.

**Comment by lpil** [comment]
It's here!

![Screenshot 2024-05-25 at 14-49-21 Gleam](https://github.com/gleam-lang/gleam/assets/6134406/216f657e-0bbf-4af9-8778-7bbee2a183f6)

**Comment by d-m-h** [comment]
@lpil - thanks for your response, however, that doesn't take me to the "this is how you install gleam" page. It instead takes me to the tour of gleam page.

By getting started, I mean [this](https://gleam.run/getting-started/installing/) page.

I hope this clarifies things.
