### ISSUE TITLE
Wrong Assignment Error Message on Bad Names

### ISSUE THREAD

**Issue by Arian94** [gleam-lang/gleam#3204]
When defining a new Variable starting with a capital letter, it throws a wrong error message as in the picture. If not fixed yet, I have a possible solution by defining a new ```TypeError``` and implement its message in ```to_diagnostics()```. Please, inform me if my solution is proper.

![Screenshot 2024-05-27 143019](https://github.com/gleam-lang/gleam/assets/67897197/e8474560-4f12-4c9b-aa0a-4072decd9f38)

**Comment by lpil** [comment]
Oh dear! That is rubbish! Thank you

**Comment by lpil** [comment]
Ah! Now that I'm looking at this again I realise what is happening here. An uppercase letter means this is a pattern consisting of a single constructor. Let's make the error say something like this:

> This pattern is matching a constructor named `One`, but there is no constructor in scope with that name.

**Comment by Arian94** [comment]
If the error changes to what you mentioned, I believe there are some other cases where the error will be wrong. The ```UnknownVariable``` enum is used in multiple places and changing its error message would cause other places to change unintentionally.

**Comment by lpil** [comment]
Could you give an example of when that would be?

**Comment by Arian94** [comment]
```gleam
import gleam/io

pub fn main() {
  let one = 23
  let two = 4

  io.debug(one == three)
}
```

The error would be:
```gleam
The name `three` is not in scope here.
```

**Comment by lpil** [comment]
Yes, that's right.

**Comment by lpil** [comment]
It doesn't implement the behaviour I've outlined above, could you update it to do that please. Thank you

**Comment by Arian94** [comment]
I'm a bit unsure.

You mean it is only needed to update the ```Error::UnknownVariable``` error message to what you gave?
Or define a new Enum like I did and write the error message you mentioned?

**Comment by lpil** [comment]
I'm not saying anything specific about the implementation, I've not looked into how this would be implemented. We do need an error like the one above and only in the specific situation the first post of this issue shows.

**Comment by Arian94** [comment]
#3207 should work accordingly.
