### ISSUE TITLE
Allow string concatenation when defining const values

### ISSUE THREAD

**Issue by george-grec** [gleam-lang/gleam#3208]
This is currently not valid syntax:

```gleam
pub const foo = "foo"
pub const foo_bar = foo <> "bar"
```

It would be great if this would work!

**Comment by slightlybelowzen** [comment]
Just wondering why this isn't allowed? Is there a reason or was it just left to be implemented later?

**Comment by lpil** [comment]
Thank you! Good suggestion.

@slightlybelowzen It's just something no one has implemented.

**Comment by slightlybelowzen** [comment]
Fair enough, I could try to hack something together this weekend, see if I get anywhere.

**Comment by lpil** [comment]
Wonderful! Thank you

**Comment by DeviousStoat** [comment]
I started looking into that. Not sure if @slightlybelowzen has started something too but it doesn't matter too much to me if my code doesn't go anywhere, this is a pretty cool task to start getting familiar with the code.
I just had a question @lpil, do we want to support any binary operation in `const` statements or just the string concatenation?
If `foo <> "bar"` is allowed shouldn't any operation on consts be allowed too?

```gleam
pub const foo = 5
pub const foo_bar = foo + 5
```

**Comment by lpil** [comment]
Just concatenation for now as it does not require compile time code execution to implement.

**Comment by DeviousStoat** [comment]
why doesn't concatenation require compile time code execution? we should inline the concatenation operation? If so then what's the difference with inlining other operations?

**Comment by lpil** [comment]
Because that's how Erlang works.

**Comment by DeviousStoat** [comment]
yeah I don't know I was more thinking about the javascript part. sorry about the questions, I was just trying to understand a bit more. I will try to make a PR anyway, we'll see
