### ISSUE TITLE
Add `let assert ... as` syntax

### ISSUE THREAD

**Issue by isaacharrisholt** [gleam-lang/gleam#3216]
Originally mentioned in #2958.
Support some sort of `as` syntax when using `let assert` to add additional context as for why we want to panic.

For example, if querying for a DOM element that we need to be present:

```gleam
import plinth/document

fn main() {
  let assert Ok(el) = document.query_selector("#my-el")
  // ...
}
```

It would be nice to be able to provide some context with the crash about why we need that specific element to be there. The current alternative is:

```gleam
let el = case document.query_selector("#my-el") {
  Ok(el) -> el
  Error(_) -> panic as "Element needs to be present"
}
```

However, this is quite verbose and quite common, which is the reason for the `let assert` syntax in the first place.

There are a few options for syntax that I can come up with, in order of personal preference:

## 1. `as` at end

```gleam
let assert Ok(_) = my_result as "Element needs to be present"
```

I personally prefer to have the `as` clause at the end of the line, similar to `panic` and `todo`. The message could be varying length, and keeping it towards the end makes the line easier to read. However, to newer Gleam users, this may seem more like the `my_result as "X"` is one item, which could lead to confusion.

## 2. `as` after variable

```gleam
let assert Ok(_) as "Element needs to be present" = my_result
```

This option solves the potential confusion above, but it could also push the value we're asserting against quite far from the values we're trying to assign, e.g.:

```gleam
let assert Ok(_) as "Some really loooooooooooooooooooooooooooong message" = my_result
```

## 3. `as` after `assert`

```gleam
let assert as "Element needs to be present" Ok(_) = my_result
```

Again, this solves the confusion issue in 1, and keeps the values together, but having a string next to the `Ok(_)` just feels icky. Can't explain why. Sorry.

---

If you have any alternative syntax suggestions, let me know and I'll chuck 'em above :)

**Comment by giacomocavalieri** [comment]
I don't think 1 is what we should go for because it could lead to some confusion if you write this:
```gleam
let assert Ok(_) = todo as "error message"
```
Here you can't really tell if `as` is part of the first assertion or the `todo`.

I think 3 would be the best choice if in the future we also want some kind of `assert` keyword to support it as well in a similar way:
```gleam
// 3.
assert as "wibble" [1, 2, 3] = list.reverse([3, 2, 1])
assert as "wibble" is_empty([])
let assert as "wibble" Ok(result) = maybe_fail()
```

If we went with 2, that means that if we ever decide to add `assert` (on its own) the two ways to write it would look quite different and may be confusing:
```gleam
let assert Ok(result) as "wibble" = maybe_fail()

// I don't think this looks particularly good and has the same problems as 1.
assert [1, 2, 3] = list.reverse([3, 2, 1]) as "now this is last"

// But having `assert as "wibble" [1, 2, 3] = list.reverse([3, 2, 1])`
// now would look quite different from 2. used when assigning to a variable
// here it comes after `assert` while in the other after the pattern
```
So that's my reasoning for preferring 3, and even if we never get an `assert` keyword on its own I think it still looks slightly better 😁

**Comment by isaacharrisholt** [comment]
@giacomocavalieri I think I agree with you.

However, I'm assuming in your code example you meant something akin to this?

```diff
- assert as "wibble" [1, 2, 3] = list.reverse([3, 2, 1])
+ assert as "wibble" [1, 2, 3] == list.reverse([3, 2, 1])
```

I assume `assert` would just assert a boolean value in this case.

**Comment by LilyRose2798** [comment]
The `as` keyword as a whole is one of the more confusing keywords in Gleam in my opinion. With its use in `todo as "foo"` you can reasonably guess that the purpose of the string is to provide a label to the `todo` keyword, and with `panic as "foo"` you can possibly guess that the purpose of the string is to provide an error message to the `panic`, but the keyword `as` itself doesn't really do a good job at explaining anything about what the string is actually doing in either of those situations, so it's left up to the reader to deduce that via context.

With `assert as "foo"` (regardless of where the `as` actually ends up in the `let assert` statement), the intention of the string following the `as` is even less clear than the other two uses, and the `as` keyword in this situation does nothing to aid in the understanding of what the string might be for. Is it checking that string against something as part of the assertion? Or doing something else with the string? For new users of the language, I think this will be pretty confusing to read.

The issue that needs to be solved is being able to provide extra data to certain keywords, preferably in a way that makes it clear what the data being provided is (like with a labelled function arg), but without having the syntax be confused with a function call.

As a potential solution to this issue (or at least what I believe is an issue), I propose the following alternative to the `as` syntax, that can replace the current usage of `as` in its current use with `todo`, `panic` and be used in the future with `assert`:
```rs
todo#label="foo"
panic#error_message="foo"
assert#error_message="foo"

// whitespace should be supported (except for maybe after # to avoid parsing confusion with tuples)
todo #label = "foo"

// if a keyword supports more than one data item, they can be provided like so
todo #label="foo" #description="more detailed info"
```
The syntax is inspired by url query params (which helps to reinforce that they're optional attributes, not required ones). The language server should ideally show the available attributes that can be provided when hovering over a keyword, similar to a function signature (though distinct enough to avoid confusion).

I believe the only place the `#` symbol is used currently is in tuples, and for those it is required to be followed by either whitespace or a `(`, whereas in this situation it will always be followed by a name/identifier (which cannot include `(` or whitespace), so determining which it is in the parser should not be too difficult I imagine.

It might also be worth considering allowing this syntax to occur anywhere on the same line as a supported keyword for the purposes of keeping the main body of the line clean, such as with the following:
```rs
let assert Ok(foo) = returns_result() #error_message="got an Error instead of Ok"
```
It would basically act as a comment, except it would be passed as context to any keywords on that line. Any attributes that don't apply to a particular keyword can just be discarded when passed to it, which allows for lines containing multiple keywords to still receive their respective data:
```rs
let assert Ok(foo) = todo #error_message="got an Error instead of Ok" #label="add code that returns a Result"
```
Interested to know what others think of this suggestion, or if anyone has any other suggestions for the syntax of something like this.

**Comment by giacomocavalieri** [comment]
I've never seen `as` as confusing, it's really interesting to hear other's opinions about it!

Personally, I don't think that the labels make it any clearer than `as`: moving the error message at the end of the line away from the `assert` doesn't make it clearer, with `as` next to `assert` I immediately can tell that that's the assertion's error message and I don't have to skim through to the end of the line to see if it has any extra label attached

**Comment by LilyRose2798** [comment]
If keeping the label close to the source of the keyword is a desired property, then only allowing the `#attribute` right after the keyword could maybe be an option?
```rs
let assert#error_message="failed to match" Ok(foo) = returns_error()
```

**Comment by isaacharrisholt** [comment]
I also don't see `as` as a confusing thing. Like any keyword in any language, you have to learn its meaning, but once you've got it, it's fairly simple.

Also moving away from `as` to an attribute-based system like you've described would be a breaking change, which would need a whole new version number. The way to prevent that would be to keep `as` around, and I think having two bits of syntax for the same thing would arguably be even _more_ confusing.

**Comment by LilyRose2798** [comment]
I think `as` is ok-ish in its current usage for `todo` and `assert`, but `assert as` is getting to the point where it's becoming confusing to read in my opinion, and if more keywords are ever added, `as` is unlikely to really make sense from a readability standpoint for those either.
I understand the viewpoint of not wanting to introduce any more breaking changes though, so I'm not really sure how to improve the situation if anything breaking is off the table.

**Comment by isaacharrisholt** [comment]
It's not really any different to languages that do `assert predicate, " failure message"`, though I'd argue that's more confusing because in those languages (e.g. Python), `x, y` could be a tuple.

**Comment by lpil** [comment]
It has to be `as`, that is the established syntax for adding a message to a panic. We will not have a breaking change to change that.

Hayleigh has pointed out on discord that `let assert Ok(result) as "wibble" = maybe_fail()` is already valid syntax so we cannot use it here. This is unfortunate.

**Comment by sobolevn** [comment]
I am working on this right now :)

The main change would be:

```rust
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AssertAssignment<ExpressionT> {
    pub location: SrcSpan,
    pub message: Option<Box<ExpressionT>>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Assignment<TypeT, ExpressionT> {
    pub location: SrcSpan,
    pub value: Box<ExpressionT>,
    pub pattern: Pattern<TypeT>,
    pub assert: Option<Box<AssertAssignment<ExpressionT>>>,
    pub annotation: Option<TypeAst>,
}
```

**Comment by giacomocavalieri** [comment]
Implementation won't be too complex but we haven't landed on a design yet, I would wait until we decide what this should look like

**Comment by lpil** [comment]
How would it work with the upcoming `assert x != y` syntax? How would `as` work there?

**Comment by sobolevn** [comment]
@lpil sorry, I couldn't find the new `assert` spec anywhere, so I might be missing something. Generally `assert as "x is not equal to y" x != y` seems fine to me. In this case it would use this as a base message, while it also should show what `x` and `y` was in the error's context.

**Comment by GearsDatapacks** [comment]
What current problems are there with the proposed design? It would be nice to get this feature in the language

**Comment by lpil** [comment]
Which proposed design are you referring to @GearsDatapacks ?

**Comment by GearsDatapacks** [comment]
`let assert as "message" Ok(inner) = value`
That's the only version that works out of the initial proposal, and the one that most people seem to like

**Comment by lpil** [comment]
What do you mean it's the only one that works?

What would be the syntax for assert without let?

**Comment by GearsDatapacks** [comment]
> What do you mean it's the only one that works?

`let assert Ok(a) as "message" = value` would conflict with pattern assignment syntax, and `let assert something = panic as "message"` would also conflict.

> What would be the syntax for assert without let?

I like `assert as "message" some_condition`, I think it would fit well

**Comment by lpil** [comment]
Trailing as does not cause problems. The only thing it would do is force the programmer to specify a message for a todo or panic expression, but neither of those are real code so there's no issue.

I think preceeding `as` reads quite poorly and is an unusual syntax, with all the languages I've checked which have asserts with messages having them trailing. Because of this I'm leaning towards the trailing syntax:

```gleam
assert count == 5 as "must be multiple"
```

**Comment by GearsDatapacks** [comment]
That makes sense. Does trailing `as` for `let assert` make sense too? I can see it getting a bit tricky to read in certain situations but I feel this might be the case for any syntax we choose. For example:
```gleam
let assert Ok(something) = some_function_with_lots_of_arguments(
  arg1,
  arg2,
  arg3,
) as "This never fails because X"
```
But equally, if you have a long assert message if could make it difficult to see what is actually being asserted. Thinking about it now, rust has similar "syntax" with `Result::expect`, and that reads fine to me:
```rs
let something = some_function_with_lots_of_arguments(
  arg1,
  arg2,
  arg3,
).expect("This never fails because X");
```

**Comment by lpil** [comment]
Today this format is used

```gleam
let assert Ok(something) =
  some_function_with_lots_of_arguments(arg1, arg2, arg3)
```

So I think we'd format the message something like this


```gleam
let assert Ok(something) =
  some_function_with_lots_of_arguments(arg1, arg2, arg3)
as "This never fails because X"
```

or this



```gleam
let assert Ok(something) =
  some_function_with_lots_of_arguments(arg1, arg2, arg3)
  as "This never fails because X"
```

**Comment by GearsDatapacks** [comment]
Alright, that sounds reasonable. Are there any issues with this design?

**Comment by lpil** [comment]
I think the distance between the message and the first keyword being potentially large is not ideal as you said. I think it's the best trade-off for me atm.

**Comment by GearsDatapacks** [comment]
I agree. I think there is going to be a similar problem whatever design we choose. If it's message first it could be something like:
```gleam
let assert
  as "This will never fail because of some pretty complex explanation which takes lots of space"
  Ok(value) = do_something()
```
We won't be able to find a syntax which never has this problem, so I think this design would be best.
It also is similar to the future plan for `echo`: `echo some_value as "Some description"`

**Comment by jrstrunk** [comment]
Also looking at some non-isolated edge cases where everything fits on one line and there are surrounding lines of code, I think I still prefer the trailing message because the message is the least important part of the line. Having the important logic close to the start of the line improves line scanability to me:

```gleam
let format_regex = "[A-Z]{0,2}"
let assert Ok(re) = regex.from_string(format_regex) as "regex must compile"

let assert True = regex.check(re, input) as "input must match regex" 

do_something_with_valid_input(input)
```
versus 
```gleam
let format_regex = "[A-Z]{0,2}"
let assert as "regex must compile" Ok(re) = regex.from_string(format_regex)

let assert as "input must match regex" True = regex.check(re, input)

do_something_with_valid_input(input)
```

**Comment by sobolevn** [comment]
@jrstrunk when designing the original PR I had the same idea. For example, right now `let assert Ok(re) = regex.from_string(format_regex) as "regex must compile"` reads as:

- `let assert Ok(re)`
- `regex.from_string(format_regex) as "regex must compile"`

So, I would not expect that `as` part is connected to `let assert`

**Comment by jrstrunk** [comment]
@sobolevn I understand since the `assert` and the `as` are pretty far away on the line that it is not immediately obvious to a beginner what the message is applying to ... but also what other thing could `as` be referring to on that line? Even if someone has never seen Gleam code before, is it common anywhere else to apply a string literal to a function call? It seems like from just applying deductive reasoning for a moment, most could come to the conclusion that the `as` is tied to the assertion at the beginning.

Though my biggest concern with the trailing message is that it is not as composable with future, unknown at this point features. For example it might make the `echo` keyword a little more tricky to work with:

This quick refactor to see the compile result would then interpret `as "regex must compile"` as being part of the `echo` keyword,
```gleam
let assert Ok(re) = regex.from_string(format_regex) echo as "regex must compile"
```
So users would have to catch themselves and write something like this instead:
```gleam
let assert Ok(re) = regex.from_string(format_regex) echo as "compile result" as "regex must compile"
```
Then maybe some other feature comes along that we can't image right now but will want later:
```gleam
let assert Ok(re) = cool_new_keyword really_cool_feature regex.from_string(format_regex)  echo as "compile result" as "cool new feature msg that we must add" as "regex must compile"
```

Overall I still lean towards the trailing message because it looks the nicest in non-edge cases and we can overburden ourselves optimizing for every little edge case out there, but there is reason for caution here.

**Comment by lpil** [comment]
We don't need to concern ourself with interaction with `echo` as it's purely for debugging and will only briefly be in the code.
