### ISSUE TITLE
LSP reports 'no implementation for Erlang' for javascript-only function

### ISSUE THREAD

**Issue by ieeemma** [gleam-lang/gleam#3218]
Apologies if I've misunderstood how to use the LSP, but I've had an issue developing a gleam program targeting javascript.
For example,
```gleam
pub fn main() {
  foo()
}

@external(javascript, "./foo.mjs", "foo")
fn foo() -> Nil
```
The LSP reports `This function doesn't have an implementation for the Erlang target` on `foo()`. This is correct, but is unhelpful as I'm not developing for Erlang! This error also stops other errors from being reported, rendering the LSP useless.

I've worked around this by adding a dummy `@external(erlang, "", "")` which makes the error go away, but this doesn't work for existing libraries like `gleam_javascript` - I've had to reimplement the ref type just to avoid this LSP issue.

**Comment by Acepie** [comment]
In your gleam.toml have you set the target to javascript? By default if not set the target is assumed to be erlang hence why the lsp would give you warnings about a missing implementation. Make sure your gleam.toml file has the following line in it

```
target = "javascript"
```

**Comment by lpil** [comment]
Thanks @Acepie !
