### ISSUE TITLE
Add qualifiers for type variables in generated Erlang typespecs

### ISSUE THREAD

**Issue by dvic** [gleam-lang/gleam#3221]
Starting from OTP 26 erlang/otp#6915, warnings are emitted for unbound type variables, for example:

```erlang
 -spec try_call_timeout_test() -> {ok, GGA}
```

We need to replace this unbound type variable with `term()` so that no warning is emitted.

*originally reported in gleam-lang/erlang#46*

**Comment by dvic** [comment]
@lpil isn't it better to use a bound instead of term directly? Let's say this was the function (from the OTP PR mentioned above):

```erlang
-spec foo(atom()) -> {ok, X} | {error, X}
```

Then instead of
```erlang
-spec foo(atom()) -> {ok, term()} | {error, term()}
```

I think it's better to have
```erlang
-spec foo(atom()) -> {ok, X} | {error, X} when X :: term()
```

In this way, the typespec correctly signals that the type should be the same in the two branches?

**Comment by lpil** [comment]
@dvic The example you give there doesn't need to be changed, it's only when a parameter is used once that it is invalid.

**Comment by dvic** [comment]
> @dvic The example you give there doesn't need to be changed, it's only when a parameter is used once that it is invalid.
> 
> Thank you @dvic !

Are you sure? I just double checked this locally with the example from erlang/otp#6915:

```erlang
-module(foo).

-export([foo/1]).

-spec foo(atom()) -> {ok, X} | {error, X}.
foo(X) ->
    {ok, X}.
```

```bash
❯ erlc foo.erl
foo.erl:5:27: Warning: type variable 'X' is only used once (is unbound)
%    5| -spec foo(atom()) -> {ok, X} | {error, X}.
%     |                           ^
```

While

```erlang
-module(foo).

-export([foo/1]).

-spec foo(atom()) -> {ok, X} | {error, X} when X :: term().
foo(X) ->
    {ok, X}.
```

does not emit an warning (this is on OTP 26.2.5).

**Comment by lpil** [comment]
Huh. OK I don't understand what's happening here. It says "once" but it's clearly used twice. Is this a bug in erlc?

**Comment by dvic** [comment]
> Huh. OK I don't understand what's happening here. It says "once" but it's clearly used twice. Is this a bug in erlc?

Yeah the message is a bit confusing, I think it's more about the *(is unbound)* part. Apparently for the compiler `X` is being used twice in the following example, once  in the return type and once in the type guard.

```erlang
-spec foo(atom()) -> {ok, X} | {error, X} when X :: term().
```

**Comment by lpil** [comment]
I've opened an issue with Erlang/OTP to find out if this warning is emitted incorrectly, or if the text is misleading.

**Comment by dvic** [comment]
@lpil I may have confused you with the following comment
![image](https://github.com/gleam-lang/gleam/assets/1214337/21cbc6a1-7c1c-42e0-a0b7-bde835058ac0)

OTP 26.2.5 **also** emits a warning without the type guard, it's because of the added type guard that no warning is emitted.

**Comment by lpil** [comment]
Thank you.

This is all very confusing to me. I guess we add seemingly redundant qualifiers to everything!

**Comment by dvic** [comment]
> Thank you.
> 
> This is all very confusing to me.

Yeah it is, I guess we're all spoiled by the errors in Gleam ;)

**Comment by lpil** [comment]
Looks like I'm totally wrong about how they work. https://github.com/erlang/otp/issues/8533

**Comment by dvic** [comment]
I saw the conversation :) So for now we only add `X :: term()` when a type parameter is not used in the input? That should cover it, right?

**Comment by lpil** [comment]
I think so? It's still incorrect though unfortunately.

**Comment by dvic** [comment]
> I think so? It's still incorrect though unfortunately.

Yeah, it's the best we can do for now.

I was busy with playing around with https://github.com/gleam-lang/erlang/pull/46 but I can pick this one up, wanted to get familiar with the Rust codebase anyways :)

**Comment by dvic** [comment]
@lpil any idea how I can trigger the issue in a isolated test? I tried this but `any()` is generated:

<img width="759" alt="image" src="https://github.com/gleam-lang/gleam/assets/1214337/042685d5-33d7-46c8-8e26-80bc77bd7d30">

It makes me think: isn't that what should have been generated in the example in this issue?

**Comment by dvic** [comment]
I tried also
<img width="646" alt="image" src="https://github.com/gleam-lang/gleam/assets/1214337/a437077d-c962-4ee2-b9c5-c6038ea9830a">

but I get

```
should successfully infer root Erlang: [CouldNotUnify { location: SrcSpan { start: 161, end: 233 }, situation: Some(ReturnAnnotationMismatch), expected: Named { publicity: Public, package: "", module: "gleam", name: "Result", args: [Var { type_: RefCell { value: Link { type_: Var { type_: RefCell { value: Generic { id: 10 } } } } } }, Var { type_: RefCell { value: Link { type_: Var { type_: RefCell { value: Generic { id: 11 } } } } } }] }, given: Named { publicity: Public, package: "", module: "gleam", name: "Result", args: [Var { type_: RefCell { value: Link { type_: Var { type_: RefCell { value: Generic { id: 10 } } } } } }, Named { publicity: Private, package: "thepackage", module: "my/mod", name: "CallError", args: [Var { type_: RefCell { value: Link { type_: Var { type_: RefCell { value: Generic { id: 10 } } } } } }] }] }, rigid_type_names: {11: "b", 10: "a"} }, UnknownType { location: SrcSpan { start: 553, end: 560 }, name: "Dynamic", hint: AlternativeTypes(["Result", "BitArray", "String", "CallError", "Bool", "Float", "Int", "List", "Nil", "UtfCodepoint", "Subject"]) }]
```

**Comment by dvic** [comment]
PR is submitted!
