### ISSUE TITLE
Unable use `gleam new` command

### ISSUE THREAD

**Issue by bfg-coding** [gleam-lang/gleam#3243]
Following the asdf instructions on installing and writing Gleam on my Pop-OS system I'm getting a weird error when I try to start a new project 

```
 ╰─λ gleam new gleam-world
No version is set for command gleam
Consider adding one of the following versions in your config file at
gleam 1.2.1
```

I don't see anywhere in the documentation about needing a config file for creating new projects or where that file would live.  I'm sure there is something silly on my end but wanted to point this out

**Comment by Acepie** [comment]
I believe this error is coming from asdf and not an issue with gleam itself. https://stackoverflow.com/questions/73588577/asdf-no-version-is-set-for-command-elixir you need to tell asdf what version of the installed command to use globally

**Comment by bfg-coding** [comment]
That was it!  Sorry don't use asdf for anything so didn't know about this nuance with it
