### ISSUE TITLE
LSP: autocompletion types in import statement should account for already-typed `type` keyword

### ISSUE THREAD

**Issue by quentin-fox** [gleam-lang/gleam#3244]
On Gleam 1.2:

When autocompleting an unqualified type import, the LSP always inserts the `type` prefix before.

e.g. when triggering autocomplete for `Dict` from here:

```gleam
import gleam/dict.{type D }
                         ^
```

We end up with

```gleam
import gleam/dict.{type type Dict}
```

Another related bug:

If `type` is already typed in the import statement, it should ideally only allow autocompletion of available types, instead of all exported symbols.

e.g.

```gleam
import gleam/dict.{type }
                       ^
```

The `get` function is one of the suggestions, when the LSP should know (? unless that's not desired behaviour) that I'm only looking to import types.

**Comment by lpil** [comment]
Closing as duplicate
