### ISSUE TITLE
Type constructors are not consistent during equality

### ISSUE THREAD

**Issue by ghivert** [gleam-lang/gleam#3248]
Hi!

Currently, constructors in types are not equal to themself when they expect arguments, even if they can be used as a function. It's really disturbing, because you can't use them to detect equality (for instance, if you want to detect if the function passed as param to a function is the same as another function).

Minimal reproducible example:

```gleam
import gleam/io

pub type Test {
  Test1
  Test2(String)
}

fn test_example(content) {
  todo
}

pub fn main() {
  io.debug(Test1 == Test1)
  io.debug(Test2 == Test2)
  io.debug(test_example == test_example)
}
```

This output (for both Erlang & JS)

```
True
False
True
```

From what I understand, the constructors are not real functions in the compiled code, but are generated with lambda functions. This seems counter-intuitive though, mainly because in Gleam, you can use them as functions, and seeing the conceptual difference is hard.

This could be simply mitigated simply by using static functions instead of lambda functions each time the constructor is called.
Is this behaviour on purpose? Is it a bug?

---

A little bit more context on why that problem surfaced.
I'm trying to implement some lazy computations in Gleam (specially in Lustre). Simply said, when you render a view function in lustre, you could want to skip the render and instead keep the current DOM nodes, because nothing changed between before and now. So to make sure the computation can be skipped, I need to compare dependencies of the view functions to check if the computation can effectively be skipped. Dependencies correspond to parameters to the lazy function, the lazy function itself, and the potential mappers of the resulting VDOM elements.
It works perfectly, because Gleam functions are compiled as top-level functions, meaning equality is kept between re-renders, as well as parameters. It means we can just iterate through the dependencies, and test equality.

When using constructors though, they're not consistent between re-renders. So when you're using a constructor with lazy elements, this breaks the laziness. 

A code example that works without problems:

```gleam
fn hard_complex_computation(param) {
  ...
}

fn view(model) {
  html.div([], [
    element.lazy1(model, hard_complex_computation),
  ])
}
```

When executing this code, while the model does not change, the laziness will skip the hard computation task. However, when doing:

```gleam
pub type Msg {
  InsideMsgWrapper(InsideMsg)
}

pub type InsideMsg { 
  ... 
}

fn hard_complex_computation(param) -> Element(InsideMsg) {
  ...
}

fn view(model) -> Element(Msg) {
  html.div([], [
    element.lazy1(model, hard_complex_computation)
    |> element.map(InsideMsgWrapper),
  ])
}
```

This adds `InsideMsgWrapper` as a dependency for the lazy element (unfortunately we can't do differently at the moment, because if the mapper change, we need to reflect this on the current DOM nodes). And because it's generated as an anonymous function, it changes at every re-render, and it breaks laziness. This is where I think it's counter-intuitive, because writing this:

```gleam
pub type Msg {
  InsideMsgWrapper(InsideMsg)
}

pub type InsideMsg { 
  ... 
}

fn inside_msg_wrapper(m) {
  InsideMsgWrapper(m)
}

fn hard_complex_computation(param) -> Element(InsideMsg) {
  ...
}

fn view(model) -> Element(Msg) {
  html.div([], [
    element.lazy1(model, hard_complex_computation)
    |> element.map(inside_msg_wrapper),
  ])
}
```

Solve the problem, because now, the mapper does not change over time!

I hope this helps to better understand the context and the origin of this issue! 😄

**Comment by lpil** [comment]
Hello! This is not a bug. Function equality is reference equality and the specific behaviour will depend on the optimisations performed by the compilers and runtime being used, and may change at any time when their versions change.

**Comment by ghivert** [comment]
Oh, you mean it's by default undefined behaviour, because it could change according to the runtime?
I don't really see a use case where minifiers or anything else could change the generated code, but I trust you. 😁

Thanks for your response!
