### ISSUE TITLE
LSP: Add Document Symbol support

### ISSUE THREAD

**Issue by leonqadirie** [gleam-lang/gleam#3252]
Suggestion: Add LSP support for [Document Symbols](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol).

From the LSP spec:
> They represents programming constructs like variables, classes, interfaces etc. that appear in a document. Document symbols can be hierarchical and they have two ranges: one that encloses its definition and one that points to its most interesting range, e.g. the range of an identifier.

They provide a (subjectively) great way to quickly conceptualise/grasp and navigate code in editors that support them. An example of a buffer's Document Symbols in Rust is attached.

![LSP Document Symbols - Example](https://github.com/gleam-lang/gleam/assets/39130739/78fa40b5-7819-40fa-96ed-2b07c3acb194)

**Comment by lpil** [comment]
Oooh very nice! Sounds like it should be straightforward to add too.

**Comment by PgBiel** [comment]
Working on it!

![image](https://github.com/gleam-lang/gleam/assets/9021226/4bc24819-fcaf-4ee4-ada7-7807b4cdf25c)

By the way, it seems that Zed already supports this feature for Gleam out of the box, but this will still matter for VSCode and (potentially) other editors.

**Comment by leonqadirie** [comment]
Very nice, thank you!

Zed added support [in this PR](https://github.com/zed-industries/zed/pull/6733), without diving into the code I suspect they use Gleam's tree-sitter to implement the symbol view. It definitely matters for other editors!
