### ISSUE TITLE
LSP code action: import module 

### ISSUE THREAD

**Issue by gusinacio** [gleam-lang/gleam#3258]
Right now, if I use a module that exists but was not imported yet I receive an error message:
```
Unknown module

No module has been found with name `<name>`.
```

It would be great if we could import directly using a code action

**Comment by lpil** [comment]
I think that's the error for when you have imported a module but there is no module with that name. Would it be a code action that edits the import to the one that exists with the closest name?

**Comment by gusinacio** [comment]
See the following example:
```
pub fn main() {
  io.print("Hello world")
}
```
I haven't imported `gleam/io` yet and that's why I receive the "Unknown module" error.

I'd like to go with my cursor over the `io` and have a code action to import it from `gleam/io` or other module suggestions.

**Comment by johtso** [comment]
Should this be quite straightforward now that we have this? https://github.com/gleam-lang/gleam/pull/3219

**Comment by Acepie** [comment]
> 
> I'd like to go with my cursor over the `io` and have a code action to import it from `gleam/io` or other module suggestions.

FWIW the behavior you are describing here is almost exactly what the new completion behavior is with #3219 though it still has that issue with duplicating the module name. That being said, once #3240 is merged I think this can be closed as completed

**Comment by lpil** [comment]
I think it could still be useful to have a code action for when you did not use the autocompletion, though not as high a priority.

**Comment by johtso** [comment]
I agree, lots of situations where you copy and paste code and need to add imports, rather than typing the code and tab completing
