### ISSUE TITLE
LSP: When auto adding import, if it's the first import, a blank line should follow it

### ISSUE THREAD

**Issue by johtso** [gleam-lang/gleam#3271]
With the new tab completion auto adding of imports, if it's the first import in the file, there's no blank line between it and the first line of code.

**Comment by lpil** [comment]
Good idea. Thanks!

**Comment by codemonkey76** [comment]
I've had a go at this, see #3277

**Comment by Acepie** [comment]
This can be closed now right?

**Comment by lpil** [comment]
Yes, thank you
