### ISSUE TITLE
Horizontal scrolling in code blocks in built docs for lines 79-80 characters long

### ISSUE THREAD

**Issue by richard-viney** [gleam-lang/gleam#3276]
In documentation built with `gleam docs build`, code blocks with lines of length 79 or greater cause horizontal scrolling of the block, which is a bit unsightly. Gleam wraps code at 80 characters, so it would be good if 80 characters could be used in a code block in the docs without triggering a horizontal scrollbar. A scrollbar would still appear for lines longer than Gleam's 80 character convention.

This can be seen here: https://hexdocs.pm/ieee_float/0.1.0/index.html

Browsers affected are Safari (v17.5) and Chrome (v125), but Firefox (v126) doesn't seem to be affected.

An easy workaround is to adjust code blocks in documentation to only be max 78 characters long.

Gleam version: 1.2.1

**Comment by lpil** [comment]
Let's make the page slightly wider.

**Comment by richard-viney** [comment]
Sounds good, I'll submit a PR for this in the next day or so.
