### ISSUE TITLE
`gleam remove` always reports a removal, even if the package did not exist in `gleam.toml`

### ISSUE THREAD

**Issue by vxern** [gleam-lang/gleam#3279]
To reproduce, run `gleam remove <package>` using any arbitrary input, such as `gleam remove doesntexist`:
```
vxern@Dorian tatoeba % gleam remove doesntexist
    Removed doesntexist
```

Gleam version: `v1.2.1`

**Comment by lpil** [comment]
Thanks

**Comment by simonhammes** [comment]
I can work on this. Should `gleam remove` error in such a case or just print a warning (to stderr, I assume)?

**Comment by lpil** [comment]
Return an error please
