### ISSUE TITLE
Say "I was not expecting this keyword" in error when there is an unexpected keyword

### ISSUE THREAD

**Issue by mscharley** [gleam-lang/gleam#3286]
I recently ran into the following ambiguous situation:

![image](https://github.com/gleam-lang/gleam/assets/336509/b31c5f16-55dd-4b8d-81fa-127976ba5e7a)

Here, `as` is being interpreted as a placeholder pattern by the syntax highlighter but the compiler is interpreting it as the `as` keyword and throwing it's hands up because that's not a valid place for that keyword. It would be great if the compiler message could include what it thought was there, not just what it expected to see.

**Comment by mscharley** [comment]
Perhaps ambiguity is the wrong word, but as a human this could be either a variable name or the `as` keyword but the compiler (correctly) interprets it as the `as` keyword.

It would be nice if it said something like `I was not expecting an as keyword.` instead of `I was not expecting this.`. It isn't always clear from context what 'this' actually means.

**Comment by mscharley** [comment]
More specifically, it says "Expected one of: a pattern" but to me, that's exactly what I wrote there - a placeholder pattern.

**Comment by lpil** [comment]
Ah! Good suggestion. Thank you
