### ISSUE TITLE
Calling of functions with names that clash with keywords

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#329]
This currently generates invalid Erlang

```rust
fn receive(x) {
  x
}

fn go() {
  receive(1)
}
```

**Comment by NobbZ** [comment]
IIRC compiling the example into the following should work. For simplicity in the code generator just quoting all function and module names should be sufficient.

```erl
'receive'(X) -> X.

'go'() -> 'receive'(1).
```

**Comment by lpil** [comment]
That's what I thought but I got an error. Perhaps I was tired and made a mistake
