### ISSUE TITLE
LSP: Crash on type redefine

### ISSUE THREAD

**Issue by naomieow** [gleam-lang/gleam#3303]
Redefining an imported type crashes the LSP:
```gleam
import gleam/dynamic.{type Decoder}

pub opaque type Decoder
```

Gleam version: 1.2.1
OS: Fedora 40
Editor: VSCode

```
error: Fatal compiler bug!

This is a bug in the Gleam compiler, sorry!

Please report this crash to https://github.com/gleam-lang/gleam/issues/new
and include this error message with your report.

Panic: compiler-core/src/analyse.rs:991
	name uniqueness checked above: DuplicateTypeName { location: SrcSpan { start: 37, end: 60 }, previous_location: SrcSpan { start: 22, end: 34 }, name: "Decoder" }
Gleam version: 1.2.1
Operating system: linux
```

**Comment by naomieow** [comment]
Possible dupe of #3272

**Comment by Zhomart** [comment]
Is this allowed? I see gleam doesn't even compile this.

<img width="1205" alt="image" src="https://github.com/gleam-lang/gleam/assets/830536/c228cc0b-d5eb-4504-ba88-6f3d155804d3">

**Comment by naomieow** [comment]
It's not allowed, but shouldn't crash the compiler or LSP as it does right now, instead it should produce a compiler error.

**Comment by lpil** [comment]
A bug introduced by the fault tolerant compilation. Thank you
