### ISSUE TITLE
"Else" type variant causes erlang troubles

### ISSUE THREAD

**Issue by jtenner** [gleam-lang/gleam#3304]
![Screenshot_2024-06-20-22-34-11-50_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/gleam-lang/gleam/assets/3761339/37aa6ae8-72ca-454c-b037-a018d3cd815c)

It looks like I hit an edge case. 

```rs
pub type Example {
  Else
} 
```

I don't know if this will minimally repoduce the problem, but erlang doesn't seem to like using the "else" token.

**Comment by lpil** [comment]
Ah! This is new in OTP27. Thank you
