### ISSUE TITLE
wasm version of compiler not rejecting unsupported code for JS target

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#3310]
I have extracted this reproduction from my project but not yet managed to reduce the function much.
The following can be copied in the tour code playground an it breaks as follows.

Type checking passes, but the underline function is no in scope at runtime.
```gleam
import gleam/io
import gleam/bit_array
import gleam/list

fn underline(code, errors) {
  let code = bit_array.from_string(code)
  let #(_, _, acc) =
    list.fold(errors, #(code, 0, []), fn(state, error) {
      let #(remaining, offset, acc) = state
      let #(#(start, end), reason) = error
      let pre = start - offset
      let emp = end - start
      let offset = end
      case code {
        <<pre:bytes-size(pre), emp:bytes-size(emp), remaining:bytes>> -> {
          let assert Ok(pre) = bit_array.to_string(pre)
          let acc = case pre {
            "" -> acc
            content -> [content,..acc]
          }
          let assert Ok(emp) = bit_array.to_string(emp)
          let acc = case emp {
            "" -> acc
            content -> [content,..acc]
          }
          #(remaining, offset, acc)
        }
        _ -> panic
      }
    })
  list.reverse(acc)
}

pub fn main() {
    underline  
}
```

You can check that this is weird by replacing main with.
```gleam
pub fn main() {
  fn() { underline }  
}
```

**Comment by lpil** [comment]
Could you give more detail on this please? This does not compile on JS, but I get a compile bug on Erlang, but neither is the issue you've described?

**Comment by CrowdHailer** [comment]
https://vimeo.com/965940552/86b69701a5?share=copy

**Comment by lpil** [comment]
Thank you 💜

**Comment by Acepie** [comment]
FYI looks like this might be something specific to running the example in the tour. If you try to run this code in node/on local then you properly get a compile error

![Screenshot 2024-07-12 221607](https://github.com/user-attachments/assets/5da99bb8-caa4-4f5f-afa4-05f620192fd1)

**Comment by lpil** [comment]
Oh spooky! What's going on there
