### ISSUE TITLE
False negative diagnostic for unused (aliased) imports

### ISSUE THREAD

**Issue by ascandone** [gleam-lang/gleam#3313]
### Minimal reproduction:

```gleam
import my_type as renamed_module

pub fn example_external_imported(x) {
  case x {
    renamed_module.MyConstructor -> Nil
  }
}
```
### Expected output
No warnings (the alias `renamed_module` is used to qualify the `MyConstructor` constructor in the pattern matching)

### Actual output
The following warning (on both LSP and `gleam check`)
```
warning: Unused imported module alias
  ┌─ /Users/../src/repro.gleam:1:16
  │
1 │ import my_type as renamed_module
  │                ^^^^^^^^^^^^^^^^^ This alias is never used

Hint: You can safely remove it.

    import my_type as _
```

### Other info
reproduced on gleam 1.2.1 on MacOs Sonoma

**Comment by lpil** [comment]
How frustrating! Thank you.

This entire system is due to be rewritten from scratch soon, but let's still fix this bug in the current one.

**Comment by michaeljones** [comment]
I've created a PR for this: https://github.com/gleam-lang/gleam/pull/3328 

I hope that is ok. I don't know if the 'eyes' emoji claims ownership of the work. Sorry if it does. I've come across this in my own project and it piqued my interest enough to want to resolve it.

**Comment by ascandone** [comment]
Not at all! Sorry for the miscommunication, I wasn't planning on fixing the issue 🙂
