### ISSUE TITLE
Consider adding a flag to the formatter to force an output produced by a specific version

### ISSUE THREAD

**Issue by patrik-kuehl** [gleam-lang/gleam#3319]
I stumbled upon failed pipelines in a repository I'm contributing to due to failed formatting checks ([this](https://github.com/maxdeviant/startest/pull/15) is one of the PRs).

I checked Gleam's changelog and noticed that changes to the formatter have been made, which cause formatting checks to fail, even in minor version bumps.

I usually expect contributors to have a minimum Gleam version installed as stated in my own contribution guidelines and expect nothing to break when they are on a newer minor version within the same major version (after reaching the first major version) when the project follows SemVer.

The problem here is, that I cannot seem to find a way to tell Gleam v1.2 to format the code like in v1.1, at least `gleam format --help` showed me no flag to make this possible.

Would it be feasible to add such a flag (e.g., `gleam format --style=[1.0,1.1]`)?

I might be the only one concerned about this issue, but imo it would make contributing to projects a lot easier, and the code style of projects won't be potentially affected in a next minor version bump again.

**Comment by lpil** [comment]
This would mean making full copies of and then forever maintaining the front half of the compiler and all formatter related parts of the codebase, creating huge amounts of extra work. We would need vast amounts of funding for this to be viable, unfortunately.

**Comment by patrik-kuehl** [comment]
> We would need vast amounts of funding for this to be viable, unfortunately.

I already supposed funding would play a major role here due to the maintenance costs (I'm coming from an enterprise background where such guarantees are just common due to this, but big corpos have piles of money, indeed).

Thanks anyway for the quick response, I'll just update my contribution guidelines to require contributors to use the latest minor version.

**Comment by lpil** [comment]
Thank you @patrik-kuehl  💜💜💜 

I hope we can offer this in future
