### ISSUE TITLE
Generate header files containing Erlang records for structs

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#332]

**Comment by lpil** [comment]
Hi @AdamBrodzinski, Erlang records are being generated on the master branch now if you'd like to give it a try :)

**Comment by AdamBrodzinski** [comment]
Where can I find the header files? I'm migrating that test app and so far it's a lot easier to work with 😄  I also just found this library that will generate the elixir Records for you as well as convert records to structs and back based on the hrl file. However, I can't seem to find that. Is this part implemented or just the record data structures?

btw here's the library. I haven't tried it yet but it looks perfect (except it doesn't do nested records 😦)

**Comment by lpil** [comment]
They should be generated in the gen src directory but now I think about it that might not be right for enabling them to be imported into an Erlang or Elixir project, I will have to do some testing.

**Comment by AdamBrodzinski** [comment]
Whoops, I forgot to post the link above 🙈 
https://github.com/haljin/rec_struct

Haven't tried it yet though

**Comment by lpil** [comment]
Could be worth checking out :)
