### ISSUE TITLE
variable unbound errors when re-using variable names in nested case statements

### ISSUE THREAD

**Issue by michallepicki** [gleam-lang/gleam#333]
Hey! I was solving the 2nd part of day 2 of AoC and my code errors out with:

```
gen/src/program_alarm.erl:131: variable 'Noun1' is unbound
gen/src/program_alarm.erl:131: variable 'Verb1' is unbound
escript: There were compilation errors.
```
when trying to execute Erlang code (the Gleam code does compile just fine)

The code to reproduce this is [in this commit](https://github.com/michallepicki/adventofcode/commit/af0826b1c876b439de6e482de4c66ca84791d730) and to run it you can:
```
cd 2019/gleam
./2_program_alarm.sh
```

I'll just use a different name but I think it's worth looking at.

edit: this is a WIP solution so don't worry about it not being correct ;)

**Comment by michallepicki** [comment]
To work-around this I had to re-name the pattern variables in lines 86 and 90

**Comment by lpil** [comment]
Thank you for the report!

**Comment by michallepicki** [comment]
Still cannot reuse all names. Using gleam from master, I tried to update my day 3 AoC so that it re-uses all variable names, got an error. [Here](https://github.com/michallepicki/adventofcode/commit/24b02f8486dbf0549714ee93ac72d04f7438c002#diff-18f5f18e81f1254d838f695b5a8acd92R73)'s the commit, running `./3_crossed_wires.sh` gives `escript: exception error: no match of right hand side value 1` because erlang tries to match to an existing variable (X).

This is the gleam snippet:
```
fn walk_b(map, x, y, direction, distance, current_wire, steps, best_crossing) {
  case distance {
    0 ->
      struct(map, x, y, steps, best_crossing)
    distance -> {
      let current_steps = steps + 1
      let x = case direction {
        Right -> x + 1
        Left -> x - 1
        _ -> x
      }
```
and it produces this erlang code:
```
walk_b(Map, X, Y, Direction, Distance, CurrentWire, Steps, BestCrossing) ->
    case Distance of
        0 ->
            {Map, X, Y, Steps, BestCrossing};

        Distance1 ->
            CurrentSteps = Steps + 1,
            X = case Direction of
                right ->
                    X + 1;

                left ->
                    X - 1;

                _ ->
                    X
            end,
```

Probably names are not getting reserved properly for function arguments

**Comment by lpil** [comment]
Thank you for the report

**Comment by michallepicki** [comment]
confirming fixed :1st_place_medal:
