### ISSUE TITLE
`gleam new` pulls old version of standard library

### ISSUE THREAD

**Issue by sporto** [gleam-lang/gleam#335]
I tried following the Getting started from https://gleam.run/getting-started/creating-a-project.html

Got gleam from the releases page

```
gleam --version
gleam 0.5.0-dev
```

Then did `gleam new ...`

Then `rebar3 eunit`. I get:

```
error: Syntax error
- <.../test_gleam/_build/default/lib/gleam_stdlib/src/gleam/int.gleam>:11:3
   |
11 |   | True -> order.Eq
   |   ^ Unexpected token
```

So this is using the old syntax. 
Thanks

**Comment by AdamBrodzinski** [comment]
as a work around you can modify your rebar.config to pull in the latest git commit:
```
{erl_opts, [debug_info]}.
{src_dirs, ["src", "gen/src"]}.

{profiles, [
    {test, [
        {pre_hooks, [{compile, "gleam build ."}]},
        {src_dirs, ["src", "test", "gen/src", "gen/test"]}
    ]},

    {dev, [
        {pre_hooks, [{compile, "gleam build ."}]}
    ]}
]}.

{deps, [
    {gleam_stdlib, {git, "git://github.com/gleam-lang/stdlib.git", {ref, "eef64e6cc28ef4e001818381c317b42095653ff9"}}}
]}.

```

**Comment by lpil** [comment]
Yup, the stable version of the stdlib supports the stable version of the compiler so if you're using 5.0-* you'll need to use a development version of the stdlib too.
