### ISSUE TITLE
De-structure function parameters into record

### ISSUE THREAD

**Issue by gusinacio** [gleam-lang/gleam#3355]
Today it's possible to get the inner value of a record by using the following:

```gleam
type MyNewType {
  MyNewType(inner: String)
}

fn get_inner(my_new_type: MyNewType) {
  let MyNewType(inner) = my_new_type
  inner
}
```

But it would be great if I could de-structure directly on the function parameter like so:

```gleam
type MyNewType {
  MyNewType(inner: String)
}

fn get_inner(MyNewType(inner): MyNewType) {
  inner
}
```

**Comment by lpil** [comment]
Hello! Thank you, but isn't planned as it doesn't enable anything new and is more verbose than using accessors.

We use GitHub issues for items that can be worked on so a discussion is likely best for language design proposals.
