### ISSUE TITLE
Passing a function with just a function name to a higher order function inside pipeline compiles to invalid erlang code

### ISSUE THREAD

**Issue by michallepicki** [gleam-lang/gleam#336]
Hi! I was working on day 3 of AoC and my Gleam code compiles successfuly but erlang compilation errors out with:
```
gen/src/crossed_wires.erl:66: function crossed_wires/1 undefined
```
where the Gleam code is:
```
  let first_input =
    first_line
    |> e_string_trim
    |> e_string_split(_, ",", All)
    |> e_lists_map(parse_single_input, _)
```
and it produces this Erlang code:
```
    FirstInput = e_lists_map(
        fun crossed_wires/1,
        e_string_split(e_string_trim(FirstLine), <<",">>, all)
    ),
```
In this case `crossed_wires` is the module name.

The code to reproduce is in [this commit](https://github.com/michallepicki/adventofcode/commit/a7e4f253ad85e8649cbb502b0688d36cbc7b006c) and to run it you can
```
cd 2019/gleam
./3_crossed_wires.sh
```

Adding back the `(_)` capture solves the problem.

**Comment by lpil** [comment]
This has been fixed on master I believe, try using that :)

**Comment by michallepicki** [comment]
With gleam compiled from master, since the first file line (which is in gleam output the module declaration) is not being used by escript, so my code is effectively not in a module, I'm getting
```
escript: exception error: undefined function crossed_wires:parse_single_input/1
  in function  lists:map/2 (lists.erl, line 1239)
```

because the function is referenced with module name even though it's in the same file.

I guess escript compatibility wasn't guaranteed and I'll have to give up on my hack and start using `rebar3` but I thought you might want to know.

**Comment by lpil** [comment]
Hi @michallepicki. Could you open a new issue with a minimal example of the problem input and the code it generates please? Thank you

**Comment by michallepicki** [comment]
@lpil Just looked into this, and it turns out Erlang doesn't support referencing local functions just by name without a module - so for an escript, using an anonymous function wrapper is the way to go. There's some way modules can be loaded into escripts but I couldn't get it to work.

So all seems good!

**Comment by lpil** [comment]
I didn't know that! Thanks for the information :)
