### ISSUE TITLE
Field name "type" is not useable for Records

### ISSUE THREAD

**Issue by SundayPowerEndre** [gleam-lang/gleam#3369]
When i attempt to make the following type on Gleam version 1.2.1

```gleam
pub type Message {
  Message(type: String, id: Int, src: String, dest: String, body: MessageBody)
}
```
It gives me the error message
```text
Diagnostics:
1. Syntax error
   
   I was not expecting this.
   
   Expected one of: 
   ")"
   a constructor argument name
```
The issue is only present if i have a field named "type".

I am using the type for encoding and decoding jsons, which i do not control the shape of, and i need the value of the "type" field on the jsons. I am assuming there are several workarounds, but it would be expected and convenient in my mind if i could use the keyword type inside of records.

**Comment by lpil** [comment]
That's correct, type is a keyword in Gleam, just like how class is a keyword in Java

**Comment by SundayPowerEndre** [comment]
Thanks, that was a good answer. When thinking it over I 100% agree 👍🏽
