### ISSUE TITLE
Crash when adding cyclic import

### ISSUE THREAD

**Issue by Nicd** [gleam-lang/gleam#3376]
1. Get this repo and this specific commit: https://git.ahlcode.fi/nicd/aurinko/src/commit/6ac6e4bd7f5b7391b9cc23c78e01f94336e31ccb
2. Open file `src/aurinko/web/components/main.gleam`.
3. Add `import aurinko` at the top of the file.

```
error: Fatal compiler bug!

[...]

Panic: /Users/runner/work/gleam/gleam/compiler-core/src/build/package_loader.rs:298
	import must exist for there to be a cycle
Gleam version: 1.3.0
Operating system: macos
```

I tried running with `GLEAM_LOG=trace open . -a Visual\ Studio\ Code.app` but it didn't seem to alter the output, even though the env var value was shown in the VSCode builtin terminal.

**Comment by lpil** [comment]
Thank you
