### ISSUE TITLE
LSP: auto-imports feature doesn't handle `_` well

### ISSUE THREAD

**Issue by LoipesMas** [gleam-lang/gleam#3380]
The new auto-imports feature doesn't work with functions/constants that have `_` in their name.
For example, when I try to get `wisp.html_response`, the moment I get to `html_`, the `wisp.html_response` entry no longer shows up. What's left is `html.parse_multipart_body` and `html.parse_multipart_headers`.
![image](https://github.com/gleam-lang/gleam/assets/46327403/a0dfa38c-6835-48a8-a02c-d24e7cb66c86)

If I instead enter `htmlres` (skipping the `_`), then `wisp.html_response` shows up as expected.
![image](https://github.com/gleam-lang/gleam/assets/46327403/e199954b-ef25-4e94-ba1f-d5639538a5c2)

Normal completion (on `wisp.html_r`) handles it just fine.
![image](https://github.com/gleam-lang/gleam/assets/46327403/a208addf-e500-489c-b67a-17d9b2e42038)

Gleam version `1.3.0`
completion setup: neovim 0.10.0 + nvim-cmp

**Comment by lpil** [comment]
Thank you

**Comment by Acepie** [comment]
FWIW I would start by double checking what completions the LSP engine is returning in these cases. I have a feeling this is actually editor specific behavior and the _ is not the root issue. Most likely if we wanted to improve this we'd need to use either the filter text or the sort text field in the LSP protocol

**Comment by LoipesMas** [comment]
If you need more information or want me to test something, let me know

**Comment by GearsDatapacks** [comment]
I can't reproduce this on 1.5.0 with VSCode. Can someone try this with neovim to see if it still occurs?

**Comment by lpil** [comment]
Yup looks like this is a Neovim behaviour. Thanks all
