### ISSUE TITLE
Can use private type in signature of public function when in a very specific directory

### ISSUE THREAD

**Issue by Olian04** [gleam-lang/gleam#3387]
Normally the following code would result in an error.

```gleam
type Foo {
  Foo
}

pub fn bar(arg: Foo) -> Foo {
  case arg {
    Foo -> Foo
  }
}
```

```error
Private type used in public interface

The following type is private, but is being used by this public export.

    Foo

Private types can only be used within the module that defines them.
```

However if you put that code inside of a module located in a very specific directory, then it doesn't cause an error. On top of that, if you're generating `.d.ts` files, then those files will refer to types that don't exists.

```typescript
export function bar(arg: Foo$): Foo$;
```

```error
Cannot find name 'Foo$'.ts(2304)
```

## Steps to reproduce

```sh
gleam new type_bug
cd type_bug
mkdir src/type_bug # this folder must be named the same as the project
mkdir src/type_bug/internal # this folder must be named internal
cat > src/type_bug/internal/bug.gleam << EOF
type Foo {
  Foo
}

pub fn bar(arg: Foo) -> Foo {
  case arg {
    Foo -> Foo
  }
}
EOF
```

## Versions

**Gleam:** gleam 1.3.1
**OS:** macOS 14.5

## Gleam Logs

https://gist.github.com/Olian04/fb5cf7ebd58d4c9a89d9823a1696ccf5

**Comment by Acepie** [comment]
FYI I believe this is intentional https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/analyse.rs#L1168-L1175 Since the module is internal the function is allowed to be exported for use in the same package

**Comment by lpil** [comment]
It's not intentional! Private types should never leak from their module, even if that module is internal.

**Comment by Acepie** [comment]
Ah ok I misinterpreted this then. Lemme fix this up
