### ISSUE TITLE
LSP: Not starting in Neovim

### ISSUE THREAD

**Issue by joselevelsup** [gleam-lang/gleam#3391]
First off, I would like to say this has been an awesome lang to learn and just play around with. I'm just having issues with getting it to work with my Neovim. I have been to numerous reddit posts and searched the gleam repo's issues both closed and open to see if anyone is having the same issue. It just won't work with my neovim setup. I even used the same line of code that was advised to another reddit user ([Post for context](https://www.reddit.com/r/gleamlang/comments/1d1xp1p/problem_with_neovim_gleam/)):
```lua
  local lspServers = require("lspconfig")

  lspServers.gleam.setup({})

```

But nothing. No autocomplete, no errors. I even went as far as to remove gleam using my package manager and just use the released build from the repo. Still nothing. 

Even looking at Neovim's LSP Log, I get this:
```
[START][2024-07-11 17:27:32] LSP logging initiated
[ERROR][2024-07-11 17:27:32] .../vim/lsp/rpc.lua:770	"rpc"	"/usr/local/bin/gleam"	"stderr"	"Hello human!\n\nThis command is intended to be run by language server clients such\nas a text editor rather than being run directly in the console.\n\nMany editors will automatically start the language server for you\nwhen you open a Gleam project. If yours does not you may need to\nlook up how to configure your editor to use a language server.\n\nYou can exit this program by pressing ctrl+c.\n\n"
```

Neovim Version:
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1720049189
```

If someone can please help me out or provide me some direction to get the LSP working, that would be awesome. I have been using Gleam without the LSP and while I still have been enjoying myself, I feel like the LSP would help me to another level. Thank you so much and again...this lang is awesome.

**Comment by lpil** [comment]
What does the neovim LSP logs say?

Do you have Gleam code auto formatting?

Are you editing Gleam files that are created in a Gleam project?

Does the code successfully compile using the command line?

**Comment by joselevelsup** [comment]
Thank you for the questions!

The log I get when running `:LSPLog` is:
```
[START][2024-07-11 17:27:32] LSP logging initiated
[ERROR][2024-07-11 17:27:32] .../vim/lsp/rpc.lua:770	"rpc"	"/usr/local/bin/gleam"	"stderr"	"Hello human!\n\nThis command is intended to be run by language server clients such\nas a text editor rather than being run directly in the console.\n\nMany editors will automatically start the language server for you\nwhen you open a Gleam project. If yours does not you may need to\nlook up how to configure your editor to use a language server.\n\nYou can exit this program by pressing ctrl+c.\n\n"
```

> Do you have Gleam code auto formatting?

Nothing is being formatted at all. I just tried that. 

> Are you editing Gleam files that are created in a Gleam project?

I most definitely am! I created a simple wisp project and have a gleam.toml  and manifest.toml file in the root of my project.

> Does the code successfully compile using the command line?

Ok so it wasn't compiling. I was getting an error in one of my functions not properly returning a response. But it's weird...now it's working. 

Did I misunderstand something? Did I need to compile first in order to get the LSP to work?

Apologies if I messed up or didn't read something properly. It's just that before I compiled (or tried compiling) it wasn't working but after, it works just fine. Provides me no autocomplete and errors.

**Comment by joselevelsup** [comment]
Oh the log I attached above was when the LSP was started BEFORE compiling.

**Comment by lpil** [comment]
Auto formatting should always work. Anything that requires type information won't work if the project has never successfully started compiling, for example due to dependencies not compiling.

Glad whatever the problem was went away!

**Comment by joselevelsup** [comment]
Thank you for the explanation! I'll remember to keep that in mind.
