### ISSUE TITLE
Formatter moves doc comments around when surrounded by commented-out code

### ISSUE THREAD

**Issue by JosephTLyons** [gleam-lang/gleam#3396]
https://github.com/user-attachments/assets/460a0bcd-fe68-4e2d-91ae-bb0fa53464b1

```gleam
/// Docs
pub fn func_1() {
  todo
}

/// Docs
pub fn func_1() {
  todo
}
```

gleam 1.3.0
macOS 14.4

**Comment by giacomocavalieri** [comment]
I think this is the same as <https://github.com/gleam-lang/gleam/issues/2015>

**Comment by JosephTLyons** [comment]
Yep, that is the same! Thanks. 

Wow, even our repro cases are almost identical! 😆
