### ISSUE TITLE
gleam compiler seems confused when erlang module has the same name of gleam module

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [gleam-lang/gleam#3403]
### Description/Steps to Reproduce

When creating crearting an erlang module and using the ffi from gleam module, the gleam compiler (or something else) seems to confuse the native function and the gleam function.

I have an example repository here: https://github.com/RudolfVonKrugstein/gleam_ffi_test but it is very simple:

There is an erlang module:

```erlang
-module(native).
-export([ping/0]).

ping() ->
        io.write("ping~n").
```

and an gleam module with the same name using the function in the erlang module via ffi:

```gleam
@external(erlang, "native", "ping")
pub fn ping() -> Nil
```

and than a main module that uses the ffi function:

```gleam
import native

pub fn main() {
  native.ping()
}
```

when running this with `geam run` the result is that it never returns.

Looking at the compiled source, I think what happens is that the `ping` function calls itself and therby creates an infinite loop.

One can also import the `ping` function with a different name:

```gleam
@external(erlang, "native", "ping")
pub fn ping_native() -> Nil
```

In this case I get:

```bash
> gleam run
  Compiling ffi_test
   Compiled in 0.22s
    Running ffi_test.main
exception error: undefined function native:ping/0%
```

### What I would expect

It's probably totally OK, that the gleam module and the erlang module may not have the same name, but the gleam compiler should give me an error message in these situation, telling me that this does not work.

### My system 

Ubuntu in WSL and gleam version:

```bash
> gleam --version
gleam 1.2.1
```

**Comment by lpil** [comment]
Hello! You are overriding one with the other there, causing the first to be evicted from the VM.

There's an issue here for statically preventing this from being done accidentally https://github.com/gleam-lang/gleam/issues/1267

**Comment by RudolfVonKrugstein** [comment]
oh, I didn`t see that when seraching for related issues, sorry :(.
