### ISSUE TITLE
Gleam exits silently when erl doesn't work

### ISSUE THREAD

**Issue by hfjallemark** [gleam-lang/gleam#3407]
Turns out that when `erl` exited with `[1]    53507 bus error  erl` running `gleam run` (or `gleam test`) just exited silently. Not sure how to reproduce it but updating erlang fixed the issue for me. Would probably be good to fail `gleam run/test` if erlang doesn't work probably.

**Comment by lpil** [comment]
Sorry, I'm not sure what you're asking for. By this point the Gleam build tool is no longer running as the VM has been booted.

**Comment by hfjallemark** [comment]
Yeah maybe nothing to do with Gleam itself. On the gleam discord they asked right away if my erl was working so they seemed have made some connection to that being the issue.

**Comment by hfjallemark** [comment]
Closing for now as I can't reproduce it anymore since upgrading erlang 👍
