### ISSUE TITLE
Field punning

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#3411]
```gleam
let day = something()
let month = something()
let year = something()
let date = Date(day:, month:, year:)
```

And `Date(day:, month:, year:)` expands to `Date(day: day, month: month, year: year)`.

Should work in:
- Record constructors, both patterns and values
- Labelled functions

https://github.com/gleam-lang/gleam/discussions/3146

**Comment by giacomocavalieri** [comment]
If you were not planning to do it yourself, I can start working on this right away! 😁

**Comment by lpil** [comment]
Go for it!
