### ISSUE TITLE
LSP: Hover shows "a" when a function call is wrong

### ISSUE THREAD

**Issue by themartdev** [gleam-lang/gleam#3446]
When using the _hover_ lsp capability on function calls with mismatched types or a bad arity, the language server show "a":

[Screencast from 2024-07-28 16-55-02.webm](https://github.com/user-attachments/assets/573e22fc-9103-4935-b458-2f38748efbf7)

Gleam: `gleam 1.3.2`
OS: `Ubuntu 24.04 LTS x86_64`
Erlang: `Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:32:16] [ds:32:16:10] [async-threads:1] [jit:ns]`
Using the default gleam neovim lspconfig setup

**Comment by themartdev** [comment]
Just tested the main branch and its looks like it got fixed by #3406. Thank you!

**Comment by lpil** [comment]
Note this wasn't a big, rather that's the most general type and all that could be inferred when there is an error.
