### ISSUE TITLE
Prefixed ints require brackets to be negated

### ISSUE THREAD

**Issue by richard-viney** [gleam-lang/gleam#3448]
Ints with a prefix of `0x`, `0b`, or `0o` can't be written as negative values. For example,

```gleam
let i = -0xFF
```

gives the error

```gleam
let f = -0xFF
          ^^^ This is not a valid name
```

However, it's possible to add brackets to get the desired result:

```gleam
let x = -{ 0xFF }
```

I'm not sure if the is intentional / expected as it's not mentioned on https://tour.gleam.run/basics/number-formats/.

FWIW, both Node and Rust do allow `-0xFF` syntax.

Gleam v1.3.2.

**Comment by richard-viney** [comment]
Closing as this seems to be a won't fix situation.

**Comment by richard-viney** [comment]
Could do, tbh I'm not clear on the exact reason why this is a breaking change in the syntax.

**Comment by inoas** [comment]
> Could do, tbh I'm not clear on the exact reason why this is a breaking change in the syntax.

I meant this more as an impulse, not that I have any say or plan, just an idea to keep things. To reduce labour for this, there could be two new github labels:

- breaking-1.x-wontfix
- wontfix

Where latter would be applied if something is not desired and earlier is applied if it cannot be fixed within 1.x

Those breaking-1.x-wontfix can then later be visited again if 2.x ever happens to see if they can be then done.
