### ISSUE TITLE
LSP: Add local variable suggestions

### ISSUE THREAD

**Issue by Bkeinn** [gleam-lang/gleam#3455]
Add lsp support for suggesting local variables

Expect: 
![Screenshot from 2024-07-29 21-36-43](https://github.com/user-attachments/assets/ff18cc48-6827-4c9d-87c7-170f86ba54b8)
it to suggest the add_one variable

**Comment by lpil** [comment]
Thank you

**Comment by GearsDatapacks** [comment]
This can be closed now that #3480 has been merged
