### ISSUE TITLE
Warning of unused function

### ISSUE THREAD

**Issue by mgwidmann** [gleam-lang/gleam#348]
Compiling on the master branch (edc93f5c0cd71b8f628c8533978e9e5f47ac5c0f) gave the following warning:

```
warning: method is never used: `new`
    --> /Users/mgwidmann/code/gleam/gleam/target/release/build/gleam-6dfb76ad56a57b49/out/grammar.rs:3939:9
     |
3939 |         pub fn new() -> ExprParser {
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: `#[warn(dead_code)]` on by default
```

**Comment by lpil** [comment]
This is an expected warning being emitted by the parser generator. I'll leave this open to prompt us to suppress the warning. Thank you :)

**Comment by mgwidmann** [comment]
Why is a public function thats never called flagged as dead code? Seems public functions shouldn't do this as they could be used externally.

**Comment by lpil** [comment]
That's true for compilers that compiler per-module (like Erlang, Gleam, Typescript), but it is not true for whole-program compilers like Rust's. A function that is never called is dead code even if it public.

**Comment by OvermindDL1** [comment]
> but it is not true for whole-program compilers like Rust's. A function that is never called is dead code even if it public.

Well unless it's `extern`, as then it could be called by something dynamically linked.  ^.^
