### ISSUE TITLE
`gleam export package-interface` breaks when build is cached

### ISSUE THREAD

**Issue by GearsDatapacks** [gleam-lang/gleam#3488]
How to reproduce:
```sh
# In the root directory of a gleam project
gleam export package-interface --out pi.json
gleam export package-interface --out pi.json
```

After the second build, `pi.json` contains no modules, only the package name and version:
```json
{"name":"<package name>","version":"1.0.0","gleam-version-constraint":null,"modules":{}}
```

Gleam version: 1.4.0
OS: Ubuntu 24.04

**Comment by GearsDatapacks** [comment]
Furthermore, if you change one file in the project, it only generates the `package-interface` for the module that changed, and any dependencies of that module

**Comment by lpil** [comment]
How strange! I thought we made this throw away the cache to ensure this didn't happen.

**Comment by GearsDatapacks** [comment]
Looks like this is a duplicate of #2898, which has been reopened now
