### ISSUE TITLE
gleam doesn't update, on AUR helper (yay)

### ISSUE THREAD

**Issue by TotoShampoin** [gleam-lang/gleam#3491]
## Steps and code to reproduce

`yay -S gleam`

## Versions for Gleam, OS, the runtime and any other software used

Gleam 1.3.2-1 -> 1.4.1-1  
Linux 6.10.2-arch1-1.1-g14  
yay v12.3.5 - libalpm v14.0.0  
rustc 1.76.0  
rustup 1.27.1 (if that's relevant)

## Logs from running the command

[gleam.log](https://github.com/user-attachments/files/16493218/gleam.log)

**Comment by lpil** [comment]
Hello! We are not the maintainers of any OS package, you will need to open an issue with whoever is.

**Comment by lpil** [comment]
We do not support old versions of Rust I'm afraid.
