### ISSUE TITLE
Infer minimum Gleam version 

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#3492]
Currently you can specify the minimum required Gleam version, but there's nothing to ensure that you have got it correct.

When analysing the code keep track of what features are used and use that to determine what the minimum Gleam version would be, and then complain if the version in `gleam.toml` is too permissive.

We don't need to worry about v0.* versions.

We could automatically add it to the package config before publishing if none is set.

**Comment by adamroyle** [comment]
This would be a good addition to `gleam fix`. It would be ideal if it could look at dependencies as well.

**Comment by sobolevn** [comment]
Questions:
- What about some bug fixes that can affect the version number implicitly? Like https://github.com/gleam-lang/gleam/pull/3525
- What about minor inference features that can also affect the final result? Like https://github.com/gleam-lang/gleam/pull/3522

I would say that I would only trust the minimal version number if I have a CI with this version passing and the CI with version-1 is failing. Maybe we can somehow work with this metadata?

**Comment by lpil** [comment]
Just features, we won't attempt to infer for bugs, and we won't depend on any CI systems or such for this information as there's too many factors for us to do it reliably, and it won't tell us the bounds.

**Comment by giacomocavalieri** [comment]
@sobolevn are you planning to work on this? Otherwise I'll be giving it a shot today

**Comment by sobolevn** [comment]
@giacomocavalieri, please, go ahead :)
I don't know the project's history well enough to do this.

**Comment by giacomocavalieri** [comment]
So after reading through the changelogs I've written down all the features I think should be taken into account, I'll go with this in the coming PR, please let me know if anything shouldn't be included or if you notice something is missing!

## Needs v1.1

- `@internal` annotation
- nested tuple access `#(#(a, b), c).0.1`

## Needs v1.2

- javascript external module name containing a `@`

## Needs v1.3

- arithmetic operations in guards

## Needs v1.4

- label shorthand syntax
- `<>` used in constant string
- options `little`, `big`, `signed`, `unsigned` and sized floats in bit array
  patterns and expressions on the js target
- option `utf8` in bit array patterns on the js target
