### ISSUE TITLE
Allow Strings in a BitArray literal without having to specify utf8 encoding

### ISSUE THREAD

**Issue by schurhammer** [gleam-lang/gleam#3495]
I think it would be a neat little ux improvement to allow strings in a bit array without specifying the encoding, defaulting to utf8.

```gleam
// instead of
<<"a":utf8, 1, 2, 3>>
// just write
<<"a", 1, 2, 3>>
```

**Comment by lpil** [comment]
Agreed! Thank you

**Comment by giacomocavalieri** [comment]
Should this work only for literal strings or for string variables as well?
