### ISSUE TITLE
string.drop_left  appears to return array of ASCII codes in some circumstances

### ISSUE THREAD

**Issue by pendletong** [gleam-lang/gleam#3499]
Running the following

`io.debug(string.drop_left("\r]", 1))`

returns the following in the specified targets

javascript : "]"
erlang : [93]

If you change the debug to include an append

` io.debug("Test " <> string.drop_left("\r]", 1))`

the erlang target returns the error
Failure: badarg

Currently using gleam 1.4.1 on Mac.

GLEAM_LOG= trace doesn't appear to output anything obviously useful:
TRACE reading_directory path="/Users/gareth/Development/gleam/codecrafters-grep-gleam/build/dev/erlang"
TRACE command_exec program="erl" args="-pa /Users/gareth/Development/gleam/codecrafters-grep-gleam/build/dev/erlang/simplifile/ebin -pa /Users/gareth/Development/gleam/codecrafters-grep-gleam/build/dev/erlang/gleam.lock/ebin -pa /Users/gareth/Development/gleam/codecrafters-grep-gleam/build/dev/erlang/gleeunit/ebin -pa /Users/gareth/Development/gleam/codecrafters-grep-gleam/build/dev/erlang/filepath/ebin -pa /Users/gareth/Development/gleam/codecrafters-grep-gleam/build/dev/erlang/argv/ebin -pa /Users/gareth/Development/gleam/codecrafters-grep-gleam/build/dev/erlang/gleam_stdlib/ebin -pa /Users/gareth/Development/gleam/codecrafters-grep-gleam/build/dev/erlang/grep/ebin -pa /Users/gareth/Development/gleam/codecrafters-grep-gleam/build/dev/erlang/gleam_erlang/ebin -pa /Users/gareth/Development/gleam/codecrafters-grep-gleam/build/dev/erlang/gleam_version/ebin -eval grep@@main:run(grep_test) -noshell -extra" env=[] cwd=None

.erl output is as follows:

```
gleam@io:debug(
        <<"Test "/utf8, (gleam@string:drop_left(<<"\r]"/utf8>>, 1))/binary>>
    ).
```

**Comment by joshi-monster** [comment]
In Erlangs' `string:slice` implementation, this pattern matches, but I have no idea why. It only happens for codepoint 13 of the ascii control characters.

```erlang
<<CP1/utf8, Bin/binary>> = <<"\r]"/utf8>>.
% CP1 = 13
% Bin = <<"]">>
```

this causes Erlang to return a list instead of a binary by [calling the wrong overload](https://github.com/erlang/otp/blob/OTP-27.0.1/lib/stdlib/src/string.erl#L1220).
