### ISSUE TITLE
Inconsistency with tag name format expected for source links in docs based on repository type

### ISSUE THREAD

**Issue by Nicd** [gleam-lang/gleam#3503]
1. Create project with version `1.0.0` and configure `gleam.toml` to point to GitHub/GitLab/Bitbucket as the repository. Observe that generated source links in the docs use `v1.0.0` format with "v" prefix to link to the correct source.
2. Change repository type to e.g. `forgejo` (`{ type = "forgejo",   host = "example.com", user = "example", repo = "my_project" }`). After regeneration of docs, observe that source links now point to `1.0.0` without "v" prefix.

From here on in the code we can see that GitLab/GitHub/Bitbucket have the "v" prefix in the URL and Gitea (Forgejo), CodeBerg, and SourceHut do not: https://github.com/gleam-lang/gleam/blob/8743158ef7ac8c8bebd045fadb4f4775a0e7cc8d/compiler-core/src/docs/source_links.rs#L30

Note: Fixing this would break existing users of the latter three who depend on there _not_ being a "v" prefix.

**Comment by lpil** [comment]
Thank you

**Comment by sobolevn** [comment]
@Nicd would you like to work on this? If not, I can take this over :)

**Comment by Nicd** [comment]
Go right ahead, I don't know when I would have time to take a look at it (I'm supposed to be in bed right now too!). It's a tiny change but need to check the tests and so on.

**Comment by Nicd** [comment]
An additional thing I just noticed: the "Repository" link that is generated has a double slash. So `repository = { type = "forgejo", host = "git.ahlcode.fi", user = "nicd", repo = "scriptorium" }` results in a link to `https://git.ahlcode.fi//nicd/scriptorium`.
