### ISSUE TITLE
[BUG] Allowing definition of multiple constructors with the same name

### ISSUE THREAD

**Issue by mgwidmann** [gleam-lang/gleam#351]
Quoting the [conversion](https://elixirforum.com/t/gleam-a-statically-typed-language-for-the-erlang-vm/20349/186?u=mgwidmann) on the elixir forum:

> That’s right! It is definitely a bug that Gleam allows you to define multiple constructors with the same name. If you have the time please open an issue for that. If not I’ll do it when I’m at a computer.
>
>Gleam Structs as a special enum type that has just one constructor

>This is a really good observation and one I had not considered. Now that enums can have labelled fields they are effective equivalent to structs. I wonder if we really need both. What might a unified syntax look like?
>
> ```
> type Person {
>   Person(name: String)
> }
> 
> type Size {
>   Big
>   Small
> }
> ```
> It would be nice to not have repeat the constructor name when there is only a single constructor. Perhaps it’s not a big deal

**Comment by lpil** [comment]
Thank you for the report!
