### ISSUE TITLE
Missing tests for UnusedLiteral and ImplicitlyDiscardedResult warnings

### ISSUE THREAD

**Issue by sobolevn** [gleam-lang/gleam#3529]
1. There are no tests for `UnusedLiteral` and `ImplicitlyDiscardedResult` in `expression_discarded` function, as far as I can tell. Only `UnusedValue` warning is tested.

2. The warning itself is confusing, when used with `io.debug`. I think that it should be excluded from this check. Becase this code:

```gleam
import gleam/bit_array
import gleam/io

pub fn main() {
  let r = bit_array.slice(<<1>>, 0, 1)  // returns Result
  
  io.debug(r)  // Ok(<<1>>)
  io.debug("done")
}
```

Warning:

```
warning: Unused result value
   ┌─ /src/main.gleam:10:3
   │
10 │   io.debug(r)
   │   ^^^^^^^^^^^ The Result value created here is unused

Hint: If you are sure you don't need it you can assign it to `_`.
```

Is much easier to read / write than:

```gleam
import gleam/bit_array
import gleam/io

pub fn main() {
  let r = bit_array.slice(<<1>>, 0, 1)  // returns Result
  
  let _ = io.debug(r)  // Ok(<<1>>)
  io.debug("done")
}
```

I can add tests for `UnusedValue` and `UnusedResult` cases and also skip `io.debug` (something else?) from this check.

Do others agree?

**Comment by giacomocavalieri** [comment]
I don't think I understand point 2, are you suggesting to disable the warning for `io.debug`? As for 1 more tests is always good, I think :)

**Comment by sobolevn** [comment]
I am evaluating this, yes. 

Let's say you have a code like this:

```gleam
fn compute() {
  1  // this is a result of some computation, not just literal 1
}

pub fn main() {
  let r = compute()
  
  io.debug(r)
  io.debug("done")
}
```

It works, then you change `compute`'s API and it starts to return a result:

```gleam

fn compute() {
  Ok(1)  // this is a result of some computation, not just literal 1
}
```

Now you have a warning. I can see two sides of it.
1. Results must be handled, otherwise it might shadow some bugs in your app. And this use-case is rather syntetic. So, it might be not worth the effort / maintainance
2. This is rather surprising, `io.debug` does not "ignore" the result, it prints it. That's the whole point of this function

**Comment by giacomocavalieri** [comment]
Well `io.debug` _returns_ a result you're not handling so the compiler is telling you, I think that's good and shouldn't be removed

**Comment by lpil** [comment]
More tests sounds good to me!

**Comment by sobolevn** [comment]
Sorry, there are tests for these two warnings. I just grepped better this time.

Literal values warnings:

```
    type_::tests::warnings::unused_bit_array
    type_::tests::warnings::unused_float
    type_::tests::warnings::unused_int
    type_::tests::warnings::unused_int_negation_raises_a_warning
    type_::tests::warnings::unused_list
    type_::tests::warnings::unused_result_raises_a_warning
    type_::tests::warnings::unused_string
    type_::tests::warnings::unused_tuple
```

Result warnings:

```rust
#[test]
fn result_discard_warning_test() {
    // Implicitly discarded Results emit warnings
    assert_warning!(
        "
pub fn wibble() { Ok(5) }
pub fn main() {
  wibble()
  5
}"
    );
}
```

Closing!
