### ISSUE TITLE
Improve suggestions for inexhaustive case expression error

### ISSUE THREAD

**Issue by GearsDatapacks** [gleam-lang/gleam#3544]
Currently, for this code:
```gleam
case True {}
```

The compiler produces this error:

```
error: Inexhaustive patterns
  ┌─ FILE
  │  
5 │ ╭   case True {
6 │ │     
7 │ │   }
  │ ╰───^

This case expression does not have a pattern for all possible values. If it
is run on one of the values without a pattern then it will crash.

The missing patterns are:

    _
```

This is not super helpful; it would be much better to suggest `True` and `False` as missing patterns instead. Also, #2957 cannot be implemented in a particularly useful manner until this is improved. (See [here](https://github.com/gleam-lang/gleam/pull/3537#discussion_r1723230130))

Edit: There was some confusion about the above code. The matching on the literal value `True`, has nothing to do with this. It's merely to demonstrate this error.

**Comment by lpil** [comment]
Thank you

**Comment by sobolevn** [comment]
Wouldn't it make sense to make `case True {}` a different error instead? Something like "Matching on a single known value"? The same as `case 1 {}` or `case Nil {}`. 

I don't think that there's any practical sense to it. However, this surely makes sense:

```gleam
let x: Bool = get_bool_return()
case x {
  True -> ...
  False -> ...
}
```

I will create a PR, so we can decide whether it is helpful or not.

**Comment by giacomocavalieri** [comment]
> Wouldn't it make sense to make `case True {}` a different error instead? Something like "Matching on a single known value"? The same as `case 1 {}` or `case Nil {}`.

The compiler already raises a warning for that:
```text
warning: Match on a literal value
  ┌─ /src/main.gleam:4:8
  │
4 │   case True {
  │        ^^^^ There's no need to pattern match on this value

Matching on a literal value is redundant since you can already tell which
branch is going to match with this value.
```

**Comment by sobolevn** [comment]
@giacomocavalieri yes, true. Only when there are no parser errors:

```gleam
pub fn main() {
  case True {
    _ -> "a"
  }
}
```

warns since v1.2

**Comment by giacomocavalieri** [comment]
Iirc that'n no longer a parse error, but an error that happens during analysis, so it would "just" be a matter of making the case expression analysis more fault tolerant

**Comment by lpil** [comment]
Thanks gang. I'll hide these to not distract from this issue
