### ISSUE TITLE
Add a warning for single pattern case expression

### ISSUE THREAD

**Issue by GearsDatapacks** [gleam-lang/gleam#3562]
This code:
```gleam
type Wibble {Wibble(Int, Float, String)}

pub fn main() {
  let wibble = Wibble(1, 2.0, "three")
  case wibble {
    Wibble(int, float, string) -> { ... }
  }
}
```

Uses a `case` expression to destructure `wibble`, using a single irrefutable pattern.
This can be done in a better way using `let`:

```gleam
// [...]
let Wibble(int, float, string) = wibble
...
// [...]
```

The compiler could emit a warning here, as well as a code action to transform the former into the latter.

**Comment by lpil** [comment]
Great idea!

**Comment by vkobinski** [comment]
I'm going to work on this.
