### ISSUE TITLE
Improve error message for using `@external` with unknown target

### ISSUE THREAD

**Issue by tcoopman** [gleam-lang/gleam#3567]
Gleam version: 1.4.1

This code

```gleam
@external(erl, "decode", "index")
```

results in this error:
![image](https://github.com/user-attachments/assets/ccbb0ca9-b0a9-4e24-a28d-fe6f82b7a4a8)

Instead of saying that the attribute is not recognized, valid values for the external should be shown.

**Comment by lpil** [comment]
Thank you
