### ISSUE TITLE
Enum variants don't have first-class constructor functions

### ISSUE THREAD

**Issue by rjdellecese** [gleam-lang/gleam#358]
It seems like right now, defining a named struct also defines the constructor function for it in such a way that it is accessible as a first-class function (can be passed to other functions), e.g.

```rust
pub struct CoolRobot {
  name: String
  arms: Int
}

pub struct FunRobot {
  name: String
  arms: Int
}

pub fn double_arms_factory(
  blueprint: fn(String, Int) -> robot,
  name: String,
  arms: Int
) -> robot
{
  blueprint(name, arms * 2)
}

double_arms_factory(CoolRobot, "Bender", 2) // CoolRobot("Bender", 4)
double_arms_factory(FunRobot, "Octobot" 8) // FunRobot("Octobot", 16)
```

However, this doesn't work for variants of enums:

```rust
pub enum AthleticRobot {
  AthleticRobot(name: String, arms: Int)
}

double_arms_factory(AthleticRobot, "Joe" 6) // Something bad happens!
```

In this case, the code actually compiles, but we get an Erlang `badarg` error when it runs, because `AthleticRobot` was simply translated into a bare atom, `athletic_robot`!

Could probably just be addressed in the course of unifying custom type definition syntax (https://github.com/gleam-lang/gleam/issues/355).

And I also wonder if this is somehow related to https://github.com/gleam-lang/gleam/issues/351?

**Comment by lpil** [comment]
Good find! This is definitely a bug in the Erlang code generation.

I think #355 will fix this as we'll be reworking this area.
