### ISSUE TITLE
Pattern alias on error causes mismatch 

### ISSUE THREAD

**Issue by pendletong** [gleam-lang/gleam#3586]
Applying an alias to the Error pattern appears to cause Type mismatch error

I managed to get a simple example as follows:
```
import gleam/option.{type Option, Some}

pub fn example(
  group: Option(value),
  filter_fn: fn(value) -> Result(value2, Nil),
) {
  let assert Some(v) = group
  let _a = case filter_fn(v) {
    Ok(val) -> Ok(Some(val))
    Error(_) as err -> err
  }
  
}
```

This results in the following error:
```
Type mismatch

This case clause was found to return a different type than the previous
one, but all case clauses must return the same type.

Expected type:

    Result(Option(value2), a)

Found type:

    Result(value2, Nil)
```

If the Error(_) line is moved above the OK(val) line the error swaps the expected and found types
```
Type mismatch

This case clause was found to return a different type than the previous
one, but all case clauses must return the same type.

Expected type:

    Result(value2, Nil)

Found type:

    Result(Option(value2), a)
```

Changing `Error(_) as err -> err` to `Error(err) -> Error(err)` however resolves the issue and removes the error.
Changing Some(val) to val also resolves the issue.
Specifying a return type of the function doesn't seem to make a difference.

Hopefully I'm not misunderstanding the aliasing mechanism.

**Comment by lpil** [comment]
This is because the two errors have different value types. This could be supported in future with a sophisticated type system extension called type narrowing, which there is an issue for.
