### ISSUE TITLE
LSP Doesn't show completions for prelude values

### ISSUE THREAD

**Issue by GearsDatapacks** [gleam-lang/gleam#3590]
The Language Server does not provide completions for prelude values, such as `True`, or `Error`.

To reproduce, start typing:
```gleam
pub fn main() {
  let my_bool = T
  //             ^ Cursor here
}
```

You will see completions for various functions from different modules, but not the value `True`.

**Comment by lpil** [comment]
Oh yes, let's get these. thank you
