### ISSUE TITLE
Guards don't seem to evalutate correctly for exhasutiveness checking.

### ISSUE THREAD

**Issue by funnyman2213** [gleam-lang/gleam#3596]
Matching against an integer utilizing guards that account for all possible options still returns the error "Inexhaustive patterns" requesting to add the `_` case. 

The following example contains cases for the following: >43, 43, 42, 41, <41

```gleam 
pub fn reply(guess: Int) -> String {
  case guess {
    i if i > 43 -> "Too high"
    42 -> "Correct"
    i if i == 41 || i == 43 -> "So close"
    i if i < 41 -> "Too low"
  }
}
```

**Comment by funnyman2213** [comment]
Appending to this, gleam version is 1.4.1

**Comment by GearsDatapacks** [comment]
I will note that it's pretty hard to do this. You need to figure out the set of possible integers which is narrowed down to in each clause, which requires a lot of analysis and is unlikely to be implemented in the foreseeable future. 

For now if you're in this situation and you can know that it covers all cases, you can just add:
```gleam
case guess {
  ...
  _ -> panic as "unreachable"
}
```

**Comment by lpil** [comment]
Exhaustiveness checking of arbitrary boolean expressions is largely an unsolved problem in computer science so when a guard is present it is presumed to be possible to evaluate to false. The good news is that if the guard cannot evaluate to false then it is redundant and does nothing but make your code slightly slower, so it can be safely removed.
