### ISSUE TITLE
LSP code action: Toggle between qualified and unqualified import

### ISSUE THREAD

**Issue by george-grec** [gleam-lang/gleam#3603]
Currently, when you take a suggested auto import from the LSP for a type like here:
```gleam
pub fn wibble() {
  Som|
}
```
and select the `Some` variant from the `gleam/option` module you get the following code:

```gleam
import gleam/option

pub fn wibble() {
  option.Some|
}
```

In many cases, you actually want to use an unqualified import for a type or variant because you (plan to) use it heavily, e.g. Option, Some, None, lustre elements, Dynamic. To do that right now you have to go to the top of the file and find your way back to where you were.
This breaks your developer flow so it would be great if there was a code action when hovering the type or variant to change the import to an unqualified one or vice versa.

**Comment by AcnoSaga** [comment]
I'd love to start hacking on this. Where can I find the LSP code? Still familiarising myself with the codebase.

**Comment by lpil** [comment]
In here! https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/language_server.rs

**Comment by giacomocavalieri** [comment]
Do we want to allow this just for record constructors or for all kind of functions? I think making it easier to use functions unqualified would be a net loss given we want to encourage the opposite style

**Comment by lpil** [comment]
Just types and constructors sounds good

**Comment by Frank-III** [comment]
> I'd love to start hacking on this. Where can I find the LSP code? Still familiarising myself with the codebase.

Hi @AcnoSaga, are you still looking into this? if not, I would like to give it a shot!
