### ISSUE TITLE
Consider inserting `todo`s in incomplete `use` expressions when formatting.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#3605]
A new user [recently confused](https://discord.com/channels/768594524158427167/1282783923100844064/1282783923100844064) (discord link) about some of the rules/differences between `let` expressions and `use` expressions. I think part of this confusion comes from being able to write a program like...
```gleam
fn example() {
  use x <- f
}
```
without the formatter inserting `todo`s when saving to indicate the expression is incomplete.

This behaviour already happens with `fn` expressions, and I think it would be both a nice QoL change and a better demonstration of the "use is just syntax sugar for callbacks" mantra that is often repeated.

**Comment by giacomocavalieri** [comment]
I totally agree! I've implemented the change in the formatter, I believe it would be really nice to have this

**Comment by lpil** [comment]
Boom! Thanks both
