### ISSUE TITLE
Answer to 3593

### ISSUE THREAD

**Issue by Sajjon** [gleam-lang/gleam#3609]
@lpil hey regarding #3593 (user blocked me I think)

You can read this:
I recommend reading [this good article by Kaspersky](https://www.kaspersky.com/blog/copay-supply-chain-attack/24786/) about the one famous supply chain attack to the Copay wallet. Here you can find some more: https://chains.proj.kth.se/software-supply-chain-attacks-crypto.html

Github very subtle informs reviewers of a PR that this contributor have not contributed before. By creating a small PR which is easily approved and merged, the second PR by the same Github user will have no “First time contributor” indicator. This time other, not so vigilant colleagues might not review as closely and this time the attacker might change a dependency, to some version the attacker has created containing malicious code. 

Since gleam is a language, based on Rust, a long time investment attack would be to get CI/CD privileges and release a Gleam version with malicious code and then immediately revert that malicious code - which was included in version `X.Y.Z`.

Then attacker changes another repo `R` which used gleam, to malicious version `X.Y.Z` which looks harmless to reviewers of repo `R` and this repo might be a crypto lib in turn used by a crypto wallet. Attacker manages to drain user funds. This sounds like a longshot - it is - but it was the Copay wallet attack!

So be mindful of trivial contributions from Github users for which MANY of these criteria are true (ofc common for SOME to be true for many users)
* have no followers 
* no repo SOURCES (only branches)
* no bio
* no photo
* not Github Pro users
* not GPG/SSH signing commits

Be especially mindful of users who have cloned many crypto libs in a short time and made trivial contributions

**Comment by lpil** [comment]
Thank you.
