### ISSUE TITLE
LSP: "Go to definition" does not work on external functions declared in the same file

### ISSUE THREAD

**Issue by george-grec** [gleam-lang/gleam#3610]
How to reproduce:

1. Create this gleam file and a corresponding `wibble_ffi.mjs`.

```gleam
pub fn main() {
  external_wibble()
}

@external(javascript, "./wibble_ffi.mjs", "wibble")
fn external_wibble() -> Nil
```

2. Hover over `external_wibble()` and use the "go to definition" feature from your editor.
3. Nothing happens.

Expected behavior: the cursor should move to the function declaration of `external_wibble()`.

**Comment by lpil** [comment]
Oh dear! Thank you

**Comment by giacomocavalieri** [comment]
I'm working on this!
