### ISSUE TITLE
Formatter wraps lines with big grapheme clusters

### ISSUE THREAD

**Issue by joshi-monster** [gleam-lang/gleam#3627]
The following code snippet gets wrapped onto multiple lines. The string has been taken from the [unicode-segmenter](https://github.com/cometkim/unicode-segmenter/blob/main/test/grapheme.js#L103) javascript library tests and consists of 6 grapheme clusters and 75 codepoints.

```gleam
pub fn main() {
  sw("ZALGO!", [])
}
```

gets formatted as

```gleam
pub fn main() {
  sw(
    "ZALGO!",
    [],
  )
}
```

tested using Gleam 1.4.1 and 1.5.0-rc1 :purple_heart: 

**Edit:** It seems like Github is stripping out most of the codepoints, which I guess is reasonable since stacks of modifiers are used in spam; the link to the source file above points to the line with that string.

**Comment by joshi-monster** [comment]
Here is another example using an emoji family that github preserves:

```gleam
pub fn main() {
  sw(
    "👩‍👩‍👧‍👦👩‍👩‍👧‍👦👩‍👩‍👧‍👦👩‍👩‍👧‍👦👩‍👩‍👧‍👦👩‍👩‍👧‍👦👩‍👩‍👧‍👦👩‍👩‍👧‍👦",
    [],
  )
}
```

**Comment by lpil** [comment]
Thank you
