### ISSUE TITLE
Enable pre-gleam-1.5 `gleam run -m` compilation behaviour (maybe with a compiler flag like --build)

### ISSUE THREAD

**Issue by TanklesXL** [gleam-lang/gleam#3632]
Before gleam 1.5 was released, the `gleam run -m` command would rebuild the entire project. This behaviour was depended on by some tools (like gladvent). While I think this change was the right one, I would like some way to manually trigger full project recompilation in order to preserve the old behaviour as needed.

**Comment by lpil** [comment]
Could you expand more on the use case please 🙏

**Comment by TanklesXL** [comment]
Sure! I'll try to describe how I use it in gladvent today: 

Gladvent operates by checking that the modules it's expecting to run export the correct functions and their signatures by generating and looking at the package-interface.json. Once that step is done it knows what module names and functions to run and does so via FFI (a little cursed but incredibly practical). In order for this to work when rubbing gladvent the requisite modules (found in src/aoc_<year>/day_<day>.gleam) need to be compiled and loaded into the VM *when gladvent is run* so that gladvent can call the functions directly.

The new changes in gleam 1.5 mean that the user will either have to manually compile before running gladvent or otherwise have an outdated compiled version of their code loaded into the VM when gladvent is run.

**Comment by lpil** [comment]
I've been thinking about this and I can't think of a good way to do this that doesn't result in the niche case making the general case worse, and I don't think a flag is a good fit as the programmer would need to remember for each module which flags to give.

I think it may be best for these commands to call `gleam build` themselves.

**Comment by TanklesXL** [comment]
Hmm, that makes sense. In my particular case the issue with the command calling `gleam build` is that I would then need to manually load the newly compiled modules into the running VM session, which is a bit awkward. As mentioned in discord, I think it's probably better for me to not run as a command and simply for users to add a call to gladvent in their `main` so as to guarantee that their freshly compiled code is always available

**Comment by lpil** [comment]
Fab. Thank you 💜
