### ISSUE TITLE
Small inconsistency in error display

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#3638]
There's a small inconsistency between the look of compiler errors/warnings and the new pretty runtime errors:
![Screenshot 2024-09-20 alle 22 51 08](https://github.com/user-attachments/assets/47120de9-3827-4324-bd34-4c8bf3f970e5)
![Screenshot 2024-09-20 alle 22 51 54](https://github.com/user-attachments/assets/371cfac3-8ddf-4ed9-b090-f3470746d60d)

In runtime errors `error:` is all red, while in the compiler error reports the `:` after `error`/`warning` isn't red/yellow like the text preceding it.

It's super small, but it would be nice if the display were consistent here

**Comment by lpil** [comment]
Thank you

**Comment by radar07** [comment]
@lpil Can I work on this? I'm kinda new to Gleam. So, I might need some time and guidance over here. 😅

**Comment by lpil** [comment]
Go for it! Though this code is written in Erlang, not Gleam
