### ISSUE TITLE
Importing type record compiler error could be better

### ISSUE THREAD

**Issue by hgezim** [gleam-lang/gleam#3646]
```
// gleam_chest.gleam
pub type TreasureChest(a) {
  TreasureC(String, a)
}
```

```
// gleam_chest_test.gleam

import exercism/should
import exercism/test_runner
import treasure_chest.{TreasureChest}


```

I get this error for third import:

```
error: Unknown module field
  ┌─ /Users/gezim/Exercism/gleam/treasure-chest/test/treasure_chest_test.gleam:3:24
  │
3 │ import treasure_chest.{TreasureChest}
  │                        ^^^^^^^^^^^^^ Did you mean `type TreasureChest`?

`TreasureChest` is only a type, it cannot be imported as a value.
```

The error really doesn't help me know that I'm not importing the record ... which I should be?

I'm new to the language and I was trying to use `TreasureChest` instead of `TreasureC`, FWIW.

In general, I'm finding custom types quite confusing. Unsure about when to use `TreasureChest` vs `TreasureC` but that's neither here not there.

**Comment by giacomocavalieri** [comment]
Hello! When you write a custom type like this:
```gleam
pub type TreasureChest(a) {
  Chest(String, a)
}
```
You are defining two things:
```gleam
pub type TreasureChest(a) {
//       ^^^^^^^^^^^^^^^^ A _type_ `TreasureChest`
  Chest(String, a)
//^^^^^^^^^^^^^^^^ A _variant_ to build values of type `TreasureChest`
}
```
So when you need to build a value you use the _variant:_
```gleam
let my_treasure_chest = Chest("my_lucky_number", 11)
```
And that variable will have type `TreasureChest(Int)`, you could even add an explicit type annotation to make it extra clear:
```gleam
let my_treasure_chest: TreasureChest(Int) = Chest("my_lucky_number", 11)
```
So the _type_ only lives at the type level and is used in type annotations, while that variants live at the _value_ level and are used to build values of a given type (and when pattern matching with `case`).
I hope this clear things up a bit :)

---

Getting to the error message, when you write `treasure_chest.{TreasureChest}` the compiler can't really tell you meant to import the variant `TreasureC` or the type `TreasureChest` but you forgot the `type` keyword before it, but seeing that it looks exactly like the type name it tries to suggest importing the type by adding the `type` keyword.
It's one of those cases where no solution would make everyone happy: if it suggested to import the value instead people who wanted to import the type would find the message not helpful so there's not much we can change here I'm afraid.

**Comment by lpil** [comment]
Thanks all
