### ISSUE TITLE
Should get warning/error when variable overlaps an existing identifier

### ISSUE THREAD

**Issue by hgezim** [gleam-lang/gleam#3649]
```
pub fn busy_days(bird_count: BirdCount) -> Int {
  let busy_days = 0
  case bird_count {
    [] -> 0
    [s, ..rest] if s >= 5 -> 1 + busy_days(rest)
    [s, ..rest] -> busy_days(rest)
  }
}
```

I was really confused by the error on this when I'm calling `busy_days`:

```
Type mismatch

This value is being called as a function but its type is:

    Int
```

I didn't realize I was being an idiot and declared `busy_days` again on line 2.

**Comment by GearsDatapacks** [comment]
This shouldn't be a warning. It's a code Gleam feature that you can shadow existing identifiers

**Comment by inoas** [comment]
<small>Having something like `const` within function bodies that does the same as let but does not allow rebinding _COULD_ help here. It could also prohibit shadowing functions in the module scope.</small>
