### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by hgabe** [gleam-lang/gleam#367]
Hello Gleam

Is there a changelog as to whats new in the 0.6.0 release?

Thank You

**Comment by rjdellecese** [comment]
Hi @hgabe!

There the changelog can be found [here](https://github.com/gleam-lang/gleam/blob/master/CHANGELOG.md), and @lpil also wrote a blog post for the 0.6.0 release [here](https://lpil.uk/blog/gleam-v0.6-released/).

**Comment by lpil** [comment]
Thanks @rjdellecese !

**Comment by hgabe** [comment]
Thank You @rjdellecese
