### ISSUE TITLE
LSP: Add parentheses and cursor position when completing functions

### ISSUE THREAD

**Issue by themartdev** [gleam-lang/gleam#3674]
Hi!
I'm not sure how opinionated this is, but I would like for function completion to add parentheses and position the cursor inside/outside of those depending on the arity of the function:

```gleam
pub fn main() {
  io.debug(<cursor>)
  wisp.configure_logger()<cursor>
}
```

The only case where I can think it could be a downgrade is with pipes, but maybe we can have different behavior in that context

**Comment by lpil** [comment]
Please see prior discussion for why we do not implement this presently.

**Comment by themartdev** [comment]
@lpil Can you point me to the discussion in question? I found the older issues regarding autocompletion, but I can't find anything related to this

**Comment by giacomocavalieri** [comment]
Hello! The prior discussion happened here <https://github.com/gleam-lang/gleam/pull/3308#issuecomment-2184839999>

**Comment by themartdev** [comment]
Thank you! I understand the point of view. Personally I think that since the frequency of using a function as a value is often much lower than calling it directly, in the end it's more annoying to add brackets most of the time vs deleting it sometimes. But it does seem like a completely subjective view, and maybe since Gleam is a functional language the proportion is not as one-sided as a language like go.

Of course the best case would be to make it context-dependant, but I don't think it's something we can expect in the short term.

Thank you!
