### ISSUE TITLE
Old modules remain in `gen/` directory after recompilation

### ISSUE THREAD

**Issue by rjdellecese** [gleam-lang/gleam#368]
When I create a module, compile my Gleam code, and then rename or delete that module, its generated Erlang code sticks around in the `gen/` directory, even after recompiling again. I would have assumed that upon recompilation, the `gen/` directory would reflect only the Gleam code in my project at that time.

This very rarely has caused any issues, but is a somewhat opaque problem to debug when it does!

**Comment by lpil** [comment]
We're don't have any way of knowing whether modules have been removed or not so we cannot safely clean the gen directory. Should the rebar plugin delete the directory? Or perhaps we could keep track of what was previously generated.

**Comment by rjdellecese** [comment]
Although a bit ham-fisted, is there any reason deleting the directory before recompiling wouldn't work fine, for now?

The other solution (of keeping track of what was previously generated) would probably involve generating a manifest, right? Would that help at all with the future of https://github.com/gleam-lang/gleam/issues/157? My reference in asking is the way the [the Elixir compiler](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/compilers/elixir.ex) utilizes a manifest file.

**Comment by lpil** [comment]
I think the manifest is the way to go, and it will be required in that ticket.

I guess for now we could delete the directory, I can't think of any reason why it would cause problems :)

**Comment by rjdellecese** [comment]
If you haven't already starting working on this I'd love to take a crack at it @lpil (also assuming that wouldn't mean holding up a release!).

**Comment by NobbZ** [comment]
If we delete the `gen` folders content, then every module will be recompiled, this is probably true.

Though if we keep it, will still everything be recompiled or only those modules that need to due to changes of their sources?

If the latter I opt against unconditionally deleting the folder, but instead use heuristics to check if files need to be removed or only remove on `--force` flag.

**Comment by lpil** [comment]
We don't have incremental compilation yet, all modules are always recompiled. More fine grained compilation will come as part of #157

**Comment by lpil** [comment]
We always recompile all Gleam modules and overwrite the Erlang modules, so this shouldn't change the current behaviour of rebar3. Incremental compilation is tracked here #157
