### ISSUE TITLE
Wrong error message for values in a pipe

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#3686]
If I write the following code:
```gleam
pub fn main() {
  wibble
  |> "a"
}

fn wibble(_: Int) -> String { todo }
```
I get the following error message:
```txt
error: Type mismatch
  ┌─ /src/main.gleam:5:6
  │
5 │   |> "a"
  │      ^^^

Expected type:

    String

Found type:

    fn(fn(Int) -> String) -> a
```
It looks like it has the expected and found types swapped.

**Comment by lpil** [comment]
Thank you

**Comment by eolculnamo2** [comment]
I'm interested at giving this issue a go. What should the correct behavior be?  The more I look at this, the less it seems like expected/found is swapped. Instead, it's not valid to pass an argument to an expression (such as a string) that isn't expecting an argument, right?

**Comment by MarkusPettersson98** [comment]
I can work on this :)
