### ISSUE TITLE
Compiler error about "unknown module value" could highlight existence of type with the same name

### ISSUE THREAD

**Issue by michaeljones** [gleam-lang/gleam#3691]
*As reported on [Discord](https://discord.com/channels/768594524158427167/768594524158427170/1294276312541691935).*

I'm currently getting an error:

```
error: Unknown module value
   ┌─ /home/michael/root/projects/gleam-lang/plug/src/wisp/plug.gleam:57:7
   │
57 │   wisp.Request(
   │       ^^^^^^^^

The module `wisp` does not have a `Request` value.
```

It might be helpful it also said something like "There is a Request **type** in wisp but that cannot be constructed directly. You need to import a type constructor..." Or something like this? With the right words? And better?

Or maybe that is just too complex in this case as wisp.Request is a type alias for something that isn't normally created directly?

**Comment by lpil** [comment]
Something like "Xyz is a type/type constructor, it cannot be used as a value"?
