### ISSUE TITLE
Repeating var name inside a pattern compiles to distinct var names

### ISSUE THREAD

**Issue by zoldar** [gleam-lang/gleam#370]
👋 I may be missing something but it seems that var names repeating inside patterns are improperly compiled to distinct names. An example:

```
let [x, x] = [1, 1]
```

becomes:

```erl
[X, X1] = [1, 1]
```

, while it rather should be:

```erl
[X, X] = [1, 1]
```

**Comment by lpil** [comment]
This is by design. See #225 for how we intend to support equality testing in patterns.

**Comment by lpil** [comment]
Perhaps we should emit a warning or an error when using a named more then once in a pattern?

**Comment by zoldar** [comment]
@lpil out of curiosity, is there some write-up about this design aspect? Again, I'm probably out of my depth here and miss something obvious - I can't see though how ability to reassign the same var name goes against being able to match on the occurrences of the var name in a pattern? Unless that's about something else?

**Comment by lpil** [comment]
Not really, I just decided to go with the mainstream and require guards for equality. Under the hood Erlang converts duplicate names to equality guards I believe.
