### ISSUE TITLE
Calling a record constructor without arguments is accept in const definition

### ISSUE THREAD

**Issue by malbarbo** [gleam-lang/gleam#3730]
Using gleam 1.5.1 the following code compiles and run in both erlang and javascript backends:

```gleam
import gleam/io

pub type A {
  A(Int)
}

const a = A()

pub fn main() {
  io.debug(a) // outputs //fn(a) { ... }
}
```

**Comment by richard-viney** [comment]
Interesting, running the formatter converts

```gleam
const a = A()
```

to

```gleam
const a = A
```

I think the correct response from the compiler is an error, as no `Int` value was passed to the constructor for `A`. Does that seem right?

**Comment by giacomocavalieri** [comment]
Yeah I think it should be an error

**Comment by GearsDatapacks** [comment]
Wouldn't this be a breaking change though?

**Comment by lpil** [comment]
I think we can say this is a bug in the compiler as it doesn't conform to what the docs say. The formatter fixing it here is the saving grace as it means that people won't have this in their codebase, so we won't be breaking real code if we fix it.

**Comment by GearsDatapacks** [comment]
Good point. Formatter to the rescue!
