### ISSUE TITLE
Use `void` Instead of `undefined` for `Nil` in Generated Type Definition Function Return Types

### ISSUE THREAD

**Issue by han-tyumi** [gleam-lang/gleam#3742]
Gleam currently outputs `undefined` for `Nil` function return types.
This is probably fine in other cases, but it causes issues when using the generated type definition to write your backing function.
You could work around this by type casting or explicitly returning `undefined`, but this is not ideal.
I find this to be very valuable in keeping types in sync and would love if this awkwardness was addressed.

I believe the change would be made somewhere around here:
https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/javascript/typescript.rs#L594

Below is a simple example from within a new project named `console` with `typescript_declarations = true`.

#### `src/console.gleam`

```gleam
@external(javascript, "./console_ffi.mts", "clear")
pub fn clear() -> Nil
```

Make sure to run `gleam build` to generate the corresponding type definition file imported below.

#### `src/console_ffi.mts`

```ts
import type * as $console from "../build/dev/javascript/console/console.d.mts";

export const clear: typeof $console.clear = console.clear;
```

This produces the error:

> Type '() => void' is not assignable to type '() => undefined'.
> Type 'void' is not assignable to type 'undefined'.

**Comment by lpil** [comment]
Thank you for your input, but `Nil` is not `void`, it is a returned value. There is no concept of a non-returning function in Gleam.
