### ISSUE TITLE
Type inference limitation on anonymous functions with tuple parameters

### ISSUE THREAD

**Issue by malbarbo** [gleam-lang/gleam#3753]
Using gleam 1.5.1 on Linux, the code

```gleam
pub fn main() {
  let f: fn(#(Int)) -> Int = fn(a) { a.0 }
}
```

fails to compile and generates the error

```
error: Type mismatch
  ┌─ /src/main.gleam:2:38
  │
2 │   let f: fn(#(Int)) -> Int = fn(a) { a.0 }
  │                                      ^ What type is this?

To index into a tuple we need to know it size, but we don't know anything
about this type yet. Please add some type annotations so we can continue.
```

I'm  not sure if this is a bug or not, but considering that the example

```gleam
fn apply(f: fn(#(Int)) -> Int) {
  f(#(10))
}

pub fn main() {
  apply(fn(a) { a.0 })
}
```

works, I'm prone to consider it a bug.

**Comment by lpil** [comment]
It's not a bug, the inference algorithm works goes top to bottom, inside to outside. Context is passed forward from a function call to its arguments but that cannot be done generally. It you have a proposal for a new type inference design that would enable this please post it as a discussion. Thank you

**Comment by malbarbo** [comment]
Thank you for the clarification.
