### ISSUE TITLE
LSP: go to definiton does not work for parameters in anonymous functions

### ISSUE THREAD

**Issue by george-grec** [gleam-lang/gleam#3758]
**Steps to reproduce**
1. `$ gleam new bug_demo`
2. Add this to `src/bug_demo.gleam`:
```gleam
pub fn main() {
  let ad_hoc_wibble = fn(hello: Hello) { todo }

  Nil
}

type Hello {
  Hello
}

fn wibble(hello: Hello) {
  todo
}
```
3. In line 2: `let ad_hoc_wibble = fn(hello: Hello) { todo }` hover over `Hello` and "Go to definition"
4. Nothing happens

**Expected behavior**
The cursor should move to the definition of `Hello`. It works if you do the same thing but on the function `wibble` at the bottom.

I also noticed that documentation comments are not shown (at least in Zed) when hovering over `Hello` in `ad_hoc_wibble`.

**Comment by lpil** [comment]
Thank you
