### ISSUE TITLE
Documentation source links for packages in monorepos

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#3763]
### Discussed in https://github.com/gleam-lang/gleam/discussions/3760

<div type='discussions-op-text'>

<sup>Originally posted by **richard-viney** October 31, 2024</sup>
Generated source links in the docs currently expect the Gleam package being published to be at the root of the `repository` specified in `gleam.toml`. At the moment there doesn't appear to be any other config:

<img width="249" alt="image" src="https://github.com/user-attachments/assets/2ee446e7-a1ba-4ea7-9180-a9bdc519bd66">

Could we extend this with some kind of `path` or `prefix` option to allow for publication of Gleam packages stored in monorepos, i.e. ones that don't reside at the root of their repository?</div>

**Comment by richard-viney** [comment]
Fixed in https://github.com/gleam-lang/gleam/pull/3765.

Does this also need a small docs update e.g. at https://gleam.run/writing-gleam/gleam-toml/ ?

**Comment by lpil** [comment]
Thank you!

Yup, we need to update that too. I often forget unfortunately
