### ISSUE TITLE
Hovering over a pipeline suggests the "Add type annotation" code action

### ISSUE THREAD

**Issue by joshi-monster** [gleam-lang/gleam#3789]
(Gleam nightly)

Before:

```gleam
pub fn main() {
  5
  |> Ok
}
```

Hovering over the `5` suggests a "Add type annotation" code action.

After:

```gleam
pub fn main() {
  5: Int
  |> Ok
}
```

I inspected the AST a little bit since I was suspecting this being caused by my own changes doing something similar. `AddAnnotation::visit_typed_assignment` will be called on the generated `_pipe` variable inside of the pipeline, which then passes all the checks and adds a possible edit. ~ :purple_heart:

**Comment by GearsDatapacks** [comment]
Good catch! I wonder if there are other such generated variables which could cause this issue

**Comment by joshi-monster** [comment]
I want to introduce one for record updates! So it would be cool to find some nice solution here that works for my case as well Maybe a `AssignmentKind::Generated` variant?

**Comment by GearsDatapacks** [comment]
Ah yes, that could be good. I just looked at the list and hardcoded the ones that were relevant. I wasn't super happy with that though, your solution is much better!
