### ISSUE TITLE
Type Inference when Using Pipes in a Use Expression

### ISSUE THREAD

**Issue by portrik** [gleam-lang/gleam#3806]
Using pipes together with `use` does not infer the typing of the expression. Ideally, pipes would behave the same way everywhere, regardless whether they are used with `use` or any other expression.

```gleam
fn current_behaviour(value: String) -> Option(String) {
  let value = case value {
    "Valid" -> option.Some(value)
    _ -> option.None
  }

  use value <-
    value
    |> option.map
  // Type mismatch Expected type: fn(Option(String)) -> a Found type: fn(Option(b), fn(b) -> c) -> Option(c)

  value
}

fn ideal_behaviour(value: String) -> Option(String) {
  let value = case value {
    "Valid" -> option.Some(value)
    _ -> option.None
  }

  use value <-
    value
    |> option.map
  // String

  value
}
```

**Comment by GearsDatapacks** [comment]
This is not a bug. Pipes cannot be used in combination with `use`. I'm not sure if there are plans to add that in future, but there is no unintended behaviour here

**Comment by portrik** [comment]
Ah, I understand. I had expected the pipe and direct call to be equivalent.

I guess I can close the issue, since it is more of a nice-to-have than a bug?

**Comment by GearsDatapacks** [comment]
Yeah, or you can convert it into a feature request

**Comment by portrik** [comment]
I've updated the description and the title to better reflect a feature request 👍

**Comment by lpil** [comment]
Thank you for the proposal. Use does not have any special support for pipes today, it always desugars the same way for clarity. Adding a special case here would make it more complex and also make the resulting code harder to read, so we do not want to add this.
