### ISSUE TITLE
Unused constructors and imports reported for code targeting particular runtimes

### ISSUE THREAD

**Issue by Guria** [gleam-lang/gleam#3808]
Gleam compiler reports some entities like type constructors or module imports as unused based on target selected.

Examples:

# `plinth` 
If it presents as transitive dependency of module with non javascript target will report:

```
Compiling plinth
warning: Unused imported type
  ┌─ .../build/packages/plinth/src/plinth/javascript/compression_stream.gleam:1:34
  │
1 │ import gleam/javascript/promise.{type Promise}
  │                                  ^^^^^^^^^^^^ This imported type is never used

Hint: You can safely remove it.

warning: Unused imported type
  ┌─ .../build/packages/plinth/src/plinth/javascript/decompression_stream.gleam:1:34
  │
1 │ import gleam/javascript/promise.{type Promise}
  │                                  ^^^^^^^^^^^^ This imported type is never used

Hint: You can safely remove it.
```

While it seems [being used in javascript only targeted implementation](https://github.com/CrowdHailer/plinth/blob/170e6719970c51a382475a87ceab2c2dabdfbc3f/src/plinth/javascript/compression_stream.gleam#L6)

# `sketch`
Sketch has 2 separate constructor types that are chosen based on target used. So it always report one of them as unused while using with opposite target.

## target `erlang`
```
warning: Unused private constructor
   ┌─ .../build/packages/sketch/src/sketch.gleam:21:3
   │
21 │   JsCache(cache: style.Cache)
   │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^ This private constructor is never used

Hint: You can safely remove it.
```

## target `javascript`

```
warning: Unused imported module
  ┌─ /home/aleksei_gurianov/oss/eczaneleri/build/packages/sketch/src/sketch/internals/cache/state.gleam:4:1
  │
4 │ import gleam/otp/actor
  │ ^^^^^^^^^^^^^^^^^^^^^^ This imported module is never used

Hint: You can safely remove it.

warning: Unused imported module
  ┌─ /home/aleksei_gurianov/oss/eczaneleri/build/packages/sketch/src/sketch/internals/cache/setup.gleam:3:1
  │
3 │ import gleam/bool
  │ ^^^^^^^^^^^^^^^^^ This imported module is never used

Hint: You can safely remove it.

warning: Unused imported module
  ┌─ /home/aleksei_gurianov/oss/eczaneleri/build/packages/sketch/src/sketch/internals/cache/setup.gleam:5:1
  │
5 │ import gleam/list
  │ ^^^^^^^^^^^^^^^^^ This imported module is never used

Hint: You can safely remove it.

warning: Unused imported module
  ┌─ /home/aleksei_gurianov/oss/eczaneleri/build/packages/sketch/src/sketch/internals/cache/setup.gleam:6:1
  │
6 │ import gleam/otp/actor
  │ ^^^^^^^^^^^^^^^^^^^^^^ This imported module is never used

Hint: You can safely remove it.

warning: Unused imported module
  ┌─ /home/aleksei_gurianov/oss/eczaneleri/build/packages/sketch/src/sketch/internals/cache/setup.gleam:7:1
  │
7 │ import gleam/pair
  │ ^^^^^^^^^^^^^^^^^ This imported module is never used

Hint: You can safely remove it.

warning: Unused imported module
  ┌─ /home/aleksei_gurianov/oss/eczaneleri/build/packages/sketch/src/sketch/internals/cache/setup.gleam:8:1
  │
8 │ import gleam/result
  │ ^^^^^^^^^^^^^^^^^^^ This imported module is never used

Hint: You can safely remove it.

warning: Unused imported type
  ┌─ /home/aleksei_gurianov/oss/eczaneleri/build/packages/sketch/src/sketch/internals/cache/setup.gleam:9:22
  │
9 │ import sketch/error.{type SketchError}
  │                      ^^^^^^^^^^^^^^^^ This imported type is never used

Hint: You can safely remove it.

warning: Unused private constructor
   ┌─ /home/aleksei_gurianov/oss/eczaneleri/build/packages/sketch/src/sketch/internals/cache/setup.gleam:15:3
   │
15 │   PersistentCache(subject: Subject(state.Request))
   │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ This private constructor is never used

Hint: You can safely remove it.

warning: Unused private constructor
   ┌─ /home/aleksei_gurianov/oss/eczaneleri/build/packages/sketch/src/sketch/internals/cache/setup.gleam:16:3
   │
16 │   EphemeralCache(cache: style.Cache)
   │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ This private constructor is never used

Hint: You can safely remove it.

warning: Unused imported module
  ┌─ /home/aleksei_gurianov/oss/eczaneleri/build/packages/sketch/src/sketch.gleam:5:1
  │
5 │ import gleam/result
  │ ^^^^^^^^^^^^^^^^^^^ This imported module is never used

Hint: You can safely remove it.

warning: Unused private constructor
   ┌─ /home/aleksei_gurianov/oss/eczaneleri/build/packages/sketch/src/sketch.gleam:22:3
   │
22 │   BeamCache(cache: cache.Cache)
   │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ This private constructor is never used

Hint: You can safely remove it.
```

**Comment by Guria** [comment]
Irrelevant `unused` reports in CLI output first bring impression of unfinished work and then makes developers to be less attentive for such messages at all, so they could miss something important appeared.

**Comment by giacomocavalieri** [comment]
The compiler is right, those are unused when you're compiling for that specific target. The problem lies in those two packages using the `@target` annotation (and this is just one of the many reasons why it's highly discouraged!!)

I don't think we can do much about it, the problem should be addressed in those packages by not using the `@target` annotation

**Comment by Guria** [comment]
I am not yet so deeply familiar with this topic. I am not yet sure if above libraries could solve their problems wthout using `@target`.

I just try to highlight DX issue in "gleam ecosystem" here.
Now I have bunch of warnings that I have to ignore since they are outside of my responsibility.
If I keep them as is I will tend to just ignore the output at all.

By this issue I ask the community to work on this together.
cc @CrowdHailer @ghivert

**Comment by ghivert** [comment]
@giacomocavalieri is right there, there's nothing much we can do at the moment. The way to solve it is to avoid using `@target`. It's an open problem for Sketch, that led to some bugs exactly because of this. I'd really like to get rid of this, but at the moment I did not find a better way to handle this. I think Louis is working on this on we already talked about it though, and this could be solved in the future. 🙂

**Comment by lpil** [comment]
> I think Louis is working on this on we already talked about it though, and this could be solved in the future. 🙂

I'm not working on anything here presently. The official line is that you should not use `@target` and there's no support for any `@target` related problems.

In future we may have some support for different APIs per target within one package, but today in Gleam that is unsupported.

**Comment by ghivert** [comment]
> > I think Louis is working on this on we already talked about it though, and this could be solved in the future. 🙂
> 
> 
> 
> I'm not working on anything here presently. The official line is that you should not use `@target` and there's no support for any `@target` related problems.
> 
> 
> 
> In future we may have some support for different APIs per target within one package, but today in Gleam that is unsupported.

Oh, my bad here. I should have say it's something you know and you'll maybe address in the future. Sorry for the confusion. 

As I said, I understand `@target` should not be used, but I did not find a better way yet. I think I can give another try to find a better API for Sketch. 🙂

**Comment by lpil** [comment]
Yeah I think it'll be a challenge to do what Sketch and Lustre do today, but I am interested in exploring it in future!
