### ISSUE TITLE
Small inconsistency in target strings

### ISSUE THREAD

**Issue by GearsDatapacks** [gleam-lang/gleam#3826]
In Gleam v1.6.0-rc-1, the following code is valid and compiles:
```gleam
@target(js)
fn wibble() {
  todo
}
```
But this doesn't:
```gleam
@external(js, "./wibble.mjs", "wobble")
fn wibble() -> Nil
```

The shorthands, `js` and `erl` are allowed in various places such as `@target` and the `--target` flag for `gleam build` and `gleam run`. However, they are not allowed in `@external`. Small point, but I would expect the same set of values to be accepted in all such places.

**Comment by GearsDatapacks** [comment]
This inconsistency occurs because the parsing of `@target` uses `Target`'s [`FromStr` implementation](https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/parse.rs#L3288), but `@external` [explicitly matches](https://github.com/gleam-lang/gleam/blob/main/compiler-core/src/parse.rs#L3582) on the possible string values.

**Comment by lpil** [comment]
Let's deprecate the target one.
