### ISSUE TITLE
`let assert` could print the received value on failure

### ISSUE THREAD

**Issue by jquesada2016** [gleam-lang/gleam#3829]
For debugging, it would be great if `let assert` would panic with the value, rather than panicing with a generic "pattern match failed".

Perhaps using `string.inspect`?

**Comment by jquesada2016** [comment]
When you say running locally, do you mean within the Beam? Perhaps this issue only happens with JS, because I'm running a gleam app bundled with vite, and I only the the error message you posted above, without more details.

**Comment by lpil** [comment]
let assert raises a runtime error, it's up to whatever runtime you are using to print the error.

If you would like the tour and playground specifically to do something different then please open an issue there. Thank you!

**Comment by GearsDatapacks** [comment]
`let assert` does display the received value on JavaScript, although it's a bit harder to see than Erlang.

Erlang output:
```
runtime error: let assert

Pattern match failed, no pattern matched the value.

unmatched value:
  Error(2)

stacktrace:
  [...]
```
JS output, on nodejs:
```
Error: Pattern match failed, no pattern matched the value.
    [...]
  gleam_error: 'let_assert',
  module: 'testing_gleam',
  line: 22,
  function: 'main',
  fn: 'main',
  value: Error { '0': 2 }
  //     ^ Unmatched value
}
```

The playground however does not display this additional information. But as Louis said, that's not related to the Gleam language

**Comment by jquesada2016** [comment]
@GearsDatapacks how did you get that output? As I mentioned above, I'm running with the `vite` bundler, in other words, running in the browser.. Here's the output I'm getting, I might be missing it, as I'm legally blind.

Here, I have the stack trace expanded in the browser dev tools.

```
prelude.mjs:492 
 Uncaught Error: Pattern match failed, no pattern matched the value.
    at makeError (prelude.mjs:492:15)
    at init (app.mjs:84:11)
    at start (lustre.ffi.mjs:60:51)
    at lustre.mjs:107:20
    at Module.guard (bool.mjs:63:12)
    at Module.start (lustre.mjs:104:16)
    at main (quorvz.mjs:7:19)
    at index.html:15:5
makeError	@	prelude.mjs:492
init	@	app.mjs:84
start	@	lustre.ffi.mjs:60
(anonymous)	@	lustre.mjs:107
guard	@	bool.mjs:63
start	@	lustre.mjs:104
main	@	quorvz.mjs:7
(anonymous)	@	index.html:15
```

**Comment by jquesada2016** [comment]
Is it a bad idea to put the failed assertion's inspect representation within the error message itself, rather than rely on the specific runtime to hopefully display the value?

So perhaps, instead of" Uncaught Error: Pattern match failed, no pattern matched the value.", we could do:

"Uncaught Error: Pattern match failed, no pattern matched the value.
Assertion failed on `<inspect representation here>`."

**Comment by GearsDatapacks** [comment]
The information should be in the output somewhere, but I'm not sure the exact output format in the browser (it also depends on which browser you are using)

**Comment by lpil** [comment]
Again, it is up to whatever runtime you use to decide how to print any runtime errors. We have no control over how your system prints errors.

**Comment by jquesada2016** [comment]
Ok thanks, I'll leave it at that. I wish we could overwrite the assertion message, or add a label or something, much like with the `panic` keyword, like that I could make it show the assertion failure regardless of runtime.

**Comment by GearsDatapacks** [comment]
See #3807
