### ISSUE TITLE
validate package with multiple top level module names on publish

### ISSUE THREAD

**Issue by Guria** [gleam-lang/gleam#3834]
# Problem
Since package names don't necessarily match module names, library authors can inadvertently pollute global module names. This is especially problematic as it's easy to introduce multiple top-level modules in a single library.

Given that we have a single namespace for all dependencies, unresolvable transitive conflicts can arise for package consumers.

# Suggested Solution
Restrict packages from publishing more than one top-level module name unless explicitly defined in `gleam.toml` to indicate the library author's intent for potential valid use cases.

The CLI can optionally offer automatic `gleam.toml` updates. For stricter enforcement, we could require manual updates.

Related discussion:
https://discord.com/channels/768594524158427167/1281967484731265044/1281967484731265044

**Comment by lpil** [comment]
Thank you. Lets have it ask for confirmation as to whether it is correct when there's multiple top level names.

**Comment by Guria** [comment]
@lpil  we still need way to bybass this confirmation for publishing from CI environment

We have 2 options:
* explicitly define list of top level module names in `gleam.toml`
* have a cli argument `like --confirm-multiple-namespaces`

**Comment by Guria** [comment]
I see there is `--yes` option that confirms bunch of warnings. But I am just not sure it is ok to use it since it will not catch an explicit conset for ones who already set up automate publish.

Would like to hear your thoughts on it
