### ISSUE TITLE
Hint at tuple syntax when struggling with parenthesis

### ISSUE THREAD

**Issue by michaeljones** [gleam-lang/gleam#3836]
From a [discord interaction](https://discord.com/channels/768594524158427167/768594524158427170/1307378142440325181), the error message:
```
error: Syntax error
    ┌─ /home/michael/root/projects/contact-stack/src/contact_stack.gleam:134:34
    │
134 │       let urls = dict.from_list([("html", "https://www.contact-stack.com/friends/" <> int.to_string(row.id))])
    │                                  ^ This parenthesis cannot be understood here

Hint: To group expressions in gleam use "{" and "}".
```
Could benefit from the additional text

> and tuples are created with `#(` and `)`.

I don't know if that applies to all instances of that error but for me it was the issue and I think tuples without `#` are common enough in other languages that a hint is valid.

Louis seemed to think this was a reasonable suggestion.

**Comment by lpil** [comment]
Thank you
