### ISSUE TITLE
Provide actionable information when a package cannot be found with multiple packages and `gleam add`

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#3839]
I recently tried to add two packages to my project with the following command:

```
gleam add --dev globlin globin_fs
```

There's a typo here, it should say **globlin_fs**. This causes the package resolution to error out with the following error:

```
  Resolving versions
error: Dependency resolution failed

An error occurred while determining what dependency packages and
versions should be downloaded.
The error from the version resolver library was:

Unable to determine package versions: resource was not found
```

But the error does not tell me which package could not be found, presumably because we didn't consider the case where multiple packages may be added at once.

The DX is bad here, if I were adding many packages at once it might be a bit of a hassle to spot a subtle typo like this. It'd be great if the error message also told me what specific resource could not be found!

**Comment by lpil** [comment]
Sounds good, thank you
