### ISSUE TITLE
Notify of new major versions available when running `gleam update`

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#3843]
### Discussed in https://github.com/gleam-lang/gleam/discussions/3841

<div type='discussions-op-text'>

<sup>Originally posted by **hayleigh-dot-dev** November 17, 2024</sup>
As the ecosystem grows it is becoming more difficult to keep track of when packages are updated with new breaking changes. Short of just making a list of every dependency of every package I maintain and regularly checking for new versions, there is no real way to know if any of my dependencies have updated until a user opens an issue or I notice by happenstance.

One thing I _can_ do reliably is run `gleam update` in my packages from time to time. I'd like to propose that command also reports when any major version bumps are available, something like:

```
 % gleam deps update
  Resolving versions
Downloading packages
 Downloaded 2 packages in 0.01s
 
Hint: the following dependencies have new major versions available...

- wibble@2
- wobble@3
```

I think this would have a general benefit to the community:

- package consumers get notified when things have moved on and can make an informed decision to upgrade or not.
- package authors have an easier time broadcasting new changes, which is particularly impactful for "foundation" packages like `mist` or `lustre` where the community at large benefits from being on the same version.
- package authors can more-easily make sure they're not fragmenting the community by sticking on old versions of dependencies unnecessarily.</div>

**Comment by andho** [comment]
I'm giving this a try.

**Comment by andho** [comment]
It would be better if the output indicates the current (exact) version as well:
```bash
 % gleam deps update
  Resolving versions
  Downloading packages
  Downloaded 2 packages in 0.01s
 
Hint: the following dependencies have new major versions available...

wibble    @1.8.3  ->  @2.2.0
wobbling  @1.3.2  ->  @3.0.0
```

**Comment by lpil** [comment]
Yup it needs to show the latest versions.

Closing as duplicate of https://github.com/gleam-lang/gleam/issues/2583, thanks all
