### ISSUE TITLE
Hovering over a field, when destructuring records, should produce the field type

### ISSUE THREAD

**Issue by JosephTLyons** [gleam-lang/gleam#3847]
```gleam
use ParseData(is_positive, next_index, tokens) <- result.try(parse_data)
```

I would like to be able to hover over `tokens` and get its type, but currently, we get the overall `ParseData` record type on hover:

<img width="627" alt="SCR-20241118-mkiz" src="https://github.com/user-attachments/assets/1712ef73-ffbe-4b83-a56e-d400d755bd46">

Hovering on `ParseData` should produce `ParseData(Bool)` and hovering on tokens should produce `List(Tokens)`

**Comment by giacomocavalieri** [comment]
I can give this a try!

**Comment by giacomocavalieri** [comment]
Oh no please, go ahead!

**Comment by GearsDatapacks** [comment]
I should start writing comments when I'm looking into an issue

**Comment by giacomocavalieri** [comment]
Ah right, I'll mark it as ready for review!
