### ISSUE TITLE
Compilation fails when no digits are specified for exponent

### ISSUE THREAD

**Issue by GearsDatapacks** [gleam-lang/gleam#3856]
Currently, the compiler allows things like `1.5e`, with an empty exponent, as a valid float literal. However, this is not valid syntax in either erlang or javascript, and so the erlang compiler and javascript parser both throw errors if this is used.
I think we should disallow this syntax. From my understanding it would not be considered a breaking change as you cannot write valid code containing such syntax.

**Comment by lpil** [comment]
Oh dear! Thank you.
