### ISSUE TITLE
Removed or moved files are not tracked by the compiler

### ISSUE THREAD

**Issue by sbergen** [gleam-lang/gleam#3862]
How to reproduce:

Create project with the following main module:
```gleam
import module

pub fn main() {
  module.hello()
}
``` 

add `src/module.gleam` as:
```gleam
import gleam/io

pub fn hello() {
  io.println("Hello!")
}
```

Now, from the command line, you get the following unexpected output:
```
$ gleam run
  Compiling unmovable
   Compiled in 0.26s
    Running unmovable.main
Hello!

$ rm src/module.gleam 

$ gleam run
   Compiled in 0.01s
    Running unmovable.main
Hello!
```

Doing a `gleam clean && gleam run` will make things work normally again, giving
```
error: Unknown module
  ┌─ <omitted>/unmovable.gleam:1:1
  │
1 │ import module
  │ ^^^^^^^^^^^^^
```

I'm running Gleam version 1.6.1, in Ubuntu 24.04 in WSL 2 on Windows 11.

**Comment by sbergen** [comment]
I did a bit of poking around at the compiler, and found that if I pass `existing_modules` to `PackageLoader`, and then do
```
for (_, deps) in deps.iter() {
    for dep in deps {
        if !inputs.contains_key(dep) && !self.existing_modules.contains_key(dep) {
            tracing::error!(missing = ?dep, "Module missing:");
        }
    }
}
```

after [this line](https://github.com/gleam-lang/gleam/blob/95239b9064033ee4b4fd02212f25d107bceaafe6/compiler-core/src/build/package_loader.rs#L127), I'll get the missing module logged.

**Comment by bentomas** [comment]
I tend to constantly reorganize my code (don't know what to say 🤷‍♂️) and this is constantly happening to me. I have to `gleam clean` a lot.

**Comment by sbergen** [comment]
I was thinking about this a bit more, and perhaps storing package metadata (similarly to module metadata) with a list of modules would be a better way to approach fixing the issue? This way we could just check that list against the source files to figure out which modules have been removed, and mark them as stale.

**Comment by lpil** [comment]
Oh dear! I thought we fixed this. Thanks folks
