### ISSUE TITLE
SAAS ready: Elixir-Flow-like and/or gen-stage-like and/or broadway-like library

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#3863]
https://discord.com/channels/768594524158427167/1308359897884397578/1308363351511928833
https://discord.com/channels/768594524158427167/1308359897884397578/1308382001526472765

https://hexdocs.pm/flow/Flow.html
https://hexdocs.pm/gen_stage/GenStage.html
https://hexdocs.pm/broadway/introduction.html

**Comment by GearsDatapacks** [comment]
Shouldn't this be in https://github.com/gleam-lang/awesome-gleam?
