### ISSUE TITLE
LSP Code Action: Convert inexhaustive `let` to `case`

### ISSUE THREAD

**Issue by GearsDatapacks** [gleam-lang/gleam#3868]
For example, you have this code:
```gleam
pub type Wibble {
  Wibble(wibble: Int)
}

pub fn main(wibble: Wibble) {
  let Wibble(inner) = wibble
  do_something_with(inner)
}
```
But then you change the `Wibble` type:
```gleam
pub type Wibble {
  Wibble(wibble: Int)
  Wobble(wobble: Int)
}
```
The `let` expression now fails to compile. It could be useful to have a code action to turn:
```gleam
let Wibble(inner) = wibble
```
into:
```gleam
let inner = case wibble {
  Wibble(inner) -> inner
  _ -> todo
}
```
This would be very similar to the [code action to convert](https://github.com/gleam-lang/gleam/blob/31966a0b3503d9429cc016d29b1ba88569e22fc6/compiler-core/src/language_server/code_action.rs#L299) `let assert` to `case`, except it would only be offered if the `let` expression is not exhaustive.

**Comment by giacomocavalieri** [comment]
I love the idea!

**Comment by GearsDatapacks** [comment]
I can work on this. It should be pretty trivial to adapt the existing code action to work in this case too
