### ISSUE TITLE
Using `use` together with pattern matches compiles, when it shouldn't

### ISSUE THREAD

**Issue by sbergen** [gleam-lang/gleam#3879]
The following code compiles, when it shouldn't:
```gleam
import gleam/io
import gleam/result

pub fn main() {
  use <<var:8>> <- result.try(wibble())
  Ok(io.debug(var))
}

fn wibble() -> Result(BitArray, Nil) {
  Ok(<<42, 0>>)
}
```

On Erlang, it will result in a runtime error, while on JS, it will just print `42`.

Gleam version 1.6.1

**Comment by lpil** [comment]
Thank you for the report. This should not compile, the exhaustiveness checker should reject it.

Interestingly the runtime behaviour is different too across each target.

**Comment by sbergen** [comment]
I found out that this does not only affect bit arrays, but pretty much any kind of pattern match that _should_ have exhaustiveness checking. The most dangerous case I could come up with is this actually printing `42` on JS:
```gleam
import gleam/io
import gleam/result

pub fn main() {
  use Ok(var) <- result.try(wibble())
  Ok(io.debug(var))
}

fn wibble() -> Result(Result(Int, Int), Nil) {
  Ok(Error(42))
}
```

**Comment by GearsDatapacks** [comment]
I'll look into this

**Comment by GearsDatapacks** [comment]
Ah! Looks like I introduced this bug when adding the `Generated` variant to `AssignmentKind` in #3790. I assumed that generated assignments would always be valid but it seems `use` was relying on it for exhaustiveness checking. I'll open a PR
