### ISSUE TITLE
Error when saving file

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#3882]
I'm trying the highly version of the compiler and every time I save a file this error pops up in the editor (I'm using Zed, I've tested and the same happens in VSCode).
```txt
An error occurred while trying to delete this directory:

    <path_to_src>/src/<file_im_saving>.gleam
```
By bisecting it looks like this is the first bad commit: <https://github.com/gleam-lang/gleam/commit/f6fc09786231f1225a34bfb47e5d4c5b24a1a61c>

**Comment by lpil** [comment]
Oh dear! Thank you.

**Comment by lpil** [comment]
@PgBiel This error is from your commit, can you see what the problem is? You'll be the most familiar with this area!

**Comment by PgBiel** [comment]
Is there more information on this error? Any relevant output from `GLEAM_TRACE=1`?

**Comment by lpil** [comment]
None that I can see.

**Comment by PgBiel** [comment]
Completely superficial analysis here, but I think this could be a potential cause:
https://github.com/gleam-lang/gleam/blob/0b2cf1b9d7ec9806aec0128bc02201ce495475ff/compiler-core/src/language_server/files.rs#L53-L55

Seems like existing code assumes that `delete_directory` will also delete files if asked. A simple `is_directory()` check to delete either a file or a directory would fix it.

**Comment by lpil** [comment]
Ah yes!! Thank you @PgBiel !
