### ISSUE TITLE
`gleam remove` requires a working network connection

### ISSUE THREAD

**Issue by joshi-monster** [gleam-lang/gleam#3887]
While on a train, I noticed that I cannot remove packages while being offline:

```txt
$ gleam remove gleam_stdlib
Resolving versions
error: Dependency resolution failed

An error occurred while determining what dependency packages and
versions should be downloaded.
The error from the version resolver library was:

Unable to determine package versions: error sending request for url
(https://repo.hex.pm/packages/gleeunit)
```

I can't think of a case where deleting a package would change the resolved versions of the other installed packages, since all their versions are locked in the manifest anyways. Dependencies are also recorded in the manifest, so removing transitive packages should also be possible without calling hex again. ~ :purple_heart:

**Comment by GiregL** [comment]
It looks like the remove command first read the dependences from `gleam.toml`, removes the given ones, rewrites the `gleam.toml` file and then downloads again the new dependencies to generate a new manifest.

Can't we provide an "offline" option that could update the manifest locally ?

**Comment by GiregL** [comment]
I'm not sure to understand, `gleam remove` already uses the network ( `compiler-cli/src/dependencies.rs#download`, used by `remove.rs#command`)

**Comment by lpil** [comment]
This ticket is for removing the network usage.
