### ISSUE TITLE
Alternative patterns in case expression

### ISSUE THREAD

**Issue by zjhmale** [gleam-lang/gleam#391]
```rust
pub rec fn fibonacci(n) {
    case n {
        0 | 1 -> 1
        _ ->  fibonacci(n -1) + fibonacci(n - 2) 
    }
}
```

**Comment by lpil** [comment]
Thanks for the suggestion! I like this idea but I have some thoughts:

How would this work with multiple subjects? `case a, b { ....` 

How would this work with guards? #225

**Comment by zjhmale** [comment]
what about the following design?

* multiple subjects:

```rust
case a, b {
   1, 2 | 2, 3 -> "case1"
   _ -> "case2"
}
```

* guards:

```rust
case x {
    1 | 2 if some_predication -> "case1"
    _ -> "case2"
}
```

**Comment by lpil** [comment]
I like it :)

```rust
case x {
    1 | 2 if some_predication -> "case1"
    _ -> "case2"
}
```

For this one does the guard clause apply to 1 and 2? That seems to make more sense to me.

**Comment by zjhmale** [comment]
more general

```rust
case list {
    [h] | [h, t] if h == 1 -> "case1"
    _ -> "case2"
}
```

looks good?
