### ISSUE TITLE
I can't run gleam with the beam

### ISSUE THREAD

**Issue by OdedYanovich** [gleam-lang/gleam#3914]
I have followed the Lustre's Quickstart guide and every time i run it (gleam run -m lustre/dev start) it returns:

  Compiling argv
escript: exception error: no case clause matching {error,
                                          {no_translation,unicode,latin1}}
  in function  gleam@@compile_erlescript1732886578465401__1155:compile_package_loop/0 (C:\project_n\build\dev\erlang\argv_gleam_artefacts\gleam@@compile.erl, line 10)
  in call from escript:run/2 (escript.erl, line 904)
  in call from escript:start/1 (escript.erl, line 418)
  in call from init:start_it/1 (init.erl, line 1546)
  in call from init:start_em/1 (init.erl, line 1521)
  in call from init:do_boot/3 (init.erl, line 1210)
error: Shell command failure

There was a problem when running the shell command escript.

I tried to run a default project and the same thing happened, i can run js projects.

My erlang version is:
erl -v
Erlang/OTP 27 [erts-15.1.2] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [jit:ns]

Eshell V15.1.2 (press Ctrl+G to abort, type help(). for help) 

I use windows 11

**Comment by joshi-monster** [comment]
Hi! Could you please provide some more information on where and how you're running things?

- Which terminal emulator?
- Which shell?
- Inside WSL or not?
- What's the currently active code page?
- Do you have this experimental flag in Windows active where they use 65001 as the default codepage globally?

Thank you!! :purple_heart:

**Comment by joshi-monster** [comment]
wait. did you copy-paste the entire error? `\project_n\build\dev\erlang\argv_gleam_artefacts\gleam@@compile.erl` there should be a backslash between `argv` and `_gleam_artefacts`

**Comment by OdedYanovich** [comment]
I am running it in vscode's powershell, i don't recall ever changing the settings on windows active

**Comment by joshi-monster** [comment]
What about my other questions? Do you run vscode in windows or in WSL?

I tried it in host vscode powershell on a default installation of windows without issues.

**Comment by OdedYanovich** [comment]
I also installed vscode in windows in the usual way.
Just to be sure, i run the project with regular powershell and cmd, to the same results.

**Comment by OdedYanovich** [comment]
The way i downloaded Rebar3 was weird, could it be the problem?

**Comment by joshi-monster** [comment]
No, that should not matter. Do you maybe have non-ascii characters in the file path to your project? I think I found an issue there.

**Comment by OdedYanovich** [comment]
Yes! you did it, the complaint is gone. I can't imagine how, considering that i couldn't find information about escripts, but i can finally move past this.
