### ISSUE TITLE
vs code extention dosen't offer renaming functionality

### ISSUE THREAD

**Issue by OdedYanovich** [gleam-lang/gleam#3915]
In most programming languages, when i press F2, I get an option to rewrite the name of the element and it will change every instance of the name in the project. I would like to have it in Gleam.

**Comment by GearsDatapacks** [comment]
Thanks for the suggestion! There are already several issues regarding this feature. It's a tricky one, as it requires a program call graph to implement, which is something we don't have yet

**Comment by OdedYanovich** [comment]
Thanks you for informing me, and for your contributions in general.
