### ISSUE TITLE
Expand function capture code action

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#3938]
An action that converts a function capture syntax sugar into the anonymous function syntax
```gleam
pub fn main() {
  list.map(_, run)
}
```

```gleam
pub fn main() {
  fn(value) { list.map(value, run) }
}
```

**Comment by giacomocavalieri** [comment]
The tricky bit is figuring out a name that won't shadow existing variables used inside the anonymous function's body:
```gleam
list.map(_, value)
// fn(value_1) { list.map(value_1, value)}
```

**Comment by lpil** [comment]
Traversing the inner expression and adding all the referenced variables to a set doesn't sound too tricky, I think we could do that.
