### ISSUE TITLE
Compiler error in incremental builds even though code is valid, clean build succeeds

### ISSUE THREAD

**Issue by Aaronmacaron** [gleam-lang/gleam#3947]
In my project, I get compiler errors in one specific file when building incrementally. The error messages don't make sense to me and if I `gleam clean` and then rebuild the errors are gone even though I didn't modify the code.

I admit that the code that results in this bug is kind of weird and not exactly beautiful. I refactored my project and now the errors no longer appear, still I think this probably shouldn't happen in the first place.

## Steps to reproduce

- Download and unpack the reproduction project: [compiler-bug-reporduction-project.zip](https://github.com/user-attachments/files/17997176/compiler-bug-reporduction-project.zip)
- `gleam build --target javascript`, this should work as expected
- Now add some insignificant change to the file `src/wizard.gleam`, for example add `let foo = 0` somewhere, it's not important what change it is exactly
- Now, `gleam build --target javascript` fails for me
- After `gleam clean` it works again

## Versions

- **gleam:** 1.6.2 (issue was already present back in 1.5.x)
- **erlang:** Erlang/OTP 27 [erts-15.1.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
- **MacOS:** 14.6.1
- **rebar3:** 3.24.0 on Erlang/OTP 25 Erts 13.2.2.1
- I manage gleam, erlang and rebar3 through Nix

## Logs

These are the logs for the failing command and for the successful build after `gleam clean`.

- [log_error.txt](https://github.com/user-attachments/files/17998308/log_error.txt)
- [log_success.txt](https://github.com/user-attachments/files/17998310/log_success.txt)

**Comment by lpil** [comment]
Oh dear! That is bad. Thank you for the report
