### ISSUE TITLE
Latest source tarball builds previous version

### ISSUE THREAD

**Issue by Yewzir** [gleam-lang/gleam#3952]
I've come to notice that the latest source tarball for 1.6.3 contains the assets to build the previous version still.

![image](https://github.com/user-attachments/assets/0c4e7b6e-7037-41c9-8f86-74b07d6d4e71)

**Comment by GearsDatapacks** [comment]
It's not building the previous version; just looks like Louis forgot to update the version number in `Cargo.toml`
