### ISSUE TITLE
Spelling mistake in mod package_name

### ISSUE THREAD

**Issue by jknight-developer** [gleam-lang/gleam#3955]
Got an error while trying to edit a package name and spotted a spelling mistake in the error output string.
The spelling mistake is also repeated in the tests for this file.

```
// compiler-core/src/config.rs
let error =
    "Package names may only container lowercase letters, numbers, and underscores";
Err(serde::de::Error::custom(error))
```

**Comment by GearsDatapacks** [comment]
This issue can be closed now as the relevant PR has been merged

**Comment by lpil** [comment]
Thank you
