### ISSUE TITLE
Explicity type parameter is handled different from implicity type parameter

### ISSUE THREAD

**Issue by malbarbo** [gleam-lang/gleam#3960]
The following code compiles fine:

```gleam
fn a() {
  let id = fn(x) { x }
  let f: fn(Int) -> Int = id
}

fn b() {
  let id: fn(Int) -> Int = fn(x) { x }
  let f: fn(Int) -> Int = id
}
```

but adding type parameter to `id` generates an error in the second case:

```gleam
fn c() {
  let id = fn(x: a) { x }
  let f: fn(Int) -> Int = id
}

fn d() {
  let id: fn(Int) -> Int = fn(x: a) { x } // here
  let f: fn(Int) -> Int = id
}
```

The error is:

```
error: Type mismatch
   ┌─ /src/main.gleam:17:28
   │
17 │   let id: fn(Int) -> Int = fn(x: a) { x }
   │                            ^^^^^^^^^^^^^^

Expected type:

    fn(Int) -> Int

Found type:

    fn(a) -> a
```

I'm using gleam version 1.6.2

**Comment by lpil** [comment]
In your second one you have annotated the function as `fn(a) -> a` in the let binding but `fn(Int) -> _` in the function literal itself. This is a type error, because `forall a` is not the same as unbound type variable `'a`.

**Comment by malbarbo** [comment]
Thanks for your answer, but I'm not sure if I understand your point correctly (I'm sorry, English is not my native language). Would it be possible for you to complement your point? I would be very grateful for that.

I'll try to make my point clear:

```gleam
fn c() {
  let id = fn(x: a) -> a { x }
  let f: fn(Int) -> Int = id
}

fn d() {
  let id: fn(Int) -> Int = fn(x: a) -> a { x } // here
  let f: fn(Int) -> Int = id
}
```

If the `c` function `id` has type `fn(a) -> a`. `id` can be assigned to `f`, which has type `fn(Int) -> Int`.

In the `d` function, the literal function has type `fn(a) -> a`, it cannot be assigned to `f`.

Why a named function with type `fn(a) -> a` can be assigned to a variable with type `fn(Int) -> Int` and a function literal with type `fn(a) -> a` cannot?

**Comment by malbarbo** [comment]
Is this the same issue as [this](https://github.com/gleam-lang/gleam/discussions/3779)?
