### ISSUE TITLE
Git release tag v1.6.3 moved after the tagging?

### ISSUE THREAD

**Issue by stefanb** [gleam-lang/gleam#3962]
👋 Hey,

We noticed during a rebuild in https://github.com/Homebrew/homebrew-core/pull/200200 that the source checksum of the last release v1.6.3 has changed since last build in https://github.com/Homebrew/homebrew-core/pull/199889

This is usually happens when a release tag is moved to a different commit, which was indeed observed in https://github.com/gleam-lang/gleam/actions/workflows/release.yaml
![image](https://github.com/user-attachments/assets/deeeffbc-b801-44e7-81fa-ddf409913c48)

@lpil, or other maintainers, can you please confirm this was the case and was done intentionally, so that we can move on with fixing it in
* https://github.com/Homebrew/homebrew-core/pull/200230

Thanks!

**Comment by lpil** [comment]
That's right! 1.6.3 was released with the string "1.6.2" as the version, so it was patched and release builder was re-run. Sorry for the confusion!

**Comment by stefanb** [comment]
Thank you!
