### ISSUE TITLE
gleam/list.sort() incites racism, white supremacy

### ISSUE THREAD

**Issue by IroncladDev** [gleam-lang/gleam#3979]
## Description

Using the `list.sort()` method imported from `gleam/list` to sort a list of emojis with different skin tones, it always deprioritizes minorities.

<img width="422" alt="Screenshot 2024-12-12 at 9 02 07 AM" src="https://github.com/user-attachments/assets/c67f5997-0619-4009-aca7-5c4cf4407bfd" />

I was experimenting with the online runner at https://tour.gleam.run, so I assume I am using the latest version of Gleam and that there are no hardware-specific issues.

**Comment by lpil** [comment]
Hello! We don't have any control over UTF-8, you would need to open an issue with the Unicode consortium. Thank you

**Comment by donglabs** [comment]
Emoji are represented by a series of code points which combined form a grapheme. `Gleam/list.sort()` sorts by comparing graphemes. If this were to be handled at the Unicode consortium level, all of the example emojis above would need to be represented by identical graphemes, which is obviously impossible.

There is no way to solve this by modifying unicode. `Gleam/string.compare() would need to report them the problematic graphemes as equal.
