### ISSUE TITLE
Difference in armstrong number calculation in js vs erlang 

### ISSUE THREAD

**Issue by Unaimend** [gleam-lang/gleam#3980]
```
gleam 1.6.2
Erlang/OTP 27 [erts-15.1.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]
node: v20.9.0
Description:	Ubuntu 22.04.2 LTS
```

```
import gleam/float
import gleam/result
import gleam/list
import gleam/int
import gleam/io
import gleam/string
pub fn dbg(x) {
  io.debug(x)
  x
}

pub fn f(l: List(Int), p: Int) -> Result(List(Int), Nil)  {
  l |> list.map(fn(n) { int.power(n, of: p |> int.to_float) |> result.map(float.round)}) |> result.all 
}

pub fn is_armstrong_number(number: Int) -> Bool {
  let r = number |> int.to_string |> string.to_graphemes 
  case r |> list.map(int.base_parse(_, 10)) |> result.all |> result.try(f(_, r |> list.length)) |> dbg |> result.map(int.sum) |> dbg |> result.map(fn(x) { x == number})  {
    Ok(True) -> True
    _ -> False
  }

}

pub fn main() {
    io.debug(is_armstrong_number(
      186_709_961_001_538_790_100_634_132_976_990,
    ))
}
```
Run as with target=js -> Error(Nil), run with target=erlang -> A result (For this big a number there is some problem with the pow. function and float stuff). So the number is wrong regardless

I was already informed that this is most likely due to platform differences, but IMHO, it would be good that the platforms behave as close as possible regarding such basic operations. But maybe that's impossible/not a goal of gleam :). 

(ins)(gleam) td:armstrong-numbers $ GLEAM_LOG=trace. I did set the env. variable like this and ran `gleam run` but nothing changed :'(.

Thank you for your time 
If this is indeed a bug I could try to investigate it some more

**Comment by lpil** [comment]
Hello! That number is too large for JavaScript to represent without losing precision. You'll need to use a big-int library to represent it accurately on JavaScript runtimes.
