### ISSUE TITLE
Win10 Fatal - Unknown CA

### ISSUE THREAD

**Issue by OnorioCatenacci** [gleam-lang/gleam#402]
I'm not sure if this Windows 10 or if it's the fact that I'm trying this from a work machine (which is behind a firewall).  The error message looks like it may be somehow related to a revocation issue which Rust has on Windows (https://github.com/rust-lang/cargo/issues/2464#issuecomment-279580096)

=INFO REPORT==== 2-Mar-2020::16:31:33.523000 ===
TLS client: In state certify at ssl_handshake.erl:1370 generated CLIENT ALERT: Fatal - Unknown CA

===> Failed to update package rebar_gleam from repo hexpm
===> Plugin rebar_gleam not available. It will not be used.
===> Verifying dependencies...
===> Failed to update package gleam_stdlib from repo hexpm
=INFO REPORT==== 2-Mar-2020::16:31:33.801000 ===
TLS client: In state certify at ssl_handshake.erl:1370 generated CLIENT ALERT: Fatal - Unknown CA

===> Package not found in any repo: gleam_stdlib 0.6.0

I have another Windows 10 box which is not behind a corporate firewall and if I can I will see if I can reproduce the issue on that one.

## System and architecture

Elixir version:     1.9.4
Erlang/OTP version: 21
ERTS version:       10.3
Compiled for:       win32
Schedulers:         8
Schedulers online:  8

## Memory

Total:              18 MB
Atoms:              323 KB
Binaries:           397 KB
Code:               6 MB
ETS:                434 KB
Processes:          4 MB

I'm posting this since you asked people to test on Win10 (I have Elixir installed which is where I got the versions of everything).

**Comment by lpil** [comment]
This error is originating from rebar3 rather than Gleam. It looks like it's unable to find a suitable CA in order to connect to the Hex package registry over HTTPS. Why that is the case I couldn't say! I think an issue will need to be opened over at https://github.com/Erlang/rebar3

**Comment by OnorioCatenacci** [comment]
For what it's worth, it seems to be some sort of issue with my corporate
laptop.  Tried it on a different Windows laptop and it works fine.  I'm
planning to see if I can exercise Gleam on Windows a bit. If I find
something Gleam-related I'll share it.

I don't know what kind of momentary lapse of sense I had not to realize
that eunit message should have been reported to the Rebar3 folks.  Here's
hoping I don't repeat dumb mistakes :)

**Comment by lpil** [comment]
Thank you! I'm sure you've not made a dumb mistake, CAs and corporate laptop see notoriously tricky
