### ISSUE TITLE
Unimplemented / TODO keyword

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#403]
Provide a keyword that signifies that code is unfinished. It will type check but crash at runtime.

In Scala this is called `???`.
In Haskell this is called `unimplemented` and it exists in the prelude.

**Comment by fuelen** [comment]
I guess you mean `undefined` from Haskell.
AFAIK it is just a shorthand for throwing exception.

However, there is another feature that solves the same or similar problem, but it is more powerful - typed holes.
Compiler provides nice hints trying to automatically infer type of the hole. In Haskell, holes start with `_`, so hole can be written simply as  `_` or `_named-hole`. In Idris holes start with `?`, they are always named and can be called from REPL. It would be nice to have this in gleam too :)

Read more about holes: [Idris](http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#holes), [purescript](https://github.com/paf31/24-days-of-purescript-2016/blob/master/23.markdown#typed-holes), [haskell](https://downloads.haskell.org/~ghc/7.10.1/docs/html/users_guide/typed-holes.html)

**Comment by lpil** [comment]
Thank you for the correction RE Haskell's naming

I would be interested in supporting holes later but I think would like to get this simpler feature in first.

**Comment by lpil** [comment]
I like the user experience of the Elm debug Todo function but I do not want the standard library to have any special back doors into the compiler as in Elm. The special status of core Elm code is potentially frustrating to the user who attempts to replicate it, so Gleam will use a language level construct instead (a keyword).
