### ISSUE TITLE
One-line type aliases

### ISSUE THREAD

**Issue by JosephTLyons** [gleam-lang/gleam#4101]
The gleam formatter always breaks type aliases into 2 lines, no matter how short the line is:

Before formatting:

```gleam
type A = Int
```

After formatting:

```gleam
type A =
  Int
```

https://github.com/gleam-lang/gleam/pull/2929 introduced the ability to keep pipes in a single line, if the chain was short enough. I think a similar rule should be introduced for type aliases. The formatter could then break the alias into multiple lines if it exceeded a certain length.

**Comment by lpil** [comment]
This is the intended behaviour.
