### ISSUE TITLE
Gleam Operator Precedence

### ISSUE THREAD

**Issue by lemorage** [gleam-lang/gleam#4108]
In C, there is an exhausted table listing all the precedence among different operators. I wonder are there any docs mentioning this in Gleam?
| **Gleam Operators**             | **Examples**                          |
|--------------------------|---------------------------------------|
| **Comparison Operators**  | `==`, `!=`, `>`, `> .`, `>=`, `>=.`, `<`, `<.`, `<=`, `<=.` |
| **Logical Operators**     | `&&`, `\|\|`                            |
| **Arithmetic Operators**  | `+`, `+ .`, `-`, `- .`, `*`, `* .`, `/`, `/ .`, `%` |
| **Concatenation Operator**| `<>`                                  |
| **Pipe Operator**         |  `\|>`                           |

<br/>
I’m asking about this because the following code confuses me. I am using Blocks to print out the expected output. But we do not know when we should use Blocks in advance, and the underlying reason is that we’re unsure about the precedence between `<>` and `|>`.

```gleam
import gleam/io
import gleam/int

pub fn main() {
  let year = 2024
  "current year: " <> year |> int.to_string() |> io.debug() // output: "2024"
  { "current year: " <> year |> int.to_string() } |> io.debug() // after adding Blocks, output: "current year: 2024"
}
```

**Comment by lpil** [comment]
There's no specification like document for Gleam. We would like to have this in future, but there's no capacity for this presently as we are focusing on highest impact work while we have so little funding. Thank you
