### ISSUE TITLE
Incompatible Erlang OTP and Elixir versions in the generated test workflow

### ISSUE THREAD

**Issue by jrstrunk** [gleam-lang/gleam#4113]
Hello! Running `gleam new` and then uncommenting the Elixir line in test.yml produces a github workflow that will not run because Erlang OTP v27 is not supported by Elixir v1.15. Is there any reason we should not update the Elixir version for the test workflow to the most recent version, v1.18.1? I can confirm that Elixir 1.18.1 works with the github test runner.

**Comment by lpil** [comment]
No reason! Maybe we should change the Elixir version to just `1`?

**Comment by jrstrunk** [comment]
Sure! Users can always change it later if they need a specific version, but that should hopefully keep this from happening again as the OTP version is updated. I confirmed the test runner works with just version `1` being specified, I'll go ahead and open a PR for it.
