### ISSUE TITLE
Formatter: function captures in `list.fold` mess up with formatter

### ISSUE THREAD

**Issue by ghivert** [gleam-lang/gleam#4121]
Hi!
I'm not 100% sure it's an issue, but I think it's good to discuss about it.
Currently, a `list.fold` without function capture is properly formatted, like this:

```gleam
// Formatting with no function capture
pub fn example() {
  list.fold(my_list, t, fn(a) {
    io.print("Not meh")
    io.print("Not meh")
  })
}
```

Adding a function capture (`_`) seems to mess up with the formatter:

```gleam
// Formatting with function capture
pub fn example() {
  list.fold(
    my_list,
    _,
    fn(a) {
      io.print("Meh")
      io.print("Meh")
    },
  )
}
```

I'm not sure it's a desired behaviour, because using a function capture in `list.map` does not changes the formatting:

```gleam
// Formatting with function capture
pub fn example() {
  list.map(_, fn(a) {
    io.println("example")
    io.println("exmaple")
  })
}
```

I think for consistency, everything should be formatted on one line while it's possible.

**Comment by lpil** [comment]
Agreed, thank you.
