### ISSUE TITLE
Support custom deps location

### ISSUE THREAD

**Issue by artman41** [gleam-lang/gleam#4123]
To support using gleam as a language for a sub-app of an existing build system (i.e. erlang.mk), it'd be useful to be able to set the directory which dependencies are downloaded into so that they can be managed at a single level (i.e. in an umbrella application)

**Comment by lpil** [comment]
Could you expand on this please? Gleam only ever downloads a package release once per computer and otherwise uses the global cache.

**Comment by artman41** [comment]
Talking purely erlang here but I'm sure it'd also mesh with Javascript build systems like npm;

With build systems like erlang.mk, there is a default path of `./deps` as the download location for dependencies. For rebar, it is `_build/default/`. Both of these are customisable to allow both build systems to work in tandem, directing to the same dependencies preventing dependency pollution.

The issue I'm finding with Gleam is that the packages are _always_ built under `build/dev/erlang/$lib/ebin` which forces a lot of jank in terms of how to rig the build systems together

Ideally, the 'compiled' files would be able to have their output location specified or, at the very least, the source files of the defined `target` within the `gleam.toml` downloaded to a location also defined within the `gleam.toml`.

My issue is mainly revolving around trying to retro-fit gleam into existing build systems so that gleam can be used without requiring a total overhaul of the project structure.

An alternative to this could be the public hex repo (or #2817 in situations where a public hex repo is unavailable) but it would only allow 'merging' of the systems where the gleam library was independent of a larger app and could be pulled in as its own dependency.

What I am currently trying to work towards is developing in an 'umbrella application' style where components of a shared system are compiled within the same project to form a single application, allowing for parts of an existing Erlang system to be rewritten as Typed gleam and built using existing processes.

If this is not something envisioned for Gleam, I'll close the issue 😄 
I'd like to start using the language to better some systems but the struggles with merging it with existing systems is making it difficult to pursue

**Comment by lpil** [comment]
Ah, I see! Thank you.

`gleam build` is not a suitable API for use by other build tools, what Erlang make should use is `gleam compile-package`.
