### ISSUE TITLE
0.7.1 reports itself as 0.7.0

### ISSUE THREAD

**Issue by NobbZ** [gleam-lang/gleam#414]
The `Cargo.toml` of the commit tagged as `0.7.1` still contains `0.7.0` as version.

Will this be corrected by a re-release of 0.7.1 or is this a `wont-fix`?

I need to know before I bump Arch and NixOS packages to avoid future hash mismatches.

**Comment by lpil** [comment]
Thanks for the report. I'll re-release this version

**Comment by lpil** [comment]
Please try again now, thank you.

**Comment by NobbZ** [comment]
Seems to be fine now!

Thanks!

**Comment by lpil** [comment]
Thank you :)
