### ISSUE TITLE
Support larger Int literals

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#425]
Currently we are limited to i64, which can overflow easily.

We could store it as a string as we don't actually use the Int value in the compilation process.

**Comment by theAnnie** [comment]
@lpil can I take a look at this?

**Comment by lpil** [comment]
Yes please! :) Let me know if you need any pointers at all

**Comment by theAnnie** [comment]
> Yes please! :) Let me know if you need any pointers at all

@lpil So I've created PR, although I need to change all the Ints in test like 1 -> "1" and it does not seems to be right... Should not I parse it somewhere from String to Int back again?

**Comment by lpil** [comment]
Great job! Yes the tests will need to be updated too. I may be able to help with some Vim regex if that would be useful.

`"1"` is an str in Rust, it'll need to be `"1".to_string()`.

I don't think we'll need to convert them to ints anywhere.

**Comment by theAnnie** [comment]
@lpil ok then ;) I'll ping u when it will be done

**Comment by lpil** [comment]
thank you!

**Comment by lpil** [comment]
Thank you @theAnnie !
