### ISSUE TITLE
[v0.8.0-dev] Can't compile stdlib

### ISSUE THREAD

**Issue by gamebox** [gleam-lang/gleam#430]
Attempting to build stdlib gives this error:

```
error: Syntax error

    ┌── /Users/anthonybullard/Development/stdlib/src/gleam/list.gleam:32:10 ───
    │
 32 │     [x | _] -> Ok(x)
    │          ^ Unexpected token
    │

Expected one of r#"[a-z][0-9a-z_]*"#
```

**Comment by gamebox** [comment]
Looks like list pattern doesn't allow for `PatternDiscard` in the tail position.  Tried a low effort fix(adding a clause to the `PatternList` match, but that cause lalrpop to get very angry with a thousand line error message I'd care not to read.

**Comment by lpil** [comment]
i introduced this bug last night. Will fix shortly!
