### ISSUE TITLE
Update compiler dependencies

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#436]
This tool may be useful: https://github.com/kbknapp/cargo-outdated

Note I wish to keep Codespan the same version as it is part of the user interface and I wish to review any changes.

**Comment by gamebox** [comment]
Here's the output of `cargo outdated` on master:

| Name                                  | Project  | Compat   | Latest   | Kind    | Platform |
| ----                                  | -------  | ------   | ------   | ----    | -------- |
| aho-corasick->memchr                  | 2.2.1    | 2.3.3    | 2.3.3    | Normal  | --- |
| atty->libc                            | 0.2.66   | 0.2.68   | 0.2.68   | Normal  | cfg(unix) |
| backtrace->backtrace-sys              | 0.1.32   | Removed  | Removed  | Normal  | --- |
| backtrace->cfg-if                     | 0.1.10   | Removed  | Removed  | Normal  | --- |
| backtrace->libc                       | 0.2.66   | Removed  | Removed  | Normal  | --- |
| backtrace->rustc-demangle             | 0.1.16   | Removed  | Removed  | Normal  | --- |
| backtrace-sys->cc                     | 1.0.48   | Removed  | Removed  | Build   | --- |
| backtrace-sys->libc                   | 0.2.66   | Removed  | Removed  | Normal  | --- |
| base64->byteorder                     | 1.3.2    | Removed  | Removed  | Normal  | --- |
| blake2b_simd->arrayref                | 0.3.5    | 0.3.6    | 0.3.6    | Normal  | --- |
| blake2b_simd->constant_time_eq        | 0.1.4    | 0.1.5    | 0.1.5    | Normal  | --- |
| block-buffer->byteorder               | 1.3.2    | 1.3.4    | 1.3.4    | Normal  | --- |
| clap->atty                            | 0.2.13   | 0.2.14   | 0.2.14   | Normal  | --- |
| cloudabi->bitflags                    | 1.2.1    | Removed  | Removed  | Normal  | --- |
| codespan                              | 0.7.0    | ---      | 0.9.1    | Normal  | --- |
| codespan->unicode-segmentation        | 1.6.0    | ---      | Removed  | Normal  | --- |
| codespan-reporting                    | 0.7.0    | ---      | 0.9.1    | Normal  | --- |
| codespan-reporting->codespan          | 0.7.0    | ---      | Removed  | Normal  | --- |
| codespan-reporting->termcolor         | 1.0.5    | 1.1.0    | 1.1.0    | Normal  | --- |
| ctor->quote                           | 1.0.2    | 1.0.3    | 1.0.3    | Normal  | --- |
| ctor->syn                             | 1.0.11   | 1.0.17   | 1.0.17   | Normal  | --- |
| dirs->libc                            | 0.2.66   | 0.2.68   | 0.2.68   | Normal  | cfg(unix) |
| dirs->redox_users                     | 0.3.1    | 0.3.4    | 0.3.4    | Normal  | cfg(target_os = "redox") |
| docopt->regex                         | 1.3.1    | 1.3.6    | 1.3.6    | Normal  | --- |
| docopt->serde                         | 1.0.104  | 1.0.105  | 1.0.105  | Normal  | --- |
| failure->backtrace                    | 0.3.40   | Removed  | Removed  | Normal  | --- |
| failure->failure_derive               | 0.1.6    | Removed  | Removed  | Normal  | --- |
| failure_derive->proc-macro2           | 1.0.6    | Removed  | Removed  | Normal  | --- |
| failure_derive->quote                 | 1.0.2    | Removed  | Removed  | Normal  | --- |
| failure_derive->syn                   | 1.0.11   | Removed  | Removed  | Normal  | --- |
| failure_derive->synstructure          | 0.12.3   | Removed  | Removed  | Normal  | --- |
| im                                    | 14.1.0   | 14.3.0   | 14.3.0   | Normal  | --- |
| im->bitmaps                           | 2.0.0    | 2.1.0    | 2.1.0    | Normal  | --- |
| im->sized-chunks                      | 0.5.1    | 0.5.3    | 0.5.3    | Normal  | --- |
| itertools                             | 0.8.2    | ---      | 0.9.0    | Normal  | --- |
| lalrpop                               | 0.17.2   | ---      | 0.18.1   | Build   | --- |
| lalrpop->atty                         | 0.2.13   | 0.2.14   | 0.2.14   | Normal  | --- |
| lalrpop->lalrpop-util                 | 0.17.2   | ---      | 0.18.1   | Normal  | --- |
| lalrpop->regex                        | 1.3.1    | 1.3.6    | 1.3.6    | Normal  | --- |
| lalrpop->regex-syntax                 | 0.6.12   | 0.6.17   | 0.6.17   | Normal  | --- |
| lalrpop->serde                        | 1.0.104  | 1.0.105  | 1.0.105  | Normal  | --- |
| lalrpop->serde_derive                 | 1.0.104  | 1.0.105  | 1.0.105  | Normal  | --- |
| lalrpop->sha2                         | 0.8.0    | 0.8.1    | 0.8.1    | Normal  | --- |
| lalrpop->unicode-xid                  | 0.1.0    | ---      | 0.2.0    | Normal  | --- |
| lalrpop-util                          | 0.17.2   | ---      | 0.18.1   | Normal  | --- |
| petgraph                              | 0.4.13   | ---      | 0.5.0    | Normal  | --- |
| petgraph->fixedbitset                 | 0.1.9    | ---      | 0.2.0    | Normal  | --- |
| petgraph->ordermap                    | 0.3.5    | ---      | Removed  | Normal  | --- |
| pretty_assertions->ctor               | 0.1.12   | 0.1.13   | 0.1.13   | Normal  | cfg(windows) |
| proc-macro-error->proc-macro2         | 1.0.6    | 1.0.9    | 1.0.9    | Normal  | --- |
| proc-macro-error->quote               | 1.0.2    | 1.0.3    | 1.0.3    | Normal  | --- |
| proc-macro-error->syn                 | 1.0.11   | 1.0.17   | 1.0.17   | Normal  | --- |
| proc-macro2->unicode-xid              | 0.2.0    | Removed  | Removed  | Normal  | --- |
| quote->proc-macro2                    | 1.0.6    | 1.0.9    | 1.0.9    | Normal  | --- |
| quote->proc-macro2                    | 1.0.6    | Removed  | Removed  | Normal  | --- |
| rand->libc                            | 0.2.66   | 0.2.68   | 0.2.68   | Normal  | cfg(unix) |
| rand_core->rand_core                  | 0.4.2    | Removed  | Removed  | Normal  | --- |
| rand_jitter->libc                     | 0.2.66   | 0.2.68   | 0.2.68   | Normal  | cfg(any(target_os = "macos", target_os = "ios")) |
| rand_os->cloudabi                     | 0.0.3    | Removed  | Removed  | Normal  | cfg(target_os = "cloudabi") |
| rand_os->fuchsia-cprng                | 0.1.1    | Removed  | Removed  | Normal  | cfg(target_os = "fuchsia") |
| rand_os->libc                         | 0.2.66   | 0.2.68   | 0.2.68   | Normal  | cfg(unix) |
| rand_os->libc                         | 0.2.66   | Removed  | Removed  | Normal  | cfg(unix) |
| rand_os->rand_core                    | 0.4.2    | Removed  | Removed  | Normal  | --- |
| rand_os->rdrand                       | 0.4.0    | Removed  | Removed  | Normal  | cfg(target_env = "sgx") |
| rand_os->winapi                       | 0.3.8    | Removed  | Removed  | Normal  | cfg(windows) |
| rdrand->rand_core                     | 0.3.1    | Removed  | Removed  | Normal  | --- |
| redox_users->failure                  | 0.1.6    | Removed  | Removed  | Normal  | --- |
| redox_users->rand_os                  | 0.1.3    | Removed  | Removed  | Normal  | --- |
| redox_users->rust-argon2              | 0.5.1    | 0.7.0    | 0.7.0    | Normal  | --- |
| regex                                 | 1.3.1    | 1.3.6    | 1.3.6    | Normal  | --- |
| regex->aho-corasick                   | 0.7.6    | 0.7.10   | 0.7.10   | Normal  | --- |
| regex->memchr                         | 2.2.1    | 2.3.3    | 2.3.3    | Normal  | --- |
| regex->regex-syntax                   | 0.6.12   | 0.6.17   | 0.6.17   | Normal  | --- |
| regex->thread_local                   | 0.3.6    | 1.0.1    | 1.0.1    | Normal  | --- |
| rust-argon2->base64                   | 0.10.1   | 0.11.0   | 0.11.0   | Normal  | --- |
| rust-argon2->blake2b_simd             | 0.5.9    | 0.5.10   | 0.5.10   | Normal  | --- |
| rust-argon2->crossbeam-utils          | 0.6.6    | 0.7.2    | 0.7.2    | Normal  | --- |
| same-file->winapi-util                | 0.1.2    | 0.1.3    | 0.1.3    | Normal  | cfg(windows) |
| serde                                 | 1.0.104  | 1.0.105  | 1.0.105  | Normal  | --- |
| serde->serde_derive                   | 1.0.104  | 1.0.105  | 1.0.105  | Normal  | --- |
| serde_derive->proc-macro2             | 1.0.6    | 1.0.9    | 1.0.9    | Normal  | --- |
| serde_derive->quote                   | 1.0.2    | 1.0.3    | 1.0.3    | Normal  | --- |
| serde_derive->syn                     | 1.0.11   | 1.0.17   | 1.0.17   | Normal  | --- |
| sized-chunks->bitmaps                 | 2.0.0    | 2.1.0    | 2.1.0    | Normal  | --- |
| string_cache->new_debug_unreachable   | 1.0.3    | 1.0.4    | 1.0.4    | Normal  | --- |
| string_cache->serde                   | 1.0.104  | 1.0.105  | 1.0.105  | Normal  | --- |
| string_cache_codegen->proc-macro2     | 1.0.6    | 1.0.9    | 1.0.9    | Normal  | --- |
| string_cache_codegen->quote           | 1.0.2    | 1.0.3    | 1.0.3    | Normal  | --- |
| strsim                                | 0.9.3    | ---      | 0.10.0   | Normal  | --- |
| structopt                             | 0.3.5    | 0.3.12   | 0.3.12   | Normal  | --- |
| structopt->structopt-derive           | 0.3.5    | 0.4.5    | 0.4.5    | Normal  | --- |
| structopt-derive->proc-macro-error    | 0.2.6    | 0.4.12   | 0.4.12   | Normal  | --- |
| structopt-derive->proc-macro2         | 1.0.6    | 1.0.9    | 1.0.9    | Normal  | --- |
| structopt-derive->quote               | 1.0.2    | 1.0.3    | 1.0.3    | Normal  | --- |
| structopt-derive->syn                 | 1.0.11   | 1.0.17   | 1.0.17   | Normal  | --- |
| strum                                 | 0.17.1   | ---      | 0.18.0   | Normal  | --- |
| strum_macros                          | 0.17.1   | ---      | 0.18.0   | Normal  | --- |
| strum_macros->proc-macro2             | 1.0.6    | 1.0.9    | 1.0.9    | Normal  | --- |
| strum_macros->quote                   | 1.0.2    | 1.0.3    | 1.0.3    | Normal  | --- |
| strum_macros->syn                     | 1.0.11   | 1.0.17   | 1.0.17   | Normal  | --- |
| syn->proc-macro2                      | 1.0.6    | 1.0.9    | 1.0.9    | Normal  | --- |
| syn->proc-macro2                      | 1.0.6    | Removed  | Removed  | Normal  | --- |
| syn->quote                            | 1.0.2    | 1.0.3    | 1.0.3    | Normal  | --- |
| syn->quote                            | 1.0.2    | Removed  | Removed  | Normal  | --- |
| syn->unicode-xid                      | 0.2.0    | Removed  | Removed  | Normal  | --- |
| synstructure->proc-macro2             | 1.0.6    | Removed  | Removed  | Normal  | --- |
| synstructure->quote                   | 1.0.2    | Removed  | Removed  | Normal  | --- |
| synstructure->syn                     | 1.0.11   | Removed  | Removed  | Normal  | --- |
| synstructure->unicode-xid             | 0.2.0    | Removed  | Removed  | Normal  | --- |
| term->byteorder                       | 1.3.2    | 1.3.4    | 1.3.4    | Normal  | --- |
| termcolor                             | 1.0.5    | 1.1.0    | 1.1.0    | Normal  | --- |
| termcolor->wincolor                   | 1.0.2    | Removed  | Removed  | Normal  | cfg(windows) |
| toml                                  | 0.5.5    | 0.5.6    | 0.5.6    | Normal  | --- |
| toml->serde                           | 1.0.104  | 1.0.105  | 1.0.105  | Normal  | --- |
| walkdir                               | 2.2.9    | 2.3.1    | 2.3.1    | Normal  | --- |
| walkdir->same-file                    | 1.0.5    | 1.0.6    | 1.0.6    | Normal  | --- |
| walkdir->winapi-util                  | 0.1.2    | 0.1.3    | 0.1.3    | Normal  | cfg(windows) |
| winapi->winapi-i686-pc-windows-gnu    | 0.4.0    | Removed  | Removed  | Normal  | i686-pc-windows-gnu |
| winapi->winapi-x86_64-pc-windows-gnu  | 0.4.0    | Removed  | Removed  | Normal  | x86_64-pc-windows-gnu |
| winapi-util->winapi                   | 0.3.8    | Removed  | Removed  | Normal  | cfg(windows) |
| wincolor->winapi                      | 0.3.8    | Removed  | Removed  | Normal  | --- |
| wincolor->winapi-util                 | 0.1.2    | Removed  | Removed  | Normal  | --- |

**Comment by gamebox** [comment]
I think most worrying is the number of deps that have been removed.

**Comment by lpil** [comment]
If the tests pass then it implies the dep maintainers have slimmed their deps. That would be cool :)

**Comment by gamebox** [comment]
So should we Try to update what we can to the compat version?

>

**Comment by lpil** [comment]
I would try updating everything except codespan and see if anything breaks

**Comment by oneness** [comment]
That is exactly what I did @lpil and all is up to date except for codespan. All tests are passing. Here is the PR: https://github.com/gleam-lang/gleam/pull/597
