### ISSUE TITLE
Replace handlebars templating library with askama

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#441]
Askama offers more type safety than handlebars and as such is a better fit for our use case.

https://github.com/djc/askama

**Comment by gamebox** [comment]
You want this done before v.0.8.0? Note that I used handlebars because of familiarity and the fact that I have committed to the project before.

**Comment by lpil** [comment]
It doesn't matter when really, it's just a refinement rather than being a user-facing change :)
