### ISSUE TITLE
Erlang printer does not surround binary operator sub expressions with parens where required

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#448]

**Comment by gamebox** [comment]
Any examples?

**Comment by lpil** [comment]
Yes of course! I've added a non-exhausted set of tests that demonstrate the problem here https://github.com/gleam-lang/gleam/blob/6bfdcba255837f01188715de2c7b7f2b52df0256/test/core_language/test/binary_operators_test.gleam

Thanks for the prompt, this ticket was unclear.

**Comment by QuinnWilton** [comment]
I believe the fix for this should go in this function: https://github.com/gleam-lang/gleam/blob/master/src/erl.rs#L283

Is there any reason not to just always wrap left and right in parentheses? I know they'd often be superfluous, but that seems like the simplest and least-error prone approach.

**Comment by lpil** [comment]
It would make the output less pretty, but it would be an acceptable bug fix that can be improved later.
