### ISSUE TITLE
Handling Unicode strings correctly

### ISSUE THREAD

**Issue by itsgreggreg** [gleam-lang/gleam#457]
Currently it is impossible to input some Unicode characters.

In Erlang writing binaries directly can cause their bytes to get truncated, meaning:
`<<256>> == <<0>>` and `<<"🌵">> == <<"5">>`

Erlang has a postfix encoding you can supply to handle this so: 
`<<"🌵"/utf8> /= <<"5">>`

and perhaps more importantly:
```
unicode:characters_to_binary(string:to_graphemes("🤷‍♂️")) == <<"🤷‍♂️"/utf8>>.
```

perhaps this line:
https://github.com/gleam-lang/gleam/blob/99d033aa15622c53bb846e02e2407b8a44b8d69a/src/erl.rs#L227

should be `value.to_doc().surround("<<\"", "\"/utf8>>")` ? 

Is there a better way to handle unicode strings?

here's a little test you can add to check if things are working:
```
pub fn unicode_test() {
    "🌵"
    |> should.not_equal(_, "5")
}
```

**Comment by lpil** [comment]
Great catch! And I think you have the correct solution there. Would you like to make a PR for that change?
