### ISSUE TITLE
Run test/core_language tests on CI

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#460]
```
cd test/core_language
rebar3 eunit
```

Will need to be a new job in the `build_compiler.yaml` GitHub actions workflow that uses https://github.com/gleam-lang/setup-erlang with the compiler build from the Linux workflow step.

**Comment by DiodonHystrix** [comment]
☝️ working on it

**Comment by lpil** [comment]
Thank you @DiodonHystrix
