### ISSUE TITLE
Support literal values in guards

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#465]
```rust
case x {
  _ if x == 1 -> "here we are using an Int literal"
}
```

- [x] Int
- [x] Float
- [x] Tuple
- [ ] List
- [x] Records
- [x] String

If you pick up this ticket please no more than one implementation per PR please so that it is easier to review. Thanks!

**Comment by kyle-sammons** [comment]
Working on this!

**Comment by lpil** [comment]
Thank you @kyle-sammons ! Let me know if you would like any pointer on implementation

**Comment by gamebox** [comment]
Just a suggestion but what about.

```
case x {
  1 -> "this is an int literal pattern"
  _ -> ""
}
```

**Comment by lpil** [comment]
That would be a better way to express that, it's more an example to explain the syntax.

A more realistic example might be something like this:

```rust
case x {
  Ok(i) if i > 3 -> True
  _ -> False
}
```

**Comment by gamebox** [comment]
Could you add some detail about what this looks like for compound types?

**Comment by lpil** [comment]
Does this help?

```rust
case x {
  Ok(i) if i == [] || i == [1] -> True
  _ -> False
}
```

**Comment by lpil** [comment]
Hi @kyle-sammons are you still working on this? Thanks

**Comment by QuinnWilton** [comment]
I'm interested in taking a stab at the tuple implementation if no one is currently looking at that :)

**Comment by kyle-sammons** [comment]
@lpil I am, I am. Hopefully finishing up the tuple implementation today. @QuinnWilton you can totally take either the List or Record one if you want to help out!

**Comment by QuinnWilton** [comment]
Thanks @kyle-sammons! I'll likely start work on one of those tasks in the next few days if you haven't gotten to them by then :)

Do you by any chance have your WIP branch pushed up anywhere? I imagine the implementation for tuples / lists / records will be fairly similar, so it'd probably be worth me trying to match your approach as much as possible. No pressure if it isn't ready for public viewing yet though :D

**Comment by QuinnWilton** [comment]
Just an update -- I have not started work on the list implementation. I've been spending my time thinking about another issue (#34), so list and record support are both unclaimed at the moment.

**Comment by tomwhatmore** [comment]
No-one's working on those last two right? I'll do lists now and unless there's any other takers I'm happy to do records too.

**Comment by kyle-sammons** [comment]
@tomwhatmore Hey-o, I've actually been working on the list implementation. If you want to knock out the record one, though, go for it! :)

**Comment by tomwhatmore** [comment]
@kyle-sammons Sure, no problem, I'll do records instead.

**Comment by tomwhatmore** [comment]
Is there a reason why string literals aren't on this list?

**Comment by lpil** [comment]
I forgot! Oops!

**Comment by tomwhatmore** [comment]
That is a good reason. I'll add them in a new PR.

**Comment by lpil** [comment]
@kyle-sammons Are you working on this? :)

**Comment by kyle-sammons** [comment]
@lpil So sorry, but I don't think I'll be able to finish off the list implementation. Life has gotten increasingly complex with the recent pandemic and taken away most of my free time 😞
