### ISSUE TITLE
Refactor ClauseGuard to only have a type field for Var

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#470]
https://github.com/gleam-lang/gleam/blob/113c89fc15753d5f7f4efbec3f65af253a64a07e/src/ast.rs#L280-L287

Currently we store a Type value on all nodes, but the value contained only varies on the Var node. Remove this field from all other nodes and update the typ method to return a constant value rather than the contained field.

**Comment by tomwhatmore** [comment]
I can do this unless you'd rather people only did one `good first issue`?

**Comment by lpil** [comment]
Go for it Tom!

**Comment by CrowdHailer** [comment]
Is there anything remaining on this issue?

**Comment by lpil** [comment]
Well spotted, thanks Peter!
