### ISSUE TITLE
assert syntax for binding with with partial patterns

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#473]
Introduce a new syntax for binding variables

```rust
assert Ok(x) = result
```

This works like the `let` syntax, except it allows you to use a pattern that does not match all values (the process crashing if it does not match).

As we don't yet have #163 this would initially just be implementing the syntax so that it works the same as `let`. I would be happy for this to be a field like `assert: bool` on the `Let` AST variants.

**Comment by tomwhatmore** [comment]
I can do this one

**Comment by lpil** [comment]
Thank you !
