### ISSUE TITLE
Shorthand for discarding remaining fields in a record pattern

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#474]
```rust
type Triple {
  Triple(a: Int, b: Int, c: Int)
}
```
```rust
let Triple(a: the_a, ..) = triple
```

**Comment by lpil** [comment]
@tomwhatmore Did you say you were doing this?

**Comment by tomwhatmore** [comment]
I did. Made some progress last night, hoping to get it finished this evening.

**Comment by lpil** [comment]
Great, thanks! No rush, I just wanted to make sure no one else picked this up.
