### ISSUE TITLE
Change list prepend syntax to use .. spread operator

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#475]
Current syntax:

```rust
[1, 2 | rest]
```

Desired syntax:

```rust
[1, 2, ..rest]
```

This change is motivated by the desire to have a uniform syntax with #474 

## Requirements

This should be supported in both expressions and patterns.

The formatter should render using the new syntax.

The parser should continue to accept the old syntax so that users can upgrade their code using the formatter.

**Comment by tomwhatmore** [comment]
I can do this one if you want?

**Comment by lpil** [comment]
Yes please

**Comment by tomwhatmore** [comment]
Would be nice if the compiler told you the `|` syntax was deprecated, it doesn't currently emit any warnings right?

**Comment by lpil** [comment]
We don't currently have any way of emitting warnings so do not include that in the first PR. Please open an issue for warnings :)
