### ISSUE TITLE
Add Gleam to Linguist

### ISSUE THREAD

**Issue by gamebox** [gleam-lang/gleam#477]
Looks like we can just add Gleam to Linguist.  I’ll link an example PR.  You can assign as well since I’m not going to do much more on incremental until v0.8 ships

https://github.com/github/linguist/pull/4759

**Comment by lpil** [comment]
I like this idea a lot but I'm not sure we qualify yet. [Here](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language) it say we should have 1000s of code examples and be able to demonstrate real world code on GitHub.

**Comment by brightly-salty** [comment]
Just an FYI: We need "hundreds of repositories". We only need thousands of code examples if the extension conflicts with one already in Linguist. I think this might be worthwhile to pursue, especially as Linguist lets PRs linger if they are not ready yet.

**Comment by lpil** [comment]
Wonderful news! Would someone like to take the lead here?

**Comment by brightly-salty** [comment]
I would in general, but I'm not sure if I know enough about gleam to create the grammar for it. I'd be happy to submit the Linguist PR if we could find/create the grammar file.

**Comment by lpil** [comment]
That would be great @brightly-salty ! I'll help out if any issues arise.

I believe we can use the grammar from the vscode plugin https://github.com/gleam-lang/vscode-gleam/blob/main/syntaxes/gleam.tmLanguage.json

**Comment by lpil** [comment]
@brightly-salty After doing some digging it seems we have about 70 repos on GitHub. This is not enough yet, so let's focus on other things + getting more Gleam code on GitHub.

**Comment by Aloso** [comment]
I think there are enough repos using Gleam now. I searched GitHub and found a lot of repos solving Advent of Code 2021 in Gleam.

So I downloaded the first 1000 file entries that have ".gleam" in their path, filter by paths that end with ".gleam" and group by repository, which told me that the files are from **95** different repositories. And I was only able to download 1000 file entries due to rate limits; according to the GitHub API there are over 11,000.

**Comment by Aloso** [comment]
@lpil @gamebox I filed a PR: https://github.com/github/linguist/pull/5706

**Comment by michallepicki** [comment]
Current PR for tracking: https://github.com/github/linguist/pull/5688

**Comment by lpil** [comment]
It's finally here!!!
