### ISSUE TITLE
Support compiler warnings

### ISSUE THREAD

**Issue by tomwhatmore** [gleam-lang/gleam#479]
Would be useful for the compiler to be able to omit warnings. Specifically, deprecation notices would be nice when there are syntax changes such as in #475.

I have no idea how much work this would be as I haven't even looked into it yet, but getting this issue up as suggested by @lpil in case anyone has thoughts on the matter.

**Comment by lpil** [comment]
My first thought is this:

We have an enum to represent all possible warnings

```rust
pub enum Warning {
  DeprecatedListPrependSyntax {
    path: PathBuf,
    location: SrcSpan,
  }
}
```

And then the `infer_module` function can return a vector of these warnings. The compile then prints them after compilation, before printing any errors.

**Comment by tomwhatmore** [comment]
That sounds like a good approach to me. Not sure how complicated the pretty formatting is but presumably it could mostly reuse the current error printing logic but with some slightly different colours?

**Comment by lpil** [comment]
Yes that sounds good. We could do the warning printing as a second step later if that's easier, as to not get in the way of the warning collection.
