### ISSUE TITLE
Allow trailing commas in list prefixing

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#481]
```rust
let list = [
  1, 
  2,
  ..rest,
]
```

Both for expressions and for patterns.

**Comment by gamebox** [comment]
This seems to already work for lists...

**Comment by gamebox** [comment]
And in patterns

**Comment by lpil** [comment]
Sorry, to be more clear it is when specifically using the spread syntax.

```rust
let list = [
  1, 
  2,
  ..rest, // <- this comma
]
```

**Comment by gamebox** [comment]
Got it

**Comment by gamebox** [comment]
Interesting that I got this to compile stdlib, but the tests fail
