### ISSUE TITLE
Include custom type constructors in generated HTML docs

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#483]
https://github.com/gleam-lang/gleam/blob/7d2f1ae988e2c05608cfc94d7fd3a38909b505a9/templates/documentation_module.html#L41-L77

We'll need to add constructor information to this struct. https://github.com/gleam-lang/gleam/blob/7d2f1ae988e2c05608cfc94d7fd3a38909b505a9/src/doc.rs#L206-L211

We do not need to implement links to types at this point.

**Comment by gamebox** [comment]
I'll do this

**Comment by lpil** [comment]
Thank you
