### ISSUE TITLE
All stdlib modules need documentation comments

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#493]
https://github.com/gleam-lang/stdlib/

**Comment by CrowdHailer** [comment]
Would this be better after 0.8.0? You can keeps publishing updates to docs to hex. I'd be happy to contribute but more motivation once building things for 0.8

**Comment by lpil** [comment]
I would like it done before v0.8 so that when we release the new documentation generator all the stdlib modules have at least basic documentation to show off the new feature with.
