### ISSUE TITLE
Function naming question

### ISSUE THREAD

**Issue by gootik** [gleam-lang/gleam#496]
Hey, 
I was playing around with Gleam and decided to make a simple "cache" library built on top of `persistent_term` to play around. I noticed that gleam compiler doesn't like this sort of naming:
```
error: Syntax error

   Users/sasan.hezarkhani/MyWork/cache/src/cache.gleam:6:20 
   
 6  pub external fn getOrElse(key, default) -> Bool = "persistent_term" "get"
                       ^^^^^^ Unexpected token
   
```
I couldn't find it being explicitly noted in the documentation. Would you consider this a bug or are you planning to only allow snake_case function naming in gleam?

**Comment by lpil** [comment]
Hi @gootik ! Uppercase letter are not permitted in function names, they are for types and constructors only. Noting this in the guide is a good idea, thanks!

**Comment by gootik** [comment]
cool. thanks for the quick response
