### ISSUE TITLE
Always show types for function arguments in HTML module documentation

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#508]
Currently we only show them if the author gave annotations. We want to introspect the type of the function to see what the types are if no annotations are present.

**Comment by tomwhatmore** [comment]
I'll do this

**Comment by lpil** [comment]
Thank you

**Comment by tomwhatmore** [comment]
Do you think the best approach here would be to modify `docs_fn_signature()` to check each arg for an annotation and then construct a new `TypeAst` if they don't have one already? Then the rest of formatter could just proceed as usual.

Is there an existing mechanism for getting a `TypeAst` from a `Type` or would I have to write some sort of inverse of `type_from_ast()`?

**Comment by lpil** [comment]
I would probably try zipping together the arguments and the types of the arguments, and then implement a function which would print the label + argument with the typing using the type printer: https://github.com/gleam-lang/gleam/blob/master/src/typ/pretty.rs

**Comment by tomwhatmore** [comment]
Ah right, hadn't spotted typ/pretty.rs, that makes things a lot easier. Thanks!
