### ISSUE TITLE
Compiler errors not clear for type mismatches when expecting functions

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#510]
Here is an example.

```rust
fn bar() -> Int {
    5
}

fn run(foo: fn() -> String) {
    foo()
}

fn demo() {
    run(bar)
}
```

Error message 

```
Expected type:

    String

Found type:

    Int
```

I would expect it to say Expected Type `fn () -> String` or have a message about expected return type.

**Comment by lpil** [comment]
This has been annoying me too! We will fix this.
