### ISSUE TITLE
Warn when a result is discarded in a Seq

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#531]
Warn:

```rust
function_that_returns_a_result() // This result value is being implicitly discarded
something_else()
```

Ok:
```rust
let _ = function_that_returns_a_result() // This result value is being excplicitly discarded
something_else()
```

**Comment by CrowdHailer** [comment]
I don't understand this issue. Why are results getting special treatment? or is it just results that currently don't have warnings.

**Comment by lpil** [comment]
Results represent possible presence of errors so we want to ensure they are not discarded accidentally. Other types are less important.
