### ISSUE TITLE
Should we allow numbers in gleam package names?

### ISSUE THREAD

**Issue by nono** [gleam-lang/gleam#551]
Currently, gleam modules may only have letters and underscores in the name. In other languages, numbers are not used often for modules, but I think there are a few cases where they are useful, like `http2`, `md5`, `bzip2`, `crc32`, `base64`. What the gleam community think about it?

**Comment by lpil** [comment]
Seems reasonable to me. I think the only think we would need to change is the code that scans the file system for Gleam modules.

**Comment by scripttease** [comment]
I'd be happy to add this

**Comment by lpil** [comment]
Thanks!
