### ISSUE TITLE
Include or reference release write-up in GitHub release notes?

### ISSUE THREAD

**Issue by rjdellecese** [gleam-lang/gleam#555]
@lpil produces very nice write-ups for each new release of the Gleam language, and publishes them on his blog. [Here](https://lpil.uk/blog/gleam-v0.8-released/) is the write-up for Gleam v0.8. In order to be notified of new Gleam releases, I "watch" for them on GitHub. But whenever one arrives, I have to navigate to Louis's blog to find the write-up for it so that I can easily grok what changes the new version has brought.

I would find it helpful if that write-up were included or referenced in the GitHub release, as it would save me a few clicks and keystrokes. But for those who don't know where to go to find a nice summary of each release, and are viewing it on GitHub, I wonder if it would be nice to include either some version of that write-up or a reference to it in each release's notes?

**Comment by lpil** [comment]
That is a great idea! Let's link each one from the changelog

**Comment by scripttease** [comment]
I'll take this too, please :)

**Comment by lpil** [comment]
Thanks!
