### ISSUE TITLE
Update mix_gleam to use the compile-package API

### ISSUE THREAD

**Issue by GildedHonour** [gleam-lang/gleam#560]
Say, I have a project written in Elixir and Phoenix. What'll be a way to incorporate Gleam into my project? Create a library in Gleam and use it in the project, that's it?

**Comment by eterps** [comment]
These articles might be useful:

* https://devonestes.herokuapp.com/adding-gleam-to-your-elixir-project
* https://dev.to/michaeljones/mixing-gleam-elixir-3fe3

**Comment by lpil** [comment]
Hi @GildedHonour ! Thanks for you question.

At currently there's no officially supported way to use Gleam in an Elixir project. I would use either libraries written in Gleam or I would use an umbrella project containing both Elixir and Gleam projects.

**Comment by rschooley** [comment]
@lpil Can we consider re-opening this question and recommending a way to integrate with an Elixir app?  

There is this [post](https://devonestes.herokuapp.com/adding-gleam-to-your-elixir-project) from 2019 that suggests setting the `manager:` option in deps for the gleam lib.

We also have [mix gleam](https://github.com/gleam-lang/mix_gleam) that may be useful instead.  

When adding gleam to an elixir umbrella I am not sure on exactly what I should do.  I am seeing more posts about using gleam as the functional core and elixir as the operational wrapper, and I would like to try this out but could use some documentation on how.

**Comment by lpil** [comment]
Yes, it would be great to have this!

Really we need someone to write a new mix plugin that uses the `gleam compile-package` API as the current compiler API being used is a hack and has been deprecated. It will stop working in future versions, and it already doesn't work in many projects, including umbrella applications.

I think it would be relatively straightforward to build this plugin, but as I am focusing on core Gleam tooling I'm afraid someone else will need to do this.

**Comment by michallepicki** [comment]
I think this is now implemented (mostly by @tynanbe ) and there's a separate issue for supporting umbrellas: https://github.com/gleam-lang/mix_gleam/issues/13

**Comment by lpil** [comment]
Thank you
