### ISSUE TITLE
Inline calls to external functions

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#562]
If I define this function:

```rust
pub external fn internal(a) -> a = "some_external" "function"
```

When I use it in my code

```rust
internal("hello")
```

It should generate code calling the internal function directly:

```erl
some_external:function(<<"hello">>).
```

Currently it generates a call to `internal(<<"hello">>).`

**Comment by tomwhatmore** [comment]
I can do this one

**Comment by lpil** [comment]
Thank you!
