### ISSUE TITLE
Ability to add extra pages to the gleam docs output.

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#569]
It's a good Default to add the Readme as a page, however I would like to be able to specify other pages of markdown that should be included.

Not sure where this declaration of markdown pages should go. Perhaps Gleam.toml?

**Comment by borski** [comment]
New here; just wanted to say I'm working on this one. :)

**Comment by lpil** [comment]
Thank you @borski !

**Comment by CrowdHailer** [comment]
Awesome @borski I will definitely be using this, thanks
