### ISSUE TITLE
Module level constants

### ISSUE THREAD

**Issue by sporto** [gleam-lang/gleam#577]
It would be great to have top level constants in a module that can be used for pattern matching.

For example, I want to parse a string into a custom type.

```rust
const one = "one"
const two = "two"

type Enum {
  One
  Two
}

fn enum_to_code(enum: Enum) -> String {
  case enum {
    One -> one
    Two -> two
  }
}

fn code_to_enum(code: String) -> Result(Enum, String) {
  case code {
    one -> Ok(One)
    two -> Ok(Two)
    _ -> Err("Unknown " ++ code)
  }
}
```

This cannot be achieved with functions

```
  // invalid
  case code {
    one() -> Ok(One)
```

At the moment I would need to repeat the strings in two places:

```
fn enum_to_code...
  case enum {
    One -> "one"
   ...

fn code_to_enum...
  case code {
    "one" -> Ok(One)
  ...
```

Having these constant would allow to only have one source of truth.

**Comment by lpil** [comment]
We would only permit literals to be used as constants, no function calls etc. 

One question I have is what Erlang should be generated for this.

I think it would be good to create a zero arity function for the definition.

Where it is used we could inline the constant, or call the function. I'm not sure which is better.

**Comment by gamebox** [comment]
I would assume you would either inline the constant or generate a macro for the constant and use that in place of it

**Comment by lpil** [comment]
For Gleam use inlining would work, but we'll need something else for Erlang + Elixir users. A macro is good but would only be usable from within the same module.

**Comment by OvermindDL1** [comment]
> We would only permit literals to be used as constants, no function calls etc.

No constant expressions?  ;-)

But yeah, probably makes sense to just replace it inline in code, or use an erlang macro to do the same thing.

**Comment by lpil** [comment]
Not for the first iteration, but later that would be a great addition! A little complicated as we don't have a way to evaluate Gleam code within the Rust compiler, but we can cross that bridge later.
