### ISSUE TITLE
Code formatter

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#59]
```
gleam format path/to/file.gleam
```

Reuse the pretty printing algebra used for Erlang code generation. Effectively it's a new compiler backend that skips type inference and compiles to Gleam.

## Retaining comments

Strip the comments out, parse the remaining AST, traverse the AST and use positions in the AST and the comments to determine where to annotate which nodes with which comments.

Custom lalrpop tokenizer:

- https://github.com/lalrpop/lalrpop/blob/8a96e9646b3d00c2226349efed832c4c25631c53/doc/calculator/src/main.rs#L143-L148
- https://github.com/lalrpop/lalrpop/blob/8a96e9646b3d00c2226349efed832c4c25631c53/doc/calculator/src/calculator8.lalrpop
- https://github.com/lalrpop/lalrpop/blob/8a96e9646b3d00c2226349efed832c4c25631c53/doc/calculator/src/tok8.rs

**Comment by OvermindDL1** [comment]
Just as an interesting note, OCaml's comments become extension nodes on either the following ast node if on it's own line or the preceeding ast node if inline with ast.  Essentially something like:
```ocaml
(* Blah *)
2 + 2

2 * 3 (* blorp *) + 2
```
Becomes:
```ocaml
2 + 2 [%comment "Blah"]

(2 * 3) [%comment "blorp"] + 2
```
Although it also adds on other metadata like line number and more too, but everything gets decorated as such as well.

**Comment by lpil** [comment]
That's the approach I took with exfmt, it worked well :)

I should probably re-open this given I'm discarding them at the moment.

**Comment by lpil** [comment]
@gamebox has started work on a formatter. :)
