### ISSUE TITLE
Formatter: Wrap unqualified imports

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#610]
Have the formatter render these expressions like so:

```haskell
import my/cool/module.{
  One, Two, Three, Four, Five, Six, Seven, Eight, Nine, Ten, Eleven, Twelve,
  Thirteen, Fifteen, Sixteen,
}
```

This will require extending the printing algebra with a form like Elixir's flex_break

https://github.com/elixir-lang/elixir/blob/d1559660740c85d94e3cff942ff0b6c8f7d31818/lib/elixir/lib/inspect/algebra.ex#L680-L712

**Comment by oneness** [comment]
@lpil I can take a stab at this. Any pointer where to focus?

**Comment by lpil** [comment]
For sure. First we'll need to work in the pretty module: https://github.com/gleam-lang/gleam/blob/master/src/pretty.rs

The Document enum will need to be expanded to support this new extension which can be found in the Elixir implemention above

https://github.com/gleam-lang/gleam/blob/3cecc58691af74a1b9e1bdc7c9bd42020a7a9052/src/pretty.rs#L83-L111

Then we will want to update the formatter to use this new form when rendering the unqualified imports: https://github.com/gleam-lang/gleam/blob/3cecc58691af74a1b9e1bdc7c9bd42020a7a9052/src/format.rs#L209-L216

**Comment by oneness** [comment]
Thanks for the context, which should be enough to get me digging into.  So feel free to assign it to me so others know to avoid duplicate efforts.

**Comment by lpil** [comment]
Wonderful, thank you!
