### ISSUE TITLE
Formatter: permit doc comments before custom type constructors with arguments

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#612]
```rust
pub type Choice {
  /// left
  Left(a: String)
  /// right
  Right(a: String)
}
```

Please leave a comment if you would like to work on this, or if you would like some pointers on how to implement this. Thanks!

**Comment by tomwhatmore** [comment]
Don't we support this already?

https://github.com/gleam-lang/gleam/blob/3cecc58691af74a1b9e1bdc7c9bd42020a7a9052/src/format/tests.rs#L2259-L2271

**Comment by lpil** [comment]
Ah! It's doc comments it doesn't work for. Thanks!

**Comment by tomwhatmore** [comment]
There's a test for them too, so there must be something else going on.

https://github.com/gleam-lang/gleam/blob/3cecc58691af74a1b9e1bdc7c9bd42020a7a9052/src/format/tests.rs#L2273-L2285

**Comment by lpil** [comment]
Ah yes, I'm wrong again! Seems it happens when there are arguments. I double checked this time!
