### ISSUE TITLE
Fold definition incorrectly generated in Hex docs?

### ISSUE THREAD

**Issue by scripttease** [gleam-lang/gleam#615]
The Hex docs for list.fold state the following:
```
pub fn fold(
  over list: List(a),
  from initial: b,
  with fun: fn(a, b) -> b,
) -> a
```

Should it be this?
```
pub fn fold(
  over list: List(a),
  from initial: b,
  with fun: fn(a, b) -> b,
) -> b
```

Same for fold-right.

**Comment by lpil** [comment]
Oh dear, that is strange. Looks like a bug in the printer.

**Comment by tomwhatmore** [comment]
Is this fixed? Seems to be generating ok for me on master.

**Comment by lpil** [comment]
I don't remember changing anything. How strange.

I'll do a quick test now.

**Comment by lpil** [comment]
I'm testing it with v0.9.0 of the compiler and the stdlib and it is giving me the incorrect output that @scripttease has above. What versions are you using @tomwhatmore ?

**Comment by tomwhatmore** [comment]
Current master. I just copied the fold function into the hello_world project to give it a quick test, I didn't actually generate the full stdlib docs, so maybe that's the difference? Happy to look into it properly if you want to assign this to me.

**Comment by lpil** [comment]
Thank you Tom!

**Comment by tomwhatmore** [comment]
Actually I think you can just ignore that completely. I just did it again and I'm getting the broken one. Maybe I just misread it, sorry! I will look into it though.
