### ISSUE TITLE
Render tuple as a hanging expression as the value of a let

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#616]
Current behaviour

```rust
let module_ = tuple(
    atom.create_from_string("module"),
    atom.create_from_string("gleam@otp@actor"),
  )
```

Expected behaviour

```rust
let module_ = tuple(
  atom.create_from_string("module"),
  atom.create_from_string("gleam@otp@actor"),
)
```
Please leave a comment if you would like to work on this, or if you would like some pointers on how to implement this. Thanks!

**Comment by scileo** [comment]
Hello,
I'm am not experienced with this code base. I'd like to work on this issue. Is that possible?

**Comment by lpil** [comment]
Hi @scileo ! Thanks for your help.

For this ticket we'll need to modify the formatter to format a "hanging_expr" that is a tuple the same way as if it was a call.

The formatter code to be updated is here -> https://github.com/gleam-lang/gleam/blob/master/src/format.rs

We'll also need a test for tuples, similar to this one: https://github.com/gleam-lang/gleam/blob/98b25d4d7b154bc25d672a1abf2e0a329dc2cbef/src/format/tests.rs#L1276-L1284

Let me know if you need any other pointers.

**Comment by scileo** [comment]
Thanks! I'll investigate on that

**Comment by scileo** [comment]
I think I fixed it. See code [on my fork](https://github.com/scileo/gleam/tree/fix-616).
I split it in two commit (one for the implementation, one for the test). Is that okay for you?

(I'm waiting for your confirmation before creating a PR)

**Comment by lpil** [comment]
Sounds great! Make a PR and we'll review + merge.

btw those commits have an email address on them that isn't associated with your GitHub account. If you'd like the commits attributed to you in the history (and a link to your GitHub profile added to the release blog post) add that email to your GitHub account, or change the email used for the commits.

**Comment by scileo** [comment]
Thanks for pointing that! It should be fixed now. I'll send the PR in a couple of minutes.
