### ISSUE TITLE
Remove support for deprecated list prepend syntax

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#626]
Cleanup after this change: https://github.com/gleam-lang/gleam/pull/480

**Comment by hindenbug** [comment]
Hi @lpil do you mind if I take a dig at this  ? :)

**Comment by lpil** [comment]
That would be great, thank you! Let me know if you would like any pointers or a WIP review.

**Comment by hindenbug** [comment]
Sure, have a draft PR in progress, let me know your thoughts :)
