### ISSUE TITLE
Rename bitstring to bit_string and Bitstring to BitString

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#630]

**Comment by CrowdHailer** [comment]
Do I need this issue to be resolved before I can use bit string syntax.?

I've started a crypto module https://github.com/midas-framework/crypto/blob/master/src/gleam/crypto.gleam#L6

But I get the following error.
```
error: Type mismatch
   ââ /opt/app/crypto/src/gleam/crypto.gleam:20:57
   â
20 â   ) == bit_string.byte_size(right) && do_secure_compare(left, right, 0)
   â                                                         ^^^^

Expected type:

    Bitstring

Found type:

    BitString
```

**Comment by lpil** [comment]
The standard library does not yet support v0.10 so will not work with the bit string syntax or the BitString type. For you'll have to copy those functions to your project if you wish to use them with the BitString type.

**Comment by CrowdHailer** [comment]
I'm not making any use of the standard library. I am using gleam_bitwise but the only type that cases about is Int.

I'll investigate a bit more
