### ISSUE TITLE
Should gleam allow the reuse of a variable in a pattern?

### ISSUE THREAD

**Issue by tomwhatmore** [gleam-lang/gleam#634]
This example is from the Elixir docs, but the equivalent works in Erlang too. 

```elixir
<<name_size::size(8), name::binary-size(name_size), " the ", species::binary>> = <<5, "Frank the Walrus">>
```
name_size is bound and then used in the next segment of the same pattern. This is currently impossible in Gleam, you get a `DuplicateVarInPattern` error. I actually added the DuplicateVarInPattern error, but I must admit that I don't fully understand the reasoning for it. Is this behaviour something we:

1. Deliberately don't want to support
2. Would like support to but it's impossible with the current type system
3. Would like to support and we just haven't done it yet

**Comment by CrowdHailer** [comment]
I'd argue this is different.

The error was added to handle the case `let tuple(a, a) = tuple(3, 4)` both are assignments, and I think that error makes sense. 

In the case the second instance name_size is being used for the value in it.

**Comment by tomwhatmore** [comment]
Yeah it's definitely different, no argument there. I think that behaviour should be an error. From what I remember though, the reason the issue came up in the first place was because that double assignment didn't actually unify properly. In which case the behaviour I describe in the first post presumably wouldn't either, even if the `DuplicateVarInPattern` error was avoided.

What I don't know is why it didn't work, and that's where my question comes in. Just wanted to check I wouldn't be wasting my time working on it if we don't want it or know it wouldn't work.

**Comment by lpil** [comment]
I would like to support the behaviour specified in that example, it makes parsing some binary formats much easier, and I agree with Peter's reasoning that it is not assigning a second variable.

I would see the later use of the variable as being similar to using a pattern assigned variable in guard clause.

**Comment by tomwhatmore** [comment]
Ok, I'll see if I can get it working. Are there any other pattern variants where this behaviour would be useful?

**Comment by lpil** [comment]
I can't think of any at the moment.
