### ISSUE TITLE
`gleam eunit` runs eunit

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#648]
We have a basic version of this implemented already, further improvements are needed:

- [x] Exit 1 if tests fail
- [ ] Pretty progress output
- [ ] Pretty results output

Will want to implement Erlang code in an escript or similar to achieve this, similar to how the Erlang compiling escript works.

**Comment by thehabbos007** [comment]
I had luck turning the eunit command into a escript call yesterday, however, when it comes to pretty printing the output from `eunit:test/2` I'm running intro trouble. Seems like the proper way to intercept test results is to implement a behaviour and start that in your application, like https://github.com/eproxus/unite/blob/master/src/unite_compact.erl

Has anyone tried to do something like that from within an escript? Seems like we have to do some trickery here to make it work neatly :)

**Comment by lpil** [comment]
It may not be possible to implement this unless we have some way of compiling multiple modules into an escript, or alternatively we'll have to use something that is not an escript. This may be blocked until #695 is done

**Comment by thehabbos007** [comment]
So I looked into this more, and it looks like quite the task to create such a prettifier for eunit. I have a working version of the compiler running a [custom eunit formatter (same as rebar I believe)](https://github.com/eproxus/unite) and it looks like this for gleam
![image](https://user-images.githubusercontent.com/6988668/86518418-48f6d680-be32-11ea-9118-210b6a8af6c9.png)
If we want to go with the easy route, we could use the above project, so meaning adding the copyright notices on the top of those files in Gleam, of course. Thoughts?

We can always look into revamping this futher down the line, but having rebar like output would be nice. We just want to make sure to properly comply with the MIT license of the code.

**Comment by lpil** [comment]
That sounds good. The library is only one file which would me it easier to distribute.

Do you know what we would need to do to be compliant with the licence?

**Comment by thehabbos007** [comment]
The library depends on some color functions. I think it is https://github.com/julianduque/erlang-color/ as this is what I had to include for it to compile.

Both these libraries are MIT, so the notice states: "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."
So including the respective licenses in every file should suffice to comply with the license :)
