### ISSUE TITLE
Make module names explicit and required at top-level

### ISSUE THREAD

**Issue by OmanF** [gleam-lang/gleam#654]
Currently, according to the "Gleam book", modules are inferred by the file name of the file holding the code and are implicit per file/module.

That is restrictive and less helpful than explicit.

Restrictive in the sense that "one file - one module", a paradigm no other FP language I know of takes (certainly not Elixir, nor F#),
Having multiple modules per file can cut down file number in the entire project as well as keep all related code in the same "place" (i.e. file).

Less helpful in the sense that you have to remember/look up what file you're editing instead of scrolling to the top of the editor window and knowing in an instant.

**Comment by lpil** [comment]
Hello! Thanks for checking out Gleam.

The name of the module is explicit, it is written down in the file name.
We will not be introducing the ability to have a different module name to the file name, the reasoning is that it is confusing to have (for example) `src/list.gleam` be the file that contains the module `gen_server`. We want modules to be as easy to find as possible.

Seeing as there is always a link between the file name and the module name having the name duplicated in both the file name and a header in the file doesn't provide any advantages, just makes Gleam a touch more verbose.

If there is an additional feature or behaviour that module headers would unlock I would be interested in hearing about them, but we will not be changing a core part of the language without a very clear gain now. The language is a little too mature for that.

> Having multiple modules per file can cut down file number in the entire project as well as keep all related code in the same "place" (i.e. file).

My suggestion here is to make larger modules. Unlike in Elixir modules are not a first class data type, so there is little reason to construct extra modules beyond scoping.

> Restrictive in the sense that "one file - one module", a paradigm no other FP language I know of takes (certainly not Elixir, nor F#)

We follow Haskell, Elm, PureScript, Idris, and Erlang here, they only permit a single module per file.

As an extra fun bit of context, there are also languages which permit multiple files for the same module! Examples include Go, Common Lisp, Cojure, Java, and Scala.

**Comment by OvermindDL1** [comment]
F#, and what it's based on OCaml is also a modulename == filename.  You can define children modules within that module, but the filename is still the module name.

**Comment by lpil** [comment]
Thanks @OvermindDL1 !
