### ISSUE TITLE
[RFC] Minimal Supported Rust Version

### ISSUE THREAD

**Issue by scileo** [gleam-lang/gleam#659]
Hello everyone,
I am currently working on [butcher], a crate which will ease `Cow` handling, especially when it comes to destructuring and pattern-matching, in order to remove a lot of duplicate code required to fix #611. In this process, I had to write a proc_macro, which expands to an expression. It allows to perform additional compile-time checks, which allow to display an easy to understand error message, instead of providing borrow-checker errors to the user.

Such feature is not currently supported on stable rust, but should be available for the next release (see the [stabilization report]).

My question is: is there any targeted rust version or MSRV policy yet? As far as I know, CI uses latest stable release. I haven't find any other source of information.

[butcher]: https://github.com/scileo/butcher
[stabilization report]: https://github.com/rust-lang/rust/pull/68717#issuecomment-623197503

**Comment by lpil** [comment]
We target stable so any libraries that require nightly won't be usable in the compiler I'm afraid.

**Comment by scileo** [comment]
Thanks for your comment. I'll wait for it come to stable rust. This extra time will allow me to polish my APIs :)
