### ISSUE TITLE
Bit string patterns shouldn't be allowed let bindings

### ISSUE THREAD

**Issue by tomwhatmore** [gleam-lang/gleam#668]
A bit string pattern can always fail to match, so I think you should have to use `assert` instead. Not a big deal now but will be required to get exhaustiveness checking.

**Comment by lpil** [comment]
For sure! I think the #34 issue may cover this?

**Comment by tomwhatmore** [comment]
This would be part of implementing #34 for sure, but I was suggesting it as a separate issue because it could be done independantly of that task and finished much sooner. Would probably make sense to get it in for 0.10 so that this is how bit strings work from launch. It also isn't really related to the actual exhaustiveness checking algorithm.

**Comment by lpil** [comment]
We could do the same for strings and lists I guess!

**Comment by lpil** [comment]
See also #537

**Comment by lpil** [comment]
Closing this to be tracked in #34
