### ISSUE TITLE
Incorrect arity warning when piping into functions

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#672]
### Example

```rust
import gleam/should

pub fn hello_world() -> String {
  "Hello, from arity_error!"
}

pub fn hello_world_test() {
  hello_world()
  |> should.equal()
}
```

The following code will produce the following error. 

```
error: Incorrect arity
  /opt/app/arity_error/test/arity_error_test.gleam:9:3
  
9   hello_world()
    ^^^^^^^^^^^^^ expected 2 arguments, got 0
```

This error should be pointing at the line below, should.equal is the function that is expecting two arguments.

In addition it is only one argument short, because of the piping. I think this should say "expected 2 arguments, got 1" i.e. one came from the pipe.

Expected output would then be
```
10 |> should.equal()
     ^^^^^^^^^^^^^^^^ expected 2 arguments, got 1
```

I'm running on 0.9.0 to get this error

**Comment by lpil** [comment]
Thank you!
