### ISSUE TITLE
Add a label to todo.

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#678]
Record of a conversation that was had on IRC

https://matrix.to/#/!xBiwxFiVfVDbdvbbBu:matrix.org/$6eeTnz9NwRgBHWZSrQr7B0t0ry2HKkITR3PZduhAkK8?via=matrix.org&via=mozilla.org

```rust
case receive(Infinity)  {
  Ok(message) -> continue
  Error(Nil) -> todo("We should have waited forever")
}
```

**Comment by tomwhatmore** [comment]
I'll do this one
