### ISSUE TITLE
Permit use of functions defined later on in file

### ISSUE THREAD

**Issue by MainShayne233** [gleam-lang/gleam#682]
:wave: Hey! Apologies if this is already known, but I couldn't find anything with a quick search:

Gleam Versions:

Issue occurs on both local and CI.
- Local: `0.10.0-dev` (install from source)
- CI: `0.9.1` (install via Github Action)

Expected: If you have two functions, `A()` and `B()`, defined in the same module/file, they should be able to call on each other within their function definition regardless of the order in which they were defined in the module.

Actual: It appears that `A()` cannot call on `B()` if `A()` is defined before `B()` is defined.

Real code example:

Commit where I've moved the `to_string` function below the `length` function which uses the `to_string` function: https://github.com/MainShayne233/parcomb/commit/b8acedcb96286b740d1f71b9ce1648a2d820ef19

CI run: https://github.com/MainShayne233/parcomb/runs/812603227?check_suite_focus=true

Local run:

```sh
> rebar3 eunit

...
error: Unknown variable
   ââ /home/shayne/gleam/parcomb/src/parsable.gleam:18:6
   â
18 â   |> to_string()
   â      ^^^^^^^^^ did you mean `Nothing`?

The name `to_string` is not in scope here.

===> Unable to compile Gleam project
```

Commit where I've moved the `to_string` function back to being above the `length` function: https://github.com/MainShayne233/parcomb/commit/0a586dc024fce0500b27f5445e772f0fd3b3467f

CI run: https://github.com/MainShayne233/parcomb/runs/812605136?check_suite_focus=true

Local run:

```sh
> rebar3 eunit

...
===> Compiling parcomb
===> Performing EUnit tests...
..
Finished in 0.075 seconds
2 tests, 0 failures
```

**Comment by lpil** [comment]
This is an annoyance, for sure! This is related to https://github.com/gleam-lang/gleam/issues/346 as we could solve them both with the same expansion of the type inference algorithm.

**Comment by MainShayne233** [comment]
:heart: Much better title :stuck_out_tongue: Thanks for the speedy response, and I'm glad it's being prioritized! :slightly_smiling_face:
