### ISSUE TITLE
Render argument docs for custom type constructors in HTML documentation

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#697]
```rust
pub type Thing {
  Thing(
    /// This doc should be included
    one: Int,
    /// This doc should also be included
    two: Int,
  )
}
```

**Comment by leomindez** [comment]
Hello Louis, I would like to solve this issue, could you assign to me the issue?

**Comment by lpil** [comment]
Certainly! Thank you

**Comment by leomindez** [comment]
Hello Louis, I was reviewing the code and I just want to be sure that I am identifying correctly which files I need to modify.
I think I need to figure out how to include the args from AST into this function https://github.com/gleam-lang/gleam/blob/28c01253eb2f455aad7a0c0536de34aaba6e4248/src/docs.rs#L96
or maybe getting the arguments from this line to include them into doc HTML generated file https://github.com/gleam-lang/gleam/blob/28c01253eb2f455aad7a0c0536de34aaba6e4248/src/docs.rs#L108

Another thing I was wondering if you have a communication channel to talk about these doubts, 

Thank you Louis, have a good week 👍

**Comment by lpil** [comment]
Hey @leomindez ! Sorry about the slow reply.

I think this is bit more complicated than I first expected it to be. We'll need to change the AST for the constructor arguments to have a documentation attribute similar to how constructors do, and set that documentation at the same time as the constructor docs. Once we have that we can update the documentation rendering logic to include them too.

**Comment by leomindez** [comment]
Hey @lpil , how can I help you to do the needed changes? 
Or should we continue with another issue?

**Comment by lpil** [comment]
If you think it is clear to you how to do this please go ahead, but I don't think I've made it very clear so feel free to drop it if you don't think it's the right issue for you.

**Comment by leomindez** [comment]
@lpil I will take another issue to start learning and collaborating. 
Thanks for clarifying

**Comment by lpil** [comment]
Thank you, sorry about the confusion
