### ISSUE TITLE
"Gleam for Erlangers" and "Gleam for Elixirists" cheat sheets

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#707]
A page on the website (github.com/gleam-lang/website/) that gives a high level overview of Gleam, assuming a reader with Erlang knowledge. Information on how to call Gleam functions would also be good.

- [ ] Erlang
- [ ] Elixir

Examples from other languages:

- https://elixir-lang.org/crash-course.html
- https://reasonml.github.io/docs/en/syntax-cheatsheet
- https://reasonml-old.github.io/guide/ocaml/

**Comment by silmeth** [comment]
Old ResonML website also had [a comparison with OCaml](https://reasonml-old.github.io/guide/ocaml/) which was removed a few months ago (but I cannot find why) – also might be good as a reference example.

**Comment by lpil** [comment]
Thanks! I'll add that to the list

**Comment by CrowdHailer** [comment]
This example was shared in the IRC, it would be really useful to document how to use gleam records in Elixir

https://gist.github.com/QuinnWilton/4778d34697785e51ea5e571d1a82f4c9
