### ISSUE TITLE
Bit string documentation on website

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#709]
https://github.com/gleam-lang/website/

**Comment by tomwhatmore** [comment]
Think I'm probably the obvious candidate for this! I'll write something this evening. In general we're aiming for the website docs to not assume any pre-existing Erlang knowledge right?

**Comment by lpil** [comment]
Yes, though I think it's OK to link to Erlang docs for more detail if that would help. :) Thank you

**Comment by itsgreggreg** [comment]
Does this resolve this issue https://gleam.run/book/tour/bit-strings.html or were you guys looking for more information on the tour or some other section in the website?

**Comment by lpil** [comment]
That's a good start but I would like all the options that can be used with segments to be documented
