### ISSUE TITLE
Type aliases

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#71]
```rust
type IntMap = Map(Int, Int)
```

**Comment by djKooks** [comment]
@lpil would I try on this one if not done yet?
I'm pretty interested on your project, so hope to join on.

**Comment by lpil** [comment]
Hi @djKooks ! Contributions are very welcome :)
Do you have an idea of how you would implement this feature within the typer?

**Comment by djKooks** [comment]
@lpil thanks! I'll check and let you know.
