### ISSUE TITLE
warning when assert will never fail

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#711]
I don't know if this is important, but it's probably an indication you are not doing what you expect.

```rust
assert x = 2 + 2
```

I did this a few times this morning, because I was removing something that previously returned a result.
I think the biggest problem might be the following code.

```rust
let x = 3
io.debug(x)
assert x = 2 + 2
```

**Comment by lpil** [comment]
Going to merge this into #706
