### ISSUE TITLE
Add extra pipe operator suggestion

### ISSUE THREAD

**Issue by naomijub** [gleam-lang/gleam#712]
Maybe add a pipe operator like `|>>`. In elixir I have had situations that the captured argument was not supposed to be passed as the first argument, `regex` functions are a good example. Also Clojure has `->` as a `|>` and  `->>` as the proposed `|>`. The advantage of this in Gleam and Elixir is that it would work similar to the `as->` which allows you to define the position of the previous result. It would look something like this:

```
pub fn add(x: Int , y: Int ) -> Int {
  x + y
}

pub fn run() {
  1
  |> add(_, 3)
  |>> add(6, _)
  |> add(_, 9)
} 
```

which translates to:

```
pub fn run() {
  // This is the same as add(add(6, add(1, 3)), 9)
  1
  |> add(3)
  |>> add(6)
  |> add(9)
} 
```

**Comment by lpil** [comment]
The Gleam pipe operator doesn't require the argument to be piped into the first position, this will work

```rust
1
|> add(3) // First position
|> add(6, _) // Second position
```

Does that solve the problem?

**Comment by naomijub** [comment]
Sure!

I was testing with this case only 
```
  1
  |> add(3)
  |>> add(6)
  |> add(9)
```

**Comment by lpil** [comment]
Great! Glad it worked :)
