### ISSUE TITLE
Compiled erlang tuple has wrong amount of elements

### ISSUE THREAD

**Issue by MainShayne233** [gleam-lang/gleam#714]
Version:

```sh
❯ gleam --version
gleam 0.10.0-dev
```

(found same behavior w/ latest `0.11.0-dev` built from source)

I ran into an issue where it seems that a tuple in the generated erlang code has an incorrect amount of elements.

Code being referenced is pinned at [this commit](https://github.com/MainShayne233/xenon/commit/85eb827752d99f6a0c3e80067992473a8b06b525).

Here is my function:

```rust
fn do_parse(doc: RawDoc) -> Result(XmlElement, String) {
  case doc {
    tuple(label, _, _, _, _, _, _, _, _, _, _, _) -> parse_xml_element(doc)
    other -> {
      io.debug(other)
      Error("Unhandled node type")
    }
  }
}
```

The generated  erlang in `gen` looks like:

```erlang
do_parse(Doc) ->
    case Doc of
        {Label, _} ->
            parse_xml_element(Doc);

        Other ->
            gleam@io:debug(Other),
            {error, <<"Unhandled node type"/utf8>>}
    end.
```

As you can see, the `{Label, _}` tuple is a 2-element tuple, but the tuple in the gleam code has 12 elements.

**Comment by lpil** [comment]
That is extremely strange! Thanks for the report

**Comment by tomwhatmore** [comment]
I'll take a look at this

**Comment by tomwhatmore** [comment]
Hi @MainShayne233, I think that this code shouldn't compile at all! You have defined `RawDoc` as being a tuple with 2 elements, and are then trying to match it against a 12 element tuple, which should be a type error. I've added a commit that will make this return an error properly. Does that solve the issue for you or have I completely misunderstood what you were trying to do?

**Comment by MainShayne233** [comment]
@tomwhatmore :exploding_head: That makes so much sense! Awesome find and fix!

**Comment by MainShayne233** [comment]
Just rebuilt `gleam` from `main` and tried to rebuild my project and got:
```sh
error: Incorrect arity
   ┌─ /home/shayne/gleam/xenon/src/xenon.gleam:24:10
   │
24 │   assert tuple(_, atom_name, _, _, _, _, _, _, _, _, _, _) = doc
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 arguments, got 12
```

:confetti_ball:
