### ISSUE TITLE
Record constructor labelled arguments being re-ordered incorrectly

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#721]
This code is given an unexpected type error.

```rust
pub type Box {
  Box(a: Nil, b: Int, c: Int, d: Int)
}

pub fn main() {
  Box(b: 1, c: 1, d: 1, a: Nil)
}
```
```
error: Type mismatch
  ┌─ /home/louis/src/gleam/http/src/wjetw.gleam:6:16
  │
6 │   Box(b: 1, c: 1, d: 1, a: Nil)
  │                ^

Expected type:

    Nil

Found type:

    Int
```
When these labelled arguments are given in this order arguments c and a get swapped.

**Comment by lpil** [comment]
Nope! A mistake in my code. Phew

**Comment by tomwhatmore** [comment]
Shall I fix this or are you doing it?

**Comment by lpil** [comment]
I've not looked at this yet, I've been working on the HTTP libraries, if you want it please go ahead.

I'm wondering if the approach I took to reordering the fields is flawed and we would do better creating a new vector rather than mutating the existing one in place.

**Comment by tomwhatmore** [comment]
Might be simpler, yeah. I'll give it a go

**Comment by tomwhatmore** [comment]
Am I misunderstanding the intended behaviour or shouldn't this be an `Error::PositionalArgumentAfterLabelled`?

https://github.com/gleam-lang/gleam/blob/a476d66954e9b4120b137628b9558ce27c9ab86a/src/typ/tests.rs#L81-L120

**Comment by lpil** [comment]
I don't think so? All of the arguments are given with labels there. Perhaps I'm misunderstanding?

**Comment by tomwhatmore** [comment]
I'm sure it's me who is confused! A `CallArg` with `label: None` isn't a positional argument?

**Comment by lpil** [comment]
Oh right! Sorry I got confused there. Yes, I think you are right and that should be an error. Seems this whole area is buggy!

**Comment by tomwhatmore** [comment]
Confusion is clearly the order of the day! Think I've fixed it then, but I'll need to update some tests.

**Comment by lpil** [comment]
Thank you Tom!!
