### ISSUE TITLE
Support tuple access in guards

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#724]
```rust
case x {
  [first, ..rest] if first.0 == key -> "ok"
  _ -> "ko"
}
```

**Comment by mrgleam** [comment]
@lpil I try to add tuple index and field access in pattern function but it still do not work for me. Do you have any suggestions for solve this issue?
[
<img width="815" alt="Screen Shot 2563-10-06 at 11 51 10" src="https://user-images.githubusercontent.com/11692854/95160309-6721f900-07ca-11eb-8d26-576f02d34556.png">
](url)

**Comment by lpil** [comment]
Hey @mrgleam ! Thanks for your help.

I think we'd need to make these changes:

Update the ClauseGuard type to have a tuple index variant containing the tuple value and the field number
https://github.com/gleam-lang/gleam/blob/main/src/ast.rs#L391

Update the parser to parse the new `guard.1` syntax
https://github.com/gleam-lang/gleam/blob/main/src/grammar.lalrpop#L505
It would be similar to the `expr.1` syntax: https://github.com/gleam-lang/gleam/blob/main/src/grammar.lalrpop#L530

Add type inference for this new variant to the `infer_clause_guard` function. It would need to return an error if size of the tuple being indexed is not know.
https://github.com/gleam-lang/gleam/blob/main/src/typ/expr.rs#L824

Add Erlang rendering to the `bare_clause_guard` function which would look similar to the `tuple_index` function.
https://github.com/gleam-lang/gleam/blob/main/src/erl.rs#L830
https://github.com/gleam-lang/gleam/blob/main/src/erl.rs#L1174

Does that feel like enough information to get started?

**Comment by mrgleam** [comment]
Thank you @lpil 

I tried to follow your step but I found error on step "Update the parser to parse the new guard.1 syntax"

I add this line (in picture)
<img width="893" alt="Screen Shot 2563-10-06 at 22 15 50" src="https://user-images.githubusercontent.com/11692854/95221719-edb5f500-0821-11eb-80cf-584b5b25280e.png">

sorry, I'm not familiar with lalrpop
