### ISSUE TITLE
Support lists in constant expressions

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#725]
```rust
const x = [1, 2, 3]
```

**Comment by Tuxified** [comment]
👋  is this still needed? I'm a bit new to Gleam, so I tried this and I got an expected type error:

```rust
const x = [1, 2, 3]

const result = "Hello, from gleam_test!"

pub fn hello_world() -> String {
  result
	x
}
```

**Comment by lpil** [comment]
Ah yes! This has been implemented. Thank you for notifying me

**Comment by Tuxified** [comment]
Alright, then I'll start looking for a different issue to contribute, thanks for the "good first issue" tags 🤗

**Comment by lpil** [comment]
Maybe this one? https://github.com/gleam-lang/gleam/issues/761

I can offer some guidance on it.

It will likely mean quite a few of the Erlang generation tests need updating though as the variable output format will change a little. Might be a bit boring!
