### ISSUE TITLE
Formatter: Sort imports into alphabetical order

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#727]
```rust
import b
import c
import a
```

Is formatted as 

```rust
import a
import b
import c
```

**Comment by CrowdHailer** [comment]
Should this break on comments, if I want to group import separately
```rust
import a
import c
// comment
import b
import c
```

**Comment by lpil** [comment]
Good question! Should we split imports into groups before sorting them then?

**Comment by NobbZ** [comment]
In python and got it is quite common to group imports by roughly the following categories, while sorting alphabetically within each category.

* stdlib
* third party libraries
* in-house/same-project-group libraries
* same package imports

**Comment by lpil** [comment]
Maybe the rule could be that the formatter will split imports into a new block if it is preceeded by a comment?

**Comment by NobbZ** [comment]
In go the formatter just sorts each block individually, separated by newlines. It will not regroup imports. In this regard it just assumes that the developer is right.

For python, the most commonly used tool (from my limited experience), seems to be `isort`, which does indeed try to not only sort, but also categorize and requires additional configuration for the "inhouse" category.

Personally I prefer the approach taken by go. It is more flexible.

Requiring a comment as delimiter for groups feels a bit like the go approach, but is more verbose.

**Comment by lpil** [comment]
Great points, thank you. I especially agree with you that the go style is more flexible.

How about a comment or an empty line?

**Comment by NobbZ** [comment]
One ore more lines of whitespace only, under the assumption that a comment is just whitespace. Sounds like a good definition for the rule I think.

**Comment by lpil** [comment]
I'm not sure this is worth putting work into

**Comment by inoas** [comment]
I would prefer this but I can see why this is low priority at best.

I also got wind of that import statements can be anywhere in the file.

Is this a feature to stay? Would it be even nice to bundle imports in larger modules ontop of blocks that require those? An opinionated formatter could make the decision to move all imports to the top or let them be.

**Comment by lpil** [comment]
The formatter currently moved them to the top but it does not sort them. Sorting would be good but it needs to preseve comments to be mergable.
