### ISSUE TITLE
Permit newlines in assigned case expressions

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#742]
```rust
let x = case y {
  1 -> 1

  2 -> 2

  _ -> 3
}
```

**Comment by thehabbos007** [comment]
Is this in terms of compiling or formatting? The code above seems to compile for me on main :)

**Comment by QuinnWilton** [comment]
I believe this is about formatting. The above code will get condensed such that there's no newlines between patterns iirc.

**Comment by lpil** [comment]
Yes that's right, I'm talking about formatting. Sorry for the confusion.
