### ISSUE TITLE
uft8 and uft8_codepoint both match as a utf8_codepoint type

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#744]
I might be wrong in my understanding of the expected behaviour but I believe the following is a bug.

I think this code should compile
```rust
  let <<"ab":utf8, rest:utf8>> = "abcd"
  should.equal("cd", rest)
```

it however fails because the type of rest is `UtfCodepoint`.
My assumption is if the match was to say `rest:utf8_codpoint` explicitly then the type of rest should be UtfCodepoint and this would be the correct compilaton failure. However I think that `rest:utf8` should return rest with a type of string.

**Comment by lpil** [comment]
I agree with you that this would be a desired behaviour, but I'm afraid that's how bit string pattern matching works in Erlang, and we're limited by what Erlang supports.

The bit segment `X/utf` will only ever match a single character. It's not possible to assert that the rest of a bit string is utf8 encoded in a pattern.

**Comment by CrowdHailer** [comment]
Would it make sense to only support the qualifier utf8_codepoint in that situation?

**Comment by lpil** [comment]
Maybe! I would be interested in knowing what other people think

**Comment by lpil** [comment]
@QuinnWilton @thehabbos007 @tomwhatmore Any thoughts?

**Comment by QuinnWilton** [comment]
I don't have a good answer off the top of my head. I'll have to do some reading about handling UTF-8 in Erlang I think, since it isn't something I have any firsthand experience with.

**Comment by thehabbos007** [comment]
I'm in the same boat as Quinn here, I haven't done enough with it to have insight, will drop a comment if I stumble upon anything though :)

**Comment by tomwhatmore** [comment]
Yeah that definitely lends itself to a nicer explanation message. I'll make it an error.
