### ISSUE TITLE
Pattern matching on bitstrings formats strangely

### ISSUE THREAD

**Issue by QuinnWilton** [gleam-lang/gleam#748]
I don't know that this is a bug per se, but in the project I'm working on, my code formats like this:

```
  case data {
    <<0:4, nnn:12>> -> InstSYS(address: nnn)
    <<0:4, 0:4, 14:4, 0:4>> -> InstCLS
    <<0:4, 0:4, 14:4, 14:4>> -> InstRET
    <<1:4, nnn:12>> -> InstJPAbsolute(address: nnn)
    <<2:4, nnn:12>> -> InstCALL(address: nnn)
    <<3:4, x:4, kk:12>> -> InstSEImm(vx: registers.to_register(x), value: kk)
    <<4:4, x:4, kk:12>> -> InstSNEImm(vx: registers.to_register(x), value: kk)
    <<
      5:4,
      x:4,
      y:4,
      0:4,
    >> -> InstSEReg(vx: registers.to_register(x), vy: registers.to_register(y))
    ... // more patterns after this
  }
```

I'm not sure what the ideal formatting is, but I would prefer the pattern not break in this case. Something like this would be easier to read, for example:

```
  case data {
    <<0:4, nnn:12>> -> InstSYS(address: nnn)
    <<0:4, 0:4, 14:4, 0:4>> -> InstCLS
    <<0:4, 0:4, 14:4, 14:4>> -> InstRET
    <<1:4, nnn:12>> -> InstJPAbsolute(address: nnn)
    <<2:4, nnn:12>> -> InstCALL(address: nnn)
    <<3:4, x:4, kk:12>> -> InstSEImm(vx: registers.to_register(x), value: kk)
    <<4:4, x:4, kk:12>> -> InstSNEImm(vx: registers.to_register(x), value: kk)
    <<5:4, x:4, y:4, 0:4>> -> {
      InstSEReg(vx: registers.to_register(x), vy: registers.to_register(y))
    }
    ... // more patterns after this
  }
```

**Comment by CrowdHailer** [comment]
I find the same or similar behaviour in matches.

I think currently I get

```rust
assert Ok(
  _
) = long_function(big_arguments)
```

where as I would prefer
```rust

```rust
assert Ok(_) = 
  long_function(big_arguments)
```

P.s. I don't feel strongly one way of the other but it looks like a supporting case, and potentially having consistency would be good

**Comment by lpil** [comment]
I would prefer this too! Let's look at how we could do this.

**Comment by QuinnWilton** [comment]
I don't know if I should make a new issue, but the same problem seems to occur for constants:

```
const font = <<
  240,
  144,
  144,
  144,
  240,
  32,
  96,
  32,
  32,
  112,
  240,
  16,
  240,
  128,
  240,
  240,
  16,
  240,
  16,
  240,
  144,
  144,
  240,
  16,
  16,
  240,
  128,
  240,
  16,
  240,
  240,
  128,
  240,
  144,
  240,
  240,
  16,
  32,
  64,
  64,
  240,
  144,
  240,
  144,
  240,
  240,
  144,
  240,
  16,
  240,
  240,
  144,
  240,
  144,
  144,
  224,
  144,
  224,
  144,
  224,
  240,
  128,
  128,
  128,
  240,
  224,
  144,
  144,
  144,
  224,
  240,
  128,
  240,
  128,
  240,
  240,
  128,
  240,
  128,
  128,
>>
```

Better would probably be to still break it onto multiple lines, but put more than one byte per line.

**Comment by lpil** [comment]
I think that's a different issue, and it's a formatting question we could ask for tuples and lists too. It could be implemented using the new flex group printer algebra

**Comment by lpil** [comment]
I have been unable to work out how to implement this using our current algebra. I think we may need to implement Elixir's next_break_fits.

https://github.com/elixir-lang/elixir/blob/11ce4999c54f1da9766e1905bef96a722ae6d0b3/lib/elixir/lib/inspect/algebra.ex#L629-L675

**Comment by lpil** [comment]
I tested using Elixir's printing algebra and it seems to work

https://github.com/lpil/learning/blob/b9830b00c2b546a0ffa43097ebcb6dd0a858c4e0/elixir/next_break_fits/test/next_break_fits_test.exs

Looks like this is the way to go.

**Comment by QuinnWilton** [comment]
Thank you!!! I'll rebuild Gleam today and test the new formatter out.

**Comment by lpil** [comment]
@QuinnWilton Still not quite there yet, there's a bunch of other things to neaten up after this change, but I'm getting there!

**Comment by lpil** [comment]
Alright we might be good now! Let me know if you find any oddities
