### ISSUE TITLE
Allow using `_` as a separator when defining integers and floats

### ISSUE THREAD

**Issue by QuinnWilton** [gleam-lang/gleam#756]
This is a fairly popular feature in many modern languages, Elixir included: https://hexdocs.pm/elixir/syntax-reference.html#numbers

```
let n = 1_000_000
```

What do you think?

**Comment by lpil** [comment]
Tada! https://github.com/gleam-lang/gleam/commit/164bca45f0ddefa1031482959ea16935e9bb94b1

I wasn't able to permit underscores to the right of the `.` I'm afraid, ran into some parser problems that I didn't want to tackle now
