### ISSUE TITLE
Conflict in variable name generation

### ISSUE THREAD

**Issue by QuinnWilton** [gleam-lang/gleam#761]
I haven't been able to find a minimal example, but this block [here](https://github.com/QuinnWilton/gleam-chip8/blob/master/src/chip8/emulator.gleam#L368) is generating the following Erlang:

```erlang
            X1 = chip8@registers:read(erlang:element(3, Emulator), Vx23),
            X0 = X1 div 100,
            X1 = (X1 rem 100) div 10,
            X2 = X1 rem 10,
```

Since `X1` gets reused, I get a match error at runtime. I've temporarily worked around this by changing the first variable to `n` instead.

**Comment by lpil** [comment]
Variable rewriting continues to be a pain in the butt! Thank you

**Comment by lpil** [comment]
Minimal reproduction:

```rust
fn main() {
  let x = 1
  let x = 1
  let x1 = 2
  x
}
```

I think we should start adding a `@` between the variable name and the iteration number to prevent clashes.

```rust
let x = 1
let x = 2
x
```
```erlang
X = 1,
X@1 = 1,
X@1.
```
