### ISSUE TITLE
0.11.0-rc1 won't run on Mac

### ISSUE THREAD

**Issue by QuinnWilton** [gleam-lang/gleam#768]
I'm not sure if the upload got corrupted or something, but the Mac build doesn't seem to work.

```fish
❯ tar xvf gleam-v0.11.0-rc1-macos.tar.gz 
x gleam

~/Downloads via 🐍 v2.7.16 
❯ ./gleam --version
Failed to execute process './gleam'. Reason:
exec: Exec format error
The file './gleam' is marked as an executable but could not be run by the operating system.

~/Downloads via 🐍 v2.7.16 
❯ shasum gleam
322790fce84bcd91bcceae6baebef55ca1291642  gleam

~/Downloads via 🐍 v2.7.16 
❯ file gleam
gleam: data
```

**Comment by QuinnWilton** [comment]
Contrast this with the 0.10.1 build:

```fish
~/Downloads via 🐍 v2.7.16 
❯ tar xvf gleam-v0.10.1-macos.tar.gz 
x gleam

~/Downloads via 🐍 v2.7.16 
❯ file gleam
gleam: Mach-O 64-bit executable x86_64
```

**Comment by lpil** [comment]
Here's the CI build that produced that binary: https://github.com/gleam-lang/gleam/runs/1015850357?check_suite_focus=true

**Comment by lpil** [comment]
Link to the tarballed binary from the release -> https://github.com/gleam-lang/gleam/releases/download/v0.11.0-rc1/gleam-v0.11.0-rc1-macos.tar.gz

**Comment by lpil** [comment]
I'll try re-running that build

**Comment by QuinnWilton** [comment]
Let me know when it's done and I'll test it out!

**Comment by lpil** [comment]
Could you try again please?

**Comment by QuinnWilton** [comment]
I'm still seeing the issue. I also just noticed the file sizes for the release:

![image](https://user-images.githubusercontent.com/285821/91086192-6f035080-e603-11ea-9771-e45372447c7c.png)

The MacOS build being that much smaller seems off to me.

**Comment by QuinnWilton** [comment]
I've built a release locally, with `cargo build --release`, and uploaded it here if you'd find it useful. This build does work for me.

[gleam-0.11.0-rc1-macos.tar.gz](https://github.com/gleam-lang/gleam/files/5119823/gleam-0.11.0-rc1-macos.tar.gz)

**Comment by lpil** [comment]
Thank you

**Comment by lpil** [comment]
OK that's working now, thank you. I don't understand why CI didn't work here. I'm going to cut a rc2 to see if that works.
