### ISSUE TITLE
Test uploaded binaries as part of CI release process

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#769]
https://github.com/gleam-lang/gleam/blob/main/.github/workflows/create_release.yaml

For each OS, after uploading the binary archive to GitHub download it, extract it, and then run it to see if it works.

This will help detect problems like #768

**Comment by isacsund** [comment]
Hello!
I would like to take a stab at this, and also refactor the CI pipeline at the same time to see if it will help with the OSX builds.

**Comment by lpil** [comment]
That would be great, thank you @isacsund

**Comment by michallepicki** [comment]
I think this is implemented! The release workflow executes `gleam --version` to see if the binary runs on given platform.

**Comment by lpil** [comment]
Thank you 💜
