### ISSUE TITLE
Invalid Erlang variable rewriting

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#772]
```rust
pub fn filter(board, with predicate) {
  let reduce = fn(row, acc) {
    let tuple(index, board) = acc
    case predicate(row) {
      False -> tuple(index, board)
      True -> tuple(index + 1, merge(board, raise_by_rows(row, index)))
    }
  }
  let tuple(_, filtered) = fold_bottom(board, tuple(0, new()), reduce)
  filtered
}
```

I'll create a minimal reproduction later.

**Comment by tomwhatmore** [comment]
Who would have guessed that the hardest parts of creating a compiler would be rewriting variable names and formatting blocks of code onto new lines properly? This is what the textbooks will never tell you.

**Comment by lpil** [comment]
I think the hardest might be exhaustiness checking, but sticking an integer on a variable name might be the second trickiest

**Comment by CrowdHailer** [comment]
I've hit this bug a few times. With variables called `id` couldn't work out the minimal repro. Glad to see it's been raised here
