### ISSUE TITLE
Questions of labelled function arguments

### ISSUE THREAD

**Issue by iredmail** [gleam-lang/gleam#792]
About labelled function arguments in Language Tour:

```
pub fn replace(
  in string: String,
  each pattern: String,
  with replacement: String,
) {...}

// Calls
replace(in: "A,B,C", each: ",", with: " ")
replace(each: ",", with: " ", in: "A,B,C")
replace("A,B,C", ",", " ")
```

Questions:

### Why not use the original argument names directly?

For example:
```
replace(string: "...", pattern: "...", replacement: "...")
replace(pattern: "...", string: "...", replacement: "...")
```

- Isn't it how function arguments used in other programming language? Why is extra labelled arguments introduced?
- If we have to use a label, why not use original argument name as its own label since we already make argument name clear and easy to understand? Naming is hard, why name a argument twice with different names (e.g. `string` and `in`)?

I tried with original argument names, but failed:

```
error: Unknown labels
  ┌─ tmp/gleam/t/src/t.gleam:4:20
  │
4 │     string.replace(string: "A,B,C", pattern: ",", replacement: " ")
  │                    ^^^^^^^^^^^^^^^  ^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^ did you mean `each`?
  │                    │                │              
  │                    │                did you mean `in`?
  │                    did you mean `in`?

The other labelled arguments that this constructor accepts are `each`, `in`, `with`.
```

### Why not use the popular `=` here?

```
replace(string="...", pattern="...", replacement="...")
```

It's much easier to use and remember.

BTW, Gleam looks awesome.  👍

**Comment by lpil** [comment]
It's common to have the argument name and the label name to be the same, but we've opted to go down the path that Swift has taken and permit them to be different. This allows us more flexibility in our naming, chosing names that are optimal for the definition and at the call site.

> Why not use the popular = here?

We may use this for optional arguments later :)

**Comment by iredmail** [comment]
> It's common to have the argument name and the label name to be the same, but we've opted to go down the path that Swift has taken and permit them to be different. This allows us more flexibility in our naming, chosing names that are optimal for the definition and at the call site.

ok, it's permitted to be different, i suppose this means if no labelled names, then use the argument names is ok too. But why cannot we use the argument names directly? It feels really very odd and not adjective. Please consider supporting argument names:

```
replace(string: "...", pattern: "...", replacement: "...")
replace(pattern: "...", string: "...", replacement: "...")
```

**Comment by lpil** [comment]
It's permittable for the label and the argument to have the same name:

```rust
fn go(x x: Int) -> Int {
  todo
}
```

I'm afraid it is too late to change this part of the language unless there is a clear advantage to doing so that was not considered when we were designing this language feature.

**Comment by iredmail** [comment]
This is very odd.
Since Gleam is not widely used in production, i think we still have time to make it "right".

**Comment by iredmail** [comment]
About `clear advantage`, i think it's very clear that an extra name is duplicate and not necessary at all.

**Comment by lpil** [comment]
The issue is that what you're saying is "right" is not objectively better, it is just your preference. At points in the past Gleam did behave this way, but during the design period of this feature we decided that the current behaviour is preferred, though there is not much in it.

**Comment by iredmail** [comment]
- ok. thanks for the explanation.
- about "right", i hope you see i used quotes (`"right"`) to be humble and it doesn't mean what i said is absolute right.

**Comment by iredmail** [comment]
btw, out of curiosity, is there any other programming language use labelled argument like Gleam?

**Comment by lpil** [comment]
Swift is the main one, though they're different in that functions always have labels

**Comment by iredmail** [comment]
Thanks. I will do some research.
