### ISSUE TITLE
Cannot compile stdlib on Windows

### ISSUE THREAD

**Issue by sharno** [gleam-lang/gleam#801]
I'm not able to compile `stdlib`
first time running gleam showed this error which is shown as well when running `rebar3 eunit`

```
PS C:\Users\sharno\projects\gleam_stdlib> rebar3 eunit
===> Verifying dependencies...

error: Syntax error
   ├ó┬ö┬î├ó┬ö┬Ç \\?\C:\Users\sharno\projects\gleam_stdlib\test\gleam\bit_builder_test.gleam:75:2
   ├ó┬ö┬é
75 ├ó┬ö┬é }
   ├ó┬ö┬é  ^ Unexpected end of file


===> Unable to compile Gleam project
```

I checked the file and not sure what's the problematic syntax.

When I removed the test folder completely just to try, this error appeared instead:
```

error: Unknown module field
  ├ó┬ö┬î├ó┬ö┬Ç \\?\C:\Users\sharno\projects\gleam_stdlib\src\gleam\set.gleam:1:19
  ├ó┬ö┬é
1 ├ó┬ö┬é import gleam/map.{Map}
  ├ó┬ö┬é                   ^^^

The module `gleam/map` does not have a `Map` field.
```

What am I missing?

**Comment by lpil** [comment]
You were right @sharno ! That was the problem. Comments didn't get terminated correctly

**Comment by sharno** [comment]
@lpil  Awesome! thanks a lot for dealing with this 😄 
I'm excited for Gleam and want to build something with it

**Comment by lpil** [comment]
Awesome!

I'm primarily on Windows now so hopefully this won't happen again!
