### ISSUE TITLE
Documentation layout improvement to reduce scrolling

### ISSUE THREAD

**Issue by sporto** [gleam-lang/gleam#803]
Hi

![image](https://user-images.githubusercontent.com/1005498/96388628-dd285600-11f5-11eb-83d3-789930879df3.png)

I find the documentation layout hard to use. There is a lot of scrolling up and down involved.
E.g. I click `is_empty` and the pages goes down. Then I have to scroll all the way up to find the other functions in the module.

Is this a custom layout or something pre-defined by hex?

Optimally the layout could have scroll independed panels for modules, functions and content. e.g.

![image](https://user-images.githubusercontent.com/1005498/96388785-ed8d0080-11f6-11eb-85fa-4ca06efca63a.png)

I would be happy to help if this is flexible

**Comment by sporto** [comment]
@lpil I'll have a go at this, thanks

**Comment by sporto** [comment]
@lpil I see the templates but I have no clue how to build them and preview something. Can you give me some instructions or point me to something on how is this done? Thanks

**Comment by lpil** [comment]
There's no mechanism for previewing etc I'm afraid, I edited some generated docs manually, copied to the templates, and the recompiled the compiler + run `gleam docs build` to test.

**Comment by michallepicki** [comment]
I think this can be closed now?

**Comment by lpil** [comment]
Thanks @michallepicki
