### ISSUE TITLE
Help compiler discriminate between module.function and variable.field when variable name shadows module name

### ISSUE THREAD

**Issue by edkelly303** [gleam-lang/gleam#807]
```gleam
import power.{Power}

pub fn do_something(power: Power) -> Int {
  power.to_int(power)
}
```
`gleam build` gives the following error message:
```
error: Unknown field
  ┌─ /path/whatever.gleam:4:8
  │
4 │   power.to_int(power)
  │        ^^^^^^^ This field does not exist
```

@lpil commented on Discord: 

> In this case the variable is shadowing the module. This is probably one of the most frequent issues in Gleam
>
> In this case the compiler has all the information needed to be able to tell that power means the module (it knows it can't be the variable because it has type Power, which doesn't have that field.
> 
> ```
> if type_is_known && !does_not_have_field {
>   check_if_module_access()
> } else {
>   type_error()
> }
> ```
> We do something like this with the pipe operator already.

**Comment by lpil** [comment]
A great suggestion, thanks @rasputin303 . I want this feature in for sure.

**Comment by QuinnWilton** [comment]
I'm working on this today!

**Comment by lpil** [comment]
Thanks Quinn!
