### ISSUE TITLE
Windows Executable for v0.12.0-rc3?

### ISSUE THREAD

**Issue by sharno** [gleam-lang/gleam#817]
I'm not sure why CI cannot find the file to upload, maybe a rerun can solve it?
https://github.com/gleam-lang/gleam/runs/1303302986?check_suite_focus=true

**Comment by lpil** [comment]
Oh dear I must have broken it when fixing the Linux + OSX ones. Sorry about that :( I'll fix this ASAP.

**Comment by lpil** [comment]
rc4 is out and the Windows build now works. Phew!
