### ISSUE TITLE
type constructors scope/qualified name

### ISSUE THREAD

**Issue by sharno** [gleam-lang/gleam#818]
Is there a way to scope or fully qualify a type constructor to use the same constructor like one of the existing types?

example:
```
type FindResult(value) = {
  Error
  Ok(value)
}
```

I couldn't make it possible to use the constructors of this type for example as they always conflict with `Result`'s constructors. I wanted those exact constructor names to FFI with erlang code

**Comment by lpil** [comment]
No there is not. It would be useful to be able to refer to prelude types once shadowed like this, once we have https://github.com/gleam-lang/gleam/issues/614 it will be possible to re-export `Ok` and `Error` in the `gleam/result` module so they can be overridden locally in a module.

**Comment by sharno** [comment]
Absolutely, I don't want subtyping 😁, just being able to fully qualify constructors to be able to use the same constructor name in different types would be great.

BTW, is `Result` type constructors defined inside the compiler? I didn't see it in stdlib

**Comment by sporto** [comment]
My two cents.

Based on my experience with Rust (which uses qualified constructors) and Elm (which doesn't) I lean towards qualified constructors. 

The unqualified ones are nice and terse when the app is small. But as it grows bigger the qualified ones are easier to use (you can easily see what type). 

In Elm we use a lot of custom types like:

```elm
type Stage = Stage_Idle | Stage_Editing ... | Stage_New ...
```

We end up adding the name of the type as prefix so we can understand the code better.

**Comment by lpil** [comment]
> Absolutely, I don't want subtyping 😁, just being able to fully qualify constructors to be able to use the same constructor name in different types would be great.

Ah yes! This is what I want. Once we have #614 we can do this:

```rust
import gleam/result

type MyResult {
  Ok
  Error(String)
}

fn main() {
  let normal_result = result.Ok(1)
  let my_result = Ok
}
```

@sporto It's too late to introduce namespaces for each custom type I'm afraid, we are to continue down the ML tradition of them residing in the module namespace.

**Comment by lpil** [comment]
Closing this to be tracked in #614. Please reopen if you think there is more then that, thank you.

**Comment by lpil** [comment]
> Forgive me for being ignorant of Gleam's development, but why is it too late?

The language is now sufficiently mature that breaking changes and major changes to the core language are extremely unlikely. We would need to have a very strong motivator such as a soundness bug in the design of the type system.
