### ISSUE TITLE
GitHub action workflow for automatically publishing new versions to Hex when a tag is created in a Gleam library

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#824]
Currently we have automatic release functionality for the compiler, it would be good to also have this for the Gleam projects it generates.

This would need to be rendered by commentted out by default so that users can opt-in to this functionality.

**Comment by lpil** [comment]
We can render a file containing the required workflow definition but we can comment out the value for `on` so that it won't run unless the user uncomments that section and adds their hex API key to the repo

Here's an example from one of our repos at my work

https://github.com/EmbarkStudios/opensource-template/blob/3f181f5e1385a7e98cdea3fb62cb77655728a46d/.github/workflows/rust-ci.yml#L3

**Comment by RodrigoLeiteF** [comment]
Ah, I understand. This should be added to the Github Actions workflow the compiler generates when creating a new project. I wasn't aware of that feature (which is pretty cool by the way), and thought we'd close this issue by developing something like [the NPM Publish action](https://github.com/marketplace/actions/npm-publish) which users can then add to their projects.

I'll see if I can get it done, thanks for the follow-up.

**Comment by lpil** [comment]
Great! Thank you

**Comment by lpil** [comment]
Closing for now as it's not a priority, but please continue if you would like to pick this one up
