### ISSUE TITLE
Update libraries to use gleam_otp v0.1.2

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#825]
Libraries should be updated to return a StartResult from their start functions as well.

https://github.com/gleam-lang/cowboy
https://github.com/gleam-lang/elli

**Comment by l1x** [comment]
Hi @lpil, I would love to work on these. I have forked the projects and modified the code Result -> StartResult but it cannot find StartResult. Which package should I import?

**Comment by michallepicki** [comment]
I believe that would be `gleam/otp/actor.{StartResult}`. There's a PR for cowboy open already that might fix it there: https://github.com/gleam-lang/cowboy/pull/5

**Comment by michallepicki** [comment]
This can probably be closed now.

**Comment by lpil** [comment]
Fast as always! Thank you
