### ISSUE TITLE
Rendered HTML documentation is now too wide and difficult to read

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#826]
It seems we lost a max-width so any text is rendered extremely wide, making it difficult to read.

![image](https://user-images.githubusercontent.com/6134406/97904516-e6aad580-1d40-11eb-9a28-978628ad28d1.png)

Here is the commit that introduced the problem: 

https://github.com/gleam-lang/gleam/commit/b36aa93b83474d112fda5adcb2c34eeb6bfbc284#diff-fd95152bde957f33fe95e62d56c9bdf1af8c94300949c525bf5d442416cdb666L24

**Comment by michallepicki** [comment]
I'll try to fix this
