### ISSUE TITLE
Improve table styling in rendered HTML

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#827]
![image](https://user-images.githubusercontent.com/6134406/97906629-4a82cd80-1d44-11eb-9ef1-475c41014a3f.png)

The current isn't very clear. Perhaps some extra spacing or borders to make the columns and rows clearer?

**Comment by michaeljones** [comment]
I'll have a look at this.

**Comment by lpil** [comment]
Thanks @michaeljones !
