### ISSUE TITLE
Formatter: consistent handling of empty lines

### ISSUE THREAD

**Issue by edkelly303** [gleam-lang/gleam#833]
in 0.12.0, if you run `gleam format` on this: 
```gleam
fn something() {
  let x = 1

  let y = 2
  x + y
}
```
The result can differ. 

If there are any spaces in the empty line, the formatter will remove the whole line, like this:
```gleam
fn something() {
  let x = 1
  let y = 2
  x + y
}
```
On the other hand, if the empty line is just a linebreak, the formatter will preserve it. This seems a little unexpected, and it might be better to handle both cases the same way.

(If I get a vote, I would prefer it if the formatter would delete the unnecessary spaces but preserve the linebreak - personally I find it easier to read code if I can space it out using a single linebreak between sections.)

**Comment by lpil** [comment]
Ah yes, I totally agree! The formatter should consider a line of nothing but spaces an empty line.
