### ISSUE TITLE
Type aliases cannot refer to other types or type aliases that are defined later in the file

### ISSUE THREAD

**Issue by edkelly303** [gleam-lang/gleam#834]
In Gleam 0.12.0:
```gleam
type This =
  That

type That {
  That
}
```
gives:
```
error: Unknown type
  ┌─ /home/ed/dev/gleam_bugs/gleam_bugs/src/gleam_bugs.gleam:2:3
  │
2 │   That
  │   ^^^^ did you mean `Int`?

The type `That` is not defined or imported in this module.
```
Problems:
1) The error message is not accurate here
2) Since we can define `functions` and `types` in any order, it feels inconsistent that `type aliases` depend on order of definition within the file

Notes:
1) The problem also occurs with `type aliases` that refer to other `type aliases`. This does not compile:
```gleam
type That = This
type This = Int
```
2) There's no problem with `types` referring to `type aliases` - i.e. this compiles ok:
```gleam
type That {
  That(This)
}

type This =
  Int
```
3) I guess there might be a problem if we allow `type aliases` to mutually alias each other though! At the moment, this doesn't compile:
```gleam
type That = This
type This = That
```
But this does! Should it?
```
type That {
  That(This)
}

type This =
  That
```

**Comment by lpil** [comment]
Oh dear! I'm surprised this doesn't work as I thought we recently implemented that. Can I ask what version of Gleam you are using?

**Comment by edkelly303** [comment]
Yep, it's 0.12.0

**Comment by lpil** [comment]
Alright lets get this fixed :)

**Comment by brightly-salty** [comment]
Hello! I'd like to attempt to implement this and submit a PR when I'm done! Looks like it has to do with the `typ::environment::get_type_constructor` method?

**Comment by lpil** [comment]
Hey @brightly-salty ! A contribution would be very welcome! I'm not sure the right way to implement this. It's a tricky one and I've not yet investigated.

**Comment by lpil** [comment]
Closing this in favour of #1925
