### ISSUE TITLE
Code cannot refer to consts that are defined later in the file

### ISSUE THREAD

**Issue by edkelly303** [gleam-lang/gleam#837]
In Gleam 0.12.0:
```gleam
fn something() -> String {
  hello
}

const hello: String = "Hello"
```
Gives an error:
```
error: Unknown variable
  ┌─ /whatever/src/gleam_bugs.gleam:2:3
  │
2 │   hello
  │   ^^^^^ did you mean `Nil`?

The name `hello` is not in scope here.
```
Honestly, for readability's sake, I think I probably *should* be defining my constants before I use them - but given we can now write functions and types in an arbitrary order, perhaps the same should be true of constants?

One option might be to issue be a compiler warning, rather than an error, if you use a constant before it has been defined?

**Comment by lpil** [comment]
This one will be trickier as we need to know the values of constants before they are used in other constants. We can however ensure they can be used in any functions.
