### ISSUE TITLE
Logo / branding

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#84]
@ktec has suggested the colour pink. Not frequently used for a language, could be good!

A style that suggest friendliness would be good.

Here's a collection of logos I enjoy, for future reference.

The sparkles emoji
# ✨ 

https://github.com/expede/witchcraft

![wc-wordmark-lrg 2x](https://user-images.githubusercontent.com/6134406/53606276-33283000-3bb2-11e9-8608-60f205fb6bc6.png)

https://github.com/elixir-lang/elixir
![flat 550x550 075 f](https://user-images.githubusercontent.com/6134406/53606410-ac278780-3bb2-11e9-85b6-0518aa43adc5.jpg)

https://github.com/pikelet-lang/pikelet
![pikelet](https://user-images.githubusercontent.com/6134406/53680509-ae820280-3cd4-11e9-83cc-aae9110e17bc.png)

**Comment by jwinnie** [comment]
![gleam logo](https://user-images.githubusercontent.com/20506149/53676398-97043480-3c56-11e9-9432-5ed4c2c12a45.png)

**Comment by jwinnie** [comment]
@lpil I thought a lot about the color of the logo. You said you liked purple, so I made it purple, but I also considered making it orange (since Gleam has strong influences from both Rust and OCaml). Also, should it be solid purple or have a linear gradient?

**Comment by lpil** [comment]
Oh! This is very cool! Not something I expected to wake up to this morning.

I was also thinking orange, that or a pink. I think that purple may be too close to Elixir, a language we may often be beside.

Visual design is very much outside my understanding so it's hard for me to say much about colours or gradients. Perhaps solid colour is better?

RE selection of a logo: this feels like a decision that will stick with us for some time so I don't want to rush into picking any specific logo. I'm likely to sit on this decision and mull any options for some time. Thanks

**Comment by jwinnie** [comment]
Orange with a gradient:
![group](https://user-images.githubusercontent.com/20506149/53686528-1e948680-3cdd-11e9-9002-c0ff352d53bf.png)
Pink(ish) with a gradient:
![group 1](https://user-images.githubusercontent.com/20506149/53686537-3e2baf00-3cdd-11e9-8b67-a50b7f82f431.png)

**Comment by jwinnie** [comment]
Also consider making a website (Github pages?)

References:
https://crystal-lang.org/
https://clojure.org/
https://www.ponylang.io/
https://www.ruby-lang.org/en/

**Comment by lpil** [comment]
Yes definitely, though the book with a logo will be a good low cost alternative until then. https://gleam.run

**Comment by lpil** [comment]
A friend and I have been iterating with the ideas above and will have something to show shortly. Thanks all!

**Comment by lpil** [comment]
Reopening as we're thinking about refreshing the logo and mascot
