### ISSUE TITLE
Add a versions dropdown to package documentation

### ISSUE THREAD

**Issue by michallepicki** [gleam-lang/gleam#844]
The way the versions dropdown is implemented on Elixir hexdocs pages, is based around a configurable javascript file. This file currently contains a `versionNodes` global array value that contains a list of version names with links to their documentation. (I tried to push an idea of exposing hex.pm "Links" section there as well but it wasn't heard at the time, maybe it could be proposed once again).

The javascript config file is being generated by default on hexdocs for all packages, not just Elixir ones. Thus, Gleam documentation could use it as well! Example: https://hexdocs.pm/gleam_stdlib/docs_config.js

Right now, I don't know how it could look like. Something simple, similar to the ex_doc dropdown, but placed on the top pink bar right to the package name?

PR that added the versions dropdown to ex_doc (implementation might have changed slightly since then): https://github.com/elixir-lang/ex_doc/pull/970
PR that added the js file generation to hexdocs: https://github.com/hexpm/hexdocs/pull/9

**Comment by lpil** [comment]
Brilliant, that would be a find addition!

I think next to the package name would be best. If you look there's actually already a commented out version number there.

**Comment by michallepicki** [comment]
Awesome! I will work on this, for now hardcoding the javascript config path to get things working and I'll submit a WIP PR so that we can iterate on visuals
