### ISSUE TITLE
Trailing underscores in variable names get compiled away causing crash

### ISSUE THREAD

**Issue by itsgreggreg** [gleam-lang/gleam#848]
Sorry for the bad title, didn't know what to write.

```
$ gleam --version
gleam 0.12.1
```

Variables with trailing underscores (`name_`) are allowed in gleam, but the underscores get compiled away making them indistinguishable from the same variable name without trailing underscores in erlang.

This Gleam:
```rust
import gleam/string

pub fn this_will_crash(name_: String) -> String {
  let name = string.concat(["hi ", name_])
  name
}
```

Gets compiled to:
```erlang
-module(gleam_crash).
-compile(no_auto_import).

-export([this_will_crash/1]).

% Notice that all the variables are named Name (no underscore)
this_will_crash(Name) ->
    Name = gleam@string:concat([<<"hi "/utf8>>, Name]),
    Name.
```

Which will crash when run, as erlang doesn't allow variable re-binding
and it thinks this is a pattern match against an existing value:
```
Failures:

  1) gleam_crash_test:crash_test/0: module 'gleam_crash_test'
     Failure/Error: {error,
                        {badmatch,<<"hi greg">>},
                        [{gleam_crash,this_will_crash,1,
                             [{file,
                                  "/Users/a/Trash/gleam_crash/gen/src/gleam_crash.erl"},
                              {line,7}]},
                         {gleam_crash_test,crash_test,0,
                             [{file,
                                  "/Users/a/Trash/gleam_crash/gen/test/gleam_crash_test.erl"},
                              {line,8}]},
                         ...
```

**Comment by greg-enbala** [comment]
i'm guessing it's this line:
https://github.com/gleam-lang/gleam/blob/1053873aa9c4419b0bdf5d60890616c717e18c49/src/erl.rs#L77

which results in this:
https://github.com/withoutboats/heck/blob/937459a039e8cbe151ee6bf16bcd35f7f63829ed/src/lib.rs#L87

**Comment by itsgreggreg** [comment]
i'm guessing it's this line:
https://github.com/gleam-lang/gleam/blob/1053873aa9c4419b0bdf5d60890616c717e18c49/src/erl.rs#L77

which results in this:
https://github.com/withoutboats/heck/blob/937459a039e8cbe151ee6bf16bcd35f7f63829ed/src/lib.rs#L87


Reading that library I'm realizing other things are going to be ambiguous as well

```rust
pub fn this_will_crash() -> String {
  let one1 = "one1"
  let one_1 = "one_1"
  one1
}
```

compiles to

```erlang
hello_world() ->
    One1 = <<"one1"/utf8>>,
    One1 = <<"one_1"/utf8>>,
    One1.
```

**Comment by lpil** [comment]
Yup, you've found the problem. We're going to need different logic for how we change the case of variables.
