### ISSUE TITLE
gleam new generating invalid code

### ISSUE THREAD

**Issue by sporto** [gleam-lang/gleam#867]
After I do `gleam new --template app ...` I get a module `application.gleam` with:

```
import gleam/otp/supervisor.{{ApplicationStartMode, ErlangStartResult}}
import gleam/dynamic.{{Dynamic}}
```

Generated from https://github.com/gleam-lang/gleam/blob/b0065b656ccc7732478afc1d320680a906cb0401/src/new.rs#L217

Which fails to compile with 
```
 import gleam/otp/supervisor.{{ApplicationStartMode, ErlangStartResult}}
                              ^ Unexpected token
```

Changing to this fixes the issue

```
import gleam/otp/supervisor.{ApplicationStartMode, ErlangStartResult}
import gleam/dynamic.{Dynamic}
```

**Comment by lpil** [comment]
Oh dear, that is embarrassing. Sorry about that. Let's get this fixed right away. ￼Which version are you using?￼
