### ISSUE TITLE
Formatter changes sematics of boolean expression

### ISSUE THREAD

**Issue by jakobht** [gleam-lang/gleam#868]
The code:
```gleam
fn test() {
  True != {2 == 2}
}
```
Is changed by the formatter to:
```gleam
fn test() {
  True != 2 == 2
}
```
The first version compiles, the second does not compile as it is not possible to compare a `Bool` to an `Int`.

I use the version from AUR (https://aur.archlinux.org/packages/gleam/) my version is:
```sh
$ gleam --version
gleam 0.12.0
```

**Comment by lpil** [comment]
Oh dear! That's not good. Let's get this fixed

**Comment by lpil** [comment]
Ah, pesky off by one error!
