### ISSUE TITLE
More helpful error message on syntax error with anonymous function

### ISSUE THREAD

**Issue by edman** [gleam-lang/gleam#871]
If you write `fn(...)` it works fine, if you write `fn (...)` it breaks with

```
27 │   let consume = fn (letter, range) {
   │                 ^^ Unexpected token
```

Can we improve this error message?

**Comment by lpil** [comment]
Good suggest. Let's see if we can make the compiler accept this syntax.

**Comment by lpil** [comment]
It should compile now. I'll release a new version after a few more bugs are fixed
