### ISSUE TITLE
"Unused type" warning not triggered consistently

### ISSUE THREAD

**Issue by edman** [gleam-lang/gleam#875]
In a module with the following content

```
import gleam/bool.{negate}
import gleam/option.{Some}
import gleam/set.{Set}
```

(this is all, no functions or type definitions are needed)

The compiler warns

```
warning: Unused type
  ┌─
  │
3 │ import gleam/set.{Set}
  │                   ^^^

The type Set is never used, it can be safely removed.
```

Delete line 3, the warning goes away.

In this case all imports are unused, including modules, functions, and types. Should the compiler warn on all of them? It's unclear why `Set` is singled out.

**Comment by lpil** [comment]
The unused type warning is emitted but the unused value warning is not. It is a bit more complicated to implement that one in order to handle reference cycles, so it has not yet been done. There is a related issue here #532
