### ISSUE TITLE
Warning about unused literals

### ISSUE THREAD

**Issue by jakobht** [gleam-lang/gleam#876]
The parser will parse `2-1` as `2; -1`.
I understand that it might be hard to change the formatter to parse it as `2 - 1` so I suggest to add a warning about `2` being unused.

**Comment by lpil** [comment]
Good idea! Let's emit this warning

**Comment by brightly-salty** [comment]
Maybe this should be closed? Seems like both PR#891 and PR#893 have been merged

**Comment by lpil** [comment]
The 1-1 issue has been solved but unused literals need to emit a warning still.

To implement this we would need code similar to this code for discarded results: 

https://github.com/gleam-lang/gleam/blob/9b895b80f2c0dcf3544cd6f17c237895c32a9a72/src/typ/expr.rs#L341-L355

The main difference would be that we would be that we would have a check along the lines of `if first.is_literal() { return Err(Error::UnusedLiteral { .. }) }`

**Comment by brightly-salty** [comment]
Would that be in the same infer_seq method? If so, I think I would be willing to attempt this.

**Comment by lpil** [comment]
Yes, that would be the right place to do it. A contribution would be wonderful, thank you
