### ISSUE TITLE
Should `opaque` and `const` be in the list of reserved words?

### ISSUE THREAD

**Issue by itsgreggreg** [gleam-lang/gleam#879]
https://github.com/gleam-lang/gleam/blob/main/src/parser.rs#L522

Should this list include the words `opaque`, `const`, and `tuple`? as in:

`pub opaque type X { ... }`
`const x = 1`
`tuple(1,2)`

**Comment by lpil** [comment]
They should! Looks like we're not doing a great job of keeping this list up to date
