### ISSUE TITLE
Compilation to JavaScript

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#888]
Compilation of Gleam to JavaScript in order to run in the browser, as CLI scripts, on serverless functions, etc.

This post will be continuously updated to reflect the status of the ticket and design.

# Codegen

## Literals

| Gleam | JavaScript |
| --- | --- |
| `1` | `1` |
| `1.0` | `1.0` |
| `Nil` | `null` |
| `True` | `true` |
| `False` | `false` |
| `"Hello"` | `"Hello"` |
| `<<1, 2, 3>>` | ??? |
| `tuple(1, 2, 3)` | `[1, 2, 3]` |
| `[]` | `[]` |
| `[1, 2, 3]` | `[1, [2, [3, []]]]` |
| `Ok(1)` | `{ type: "ok", 0: 1 }` |
| `Error(1)` | `{ type: "error", 0: 1 }` |
| `Some(1)` | `{ type: "some", 0: 1 }` |
| `None` | ??? |
| `MyType(name: "Dave", age: 39)` | `{ type: "my_type", name: "Dave", age: 39 }` |

## Let

| Gleam | JavaScript |
| --- | --- |
| `let x = 1` | `let x = 1;` |

TODO: How does destructuring work? We need to raise an exception if it does not match.

todo

## Functions

todo

## Exports

todo

## Imports

todo

## Case

todo

## Try

todo

## External functions

todo

## Const

# Questions

## Equality

How do we implement structural equality?

## Numbers

JS doesn't have an integer type. Shall we use bitwise trickier to hint to the runtime that we are using ints?

https://en.wikipedia.org/wiki/Asm.js#Code_generation

## Bit strings

What do we use for bit strings? Perhaps we could just compile a subset to start.

## Tail call optimisation

We will need to generate trampolines in order to not blow the stack when recursing. We will need to do some research on how to do this and also how to detect + support mutual recursion.

## Conditional compilation

We will need to be able to compile code differently on different platforms based on their capabilities. An example here is that the stdlib will need a different implementation for `gleam/map.Map` and `gleam/io.println` on JS compared to Erlang.

What should the design be for conditional compilation?

## External functions

The current design for external functions is based around the Erlang module system. Does it need to be altered for other targets?

# References

Prior work: https://github.com/gleam-lang/gleam/pull/840

**Comment by lpil** [comment]
@CrowdHailer ping

**Comment by lpil** [comment]
Splitting sub-tickets out of this and tracking with this milestone
https://github.com/gleam-lang/gleam/milestone/17

**Comment by CrowdHailer** [comment]
@lpil are you encouraging PR's that tackle with one issue at a time the way you've broken them up. It would be nice to not have a long lived JS PR and will probably allow better reviewing if we can merge it piece by piece.

**Comment by lpil** [comment]
I think that sounds like a really good strategy! We could also do multiple bits concurrently too

**Comment by CrowdHailer** [comment]
I think I have some that are already to go. A really nice first issue might be to add the JS compilation flag as a PR but which fails with a nice new this features is not implemented error for every feature.
