### ISSUE TITLE
Misleading documentation for escripts

### ISSUE THREAD

**Issue by bobbui** [gleam-lang/gleam#894]
Hi,
I try template project following the doc from here https://gleam.run/documentation/ but when I tried to execute the binary got this error
```bash
escript: exception error: undefined function test:main/1
  in function  escript:run/2 (escript.erl, line 758)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3
```

 These are the commands I tried to run
```bash 
gleam new test
cd test
rebar3 compile
rebar3 escriptize
_build/default/bin/my_project_name
```
my environment:
- docker container with debian buster
- gleam 0.12.1
- rebar 3.14.3 on Erlang/OTP 21 Erts 10.2.4

Thanks in advance for any help

**Comment by lpil** [comment]
Thanks for the report! This has been fixed on the main branch and will be released soon.

**Comment by lpil** [comment]
Oh sorry, this is not the issue I thought it was.

The new project template does not implement an escript. If you wish to create an escript you will need to add a “main” function that will be called by the Erlang escript code. It takes a list of character lists as an argument.

For more information see the Rebar3 and Erlang documentation.

**Comment by bobbui** [comment]
I'm not familiar with Rebar3 and Erlang, but if that the case so following the documentation exactly step by step won't work, specifically **Using Escripts** section on this page: https://gleam.run/writing-gleam/running-the-project/

**Comment by lpil** [comment]
Ah yes, the current docs are not very clear. It say this:

> _build/default/bin/my_project_name which requires a fn main as the entrypoint

But that is pretty vague! We should make it more clear how to define the main function as required.

In your `test.gleam` file add this code, recompile the escript and I think it should work.

```rust
import gleam/io

pub fn main(_args: List(List(Int))) {
  io.println("Hello from the program!")
}
```

**Comment by bobbui** [comment]
> Ah yes, the current docs are not very clear. It say this:
> 
> > _build/default/bin/my_project_name which requires a fn main as the entrypoint
> 
> But that is pretty vague! We should make it more clear how to define the main function as required.
> 
> In your `test.gleam` file add this code, recompile the escript and I think it should work.
> 
> ```rust
> import gleam/io
> 
> pub fn main(_args: List(List(Int))) {
>   io.println("Hello from the program!")
> }
> ```

yeah it's working now. you want to leave this open or u want me to close it?

**Comment by lpil** [comment]
Let's leave it open in order to have the documentation approved. Thank you￼

**Comment by lpil** [comment]
Fixed in this PR https://github.com/gleam-lang/website/pull/74, thank you
