### ISSUE TITLE
Divide by zero without crashing

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#895]
Currently dividing by zero causes a crash, something that should not occur in Gleam other than when using the `assert` keyword.

We cannot follow IEEE 754 because Erlang doesn't support `Infinity` or `Nan`, so using them would break interop.

Take a leaf out of Pony, Isabelle, Lean and Coq's book and have `1 / 0 == 0`.

Also add alternative functions to the `int` and `float` modules that return Results.

## Notes

https://www.hillelwayne.com/post/divide-by-zero/

**Comment by itsgreggreg** [comment]
don't forget mod and related: `x % 0` will also crash with a `badarith` error.

**Comment by lpil** [comment]
Yes certainly. If you use a division function that returns a result you
will be able to handle the error rather than returning the default value.

**Comment by kevlarr** [comment]
I definitely understand the logic of wanting exception-free and working within the constraint of not having Infinity. I think the biggest problem is that so few languages do this, including Erlang and Elixir, and it's not really called out except for the release note. We tend to just assume that division by 0 is an exception. Even Rust (despite having a similar "prefer results over panics" philosophy) chooses to panic rather than returning `0` or a `Result` for `1 / 0`.

I was just thinking it could be nice when compiling a project to say "be like Erlang and panic on 0". Especially because we can't tell third-party code whether to use `/` or the division function. If they use `/` then did I get a `0` because it's the actual mathematical result or because division by zero has been defined like this?

**Comment by lpil** [comment]
The reasoning for the behaviour is given in the post for that release https://gleam.run/news/gleam-v0.13-released/

> We tend to just assume that division by 0 is an exception.

The issue here is that you're speaking of your own expectations as if they are universal, while in my surveying and research prior to designing this functionality I found that this is both not a majority behaviour, and not a majority expectation. Returning an inert value such as `Infinity` was the most common.

I don't believe it's possible to design a system that is not surprising to any future user as there's no wider consensus. Given this it is better to design a behaviour that is consistent with the wider language and works towards the language's goals.


> I can't tell third-party code to use a division function instead of /

In what situation have you needed to know this?

**Comment by kevlarr** [comment]
I wasn't pushing against you or criticizing. I read the post, and I said I understood the logic. My tone was neither negative nor condescending at all, and I did not imply you didn't think this through or have valid reasons.

You chose a very non-standard approach, one that deviates from the underlying platform. Of course you'll have people ask about it.

**Comment by lpil** [comment]
Not at all, I didn't think you were being hostile! It's good to talk about
design to ensure we get things right.

That's right, we are deviating from what Erlang does here. Gleam takes a
very different approach to error handling than Erlang and it can be
expected that Gleam will opt not to crash in situations that Erlang would.
To crash would not be in keeping with the wider language and would be
undermining the safety properties of the type system, so we take
inspiration from type safe languages here.

**Comment by lpil** [comment]
Good feedback! In future I do hope to have a good amount of information on error handling, documentation and onboarding are very important, and there's lots of different mindsets and experience to consider.

Thank you for your support! It means a lot

**Comment by kevlarr** [comment]
Honestly, it's impressive how much progress you've made on all fronts. Website and documentation are way farther ahead than they should be.

**Comment by ergre314** [comment]
> Currently dividing by zero causes a crash, something that should not occur in Gleam other than when using the `assert` keyword.
> 
> We cannot follow IEEE 754 because Erlang doesn't support `Infinity` or `Nan`, so using them would break interop.
> 
> Take a leaf out of Pony, Isabelle, Lean and Coq's book and have `1 / 0 == 0`.
> 
> Also add alternative functions to the `int` and `float` modules that return Results.
> 
> ## Notes
> https://www.hillelwayne.com/post/divide-by-zero/

I am just trying to learn gleam when I googled this issue and found this thread. 
To me that post from www.hillelwayne.com does not seem very helpful. It is throwing around big math concepts like algebraic fields or Martin-Löf’s constructive type theory. The person seems more about winning arguments than about understanding math.  I got the feeling or I hoped that that is not really what gleam is about.  In the end in one of his updates he is even arguing against what wikipedia has to say about the subject. 
I hope you can react in a way that is more empathetic to people who are surprised by this dision.

**Comment by lpil** [comment]
I'm sorry, I don't know what you mean about winning arguments. Gleam's behaviour here is the result of the set of constraints we have in the language- infinity and crashing are not possible, so division by zero was selected instead.

**Comment by ergre314** [comment]
Did you read the link you added?
