### ISSUE TITLE
"\^" at end of string causes erlang to see the string as unclosed

### ISSUE THREAD

**Issue by itsgreggreg** [gleam-lang/gleam#902]
Erlang interprets escaped caret (`\^`) in a string as the start of a control code escape. According to erlang's docs, `\^a..\^z` and `\^A..\^Z` are valid control code escapes and get replaced with their ascii control code equivalent. 

Erlang docs: http://erlang.org/doc/reference_manual/data_types.html#escape-sequences
Escape sequences (column starting with `^@`): https://en.wikipedia.org/wiki/ASCII#Control_code_chart

So in erlang terms this means:
```
<<"\^@"/utf8>> == <<0>>
<<"\^a"/utf8>> == <<1>>
-- and so forth

-- and very unfortunately
<<"\^""/utf8>> == <<2>>
```

In Gleam terms this means:
```
"\^I" == "\t"
"\^J" == "\n"

// and very unfortunately
"\^"" is a syntax error in gleam

// and also very unfortunately 
"\^" causes the string to be un-closed in erlang
```

There are a few interesting things here.
1) Erlang's docs specify that a-z and A-Z are valid, they don't say anything about other characters. `\^"` being interpreted as <<2>> is redundant with `\^b`. Perhaps this is a bug in erlang. probably not :(

2) this passes:
```rust
  <<0:8>>
  |> bit_string.to_string()
  |> result.unwrap("")
  |> should.equal("\^@")
```

3) If you for some reason end a string with `\^`, so "any text \\^", Gleam will compile it to Erlang that won't compile. This is because of the previously mentioned `\^"` gets interpreted as `<<2>>` and erlang sees the string as still open.

Considering this is probably not something erlang will "fix" what should be done here?

**Comment by lpil** [comment]
Yikes. That is not fun. How did you find that one?

Seems like we could replace `\^` with `\\^` when rendering Erlang unless I'm missing something. This is the first time I'm learning about these escape codes.

**Comment by itsgreggreg** [comment]
I was escaping strings destined for a regex and didn't properly escape a caret. I wrote `string.replace("^", "\^")` and it generated the offending Erlang.

Unfortunately it's not a simple as replace `\^` with `\\^` as you have to backwards count slashes. Doing that on `\\^`, which is properly escaped, would produce `\\\^` which is not properly escaped. 

This is also complicated by gleams desire to have multiple targets.

Javascript has these escapes:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Escape_notation

Erlang also supports these escapes:
|sequence|result|
|-|-|
| \XYZ, \YZ, \Z | Character with octal      |   representation XYZ, YZ or Z |
|\xXY | Character with hexadecimal     |    representation XY |
|\x{X...} | Character with hexadecimal    |     representation; X... is one or more hexadecimal characters |

So in order to properly support different targets with the same functionality gleam is probably going to have to figure out what escapes it wants to support and then parse and render strings itself, in either a platform dependent or agnostic way.

**Comment by itsgreggreg** [comment]
I'm thinking on lexing we could check if a string contains a `\` and mark it as dirty or something. Then during code generation if the string is dirty pass it through an escape parser.

Perhaps the first pass of this is to only support common whitespace escapes. \n, \r, \t,  and quote \"

**Comment by lpil** [comment]
That sounds like a good plan to me. Those would cover 99% of uses and we can introduce more later.

**Comment by lpil** [comment]
@CrowdHailer I've noticed you've used `\c` in Gleam HTTP. I'm not familiar with that one, what is it?

**Comment by CrowdHailer** [comment]
I'm sorry to say I can't remember, I feel like I've copied that case statement from some Plug code without leaving a link

**Comment by lpil** [comment]
No worries, thank you
