### ISSUE TITLE
Marking functions as deprecated

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#904]
When a deprecated function is used we want to detect this and emit a warning at compile time.

```rust
@deprecated(since: "1.1.0", note: "Will set fire to your laundry")
pub fn two() { ... }
```

**Comment by tclain** [comment]
is the decorator syntax already standardized  or would it be a first ?

**Comment by lpil** [comment]
No syntax has been finalised and there is no decorators or similar yet. Bikeshedding and such is very welcome
