### ISSUE TITLE
Error highlight end off by one

### ISSUE THREAD

**Issue by itsgreggreg** [gleam-lang/gleam#918]
I'm seeing a lot of this now:
```

error: Syntax error
  ┌─ /Users/a/parser_test/src/one.gleam:1:1
  │
1 │ pub cons a = 5
  │ ^^ I was not expecting this.

error: Unknown type
  ┌─ /Users/a/parser_test/src/one.gleam:1:14
  │
1 │ pub const a: Resul = 5
  │              ^^^^ did you mean `Result`?
```

Notice the end of the underline is one character short.

I see it was recently changed: https://github.com/gleam-lang/gleam/commit/a60f6434e6faf9acfbd4912950e458e2a9f24b83#diff-8d107ec1ada422c8fb3a9e974a308d42076e8c4ffdee0d882687aa6f39dddb03R49

What was off by one before?

**Comment by lpil** [comment]
Oh that is interesting. It was seeing off-by-one errors before in the other direction, though I'm forgetting where they were exactly. I'll revert that commit and then make a new issue if I find the problem I originally had. Thanks Greg
