### ISSUE TITLE
Outdated Cargo.lock file?

### ISSUE THREAD

**Issue by carlocab** [gleam-lang/gleam#920]
gleam is currently failing to build for Homebrew with Rust 1.49 on Apple Silicon: https://github.com/Homebrew/homebrew-core/pull/68957, https://github.com/Homebrew/homebrew-core/pull/68089

It appears this is due to a stale lock file, causing `cargo install --locked` to pull in dependencies that do not work for gleam on Apple Silicon. Is it possible for the `Cargo.lock` file to be updated? If this could be done with a new release, that would be especially helpful.

Related: https://github.com/Homebrew/homebrew-core/issues/68301

**Comment by shritesh** [comment]
This is because of `ring`, depended on by `hexpm-rust`. Executing `cargo update -p ring` solves this for me. It upgrades from `v0.16.15` to `v0.16.19`.

**Comment by carlocab** [comment]
ARM build logs: [logs.tar.gz](https://github.com/gleam-lang/gleam/files/5811714/logs.tar.gz)

The reason I suspect the issue is with the `Cargo.lock` file is that doing `cargo install` without passing the `--locked` flag succeeds. Omitting the `--locked` flag causes `cargo` to pull in the latest versions available of each dependency.

On the other hand, when the `--locked` flag is included, the build fails.

**Comment by carlocab** [comment]
Yes, but we don't run `cargo update`, because that leads to non-reproducible builds...

**Comment by shritesh** [comment]
`hexpm-rust` has specified `^0.16` for `ring`'s requirement and it itself doesn't have a Cargo.lock file. I have submitted a PR that fixes this.

**Comment by carlocab** [comment]
Thanks very much! Really appreciate it.

**Comment by carlocab** [comment]
Thanks for the lightning-quick turnaround, @lpil!

**Comment by lpil** [comment]
No problem! Thank you for finding the problem and kicking off the debugging
