### ISSUE TITLE
[import module aliasing?] Compile error: "Failed to find previously located module import"

### ISSUE THREAD

**Issue by subsetpark** [gleam-lang/gleam#922]
Was writing some unit tests when suddenly started getting compiler crashes. Here's the full output: 

```
code/lang/gleam/brzo [] ⊕ ./rebar3 compile
===> Verifying dependencies...
Compiling gleam/pair
Compiling gleam/io
Compiling gleam/atom
Compiling gleam/option
Compiling gleam/order
Compiling gleam/bit_string
Compiling gleam/bool
Compiling gleam/regex
Compiling gleam/string_builder
Compiling gleam/bit_builder
Compiling gleam/float
Compiling gleam/should
Compiling gleam/int
Compiling gleam/list
Compiling gleam/queue
Compiling gleam/result
Compiling gleam/map
Compiling gleam/dynamic
Compiling gleam/function
Compiling gleam/set
Compiling gleam/iterator
Compiling gleam/string
Compiling brzo
Compiling brzo_test
error: Fatal compiler bug!

This is a bug in the Gleam compiler, sorry!

Please report this crash to https://github.com/gleam-lang/gleam/issues/new
with this information and the code that produces the crash:

Failed to find previously located module import

===> Unable to compile Gleam project
code/lang/gleam/brzo [] ⊕ 
```

I presume it is some kind of bad state in the build directory, because even if I comment out all the tests, the compile still fails (when it was succeeding with an empty test file and the source file in the current state a minute ago).

I'll refrain from clearing the build directory for now, in case anything there would be useful in debugging.

The gleam format command works fine, so it parses ok.

**Comment by subsetpark** [comment]
Full project available here: https://github.com/subsetpark/gleam_brzo

**Comment by lpil** [comment]
Yikes! That is an ugly one! Thanks for the report and the repo.

Here's the code in question:

https://github.com/gleam-lang/gleam/blob/a60f6434e6faf9acfbd4912950e458e2a9f24b83/src/typ/expr.rs#L1566-L1586

I'm not sure what the issue right now but that doesn't look like my finest code. I'll dig into this when I have time.

**Comment by subsetpark** [comment]
Thanks @lpil . If it makes any difference, blowing away my `_build` and then commenting out the unit test module does resolve the issue. However, if I uncomment it, the failure returns. So it's reproduceable (on my machine), anyway.

**Comment by lpil** [comment]
That's very useful, thank you

**Comment by subsetpark** [comment]
Further, it seems like it's related to the module aliasing. Replacing `import brzo as b` with `import brzo` (and changing `b.` to `brzo.`) allows me to run `eunit` normally.

**Comment by lpil** [comment]
Wonderful, thank you for the debug information. ￼Very useful￼

**Comment by benmyles** [comment]
Just hit this issue myself under similar circumstances. It seems to be having trouble using _qualified_ imports in `const`.

This code produces the `Failed to find previously located module import` error:

```
import money/currency

const currency_db_data: List(tuple(String, currency.Currency)) = [
  tuple(
    "USD",
    currency.Currency(
      code: "USD",
      symbol: "$",
      numeric_code: 840,
      minor_units: 2,
      name: "United States dollar",
    ),
  ),
  tuple(
    "GBP",
    currency.Currency(
      code: "GBP",
      symbol: "£",
      numeric_code: 826,
      minor_units: 2,
      name: "Pound sterling",
    ),
  ),
]
```

However, if I tweak the code to import the `Currency` type directly it works fine:

```
import money/currency.{Currency}

const currency_db_data: List(tuple(String, Currency)) = [
  tuple(
    "USD",
    Currency(
      code: "USD",
      symbol: "$",
      numeric_code: 840,
      minor_units: 2,
      name: "United States dollar",
    ),
  ),
  tuple(
    "GBP",
    Currency(
      code: "GBP",
      symbol: "£",
      numeric_code: 826,
      minor_units: 2,
      name: "Pound sterling",
    ),
  ),
]
```

**Comment by lpil** [comment]
Wonderful, thank you for the extra data. This is very helpful.

**Comment by lpil** [comment]
OK, fixed that one. Thank you @benmyles .

Unsure if the original issue is still there so I'm keeping this open until I've tested.
