### ISSUE TITLE
A project template that sets up a gleam project to make a single binary/executable/escript

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#925]
The proposal here is to have `gleam new --escript` or similar as an answer to how to make an executable Gleam program.

For version one I think there is no reason to be careful about performance. In a future where compiling Gleam to native is a reality you can deprecate the old version and use the new one without any breaking changes because projects are only generated once.

**Comment by ryanzidago** [comment]
This PR has already been implemented on the main branch or?
Right now, when I compile gleam from the main branch I can run
```bash
gleam new project --template=escript
rebar3 escriptize
_build/default/bin/project
```
And it will output:
```
Hello, from project!
```

**Comment by lpil** [comment]
Well spotted, thanks!
