### ISSUE TITLE
Improved pipe type error messaging

### ISSUE THREAD

**Issue by sporto** [gleam-lang/gleam#936]
I find this error message confusing.

Consider:

```gleam
type Fruit{ Orange }
type Veg{ Lettuce }

fn eat_veggie(v: Veg) {
  "Ok"
}

  Orange
  |> eat_veggie
```

```gleam
error: Type mismatch
   ââ /Users/Sebastian/Source/sporto/stdlib/src/gleam/map.gleam:13:3
   â
13 â   |> eat_veggie
   â   ^^^^^^^^^^^^^

Expected type:

    fn(Veg) -> String

Found type:

    fn(Fruit) -> a
```

By looking at this information is hard to understand what the problem is.

The error points to `|> eat_veggie`. Saying that it expected `fn(Veg) -> String`

Indeed `|> eat_veggie` is a function that take a `Veg` and returns a `String`. It says it found `fn(Fruit)`, but `eat_veggie` doesn't take a fruit.

I know that my interpretation of the error is the other way around, but this is what I understand at first glance.

I think Elm could be a good inspiration to make this clearer:

```elm
This function cannot handle the argument sent through the (|>) pipe:

17|   Orange
18|   |> eatVeggie
         ^^^^^^^^^
The argument is:

    Fruit

But (|>) is piping it to a function that expects:

    Veggie
```

**Comment by lpil** [comment]
Very nice suggestion, thank you.

**Comment by lpil** [comment]
Reopening this as it has been partially reverted.

**Comment by lpil** [comment]
Yes I think so, I must have broken the snapshot by mistake.
