### ISSUE TITLE
Unknow field error reports misleading type information

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#937]
```
error: Unknown field
   ┌─ /opt/app/src/plum_mail/web/router.gleam:72:33
   │
72 │   let identifier_id = identifier.id(identifier)
   │                                 ^^^ This field does not exist

The value has this type:

    Identifier

It does not have any fields.
```

In this call `.id` is on the module called identifier. therefore it doesn't have the type Identifier

**Comment by michallepicki** [comment]
You have a variable in scope bound to name `identifier`. I think that's expected that it's shadowing the module name?

**Comment by lpil** [comment]
Yup that's right @michallepicki. If you have shadowed a module with a variable we print an error for the variable. We could possible add to the error message saying neither the variable or the module have that field.
