### ISSUE TITLE
Cheatsheet: Gleam for Elm users

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#944]
In the style of https://gleam.run/cheatsheets/gleam-for-elixir-users/

**Comment by michaeljones** [comment]
Has there been any movement on this? I could potentially take a swing at the first draft?

**Comment by lpil** [comment]
I don't think anyone has done anything. Go for it! Don't feel you have to do it all either.

**Comment by michaeljones** [comment]
Cool, I'll try to find time over the next week. Do you feel each language should have a fresh take or is it a case of copying & pasting one of the other ones and reshaping it to suit Elm?

**Comment by lpil** [comment]
I think Elixir may be relatively close to Elm so that could be a starting point? There will be lots to add around types for sure
