### ISSUE TITLE
Cheatsheet: Gleam for Python users

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#946]
In the style of https://gleam.run/cheatsheets/gleam-for-elixir-users/

**Comment by tclain** [comment]
@lpil I'm interested

**Comment by lpil** [comment]
That's great! Thank you @tclain . Feel free to have a go and don't worry about having to finish it all. A partial cheatsheet is better than none at all

**Comment by tclain** [comment]
I think we can close this @lpil

**Comment by lpil** [comment]
Wonderful, thank you
