### ISSUE TITLE
Some ways bitstrings can crash or not compile correctly

### ISSUE THREAD

**Issue by itsgreggreg** [gleam-lang/gleam#949]
These are all in declaration not patterns. I haven't investigated what will cause invalid patterns.

# Fixed
these are notes while i work on this

## Compiles but not what intended

An Expression in unit
```gleam
  <<3:size(1 + 1)-unit(1 + 1)>>
// Renders as
    <<3:(1 + 1)>>.
```

## Runtime Crash

Function that evaluates to a negative number
```
  let a = fn(b) { b - 4 }
  <<3:size(a(3))>>

// ** exception error: bad argument
```

## Compiles in Gleam, not in Erlang

A variable in unit 
```
let a = 4
<<3:size(2)-unit(a)>>
// Warning: variable 'A' is unused
// renders as 
//    A = 4,
//    <<3:2>>. 
```

A negative size
```gleam
<<3:size(-1)>>
<<3:-1>>
// syntax error before: '-'
```

A negative number in variable
```gleam
let a = -1
<<3:size(a)>>
// Warning: binary construction will fail because of a type mismatch
```

Any use of `unit` without an explicit size:
```gleam
<<10:unit(4)>>
// a bit unit size must not be specified unless a size is specified too
```

Size or unit given with utfx option
```
  <<"3":8-utf32>>
// neither size nor unit must be given for segments of type utf8/utf16/utf32
```

Size or unit given with utfx_codepoint
```
  assert Ok(c) = string.utf_codepoint(97)
  <<c:10-utf8_codepoint>>
// neither size nor unit must be given for segments of type utf8/utf16/utf32
```

### Erlang warning will crash

Bad size for a `float` type
```
  <<3.0:8-float>>
// Warning: bad float bit size
```

Using `binary` option on a non 8 bit divisible segment
```
  <<<<1:1>>:binary>>
// Warning: binary construction will fail with a 'badarg' exception (size 1 cannot be evenly divided by unit 8)
```

## Compiler panics
```
pub fn bts() {
  let <<<<1>>:bit_string>> = <<<<1>>:bit_string>>
  1
}

**Comment by lpil** [comment]
Good finds, thank you Greg. As much as possible let's make it so the compiler only accepts bit strings that will be valid at runtime.

**Comment by itsgreggreg** [comment]
I've started working on this, feel free to assign me to it. gonna take me a couple days.

**Comment by lpil** [comment]
Thanks Greg!
