### ISSUE TITLE
Source links are altered when published to hexdocs

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/gleam#950]
Everything between the github repository root and the hash gets removed, though it is correct on the local copy. This doesn't seem to be the case with `gleam_stdlib`, so I'm not sure about steps to reproduce, other than to link the example for now.

https://hexdocs.pm/shellout/shellout/

Local copy generated with `gleam docs publish --version 0.1.0`
https://gist.github.com/tynanbe/7f5fa408bc33f562361f3ab30665d276

**Comment by itsgreggreg** [comment]
I'm not sure why but I'm guessing `path_in_repo` is coming up blank https://github.com/gleam-lang/gleam/blob/main/src/docs/source_links.rs#L19

**Comment by lpil** [comment]
@tynanbe would you be able to build the compiler from the main branch and see if building the docs work with that?

**Comment by tynanbe** [comment]
@lpil: Just built Gleam from latest main branch and can confirm that this issue is indeed resolved.
