### ISSUE TITLE
Scroll bars are inside padding of code snippets in rendered docs

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#955]
![image](https://user-images.githubusercontent.com/6134406/106290769-bd67eb80-6242-11eb-9205-dfe15d7e60b5.png)

The scroll bar should be outside of the padding, at the bottom edge of the box

**Comment by syukronrm** [comment]
I think this bug has been resolved. I generated this docs from stdlib.

![image](https://user-images.githubusercontent.com/6128604/107849822-4c265c00-6e30-11eb-9305-9cbe5ecd6e54.png)

**Comment by lpil** [comment]
Well spotted! Thank you
