### ISSUE TITLE
Include Gleam file information when a program crashes on assert.

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#958]
Suggested solution from discord is to compile the following
```rust
assert Ok(x) = y
```
as
```erlang
X1 = case Y of 
  {ok, X} -> X;
  _ -> error({gleam_error, #{error => assert, line => LineNumber, file => File}})
end.
```

Should also include gleam filename

**Comment by CrowdHailer** [comment]
Would it make sense to also put line information for case errors. Something that is perfectly possible before exhaustiveness.
i.e.
```rust
case result {
  Ok(5) -> // do it
}

as 
```erl
X1 = case Y of 
  {ok, 5} -> X;
  _ -> error({gleam_error, {case_failure, LineNumber, OtherInfoGoesHere}})
end.
```

**Comment by lpil** [comment]
Makes sense yup!

**Comment by lpil** [comment]
Here's my proposed error format

```erlang
    erlang:error(#{gleam_error => assert,
                   pattern => <<"Ok(x)">>,
                   value => {error, "Hello"},
                   module => <<"the_app">>,
                   function => <<"main">>,
                   line => 3}).
```

We would also need to give `todo` the same treatment.
```erlang
    erlang:error(#{gleam_error => todo, 
                   message => <<"This has not yet been implemented">>,
                   module => <<"the_app">>,
                   function => <<"main">>,
                   line => 3}).
```

Do implement this we will need to extract the line number handling from SourceLinks and make a generically useful version of it that we can use in documentation and Erlang generation without traversing the source multiple times.

**Comment by CrowdHailer** [comment]
Looks good. `module` and `function` might become the first item in a stacktrace in the future? or is that thinking too many steps ahead.

**Comment by lpil** [comment]
I'm not sure, I've not thought about stack traces yet

**Comment by CrowdHailer** [comment]
I like this feature, it looks like it was tackled for todo/assert but incomplete case statements still throw the beam error.

Should this issue remain open until it handles a fallback case for case

**Comment by lpil** [comment]
I'll make a new one for case
