### ISSUE TITLE
Repository sidebar link is wrong

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/gleam#962]
Source code links in the page content are correct in the following example, but the sidebar repository link is not.
Generated just now with the latest Gleam main.
https://hexdocs.pm/shellout/shellout/

**Comment by lpil** [comment]
Well spotted, thank you.

Possibly a similar problem to https://github.com/gleam-lang/gleam/issues/950

**Comment by ShubhamPalriwala** [comment]
Should this be fixed with the href bringing the user to this repo?

**Comment by lpil** [comment]
Sorry, what do you mean @ShubhamPalriwala ?

**Comment by ShubhamPalriwala** [comment]
I am looking to resolve the issue, so was asking if the correct link is the url to this GitHub repo.

**Comment by lpil** [comment]
Yes that's right. It should use the repository information taken from the config file. For some reason it is not working at the moment, possibly for similar reasons to the other linked issue
