### ISSUE TITLE
Improve error messages for string concat

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#985]
In some languages that either/and/or feature any of this: auto-casting, weak-types, operator overloading, `+` may be used to concat strings.

Similar to the warning that `+` is for integer addition (where `+.` is for float addition) the gleam compiler could emit a warning when `+` is used to attempt to concat strings and reference the correct operator to be used.

**Comment by lpil** [comment]
Good idea! Thank you.

For the int based operators we suggest the appropriate operator, but we don't have a string concat operator. What could we suggest instead? `string.concat` perhaps. We would need to note that this is a library function rather than being in Gleam core.
