### ISSUE TITLE
Not possible to change record type using `..` operator.

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#995]
I'm trying to map the type of a http_request from a String body to a bit_string body. i.e.

```rust
  let Request(body: body, ..) = request
  let bit_request = Request(..request, body: bit_string.from_string(body))
```

I know variables have to keep the same type. i.e you couldn't make this change and reassign the new value to `request`. However I expected to be able to use this approach if assigning to a new variable, as in the example above. Instead I get the following error.

```
error: Type mismatch
   ┌─ /opt/app/src/perimeter/services/http_client.gleam:25:37
   │
25 │   let bit_request = Request(..request, body: bit_string.from_string(body))
   │                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Expected type:

    String

Found type:

    BitString
```

The reason this is a pain is the best work around I have found is to write the following.
```rust
  let Request(a, b, c, d, e, f, g, h) = request
  let bit_request = Request(a, b, bit_string.from_string(c), d, e, f, g, h)
```

**Comment by lpil** [comment]
Yup, something we want for sure. There's an issue for this here https://github.com/gleam-lang/gleam/issues/745
